### ISSUE TITLE
Use icons to convey pairing status, online/offline, and running games

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-qt#10]
Text isn't great from a UI design and localization perspective and it also has issues for accessibility to colorblind people. We should use icons instead.

I propose:
- A play button overlaid in the middle of the running app (like Android)
- A padlock to indicate machines that are not paired
- An exclamation point error icon or some sort of "broken connectivity" icon for offline machines

**Comment by Jorys-Paulin** [comment]
@cgutman There's the material icons for that, specifically for your case:
- The _play_arrow_ one (https://material.io/tools/icons/?search=play&icon=play_arrow&style=baseline)
- The _lock_ one (https://material.io/tools/icons/?search=lock&icon=lock&style=baseline)
- The _warning_ one (https://material.io/tools/icons/?search=warn&icon=warning&style=baseline)
