### ISSUE TITLE
Long-press "select" key on controller automatically interrupted after ~2.5 seconds

### ISSUE THREAD

**Issue by rubin55** [moonlight-stream/moonlight-qt#1004]
**Describe the bug**
Moonlight on Linux to Sunshine on Windows. Select button on controller is automatically interrupted after ~2.5 seconds. Meaning: keep button pressed, observe the button being "unpressed" after about 2.5 seconds, even though you did not let go of the button. I verified that the controller works normally on the Linux driver level (i.e., keeping select pressed does not get interrupted at the Linux driver level, tested with https://gamepad-tester.com/).

**Steps to reproduce**
Connect gamepad to Linux, start moonlight, connect to windows box with sunshine. Start the USB Game Controller app. Click on properties. Observe the "Buttons" section. Observe that any other key, like A or B or X long press do not interrupt. Do the same with "select". Observe that after about 2.5 seconds, select press is de-activated.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? `no`
- If so, which settings have been changed? `n/a`
- Does the problem still occur after reverting settings back to default? `n/a`

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly? `no`
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad? `yes`

**Client PC details (please complete the following information)**
 - OS: Void Linux, Kernel 6.1.27
 - Moonlight Version: v4.3.1
 - GPU: AMD Radeon integrated graphics

**Server PC details (please complete the following information)**
 - OS: Windows 10 22H2
 - Sunshine version: v0.17.0
 - AMD GPU driver: 23.4.3
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Additional context**
I suspect the select button is treated as a possible virtual-mouse-activation key, just like start? even though it does not actually work. When pressing start for about the same amount of time, I switch to virtual mouse mode. Note that disabling  "Enable mouse control with gamepads" does *not* make this issue go away.

**Comment by cgutman** [comment]
This is Sunshine's guide button emulation It was disabled by default in v0.20 for exactly this reason.
