### ISSUE TITLE
Aspect Ration doesn't change when using with sunshine

### ISSUE THREAD

**Issue by bruce119** [moonlight-stream/moonlight-qt#1023]
**Describe the bug**
When I connect my Steam Deck to my PC(hosted by geforce stream) using moonlight the aspect ratio is fine there is no black lines on top and bottom but when my pc is hosted with sunshine the aspect is stuck to 16:9 and doexn't change to 16:10 no matter what I do.

**Steps to reproduce**
just host your pc with sunshine it and connect using moonlight and try to change the aspect ratio to 16:10

**Affected games**
all games

**Other Moonlight clients**
happened with android  client also it didn't fit to screen

**Moonlight settings (please complete the following information)**
changed the resolution to my native screen resolution

**Client PC details (please complete the following information)**
 - OS: Steam OS 
 - Moonlight Version: linux flatpak
 - GPU: AMD 405

**Comment by cgutman** [comment]
This is an issue (or more accurately unimplemented functionality) in Sunshine, not a Moonlight bug. It's known but I don't see a GitHub issue for it, so I suggest opening one there: https://github.com/LizardByte/Sunshine/issues
