### ISSUE TITLE
Windows 7 application text not showing

### ISSUE THREAD

**Issue by SetLogon** [moonlight-stream/moonlight-qt#1025]
**Describe the bug**
There is no application text when running moonlight-qt on Windows 7. 
I restarted the PC, reinstalled moonlight, installed the old version, the result is the same - there is no text.

**Screenshots**
![1](https://github.com/moonlight-stream/moonlight-qt/assets/81163858/f529c78a-c955-46d0-b4fc-17f2ab57df42)

![2](https://github.com/moonlight-stream/moonlight-qt/assets/81163858/cf132f48-c148-419f-b193-078e9b38d6b5)

**Client PC details (please complete the following information)**
Windows 7 Pro
Moonlight-qt  ver 4.3.1
GPU Nvidia Geforce 540M

**Moonlight Logs (please attach)**
[Moonlight-1687295115.log](https://github.com/moonlight-stream/moonlight-qt/files/11807516/Moonlight-1687295115.log)

**Comment by reloxx13** [comment]
windows 7 is EOL, use an up-to-date operating system.

**Comment by SetLogon** [comment]
Tried all versions.
Version 1.1.1 shows text in English.
After version 1.1.1, starting from version 1.2.0, the text is no longer displayed. What was changed in version 1.2.0 that the text disappears?

**Comment by RadarNyan** [comment]
I'm using this on Windows 7 with no issue.
Do you have Windows 7 SP1 and Platform Update for Windows 7 (KB2670838) installed?

**Comment by SetLogon** [comment]
Yes, all updates are installed.
There is a problem with fonts.
For example, when choosing fonts, only Arabic and Chinese spellings are visible. 
There is no English or any other spelling.

![1](https://github.com/moonlight-stream/moonlight-qt/assets/81163858/ce594a68-e617-4bde-a6b4-ff1da6b202db)

![2](https://github.com/moonlight-stream/moonlight-qt/assets/81163858/6dc9cd96-fdc6-481c-992e-b11531670c37)

**Comment by RadarNyan** [comment]
Then I have no clue. I've only observed a similar behavior where some scripts don't render when KB2670838 is not installed.

Platform Update for Windows 7 (KB2670838) brings some DirectX features of Windows 8 to Windows 7, including DirectWrite (which I believe is responsible for rendering texts). Please double-check if it's installed, and maybe try to update your graphics driver and run the [DirectX End-User Runtime Web Installer](https://www.microsoft.com/en-us/download/details.aspx?id=35) to install any missing DirectX components and see if that helps.

**Comment by SetLogon** [comment]
You were right, this update didn't happen.
Installed it and everything worked.
Thank you very much, everything worked out.
