### ISSUE TITLE
"nprotect game guard" blocks keyboard and mouse when enabled

### ISSUE THREAD

**Issue by phoenix91love** [moonlight-stream/moonlight-qt#1031]
Connect moonlight to sunshine, when "nprotect game guard" is run by another software, can't move mouse and use keyboard.
But moonlight connect to geforce running normal. 
I have use moonlight and sunshine latest version (moonlight 4.3.1, sunshine 2.0)

**Comment by cgutman** [comment]
Duplicate of https://github.com/LizardByte/Sunshine/issues/1416
