### ISSUE TITLE
v0.6.0 crashes on macOS when audio output device has non-ASCII characters

### ISSUE THREAD

**Issue by moycat** [moonlight-stream/moonlight-qt#104]
**Describe the bug**
I just upgraded Moonlight from v0.5.1 to v0.6.0. When I start a game, the program crashes and quits. v0.5.1 works fine.
From the logs it seems that it's related to the audio devices.

**Steps to reproduce**
 - Just start a game.

**Screenshots**
![2018-10-13 12 46 25](https://user-images.githubusercontent.com/12007097/46901421-11216000-cee6-11e8-84e3-3e2789498bc2.png)
(Moonlight quit unexpectedly)

**Moonlight settings (please complete the following information)**
<img width="1117" alt="2018-10-13 12 53 15" src="https://user-images.githubusercontent.com/12007097/46901466-f8fe1080-cee6-11e8-96ec-4880a3505d4f.png">
Resetting to default settings doesn't help.

**Client PC details (please complete the following information)**
 - OS: macOS Mojave
 - Model: MacBook Pro (15-inch, 2016)
 - Moonlight Version: v0.6.0

**Logs (please attach)**
[Moonlight-1539406372.log](https://github.com/moonlight-stream/moonlight-qt/files/2475084/Moonlight-1539406372.log)
[apple.log](https://github.com/moonlight-stream/moonlight-qt/files/2475083/apple.log)

**Comment by cgutman** [comment]
can you send a screenshot of your Sound output page in System Preferences too?

**Comment by moycat** [comment]
Sure. The first device is the laptop built-in "Internal Speakers". I always use it and it works fine. The second one is from my USB Type-C to HDMI adapter (for my second monitor).
<img width="780" alt="2018-10-13 1 59 02" src="https://user-images.githubusercontent.com/12007097/46902084-73cc2900-cef1-11e8-8efb-fbd2868ad13a.png">
But even if I take the adapter off and there is only one output device on this page, it still crashes.

**Comment by cgutman** [comment]
Thank you. I've reproduced the issue locally by changing my Mac's language to Simplified Chinese as a test. I think it's a Unicode encoding issue.

**Comment by cgutman** [comment]
Fix released in v0.6.1. Thanks for the report.

**Comment by moycat** [comment]
Thank you! It works great now! 😊
