### ISSUE TITLE
There is windows ARM64 binary release but not Linux (in snap)

### ISSUE THREAD

**Issue by weiwu-zhang** [moonlight-stream/moonlight-qt#1043]
**Is your feature request related to a problem? Please describe.**
````
$ sudo snap install moonlight
error: snap "moonlight" is not available on stable for this architecture
       (arm64) but exists on other architectures (amd64, i386).
````

**Describe the solution you'd like**
Wish to see the arm64 binary for Moonlight (not in docker, which already exist https://github.com/moonlight-stream/moonlight-embedded/issues/807)

**Describe alternatives you've considered**
I wish to emphasize that Linux arm64 binary is more needed than Windows, because Windows users can use WOW64 to run x86 binary but Linux users don't have this advantage and have to seek out 64-bit native executables.

**Additional context**

**Comment by cgutman** [comment]
Please file a ticket on the Snap repo: https://github.com/maxiberta/moonlight-snap

Btw, the Flatpak does have ARM64 support, though I doubt most hardware decoders will work with that unless you're using an discrete GPU on your ARM system. What kind of ARM64 system are you trying to use?

**Comment by weiwu-zhang** [comment]
@cgutman Lenovo X13s Snapdragon. I filed https://github.com/maxiberta/moonlight-snap/issues/20
