### ISSUE TITLE
Gamepad Mapping

### ISSUE THREAD

**Issue by diogoribeiro09** [moonlight-stream/moonlight-qt#105]
Hello everyone,
First i would like to thank you for developing such an amazing app.
My issue with Moonlight on a PC running windows 10 is that i connected a Logitech Driving Force GT, installed the drivers and configured everything as i would normally do. Whenever i start a game, lets say Assetto Corsa, i receive a warning saying that a detected gamepad controller has no mappings and won't be used. Although i can use my keyboard and mouse the steering wheel doesn't work. Am i doing something wrong or is it a bug ? 

Edit: I also have 3 PS3 controllers installed via SCP Toolkit and only one gets detected on Fifa, or any other game. Any help?

Thank you in advance,
DR

**Comment by Jorys-Paulin** [comment]
@diogoribeiro09 Well steering wheels aren't supported by either Moonlight nor GeForce Experience.
If you could to make the steering wheel look like a controller to the client, it would work, but it would also be seen as a controller to the host.
The only way I see to make it work is to implement it on both Moonlight and GFE, but we don't have access to GFE unfortunately.

**Comment by diogoribeiro09** [comment]
@Jorys-Paulin i see. Thank you either way for the quick input. 
What about the Ps3 controllers? Any hint on how to approach my situation ? Fifa only detects one gamepad (which is the one assigned to player 1) and the keyboard.

**Comment by cgutman** [comment]
@diogoribeiro09 please post Moonlight logs of you attempting to stream with your 3 PS3 controllers connected.

On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
