### ISSUE TITLE
Losing quotation mark in executing arguments when launching a game

### ISSUE THREAD

**Issue by zsmfashi** [moonlight-stream/moonlight-qt#1057]
**Describe:**
I was launching Hogwarts Legacy in Steam Big Picture Mode from moonlight, however my game can not find the saves files.
I think this is caused by losing the quotation mark when launching the game.

If I launch the game from Steam Big Picture **without moonlight**, everything goes well. And the executing arguments is
`Phoenix -SaveToUserDir -UserDir="Hogwarts Legacy"`
![Process Explorer - Sysinternals_ www sysinternals com  DESKTOP-9RGFH6D_Administrator  2023_8_17 1_44_04](https://github.com/moonlight-stream/moonlight-qt/assets/42319560/c7b6eeab-e4a1-4c20-afd2-4c9a66cf3d3b)

But if I **first launch Steam Big Picture from moonlight**(By clicking the "Steam" in moonlight), then launch the game, **the quotation mark in "-UserDir" got lost.** So my game can not find my saves.
`Phoenix -SaveToUserDir -UserDir=Hogwarts Legacy`
![Process Explorer - Sysinternals_ www sysinternals com  DESKTOP-9RGFH6D_Administrator  2023_8_17 1_46_03](https://github.com/moonlight-stream/moonlight-qt/assets/42319560/76cdc7d9-684d-46f3-924d-5ed3c91609bb)
And then my game created a directory of "Hogwarts"
![Local 2023_8_17 1_47_51 (2)](https://github.com/moonlight-stream/moonlight-qt/assets/42319560/ce24aaac-57e2-4dd8-86cc-4a1e3690598c)

I tried v4.3.1 and r2116, both of them are not working.

**Comment by cgutman** [comment]
Moonlight doesn't directly send command-line parameters. Those are passed into the app by the host software. I assume you're running Sunshine, so this should go to the [Sunshine bug tracker](https://github.com/LizardByte/Sunshine/issues)
