### ISSUE TITLE
Settings page is cut off on smaller screens

### ISSUE THREAD

**Issue by paul70078** [moonlight-stream/moonlight-qt#106]
**Describe the bug**
On smaller screens window gets cut on right and lower border and  content doesn't get resized

**Steps to reproduce**
Open Moonlight on Tablet PC/Convertible

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/2229858/46904937-855f0200-ceec-11e8-9201-57c6ee3dd2fc.png)

**Moonlight settings (please complete the following information)**
default settings

**Client PC details (please complete the following information)**
 - OS: Windows 10 1803
 - Moonlight Version: v0.6.0

**Comment by Jorys-Paulin** [comment]
@paul70078 Can't you scroll with your fingers?

**Comment by paul70078** [comment]
no. I think windows scaling is causing this issue. It is set to 150%. I changed it to 100% and not it works

**Comment by xatornet** [comment]
I can confirm same issue on version 0.6.1:
![image](https://user-images.githubusercontent.com/43992639/47003596-e7f41000-d12f-11e8-96da-7c1d3bcec077.png)

**Comment by xatornet** [comment]
I get issues with my ASUS Zenbook 3 Deluxe, only in settings screen, everything else works properly.

My screen is a 1080p screen, it defaults to 150% scaling.

**Comment by bigmacxman** [comment]
1080p 150% scaling. Have laptop connected to tv, so the 150% scaling is needed.
