### ISSUE TITLE
fails to build on musl

### ISSUE THREAD

**Issue by jenneron** [moonlight-stream/moonlight-qt#1069]
**Describe the bug**
Errors while building with musl on aarch64 

[moonlight-alpine-aarch64-build.log](https://github.com/moonlight-stream/moonlight-qt/files/12653478/moonlight-alpine-aarch64-build.log)

**Steps to reproduce**
Build it on a distribution using musl instead of glibc

**Client PC details**
 - OS: postmarketOS (Alpine Linux)
 - Device: https://wiki.postmarketos.org/wiki/Acer_Chromebook_Spin_513_(google-lazor)

**Comment by cgutman** [comment]
This should be fixed by 654be492a0faf9be25af1c6160c54aabfb3a1c81

Please try the latest code in master and see if it builds now.

**Comment by jenneron** [comment]
It builds and runs on master

This patch fails when applying on 4.3.1 which blocks me from packaging it to Alpine Linux, but there is another blocker: sdl2 is built with directfb support and moonlight fails to build with that. We need to disable directfb in sdl2 firstly, and only then package moonlight

Thank you for looking into this

**Comment by cgutman** [comment]
I think it should apply to v4.3.1 if you drop the part that touches DrmRenderer.cpp. That `mmap64()` call there didn't exist in v4.3.1.

I plan to release the next version within a couple of weeks, so it may not be worth messing with packaging v4.3.1.

**Comment by jenneron** [comment]
@cgutman, my MR to Alpine got merged a while ago. it is now available in stable Alpine release as well. it may be worth mentioning that it is possible to install moonlight-qt on Alpine and postmarketOS from the repos at https://github.com/moonlight-stream/moonlight-qt?tab=readme-ov-file#downloads
