### ISSUE TITLE
Missing configuration under Qt 5.9

### ISSUE THREAD

**Issue by kshots** [moonlight-stream/moonlight-qt#107]
Getting the following in my logs after compiling head and hitting the config gear button:

00:00:04 - Qt Warning: qrc:/gui/main.qml:34:5: QML StackView: push: qrc:/gui/SettingsView.qml:76 Type AutoResizingComboBox unavailable
qrc:/gui/AutoResizingComboBox.qml:1 module "QtQuick" version 2.11 is not installed

I have QtQuickControls and QtQuickControls2 installed for Qt 5.9

**Comment by cgutman** [comment]
Sorry for breaking that again. I really need to get some automation for testing Qt 5.9.
