### ISSUE TITLE
Moonlight-qt, no audio from Sunshine Windows host

### ISSUE THREAD

**Issue by neta79** [moonlight-stream/moonlight-qt#1075]
**Bug description**
Migrated a Windows host to Sunshine after the loss of GameStream, I get no audio when connecting via moonlight-qt.
The system audio keeps being played on the host side.
To confirm that this is probably an issue specific to moonlight-qt, connecting to the same host via moonlight-android works as intended: 
- the audio is muted on the host
- and played on the client side.

**Steps to reproduce**
Install Sunshine v0.20.0 on Windows 10 host. Connect via LAN using moonlight-qt 4.3.1 Windows client.

**Screenshots**
Output of audio-tool.exe on the host:
![image](https://github.com/moonlight-stream/moonlight-qt/assets/4980155/465ab9a2-5394-4093-95a4-dab5a2102559)

What the host system shows via mmsys.cpl:
![image](https://github.com/moonlight-stream/moonlight-qt/assets/4980155/f242f77c-577c-41c8-8c37-1ed8bd8fb92d)

**Affected games**
Desktop and Steam Big Picture (no other tests)

**Other Moonlight clients**
moonlight-android works perfectly.

**Moonlight settings**
- Audio configuration (stereo/surround) does not affect the issue
- *Mute host PC speakers* does not seem to have any effect

**Client PC details**
 - OS: Microsoft Windows 10 22H2 [Version 10.0.19045.3448]
 - Moonlight Version: 4.3.1
 - GPU: Intel Iris Xe (1GB)

**Server PC details**
 - OS: Microsoft Windows 10 22H2 [Version 10.0.19045.3448]
 - Sunshine v0.20.0
 - Nvidia GPU driver: 537.42
 - GPU: RTX 2060
 - Host audio output: NVidia HDMI
 - Antivirus and firewall software: Windows Defender, Windows Firewall (able to connect to host)

**Moonlight Logs**
[Moonlight-1696077964.log](https://github.com/moonlight-stream/moonlight-qt/files/12774689/Moonlight-1696077964.log)

**Additional notes**
- Explicitly and correctly setting audio_sink and/or virtual_sink on the Sunshine host does not seem to induce changes. I think Sunshine grabs the correct audio sinks by default.
- Does not seem something related to this one https://github.com/loki-47-6F-64/sunshine/issues/242#issuecomment-933981396

Thanks in advance for any feedback on this one.

**Comment by cgutman** [comment]
Please try the latest nightly build: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/48162116/job/1j41ynv4lfgfg6n7/artifacts

If it still fails, please post logs from that. It will have more details about the configuration than v4.3.1 did.

**Comment by neta79** [comment]
Unfortunately no changes with the nightly build.
I am attaching log of a complete session (connect, clean disconnect).
[Moonlight-1696149011.log](https://github.com/moonlight-stream/moonlight-qt/files/12776705/Moonlight-1696149011.log)

**Comment by neta79** [comment]
Update: I can confirm that moonlight-qt macOS work correctly.
I tested 4.3.1 and ancient 3.1.4 for good measure, audio works as intended.

I can't confirm or rule out that the problem is specific to Windows client system:
unfortunately I don't have another Windows system to test the client on, just the one which is malfunctioning.

**Comment by neta79** [comment]
Final update.
The issue is windows-specific and tied to the client system, moonlight-qt is not at fault.
Whatever the problem was, this "Troubleshoot sound problems" managed to fix it.
![image](https://github.com/moonlight-stream/moonlight-qt/assets/4980155/738e0ca4-cf5c-406b-bb18-c13ce5eab509)

Thanks for your time. I'm closing the ticket.

**Comment by Fantik89** [comment]
> Final update. The issue is windows-specific and tied to the client system, moonlight-qt is not at fault. Whatever the problem was, the "Troubleshoot sound problems" wizard managed to fix it. ![image](https://github.com/moonlight-stream/moonlight-qt/assets/4980155/738e0ca4-cf5c-406b-bb18-c13ce5eab509)
> 
> Thanks for your time. I'm closing the ticket.

what did u do exactly

**Comment by Miustone** [comment]
Not working on Windows 11. Log says: [2026-04-09 23:44:30.087]: Warning: Unable to install Steam Streaming Speakers on unknown architecture
