### ISSUE TITLE
HDR too bright/washed out under macOS Sonoma

### ISSUE THREAD

**Issue by sb10** [moonlight-stream/moonlight-qt#1079]
**Describe the bug**
HDR too bright/washed out under Mac OS Sonoma.

**Steps to reproduce**
Start a stream with the Mac OS Sonoma client, with HDR turned on in both Mac OS and Windows.
Using an LG CX OLED TV, in auto mode and even when forced to use REC2020.

**Moonlight settings (please complete the following information)**
Enable HDR

**Client PC details (please complete the following information)**
 - OS: macOS 14.0
 - Moonlight Version: 4.3.1
 - GPU: Apple M2

**Server PC details (please complete the following information)**
 - OS: Windows 11 
 - GeForce Experience version: 3.27.0.112 (but using Sunshine)
 - Nvidia GPU driver: 537.42
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Moonlight Logs (please attach)**
[Moonlight-1696796092.log](https://github.com/moonlight-stream/moonlight-qt/files/12841737/Moonlight-1696796092.log)

**Additional context**
Used to work perfectly immediately prior to upgrading to Sonoma. No other changes made.

**Comment by cgutman** [comment]
GeForce Experience doesn't have proper support for OS HDR, specifically it doesn't properly detect streams that being with HDR enabled on the host. It encodes them as SDR, with predictably poor results.

You can either toggle OS HDR off and back on at the host side, or switch from GFE to Sunshine which doesn't have this bug.

**Comment by sb10** [comment]
> You can either toggle OS HDR off and back on at the host side after you start streaming, or switch from GFE to Sunshine which doesn't have this bug.

Sorry, I only put in my GFE version above because the template asked for it. I'm using Sunshine, and toggling OS HDR doesn't help.

I should say this isn't a normal looking "washed out" effect, but rather some extreme level of corruption. I have a black background, it and displays as bright purple with blocking artefacts around the mouse pointer.

**Comment by cgutman** [comment]
I've tested HDR on macOS Sonoma and it works perfectly for me on the built-in display of my 14-inch M2 MacBook Pro (both with v4.3.1 and the latest nightly). The display brightness increases when entering HDR mode and the colors look correct. Even in windowed mode, it works properly with HDR content in the window blended with the SDR desktop. Does it work if you try on the built-in display?

> I'm using Sunshine, and toggling OS HDR doesn't help.

Are you using the latest Sunshine nightly build or v0.20?

> I should say this isn't a normal looking "washed out" effect, but rather some extreme level of corruption. I have a black background, it and displays as bright purple with blocking artefacts around the mouse pointer.

Can you attach a screenshot of the corruption? It's easier to identify the likely cause if I can see what it looks like.

**Comment by sb10** [comment]
Here's a video of the effect. My camera compensates some of the problem; in real life it looks much worse and I can barely see what I'm doing. At end of the video you can just about see what I mean by black becoming bright purple.

https://youtu.be/9fFojzwQLKk

**Comment by Azonnali** [comment]
I observe the same thing as sb10. I think it's an issue that shows up with external monitors, not the the built-in ones although I could be wrong there.

**Comment by sb10** [comment]
> I've tested HDR on macOS Sonoma and it works perfectly for me on the built-in display of my 14-inch M2 MacBook Pro (both with v4.3.1 and the latest nightly). The display brightness increases when entering HDR mode and the colors look correct. Even in windowed mode, it works properly with HDR content in the window blended with the SDR desktop. Does it work if you try on the built-in display?

I'm using a Mac mini, so no built-in display.

> Are you using the latest Sunshine nightly build or v0.20?

v0.20

> Can you attach a screenshot of the corruption? It's easier to identify the likely cause if I can see what it looks like.

https://youtu.be/9fFojzwQLKk

**Comment by earglass** [comment]
I have identical problem on Macbook pro with M1. Important thing is, it only shows artefacts and super bright colors on external display (like in video above), on built-in display it works fine.
SDR on external display is also ok, just HDR not - I checked performance stats and on external display, there is not label that codec is using HDR. Maybe that helps narrowing down the problem?

**Comment by abhiaagarwal** [comment]
Having a similar issue on M1 Pro 14 inch, running latest Sunshine nightly + Moonlight qt nightly. 
![F5421608-11B4-4457-A130-73C3D387FF55_4_5005_c](https://github.com/moonlight-stream/moonlight-qt/assets/12056337/591dbffd-16b4-4d89-8915-a9e2e9a6022d)
