### ISSUE TITLE
WIndows client doesn't pass multiple gamepads

### ISSUE THREAD

**Issue by ABF81** [moonlight-stream/moonlight-qt#108]
When using the Windows client only the first gamepad gets passed through to the host PC

Client PC normally has 4 x Xbox 360 wireless gamepads connected via a single Xbox 360 wireless adapter however I've also got 2 x Logitech F710 and a Gamesir G3s kicking about. Issue occurs on all combinations of the aforementioned gamepads with only whichever one is device 1 being passed through to the host PC. Confirmed by starting Steam Big Picture mode and then going into Settings->Controller settings and there is only a single Xbox 360 gamepad showing there.
Confirmed the issue is not the host PC, have tested with the Android version of Moonlight with multiple gamepads connected and they all get passed to the host PC correctly. Have also tested using Steam In-Home streaming from the client PC and it also detects all gamepads correctly but I'd prefer to use Moonlight as it's a lighter install, runs better and supports non-steam games. 

Left all Moonlight settings as default except I've upped the bandwidth a bit for better image quality and I've changed the video mode to full screen border less window so it scales correctly. The Multiple Gamepad support box is ticked. 

Client PC is an Intel Nuc NUC6CAYH with 8Gb of RAM and a 128Gb SSD. Running Win10 build 1809 (issue also occured on 1803). Moonlight versions tested are 0.51 and 0.60. 

Thanks for making such an awesome little app and any help would be appreciated :)

**Comment by ABF81** [comment]
I've attached my log file and my Geforce Experience version on the host PC is 3.15.0.164

[Moonlight-1539522094.log](https://github.com/moonlight-stream/moonlight-qt/files/2476393/Moonlight-1539522094.log)

**Comment by cgutman** [comment]
OK, it looks like gamepads are being detected and assigned distinct controller numbers as expected in your log.

Can you try [streaming your whole desktop](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop), and then go to http://html5gamepad.com/ in Chrome and see if it detects multiple controllers? I tried on my test machine and it saw my 2 independent controllers correctly.

**Comment by ABF81** [comment]
Done and screen dumps attached. Definitely only the single gamepad showing up.

![gamepad test](https://user-images.githubusercontent.com/44127447/46948793-91042180-d0c2-11e8-9077-6b5fb5f9d9e2.jpg)
![devices](https://user-images.githubusercontent.com/44127447/46948797-93ff1200-d0c2-11e8-92ed-cc36f653fd13.jpg)
![device manager](https://user-images.githubusercontent.com/44127447/46948803-95c8d580-d0c2-11e8-8139-872c790e61c2.jpg)

**Comment by TENFIRE** [comment]
I'm having the same problem on ubuntu.

**Comment by cgutman** [comment]
@TENFIRE can you get the same data I requested in the above comment?

In addition, please grab Moonlight logs by running `flatpak run com.moonlight_stream.Moonlight` and copying from the terminal window or redirecting it to a file.

**Comment by cgutman** [comment]
I was able to work through this issue with a user on the Discord server and we identified the issue. It should be fixed in the next release.
