### ISSUE TITLE
fails to build against sdl2 with directfb

### ISSUE THREAD

**Issue by jenneron** [moonlight-stream/moonlight-qt#1089]
I'm trying to package it to Alpine. Alpine packages sdl2 with directfb support enabled, and moonlight fails to build with it

Logs: https://gitlab.alpinelinux.org/jenneron/aports/-/jobs/1148371#L7185

**Comment by cgutman** [comment]
Yeah, that's unfortunate. It looks like Limelight.h defines `DR_OK` which conflicts with DirectFB's `DR_OK` in the `DirectResult` enum. That leads to a flood of compilation errors because `DirectResult` wasn't defined. Fixing this will probably require a patch to the moonlight-common-c submodule.

Is there a reason Alpine has DirectFB enabled in SDL? That backend has been deprecated for a long time and was removed from SDL3.

```
In file included from ./backend/nvhttp.h:7,
                 from ./backend/nvcomputer.h:3,
                 from ./backend/computermanager.h:3,
                 from streaming/input/input.h:4,
                 from streaming/input/abstouch.cpp:1:
../moonlight-common-c/moonlight-common-c/src/Limelight.h:294:15: error: expected identifier before numeric constant
  294 | #define DR_OK 0
      |               ^
/usr/include/directfb/direct/result.h:99:6: note: in expansion of macro 'DR_OK'
   99 |      DR_OK,              /* No error occured */
      |      ^~~~~
../moonlight-common-c/moonlight-common-c/src/Limelight.h:294:15: error: expected '}' before numeric constant
  294 | #define DR_OK 0
      |               ^
/usr/include/directfb/direct/result.h:99:6: note: in expansion of macro 'DR_OK'
   99 |      DR_OK,              /* No error occured */
      |      ^~~~~
In file included from /usr/include/directfb/direct/types.h:56,
                 from /usr/include/directfb/direct/Types++.h:38,
                 from /usr/include/directfb/directfb++.h:35,
                 from /usr/include/directfb/directfb.h:32,
                 from /usr/include/SDL2/SDL_syswm.h:80,
                 from streaming/input/abstouch.cpp:5:
/usr/include/directfb/direct/result.h:98:14: note: to match this '{'
   98 | typedef enum {
      |              ^
../moonlight-common-c/moonlight-common-c/src/Limelight.h:294:15: error: expected unqualified-id before numeric constant
  294 | #define DR_OK 0
      |               ^
/usr/include/directfb/direct/result.h:99:6: note: in expansion of macro 'DR_OK'
   99 |      DR_OK,              /* No error occured */
      |      ^~~~~
/usr/include/directfb/direct/result.h:143:3: error: 'DirectResult' does not name a type
  143 | } DirectResult;
```

**Comment by jenneron** [comment]
> Is there a reason Alpine has DirectFB enabled in SDL? 

https://gitlab.alpinelinux.org/alpine/aports/-/blob/282fed14281048e34f96ff775f5e6f50714b9696/community/sdl2/APKBUILD#L54

To be more specific, postmarketOS uses osk-sdl. osk-sdl is on-screen keyboard working on initramfs stage for unlocking encrypted partition. It requires directfb to work with downstream kernels

We are going to drop it in favor of another unlocking utility: https://gitlab.com/postmarketOS/pmaports/-/issues/2319, but it's going to take several months.

At this point if there is an easy fix it would be good to include a it as a patch in the package, so we can package it now and drop the patch later when dropping directfb

> Yeah, that's unfortunate. It looks like Limelight.h defines DR_OK which conflicts with DirectFB's DR_OK in the DirectResult enum.

I see. So if i add a patch renaming `Limelight.h`'s DR_OK it should work. Or simply removing it and replacing with 0 in the code. Probably not good for you in upstream, but good enough to include in the package

**Comment by cgutman** [comment]
> I see. So if i add a patch renaming Limelight.h's DR_OK it should work. Or simply removing it and replacing with 0 in the code. Probably not good for you in upstream, but good enough to include in the package

Yep, either of those should work.

**Comment by jenneron** [comment]
I'm closing this because it is probably not worth fixing upstream

I got it merged btw: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/53611
