### ISSUE TITLE
Banding/Dithering

### ISSUE THREAD

**Issue by decknine** [moonlight-stream/moonlight-qt#110]
I have noticed is some games the sky looks quite horrible due to banding, specifically "Shadow of war" during night time. Is this due to incorrect dithering on the user end? if so, what are the correct Windows display settings to use for Moonlight e.g. RGB full, 8bpc, vs 422 limited, 12bpc. Does Moonlight capture in 12bit, 10bit or 8bit?

**Comment by decknine** [comment]
I wanted to provide a small update to this. When I set the client desktop to 4:2:2, 12bit, limited. I notice significantly less banding.

**Comment by cgutman** [comment]
We're asking the video driver to convert to the appropriate color space/range for the display, so it shouldn't matter whether you use full or limited displays. The video color range should be scaled to match by the video driver.

There are some display drivers that don't scale it properly (Intel), but I believe those issues should be solved. If there are still issues, you can probably fix them by adjusting color settings on the client, like you did. Software and hardware decoding seems to have identical colors on all tested machines now.

As for your question about capture, as far as I know, it's 8-bit 4:2:0. In HDR mode, it's 10-bit 4:2:0.

**Comment by galeksandrp** [comment]
Hi. This looks like oldest issue in tracker about 4:2:0 banding, so:

Is it possible to add request of 4:4:4 in protocol? GameStream being discontinued, so 4:4:4 can be added in Sunshine.

duplicates of this: #497 #317
