### ISSUE TITLE
Moonlight client blank GUI

### ISSUE THREAD

**Issue by Rabanad** [moonlight-stream/moonlight-qt#1102]
**Describe the bug**
Moonlight client shows no GUI, only title bar.

**Steps to reproduce**
Launch Moonlight -> see blank window with only title bar.

**Screenshots**
![Screenshot_2023-10-24_at_5](https://github.com/moonlight-stream/moonlight-qt/assets/60204329/6cbd3488-c95a-4f1f-a6e7-5af1166724e2)

**Affected games**
Moonlight client only

**Other Moonlight clients**
N/A

**Moonlight settings (please complete the following information)**
Unable to reach settings.

**Gamepad-related issues (please complete if problem is gamepad-related)**
N/A

**Client PC details (please complete the following information)**
 - OS: MacOS Sonoma 14.0
 - Moonlight Version: 5.0.0 (also tested 4.3.1)
 - GPU: AMD Radeon R9 M370X 2 GB iGPU:Intel Iris Pro 1536 MB

**Server PC details (please complete the following information)**
Moonlight client bug only.

**Moonlight Logs (please attach)**
[Moonlight-1698261196.log](https://github.com/moonlight-stream/moonlight-qt/files/13169783/Moonlight-1698261196.log)

**Additional context**
Seems Qt related, also tried compiling the program from source but am getting this error: 
![Screenshot 2023-10-25 at 11 52 51 AM](https://github.com/moonlight-stream/moonlight-qt/assets/60204329/41bd9b57-9011-44e5-8d64-f26e4cea41e7)

**Comment by cgutman** [comment]
It looks like you're using macOS Sonoma on an unsupported Mac, so the Metal GPU driver is probably missing/broken. This is likely the cause of the render pipeline errors in the log and failure to render the UI.

If this problem can be produced on a supported version of macOS, please reopen.

**Comment by beren12** [comment]
I'm having this issue on Sonoma, I just used OCLP to install it on my 2015 (normally stops at 13.x) I was able to fix it by setting QT_QUICK_BACKEND="software" and opening it in the terminal.

No other metal apps have issues, so it likely is a bug in QT not detecting something correctly.
