### ISSUE TITLE
Unsupported resolutions cause GFE to set display to 720p

### ISSUE THREAD

**Issue by decknine** [moonlight-stream/moonlight-qt#111]
When I stream any game in 1440p, Moonlight changes my host PC to 720p before launching the game.

My Host PC is 1080p native, so I have to set a custom resolution through Nvidia Control Panel of 1440p, to be captured and sent to my 4k TV and I assume this is where the issue lies. For games that use dynamic or scaled resolutions this actually stops you from being able to set your resolution correctly once in game, due to the game not knowing your native resolution and guessing wrong. The only fix is to manually stream the desktop, set the resolution you want to game in and then manually launch the game.

**Comment by decknine** [comment]
ah I see, I thought it was something along those lines. The workaround then, for those games with scaled resolution options instead of native resolution options would be to stream in 4k and then set the in-game scaled resolution to 0.6 or 0.7 to achieve a 1440p effective resolution. It is odd that GFE doesn't officially support 1440p given its popularity, so I for one am glad you decided to add it!

**Comment by cgutman** [comment]
I'm closing this as can't fix (nvidia bug).
