### ISSUE TITLE
Intel N100 (alder lake) hardware support

### ISSUE THREAD

**Issue by lodesmets** [moonlight-stream/moonlight-qt#1121]
I got the message that no supported GPU could be found, and moonlight would fall back to software decoding.

But I'm using an Intel N100 mini pc. It has integrated graphics.

The OS I'm using is libreelec. I tried different versions (both nightly and regular). But now I'm using the nightly version with Linux kernel v 6.6.0.

Moonlight QT version I'm using it V5.0.1

Is here the correct place to report it? Or should I report it with libreelec?

**Comment by Originalimoc** [comment]
It is working on N100, check your OS driver libva version.
Or build from source it will link correct library(given you installed ffmpeg and GPU driver).
Or use flatpak.

**Comment by lodesmets** [comment]
apparently libreelec has 2 differen OS  versions. With different graphics drivers. I had to use the Legacy-build version
