### ISSUE TITLE
Port Android moonlight gyro emulation to Qt. For handheld like Steam Deck/Rog Ally/Legion Go to act like a DS4 controller.

### ISSUE THREAD

**Issue by Originalimoc** [moonlight-stream/moonlight-qt#1123]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Screen touch as DS4 Touchpad(This one is slightly tricky, Linux/Windows touch normally is a cursor move(?), so that touchscreen as trackpad feature needs a fix to be functional too(Windows is working, Steam Deck in gamemode is broken)). Grey out with "[No gyro detected]" on other no gyro platform.

**Describe alternatives you've considered**
Windows has DS4 emulator like this one: https://github.com/Valkirie/HandheldCompanion, but not aware of a Linux alternative.

**Additional context**
Gyro data reference: https://github.com/kmicki/SteamDeckGyroDSU

**Comment by Originalimoc** [comment]
External DS4 emulation like HC mentioned above really is clunky sometimes because some of these device itself's software is already emulating a Xbox controller, and HC might not work, so moonlight reading sensor directly then add it on top of device emulated Xbox is indeed the way to go.

**Comment by Originalimoc** [comment]
Currently can be done through another program then moonlight will "passthrough"(actually also emulating) it.

**Comment by jdancouga** [comment]
@Originalimoc 
Can you please elaborate how you achieve gyro passthru?

**Comment by Originalimoc** [comment]
> @Originalimoc Can you please elaborate how you achieve gyro passthru?

On Legion Go I made this https://github.com/Originalimoc/compatctl/releases
On Steam Deck I just use Steam input which is versatile enough for my playing

What do you want to achieve?
