### ISSUE TITLE
Client UI Title Banner render issue

### ISSUE THREAD

**Issue by leaskovski** [moonlight-stream/moonlight-qt#1130]
So I have a raspbian lite OS install of bookworm running on my Pi 3b+.  Its a lite OS, as a recommendation of moonlightis to run it from the commandline as it sorts its own x11 out.  Upon running moonlight-qt, after installing per the guide here (https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4), moonlight launches, but the rendering of the main UI is somewhat corrupt, which the title banner bar, overlapping other parts of the UI.

See attached picth as an example of the render issue
![IMG_20231116_220736086_-_Copy](https://github.com/moonlight-stream/moonlight-qt/assets/13252143/2c624dcf-1e43-4277-9da4-f02a078fc45d)

**Steps to reproduce**
There are no specific steps to reproduce.  Just install on bookworm raspbian os lite as per the install guide (https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4) and launch.

**Screenshots**
See above

**Affected games**
Not game impacting, only main UI impacting

**Other Moonlight clients**
Only seen with moonlight-qt raspbian distro install.

**Moonlight settings (please complete the following information)**
Everything set as default out of the box install following the online docs on how to install

**Gamepad-related issues (please complete if problem is gamepad-related)**
Main UI issue

**Client PC details (please complete the following information)**
Raspbian bookworm lite os
Moonlightlight-qt client from following https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4

**Server PC details (please complete the following information)**
Windows 10 22H2
GeForce Experience 3.27.0.120
RTX 3060 Ti
Driver 546.17

**Moonlight Logs (please attach)**
Sorry, not able to easily get this...

**Additional context**
Nope

**Comment by cgutman** [comment]
Yeah, this is a known rendering bug with the Qt EGLFS renderer. It seems to be specific to 4K resolution displays too, oddly enough.

**Comment by leaskovski** [comment]
@cgutman thanks for your response.  I have had a look around at other ender issue, and have noticed that some people are set an ENV variable to force the moonlight client to run at a lower resolution.  Is that something that should work around the issue by removing 4k from the picture?

**Comment by leaskovski** [comment]
I did work around the issue in the end by adding "QT_QPA_PLATFORM=linuxfb:size=1920x1080" as an environment parameter.  I can't remember where I found this, but it did seem to work, though it is annoying with terminal cursor deciding to show through to the moonlight ui.
