### ISSUE TITLE
Moonlight stream has no video on any client devices when launching any game after system wakes up from sleep

### ISSUE THREAD

**Issue by suvi2k** [moonlight-stream/moonlight-qt#1135]
**Describe the bug**
After launching any game from the client machine via moonlight after the Host PC was "woken up from sleep mode", there is no video upon game launch of any emulator I am using.  The audio can be heard and inputs work fine as I set the client machine (iPad) right next to the host machine and could see everything working on the host machine fine.  In my testing, I used Big Box software to host games and the program launches fine (shows all start up videos, menu etc..) However, when launching any game, this problem occurs.  I have ruled out a particular emulator problem as I have tried launching different emulators through BigBox, Launchbox and stand alone software and issue occurs for all of them only upon game launch.

When loading Windows PC games, there is no issue observed.  Stand alone or through Big Box, there is no issues and everything works as expected. (this rules out LaunchBox/BB issues from my perspective)
When loading any videos from the internet, there is no issues.  
Exploring my desktop or using any other apps, there is no issues so far.

I think the issue has to do with Moonlight or Nvidia gamestream/settings somewhere because it seems odd that only all emulators aren't displaying video upon game launch and only when the system wakes up from sleep.

Upon a system restart, everything works correctly.  This is annoying to do each and every time I launch moonlight however.

**Steps to reproduce**
Windows 11 system must wake up from sleep mode to cause this issue.

**Screenshots**
Monitor on left is host 
iPad on right is the client
 
Everything synched during menus
![IMG_3684](https://github.com/moonlight-stream/moonlight-qt/assets/120870582/f53721be-a8df-4f40-8ca1-cddcdf427162)

Everything synched during other screens also:
![IMG_3685](https://github.com/moonlight-stream/moonlight-qt/assets/120870582/0332875c-de45-4a4a-b1b9-f07b305817d8)

Only upon launching game, does the video stream stop:  
![IMG_3686](https://github.com/moonlight-stream/moonlight-qt/assets/120870582/852dea97-0530-4022-ae50-4b3419bf5bd2)
![IMG_3688](https://github.com/moonlight-stream/moonlight-qt/assets/120870582/32a8914f-501d-47de-b59f-f3191ae1dba4)

**Affected games**
All emulators.  Tested so far and failing (PSCX2, Yuzu, Retroarch, RPCS3)

**Other Moonlight clients**
Issue occurs on both Ios and android devices.  Tested on iPad pro, iPhone and amazon firestick, amazon fireTV cube.
Again, all these devices work fine upon host system restart without changing any settings.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?  No and I have tried both default along with optimized streaming options.
- If so, which settings have been changed? N/A
- Does the problem still occur after reverting settings back to default? Yes

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
This is not related to gamepads

**Client PC details (please complete the following information)**
 - OS: IOS (iPad Pro, iPhone 14 Pro)
 - Moonlight Version: iPad v8.5, iPhone v8.5
 - GPU: Unknown
 - 
**Server PC details (please complete the following information)**
 - OS: Windows 11 23H2
 - GeForce Experience version: 3.27.0.120
 - Nvidia GPU driver:546.29
 - Antivirus and firewall software: Kaspersky

**Moonlight Logs (please attach)**
Unsure how to find logs from iPhone or iPad client devices.  
Not sure if it will reveal anything since only the video isn't working for emulators when launching games while everything is working fine on the host PC.  Kindly share more information to help here if possible. 

**Additional context**
I haven't tried on my apple TV but I suspect the same issue will persist.  I have tried both using local network hard wired and over internet wireless and have the same issue.

Nvidia drivers and Windows are updated.
I tried testing with anti virus disabled and that didn't work either.  

Power settings on my windows machine included a variety of tests to disable/enable PCI express, USB settings.
Hibernation is off and PC fast startup is on but since I am never shutting down or using hibernation, I do not think it has any impact to these failures.

My PC display settings do not have HDR enabled but I do have multiple displays.  I do not think this is the issue because only the emulated game videos are failing while displaying on the correct host monitor.

**Comment by cgutman** [comment]
This is a host-side issue, since Moonlight has no idea if your computer has slept or not. Since it's an issue with GeForce Experience, there is probably no fix. You can try Sunshine and see if it has the same issue.
