### ISSUE TITLE
appveyor unstable windows builds can't be downloaded anymore

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#1142]
`{"message":"Artifacts download limit (1024 MB/day) exceeded."}`

is the message displayed.
I tried downloading a ubuntu build and it works

**Comment by cgutman** [comment]
This happens from time to time due to load from users grabbing nightly builds when new features or bugfixes land. I don't think there's really any action to take here other than monitor and ask AppVeyor for an increase if it continues.
