### ISSUE TITLE
Unable to connect to the specified PC

### ISSUE THREAD

**Issue by Junn-Sorran** [moonlight-stream/moonlight-qt#115]
Hi everyone,

**Describe the bug**
I have an issue with the new moonlight-qt, I can't connect to my host with it but I can still perfectly use the old chrome version I had.

The issue happen when I try to add the host for the first time. I enter the IP (10.8.0.1, the vpn server), then it does nothing for a few seconds and display this message :
"Unable to connect to the specified PC. Click the Help button for possible solutions."

I do think there is a problem with my client, I tried it with another one and it worked perfectly and the fact that moonlight-chrome also work proves that the network part is fine (unless the new moonlight needs more stuff to work) and I'm out of ideas to try.

**Screenshots**
![image](https://user-images.githubusercontent.com/27011787/47441513-93e0cf80-d7b0-11e8-8efe-b549af4c7ee4.png)

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
No, I just installed moonlight

- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Client PC details (please complete the following information)**
Here's my DxDiag
[DxDiag.txt](https://github.com/moonlight-stream/moonlight-qt/files/2511117/DxDiag.txt)
 - OS: Windows 7 Entreprise 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr.180908-0600)
 - Moonlight Version: Moonlight PC v0.6.1

**Logs (please attach)**
- There are some warnigs in this one but I don't know what it means.
[Moonlight-1540392788.log](https://github.com/moonlight-stream/moonlight-qt/files/2511130/Moonlight-1540392788.log)

**Additional context**
The host is on windows 10 and gtx 780 (all up to date) and the client is on windows 7 (also up to date).
I connect to the host thought an OpenVPN hosted by the host computer (who works fine for everything else, including moonlight chrome).
The firewall is also configured according to the setup guide, the following ports are open in and out : 
TCP: 47984, 47989, 48010
UDP: 5353, 47998, 47999, 48000, 48002, 48010

I also added moonlight to the "authorized programs" in the firewall just to be sure, allowing it to connect to every network (domain, private, public).

**Comment by Junn-Sorran** [comment]
up

**Comment by cgutman** [comment]
It looks like Qt might be using the default system proxy. Can you try disabling your work proxy and connecting?

**Comment by Junn-Sorran** [comment]
Well first problem is that I can't connect the vpn If I'm not connected to the proxy, somehow connecting it first and then disabling the proxy can do the job and the vpn stay up, I can access the host though rdp. But the shield sharing seem to be deactivated and I can't reactivate it though rdp.

I'll try to fist it when I get back up but I wont be able to test it further this week so I'll update the issue on monday.

**Comment by Junn-Sorran** [comment]
Well first problem is that I can't connect the vpn If I'm not connected to the proxy, somehow connecting it first and then disabling the proxy can do the job and the vpn stay up, I can access the host though rdp. But the shield sharing seem to be deactivated and I can't reactivate it though rdp.

I'll try to fist it when I get back up but I wont be able to test it further this week so I'll update the issue on monday.

**Comment by cgutman** [comment]
I disabled usage of proxy servers. Can you try the portable build here and see if it fixes your issue? https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/20042932/job/shd6mj7orb0w67g5/artifacts

If you already have an installation of Moonlight, you can delete portable.dat in the portable app directory and it will pick up your local settings and paired PCs.

**Comment by Junn-Sorran** [comment]
This new portable build is working perfectly (with the system proxy on), thank you very mutch!
Is this based on the latest version? I saw it was 6 month old.
Do you think you could add some proxy options directly in moonlight in the future (use system/don't use/configure manualy)

**Comment by cgutman** [comment]
The build is from two days ago, not 6 months. It was saying the binaries from that specific unofficial build will be hosted by AppVeyor for 6 months.

I'll think about proxy options, but I'm concerned with performance impact caused by relaying though a proxy server.

**Comment by Junn-Sorran** [comment]
Does redirecting himself to a proxy could cause a performance impact? Because now moonlight is already relaying though a proxy if the system has one.
