### ISSUE TITLE
Black screen on Intel UHD

### ISSUE THREAD

**Issue by royka1** [moonlight-stream/moonlight-qt#1150]
**READ ME FIRST!**
If you're here because something basic is not working (like gamepad input, video, or similar), it's probably something specific to your setup, so make sure you've gone through the Troubleshooting Guide first: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

If you still have trouble with basic functionality after following the guide, join our Discord server where there are many other volunteers who can help (or direct you back here if it looks like a Moonlight bug after all). https://moonlight-stream.org/discord

**Describe the bug**
When I start the stream I'm getting a black screen, when I revert back to a month ago then it works again.
Vulk
**Steps to reproduce**
Compile from master and start a stream with an Intel UHD

**Screenshots**
Black screen

**Affected games**
Any

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?
 On Debian Trixie, on Wayland as well on KMSDRM
**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? On default it gives a black screen, on software it shows output.
- If so, which settings have been changed? Decoder
- Does the problem still occur after reverting settings back to default? Yes

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
  - Instructions for streaming the desktop can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - Moonlight Version: v5.01 (Master 2024-01-05)
 - GPU: NVIDIA Geforce RTX 4070 TI
**Server PC details (please complete the following information)**
 - OS: Windows 10
 - GeForce Experience version:  3.27.0.120
 - Nvidia GPU driver: 546.33
 - Antivirus and firewall software: [e.g. Windows Defender and Windows Firewall]

**Moonlight Logs (please attach)**
[moonlight-wayland.log](https://github.com/moonlight-stream/moonlight-qt/files/13843728/moonlight-wayland.log)
[moonlight-kmsdrm.log](https://github.com/moonlight-stream/moonlight-qt/files/13843770/moonlight-kmsdrm.log)

**Additional context**

While starting the stream it always show that the hardware doesn't support HDR even while HDR is turned off (greyed out) and the hardware actually does support it.
In the log it says that Vulkan can't find a display while Vulkan is installed:
$ vulkaninfo --summary

VULKANINFO

Vulkan Instance Version: 1.3.268

Instance Extensions: count = 22
-------------------------------
VK_EXT_acquire_drm_display                       : extension revision 1
VK_EXT_acquire_xlib_display                        : extension revision 1
VK_EXT_debug_report                                   : extension revision 10
VK_EXT_debug_utils                                      : extension revision 2
VK_EXT_direct_mode_display                       : extension revision 1
VK_EXT_display_surface_counter                 : extension revision 1
VK_EXT_swapchain_colorspace                    : extension revision 4
VK_KHR_device_group_creation                   : extension revision 1
VK_KHR_display                                            : extension revision 23
VK_KHR_external_fence_capabilities            : extension revision 1
VK_KHR_external_memory_capabilities        : extension revision 1
VK_KHR_external_semaphore_capabilities   : extension revision 1
VK_KHR_get_display_properties2                 : extension revision 1
VK_KHR_get_physical_device_properties2  : extension revision 2
VK_KHR_get_surface_capabilities2              : extension revision 1
VK_KHR_portability_enumeration                 : extension revision 1
VK_KHR_surface                                          : extension revision 25
VK_KHR_surface_protected_capabilities     : extension revision 1
VK_KHR_wayland_surface                           : extension revision 6
VK_KHR_xcb_surface                                  : extension revision 6
VK_KHR_xlib_surface                                  : extension revision 6
VK_LUNARG_direct_driver_loading             : extension revision 1

Instance Layers: count = 7
--------------------------
VK_LAYER_FROG_gamescope_wsi_x86_64   Gamescope WSI (XWayland Bypass) Layer (x86_64) 1.3.221  version 1
VK_LAYER_INTEL_nullhw                                INTEL NULL HW                                                            1.1.73   version 1
VK_LAYER_KHRONOS_validation                   Khronos Validation Layer                                               1.3.250  version 1
VK_LAYER_MESA_device_select                    Linux device selection layer                                           1.3.211  version 1
VK_LAYER_MESA_overlay                              Mesa Overlay layer                                                        1.3.211  version 1
VK_LAYER_VKBASALT_post_processing       a post processing layer                                                  1.3.223  version 1
VK_LAYER_hdr_wsi                                         WSI HDR Layer (x86_64)                                               1.3.221  version 1

Devices:
========
GPU0:
	apiVersion                 = 1.3.274
	driverVersion             = 23.99.99
	vendorID                    = 0x8086
	deviceID                    = 0x46d1
	deviceType                = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName              = Intel(R) Graphics (ADL-N)
	driverID                     = DRIVER_ID_INTEL_OPEN_SOURCE_MESA
	driverName               = Intel open-source Mesa driver
	driverInfo                   = Mesa 24.0.0-devel (git-2464cd81d3)
	conformanceVersion = 1.3.6.0
	deviceUUID               = 8680d146-0000-0000-0002-000000000000
	driverUUID                = c9d23fa0-855d-d1c4-b4e2-530d867a486a

**Comment by cgutman** [comment]
HDR is disabled because:
```
00:00:07 - SDL Warn (0): Vulkan device 'Intel(R) Graphics (ADL-N)' does not support HDR10 (ST.2084 PQ)
```
This is likely because your compositor doesn't support it, so the WSI layers don't expose it.

Does the black screen happen even if you build with `qmake config+=disable-libplacebo ...` (or just remove libplacebo-dev from your system)?

**Comment by royka1** [comment]
> HDR is disabled because:
> 
> ```
> 00:00:07 - SDL Warn (0): Vulkan device 'Intel(R) Graphics (ADL-N)' does not support HDR10 (ST.2084 PQ)
> ```
> 
> This is likely because your compositor doesn't support it, so the WSI layers don't expose it.
> 
> Does the black screen happen even if you build with `qmake config+=disable-libplacebo ...` (or just remove libplacebo-dev from your system)?

Build without libplacebo and it works, but somehow only when I've selected HDR (which is now selectable again). It seems like the black screen occurs when nv12 is selected instead of p010le.
[moonlight-no-hdr.log](https://github.com/moonlight-stream/moonlight-qt/files/13853983/moonlight-no-hdr.log)
[moonlight-with-hdr.log](https://github.com/moonlight-stream/moonlight-qt/files/13853985/moonlight-with-hdr.log)

**Comment by royka1** [comment]
Previous one was build on QT6, rebuild on QT5 and NV12 does work again. Still need to disable/remove libplacebo to get the option HDR selectable.
So on QT5 and without libplacebo everything works.
