### ISSUE TITLE
Widgets on Desktop in macOS Sonoma Disappear after Ending the Stream

### ISSUE THREAD

**Issue by Juhao73692** [moonlight-stream/moonlight-qt#1151]
**Describe the bug**
When I end the stream, widgets on desktop (a new feature in macOS Sonoma) disappear. Restarting the finder couldn't fix it. the widgets only come back after re-login.

**Steps to reproduce**
Place a widget on the desktop and start streaming. After the stream ends, the widgets will disappear.

**Screenshots**

https://github.com/moonlight-stream/moonlight-qt/assets/61570580/08ad9c6b-c15a-48fa-8cad-c92cdeadd7ac

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
Here is the screenshot
![截屏2024-01-08 11 41 05](https://github.com/moonlight-stream/moonlight-qt/assets/61570580/acd6f880-6146-48fb-b255-c8f72bd06888)

- Does the problem still occur after reverting settings back to default?
No

**Client PC details (please complete the following information)**
 - OS: macOS 
 - Moonlight Version: 5.0.1
 - GPU: apple M1 Max 

**Server PC details (please complete the following information)**
I don't think this information is needed.

**Moonlight Logs (please attach)**
[Moonlight-1704685419.log](https://github.com/moonlight-stream/moonlight-qt/files/13856080/Moonlight-1704685419.log)

**Comment by cgutman** [comment]
I think this is related to your selection of "Fullscreen" display mode rather than the recommended "Borderless windowed" mode. The former seems to trigger all sorts of strange issues in macOS, like hangs and driver bugs, which is why the latter is recommended.

**Comment by Juhao73692** [comment]
Thank you very much. It does solve the problem.
