### ISSUE TITLE
[L4T] Fedora 39 - HW decoder reported missing

### ISSUE THREAD

**Issue by Azkali** [moonlight-stream/moonlight-qt#1164]
**Describe the bug**
On L4T Fedora 39, moonlight-qt fails to recognize the presence of a hardware decoder.

**Sources:**
[Moonlight package source](https://build.opensuse.org/package/show/home:Azkali:Apps/moonlight-qt)
[FFmpeg-static package source](https://build.opensuse.org/package/show/home:Azkali:Tegra/ffmpeg-rpmfusion-static)
[FFmpeg sources -  branch n6.0.1-nvv4l2 (the default one)](https://gitlab.azka.li/l4t-community/switch-l4t-multimedia/FFmpeg)

You can check the *.spec file in the package sources to see how FFmpeg and moonlight are compiled.

**Comment by cgutman** [comment]
Nothing looks out of the ordinary in either Moonlight or FFmpeg build logs.

Can you post the log output from Moonlight?

**Comment by Azkali** [comment]
[moonlight.txt](https://github.com/moonlight-stream/moonlight-qt/files/14051700/moonlight.txt)

**Comment by cgutman** [comment]
Hmm, are you certain that this ended up linking to the FFmpeg build that you posted there? The lack of _any_ HEVC decoder and the missing libopenh264.so warning makes me suspicious...

**Comment by cgutman** [comment]
Closing because this is a problem with the build process, not Moonlight.

**Comment by Azkali** [comment]
The [shared FFmpeg libs is also l4t one](https://build.opensuse.org/package/show/home:Azkali:Tegra/ffmpeg-rpmfusion), so the error should not happen ? 
Trying to build against ffmpeg static build doesn't work either and reports that the static lib is missing despite reproducing your packaging script

**Comment by Azkali** [comment]
@cgutman I fixed the linking issues. It now correctly link against the static version of ffmpeg I wanted to use but SDL fails to handle the decoders. I am using fedora 39's SDL2-static and my own SDL2_ttf-static.
See the attached [pastebin log](https://pastebin.com/jxsHvWwu)
