### ISSUE TITLE
I cant enter 0 on my virtual keyboard

### ISSUE THREAD

**Issue by Mrsalai** [moonlight-stream/moonlight-qt#1166]
Hey guys, so basically at windows login I have to enter my pin, I pull up the virtual keyboard with 3 fingers in moonlight but it doesnt detect 0 for some reason, I press it but it doesnt get typed, all other numbers and letters work.
I tried switching keyboard layout on my phone but nothing.
Using the latest version of sunshine

**Comment by cgutman** [comment]
I'm assuming this was meant to go to https://github.com/moonlight-stream/moonlight-ios or https://github.com/moonlight-stream/moonlight-android rather than the PC client (which doesn't have a 3 finger tap for virtual keyboard gesture)
