### ISSUE TITLE
Waveshare VisionFive2 OpenSSL3 not supported in vendor QT package

### ISSUE THREAD

**Issue by fipso** [moonlight-stream/moonlight-qt#1169]
Hello,
I am trying to get this tool running on my vision five 2 risc board.
I followed the device specific instructions from the wiki.
When i try to connect to my windows pc's sunshine server i am promted with a 401 ssl error.

This seems to be related to the following issue:
https://github.com/starfive-tech/Debian/issues/3

Did anyone manage to get this running on the visionfive2 yet? It says so in the wiki atleast, but I have no idea how is this going to work without openssl support from the vendor patched qt package

**Comment by cgutman** [comment]
Yeah, the trick is to just ignore StarFive's Qt packages and use the ones that are included in Debian.

**Comment by fipso** [comment]
Thanks. I uninstalled StarFive's Qt package and now the OpenSSL issue is gone.
I will create a PR to update the wiki accordingly. Its a little confusing, because the wiki sends you to StarFive's debian setup guide where they give u a script that installs all those packages.

**Comment by fipso** [comment]
Hello, it seems like Github does not allow PR's to the Wikipage.
Here is a fork of the risc docs page where I added some recommendations that i had to follow to get moonlight running on my starfive vision five2

https://github.com/fipso/moonlight-docs/wiki/Installing-Moonlight-Qt-on-RISC%E2%80%90V-Single-Board-Computers

**Comment by cgutman** [comment]
Thanks, I added a note to the docs based on your example. I didn't go as far as suggesting them to change their APT sources list for updated packages though.
