### ISSUE TITLE
Uninstalling Moonlight Internet Streaming Helper does not turn of UPnP rules used by PC

### ISSUE THREAD

**Issue by yahaverlich** [moonlight-stream/moonlight-qt#117]
**Describe the bug**
After installing the Moonlight Internet Streaming Helper, my router settings showed several new UPnP rules for the PC that had moonlight installed. Since I could not get it to work properly, I manually forwarded ports and uninstalled the Helper so that UPnP would stop being used. However, after uninstalling the Helper and restarting my PC, my router settings show that my PC is still using those same UPnP rules that are directly conflicting with the ports I manually forwarded. Therefore I cannot stream over the internet. However, if I turn off UPnP completely, I am able to stream over the internet.

**Steps to reproduce**
Install Moonlight Internet Streaming Helper. Check the new UPnP rules that were made. Uninstall Moonlight Internet Streaming Helper and restart PC. Check if UPnP rules still exist, after the PC has been on for a little bit of time. Also try connecting through a client Moonlight app (just to make sure your PC is still triggering those UPnP rules, though this is not absolutely necessary).

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1803]
 - Moonlight Version: [e.g. v0.2.0]
Windows 10 1803, GeForce Experience 3.15, Moonlight Internet Streaming Helper 1.3

**Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux, logs print to the terminal when running via `flatpak run com.moonlight_stream.Moonlight`

**Additional context**

**Comment by cgutman** [comment]
This should already be fixed in v1.2 (but you need to be running 1.2 or later when you uninstall).

If not, please move to https://github.com/moonlight-stream/Internet-Streaming-Helper and grab the logs from C:\ProgramData\MISS and attach them to the ticket.
