### ISSUE TITLE
MacOS Sonoma (M1Pro) game mode causes local audio burst

### ISSUE THREAD

**Issue by iseku** [moonlight-stream/moonlight-qt#1170]
**Describe the bug**
On my M1Pro MBP (macOS Sonoma 14.3), when Moonlight is started and linked to the server, macos automatically starts game mode, causing local audio to burst, but there is no problem streaming audio remotely, and when manually turning off game mode everything becomes normal .

**Client PC details (please complete the following information)**
 - OS: [macOS Sonoma 14.3]
 - Moonlight Version: [v5.0.1]
 - GPU: [Apple M1Pro]

**Server PC details (please complete the following information)**
 - OS: [Windows 11 23H2]
 - GeForce Experience version: [e.g. 3.16.0.140]
 - Nvidia GPU driver: [e.g. 417.35]
 - Antivirus and firewall software: [e.g. Windows Defender and Windows Firewall]

**Comment by ademlabs** [comment]
I was experiencing severe crackling of audio when Moonlight was in borderless window or fullscreen mode and having focus. Didn't happen in window mode or when Moonlight didn't have focus.  
Not sure if Game Mode was being triggered before but when I disable it for Moonlight everything works perfectly.

**Comment by k-ryan-xydus** [comment]
@ademlabs How do you turn game mode off even when in fullscreen I've tried turning it off before starting a session but it just turns back on again
