### ISSUE TITLE
what does the ”NvApp" mean?, is it the android's  app program?

### ISSUE THREAD

**Issue by daxue2017** [moonlight-stream/moonlight-qt#1176]
in the file moonlight-qt\app\backend\nvapp.h, what does the class  NvApp mean, is it means the 
android app?

**Comment by cgutman** [comment]
NvApp encapsulates instances of streamable apps from the host PC that are returned in the `/applist` request. It's not related to the Android app, which is a separate codebase located here: https://github.com/moonlight-stream/moonlight-android
