### ISSUE TITLE
lag spike?

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-qt#118]
hay im  getting a lag spike once every 5-6 mins of streaming it does not matter what wifi im on (5hz or 2.4) an i tried changing the setting around but it still happens. I don't get his problem with any of my Android devices. Any ideas?

**Comment by AgentCrowe** [comment]
Have you tried to test it on Ethernet? Also do you know if a service on your computer is doing any kind of checks? How long does the lag spike take? It could be an AV or something either pulling updates or doing a quick scan. (Be sure to check the host and client)

**Comment by jliang14** [comment]
i just upgraded to 0.7 and i'm now having severe lagspikes. even rolling back to 0.64 doesn't fix the issue. not sure what's going on.

**Comment by cgutman** [comment]
If rolling back doesn't fix it (and there weren't changes to streaming in v0.7.0 anyway), then it's not a Moonlight regression. It's likely that your network environment or the behavior of PCs on your network is what changed.

Could be WiFi interference from a neighboring network or WiFi Direct device, PCs on your network periodically downloading stuff (possibly in the background), appliances like microwaves or Bluetooth devices causing periodic 2.4 GHz interference, or any number of other causes.

Unless this is reproduceable on a fully wired connection to both PCs, it can be reproduced with a network conditioning tool like Clumsy over a fully reliable link, or it is not visible in another tool like iperf3 when emulating GameStream, I don't think it's appropriate for this issue tracker. This is a tech support issue that should be dealt with on Discord.
