### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by efifogel** [moonlight-stream/moonlight-qt#1186]
The code fails to compile under Ubuntu 22.04 with default installations:

/home/efif/trees/xanadu/moonlight-qt/app/streaming/input/abstouch.cpp:122:41: error: ‘SDL_GetTouchName’ was not declared in this scope; did you mean ‘SDL_GetTouchFinger’?
  122 |                 const char* touchName = SDL_GetTouchName(i);
      |                                         ^~~~~~~~~~~~~~~~
      |                                         SDL_GetTouchFinger

**Client PC details (please complete the following information)**
 - OS: Ubuntu 22.04.3 LTS
 - Moonlight Version: master branch from sources
 - Qt version: 5.14.0
 
At https://wiki.libsdl.org/SDL2/SDL_GetTouchName is says and I quote "This function is available since SDL 2.0.22".
The version of sdl2-dev package installed with the standard command (sudo apt install libsdl2-dev) is 2.0.20.
I've installed 2.30.0, but this resulted in many errors.
So, I realize that this is not necessarily a bug, and I apologize...
1. Is there a stable branch?
2. What should I do to build from the master branch? (e.g., a specific version of libsdl2-dev)

**Comment by efifogel** [comment]
The master branch still fails to compile:
```
In file included from /home/efif/trees/xanadu/moonlight-qt/app/streaming/video/ffmpeg-renderers/plvk_c.c:12:
/usr/include/libplacebo/utils/libav.h:26:10: fatal error: libavformat/avformat.h: No such file or directory
   26 | #include <libavformat/avformat.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

If I install libavformat-dev (sudo apt install libavformat-dev), I get tons of errors. Here is the first:

```
/home/efif/trees/xanadu/moonlight-qt/app/streaming/video/ffmpeg-renderers/plvk_c.c:19:10: error: conflicting types for ‘av_stream_get_side_data’; have ‘uint8_t *(const AVStream *, enum AVPacketSideDataType,  size_t *)’ {aka ‘unsigned char *(const AVStream *, enum AVPacketSideDataType,  long unsigned int *)’}
   19 | uint8_t *av_stream_get_side_data(const AVStream *stream, enum AVPacketSideDataType type, size_t *size)
      |          ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/libplacebo/utils/libav.h:26,
                 from /home/efif/trees/xanadu/moonlight-qt/app/streaming/video/ffmpeg-renderers/plvk_c.c:12:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:2105:10: note: previous declaration of ‘av_stream_get_side_data’ with type ‘uint8_t *(const AVStream *, enum AVPacketSideDataType,  int *)’ {aka ‘unsigned char *(const AVStream *, enum AVPacketSideDataType,  int *)’}
 2105 | uint8_t *av_stream_get_side_data(const AVStream *stream,
      |          ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by cgutman** [comment]
You are probably using your distro's old version of `libplacebo` without support for all the brand new Vulkan video stuff. Moonlight requires basically bleeding edge upstream libplacebo for proper 10-bit color support.

I suggest removing `libplacebo-dev` from your system if you installed it for Moonlight, or compiling with `qmake CONFIG += "disable-libplacebo"`. I will update the readme to specifically mention `libplacebo` as requiring extremely recent versions.

**Comment by efifogel** [comment]
Thanks for the quick reply.
Indeed, any one of the two options you provided fixed the problem, and now
it successfully compiles all the way through.
Just for the record, I installed it in the first place, because I wanted to
compile Sunshine on the same machine, and this is a requirement (at least
this is listed as a requirement in the installation instructions for
Sunshine).
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
