### ISSUE TITLE
Crashing on connection / macOS 14.4 

### ISSUE THREAD

**Issue by fixerivan** [moonlight-stream/moonlight-qt#1188]
when i try to connect to my windows machine running sunshine on every connection (aka clicking on Explorer in the game list) crashes moonlight, happens consistently all the time

crash log / debug trace: https://gist.github.com/fixerivan/fb20ab53d7b6dd091278c58264d11eb1

**Comment by cgutman** [comment]
Please test with the latest nightly: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/49211978/job/2exqqybbsko35tww/artifacts

**Comment by Beena222** [comment]
Do you have a joystick/gamepad etc plugged in?
If so, does it crash when this is not connected? 
(see this issue - https://github.com/moonlight-stream/moonlight-qt/issues/1119#issue-2000336396)

**Comment by cgutman** [comment]
@fixerivan Does it still happen with the nightly build I linked in my comment above?

**Comment by cgutman** [comment]
Is this still happening with the macOS 14.4 Beta 5?

**Comment by cgutman** [comment]
It seems to work fine in fullscreen for me on my M2 MacBook Pro with the official release of macOS 14.4. Maybe it was bug Apple fixed during beta.

Please reopen if it still occurs on your Mac.
