### ISSUE TITLE
I can't launch Moonlight with Ubuntu Mate

### ISSUE THREAD

**Issue by thomas7428** [moonlight-stream/moonlight-qt#119]
**Describe the bug**
Moonlight crash after launch or can't just run.

**Steps to reproduce**
When I launch Moonlight.

**Moonlight settings (please complete the following information)**
- Default settings

**Screenshot**
![capture du 2018-10-28 19-06-08](https://user-images.githubusercontent.com/44552992/47620033-a8410700-dae5-11e8-851f-7d9426d6f61d.png)

**Client PC details (please complete the following information)**
 - OS: Ubuntu 18.04 LTS (Bionic Beaver) 32-bit
 - Moonlight Version: v.0.6.1

**Logs (please [attach)**
[Log.txt](https://github.com/moonlight-stream/moonlight-qt/files/2523058/Log.txt)

**Comment by cgutman** [comment]
Hmm, there are several OpenGL errors in that log. What GPU do you have in that PC?

Can you try running `flatpak update` just in case it needs to download a GL driver module?

**Comment by thomas7428** [comment]
Thank you very much for your answer.
I have an old Toshiba Satellite A60 with a Mobility Radeon 7000 IGP.
I know that's really old. 😅
If you need it, I can send you all the specifications of this antiquity.
I made all the updates but no effect.


De : Cameron Gutman <notifications@github.com>
Envoyé : lundi 29 octobre 2018 18:38
À : moonlight-stream/moonlight-qt
Cc : thomas7428; Author
Objet : Re: [moonlight-stream/moonlight-qt] I can't launch Moonlight with Ubuntu Mate (#119)


Hmm, there are several OpenGL errors in that log. What GPU do you have in that PC?

Can you try running flatpak update just in case it needs to download a GL driver module?

**Comment by cgutman** [comment]
Can you run `glxinfo -B` and attach the output?

**Comment by thomas7428** [comment]
[log.txt](https://github.com/moonlight-stream/moonlight-qt/files/2529221/log.txt)

**Comment by cgutman** [comment]
OK, try running it like: `flatpak run --env=QMLSCENE_DEVICE=softwarecontext com.moonlight_stream.Moonlight`

**Comment by cgutman** [comment]
I wonder if your GPU is too old to support hardware accelerated decoding on Linux open-source drivers.

Can you run `vdpauinfo` and `vainfo` and attach the output?

**Comment by thomas7428** [comment]
[vdpauinfo.txt](https://github.com/moonlight-stream/moonlight-qt/files/2543979/vdpauinfo.txt)
[vainfo.txt](https://github.com/moonlight-stream/moonlight-qt/files/2543983/vainfo.txt)

**Comment by cgutman** [comment]
Yeah, it looks like you don't have any hardware accelerated video decoding working on your GPU.

I don't think that Ubuntu 18.04 supports AMD's legacy fglrx driver package which may provide hardware acceleration. Since CPU performance on that laptop is weak too, I don't think you'll be able to get a satisfactory streaming experience.

**Comment by cgutman** [comment]
Closing this because it seems to be hardware too old to support streaming well
