### ISSUE TITLE
Launching Moonlight on Rasberry Pi 5 Terminal: Qt Fatal: Cannot Create Window Error

### ISSUE THREAD

**Issue by ninjaxcore** [moonlight-stream/moonlight-qt#1193]
**Describe the bug**
Running Moonlight on a Raspberry Pi 5 V12 Bookworm 8GB model. Moonlight installs and runs perfectly in the desktop environment, but when moonlight is launched in a terminal environment it results in a Qt Fatal error: Cannot create window: no screens available. Apparently this only occurs on the Raspberry Pi 5, not on previous Raspberry Pi versions.

I've tried the following steps to fix:
1. Plug mini-HDMI to port closest to power (HDMI0)
2. Launch Moonlight using QT_QPA_EGLFS_ALWAYS_SET_MODE=0 moonlight-qt - Doesn't work
3. Set hdmi_force_hotplug=0 in rpi settings - doesn't work
Replicate steps 2-3 with mini-HDMI plugged into HDMI1 port and changing 0 to 1. - Doesn't work

I found one solution at: https://forums.raspberrypi.com/viewtopic.php?t=361454
`echo '{ "device": "/dev/dri/card1" }' > eglfs.json
QT_QPA_EGLFS_KMS_CONFIG=eglfs.json moonlight-qt`
This works but seems to be not an ideal solution.

**Steps to reproduce**
1. Ctrl+Alt+1 to launch terminal environment
2. Launch Moonlight using command "moonlight-qt"
3.  Output: 
> 00:00:00 - Qt Info: Unable to detect Wayland or X11, so EGLFS will be used by default. Set QT_QPA_PLATFORM to override this.
00:00:00 - Qt Warning: QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0770 instead of 0700
00:00:00 - Qt Critical: drmModeGetResources failed (Operation not supported)
00:00:00 - SDL Info (0): Compiled with SDL 2.29.0
00:00:00 - SDL Info (0): Running with SDL 2.29.0
00:00:00 - Qt Info: No translation available for "en_GB"
00:00:00 - Qt Fatal: Cannot create window: no screens available
Aborted

**Affected games**
Affects Moonlight at launch

**Other Moonlight clients**
- Just on RP5

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? No

**Client PC details (please complete the following information)**
 - OS: Raspbian V12 Bookworm
 - Moonlight Version: v5.0.1
 - GPU: Onboard RP5 graphics
 - Linux package type (if applicable): Bookworm

**Server PC details (please complete the following information)**
N/A - this issue is only at the client level

**Moonlight Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux with the Flatpak, logs print to the terminal when running with the command: `flatpak run com.moonlight_stream.Moonlight`
- On Linux with the Snap, logs print to the terminal when running with the command: `moonlight`

> 00:00:00 - Qt Info: Unable to detect Wayland or X11, so EGLFS will be used by default. Set QT_QPA_PLATFORM to override this.
00:00:00 - Qt Warning: QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0770 instead of 0700
00:00:00 - Qt Critical: drmModeGetResources failed (Operation not supported)
00:00:00 - SDL Info (0): Compiled with SDL 2.29.0
00:00:00 - SDL Info (0): Running with SDL 2.29.0
00:00:00 - Qt Info: No translation available for "en_GB"
00:00:00 - Qt Fatal: Cannot create window: no screens available
Aborted

**Additional context**
Anything else you think may be relevant to the issue
The website I linked earlier seems to indicate this is just an issue on the Raspberry Pi 5, not the 4. Could this be related to the ARM64-bit architecture on the RP5?

**Comment by ninjaxcore** [comment]
I found this previous issue that fixed it for me: https://github.com/moonlight-stream/moonlight-qt/issues/1133#issuecomment-1858841158

**Comment by cgutman** [comment]
Fixed by 011feab6ceb1922e997cc9e8d82dd7387f9479a5
