### ISSUE TITLE
Streaming broken by new version of wlroots

### ISSUE THREAD

**Issue by qdii** [moonlight-stream/moonlight-qt#1198]
**Describe the bug**
New version of wlroots includes a check that causes Moonlight to abort streaming.

**Steps to reproduce**
- Start any stream using new version of wlroots.
- Witness that shortly after the handshake finishes, no stream is displayed and he main menu appears.

**Moonlight settings (please complete the following information)**
- No

**Client PC details (please complete the following information)**
 - OS: Linux, running Sway
 - Moonlight Version: 5.0.1
 - GPU: Radeon RX 6700
 - Linux package type (if applicable): [e.g. Flatpak]

**Server PC details (please complete the following information)**
 - OS: Sway 1.9
 - Sunshine or GeForce Experience version: Sunshine (version ?)
 - GPU: AMD Radeon RX 6700
 - GPU driver: irrelevant (amdgpu)

**Moonlight Logs (please attach)**
- Good & Bad logs: https://gist.github.com/qdii/55fb27cf83698c5395d13ce726a103de

**Comment by qdii** [comment]
The bug was originally opened on sway bug report, this comment is relevant: https://github.com/swaywm/sway/issues/8027#issuecomment-1974867491

**Comment by cgutman** [comment]
This is an SDL bug. Please try to reproduce with the SDL test binaries (SDL2 branch) and file a bug on https://github.com/libsdl-org/SDL/issues. If it doesn't reproduce with any of the SDL2 test binaries, then I can investigate further.
