### ISSUE TITLE
MacOS menubar and dock borderless / fullscreen

### ISSUE THREAD

**Issue by ErwinMeulman** [moonlight-stream/moonlight-qt#1206]
I use MacOS but in borderless display mode the menubar and dock are not usable, in fullscreen all keyboard shorts of MacOS are locked in the VM host, so switching to a new virtual desktop is not an option, i use a mx master with horizontal scrolling for switching, can we get a options to exclude buttons in the vm hosts?

**Comment by stfm1973** [comment]
If I have it in Windowed borderless it behaves as a normal window that I can have in fullscreen. Switching between desktops work with ctrl-back- and forward arrows.

**Comment by cgutman** [comment]
Yep, borderless windowed is the way.

Anyway this is resolved in current code because fullscreen is now handled like borderless windowed on macOS.
