### ISSUE TITLE
Rendering frame rate lower than Incoming/Decoding frame rate on Moonlight on macOS crashes with Fullscreen option - v0.0.0.2376 (in appveyor)

### ISSUE THREAD

**Issue by rramnel** [moonlight-stream/moonlight-qt#1218]
As shown in the picture, the rendering frame rate is usually around 10-15 fps lower than the incoming and decoding frame rates. I guess this is coming from frames being dropped due to Network jitter, but the odd thing is that when I use Borderless Windowed on Moonlight the issue is not there (both with network jitter and lower rendering frame rate). The issue seems to be only happening when Fullscreen option is used.

![IMG_1415](https://github.com/moonlight-stream/moonlight-qt/assets/865327/0e2521de-83c9-4d09-b14f-3862527772c9)

**Comment by rramnel** [comment]
Seems to be network related, closed the issue for now

**Comment by rramnel** [comment]
Looks like the issue seems to be with the Fullscreen mode enabled, I checked also with an Ethernet connection

**Comment by cgutman** [comment]
Please try the latest nightly build: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/49471909/job/350hdrlhdwpju442/artifacts

**Comment by rramnel** [comment]
Unfortunately the issue still seems to be there with this build

**Comment by rramnel** [comment]
Seems like the problem is still there, not sure if it is related to macOS or Moonlight though

**Comment by rramnel** [comment]
Wanted to share that since the nightly build [0.0.0.2415](https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/49648606) I don't seem to experience the issue so far. Will continue to monitor it and report if the issue is resolved.

**Comment by cody151** [comment]
Having this same issue on Windows latest, any fix??

**Comment by woiza** [comment]
same here, Linux arm64
