### ISSUE TITLE
Windows key press not being passed from guest to host

### ISSUE THREAD

**Issue by JaleSwiftpaw** [moonlight-stream/moonlight-qt#1219]
**Describe the bug**
When I press the Windows key on the guest, the guest's Start menu pops up instead of the host's Start menu. The expected behavior is to pop up the host's Start menu or at least both the host's and guest's Start menus at the same time (just like Parsec when not in immersive mode)

**Steps to reproduce**
Just pressing the Windows key

**Screenshots**
N/A

**Affected games**
Desktop

**Other Moonlight clients**
N/A

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? - Enabling the Right Alt key didn't work.
- If so, which settings have been changed? - Right Alt key, but doesn't seem to work.
- Does the problem still occur after reverting settings back to default? - Yes.

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly? - N/A
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad? - N/A
  - Instructions for streaming the desktop can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Client PC details (please complete the following information)**
 - OS: Microsoft Windows 11 Education 22H2 Build 22621.3007
 - Moonlight Version: 5.0.1
 - GPU: Intel UHD Graphics 630
 - Linux package type (if applicable): N/A

**Server PC details (please complete the following information)**
 - OS: Microsoft Windows 11 Pro 23H2 Build 22631.3296
 - Sunshine or GeForce Experience version: Sunshine 0.22.0
 - GPU: Nvidia GeForce RTX 2060 Super
 - GPU driver: 551.61

**Moonlight Logs (please attach)**
N/A

**Additional context**
- Issue is similar to https://github.com/moonlight-stream/moonlight-qt/issues/1108, but on Windows 11 guest instead of Steam Deck.
- Keyboard language is set to Spanish - Latin America.

**Comment by cgutman** [comment]
I believe this is working as intended. To pass the Windows key or other system-wide key combos like Alt+Tab to the host, you need to enable the "Capture system keyboard shortcuts" option in Moonlight's settings.

**Comment by JaleSwiftpaw** [comment]
> I believe this is working as intended. To pass the Windows key or other system-wide key combos like Alt+Tab to the host, you need to enable the "Capture system keyboard shortcuts" option in Moonlight's settings.

This is it, how dumb of me. Thanks.

**Comment by JaleSwiftpaw** [comment]
> I believe this is working as intended. To pass the Windows key or other system-wide key combos like Alt+Tab to the host, you need to enable the "Capture system keyboard shortcuts" option in Moonlight's settings.

This is it, how dumb of me. Thanks.
