### ISSUE TITLE
Custom ports support

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#122]
**Is your feature request related to a problem? Please describe.**
Since there are many that are trying to use moonlight form "locked" networks and vpn isn't a very good alternative I was wondering if it were possible to add custom ports support for moonlight.

**Describe the solution you'd like**
specify different ports/ ranges for moonlight to geforce gamestream

**Describe alternatives you've considered**
OpenVPN - but it is very inconsistent (many times choppy)

**Additional context**
On the host side the "custom port range" for GeForce Gamestream can be achieved via router internal to external port remapping, so it shouldn't be issues there.

**Comment by cgutman** [comment]
I don't think we'll add the option for custom ports. It's a lot of extra work for not much gain. It won't change the fact that you need several TCP and UDP ports to stream. Chances are that if your network administrator is draconian enough to block the normal ports, you will probably have difficulty finding another set of 5 ports that aren't blocked.

I've heard several users report success with ZeroTier (performing better than OpenVPN). I'm going to update the documentation to favor that as a second option for streaming from 2+ machines or working around firewall issues.

**Comment by apoklyps3** [comment]
The network administrator is not draconian, it's just those ports are closed for security reasons. I already know about 1000 other ports that aren't blocked, but if you say you have a better option, i'm all ears

**Comment by cgutman** [comment]
Your network administrator has blocked 47984 - 48010 TCP/UDP outbound? What security benefit is there to that?

**Comment by apoklyps3** [comment]
inbound.
This is a workplace network.

**Comment by apoklyps3** [comment]
anyway, looking forwards to the zerotier guide. installed it on both computers,but got no ideea how to link them...
