### ISSUE TITLE
Streaming with monitor off

### ISSUE THREAD

**Issue by cain-dev** [moonlight-stream/moonlight-qt#1226]
**Is your feature request related to a problem? Please describe.**
I want to stream without the monitor turned on, but everytime i turn the monitor off the stream ends =\

**Describe the solution you'd like**
Just turning off the monitor wihtout stopping the stream.

**Describe alternatives you've considered**
I tried using dummy plugs but it sucks.

**Additional context**
That's it

**Comment by Foul-Tarnished** [comment]
Just use virtual display driver...
https://github.com/itsmikethetech/Virtual-Display-Driver

**Comment by cgutman** [comment]
This is a host-side issue, so there's nothing we can do as the client here. It has to be solved on the host-side.

**Comment by cain-dev** [comment]
Just a question, it may be stupid but, why AMD supported this and moonlight-qt don't? What's the difference? 

Sorry about the inconvenience btw

**Comment by Foul-Tarnished** [comment]
> Just a question, it may be stupid but, why AMD supported this and moonlight-qt don't? What's the difference?
> 
> Sorry about the inconvenience btw

moonlight is the client, the "issue" is on sunshine side...
just use the virtual display driver I linked above

**Comment by Foul-Tarnished** [comment]
because AMD is a gpu vendor and can do whatever it wants with displays ?
like keeping the gpu on even with no display output active ?

**Comment by shevtsov-dmitry** [comment]
> Just use virtual display driver... https://github.com/itsmikethetech/Virtual-Display-Driver

Thanks, I had the same problem/ this is a perfect solution.
