### ISSUE TITLE
Option to wake host display(s)

### ISSUE THREAD

**Issue by drws** [moonlight-stream/moonlight-qt#1228]
**Is your feature request related to a problem? Please describe.**

Sunshine can only stream active displays, which is unfortunate for when the PC power management turns display(s) off after some time.

**Describe the solution you'd like**
Similar to Wake-on-LAN suggestions in this issue tracker there should also be a "send DPMS switch-on signal on connect", which would wake the monitor(s) before starting the video stream.

**Describe alternatives you've considered**
`xset dpms force on` as a custom command, but it would be much more practical for it to be built-in.

**Comment by cgutman** [comment]
This sounds like a Sunshine feature request, not a Moonlight one. I suggest filing it on Sunshine's issue tracker.
