### ISSUE TITLE
Performance overlay not display on LibreELEC with veldenb/plugin.program.moonlight-qt

### ISSUE THREAD

**Issue by moi952** [moonlight-stream/moonlight-qt#1229]
**Describe the bug**
Performance overlay not display on LibreELEC with veldenb/plugin.program.moonlight-qt

**Steps to reproduce**
Install  veldenb/plugin.program.moonlight-qt on LibreELEC and press ctrl+alt+maj+S Or press shortcut on xbox serie controller not working. 
press ctrl+alt+maj+Q work great

**Affected games**
All games

**Other Moonlight clients**
Only on veldenb/plugin.program.moonlight-qt

**Client PC details (please complete the following information)**
 - OS: LibreELEC
 - Moonlight Version: v5.0.1
 - GPU: Intel HD Graphics 620
 - Install from veldenb/plugin.program.moonlight-qt
 - Keybord configuration : FR (fr azerty)

**Server PC details (please complete the following information)**
 - OS: Windows 11
 - Sunshine or GeForce Experience version: Sunshine v0.22.1
 - GPU: RTX 4070
 - GPU driver: 551.61

**Comment by moi952** [comment]
This PR can be a perfect alternative to shortcut 
https://github.com/moonlight-stream/moonlight-qt/pull/1209

**Comment by jorys-paulin** [comment]
Hello! As you can see in my screenshot of that PR, the performance overlay isn't supported on Raspberry Pi (something about the decoder used I think?), so of course it won't be supported on veldenb's plugin either.

**Comment by moi952** [comment]
> Hello! As you can see in my screenshot of that PR, the performance overlay isn't supported on Raspberry Pi (something about the decoder used I think?), so of course it won't be supported on veldenb's plugin either.

Your pull request is in draft, is that normal?

Do you know if anyone is planning to do the review so that it can be used for the next production release?

Why doesn't it work on raspberry pi?

**Comment by cgutman** [comment]
Performance overlay depends on support within the renderer being used. Most renderers do support it, but KMSDRM and MMAL renderers (used on the Pi for HEVC and H.264, respectively) don't support it. The reason is the complexities of correctly juggling multiple overlay planes at the same time (and hardware limitations on the number of overlay planes and which pixel formats they support.
