### ISSUE TITLE
Dualshock 4 recognised as Xbox 360 Controller

### ISSUE THREAD

**Issue by PatiB87** [moonlight-stream/moonlight-qt#123]
I use Windows 10 on both machines and the most recent moonlight build.
When I now connect my DS4 via bluetooth to the client PC, the client PCs Steam recognizes it as Playstation 4 controller.
Now I quit Steam (and turn off / back on the controller, otherwise Steam seams to "hoard" the controller so no other app can use it) and STREAM Steam via moonlight from my gaming pc to my client. The streamed Steam now also recognizes the controller, however, it shows up as "Xbox 360 Controller".

Is there a way to fix this? Maybe install drivers somewhere? Or has this to be fixed in moonlight?

**Comment by cgutman** [comment]
This is just how GameStream emulates controllers. GameStream always presents an XInput controller to the app on the PC, no matter what is actually plugged into the client.

If you need the PS4 controller to be identified explicitly, you can try VirtualHere (which may require USB or forwarding your whole Bluetooth adapter) or maybe Steam's controller configurator might be able to emulate it (unsure).
