### ISSUE TITLE
Raspberry Pi 4 Installer Does Not Recognize OSMC 2024.02-1

### ISSUE THREAD

**Issue by alik250** [moonlight-stream/moonlight-qt#1232]
**Describe the bug**
Fails to install on Raspberry pi 4 running OSMC 2024.02-1

**Steps to reproduce**
- Install OSMC
- SSH into OSMC
- $ curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | distro=raspbian sudo -E bash
- ^^^^: ... Failed to fetch configuration for your OS distribution release/version

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
-   - No, besides testing distro=osmc (which results in the same error) 

**Client PC details (please complete the following information)**
 - OS: OSMC 2024.02-1
 - Moonlight Version: n/a
 - GPU: Raspberry Pi 4 2GB
 - Linux package type (if applicable): Install script from: https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4

**Moonlight Logs (please attach)**
```
$ curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | distro=raspbian sudo -E bash
Executing the  setup script for the 'moonlight-game-streaming/moonlight-qt' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=raspbian  version=2024.02-1  codename=February  arch=aarch64
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Checking for apt signed-by key support ...
   OK: Importing 'moonlight-game-streaming/moonlight-qt' repository GPG keys ...
 NOPE: Checking if upstream install config is OK ...
 ^^^^: ... Failed to fetch configuration for your OS distribution release/version.
 >>>>:
 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=raspbian  version=2024.02-1  codename=February  arch=aarch64
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as Ubuntu/Xenial (16.04), use the following:
 >>>>:
 >>>>:   <curl command> | distro=ubuntu version=16.04 codename=xenial sudo -E bash
 >>>>:
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!:
 !!!!: You can contact Moonlight Game Streaming for further assistance.
 !!!!:
 !!!!: URL: https://github.com/moonlight-stream/moonlight-qt
 !!!!:
 !!!!: Last 20 log lines from .csm_setup_TZRkbo3vM (might not be errors, nor even relevant):
 !!!!:
 !!!!: > ii  gnupg                                2.2.27-2+deb11u2
 !!!!: > all          GNU privacy guard - a free PGP replacement
 !!!!: > ii  gnupg-l10n                           2.2.27-2+deb11u2
 !!!!: > all          GNU privacy guard - localization files
 !!!!: > ii  gnupg-utils                          2.2.27-2+deb11u2
 !!!!: > armhf        GNU privacy guard - utility programs
```

**Additional context**
I have also tried replacing distro=raspbian with distro=osmc just in case. I got the same error.

The installation guide describes extra steps to finalize an install on OSMC, but not how to initiate it so I figured it was the same as Raspberry Pi OS.

**Comment by kurac338** [comment]
The following are my own instructions for OSMC + Moonlight-QT + [Moonlight Kodi plugin](https://github.com/veldenb/plugin.program.moonlight-qt).

# Installation
- Configure `/boot/config-user.txt`

- (If not fixed on the OS level) Add the `osmc` user into the `input` group
``` shell
sudo usermod -a -G input $USER
sudo reboot
```

- Install `moonlight-qt` as per [instructions](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4)
``` shell
# The following command will try to resolve the distribution release
# If that does not work, use 'codename=buster' to override the value
curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | distro=raspbian codename=$(lsb_release -cs) sudo -E bash
sudo apt install moonlight-qt
```

- (Optional) Install Docker
- Install addon
``` shell
# Check the website for latest release version (https://github.com/veldenb/plugin.program.moonlight-qt/releases/latest)
VERSION=0.4.3; wget https://github.com/veldenb/plugin.program.moonlight-qt/releases/latest/download/plugin.program.moonlight-qt-${VERSION}.zip
# Install the downloaded addon package using Kodi GUI. For convenience, download into $HOME folder
# Remove downloaded plugin archive, as its no longer needed
```
- Configure addon
- Connect a keyboard to RPI (controller navigation does not work for all buttons)
- Configure `moonlight-qt` settings and add a host

## Updating
Plugin needs to be updated manually by following the steps outlined above.
From official addon repository docs:
``` text
When you want to update Moonlight you can use the update menu in the add-on settings and press "Update Moonlight to the latest version".
The plugin will update Moonlight and will notify you when it's finished.
```

# Monitoring
``` shell
tail -f ~/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt.log
```

# References:
- https://github.com/veldenb/plugin.program.moonlight-qt
- https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4

**Comment by alik250** [comment]
^ That worked for me! I wish it was a part of the official documentation though. In all my research I haven't found that repo on my own. Thanks for your reply!

For anyone with the same problem, basically, try to run 
```curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | distro=raspbian codename=$(lsb_release -cs) sudo -E bash```
instead of 
```curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | distro=raspbian sudo -E bash```

**Comment by cgutman** [comment]
I updated the installation steps to add `codename=$(lsb_release -cs)`. Thanks for the suggestion.
