### ISSUE TITLE
"Mute host's PC speakers" option doesn't work

### ISSUE THREAD

**Issue by JaleSwiftpaw** [moonlight-stream/moonlight-qt#1235]
Basically what the title says. I'm streaming my room's gaming PC (host) to the living room laptop connected to a TV and I can still hear the host's speakers from my room loud and clear, even if the "Mute host PC speakers" option is enabled.

Moonlight version is 5.0.1.

**Comment by cgutman** [comment]
This isn't a client issue, so it belongs on Sunshine. However if I had to guess, the problem is probably that you don't have Steam installed, so there's no virtual audio device for Sunshine to use in place of your real speakers.
