### ISSUE TITLE
Leaves a shadow process in win7

### ISSUE THREAD

**Issue by Dalizzi** [moonlight-stream/moonlight-qt#124]
**Describe the bug**

**Steps to reproduce**
Any special steps that are required for the bug to appear.

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1803]
 - Moonlight Version: [e.g. v0.2.0]

**Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux, logs print to the terminal when running via `flatpak run com.moonlight_stream.Moonlight`

**Additional context**

**Comment by Dalizzi** [comment]
When Moonlight app is running on win7, after hibernate and reopen, Moonlight leaves a shadow process which is seen in the tray. Only With Taskmgr or from cmd line you can kill it. I think Qt App is not handling SIGTERM correctly.

**Comment by Dalizzi** [comment]
[Moonlight-1541142852.log](https://github.com/moonlight-stream/moonlight-qt/files/2545363/Moonlight-1541142852.log)
[Moonlight-1541164082.log](https://github.com/moonlight-stream/moonlight-qt/files/2545364/Moonlight-1541164082.log)
[Moonlight-1541279114.log](https://github.com/moonlight-stream/moonlight-qt/files/2545365/Moonlight-1541279114.log)
,
not zipped, hope you can find you the problem

**Comment by Dalizzi** [comment]
Checked logs and *852 seems to be the right related to the case 
01:26:18 - Qt Warning: qrc:/gui/StreamSegue.qml:8:1: QML StreamSegue: StackView has detected conflicting anchors. Transitions may not execute properly.
01:26:18 - Qt Warning: qrc:/gui/AppView.qml:9:1: QML AppView: StackView has detected conflicting anchors. Transitions may not execute properly.
01:26:18 - SDL Info (0): done
01:26:18 - SDL Info (0): Stopping video stream...
01:26:18 - SDL Info (0): done
01:26:18 - SDL Info (0): Stopping control stream...
01:26:18 - SDL Info (0): done
01:26:18 - SDL Info (0): Cleaning up input stream...
01:26:18 - SDL Info (0): done
01:26:18 - SDL Info (0): Cleaning up audio stream...
01:26:18 - SDL Info (0): done
01:26:18 - SDL Info (0): Cleaning up video stream...
01:26:18 - SDL Info (0): done
01:26:18 - SDL Info (0): Cleaning up control stream...
01:26:18 - SDL Info (0): done
01:26:18 - SDL Info (0): Cleaning up platform...
01:26:18 - SDL Info (0): done

<-- Now I don't understand how you implement a process with Qt eventloop, which is not closing on SIGTERM.

**Comment by cgutman** [comment]
I will need the dump file to debug this. The logs probably won't be enough. Please try to get a dump file using my instructions.

**Comment by Dalizzi** [comment]
Not reproduced with latest GFE / Moonlight.
