### ISSUE TITLE
Can't use Moonlight on school network

### ISSUE THREAD

**Issue by Ramine0** [moonlight-stream/moonlight-qt#1240]
**Describe the bug**
Moonlight is working perfectly on home network. I even tried connecting my other PC using hotspot on my phone and port forwarding and it works. But at my school, nothing works, Moonlight doesn't even detect the host PC.

**Steps to reproduce**
- Launch Sunshine on the host PC.
- Download the portable version of Moonlight and copy it to an USB drive.
- Disable my VPN (Proton VPN), launch Moonlight, go to frameip.com (or whatismyip) to get the router IP address and add a new PC with this address.
- Put the PIN code into Sunshine.
- Plug the USB drive on a school PC and launch it. My PC is already configured and linked with Sunshine, because it's the portable version, but Moonlight can't find it.
- Do a network test : the ports are blocked.

**Screenshots**
Not needed I think

**Affected games**
No games, just connecting to my PC

**Other Moonlight clients**
Didn't try. But I think I would work because I would use mobile data instead of school network (it's not WiFi, just Ethernet).

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? No, expect the ports in Sunshine.
- Does the problem still occur after reverting settings back to default? Yes, it's network related.

**Client PC details (please complete the following information)**
 - OS: Windows 10 Pro
 - Moonlight Version: v5.0.1
 - GPU: Don't know

**Server PC details (please complete the following information)**
 - OS: Linux Mint Cinnamon 21.3
 - Sunshine version: 0.22.2.33c6c3e.dirty
 - GPU: RTX 3060 Laptop
 - GPU driver: nvidia-driver-535

**Moonlight Logs (please attach)**
[Moonlight-1711471895.log](https://github.com/moonlight-stream/moonlight-qt/files/14761957/Moonlight-1711471895.log)

**Additional context**
I think the problem is my school network which is blocking ports. I tried with my phone hotspot, it worked, but it takes too much data.

I also tried using my PC with AnyDesk in order to change the ports to the following : 1900, 3389, 2869 and 8080 but nothing works.

I want to protect my personal data, so I don't want to create a ZeroTier or TailScale account, and I'm not sure that my school's network allows VPN. Already tried using my own PC, plug the Ethernet and enable Proton VPN. Result : I didn't have Internet, so I guess that all VPNs are blocked.

I love Moonlight because it's open-source and works like a charm on Linux. I want to remote control my PC very fluidly, to have a good experience and maybe do some gaming one day. Parsec is not a good option. It requires an account and hosting is not supported on Linux.

Is there anything to do ? A way to test working ports on Windows without admin rights ? Or should I send a mail to my school to explain them ?

I need help, please

Sorry for bad English, I'm French.

**Comment by gschintgen** [comment]
That's normal for a corporate or school network. Specific ports are whitelisted. Circumventing such a firewall might well be against the terms of service.
Anyway, for checking specific ports, you can use http://portquiz.net/.
Tunneling could possibly be done via websockets. (wstunnel comes to mind).

**Comment by Ramine0** [comment]
Thanks for fast reply!
If I understand correctly, I need to open http://portquiz.net:port to test if it's blocked ?
And what is wstunnel ? What's the difference with a VPN like ZeroTier ?

**Comment by gschintgen** [comment]
I think at this point you're on your own ;-)
stunnel or even wstunnel can be used to tunnel arbitrary traffic via TLS or websockets. (Those are difficult to block without breaking all web activity.) But that's probably way out of scope for this bugtracker.

(I'm not affiliated with the project, I just wanted to give you some pointers what you could try.)

**Comment by Ramine0** [comment]
I did some searches about wstunnel but I'm quite confused.
Network is complex sometimes :-)
But if it's out of this bugtracker, I guess I will have to understand by myself...

**Comment by cgutman** [comment]
Closing since this is an issue with firewalls intentionally blocking apps like Moonlight.
