### ISSUE TITLE
Client GPU selection (again)

### ISSUE THREAD

**Issue by farnoy** [moonlight-stream/moonlight-qt#1241]
**Is your feature request related to a problem? Please describe.**
My laptop has optimus/switchable graphics and only the dGPU supports AV1. Since https://github.com/moonlight-stream/moonlight-qt/commit/212ed33b21793193b87f1002ebfc06eb6c662f75, moonlight blocks optimus and dGPU from loading at all. 

**Describe the solution you'd like**
I think removing the explicit DLL blacklist should be enough. Users should be able to select the GPU they want to use in windows settings.

**Describe alternatives you've considered**
The only workaround is to boot the laptop in dGPU-first mode, where it has the MUX switch locked to the dGPU at all times.

**Additional context**
Selecting the GPU to use on the client has been suggested before, in #388, but I think there's a better motivation for this change now, which wasn't there before.

**Comment by cgutman** [comment]
I agree, especially now that we are defaulting to D3D11VA instead of DXVA2. We should encounter significantly fewer driver/hook compatibility issues since our D3D11 rendering code is much more similar to a regular game or other 3D application than our DXVA2 code was.
