### ISSUE TITLE
Black vertical bars and black menu bar in borderless fullscreen on macos

### ISSUE THREAD

**Issue by Vertreal** [moonlight-stream/moonlight-qt#1244]
**Describe the bug**
When streaming in borderless fullscreen, despite native resolution the received stream is cropped on the top and sides. Effectively this results in big "bezels". In exclusive fullscreen, this doesn't happen. 

**Steps to reproduce**
Start a borderless fullscreen stream at native resolution. In my case on a 14 inch MBP M1 Pro.

**Moonlight settings (please complete the following information)**
- Native resolution 3024x1964
- Changing other settings (except to exclusive fullscreen) doesn't help. Changing stream resolution can result in the stream being cropped differently, for example only horizontally instead of vertically. 

**Client PC details (please complete the following information)**
 - macOS Sonoma 14.4
 - Moonlight Version: 5.0.1
 - GPU: M1 Pro

**Server PC details (please complete the following information)**
 - OS: Windows 11
 - Sunshine 0.22.2
 - GPU: RTX 4080
 - GPU driver: Geforce Game Ready Deiver 551.86

**Comment by cgutman** [comment]
I'm pretty sure the reason for the black bars is because our "native" resolution is the full resolution of the display (excluded insets like the display notch). When using borderless fullscreen, the OS lays out the window _including_ insets.

**Comment by cgutman** [comment]
This should be fixed in the latest nightly build. There's now separate entries for native resolutions with and without the notch.

You can test it from here: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/49795697/job/q2f3adjbrm2uhjap/artifacts
