### ISSUE TITLE
Issue - Windowed Mode on Android Client doesn't work

### ISSUE THREAD

**Issue by sambuev** [moonlight-stream/moonlight-qt#1246]
Hello, I use Android Client to connect to my PC from my Samsung Galataxy Tab S8 Plus, everything work great, but I missing Windowed mode and cannot see any default Galaxy Tabs such as Time, Notifications, etc and at the bottom missing some Galaxy-Icons to start another apps, since they do not cover any area, I have black-bars on top and bottom. 

I also did a research and found out that PC Client have shortcuts to switch between the modes, but the same shortcuts do not work on Android, while some shortcuts do.

For example:
Ctrl+Alt+Shirt+C - I use to use my own mouse because remote-mosue have significant delay. 
Ctrl+Alt+Shift+X - supposed to switch between Full-Screen and Windowed, but it doesn't work on Android, only on PC. Please help.

**Comment by cgutman** [comment]
Duplicate of https://github.com/moonlight-stream/moonlight-android/issues/1353

**Comment by asdChenJin** [comment]
Hello, I encountered a similar problem to yours, I'm not sure if you still need to solve this problem， after all, two years have passed. 

I discovered that I can use a keyboard shortcut:Ctrl+Alt+Shift+Z to solve the problem of the mouse being locked inside the app.
