### ISSUE TITLE
Mouse freezes and is unusable for some games (Valorant)

### ISSUE THREAD

**Issue by AlexSwartz** [moonlight-stream/moonlight-qt#1253]
For some games with newer anti-cheat such as Valorant, mouse inputs are completely locked out. Currently the only workaround is using VirtualHere (supports all platforms) or USB/IP Project (windows and linux).

There are some major downsides to this, especially for Android. VirtualHere has arguably predatory licensing, for Windows/Mac/Linux allowing 1 usb device for free which is great, but for Android there is only a limited free trial and then it requires a license. The predatory licensing occurs because a license is hardware bound and cannot be transferred to a new devices. So changing phones or upgrading phones you have to buy a new license for $25.

It would be great of moonlight could support mouse inputs for these games and not have to rely on paid outside software, for Android especially.

**Steps to reproduce**
Launch Valorant and try to use the mouse. Mouse will be completely locked out and no inputs registered.

**Comment by cgutman** [comment]
This isn't a client-side issue. It would need to be addressed in Sunshine, if possible.
