### ISSUE TITLE
Moonlight uses an old VA-API

### ISSUE THREAD

**Issue by MartinX3** [moonlight-stream/moonlight-qt#1257]
**Describe the bug**
No GPU decoding.
Moonlight uses 1.20.  
I use 1.21.

**Steps to reproduce**
Starting moonlight on Arch Linux.

**Client PC details (please complete the following information)**
 - OS: Arch Linux
 - Moonlight Version: 5.0.1
 - GPU: Intel HD Graphics 530
 - Linux package type (if applicable): native

**Moonlight Logs (please attach)**
[log.log](https://github.com/moonlight-stream/moonlight-qt/files/14962643/log.log)

**Comment by cgutman** [comment]
The version of libva.so that Moonlight uses is whatever your system provides per the regular library search path. It's not included as part of Moonlight itself (unless you're using the AppImage or Snap package). You can confirm this by running `ldd` on the Moonlight binary.

**Comment by MartinX3** [comment]
Ah, I read the app is not dynamical linked.  
Should this be the reason?
Then I prepare a downstream issue ticket.

**Comment by cgutman** [comment]
I'd recommend using the `moonlight-qt` package instead of the `moonlight-qt-bin` package. The former compiles from source using your system's libraries, while the latter is just a repacked AppImage (with all the limitations that come with that).
