### ISSUE TITLE
Add support for full E2E stream encryption

### ISSUE THREAD

**Issue by manstheram** [moonlight-stream/moonlight-qt#1258]
**Is your feature request related to a problem? Please describe.**
Video and audio should be fully encrypted when being sent over the internet to prevent a data breach.

**Describe the solution you'd like**
Supporting the encryption modes of Sunshine on Moonlight

**Describe alternatives you've considered**
Moonlight Android now supports this since version [12.1](https://github.com/moonlight-stream/moonlight-android/releases/tag/v12.1)

**Additional context**
Sunshine now supports this function since version [v0.22.0](https://github.com/LizardByte/Sunshine/releases/tag/v0.22.0) from a month ago.

**Comment by cgutman** [comment]
It already supports it, but not yet in an official release.

You can find nightly builds here: https://ci.appveyor.com/project/cgutman/moonlight-qt/branch/master (Click on one of the platforms then go to the Artifacts tab)
