### ISSUE TITLE
About gamepad mappings again

### ISSUE THREAD

**Issue by Andryshik345** [moonlight-stream/moonlight-qt#127]
Hello, I'm using XONE gamepad and connect directly to pc through adapter(no bluetooth), but when i start streaming, moonlight is mapping own gamepad(but gives error, because nothing is connected to the client) and on pc appear two gamepad, nonexistent moonlight's gamepad on 0 port and my XONE gamepad on 1 port(1-2 player, accordingly). Because of this, my games detects my XONE gamepad is like X360 or does not detect at all. Can i not mapping anything in moonlight?
p.s.: sorry for may bad english.

**Comment by cgutman** [comment]
Can you get logs after encountering this issue?

On Windows, `Moonlight-###.log` files can be found in %TEMP%. Simply type that into the File Explorer path field to navigate there.
On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
On Linux, logs print to the terminal when running via `flatpak run com.moonlight_stream.Moonlight`

**Comment by Andryshik345** [comment]
I forget to mention that I use Raspberry Pi 3B as client, so i may write issue in the wrong git. I'll make logs later.

**Comment by Andryshik345** [comment]
Okay, then i close this issue and a create one there, thanks.
