### ISSUE TITLE
moonlight-qt unable to launch on Raspberry Pi 5

### ISSUE THREAD

**Issue by Rubikz91** [moonlight-stream/moonlight-qt#1272]
On a Raspberry Pi 5 running 64bit Lite Bookworm; from the console, I am unable to launch moonlight-qt.
When running the command "moonlight-qt", I receive the following:

`00:00:00 - Qt Info: Unable to detect Wayland or X11, so EGLFS will be used by default. Set QT_QPA_PLATFORM to override this.`
`00:00:00 - Qt Info: Setting display mode by default. Set QT_QPA_EGLFS_ALWAYS_SET_MODE=0 to override this.`
`00:00:00 - Qt Critical: drmModeGetResources failed (Operation not supported)`
`00:00:00 - SDL Info (0): Compiled with SDL 2.29.0`
`00:00:00 - SDL Info (0): Running with SDL 2.29.0`
`00:00:00 - Qt Info: No translation available for "en_GB"`
`00:00:00 - Qt Fatal: Cannot create window: no screens available`
`Aborted`

I have seen a couple posts where people note there are fixes, but I have not been able to figure out exactly how to apply a fix.

**Comment by gschintgen** [comment]
See here:
https://github.com/moonlight-stream/moonlight-qt/issues/1133#issuecomment-1858841158

**Comment by cgutman** [comment]
Closing as fixed in v6.0.0
