### ISSUE TITLE
[Feature Request] Hide server mouse cursor, and show client mouse cursor instead

### ISSUE THREAD

**Issue by Gfrni** [moonlight-stream/moonlight-qt#1273]
Problem:
Delays in mouse cursor motion, is more problematic than other type of delays.
Because a human **cannot move the mouse without watching the cursor real-time path** and position. The less the delay, the easier the control.

Solution:
Despite being the most problematic delay, it has a very easy solution.
Hide the server cursor, and **view the client cursor instead**.
**The cursor icon cannot be updated without delay**, when it enters a new location which needs a different cursor icon. It may feel inconsistent. But, instead, the cursor position will be always up to date, with zero delay.
Also, **clicks should be sent with the client mouse x and y**, ignoring the server mouse location.

**Additional context**
Seeing some VNC clients can help, if I have not explained it well enough

**Comment by thetubster99** [comment]
Linking for completeness

#1268

**Comment by Gfrni** [comment]
> Linking for completeness

Thanks for mentioning you issue. I have forgot to search before submitting the same issue again.
I think mine should be closed because you have explained it better than me.
Thanks.

**Comment by kevinshane** [comment]
bump this up! really need this feature!! also I think the ctrl+alt+shift+L should also can be persisted when start streaming, so does the ctrl+alt+shift+N and ctrl+alt+shift+C of cause.

**Comment by slrgt** [comment]
please make this possible by default
