### ISSUE TITLE
Unable to play epic games streaming my PC to my ROG Ally. 

### ISSUE THREAD

**Issue by twostepjake** [moonlight-stream/moonlight-qt#1274]
**READ ME FIRST!**
If you're here because something basic is not working (like gamepad input, video, or similar), it's probably something specific to your setup, so make sure you've gone through the Troubleshooting Guide first: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

If you still have trouble with basic functionality after following the guide, join our Discord server where there are many other volunteers who can help (or direct you back here if it looks like a Moonlight bug after all). https://moonlight-stream.org/discord

**Describe the bug**
Regardless of how i try to launch an Epic game, whether its through the epic launcher or playnite, my controls do not work. 

**Steps to reproduce**
Any special steps that are required for the bug to appear.

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Affected games**
All epic games

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?

**Moonlight settings (please complete the following information)**
Only settings changed were to 1080 and 60fps

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
still happens if i stream desktop

**Client PC details (please complete the following information)**
ROG Ally z1 NOT EXTREME

**Server PC details (please complete the following information)**
 - OS: Windows 11
 - Sunshine 23.1
 - GPU: RTX 4070
 - GPU driver: 552.22

**Moonlight Logs (please attach)**
i dont have any logs

**Additional context**
I've been going at this researching and posting on every reddit and discord and no one has replied or been able to help. I wanna tear my hair out! everything else works just fine. But epic refuses! Any help is beyond appreciated!

**Comment by cgutman** [comment]
This isn't a Moonlight problem - Moonlight doesn't know or care which games you're playing on the host. It's likely a compatibility issue with the host software (probably Sunshine) and whatever game you're using, so the issue should be filed there instead.
