### ISSUE TITLE
Incoming frame rate suddenly drop to <1 fps

### ISSUE THREAD

**Issue by VGT789** [moonlight-stream/moonlight-qt#1275]
**Describe the bug**
When using the windows client and after a seemingly random amount of time (from 30 secs to more than 5min) the client will start lagging and after a few seconds, completely freeze. Quitting the session (with Ctrl+Alt+Shift+Q) and joining it again will temporarily fix it.

**Steps to reproduce**
Start a session and wait.

**Screenshots**
Screenshot of the performance overlay
![bug moonlight](https://github.com/moonlight-stream/moonlight-qt/assets/36519476/6fee3222-8b72-4665-b3ac-660b0a19eee9)

**Affected games**
Everything I've tried, desktop and games.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?
Not on android

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? 
No, I've done a fresh install of windows and moonlight.

**Client PC details (please complete the following information)**
- OS: windows 11 23h2
- Moonlight Version: v5.0.1
- GPU: intel iris Xe graphics

**Server PC details (please complete the following information)**
- OS: windows 11 23h2
- Sunshine or GeForce Experience version: Sunshine v0.23.1
- GPU: Nvidia rtx 3060
- GPU driver: 552.22

**Moonlight Logs (please attach)**
[Moonlight-1715199365.log](https://github.com/moonlight-stream/moonlight-qt/files/15254946/Moonlight-1715199365.log)

**Comment by cgutman** [comment]
Your log has tons of network drops logged.

Particularly these kind:
```
01:21:57 - SDL Info (0): Unrecoverable frame 49196: 1+0=1 received < 72 needed
01:21:58 - SDL Info (0): Unrecoverable frame 49199: 1+0=1 received < 72 needed
01:21:58 - SDL Info (0): Unrecoverable frame 49200: 1+0=1 received < 75 needed
01:21:58 - SDL Info (0): Unrecoverable frame 49202: 1+0=1 received < 74 needed
01:21:58 - SDL Info (0): Unrecoverable frame 49208: 1+0=1 received < 74 needed
01:21:58 - SDL Info (0): Unrecoverable frame 49211: 1+0=1 received < 82 needed
01:21:58 - SDL Info (0): Unrecoverable frame 49212: 1+0=1 received < 74 needed
01:21:58 - SDL Info (0): Unrecoverable frame 49215: 1+0=1 received < 83 needed
```

Only receiving a single packet per frame is a giant red flag that indicates an underlying network connectivity issue between the client and host. It could be anything from the NICs on either side to switches, cables, or other hardware between them.

**Comment by VGT789** [comment]
I was able to try on the same PC with ethernet and the issue disappeared. After looking into it, I'm pretty sure the issue came from my WIFI card.
