### ISSUE TITLE
Update Windows build instruction, Wix 4.0.4 how to? Undefined symbol D3D11_DECODER_PROFILE_AV1_VLD_PROFILE0.

### ISSUE THREAD

**Issue by Originalimoc** [moonlight-stream/moonlight-qt#1277]
Using latest Qt official installer 6.7.0(But it only comes with MSVC 2019???) and latest VS 2022.
Problem 1:
Undefined symbol in file ./app/streaming/video/ffmpeg-renderers/d3d11va.cpp, not sure if SDK with Qt too old...?
After adding
```
DEFINE_GUID(D3D11_DECODER_PROFILE_AV1_VLD_PROFILE0, 0xb8be4ccb,0xcf53,0x46ba,0x8d,0x59,0xd6,0xb8,0xa6,0xda,0x5d,0x2a);
```
to it then it compiles, then problem 2:
The WixToolset 4.0.4 is neither installed with VS 2022 nor included in its plugin marketplace, and I seriously can not find a way to correctly install it...

The compiled binary works though.
After copy Moonlight.exe from `.\moonlight-qt\build\build-x64-release\app\release` to `.\moonlight-qt\build\deploy-x64-release` and all contents inside "deploy-x64-release" can be distributed as a complete build.

**Comment by cgutman** [comment]
`D3D11_DECODER_PROFILE_AV1_VLD_PROFILE0` is part of the latest Windows 11 22H2 SDK, so I suspect you have an older version.

WixToolset is a NuGet package so there's no need to install anything. It will be fetched automatically when you run the build scripts correctly. I've upgraded to WiX 5.0.0, so I suggest pulling the latest code and trying again.

**Comment by Originalimoc** [comment]
Ok, turns out official repo is not included. Solution: in VS 2022 - Tools - NuGet Manager - Settings - Repo, add "https://api.nuget.org/v3/index.json", then click update.

**Comment by Originalimoc** [comment]
So FAQ a how to install and invoke newer SDK version in Qt command env? Add I think adding `DEFINE_GUID(D3D11_DECODER_PROFILE_AV1_VLD_PROFILE0, 0xb8be4ccb,0xcf53,0x46ba,0x8d,0x59,0xd6,0xb8,0xa6,0xda,0x5d,0x2a);` to ./app/streaming/video/ffmpeg-renderers/d3d11va.cpp is fine since it doesn't break anything AFAIK and making it buildable from an older SDK.

**Comment by cgutman** [comment]
> So FAQ a how to install and invoke newer SDK version in Qt command env? 

I'm not sure how you ended up with an old one. The required SDK version has been shipping with Visual Studio 2022 for like 2 years. I've set up a few Windows machines since then and never had to do any special configuration to be able to build Moonlight.

**Comment by Originalimoc** [comment]
No idea. My Windows 11 install date is 2023/‎3/‎22, I use all installer from official sites too. I'll try again in a new VM next time.
