### ISSUE TITLE
HDR in games without required Windows setting washed out (unlike Cyberpunk i.e.)

### ISSUE THREAD

**Issue by ap3nr0ts** [moonlight-stream/moonlight-qt#1285]
On the latest version of Moonlight, a custom build linked [here](https://github.com/moonlight-stream/moonlight-qt/issues/1117), a game like Cyberpunk works perfectly via Moonlight via Sunshine. It's gorgeous. Any game I try without the requirement of HDR enabled in Windows, such as Elden Ring or the latest Mass Effect, look completely washed out when enabling HDR via their menus.

I feel like I've tried literally anything today, from Auto-HDR on or off, enabling and disabling certain functionalities on my RTX 4070, and countless reboots or mods that make it so these games could support HDR (or Auto-HDR) in windowed mode etc.

Is this something that can and will be fixed? Because I'd love to replay Elden Ring on my Steam Deck OLED via Moonlight, but the only thing I'm missing right now is HDR. I get the feeling it does look okay on my host PC, but keeps looking washed out on my Deck's screen.

Settings in Moonlight are pretty standard. HDR is on, of course. The rest is on automatic or just adjusted to the needs of my resolution (1280x800) and desired framerate (90). Using Windows 11 and all the latest drivers (RTX 4070). Hope someone here has some tips.

**Comment by cgutman** [comment]
This is a limitation of Sunshine that is documented [here](https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/setup.html#hdr-support)

Specifically:
> Older games that use NVIDIA-specific NVAPI HDR rather than native Windows HDR support may not display properly in HDR.

You may be able to use a tool like [SpecialK](https://www.special-k.info/) to convert NVAPI HDR to proper Windows HDR for correct capture via Sunshine, but it's not something I've tried.

**Comment by christofin** [comment]
Same here on 6.0.1. Elden Ring and Sekiro both come to mind.

**Comment by rip3rs** [comment]
I can confirm that using SpecialK it fixed on Sekiro RE2:RE ER Thank you for this.
