### ISSUE TITLE
error: app/com.moonlight_stream.moonlight/x86_64/master not installed

### ISSUE THREAD

**Issue by Sn34k** [moonlight-stream/moonlight-qt#129]
Not sure whats is the issue here, i was on a older patch and it worked for me but after while it stopped working. So a friend insisted i update it as it was a issue that was fixed. So now i tryed the update but i'm getting this error code after the flatpak installion through my terminal. BTW, i'm on linux mint 18.3

error: app/com.moonlight_stream.moonlight/x86_64/master not installed

but i can't locate my master file , the app will launch but after the initial handshake its fails to launch. Worked before but i'm not sure whats the issue!? Any help would be appreciated. Thanks!

**Comment by cgutman** [comment]
Can you try a reinstall?

`flatpak uninstall com.moonlight_stream.Moonlight`
`flatpak install flathub com.moonlight_stream.Moonlight`

**Comment by Sn34k** [comment]
Prefect , this got it going, but i had some other outstanding issues unresolved which contributed to it's problem. None the less thanks!

**Comment by Manjarly** [comment]
Using Ubuntu and I am still getting this problem after re-installing.
Command : flatpak run fr.easyeffects.ghb
error: app/fr.easyeffects.ghb/x86_64/master not installed
