### ISSUE TITLE
how to change or add the translation text to formal language

### ISSUE THREAD

**Issue by comsyspro** [moonlight-stream/moonlight-qt#1292]
**Is your feature request related to a problem? Please describe.**
in german we have formal language "per Sie". is it possible to add a separate language for formal german?

**Describe the solution you'd like**
either want to change the german translation to formal or add a second translation for formal german.

**Additional context**
in which files to change the language translation? how to add another option for formal german? is language compiled automatically?

**Comment by cgutman** [comment]
We use Weblate for translations. I don't know how localization works for different variants of the German language, but if there are special locale codes for that, it might be supported.

You can check there to see if there is an option for formal german: https://hosted.weblate.org/projects/moonlight/moonlight-qt/

**Comment by comsyspro** [comment]
at the moment there is no formal german and it has a mixture of non-formal and formal sentences. so i change all non-formal to formal expression. i don't know if the update is automated somehow by weblate or you can download it now.
