### ISSUE TITLE
Custom Resolutions not displaying correctly V6.0.0 MacOS

### ISSUE THREAD

**Issue by HankHill121** [moonlight-stream/moonlight-qt#1301]
**Describe the bug**
Custom Resolutions used on previous versions of Moonlight now give black bars when they previously filled the entire screen.
In version 5.0.1 and before I used the custom resolution of 2624x1696 and set the display mode to fullscreen which would display the image using my entire screen, including the notch area. In v5.0.1 If I set the display mode to borderless windowed then I would get black bars like in v6.0.0. Now in v6.0.0 I get black bars on the top and bottom of my screen no matter if its set to fullscreen or borderless windowed when using custom resolutions.

The resolution on the host pc is set to 2624x1696 on a virtual monitor.

**Steps to reproduce**
Just set the custom resolution and connect.

**Affected games**
Everything is affected.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?
 MacOS
**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
 Yes
- If so, which settings have been changed?
A custom resolution has been set and the display mode has been set to fullscreen
- Does the problem still occur after reverting settings back to default?
The problem doesn't occur when using the native res (3456x2234).

**Client PC details (please complete the following information)**
 - OS: MacOS Sonoma 14.5
 - Moonlight Version: v6.0.0
 - GPU: 16in M1 Macbook Pro Apple Silicon

**Server PC details (please complete the following information)**
 - OS: Windows 11 Version 10.0.22631 Build 22631
 - Sunshine or GeForce Experience version: Sunshine v0.23.1
 - GPU: RTX 3090 FE
 - GPU driver: 555.99

**Moonlight Logs (please attach)**
[Moonlight-1717687990.log](https://github.com/user-attachments/files/15646653/Moonlight-1717687990.log)

**Comment by TsaiTung-Chen** [comment]
Similar issue here. In the previous v5.0.1 version, the image looks blurry in borderless mode but clear in fullscreen mode. But now in the v6.0.0 version, they look the same; the image looks blurry in both borderless mode and fullscreen mode. So I temporarily switch back to the old v5.0.1 version.

BTW, I'm using [BetteryDisplay](https://github.com/waydabber/BetterDisplay) to apply a custom HiDPI which makes the UI look like 1680x945 on my 2560x1440 display.

**Comment by cgutman** [comment]
This build should resolve the issue: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/49983730/job/84mb5cv3d64jkg68/artifacts

For @TsaiTung-Chen, I'm unsure if yours will be resolved, because I'm not sure how exactly BetteryDisplay is working and whether it would interfere with native 2560x1440 rendering in applications. We've moved away from forcing display mode setting in macOS due to many reports of OS hangs, crashes, and other nasty things. In the case that your workflow depends on Moonlight actually forcing a display mode that overrides what BetteryDisplay is doing, you can set the `I_WANT_BUGGY_FULLSCREEN=1` environment variable using the new build to get the old pre-6.0 fullscreen behavior.

**Comment by TsaiTung-Chen** [comment]
> you can set the `I_WANT_BUGGY_FULLSCREEN=1` environment variable using the new build to get the old pre-6.0 fullscreen behavior.

I have added this environment variable to the info.plist in the Moonlight bundle, and it works well.

Thank you @cgutman 👍

**Comment by LetrixZ** [comment]
> This build should resolve the issue: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/49983730/job/84mb5cv3d64jkg68/artifacts
> 
> For @TsaiTung-Chen, I'm unsure if yours will be resolved, because I'm not sure how exactly BetteryDisplay is working and whether it would interfere with native 2560x1440 rendering in applications. We've moved away from forcing display mode setting in macOS due to many reports of OS hangs, crashes, and other nasty things. In the case that your workflow depends on Moonlight actually forcing a display mode that overrides what BetteryDisplay is doing, you can set the `I_WANT_BUGGY_FULLSCREEN=1` environment variable using the new build to get the old pre-6.0 fullscreen behavior.
> 
> Let me know if this resolves everything.

I can't download this. Tried with r2493 (latest build) and this environment variable but still have this issue.
