### ISSUE TITLE
Steam audio driver reverting to 16bits/48KHz on host at each new session

### ISSUE THREAD

**Issue by ftt-prod** [moonlight-stream/moonlight-qt#1307]
Host is on updated Windows 10, updated drivers and such.
Same for the client.
Moonlight is on last version (same issue with the previous one) & Sunshine is updated too.

Everytime I launch a session from the client (laptop) to the host (desktop), the host Steam audio drivers settings go back to 16bits & 48KHz.

If i switch to 32 bits & 196KHz on the host while streaming, it works ok, no dropout, bug or whatever but if i exit the moonlight session and reconnect again, the host settings swtich to the default (16bits 48KHz). 
Same behavior if i kill the session & start a new one.
Same behavior from different hosts & clients, reverts back to default at launch of a session.
Steam audio drivers are up to date, tried reinstalling from GitHub, reset settings etc... same behavior.

You'll tell me, what's the matter? 16bits & 48KHz are ok! Maybe, but i have an audiophile setup, a dedicated & audio treated cinema room, 5.1, you can hear the difference between 32bits/196KHz & 16bits/48KHz.

And also, I can do it and have the setup for, so why not? :)

Is it possible to lock the steam audio drivers settings? What exactly interacts with the driver settings? The launch command from Moonlight? A backend script from Sunshine?

Thanks!

**Comment by cgutman** [comment]
Please file this against Sunshine. Moonlight has no control over what audio settings are used on the host.

**Comment by cgutman** [comment]
We tell Sunshine how many channels the user wanted, but neither sample size nor sample rate are communicated and the configuration of the audio device is Sunshine's job. Moonlight has no clue what audio devices exist on the host and what configurations they may or may not support.
