### ISSUE TITLE
How could I install it on a Raspberry Pi with Ubuntu?

### ISSUE THREAD

**Issue by STBBRD** [moonlight-stream/moonlight-qt#1308]
I tried to install it with the instruction for Raspberry Pi OS. But it went wrong.

![image](https://github.com/moonlight-stream/moonlight-qt/assets/62409850/a728c907-e1ab-461d-b1db-86e15b41e6bc)

**Comment by cgutman** [comment]
We do not officially support Ubuntu on Raspberry Pi per our [system requirements](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4), so there are no Ubuntu packages available. We only provide official support for Raspberry Pi OS.

You can try to use one of the Bullseye or Bookworm packages on Ubuntu 22.04 and that may work, but no guarantees. To do so, modify the command as it mentions in that error output, adding `codename=bullseye` or `codename=bookworm`.
