### ISSUE TITLE
Moonlight 6.0.0. Setup - 0x80070643 - Fatal error during installation

### ISSUE THREAD

**Issue by rumplin** [moonlight-stream/moonlight-qt#1309]
**Describe the bug**
Trying to install Moonlight 6.0.0 I get 0x80070643 - Fatal error during installation

**Steps to reproduce**
Moonlight 5 tells me that there is a newer version of Moonlight.
Get on GitHub page, download installer MoonlightSetup-6.0.0.exe
Run it, follow through and get error:
0x80070643 - Fatal error during installation

**Screenshots**
![Screenshot 2024-06-08 154145](https://github.com/moonlight-stream/moonlight-qt/assets/35449956/04e5e0b6-58d5-4bfe-847d-99eaf1943b75)

**Client PC details (please complete the following information)**
 - OS: Windows 11 Pro 22H2
 - Moonlight Version: 5.0.1
 - GPU: CPU AMD Ryzen 7 PRO 6850U with Radeon Graphics 

**Moonlight Logs (please attach)**
[Moonlight_Game_Streaming_Client_20240608153841.log](https://github.com/user-attachments/files/15748236/Moonlight_Game_Streaming_Client_20240608153841.log)

**Comment by cgutman** [comment]
There should be an accompanying log called `Moonlight_Game_Streaming_Client_20240608153841_000_Moonlight_x64.log` that contains the details of the exact failure inside the Moonlight.msi package. Please upload that so I can take a look.

**Comment by rumplin** [comment]
Here is the Log file:
[Moonlight_Game_Streaming_Client_20240608153841_000_Moonlight_x64.log](https://github.com/user-attachments/files/15751172/Moonlight_Game_Streaming_Client_20240608153841_000_Moonlight_x64.log)

**Comment by rumplin** [comment]
Here is the Rollback Log file:
[Moonlight_Game_Streaming_Client_20240608153841_001_{33FE6E7B-2B3E-4B59-9F47-1B6C1E9953A6}_rollback.log](https://github.com/user-attachments/files/15751176/Moonlight_Game_Streaming_Client_20240608153841_001_.33FE6E7B-2B3E-4B59-9F47-1B6C1E9953A6._rollback.log)

**Comment by rumplin** [comment]
After reviewing the log files myself, I found this line:
```
DEBUG: Error 2911:  Could not remove the folder C:\Program Files\Moonlight Game Streaming\.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2911. The arguments are: C:\Program Files\Moonlight Game Streaming\, , 
```

Which looked like a permission issue.
So I started the installation with "Run as administrator" and now the installation completed OK.
We can close this ticket.
