### ISSUE TITLE
HDR not work on Ubuntu Desktop 24.04

### ISSUE THREAD

**Issue by comsyspro** [moonlight-stream/moonlight-qt#1310]
**Describe the bug**
In the description of new release moonlight-qt v6.0.0 it is mentioned that it supports HDR mode on Linux

> HDR is now supported on Steam Deck and other HDR-capable Linux systems using a new Vulkan-based renderer
> By default, the new Vulkan renderer is only used for HDR streaming, but it can be used all the time by setting the PREFER_VULKAN=1 environment variable

**Steps to reproduce**
I installed a fresh Ubuntu Desktop 24.04 on a workstation with Nvidia GTX 1080 and also on a Thinclient with Intel UHD 730 onboard graphics. I compiled the moonlight-qt v6.0.0 release on both systems with libplacebo-dev and also compiled the newest ffmpeg version in xorg and disabled wayland. On both systems the HDR mode is grayed out.

**Additional context**
Is it possible to use HDR (for SDR 10bit video encoding/decoding streams) on these systems? If not, why and on which Linux systems should it work? Could you explain and add more infos in the release or in the Build Setup Steps?

**Comment by cgutman** [comment]
>  it is mentioned that it supports HDR mode on Linux

It says "HDR-capable Linux systems" and that "HDR-capable" part is important. The HDR ecosystem on Linux is very early and unfinished, lacking standards for Wayland color management protocols, composition in wide color spaces, and more. Valve basically plumbed their own thing for Gamescope with both a WSI layer and compositor on the Steam Deck to solve the lack of standarization.

Unless you really plan to get deep into the weeds with it, I would not expect a full working HDR setup on anything other than Steam Deck out of the box. It can certainly be made to work with other distros, but you'll have to figure out how to put the pieces together for that yourself.
