### ISSUE TITLE
RPi: Recent logging changes (stdout to stderr) gives logs filled with v4l2 events.

### ISSUE THREAD

**Issue by Bobbar** [moonlight-stream/moonlight-qt#1315]
On my Raspberry Pi client I'm redirecting `stdout` to a log file whenever I launch moonlight for debugging and performance monitoring purposes.

My launch script resembles this:
`moonlight-qt > last_moonlight_log.log`

However with the recent changes in https://github.com/moonlight-stream/moonlight-qt/commit/02d867fe09605f23437301b2656711dbeb545c5b, I had to change it to redirect `stderr` instead: `moonlight-qt &> last_moonlight_log.log`

But now the log file includes a _huge_ amount of `v4l2` events like these:

```
v4l2_request_free_frame_priv
<<< v4l2_request_hevc_start_frame: 273
<<< v4l2_request_hevc_decode_slice
<<< v4l2_request_hevc_end_frame: 273
<<< frame_post_process
<<< alloc_frame
v4l2_request_free_frame_priv
<<< v4l2_request_hevc_start_frame: 274
<<< v4l2_request_hevc_decode_slice
<<< v4l2_request_hevc_end_frame: 274
<<< frame_post_process
<<< alloc_frame
v4l2_request_free_frame_priv
<<< v4l2_request_hevc_start_frame: 275
<<< v4l2_request_hevc_decode_slice
<<< v4l2_request_hevc_end_frame: 275
<<< frame_post_process
<<< alloc_frame
```

It appears to occur on every new frame, and my log file will quickly exceed 100MB, and there is also noticeable increase in hitches/dropped frames while logging is enabled. 

Is there something I'm doing incorrectly, or some way to silence these log messages?   Or perhaps even an alternate method to record moonlight logs?

Client:
Raspberry Pi 4  (6.1.19)

**Comment by cgutman** [comment]
These are from the FFmpeg updates that I pulled in from [upstream](https://github.com/jc-kynesim/rpi-ffmpeg). I'll patch them out in the next update.

**Comment by cgutman** [comment]
This was fixed in the package build repo in https://github.com/cgutman/moonlight-packaging/commit/5e91db44907f6a42e4bb56ddcafb62b35b20ed13
