### ISSUE TITLE
Gnome-Screensaver shows last frame of moonlight-qt

### ISSUE THREAD

**Issue by NoDiskNoFun** [moonlight-stream/moonlight-qt#132]
**Describe the bug**
Instead of autheticationscreens the screensaver shows the last frame of moonlight-qt. Login works anyway by blindly typing passwort
**Steps to reproduce**
start moonlight
play your favorite title
stop streaming and fully close moonlight-qt
lock screen
try unlocking screen

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
changed resolution to 1366x768 and bitrate to 2.5MBit/s
- Does the problem still occur after reverting settings back to default?
Yes

**Client PC details (please complete the following information)**
 - OS: Ubuntu 18.04
 - Moonlight Version: 0.6.2

**Logs (please attach)**
tk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
00:00:00 - Qt Warning: Qt: Session management error: None of the authentication protocols specified are supported
00:00:01 - SDL Info (0): Loading gamepad mappings from: /app/share/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt
00:00:01 - SDL Info (0): Loaded 110 new gamepad mappings
00:00:01 - Qt Debug: Current Moonlight version: "0.6.2"
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
00:00:01 - SDL Info (0): Initialized VAAPI 0.39
00:00:01 - SDL Info (0): Driver: Intel i965 driver for Intel(R) Sandybridge Mobile - 1.8.3
00:00:01 - SDL Info (0): Frame pacing in tear-free mode: target 60 Hz with 60 FPS stream
00:00:01 - SDL Info (0): Using VAAPI accelerated renderer on X11
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
00:00:01 - SDL Info (0): Initialized VAAPI 0.39
00:00:01 - SDL Info (0): Driver: Intel i965 driver for Intel(R) Sandybridge Mobile - 1.8.3
00:00:01 - SDL Info (0): Frame pacing in tear-free mode: target 60 Hz with 60 FPS stream
00:00:01 - SDL Info (0): Using VAAPI accelerated renderer on X11
00:00:01 - SDL Info (0): Using H.264 SPS fixup
00:00:01 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:01 - SDL Info (0): Loading gamepad mappings from: /app/share/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt
00:00:01 - SDL Info (0): Loaded 0 new gamepad mappings
00:00:01 - Qt Info: Loaded unique ID from settings: "4a02d134374398b6"
00:00:09 - Qt Warning: qrc:/gui/PcView.qml:13:1: QML PcView: StackView has detected conflicting anchors. Transitions may not execute properly.
00:00:09 - SDL Info (0): Loading gamepad mappings from: /app/share/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt
00:00:09 - SDL Info (0): Loaded 0 new gamepad mappings

**Comment by cgutman** [comment]
I've seen this too on my XPS 13 9370 running Fedora 29. I don't think it's Moonlight's fault though.

The display stack should be clearing the framebuffer of stale data upon termination or reuse (or gnome-screensaver should do it). Requiring the app itself to clear its own state would not work in cases where the app crashes or is killed by some administrative tool.

I don't know what is responsible for clearing the stale framebuffer data, but you can try filing a bug on Ubuntu and see if they can direct the issue properly.

**Comment by cgutman** [comment]
Closing this as it's not a Moonlight bug
