### ISSUE TITLE
Stream takes long time to display on Raspberry Pi 4 running Raspberry Pi OS Lite 64bit (Bookworm)

### ISSUE THREAD

**Issue by dvnkln** [moonlight-stream/moonlight-qt#1331]
**Description**
moonlight sometimes takes a pretty long time to even display the stream (the tv the pi is attached to just says "no signal" for some reason).

**Steps to reproduce**

- Fresh install of Raspberry Pi OS Lite 64bit (Bookworm) on a Raspberry Pi 4 B 8GB via Raspberry Pi Imager.

- Get the OS up-to-date:

```
sudo apt update
sudo apt upgrade
```

- Install moonlight-qt as described [here](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4).

- Run moonlight-qt normally (via `moonlight-qt,` pair your host (win 11 client running Sunshine in my case) and stream anything (i tried Steam Big Picture Mode).

Occasionally the stream will show quickly but most of the times it takes 1-3 minutes. The log 

**Other Moonlight clients**
Did a test with my android using the moonlight app to rule out the source of the problem and it was running just fine. The stream is displayed almost instantly.

**Moonlight settings**
Happened with default settings and after adjusting resolution, fps, bitrate and video encoding.

**Client PC details**
 - OS: Raspberry Pi OS Lite 64Bit (Bookworm)
 - Moonlight Version: 6.0.0
 - Linux package type (if applicable): apt package

**Server PC details (please complete the following information)**
 - OS: Windows 11 Pro 10.0.22631 Build 22631
 - Sunshine or GeForce Experience version: Sunshine v0.23.1
 - GPU: NVIDIA GeForce RTX 3070
 - GPU driver: Game Ready 555.99

**Moonlight Logs**
The attached logs show one of the quicker attempts. The root of the problem seem to be all those `buf caps insufficient`, `waiting for IDR frames` and `video decode unit queue overflow` message appearing repeatedly.
[moonlight.log](https://github.com/user-attachments/files/15914876/moonlight.log)

**Comment by mpendel** [comment]
For the same reason, I have not been able to get moonlight-qt v6.0 working on the rPi4. The differences in my set up are:
- Client rPi4 *4GB*
- Host GPU: Nvidia RTX 2060 
Otherwise, system versions and process is the same as in OP.

I've verified my network and host pc config by successfully streaming via moonlight-embedded on RetroPie on the rpi4, and separately by using moonlight on my steamlink.

I've also tried flashing bullseye 64b lite, installing following the instructions on the wiki, only to get the same results.

**Comment by Bobbar** [comment]
Are you launching from TTY console, or from the desktop?  If you are launching from desktop, Moonlight is only good for 1080p.

**Comment by mpendel** [comment]
Raspberry Pi OS Lite is without desktop

**Comment by Bobbar** [comment]
Ah, right, my bad! 

I'm curious about the `SDL Error (0): No connected displays found!` errors. That doesn't appear normal. 

Does it do the same thing with a different TV (and/or resolution)?

**Comment by cgutman** [comment]
Fixed by e76780e105c6def23d9e95faa35802049b13dfd5
