### ISSUE TITLE
Mac OS M3 AV1 Hardware Decoding

### ISSUE THREAD

**Issue by A-dvocate** [moonlight-stream/moonlight-qt#1333]
AV1 Software decoding only available for Mac OS.

Since the M3 Macbook Pro supports hardware decoding, it would be a great addition to utilize the dedicated hardware saving latency.

**Comment by kode54** [comment]
This was closed as completed, but it was never completed.

**Comment by mamoun90** [comment]
I hope this will be resolved soon!

**Comment by rowbawts** [comment]
+1

**Comment by mamoun90** [comment]
This is a custom build which links against [jellyfin-ffmpeg](https://github.com/jellyfin/jellyfin-ffmpeg) which already enabled AV1 hardware decoding for M3/M4 series
https://github.com/gnattu/moonlight-qt/releases/tag/jellyfin-ffmpeg

**Comment by mausfield** [comment]
Is there any update on this?

**Comment by cgutman** [comment]
Duplicate of #1125
