### ISSUE TITLE
(Arch Linux) moonlight-qt no longer opens, crashes immediately

### ISSUE THREAD

**Issue by sharkeylaser** [moonlight-stream/moonlight-qt#1341]
**READ ME FIRST!**
If you're here because something basic is not working (like gamepad input, video, or similar), it's probably something specific to your setup, so make sure you've gone through the Troubleshooting Guide first: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

If you still have trouble with basic functionality after following the guide, join our Discord server where there are many other volunteers who can help (or direct you back here if it looks like a Moonlight bug after all). https://moonlight-stream.org/discord

**Describe the bug**
moonlight-qt crashes immediately, does not open.

**Steps to reproduce**
Attempt to run moonlight either via icon or terminal.

**Screenshots**
N/A
**Affected games**
N/A

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?
Not a clue.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? No
- If so, which settings have been changed? N/A
- Does the problem still occur after reverting settings back to default? Yes / N/A

**Gamepad-related issues (please complete if problem is gamepad-related)**
N/A

**Client PC details (please complete the following information)**
 - OS: Arch Linux
 - Moonlight Version: Latest? Unsure. Can't open to find out
 - GPU: Intel HD Graphics 4000
 - Linux package type (if applicable): Installed via aur

**Server PC details (please complete the following information)**
Not relevant

**Moonlight Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux with the Flatpak, logs print to the terminal when running with the command: `flatpak run com.moonlight_stream.Moonlight`
- On Linux with the Snap, logs print to the terminal when running with the command: `moonlight`
00:00:00 - SDL Info (0): Compiled with SDL 2.30.3
00:00:00 - SDL Info (0): Running with SDL 2.30.3
00:00:00 - Qt Info: No translation available for "en_US"
00:00:00 - Qt Warning: QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
00:00:00 - Qt Warning: qrc:/gui/main.qml:13:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/home/patrick/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 322 new gamepad mappings
00:00:00 - SDL Info (0): V-sync disabled
00:00:00 - SDL Info (0): Initialized VAAPI 1.21
00:00:00 - SDL Info (0): Driver: Intel i965 driver for Intel(R) Ivybridge Mobile - 2.4.1
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Format 0x32315659 -> yuv420p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Format 0x30323449 -> yuv420p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Format 0x3231564e -> nv12.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Format 0x32595559 -> yuyv422.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Format 0x59565955 -> uyvy422.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Format 0x48323234 -> yuv422p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Format 0x58424752 -> rgb0.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Format 0x58524742 -> bgr0.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Format 0x30313050 -> p010le.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] VAAPI driver: Intel i965 driver for Intel(R) Ivybridge Mobile - 2.4.1.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7270e002b900] Driver not found in known nonstandard list, using standard behaviour.
00:00:00 - SDL Info (0): Selected overlay subpicture format: BGRA8888
/usr/include/c++/14.1.1/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = VkPhysicalDevice_T*; _Alloc = std::allocator<VkPhysicalDevice_T*>; reference = VkPhysicalDevice_T*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    6470 IOT instruction (core dumped)  moonlight

**Additional context**
Anything else you think may be relevant to the issue
Happened today. Worked just fine yesterday.

**Comment by CityofSirtel** [comment]
I had the exact same problem earlier today with moonlight-qt and moonlight-qt-bin, worked fine with moonlight-qt-git in the aur

**Comment by cgutman** [comment]
Fixed by bd60b873ec81cde11a65c62160a7f31252b0e89b
