### ISSUE TITLE
Vulkan Renderer using VK_KHR_video_decode_h264 and VK_KHR_video_decode_h265

### ISSUE THREAD

**Issue by KWottrich** [moonlight-stream/moonlight-qt#1342]
**Is your feature request related to a problem? Please describe.**
Moonlight and Sunshine do not support 4:4:4 chroma subsampling, which is partly due to poor hardware support for 4:4:4 decoding. The Vulkan extensions for video decoding (`VK_KHR_video_decode_h264` and `VK_KHR_video_decode_h265`) do support 4:4:4 decoding, meaning that a Vulkan renderer supporting `VK_VIDEO_CHROMA_SUBSAMPLING_444_BIT_KHR` would open the door for hardware-accelerated 4:4:4 subsample decoding support for any device whose driver supports the corresponding Vulkan extensions.

**Describe the solution you'd like**

- Add a Vulkan renderer with support for `VK_KHR_video_decode_h264` and `VK_KHR_video_decode_h265` alongside DXVA2 and D3D11VA on Windows.
- Add a Vulkan renderer with support for `VK_KHR_video_decode_h264` and `VK_KHR_video_decode_h265` alongside VAAPI, VDPAU, and NVDEC on Linux.
- (_MacOS does not support Vulkan directly, and MoltenVK does not appear to support `VK_KHR_video_decode_h264` or `VK_KHR_video_decode_h265`_)

**Describe alternatives you've considered**
The only other game streaming solution with support for 4:4:4 chroma subsampling is a premium subscription for Parsec Warp.

**Additional context**
Discussion about hardware support limitations for hardware encoding/decoding video streams with 4:4:4 subsampling on the Sunshine GitHub page: https://github.com/LizardByte/Sunshine/discussions/1188

**Comment by cgutman** [comment]
There is already a [Vulkan renderer](https://github.com/moonlight-stream/moonlight-qt/blob/master/app/streaming/video/ffmpeg-renderers/plvk.cpp) that supports `VK_KHR_video_decode_h264`, `VK_KHR_video_decode_hevc`, and `VK_KHR_video_decode_av1` in Moonlight v6.0.0. It is shipping for Linux in v6.0 but will also ship for Windows in v6.1 for YUV 4:4:4. See also #1282
