### ISSUE TITLE
Uncap the bitrate from 150mbps

### ISSUE THREAD

**Issue by darkalfx** [moonlight-stream/moonlight-qt#1343]
My home network is on 10GB fiber and I want to play 4k@120hz but the 150mbps is not acceptable for this.

I'm using Sunshine and have no need for articifial bitrate caps like this, please allow me to input whatever bitrate I deem necessary.

Thank you for considering.

**Comment by Decbuan** [comment]
agree！

**Comment by PlayXboxtion963** [comment]
I agree with you. 
I had compile a version that improves bitrate upper limit to 1000Mbps which only need modify UI seekbar.....So that is UI limit instead of back end limit

**Comment by WinkelCode** [comment]
You don't have to necessarily compile a custom version, on macOS (and most likely Windows), you can set a custom value by editing the configuration\*. The caveat is that the value is reset to the highest "allowed" when the settings are opened. You should also check with a bandwidth monitoring tool (the built in Windows ones should work, Resource Monitor, Task Manager) to see what bandwidth is actually used, make sure to play/view something with plenty of motion.

\*It's actually really easy on macOS: https://github.com/moonlight-stream/moonlight-qt/issues/1375#issuecomment-2294548689
