### ISSUE TITLE
Can I wake up a Wake-On-LAN enabled PC using this project?

### ISSUE THREAD

**Issue by jerry-yuan** [moonlight-stream/moonlight-qt#135]
I have successfully wake up the pc using an Android WOL client, but failed with moonlight by right click the icon of that pc and choose wake pc. I found there was no options for WOL in moonlight's settings, does it work if it based on the WOL.
if it doesn't base WOL could anybody tell me how to make it work.

**Comment by cgutman** [comment]
Yes, it uses Wake-on-LAN to all known addresses and 255.255.255.255 on ports 7, 9, 47998, 47999, and 48000.

Are you testing this within the same network?

**Comment by njibhu** [comment]
I am on Archlinuxm latest git version with the AUR package moonlight-qt-git, using the wol utility works but not when using the Wake On Lan utility.
Using Wireshark to inspect networks reveal that no packet was sent and Moonlight doesn't log anything.
Is my system missing some libraries used for the Wake On Lan feature ?

**Comment by cgutman** [comment]
@njibhu can you run moonlight from the terminal and attach the log after attempting to wake?

**Comment by njibhu** [comment]
There is no output specific to wake on lan ..
`00:00:00 - SDL Info (0): Loading gamepad mappings from: /usr/share/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt
00:00:00 - SDL Info (0): Loaded 14 new gamepad mappings
00:00:00 - Qt Debug: Current Moonlight version: "0.8.0"
00:00:00 - SDL Info (0): V-sync enabled
00:00:00 - SDL Info (0): Initialized VAAPI 1.3
00:00:00 - SDL Info (0): Driver: Mesa Gallium driver 18.3.1 for AMD ARUBA (DRM 2.50.0 / 4.19.12-arch1-1-ARCH, LLVM 7.0.0)
00:00:00 - SDL Warn (0): Avoiding VAAPI on AMD driver
00:00:00 - SDL Info (0): Driver: G3DVL VDPAU Driver Shared Library version 1.0
00:00:00 - SDL Info (0): Frame pacing disabled: target 60 Hz with 60 FPS stream
00:00:00 - SDL Info (0): Using VDPAU accelerated renderer
00:00:00 - SDL Info (0): Driver: G3DVL VDPAU Driver Shared Library version 1.0
00:00:00 - SDL Info (0): Frame pacing disabled: target 60 Hz with 60 FPS stream
00:00:00 - SDL Info (0): Using VDPAU accelerated renderer
00:00:00 - SDL Info (0): Using H.264 SPS fixup
00:00:00 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:00 - SDL Info (0): Loading gamepad mappings from: /usr/share/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt
00:00:00 - SDL Info (0): Loaded 0 new gamepad mappings
00:00:11 - Qt Info: "DESKTOP-*******" is now offline
`
I did wait for the computer to be recognized as offline before trying to use the wake on lan feature.

**Comment by cgutman** [comment]
You don't see output like:
```
Send WoL packet to WIN81-GS via 192.168.35.130:7
Send WoL packet to WIN81-GS via 192.168.35.130:9
Send WoL packet to WIN81-GS via 192.168.35.130:47998
Send WoL packet to WIN81-GS via 192.168.35.130:47999
Send WoL packet to WIN81-GS via 192.168.35.130:48000
Send WoL packet to WIN81-GS via 255.255.255.255:7
Send WoL packet to WIN81-GS via 255.255.255.255:9
Send WoL packet to WIN81-GS via 255.255.255.255:47998
Send WoL packet to WIN81-GS via 255.255.255.255:47999
Send WoL packet to WIN81-GS via 255.255.255.255:48000
```

**Comment by cgutman** [comment]
@njibhu can you try the latest source? You should get an error message now if it can't bind or send the packet.

**Comment by njibhu** [comment]
Result is:
00:00:11 - Qt Warning: Bind failed: QAbstractSocket::SocketAccessError
00:00:11 - Qt Warning: Bind failed: QAbstractSocket::SocketAccessError
00:00:11 - Qt Warning: Bind failed: QAbstractSocket::SocketAccessError
