### ISSUE TITLE
AppImage crashes immediately (core dump) when trying to use eglfs

### ISSUE THREAD

**Issue by gschintgen** [moonlight-stream/moonlight-qt#1352]
**Describe the bug**

Moonlight-qt fails immediately on Ubuntu 22.04 server with this crash:
```
$ Downloads/Moonlight-6.0.1-x86_64.AppImage -platform eglfs
00:00:00 - Qt Info: Unable to detect Wayland or X11, so EGLFS will be used by default. Set QT_QPA_PLATFORM to override this.
00:00:00 - Qt Info: Setting display mode by default. Set QT_QPA_EGLFS_ALWAYS_SET_MODE=0 to override this.
00:00:00 - Qt Warning: Could not find the Qt platform plugin "eglfs" in ""
00:00:00 - Qt Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

On the same system the snap version has been working fine, but now the 10-bit option (experimental HDR) is grayed out, maybe due to the automatic upgrade to 6.0.x done by snapd, and I'd like to try out 5.0.1 again. (I'm fairly sure that 10-bit HEVC SDR was working fine before, but it may have been on another client device.). Since the snap version can't be downgraded I want to migrate to a package format that is not managed automatically.

Is the AppImage compiled without eglfs support? Or is my system missing a dependency?

(But in any case it should terminate gracefully.)

**Steps to reproduce**
download the AppImage and try to run it.

**Moonlight settings (please complete the following information)**
Moonlight doesn't even start, but I do have to start it with `-platform eglfs` since no desktop environment is installed.

**Client PC details (please complete the following information)**
 - OS: Ubuntu 22.04
 - Moonlight Version: 6.0.1
 - GPU:  Intel® HD Graphics 630
 - Linux package type (if applicable): AppImage

**Server PC details (please complete the following information)**
 - OS: Ubuntu 22.04
 - Sunshine or GeForce Experience version: Sunshine (git master)
 - GPU: AMD Radeon RX 6650 XT
 - GPU driver: mesa 23.2.1

**Moonlight Logs (please attach)**
logs are posted above

**Comment by gschintgen** [comment]
If I understand the comment below correctly, eglfs not working with the AppImage packages is a known limitation:
https://github.com/moonlight-stream/moonlight-qt/blob/d5a198b764b1dc379f844c1ecc85daf079d63dd9/scripts/build-appimage.sh#L36

**Comment by cgutman** [comment]
Yep that's correct. EGLFS is not supported by the AppImage.

Loss of the HDR toggle likely means there's something wrong with the dependencies of the Snap that leads to Vulkan and the KMSDRM renderer being unusable. You should file a bug on the Snap package for that: https://github.com/maxiberta/moonlight-snap

As for the segfault, that is Qt internally calling `abort()` when it can't find a working platform plugin. Qt could terminate gracefully in that case, but that's a Qt issue/improvement not something we can handle downstream in Moonlight.
