### ISSUE TITLE
I want to make close moonlight window when sunshine process is killed.

### ISSUE THREAD

**Issue by Kobain-Seo** [moonlight-stream/moonlight-qt#1359]
Hi. 

When I quit sunshine from tray, the window of moonlight is closed immediately, but when i kill the process of sunshine, it hangs for about 10 seconds. I want to reduce time to close. What value should I adjust from the source?

Thank you.

**Comment by cgutman** [comment]
I suggest not forcefully terminating Sunshine by killing the process. As you see, it's not able to tell the client it's quitting and so the client waits for it to respond for several seconds before giving up and closing the connection.

If you're looking for scriptable ways to terminate Sunshine safely, I suggest you stop the Sunshine Service instead. You can accomplish this by running `net stop sunshineservice`.

**Comment by Kobain-Seo** [comment]
@cgutman 
I understand, but I am currently using wgc method so it is not possible to quit sunshine via service command. When I shutdown the host, moonlight freezes(it is not freezing, just waiting response) for 10 seconds. So I am trying to adjust timeout value to disconnect smoothly.

**Comment by cgutman** [comment]
I think this was fixed in Sunshine by https://github.com/LizardByte/Sunshine/commit/4fd6c66edb9eac295315a950ac8e734ddac91008
