### ISSUE TITLE
add shortcut to minimize or close the game on mac

### ISSUE THREAD

**Issue by rendiga** [moonlight-stream/moonlight-qt#136]
Shortcut in mac just to close the session. not close the game or minimize it. so I need to reopen moonlight to quit the game after pressing control+alt+shift+q
If I didn't quit game from moonlight game list. my computer sound doesn't working because it still emulate to moonlight.
If I forgot to quit the game from moonlight game list. I need to restart my computer, so it will stop the emulate.

**Comment by cgutman** [comment]
This was a bug in v0.6.3 where Moonlight would crash when you pressed Ctrl+Alt+Shift+Q. On other versions, including the latest build, that key combo will return you to the app list where you can quit the game by right clicking on it like normal.
