### ISSUE TITLE
xml error 4 not well-formed (invalid token)

### ISSUE THREAD

**Issue by zl1234aaa** [moonlight-stream/moonlight-qt#1365]
Hello i have installed the sunshine app, it's running OK.There is no problem when i use the phone to connect pc.I have installed zerotierone.When i place my ip  on my LG TV moonlight client it gives me the return "xml error 4 not well-formed (invalid token)", if i tried my public internet ip it gives me timeout, my ethernet is private, firewall is disable, windows is configured with all ports, i don't know what i can do, can anybody help ?

**Comment by cgutman** [comment]
For the LG TV Moonlight client project, you should file issues here: https://github.com/mariotaku/moonlight-tv
