### ISSUE TITLE
problem building moonlight-qt

### ISSUE THREAD

**Issue by levan89** [moonlight-stream/moonlight-qt#137]
i have problem when building project moonlight-qt
\moonlight-qt\libs\windows\include\NktHookLib.h:77: error
![default](https://user-images.githubusercontent.com/20702547/48856592-3ef4a100-edd0-11e8-83b6-5663f4d7bc92.PNG)
: 'DWORD CNktHookLib::RemoteHook(int)' cannot be overloaded
   DWORD RemoteHook(__out SIZE_T *lpnHookId, __out LPVOID *lplpCallOriginal, __in HANDLE hProcess,
         ^

**Comment by cgutman** [comment]
Are you building with MinGW instead of MSVC?

**Comment by levan89** [comment]
yes use MinGW

**Comment by cgutman** [comment]
Ok, the included libraries and headers are only compatible with MSVC, so you should install Visual Studio 2017, then add Qt 5.11.2 MSVC using the Qt Maintenance tool, then it should build if you select the MSVC toolchain.

**Comment by levan89** [comment]
this is bad i can not install Visual Studio 2017

**Comment by cgutman** [comment]
Why not?

**Comment by levan89** [comment]
in Visual Studio 2017 same problem 
appmodel.cpp
sdlgamepadkeynavigation.cpp
‘®§¤ ­ЁҐ Є®¤ ...
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.EXE" : return code "0x2"
Stop.
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe" : return code "0x2"
Stop.
NMAKE : fatal error U1077: cd : return code "0x2"
Stop.
21:36:45: Процесс «C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe» exit with code 2.
Ошибка при сборке/установке проекта moonlight-qt (комплект: Desktop Qt 5.9.7 MSVC2017 64bit)
Комплект Desktop Qt 5.9.7 MSVC2017 64bit имеет недостатки в конфигурации, которые могут быть источниками данной проблемы.
Во время выполнения этапа «Сборка»

**Comment by cgutman** [comment]
Where are the actual compilation errors? This just shows the exit codes

**Comment by levan89** [comment]
i found my error and fix it
thanks for helping
