### ISSUE TITLE
MacOS Sequoia Beta 4 causes SecPKCS12 Import error

### ISSUE THREAD

**Issue by markraub** [moonlight-stream/moonlight-qt#1373]
**Describe the bug**
This is probably a _very_ niche issue that I'm experiencing being a sequoia beta user, but whatever change they made might get pushed through to release, which could ultimately break moonlight for all macos users that upgrade.
When I updated from Beta 3 to Beta 4, after having made no changes to Moonlight myself, moonlight can no longer connect to any of my hosts and throws the following error:
`SecPKCS12Import failed: -25300 (Error 99)`

**Steps to reproduce**
Install macos Sequoia Beta 4
Install Moonlight
Configure host
Connect to host

**Screenshots**
<img width="351" alt="Screenshot 2024-07-30 at 8 09 17 AM" src="https://github.com/user-attachments/assets/eaa4a0db-6f58-41e7-ae97-43e312e641de">

**Moonlight settings (please complete the following information)**
Just resolution custom set to 1920x1200. Encoders are all set to auto, HDR disabled. 

**Client PC details (please complete the following information)**
 - OS: MacOS Sequoia Beta 4
 - Moonlight Version: 6.0.1
 - GPU: M3 Pro

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - Sunshine or GeForce Experience version: v0.23.1
 - GPU: RTX 2080 Ti

**Moonlight Logs (please attach)**
[Moonlight-1722352398.log](https://github.com/user-attachments/files/16430052/Moonlight-1722352398.log)

**Comment by Juhao73692** [comment]
see https://github.com/moonlight-stream/moonlight-qt/issues/1355
