### ISSUE TITLE
Diagonal tearing with 1440p on Intel HD 4000 GPU

### ISSUE THREAD

**Issue by donbonjorno** [moonlight-stream/moonlight-qt#1381]
Hello i expirience dioganal tearing with 6.0.1, and horizontal with 6.0.0 in win10x64 with sunshine. Both gpus are intel, hd630 for sunshine with default profile and hd 4000 as player. I havent tried diferent gpus yet. Everything is fine if i go with 1080p resolution.  androd is fine.
![изображение_2024-08-04_144356192](https://github.com/user-attachments/assets/4671095d-d739-417c-bde5-eee50d7d6ec8)
![Screenshot_4](https://github.com/user-attachments/assets/2e251fe0-0cd1-4b6e-b97d-7008a0f8faa2)

Going back do 5.0.1.

**Comment by mbilker** [comment]
I experience a very similar kind of tearing on my client that has an Intel HD Graphics 4000 with the tearing being horizontal then diagonal in the middle and then moving back to horizontal. I am going back to 5.0.1 to use D3D9 and DXVA2.
