### ISSUE TITLE
Bitrate setting is not saved when YUV 4:4:4 is enabled

### ISSUE THREAD

**Issue by KWottrich** [moonlight-stream/moonlight-qt#1387]
**Describe the bug**
When using a build of the client that has YUV 4:4:4 enabled, going into the settings and changing the Video bitrate setting doesn't do anything. Dragging the slider and then closing and reopening settings resets the slider right back to the default for the resolution/FPS. In my case, that's 65 Mbps for 1920x1200@120 FPS. Disabling YUV 4:4:4 makes this issue go away

**Steps to reproduce**
Build from the latest master branch, with the changes merged in https://github.com/moonlight-stream/moonlight-qt/pull/1282. Enable "Enable YUV 4:4:4 (Experimental)" under Advanced Settings. Attempt to adjust video bitrate.

**Screenshots**
![image](https://github.com/user-attachments/assets/583e4521-86c9-4e5d-83f2-38f0a77ad6b1)
![image](https://github.com/user-attachments/assets/0aaf23d8-4c52-43fa-b7cd-13b657305fc6)

**Affected games**
N/A

**Other Moonlight clients**
N/A

**Moonlight settings (please complete the following information)**
- Enable YUV 4:4:4
- Adjusting Resolution/FPS/Video bitrate

**Gamepad-related issues (please complete if problem is gamepad-related)**
N/A

**Client PC details (please complete the following information)**
 - OS: Windows 11 23H2 (Build 22631.3880)
 - Moonlight Version: da0244c5387cab3ccd682d8de24085720d6f6501
 - GPU: NVidia Laptop 3050 Ti

**Server PC details (please complete the following information)**
 - OS: Windows 11 23H2 (Build 22631.3880)
 - Sunshine or GeForce Experience version: Sunshine appveyor build from https://github.com/LizardByte/Sunshine/pull/2533
 - GPU: NVidia RTX 3070

**Moonlight Logs (please attach)**
[Moonlight-1723551292.log](https://github.com/user-attachments/files/16599553/Moonlight-1723551292.log)

**Additional context**
https://github.com/moonlight-stream/moonlight-qt/pull/1282

**Comment by ns6089** [comment]
I will have a look.

**Comment by ns6089** [comment]
The value *is* getting saved, but the slider is reset to default when the options page reopened.
Will open PR with a fix shortly.

**Comment by ns6089** [comment]
Ready.
