### ISSUE TITLE
Has anyone actually gotten the QT Mac client to work remotely?

### ISSUE THREAD

**Issue by minnux** [moonlight-stream/moonlight-qt#141]
I never had an issue with the Chrome extension on Mac OS when connecting to my Windows gaming PC over the internet. After recently installing the QT client on mac as the chrome extension was deprecated whenever I try to add my remote PC's IP address I just get "Unable to connect to the specified PC." The message is instant. Keep in mind I have no problem connecting via the Android client with my phone over a mobile network. I have no idea where a log would be that I can submit either. This is with the latest Moonlight-0.6.4.dmg. UPnP is on on my router, and the streaming and testing tools have both been ran successfully on the host PC. I've tried connecting with and without port forwarding set tup on the router. Any clues? Or has anyone successfully done this this?

**Comment by cgutman** [comment]
I do it all the time. Please upload the log from the `/tmp` folder on your Mac like the issue template says.

**Comment by minnux** [comment]
Ok found the log, I tried adding the PC with both my DNS address and my numerical IP:

00:00:00 - SDL Info (0): Loading gamepad mappings from: /Applications/Moonlight.app/Contents/Resources/gamecontrollerdb.txt
00:00:00 - SDL Info (0): Loaded 34 new gamepad mappings
00:00:00 - Qt Debug: Current Moonlight version: "0.6.4"
00:00:00 - Qt Warning: Error receiving trust for a CA certificate
00:00:00 - Qt Warning: Error receiving trust for a CA certificate
00:00:00 - Qt Warning: Error receiving trust for a CA certificate
00:00:00 - Qt Warning: Error receiving trust for a CA certificate
00:00:00 - Qt Warning: Error receiving trust for a CA certificate
00:00:00 - Qt Warning: mDNS is disabled by user preference
00:00:01 - SDL Warn (0): Assuming H.264 HW decode on < macOS 10.13
00:00:01 - SDL Info (0): Frame pacing in tear-free mode: target 60 Hz with 60 FPS stream
00:00:01 - SDL Info (0): NSWindow on display: 4248824
00:00:01 - SDL Info (0): Using VideoToolbox accelerated renderer
00:00:01 - SDL Info (0): Using H.264 SPS fixup
00:00:01 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:01 - SDL Info (0): Loading gamepad mappings from: /Applications/Moonlight.app/Contents/Resources/gamecontrollerdb.txt
00:00:01 - SDL Info (0): Loaded 0 new gamepad mappings
00:00:01 - Qt Debug: Found update manifest match for current platform
00:00:01 - Qt Debug: Latest version of Moonlight for this platform is: "0.6.4"
00:00:01 - Qt Debug: Update manifest version equal to current version
00:01:28 - Qt Info: Processing new PC at "marla.asuscomm.com" from user
00:01:28 - Qt Info: Loaded unique ID from settings: "be3c027a5afb9e7a"
00:01:28 - Qt Info: Executing request: "https://marla.asuscomm.com:47984/serverinfo?uniqueid=be3c027a5afb9e7a&uuid=c00b4f0f4ae1410ba777b75d340bde8d"
00:01:28 - Qt Warning: "serverinfo"  request failed with error  QNetworkReply::NetworkError(SslHandshakeFailedError)
00:01:43 - Qt Info: Processing new PC at "70.113.146.241" from user
00:01:43 - Qt Info: Executing request: "https://70.113.146.241:47984/serverinfo?uniqueid=be3c027a5afb9e7a&uuid=5178f50adca24da283f4c9e1effbbb5d"
00:01:43 - Qt Warning: "serverinfo"  request failed with error  QNetworkReply::NetworkError(SslHandshakeFailedError)

**Comment by cgutman** [comment]
`Qt Warning: Error receiving trust for a CA certificate` is unexpected.

What version of macOS are you running?

**Comment by cgutman** [comment]
We sorted this out on Discord. It seems to be something specific to this machine. It may be related to an outdated macOS version.
