### ISSUE TITLE
Monitor keeps disconnecting and reconnecting when mouse hovers over Moonlight GUI elements and found invalid memory access popup while streaming video

### ISSUE THREAD

**Issue by humdogm** [moonlight-stream/moonlight-qt#1420]
**Describe the bug**

Recently updated moonlight from 6.0.1.0 to 6.1.0.0 on Windows, now main monitor continuously loses connection and reconnects every few seconds when Moonlight system picker and application picker is the foreground window.

I have 2 monitors, only my primary 144hz 1440p monitor disconnects, my 60hz 1080p secondary monitor stays fine. Both monitors are connected through a dock, primary one over USB type C cable, and secondary one over HDMI. Dock is connected to a laptop over a USB type C Displayport 1.2 alt-mode.

When I move the moonlight window to my secondary monitor, my primary monitor stops disconnecting. But when I move it back, my primary monitor sometimes immediately starts disconnecting and reconnecting again, or other times it will take a little while and then start disconnecting.

When the moonlight system picker and application picker are a background window, the disconnects do not happen either.

However, if I am eventually able to start streaming video from my other system with Moonlight, by moving the mouse in between the flashing of the screen, the streaming Windows does not cause my monitor to disconnect.

Also, while I was streaming video after awhile I saw a crash pop up essentially saying that there was an invalid memory access to memory address 0xFFFFFFFFFFFFFFFF. The crash created an empty dump file in %TEMP%

**Steps to reproduce**
Any special steps that are required for the bug to appear.

- Open Moonlight from start menu.
- Monitor starts disconnecting immediately after moonlight window opens.

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

Video attached below
https://github.com/user-attachments/assets/9ebdf213-2701-46a2-9b2c-e2f97a93cb9a

**Affected games**
List the games you've tried that exhibit the issue. To see if the issue is game-specific, try streaming Steam Big Picture with Moonlight and see if the issue persists there.

N/A, not related to gameplay

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?
Not on android

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
-- Yes
- If so, which settings have been changed?
-- Hard to say, not sure which settings I configured in the past
- Does the problem still occur after reverting settings back to default?
-- If I uncheck every checkbox, set every dropdown to recommended, when I restart Moonlight the primary monitor starts spazzing out again

**Client PC details (please complete the following information)**

 - OS: Windows 10 22H2
 - Moonlight Version: 6.1.0
 - GPU: RTX 2060 and AMD Radeon Integrated Graphics (Laptop)
 - Linux package type (if applicable): N/A

**Server PC details (please complete the following information)**

Not important but:
 - OS: Windows 11 23H2
 - Sunshine or GeForce Experience version: Sunshine v0.23.1
 - GPU: Radeon RX 7800XT
 - GPU driver: 24.7.1

**Moonlight Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.

[Moonlight-1726971619.log](https://github.com/user-attachments/files/17088026/Moonlight-1726971619.log)

**Comment by humdogm** [comment]
Update: seems like this happens when my mouse hovers over or clicks elements in the Moonlight GUI

But it still only happens when Moonlight is the focused foreground window, when the Moonlight window is unfocused it doesn't cause this issue. So it makes sense that this doesn't happen when Moonlight is a background window either because the mouse cannot hover over Moonlight's GUI elements.

So I  guess I can reliably recreate this issue now.

**Comment by sephirothmk** [comment]
Same thing started happening to me just now on v6.1.0. Moonlight was working fine, then I upgraded my monitor to an OLED Asus XG27AQDMG and the monitor now disconnects every time I hover the Moonlight interface with my mouse. If I start a game, everything is okay.

Setup was - v6.1.0 -> GeForce 1030 -> DP -> Dell U2722DE -> DP Daisychain -> MSI Gaming monitor (set to primary in windows) = Worked fine

Setup is now- v6.1.0 -> GeForce 1030 -> DP -> Dell U2722DE -> DP Daisychain -> Asus OLED XG27AQDMG (set to primary in windows) = Asus monitor switches on/off constantly if Moonlight is in foreground
