### ISSUE TITLE
Amd 5650m don't support hardware decoder?

### ISSUE THREAD

**Issue by HighPingTek** [moonlight-stream/moonlight-qt#143]
Host pc gtx 970 with latest GFE build
Client pc amd 5650m with latest catalyst driver
windows 10 1803 on both
moonlight PC v0.7.0 installer

client pc settings
https://imgur.com/a/ffRMafb

problem in video
https://streamable.com/f5tpj

log
[Moonlight-1544385077.log](https://github.com/moonlight-stream/moonlight-qt/files/2663226/Moonlight-1544385077.log)

**Comment by cgutman** [comment]
Please include the requested information from the bug report template. https://github.com/moonlight-stream/moonlight-qt/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by HighPingTek** [comment]
> Please include the requested information from the bug report template. https://github.com/moonlight-stream/moonlight-qt/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

done

**Comment by cgutman** [comment]
Still missing logs

**Comment by HighPingTek** [comment]
> Still missing logs

[Moonlight-1544385077.log](https://github.com/moonlight-stream/moonlight-qt/files/2660953/Moonlight-1544385077.log)

**Comment by HighPingTek** [comment]
> Still missing logs

some idea?

**Comment by cgutman** [comment]
Not at the moment. It appears that your GPU supports H.264 decoding, but attempts to actually render something causes the GPU driver to return E_FAIL.

**Comment by cgutman** [comment]
I may have fixed this with this change here: https://github.com/moonlight-stream/moonlight-qt/commit/86874489663721c8256df643f576a8ce627a1ba9

Please confirm by testing this build: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/21957323/job/81k8tid7dlcp3b4g/artifacts

You should use the portable version to avoid breaking your existing installation, but you can delete portable.dat in the extracted folder to let it us your existing settings and pairing.

**Comment by HighPingTek** [comment]
Perfect, it works
