### ISSUE TITLE
Autostart session / app via gui or cmdline

### ISSUE THREAD

**Issue by zackfuchtel** [moonlight-stream/moonlight-qt#1431]
I am starting moonlight also as "thinclient" in .bash.rc via 

`[[ $(tty) == '/dev/tty1' ]] && SDL_AUDIODRIVER=alsa /usr/bin/moonlight-qt >/tmp/moon.log 2>&1`

Please implement a way to autostart a session/app via gui or cmdline to connect to client without user interaction.

Thanks

**Comment by jorys-paulin** [comment]
That's already the case, try `moonlight-qt --help`
