### ISSUE TITLE
Proxy blocking connection

### ISSUE THREAD

**Issue by easly1989** [moonlight-stream/moonlight-qt#144]
Hello there,
I wanted to try and connect from my workplace to my home pc and play while i have "dead-times" during work.

But here at work we can access internet only going through a proxy (a strict one)
we use a .pac file, but to use things like git or nuget i simply did the authentication for the proxy and was able to use them without restrictions.

With moonlight I'm not prompted to insert my auth data, and thus when i try to connect to my home PC it gives the **Unable to connect to the specified PC**

Can I do something about it?
Is it a bug or a planned feature?

Thank you for the great work, keep it up (:

--- EDIT
To be sure that everything was working on my home PC i tried connecting to it using my phone and the android moonlight app (using 4g instead of the work wifi)
And it worked smoothly, so the problem is, for sure, the proxy auth

**Comment by cgutman** [comment]
I don't think this is fixable. An HTTP proxy can't tunnel UDP packets which are required for real-time streaming.
