### ISSUE TITLE
Unable to install moonlight-qt on Ubuntu 24.04 arm

### ISSUE THREAD

**Issue by ameer4** [moonlight-stream/moonlight-qt#1442]
SBC: Orange pi 5  
Ubuntu 24.04 , 64bit, linux kernel 6.10

After running:
`curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | sudo -E bash`

Then

`sudo apt install moonlight-qt`

Received this error:
`E: Unable to locate package moonlight-qt`

How to force installation? or manually grab the deb file from source.  I think the setup.sh needs to adapt the noble release, because Nvidia tegra one installed correctly (but not working of course, nothing happens when clicking the moonlight icon)

**Comment by cgutman** [comment]
I pushed generic embedded packages for Ubuntu Jammy and Ubuntu Focal last night. If you run the same command again, it should find a package now.

**Comment by ameer4** [comment]
> I pushed generic embedded packages for Ubuntu Jammy and Ubuntu Noble last night. If you run the same command again, it should find a package now.

Thanks, it worked..
