### ISSUE TITLE
Streaming from Bazzite PC (with Sunshine) in non-native resolution looks messed-up 

### ISSUE THREAD

**Issue by jonnypanic** [moonlight-stream/moonlight-qt#1443]
I asked around on the Discord, but think not many other people have had this issue, yet. 

Describe the Bug:
Using a Bazzite Desktop to stream to Steam Deck, in game mode, if I choose any non-native resolution in-game, many games will display in a smaller window in the top left corner, surrounded by a garbled image. The same will happen to Steam itself if the resolution is changed to non-native. 
This is exactly the same issue as posted here:
https://github.com/LizardByte/Sunshine/issues/2646
The Sunshine devs seem to think it's a Moonlight issue.  
Desktop mode does not have this issue, it all works fine. 

**Steps to reproduce**
Stream from Bazzite in Gamemode with native resolution set in Steam, and run a game at lower than native resolution. UE games in particular seem to have trouble, as well as RE engine games. 

**Screenshots**
I don't have a screenshot but there is one on here: 
https://github.com/LizardByte/Sunshine/issues/2646

**Affected games**
Mainly UE and RE engine, it seems, of the games I have tried. Some examples being Robocop, Hi-Fi Rush, Resident Evil 8, Resident Evil 4. 

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

Problem occurs with default settings. I tried reinstalling and wiping settings, but it persists. 

**Client PC details (please complete the following information)**
- Steam Deck
- SteamOS: latest beta (3.6.8)
 - Moonlight Version: 6.1.0
 - Linux package type (if applicable): Flatpak

**Server PC details (please complete the following information)**
 - OS: Bazzite Fedora 40
 - Sunshine 2024.911.215654.copr
 - GPU: AMD 6750 XT
 - Linux package type (if applicable): Flatpak
 - GPU Driver:  Mesa 24.2.3
 
**Moonlight Logs (please attach)**
In desktop mode, Moonlight works fine so I don't think that would help, not sure how to get logs when running Game Mode

**Additional context**
A simple workaround is to not run the game at lower than native resolution, but of course performance will be affected. I'm streaming from a PC connected to a 4K TV, so I can't run everything at native. If anyone could help work this out, I'd be grateful. 

Thanks.

**Comment by cgutman** [comment]
Since you say it depends on resolution on the host computer, that's not something Moonlight would have any knowledge of. I reopened the issue on the Sunshine side.

**Comment by jonnypanic** [comment]
Got it, thanks. Hope it can get sorted on the Sunshine side.

**Comment by TariqMK** [comment]
> Got it, thanks. Hope it can get sorted on the Sunshine side.

I am experiencing this issue as well exactly as you described. Did you manage to re-raise it with the Sunshine devs?

**Comment by jonnypanic** [comment]
Unfortunately not. I have just been streaming in native resolution.

**Comment by xrishox** [comment]
I've only tested this for a few minutes but, I was seemingly able to solve this by enabling developer mode and inside of developer mode checking force composite.

This also solved another major problem I was having where I couldnt see the steam overlay from moonlight clients

( https://github.com/LizardByte/Sunshine/issues/3860#issuecomment-2954267416 thank you @mrpppbtthl5 )
