### ISSUE TITLE
Hardware decoding not working on Arch Linux

### ISSUE THREAD

**Issue by Azuriye** [moonlight-stream/moonlight-qt#1449]
**Describe the bug**
When forcing hardware decoding on moonlight client, moonlight-qt-bin shows a black screen when connected to sunshine host but mouse is responsive (if I move my mouse the sunshine host captures it as well) but the whole display is black and if I exit the application it hangs until I force terminate it.

moonlight-qt just crashes after connecting to my host and on terminal it says along the lines of segmentation fault core dumped.

**Steps to reproduce**
1) Force hardware decoding
2) Connect to any sunshine host

**Moonlight settings (please complete the following information)**
Default

**Client PC details (please complete the following information)**
 - OS: Arch Linux, KDE Plasma 6.2.1, Wayland
 - Moonlight Version: 6.1.0-2
 - GPU: NVIDIA GeForce RTX 3050 Laptop GPU, AMD Radeon Graphics
 - Linux package type (if applicable): AUR

**Server PC details (please complete the following information)**
 - OS: Windows 11 26100
 - Sunshine or GeForce Experience version: Sunshine v0.23.1
 - GPU: NVIDIA GeForce GTX 1080
 - GPU driver: 565.90

**Moonlight Logs (please attach)**
[moonlight.log](https://github.com/user-attachments/files/17482817/moonlight.log)

**Comment by cgutman** [comment]
Interesting, I wonder if it is the combination of AMD and Nvidia GPUs that are causing an issue when rendering with VDPAU.

Can you try running Moonlight the following 2 ways and see if either or both of them solve the problem?
- `FORCE_VAAPI=1 moonlight`
- `PREFER_VULKAN=1 moonlight`

**Comment by Azuriye** [comment]
> `FORCE_VAAPI=1 moonlight`

Okay so running those parameters fixed the black-screen issue. Upon further digging I found out that

`FORCE_VAAPI=1 moonlight`
Forces the moonlight streaming to use my integrated AMD card
Whereas,
`PREFER_VULKAN=1 moonlight`
Uses my discrete GPU in my dual-gpu laptop which is my RTX 3050.

Now if I run with both the parameters it only uses my integrated AMD card.

Lastly, in the AUR would you suggest to use the qt-bin package or just qt? I've noticed that the original qt package seems a bit grainy compared to qt-bin but I might be mistaken.
