### ISSUE TITLE
Make port configurable when have internet streaming to stream 2 or more game pc

### ISSUE THREAD

**Issue by jack2007** [moonlight-stream/moonlight-qt#145]
**Is your feature request related to a problem? Please describe.**
I have 2 nvidia pc in my home, and I have an internet access only and 1 public IP only.
Right now, moonlight need forword port tcp 47984, 47989, 48010 and udp 47998, 47999, 48000, 48002, 48010 to make internet streaming and the port is built-in moonlight's code.
With port forword configuration on my router, I can have only 1 nvidia pc streaming over internet at the same time. 
Could I streaming 2 nvidia pc over my internet access?
e.g., I could forward tcp 37984,37989,38010 and udp 37998, 37999, 38000, 38002, 38010 to pc1's streaming  ports.
and forword tcp 47984,47989,48010 and udp 47998, 47999, 48000, 48002, 48010 to pc2's streaming ports.

**Describe the solution you'd like**
I am a c programmer, so I looked into the code. I think it could be possible to make below use case done if I could configure ports on moonlight app.
In the code, I have found tcp 47984,47989,48010 and udp 47998, 47999, 48000, 48010, but udp 48002 is not exist in the code.
Am I missing some code file or udp 48002 is not used any more?
BTW, I used tcpview of systeminternal toolkit to observer nvidia ports, and I didn't find udp 48002 is used.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by cgutman** [comment]
There are other options for streaming from multiple PCs behind a single internet connection that are already covered in the Setup Guide, such as ZeroTier and IPv6 - https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#zerotier

I don't think the complexity of allowing custom ports is worth it. It will be very seldom used except for advanced users, who would already be able to do the ZeroTier or IPv6 solutions.

UDP 48002 is not currently used but it is reserved for GFE microphone audio (see the nvstreamer logs on the host. It exists in the port lists to future-proof them for when Nvidia enables this functionality for GameStream (GF Now already has it).

**Comment by jack2007** [comment]
Thanks a lot.

**Comment by apoklyps3** [comment]
I myself, still believe this is not a niche feature.
Sure, it's for the more advanced users and should be branded so, but in no way something to not take into consideration.
When was the last time Nvidia changed ports? 
The would provide a free alternative for those that have relax days at work, but the LAN architecture forbids a specific port range(nvidia's game stream for example) and also vpn connections that don't come or go to devices in the company's ownage.
Rerouting the external ports to internal ports is done so easily via the router's settings nowadays.
I agree that it might be confusing for some users, but then again they won't need it and won't need to mess with it, but for the advanced users: this is gold.
