### ISSUE TITLE
Moonlight for Xbox Series S and Series X

### ISSUE THREAD

**Issue by woiza** [moonlight-stream/moonlight-qt#1451]
**Is your feature request related to a problem? Please describe.**
Do you have any plans for moonlight on Xbox Series S and Series X?

**Describe the solution you'd like**
Similar app and experience as with moonlight for Windows, Mac, etc.
Support for 4k120 (and possibly 4:4:4) and h265. The hardware (S and X) is capable enough, supports VRR, and the decoding latency is very low. 

**Describe alternatives you've considered**
https://github.com/TheElixZammuto/moonlight-xbox

**Additional context**
The unofficial port is buggy, lacks features, and it looks like the developer hasn't responded to issues and PRs for some weeks now.

**Comment by cgutman** [comment]
Unless there is a port of Qt to the Xbox consoles, I doubt it. It would basically be a full rewrite akin to the existing moonlight-xbox project which wouldn't really be moonlight-qt anymore.
