### ISSUE TITLE
where is the config file path

### ISSUE THREAD

**Issue by Hiradpi** [moonlight-stream/moonlight-qt#1456]
where is the config file path ? i want to change some settings in the config like putting fps to 5

**Comment by jorys-paulin** [comment]
Not sure why you'd want to do that, but it depends on your platform. On Windows, it's somewhere in the registry or inside `Moonlight.ini` for the portable version.

**Comment by Hiradpi** [comment]
oh, thanks, and can one decrypt the UDP input packets with the certificate in the config ?

**Comment by cgutman** [comment]
No, input is encrypted via an ephemeral key that is freshly generated each time you stream.
