### ISSUE TITLE
moonlight on linux: unable to connect to the specified PC

### ISSUE THREAD

**Issue by TaugenichtsZZY** [moonlight-stream/moonlight-qt#1462]
(Discord link shows invite invalid...)
**Describe the bug**
I installed moonlight on my ubuntu 22.04 computer in the office using flatpak and would like to implement streaming with my Windows computer at home. Prior to that, I had gotten the ipv6 address of my Win computer, installed sunshine and successfully remote streamed with my Android phone. However, after installing moonlight on my office linux computer and entering the ipv6 address of another computer, it immediately shows “unable to connect to the specified PC. click the help button for possible Click the help button for possible solutions.” I have this problem whether I use vpn on linux computer or not. I'm not quite sure what the problem is, and I can't see the error from the command line output. So I'd like to ask for advice on what might be the problem? How do I troubleshoot and fix them? Thanks a lot!

**Steps to reproduce**
↑As described above↑

**Screenshots**
![img_v3_02gm_f06d0014-0755-47b7-8465-2c6626840f4g](https://github.com/user-attachments/assets/ecab88bb-d880-45f8-8742-4ff45bbd57ff)

**Affected games**
Not limited to the game, the streaming failed at the beginning

**Other Moonlight clients**
on Ubuntu22.04

**Moonlight settings (please complete the following information)**
All settings are default

**Gamepad-related issues (please complete if problem is gamepad-related)**
Not using gamepad at the moment

**Client PC details (please complete the following information)**
 - OS: [Ubuntu 22.04]
 - Moonlight Version: [v6.1.0 (from flatpak list)]
 - GPU: [nvidia 4060ti]
 - Linux package type (if applicable): [Flatpak]

**Server PC details (please complete the following information)**
 - OS: [Windows 11 23H2]
 - Sunshine or GeForce Experience version: []
 - GPU: [Nvidia 4070ti]
 - GPU driver: []

**Moonlight Logs (please attach)**
![image](https://github.com/user-attachments/assets/4505f6b5-655d-4f5b-bb05-a8e2582f5d93)
![image](https://github.com/user-attachments/assets/3a2f6907-8017-4668-a1d6-0ff46bf136a2)
![image](https://github.com/user-attachments/assets/3ce7e01f-1912-4049-b419-b4924ca7be21)

**Additional context**

**Comment by cgutman** [comment]
When using IPv6 addresses directly, you should escape them as they would be written in a URL. This was necessary to support providing a custom port number.

For example, `2001:db8::1234` would be written as `[2001:db8::1234]`. If you wanted to specify a custom port number, it would look like `[2001:db8::1234]:47989`.
