### ISSUE TITLE
A2DP not working properly with PulseAudio

### ISSUE THREAD

**Issue by xdbob** [moonlight-stream/moonlight-qt#147]
**Describe the bug**
The audio stopped working with my configuration
The bug was introduced with the commit b97758ef46e4ae6391eb94c09cd0df234ed5cf27

**Steps to reproduce**
Run moonlight

**Moonlight settings (please complete the following information)**
None in particular

**Client PC details (please complete the following information)**
I use an `XPS 9360` with ArchLinux and `pulseaudio 12.2`

**Logs (please attach)**
The not so relevant log:
```
00:00:01 - SDL Info (0): Audio configuration: 1
[...]
00:00:05 - SDL Info (0): Starting audio stream...
00:00:05 - SDL Info (0): Audio backend: PulseAudio
00:00:05 - SDL Info (0): Selected audio device: Shadow
00:00:05 - SDL Info (0): Native layout: 5.1 (back) (6 channels)
00:00:05 - SDL Info (0): Audio stream has 6 channels
00:00:05 - SDL Info (0): done
```

If I've got more time, I'll look into it further but better not count on it.

**Comment by xdbob** [comment]
PS: if it is relevant, I use an `XPS 9360` and `pulseaudio 12.2`

**Comment by cgutman** [comment]
Hmm, I have an XPS 9370 running PulseAudio 12.2 on Fedora 29 without issues.

Can you attach the output of `pactl list` and `pactl info`?

Does it work if you set the audio configuration to Stereo in Moonlight?

Is the selected audio device (Shadow) correct for your system? Is that your intended playback device?

**Comment by xdbob** [comment]
Shadow is indeed my bluetooth headset and the intended playback device.

`pactl info`

```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 32
Server Protocol Version: 32
Is Local: yes
Client Index: 253
Tile Size: 65472
User Name: xdbob
Host Name: didact
Server Name: pulseaudio
Server Version: 12.2
Default Sample Specification: s16le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: bluez_sink.04_52_C7_F0_4B_A5.a2dp_sink
Default Source: alsa_input.pci-0000_00_1f.3.analog-stereo
Cookie: ffd3:ddb7
```

`pactl list`
* [v0.6.4](https://pastebin.com/Yb3y6fvF)
* [v0.7.0](https://pastebin.com/rqwzpnZS)

And no it still don't work in stereo configuration.

**Comment by cgutman** [comment]
Does this only impact your Bluetooth headset? Does it work properly if you disconnect your headphones and use the built-in speakers?

Can you also post the entire log after streaming?

**Comment by tarruda** [comment]
I also have this issue with my bluetooth headset when using A2DP profile. If I switch to HSP/HFP, 
it starts working (with bad quality, of course).

Speakers (or anything connected to the motherboard audio port) are working fine.

**Comment by cgutman** [comment]
Thanks for confirming it's an A2DP issue. I have Bluetooth earbuds I can try, then push the fix upstream to libsoundio.

**Comment by ppibburr** [comment]
`flatpak update --commit=51c650457487f873129c0acee020fc61e25e54290e3126684e7734510652e8c3 com.moonlight_stream.Moonlight` 

that along with `PULSE_SERVER=unix:/var/foo/bar flatpak run com.example.app`

enables (not solve) audio for https://github.com/moonlight-stream/moonlight-qt/issues/146

prior to reverting the commit, audio error went away,but no sound, stream even showed up in mixer

**Comment by tarruda** [comment]
> that along with PULSE_SERVER=unix:/var/foo/bar flatpak run com.example.app

Right. I forgot to mention I have the following user systemd unit to automatically create a symlink to my non-standard PA socket location:

```
[Unit]
Description=Create a symlink to pulseaudio socket
ConditionPathExists=!%t/pulse/native
Depends=pulseaudio.socket
After=pulseaudio.socket

[Service]
Type=oneshot
ExecStart=/bin/mkdir -p %t/pulse
ExecStart=/bin/ln -s /tmp/pulse/native %t/pulse/native

[Install]
WantedBy=default.target
```

**Comment by cgutman** [comment]
Fixed by d1640e3bb8aca1de0417a73596ca9a6d0dae5205

**Comment by tarruda** [comment]
@cgutman I've tested v0.8.0 and confirm it is fixed, but the audio now has a "crackling" effect that is not present in flatpak version `51c650457487f873129c0acee020fc61e25e54290e3126684e7734510652e8c3`

**Comment by cgutman** [comment]
Ugh, that's annoying. It works perfectly for me on 2 different computers on Fedora 29 over BT.

Probably needs a larger buffer for some reason. How often does it crackle?

Are you able to build the code yourself?

**Comment by tarruda** [comment]
> Probably needs a larger buffer for some reason. How often does it crackle?

Reasonably often. It is not unbearable but a bit annoying.

> Probably needs a larger buffer for some reason. How often does it crackle?

> Are you able to build the code yourself?

I will try. Can you give some hints on where I should be adjusting the buffer size for testing locally?

**Comment by cgutman** [comment]
Ok, is your mic active during this time or just the output device?

The line to change is: https://github.com/moonlight-stream/moonlight-qt/blob/master/app/streaming/audio/renderers/soundioaudiorenderer.cpp#L14

I would try 25 and 30 to start to see if that helps.

**Comment by cgutman** [comment]
@xdbob @tarruda does v0.8.1 fix this for you both?

**Comment by tarruda** [comment]
@cgutman Is 0.8.1 already available as flatpak? https://flathub.org/apps/details/com.moonlight_stream.Moonlight only shows 0.8.0

**Comment by tarruda** [comment]
I've tested the version on flathub and confirm that A2DP is working flawless. Thanks.
