### ISSUE TITLE
Multiple UI issues on Win10 High DPI tablet

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-qt#15]
Tested on my Venue 8 Pro:

- Computer name text exceeds bounds of the grid item and overflows into the item below
- Video scaling in portrait windowed mode is screwed up badly (video is like 30 pixels wide)

**Comment by stripeyhorse** [comment]
having this same issue on a microsoft surface pro

**Comment by cgutman** [comment]
@stripeyhorse can you attach screenshots of the specific issues you're seeing on your device?

**Comment by stripeyhorse** [comment]
@cgutman Of course.

![2018-08-10 18_04_29-greenshot](https://user-images.githubusercontent.com/10705906/43946245-0cd11b94-9cc8-11e8-9984-ead6b2308476.png)
![2018-08-10 18_04_39-greenshot](https://user-images.githubusercontent.com/10705906/43946246-0d061cb8-9cc8-11e8-820d-e70c679750fc.png)
![2018-08-10 18_04_46-greenshot](https://user-images.githubusercontent.com/10705906/43946248-0d3c2e84-9cc8-11e8-83a4-04fe9346016d.png)

**Comment by cgutman** [comment]
Wow, that's remarkably bad scaling. That should be enough for me to reproduce it. Thanks.

**Comment by cgutman** [comment]
OK, I've tried on several laptops with the scaling up to 200% and I couldn't get the same glitching your're seeing (missing lines in preferences, and missing toolbar color). Is there anything else you can think of that might be causing it? Any other displays connected or accessibility settings changed to increase text size?

**Comment by stripeyhorse** [comment]
@cgutman no its actually brand new. Not much even installed on it yet. Ive tried in Tablet and normal windows mode and both the same. Not other displays connected and accessibility on default.

**Comment by cgutman** [comment]
Possibly relevant log messages from another Windows machine:
`00:00:00 - Qt Warning: Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.`

I don't see these log messages on my Windows machine with 100% scaling.

@stripeyhorse Can you grab your Moonlight log from %TEMP%?

**Comment by cgutman** [comment]
@stripeyhorse mind testing v0.3.0 to see if anything has changed? I added an app manifest claiming high DPI support (and now the Windows App Certification Kit says high DPI support is set properly).

I still haven't managed to reproduce this one sadly. I've tried maxing out scaling on all PCs I can get my hands on and haven't gotten the broken UI.

**Comment by stripeyhorse** [comment]
@cgutman version v0.3.0 actually has the scaling ALOT better. Settings is fully visible now. Thank you.

**Comment by cgutman** [comment]
Awesome! Must have been the app manifest then. I'm going to close this issue since the other issue (the portrait mode video scaling) was fixed in Alpha 1.

**Comment by cgutman** [comment]
bad bot
