### ISSUE TITLE
improve image quality for onboard intel graphics 

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#150]
**Is your feature request related to a problem? Please describe.**
Got a Dell with an intel HD graphics 520 onboard and I've noticed the video quality to be worse than on a very old laptop that uses an nvidia GT420M and stream quality is near 1:1 with the display on the host computer. The intel looks blocky sometimes with block artefacts on portions of the stream. This while using the same network and same settings.

**Describe the solution you'd like**
Is there anyway to fine tune the quality for intel onboard?

**Comment by cgutman** [comment]
Can you post the logs?

**Comment by apoklyps3** [comment]
[Temp.zip](https://github.com/moonlight-stream/moonlight-qt/files/2713156/Temp.zip)

**Comment by cgutman** [comment]
You have one of the known bad display drivers from Intel. Update it to the latest version.

```
00:00:05 - SDL Info (0): Windowed mode with DWM running
00:00:05 - SDL Info (0): Windowed: 1 | Present Interval: 80000000
00:00:05 - SDL Info (0): Detected GPU: Intel(R) HD Graphics 520 (8086:1916)
00:00:05 - SDL Info (0): GPU driver: igdumdim64.dll 22.20.16.4799
00:00:05 - SDL Info (0): Intel driver version blacklisted for HEVC
```

**Comment by apoklyps3** [comment]
thanks. will test

**Comment by apoklyps3** [comment]
`00:00:05 - SDL Info (0): Detected GPU: Intel(R) HD Graphics 520 (8086:1916)
00:00:05 - SDL Info (0): GPU driver: igdumdim64.dll 25.20.100.6471
00:00:05 - SDL Info (0): Frame pacing disabled: target 60 Hz with 60 FPS stream
00:00:05 - SDL Info (0): Using DXVA2 accelerated renderer
00:00:05 - SDL Info (0): Using H.264 SPS fixup
00:00:05 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:06 - SDL Info (0): Loading gamepad mappings from: C:\Program Files\Moonlight Game Streaming\gamecontrollerdb.txt
00:00:06 - SDL Info (0): Loaded 0 new gamepad mappings`

doesn't make a diffrence. quality still seems very bad in comparition with nvidia.
I'm playing PES2019 and what I was describing is very noticiable in the movement on the pitch area.
it becomes very blurry.

**Comment by apoklyps3** [comment]
anything else that can be done?

**Comment by cgutman** [comment]
Can you capture a video comparison of both Intel and Nvidia results?

I don't notice any decoding differences with my Intel HD 515 vs Nvidia and AMD GPUs. Sometimes Intel has some video processing stuff turned on by default which you can try to disable, but this doesn't look like that kind of issue.

**Comment by apoklyps3** [comment]
Don't think the nvidia laptop will withstand any kind of video capture especially while also using moonlight. 
It's pretty old laptop, but I can tell you the image is pretty darn close to original image at 1080p60hz(20mbps).
Will try to see if the Intel latop can take videocap.
Where do i find the video processing options so I can turn them off to see if there is any difference?

**Comment by cgutman** [comment]
Fixed in https://github.com/moonlight-stream/moonlight-qt/commit/86874489663721c8256df643f576a8ce627a1ba9 and https://github.com/moonlight-stream/moonlight-qt/commit/21aad643f3fc5b85d38f10f1b1ea4389c92f4258
