### ISSUE TITLE
Bitrate values set in the application are not respected. 

### ISSUE THREAD

**Issue by Adminjojo** [moonlight-stream/moonlight-qt#153]
Bitrate maximum values set in the application are not respected. 

Select a bitrate value like 3mbps or 2,5mbps, and it will never be respected and will go as high as 7,5 mbps in every situations (on the screenshot i was streaming my desktop).
Screenshot : https://snag.gy/08Cf2z.jpg
![08cf2z](https://user-images.githubusercontent.com/1921823/50559846-d071ff80-0cfa-11e9-8192-f1152dd883f6.jpg)

-Parsec does not do this and send the bitrate i ask, but the bitrate is set on the Parsec host side. 
-Android Moonlight client does not do this, and works perfectly on my phone.

Client specs : 
Windows 10 / Moonlight Version 0.8.0 (but i had the same problem since v 0.1... ) / Graphics : intel HD4000,
Server spec :
Windows 10  / GFE 3.16.0.140 / gtx 1080 

It's a major bug for streaming over internet.

[Moonlight-1546255665.log](https://github.com/moonlight-stream/moonlight-qt/files/2718272/Moonlight-1546255665.log)

**Comment by cgutman** [comment]
The video bitrate you choose is not the exact amount of data that will travel over the network.

You're choosing the H.264 encoder bitrate. That is just "Video bitrate" as the label says. Video bitrate doesn't include audio, which will add another 1-2 Mbps (which the tooltip also says).

Forward Error Correction will add another 20% to the encoder bitrate chosen there to provide some protection against lost packets.

Then depending on how Windows counts traffic, the Ethernet and UDP headers may or may not count toward the value in Task Manager, which are also not included in the bitrate.

If we do the math, 2.5 + (2.5 * .2) + 2 = 5.06 is pretty close.

**Comment by Adminjojo** [comment]
Ok, but you should investigate this a bit more and do the bandwidth test maybe?
I have monitored the bitrate in moonlight android too, and it really never goes as high (at 2,5mbps pc client can reach 7mbps as i said), same thing with Parsec, wich stay very closed to the server ' 2,5mbps i set.

**Comment by cgutman** [comment]
Are you using H.265 on Android? H.265/HEVC will reduce the video bitrate to 75% of the value chosen to balance the fact that HEVC is a more efficient codec. That gap can absorb much of the additional data I've mentioned above.

Audio didn't used to be such a large bandwidth consumer until a while back when Nvidia forced high quality audio enabled even if the client doesn't request it. I implemented a fix to constrain it back to something reasonable, but the next release of GFE broke it, resulting in very garbled audio, and requiring me to do an emergency patch on all Moonlight clients.

I'm not saying the current situation is ideal. I'm just describing how it works and why it currently works that way.

**Comment by cgutman** [comment]
Try this dev build: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/21325546/job/so4e6m1xrymb85dv/artifacts

Download the portable version but delete portable.dat if you have v0.8.0 installed. Don't use the installer.

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-qt/commit/2b14856d7fa30eb832cdcad573d507eaa2913222
