### ISSUE TITLE
Propose Linux binaries with releases

### ISSUE THREAD

**Issue by Jorys-Paulin** [moonlight-stream/moonlight-qt#154]
**Is your feature request related to a problem? Please describe.**
I'm currently running Linux on one of my PCs, and I'd like to try Moonlight on that system. I know you can get Moonlight via Flatpak, but I wondered if it was possible to also give Debian installers as well, as it would remove the dependency to Flatpack and might be easier for new Linux users to use a familiar installer just like on MacOS and Windows.

**Describe the solution you'd like**
Just like for MacOS and Windows, make Linux binaries available to download just like `dmg`s and `exe`s. It can be an installer `deb` file or an archive containing the binaries (in something like a `tar.gz` archive file).

**Describe alternatives you've considered**
Someone is building a snap package for Moonlight, so Moonlight might get into the Snap store soon, and so it will be available in the Ubuntu marketplace as well, for example.

**Additional context**
My current system is running Ubuntu 18.10, I haven't tested any non-Debian based distros yet, so I don't know how installers would work there.

**Comment by cgutman** [comment]
In many cases, the distros don't provide the required dependency versions for us to package in their default repositories. Ubuntu 16.04, Ubuntu 18.04, and Debian 9 don't package FFmpeg 4.0+. Debian 9 and Ubuntu 16.04 don't package Qt 5.9+. Ubuntu 16.04 also ships with an ancient version of SDL that we don't support.

Using standalone packages would also regress our ability to auto-update that Flatpak gives us. To get that back, we'd need to maintain our own repositories to distribute updates too, which is more infrastructure and maintenance burden.

To support even an Ubuntu LTS version as new as Ubuntu 18.04, the user will have to manually install one or more PPAs which defeats the point of improving accessibility to novice users. If they will already need to install a PPA, it might as well be the Flatpak PPA which gives them updates for life.

Additionally, many distros have Flatpak installed right out of the box with GNOME Software integration, like Fedora, Linux Mint, Endless OS, and CentOS. With the Snap package, we can cover Ubuntu and derivatives out of the box too. I'm happy to help with that effort if needed.

I'm happy to help other people to maintain distro-specific packages and repos (like [AUR](https://aur.archlinux.org/packages/moonlight-qt/) made by the community), but I won't be doing it myself. There's simply to much complexity and distraction from the goal of the project.

**Comment by maxiberta** [comment]
FTR I've built and published a snap package for Moonlight, which I'm happy to maintain. But please let me know if you want to do it yourself and we can transfer/share it.

https://snapcraft.io/moonlight

**Comment by cgutman** [comment]
@maxiberta yep, I saw that. It's great to see Moonlight available from the Software store right out of the box on Ubuntu.

I tossed a fix into v0.8.1 to address the broken context menus on Qt 5.9 for your Snap.

You're welcome to continue maintaining it. I'll send PRs with changes/optimization if needed.
