### ISSUE TITLE
GameStream doesn't come back up after waking PC from sleep

### ISSUE THREAD

**Issue by njibhu** [moonlight-stream/moonlight-qt#155]
On my host windows server I have set a sleep timeout of 60minutes which makes the computer goes to sleep if the mouse was not moved. I then use wake on lan to re-awake this computer.

I am playing mainly Guild Wars 2 on it, which works a bit particularly because Nvidia looses track of the process when it's started since it has a launcher. So when I am closing the game, the moonlight session is not terminated. Luckily for me closing sessions for other clients was implemented in moonlight very recently. 🎉

Sadly I still have the issue that if the session was going on when the computer went to sleep, I cannot connect Moonlight back after re-awakening the computer. The host is locked in Moonlight.

In that case I then need to ssh inside the windows computer and force a restart.
Easy fix would be to know how to close a session from within the host, and trigger that before the computer goes to sleep.

**Comment by cgutman** [comment]
Can you describe more about what is happening on the host PC? You say "softlocks". Does that mean the host PC was unusable even if you directly used its keyboard and mouse? And the lock you mentioned, do you mean the lock icon appears on the PC in the Moonlight UI?

This is the host PC running the game going to sleep right? Not the PC running Moonlight?

**Comment by cgutman** [comment]
My suggestion would be to stream the full desktop and use the "Quit app after quitting session" option to automatically quit your session after you disconnect.

**Comment by njibhu** [comment]
That works, right, but sometimes I like being able to not quit when closing, for example to re-open after I restart the computer where moonlight runs.
I guess if there would be a shortcut for quitting and one for closing that would be the best.
