### ISSUE TITLE
Makefile issues when building using qmake and make

### ISSUE THREAD

**Issue by abharga2** [moonlight-stream/moonlight-qt#156]
**Describe the bug**
I am trying to create a Moonlight executable using qmake and make. When I run
`qmake -project \
qmake -makefile moonlight-qt.pro \
make`
I get a variety of header file not found issues. I modified the Makefile to fix most of these problems, but I'm still getting many syntax problems with h264bitstream. I also found that I needed to download the Steamlink SDK in order to get the SLVideo.h header. Am I doing something wrong here or potentially missing some libraries?

All I really want to do is create an executable from the source code in the moonlight-qt directory. Is there an easier way to do this?

**Screenshots**
One of the h264bitstream errors:
![image](https://user-images.githubusercontent.com/23245373/50584618-7f125f00-0e25-11e9-90ee-d5e94b404a9e.png)

**PC details (please complete the following information)**
 - OS: MacOS Mojave
 - Moonlight Version: Recently pulled, version 0.8.0

**Comment by cgutman** [comment]
What version of Qt are you building with?

**Comment by abharga2** [comment]
> What version of Qt are you building with?

Version 5.12.0

**Comment by cgutman** [comment]
`qmake moonlight-qt.pro -spec macx-clang; make debug` is what our [Travis CI script](https://github.com/moonlight-stream/moonlight-qt/blob/master/.travis.yml) does.

You don't need any Steam Link headers to build. Those are part of a pre-build check to see if your environment has them for the Steam Link backend, but but they are not expected to be present (and none of my Macs have them).

**Comment by cgutman** [comment]
That's weird. I built Moonlight v0.8.0 with Qt 5.12 on Mojave using that script for the release, so I don't know why it doesn't work for you. Can you attach the full build log?

My guess is that there's something wrong with your Homebrew install of Qt. I installed with the official Qt installer, so you could try that (and update your PATH to point to the Qt 5.12 bin folder installed).

**Comment by utkarshdalal** [comment]
I'm still getting this issue now, I installed qt via Homebrew and am on Mac as well:

```
../../../app/backend/computermanager.cpp:979:10: fatal error: 'computermanager.moc' file not found
  979 | #include "computermanager.moc"
```

```
Utkarshs-MacBook:GameAway-moonlight utkarshdalal$ qmake -v
QMake version 3.1
Using Qt version 5.15.16 in /opt/homebrew/Cellar/qt@5/5.15.16/lib
```

also, the --with-debug option doesn't work in homebrew when I try to install:

```
Utkarshs-MacBook:GameAway-moonlight utkarshdalal$ brew install qt@5 --with-debug
Error: invalid option: --with-debug
```
