### ISSUE TITLE
No sound with PulseAudio on ArchLinux

### ISSUE THREAD

**Issue by dbatyai** [moonlight-stream/moonlight-qt#157]
I'm using moonlight on an older laptop running ArchLinux with PulseAudio 12.2. Ever since moonlight v0.7 (when the switch to libsoundio happened), I did not have any sound while streaming. Versions before that work fine.

I've been trying to identify the problem, and it seemed that moonlight correctly configures
the pulse sink. From the log:
```
00:00:10 - SDL Info (0): Starting audio stream...
00:00:10 - SDL Info (0): Audio backend: PulseAudio
00:00:10 - SDL Info (0): Selected audio device: Built-in Audio Headphones + Speaker
00:00:10 - SDL Info (0): Native layout: Stereo (2 channels)
00:00:10 - SDL Info (0): Audio buffer size: 8 packets
00:00:10 - SDL Info (0): Audio stream has 2 channels
```

I did not get any errors in the log while the stream was running that would indicate that anything went wrong. I have pulse set up to run at 48kHz with s16le format, and I verified with pacmd that moonlight set up everything appropriately, yet I still didn't get any audio.

I started debugging what was happening, and after verifying that the problem does not come from libsoundio, I came to the conclusion that there was something amiss with the logic in `sioWriteCallback`. I tweaked it around after looking through the soundio api docs, and after a while managed to get it working, albeit with some distortion in the audio.

Then after a little reading, I realized that by default PulseAudio uses 25msec buffers, and after I changed the minimum sample length to reflect this, the distortion vanished, and now I have crispy clean audio. Latency-wise I didn't notice anything out of the ordinary so far.

Here's a diff of what I changed
```diff
diff --git a/app/streaming/audio/renderers/soundioaudiorenderer.cpp b/app/streaming/audio/renderers/soundioaudiorenderer.cpp
index 47ff5c1..e67ced2 100644
--- a/app/streaming/audio/renderers/soundioaudiorenderer.cpp
+++ b/app/streaming/audio/renderers/soundioaudiorenderer.cpp
@@ -11,7 +11,7 @@ const double SoundIoAudioRenderer::k_RawSampleLengthSec = 0.005;
 // PulseAudio and ALSA require more than just 5 ms samples
 // for some reason, so write a minimum of 20 ms each time to
 // prevent underruns on Bluetooth.
-const double SoundIoAudioRenderer::k_MinSampleLengthSec = 0.020;
+const double SoundIoAudioRenderer::k_MinSampleLengthSec = 0.025;
 #else
 // This determines the size of the buffers we'll
 // get from CoreAudio. It is also the minimum
@@ -368,16 +368,7 @@ void SoundIoAudioRenderer::sioWriteCallback(SoundIoOutStream* stream, int frameC
     int framesLeft = soundio_ring_buffer_fill_count(me->m_RingBuffer) /
             (me->m_OpusChannelCount * stream->bytes_per_sample);
     int bytesRead = 0;
-
-    // Ensure we always write at least a buffer, even if it's silence, to avoid
-    // busy looping when no audio data is available while libsoundio tries to keep
-    // us from starving the output device.
-    frameCountMin = qMax(frameCountMin, (int)(stream->sample_rate * k_MinSampleLengthSec));
-    frameCountMin = qMin(frameCountMin, frameCountMax);
-
-    // Clamp framesLeft to frameCountMin to ensure that we never write more than one sample.
-    // This makes sure that we never increase our latency beyond what the sink is consuming.
-    framesLeft = qMin(framesLeft, frameCountMin);
+    int framesToWrite = frameCountMax;
 
     // Track latency on queueing-based backends
     if (me->m_SoundIo->current_backend != SoundIoBackendCoreAudio && me->m_SoundIo->current_backend != SoundIoBackendJack) {
@@ -389,9 +380,7 @@ void SoundIoAudioRenderer::sioWriteCallback(SoundIoOutStream* stream, int frameC
         int err;
         struct SoundIoChannelArea* areas;
 
-        // Always meet the minimum but don't write more than that
-        // if we'll have to insert silence
-        frameCount = qMax(framesLeft, frameCountMin);
+        frameCount = framesToWrite;
 
         if (frameCount == 0) {
             // Nothing more to write
@@ -424,10 +413,8 @@ void SoundIoAudioRenderer::sioWriteCallback(SoundIoOutStream* stream, int frameC
                            &readPtr[readPtrChannel * stream->bytes_per_sample],
                            stream->bytes_per_sample);
                 }
-
                 areas[ch].ptr += areas[ch].step;
             }
-
             // Move on to the next frame if we aren't inserting silence
             if (frame < framesLeft) {
                 readPtr += stream->bytes_per_sample * me->m_OpusChannelCount;
@@ -443,19 +430,7 @@ void SoundIoAudioRenderer::sioWriteCallback(SoundIoOutStream* stream, int frameC
             break;
         }
 
-        if (framesLeft >= frameCount) {
-            framesLeft -= frameCount;
-        }
-        else {
-            framesLeft = 0;
-        }
-
-        if (frameCountMin >= frameCount) {
-            frameCountMin -= frameCount;
-        }
-        else {
-            frameCountMin = 0;
-        }
+        framesToWrite -= frameCount;
     }
 
     soundio_ring_buffer_advance_read_ptr(me->m_RingBuffer, bytesRead);
```
I'm not entirely sure what was wrong with the original code, but it seemed that the sink was consuming frames way faster than moonlight was writing them. In the soundio docs there was a note stating that we should always write as many frames as possible, since even then it may underflow, which led me to make these changes.

Since I'm not very familiar with the code, and I don't now the reasoning behind much of it, I'd rather not jump to conclusions, but I'd like to leave this here hoping that it will be helpful in some way.

**Comment by cgutman** [comment]
The theory behind the original code is that `sioWriteCallback()` would be called any time the sink is running low on frames. We write one 5 ms frame at a time, which matches the size of the incoming audio frames from GameStream.

My assumption was that if the sink was still too low on samples, it would immediately call `sioWriteCallback()` again, which appears to be false on PulseAudio. Even though we were happy to write it 20 ms of audio in 5 ms chunks if it asked us 4 times, it wouldn't play anything unless we wrote in larger chunks in a single shot.

We definitely can't write frameCountMax all the time, as that is huge on some backends like WASAPI and we'll fill the playback buffer with tons of silence.

Can you reset back to the original code then try both of these changes separately and together:
1. Comment out `framesLeft = qMin(framesLeft, frameCountMin);`
2. Change `k_MinSampleLengthSec` to 0.025

I will test on my hardware too.

**Comment by cgutman** [comment]
I ended up reverting that change due to issues on Windows too. So go ahead and just try change 2 on that list.

**Comment by cgutman** [comment]
Does v0.8.1 work for you now?

**Comment by dbatyai** [comment]
Nope, I checked the latest master, but I didn't have any audio.

**Comment by dbatyai** [comment]
It's an Asus x205ta, with an Intel Atom Z3735F cpu and a Realtek rt5648 sound card. It's running a 4.19.4 kernel, alsa-1.1.7, and pulseuadio-12.2.

You can see the output of pactl info and pactl list [here](https://gist.github.com/dbatyai/bb4431233bb5da4179bdfc1b7bcea315).

In the meantime I'll see if I can narrow it down to anything specific, but I don't have a lot of time to put into this at the moment, so it might take a while. I'll keep you posted if I find anything.
