### ISSUE TITLE
Moonlight says HEVC is not supported

### ISSUE THREAD

**Issue by MaoDzeDun** [moonlight-stream/moonlight-qt#158]
When I try to select h265, Moonlight says it is not hardware supported on the client machine. However, the laptop has an N3450 which does support HEVC. Am I missing something?

**Comment by cgutman** [comment]
HEVC is blacklisted on Cherry Trail because the decoder performance is worse than H.264.

https://en.m.wikipedia.org/wiki/Intel_Graphics_Technology#Intel_Atom_family
