### ISSUE TITLE
The text inside the application's dialogs is not visibile

### ISSUE THREAD

**Issue by bdudelsack** [moonlight-stream/moonlight-qt#161]
**Describe the bug**
The text inside the application's dialogs is not visibile (painted with black color on the black background)

I'm using the Gnome Shell wit Adapta Nokto Eta theme. The theme was installed by flatpak while installing the application.

Because of this issue i cannot pair with the Server (PIN is not visible).

```
λ flatpak install Moonlight                                                                                                                   
Looking for matches…
Found similar ref(s) for ‘Moonlight’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: 
Found ref ‘app/com.moonlight_stream.Moonlight/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: 
Required runtime for com.moonlight_stream.Moonlight/x86_64/stable (runtime/org.kde.Platform/x86_64/5.12) found in remote flathub
Do you want to install it? [Y/n]: 

com.moonlight_stream.Moonlight permissions:
    ipc                   network       pulseaudio      wayland      x11      devices      file access [1]
    dbus access [2]

    [1] xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro
    [2] com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*


        ID                                                       Arch               Zweig              Remote              Download
 1. [✓] org.kde.Platform                                         x86_64             5.12               flathub             411,4 MB / 484,7 MB
 2. [✓] org.freedesktop.Platform.VAAPI.Intel                     x86_64             18.08              flathub               1,8 MB / 1,8 MB
 3. [✓] org.freedesktop.Platform.html5-codecs                    x86_64             18.08              flathub               2,8 MB / 2,8 MB
 4. [✓] org.gtk.Gtk3theme.Adapta-Nokto-Eta                       x86_64             3.22               flathub             208,1 kB / 206,8 kB
 5. [✓] org.kde.PlatformTheme.QGnomePlatform.Sources             x86_64             5.12               flathub              24,8 kB / 23,6 kB
 6. [✓] org.kde.PlatformTheme.QGnomePlatform                     x86_64             5.12               flathub             138,8 kB / 137,8 kB
 7. [✓] org.kde.Platform.Locale                                  x86_64             5.12               flathub              23,1 MB / 236,2 MB
 8. [✓] com.moonlight_stream.Moonlight                           x86_64             stable             flathub               8,0 MB / 8,3 MB
```

**Screenshot**
![bildschirmfoto vom 2019-01-10 16-26-03](https://user-images.githubusercontent.com/3631456/50978742-4fceb280-14f5-11e9-8069-00947f3768c2.png)

**Logs**
[Moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/2745972/Moonlight.log)

**Client PC details (please complete the following information)**
 - OS: Manjaro Linux with Gnome Shell and Adapta-Nokto-Eta theme
 - Moonlight Version: v0.8.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 1809

**Comment by cgutman** [comment]
I actually see this on my Fedora 29 machines when I'm running the non-Flatpak'd version when developing, but this is the first report I've heard of this issue with the Flatpak. It's probably an upstream bug in Qt or the theme itself.

What happens if you manually remove `org.gtk.Gtk3theme.Adapta-Nokto-Eta`?

**Comment by cgutman** [comment]
Nevermind, the issue is `org.kde.PlatformTheme.QGnomePlatform`. Installing that breaks dialog rendering and removing it fixes it again. My dev machine also comes with QGnomePlatform installed, which probably explains the occurrence of this bug when developing outside the Flatpak environment.

I guess it's a bug in QGnomePlatform, but I found that calling `QGuiApplication::setDesktopSettingsAware(false)` avoids triggering the issue.

**Comment by bdudelsack** [comment]
I can confirm that `flatpak uninstall org.kde.PlatformTheme.QGnomePlatform` serves as workaround
