### ISSUE TITLE
Mouse disappears with Windows scaling

### ISSUE THREAD

**Issue by roncamma** [moonlight-stream/moonlight-qt#163]
Hi, 
When I use windows scaling (200% instead of 100%) because in native 100% elements are too small on my remote screen due to his resolution, the mouse disappears after randomly few seconds. The mouse work but the cursor isn't displayed.
This issue is only in Windows desktop, not other game.

**Comment by cgutman** [comment]
Can you try turning on Mouse Keys in the Windows Accessibility settings?

**Comment by roncamma** [comment]
Thanks for your answer !

This options refer to user mouse with digital pad ?
See attached picture, mouse isn't displayed on my laptop.

(Sorry it is in French)

![photo_2019-01-11_20-44-07](https://user-images.githubusercontent.com/19478789/51055928-a9aca680-15e1-11e9-8241-7133b4e6363e.jpg)

**Comment by cgutman** [comment]
Yes. @Jorys-Paulin maybe you can read the text?

**Comment by DaAwesomeRazor** [comment]
Turning on mouse keys does not fix the bug.

**Comment by kshots** [comment]
Still a problem... Only workaround I've found is enabling mouse pointer trails, which ends up being shared across all MS live accounts (and consequently gets shut off when a client gets shut off). Better to have a solution that doesn't depend on Windows accessibility hacks.

**Comment by nathanvong** [comment]
This is still an issue. Workaround is to enable pointer trails or increase the mouse size. But it still can be invisible in game menus like dues ex mankind divided

**Comment by CooleRnax** [comment]
Same issue

**Comment by CooleRnax** [comment]
Selecting custom cursor color and selecting white color fixed the issue for me
![image](https://user-images.githubusercontent.com/980180/71579589-52fbed80-2b0e-11ea-9e61-ebc296e4e132.png)

**Comment by koshisan** [comment]
This is still happening unfortunately. I am running 4096x2160 at 300% (which is the recommended value) and have no visible mouse cursor in moonlight. Even though invisible the mouse is working and there is a local mouse attached. Changing the color, etc. did not help. The cursor becomes visible if I enlarge it to "5".
That is not a good workaround however, because then the mouse is the only thing that is visible...

**Comment by jekket** [comment]
Same thing. Windows 10, 4k resolution and I noticed that cursor is disappearing when you hover it above something that makes it change its shape - like the text highlighting.

**Comment by koshisan** [comment]
Since I am not sure if closed tickets are being read, and I cannot reopen here, I raised a new one: #357

**Comment by cgutman** [comment]
This is not something we can fix ourselves. It is a bug in how the mouse is captured by GeForce Experience.

**Comment by aiwipro** [comment]
For people coming here with this issue, I can second CooleRnax tip: https://github.com/moonlight-stream/moonlight-qt/issues/163#issuecomment-569649125

I'm running 5120x2880 at 200% DPI scaling and setting the mouse pointer size to 7 or greater gives me a mouse pointer again. If I set it to size 6or smaller it disappears.

**Comment by huhuazhi** [comment]
you can keep a option, is "original Mouse display", keep Android mouse cursor,let it will not hide, and another, you can draw a Mouse cursor by input data.

**Comment by Vexz00** [comment]
> 
> 
> For people coming here with this issue, I can second CooleRnax tip: [#163 (comment)](https://github.com/moonlight-stream/moonlight-qt/issues/163#issuecomment-569649125)
> 
> I'm running 5120x2880 at 200% DPI scaling and setting the mouse pointer size to 7 or greater gives me a mouse pointer again. If I set it to size 6, or smaller, it disappears.

Do I have to do this on the server or client? My client is a Linux machine with KDE. Don't know what to do there to make it work.

**Comment by somacoder** [comment]
If you increase the cursor size in Windows Settings from 1 to 2, it should persist without disappearing.
