### ISSUE TITLE
Windows 10: connection issues

### ISSUE THREAD

**Issue by Jimbazuka** [moonlight-stream/moonlight-qt#164]
2 PCs on same LAN - both Windows 10 x64, both can see and communicate with each other normally but not via Moonlight

1 PC, (ip address 192.168.1.6) with Nvidia GTX 1050 ti and set to stream games - see attached screenshot from within Ge Force Experience (myRig.jpg)
![myrig](https://user-images.githubusercontent.com/7934633/51317078-8dc85b00-1a4e-11e9-934a-f1086989b9a0.jpg)

Other PC, (ip address 192.168.1.23) running Moonlight v0.81 can not see the former (although set to automatically find PC on same LAN) and can also not add the former PC with direct IP - it comes up with "unable to connect" as shown in 2nd attachment
![cannotfindviaip](https://user-images.githubusercontent.com/7934633/51317151-ba7c7280-1a4e-11e9-9466-44354e4a761a.jpg)

Interestingly, the streaming PC with GTX 1050 ti, can see a 3rd PC (ip address 192.168.1.4) running windows 7 on same LAN but since its not configured and does not run moonlight, it comes up with web-server error not found as shown in attachment #3. This error however is of no interest to me as not trying to play via it.
![2019-01-17 03_06_38-moonlight](https://user-images.githubusercontent.com/7934633/51317183-d08a3300-1a4e-11e9-84f9-9cd8c8606a40.jpg)

**Affected games**
ALL

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? NO
- If so, which settings have been changed? NONE
- Does the problem still occur after reverting settings back to default? YES

**Client PC details (please complete the following information)**
 - OS: Windows 10 x64  Build 17134.471
 - Moonlight Version: 0.81

**Server PC details (please complete the following information)**
 - OS: WIn10 x64 build 17763.194
 - GeForce Experience version: [e.g. 3.16.0.140] GEForce Ready Driver Version 417.71 of 1-15-19
 - Nvidia GPU driver: [e.g. 417.35] The Driver for GTX 1050 ti per windows device manager is 25.21.14.1771 of 1-1-19 - the GEForce ready Driver is Version 417.71 of 1-15-19

**Moonlight Logs (please attach)**
attached as zip
[Moonlight.zip](https://github.com/moonlight-stream/moonlight-qt/files/2768503/Moonlight.zip)

**Comment by cgutman** [comment]
Can you make sure the SHIELD toggle is enabled on 192.168.1.6 per the [setup steps](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#quick-setup-instructions)?

If it is, on the host PC, try to load http://127.0.0.1:47989/serverinfo in your browser.
If that works, try http://192.168.1.6:47989/serverinfo
If that also works, try the same link on your client PC.

**Comment by Jimbazuka** [comment]
The GEforce Experience's Shield Gamestream was set to on. However, when I turned it off then tried to on again it wouldn't turn onl, even after reboot. I ended up uninstalling GEforce Experience, rebooting then re-installing and that fixed the problem....now Moonlight works.  I am closing this issue.
