### ISSUE TITLE
Two computers streaming outbound on the same network

### ISSUE THREAD

**Issue by seansemperfi** [moonlight-stream/moonlight-qt#165]
I understand this isn’t actually a bug or a glitch - that this is just the way Moonlight is programmed at this time - the issue I am having is that I can’t run multiple instances outbound from the same external IP. The reason I need to stream two PCs out - I am alway traveling, so I need to be able to play my games remotely, and my little brother’s gaming computer is going kept at my house (in case it has any hardware issues, I’ll be the one who has to buy and replace the parts), and he needs to be able to remote into his. We could remote play one at a time (turning Nvidia game streaming off for the computer not being played at that moment), but we wouldn’t be able remote play together in an online game at the moment. Would it be possible to add the ability to have two outgoing instances simultaneously in the future? (I am using future tense for his computer, because I have built it as a birthday present, and this is the final hurdle to making it completely operational for remote gaming)

**Comment by cgutman** [comment]
You should be able to do this with the [ZeroTier setup instructions](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#zerotier).
