### ISSUE TITLE
Mouse over Xephyr or vnc is uncontrollable.

### ISSUE THREAD

**Issue by njibhu** [moonlight-stream/moonlight-qt#166]
If I'm starting moonlight-qt in a virtual Xorg server (Xephyr) the mouse is basically impossible to control. It jumps directly from corner to corner like the sensibility is way way too high, both with raw input settings set or unset.

Curiously, the same problem occurs when moonlight is controlled over vnc, and I tried both with a virtual xorg attached to a vnc server or directly a xorg vnc server (tigervnc).

Steps to reproduce: (On a linux desktop)
- install xephyr
- start a Xephyr instance
- start moonlight with the DISPLAY environment variable set to the Xephyr server
- Start a game from moonlight

(Moonlight 0.8.1 on Archlinux)

**Comment by cgutman** [comment]
It sounds like your X server or VNC server is not capable of getting relative mouse motion via pointer capture with XGrabPointer. Functioning mouse pointer capture is required for Moonlight.
