### ISSUE TITLE
Please create UWP version

### ISSUE THREAD

**Issue by AceHack** [moonlight-stream/moonlight-qt#170]
Would love to be able to run this on my Xbox One

**Comment by cgutman** [comment]
In addition to the technical requirements (which shouldn't be too problematic since Qt, SDL, and FFmpeg are UWP-compatible), the concern here is that Microsoft explicitly bans emulators in their Xbox Store guidelines. I would imagine that would extend to us as well since we are another method that users could play other non-Xbox games on Xbox.

**Comment by AceHack** [comment]
@cgutman To my knowledge, MS does not put enumerators and streaming in the same regards.  There are several streaming apps in the Xbox store such as:
https://www.microsoft.com/en-us/p/airserver-xbox-edition/9nblggh52nb8?activetab=pivot:overviewtab

The reason they ban emulators is not that it allows you to play games from another platform, it's because pirate abuse is rampant in emulators as in most people do not own the roms they play.  Streaming does not fall into this same category unless MS is admitting the main use of windows is to pirate software/games.

Even if they don't allow the app in the store, it can be sideloaded in Dev Mode, I run several UWP apps like this on my Xbox.  Thanks.

**Comment by dschu012** [comment]
Rainway looks like it might've been approved based on

https://rainway.com/blog/2019/03/22/xbox-one-release-announce/

I figure moonlight would fall into the same category.

**Comment by AkazaDorian** [comment]
It might be better phrasing to say "release in Windows Store" instead of "create UWP version" since the former one sounds like recreating the whole GUI.

**Comment by AceHack** [comment]
Was looking for UWP version so you can run on Xbox in Dev mode.

**Comment by scyto** [comment]
There is no need for a UWP app in dev mode if one publishes in store - plus store app would work for win10 as well as xbox.  Also there is nothing prohibiting streaming clients in the store or developer terms of service, this is not an emulator.  There is nothing stopping the moonlight team from doing this other than hoops one has to jump through for the store.  But this would be way more accessible for folks than dev mode.

**Comment by Jonathanlodorcleary** [comment]
A UWP release would make ARM64 support on windows much easier.

**Comment by PathogenDavid** [comment]
> Rainway looks like it might've been approved based on
> 
> https://rainway.com/blog/2019/03/22/xbox-one-release-announce/

To avoid this getting anyone else's hopes up: [Microsoft asked them to remove Rainway from the app store for unspecified reasons](https://twitter.com/RainwayApp/status/1223404565531217921):

> Thank you for your overwhelming response to Rainway on the Xbox One Beta.
>
> Unfortunately, due to unexpected circumstances, Microsoft has asked us to remove Rainway from the app store. We are continuing to work with Microsoft to bring Rainway back to the Xbox.

Without knowing the reason this doesn't necessarily mean Moonlight UWP wouldn't be allowed, but Rainway can't really be an example that it would.

**Comment by cgutman** [comment]
I responded here - https://ideas.moonlight-stream.org/posts/32/moonlight-qt-uwp-release-for-xbox-and-windows-arm

**Comment by AkazaRenn** [comment]
With the recent changes of Windows Store policy can we expect Moonlight to be available in Windows Store?

**Comment by Tom60chat** [comment]
You can publish unlisted app on the Microsoft Store.
Unlisted app is unverified so you can publish anythings, if people don't report your app.

Users have to go on Microsoft Edge and type a link to acces the unlisted MS Store app.
Like this website where people regroup unlisted MS store apps like RetroArch to install on your Xbox: https://gamr13.github.io/

**Comment by Tom60chat** [comment]
> > This app is not optimized for gaming (lag), relies on MiraCast (no Ethernet support for host) and sometimes works on some devices, sometimes does not.
> > It's good for watching Movies.
> 
> Completely agree. Just pointing out that Microsoft has an app that's purpose is the same. So it's pretty unlikely they block Moonlight from the store.

Rainway, already had an app ready for UWP / Xbox for the Microsoft Store, but they were blocked.
