### ISSUE TITLE
Question: Do I need a NVIDIA Card, or NVIDIA Software such as NVIDIA GameStream?

### ISSUE THREAD

**Issue by trymeouteh** [moonlight-stream/moonlight-qt#173]
Do I need a NVIDIA Card, or NVIDIA Software such as NVIDIA GameStream? Is it possible to use this with an ATI card?

**Comment by dead** [comment]
Yes, you need a NVIDIA Card and NVIDIA GameStream.

**Comment by cgutman** [comment]
An NVIDIA GameStream-compatible card is required to host, but other GPUs are supported on the clients running Moonlight.
