### ISSUE TITLE
Allow seamless mouse capturing for desktop.

### ISSUE THREAD

**Issue by luis-banuelos-chacon** [moonlight-stream/moonlight-qt#175]
When using Moonlight as a remote desktop replacement, having to capture is inconvenient, specially with a multi-monitor setup.

Having the mouse auto-capture when going in and out of the screen (much like virtual machines or remote desktop) would be really useful.

**Comment by cgutman** [comment]
Unfortunately this isn't currently possible with Nvidia GameStream. It only supports relative mouse mode which requires capturing the mouse cursor.

**Comment by ryanizer** [comment]
It should be possible to fake this, even if there is some GameStream restriction. i.e. when the pointer enters the window, capture it normally, when the mouse hits the edge of the window, release?

This would be a killer application for remote desktop with this feature!

**Comment by cgutman** [comment]
It's not that easy. The mouse ballistics are different for the host and client, so your cursor would move some arbitrary amount on the host, then leave the window and get uncaptured. The result would be that certain areas of the screen can't be clicked, just like how Android behaves without pointer capture prior to Oreo.
