### ISSUE TITLE
Audio delay

### ISSUE THREAD

**Issue by matthewvinton** [moonlight-stream/moonlight-qt#176]
When streaming, everything works except there is a noticeable audio delay - it feels like 200ms or so. I have tried this with 5.1 channel as well as 2 channel audio, with similar results. Streaming to an iOS client does not exhibit the issue. I have attached the log file.
[Moonlight-1549678228.log](https://github.com/moonlight-stream/moonlight-qt/files/2847425/Moonlight-1549678228.log)

**Comment by cgutman** [comment]
It looks like your audio device was being pretty screwy during the session.

It was initially opened at 11 seconds during connection establishment
```
00:00:11 - SDL Info (0): Starting audio stream...
00:00:11 - SDL Info (0): Audio backend: WASAPI
00:00:11 - SDL Info (0): Selected audio device: PanasonicTV0 (4- Intel(R) Display Audio)
00:00:11 - SDL Info (0): Native layout: <UNKNOWN> (6 channels)
00:00:11 - SDL Info (0): Audio buffer size: 3 packets
00:00:12 - SDL Info (0): Audio stream has 6 channels
```

Then it disappeared from the system at 12 seconds
```
00:00:12 - SDL Error (0): Audio rendering error: unrecoverable streaming failure
00:00:12 - SDL Warn (0): Reinitializing audio renderer after failure
00:00:13 - SDL Info (0): Audio backend: WASAPI
00:00:13 - SDL Error (0): No output device found
00:00:13 - SDL Info (0): Audio latency: 0
00:00:14 - SDL Info (0): Audio backend: WASAPI
00:00:14 - SDL Error (0): No output device found
00:00:14 - SDL Info (0): Audio latency: 0
```

and finally came back at 15 seconds:
```
00:00:15 - SDL Info (0): Audio backend: WASAPI
00:00:15 - SDL Info (0): Selected audio device: PanasonicTV0 (4- Intel(R) Display Audio)
00:00:15 - SDL Info (0): Native layout: <UNKNOWN> (6 channels)
00:00:15 - SDL Info (0): Audio buffer size: 3 packets
```

Did your TV do anything odd during that period that would have caused it to disconnect from the system?

**Comment by matthewvinton** [comment]
Interesting. It seemed rock solid from my perspective. It is pretty consistent with the “no audio device” message across different sessions though. 

And not that this means anything, but Steam In Home Streaming’s audio is synced. It just sucks most other ways. :-)

**Comment by matthewvinton** [comment]
So, your comment got me to thinking that perhaps there was some connection or handshake issues with the HDMI connection that was causing the audio interface to reset and cause issues with Moonlight.

So I decided to try a custom EDID file, and as I was working on that I noticed two things:

1. The display was set to 59hz. This is non-optimal, but I doubt was causing any issues.
2. Windows had detected the display (a Panasonic Plasma) as 3D, and was indicating that in the display properties.

So, I set the display to 60hz, and set the "3D" slider to off. I never implemented the custom EDID. I tested, and that seems to have resolved the issue. I am not getting the "No audio device found" errors any longer. Audio is blissfully in sync.

My probably incorrect theory is that there was a non-obvious mode change as it went into full screen as Moonlight started streaming that caused the audio device to disconnect.

So I think this one is resolved - but I wanted to post in case anyone else runs into this particular issue.

Thanks!

**Comment by cgutman** [comment]
Thanks for the info.

The issue in Moonlight is that we accumulate audio latency during the period of time that audio rendering is waiting for the new audio device to be initialized again when the default audio output changes while streaming. Fortunately the fix for that is fairly simple.
