### ISSUE TITLE
Quit session whit keyboard shortcuts v0.9

### ISSUE THREAD

**Issue by roncamma** [moonlight-stream/moonlight-qt#178]
**Describe the bug**
The shortcut CTRL+ALT+SHIFT+Q didn't work since 0.9 update

**Steps to reproduce**
Press CTRL+ALT+SHIFT+Q

**Affected games**
All. Other shortcuts such as Z,X,S works well

**Client PC details (please complete the following information)**
 - OS: Windows 10 1809
 - Moonlight Version: 0.9

**Server PC details (please complete the following information)**
 - OS: Windows 10 1809
 - GeForce Experience version: 3.17.0.126
 - Nvidia GPU driver: 418.91

**Moonlight Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
[Moonlight-1550431988.log](https://github.com/moonlight-stream/moonlight-qt/files/2873318/Moonlight-1550431988.log)

**Comment by cgutman** [comment]
What keyboard layout does your client PC have? Is it QWERTY or something else?

**Comment by roncamma** [comment]
Oh yes of course ! I'am using AZERTY.
So, if I press A instead of Q it works !
(In the previous version of Moonlight, Q in AZERTY layout had worked

**Comment by cgutman** [comment]
Fixed in https://github.com/moonlight-stream/moonlight-qt/commit/2a12b018da83ed2fa7f74eece2b02c1f62bad063 and released in v0.9.1.

Thanks for the report.

**Comment by roncamma** [comment]
Thanks cgutman for the fix !:)
