### ISSUE TITLE
Hope to add an option for sending with a composite key

### ISSUE THREAD

**Issue by 877598499** [moonlight-stream/moonlight-qt#179]
hope  to add a combined key option for sending function. Every time when I pressed  the Alt +Tap key, it  jumped back to the local computer and it depressed me.Thanks very much.

**Comment by cgutman** [comment]
Alt+Tab is one of the key combinations blacklisted by GeForce Experience. You can make your own hotkey to mimic Alt+Tab using AutoHotkey.

**Comment by WoolenWang** [comment]
> Alt+Tab is one of the key combinations blacklisted by GeForce Experience. You can make your own hotkey to mimic Alt+Tab using AutoHotkey.

my i ask if you can give one simple example code that using AutoHotkey and simply send Alt + Tab to moonlight host ?
