### ISSUE TITLE
SEGFAULT due to no layoutPolicy in QT Quick Controls Dialog Helper

### ISSUE THREAD

**Issue by mrkmg** [moonlight-stream/moonlight-qt#185]
**Describe the bug**
Upon launch, the application SEGFAULTS

**Steps to reproduce**
Launch application. Wait about 1 second. See error.

**Screenshots**
N/A

**Affected games**
N/A

**Moonlight settings (please complete the following information)**
N/A

**Client PC details (please complete the following information)**
 - OS: Manjaro, Kernel 4.19, NO DE, i3 WM, QT 5.12
 - Moonlight Version: Built from Source, master branch as of 2019-02-27

**Server PC details (please complete the following information)**
N/A

**Moonlight Logs (please attach)**
N/A (No logs are produced)

**Additional context**
I have narrowed the issue down to this line:

https://github.com/moonlight-stream/moonlight-qt/blob/8492482e559142e71d71d1bfbf6cbe14c0319ce4/app/main.cpp#L316

Basically, by calling ` QGuiApplication::setDesktopSettingsAware(false);` QT is unaware, or unable, to determine the layout needed to be used to render the dialog. That in turn causes a SEGFAULT when trying to load the addNewPc Dialog. Curiously, MessageDialogs work fine. When I change the parameter to `true`, everything works perfectly. 

I see the comment that dialogs were broken/not correct on Gnome, and by removing the awareness to the desktop settings fix that. Obviously, there are many more users on Gnome than those who do not run a DE at all, so just reverting this is not a fix. I have not figured out if there is yet a way to fix both problems though, mostly because I do not have a gnome test environment to address the bug on that side.

Any advice on how to proceed from here would be appreciated.

**Comment by cgutman** [comment]
That call works around https://github.com/moonlight-stream/moonlight-qt/issues/161 which was reported upstream https://github.com/FedoraQt/QGnomePlatform/issues/42

As far as I understand, that call prevents Qt from using platform or DE plugins, which makes it fall back to the base styles included with Qt. I'm not sure why it fails and crashes on your machine though.

**Comment by mrkmg** [comment]
I am willing to provide any configuration files, my setup, etc.

**Comment by cgutman** [comment]
Setting the app's palette to something other than QPalette(Qt::black) seems to fix it too, so I'm doing that now instead instead of setDesktopSettingsAware(false).

**Comment by mrkmg** [comment]
I have confirmed, at least on my system, that the lastest build from master works, and no longer segfaults.
