### ISSUE TITLE
key rctrl and rshift not recognized in game

### ISSUE THREAD

**Issue by alex333666333** [moonlight-stream/moonlight-qt#186]
Hello

In game (Cs:go, Day of Infamy), the keys Rctrl and Rshift don't work for me.
The layout keybord is FR (AZERTY)
In local game work fine, in streaming this keys don't work.

Rctrl and Rshift work with GTA4

I have try mstsc.exe, Big picture and direct launch.

Client PC and Server PC have the laster Geforce experience, laster drivers and Windows 1803 and work Gigabit ethernet.

Thank

**Comment by cgutman** [comment]
Are both client and server keyboards in AZERTY layout or just the client?

**Comment by alex333666333** [comment]
Yes, client and server are AZERTY.

**Comment by cgutman** [comment]
It seems like Moonlight is working properly if they work in any game at all. The bug may be on Nvidia's side.

@Jorys-Paulin can you verify this issue?

**Comment by alex333666333** [comment]
Ok, I tried with QWERTY layout and the problem is the same.

Soon, I will try a news/fresh installation of the windows/server

**Comment by cgutman** [comment]
Any luck?
