### ISSUE TITLE
Scrolling very slowly on Mac OS doesn't generate scroll events

### ISSUE THREAD

**Issue by neyz** [moonlight-stream/moonlight-qt#188]
**Describe the bug**
Scroll wheel increments are not being registered consistently

**Steps to reproduce**
Just try to scroll slowly in any webpage, 1 increment a second, and if slow enough the page will not scroll at all.

**Affected games**
Every game, even windows

**Client PC details (please complete the following information)**
OS: Mac OS Mojave
Moonlight Version: 0.9.1

**Server PC details (please complete the following information)**
OS: Windows 10 1809]
GeForce Experience version: [e.g. 3.17.0.126]
Nvidia GPU driver: [e.g. 419.17]

**Moonlight Logs (please attach)**
Logs attached
[Moonlight-1551736941.log](https://github.com/moonlight-stream/moonlight-qt/files/2928497/Moonlight-1551736941.log)
[Moonlight-1551737970.log](https://github.com/moonlight-stream/moonlight-qt/files/2928498/Moonlight-1551737970.log)
[Moonlight-1551737996.log](https://github.com/moonlight-stream/moonlight-qt/files/2928499/Moonlight-1551737996.log)

**Comment by cgutman** [comment]
This is a bug in SDL. It was fixed in https://github.com/spurious/SDL-mirror/commit/a2165147d3bfc2047cca104ffb329b7f24e3e5d1 but we can't update Mac to SDL 2.0.9 to get the fix because there are several significant blocker bugs.

https://bugzilla.libsdl.org/show_bug.cgi?id=4394
https://bugzilla.libsdl.org/show_bug.cgi?id=4395

**Comment by cgutman** [comment]
I wasn't really prioritizing the work to fix the macOS SDL bugs since there wasn't anything that 2.0.9 seemed like it would fix on macOS. Now that you've found this, I can put some more time into debugging SDL.

**Comment by neyz** [comment]
Congrats on the new release ! I hate to be that guy but the scroll wheel thing is really stopping me from using your application as the scroll events are often use in a precise way in programs / games. Is there anything i can do to help with this issue ?

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-qt/commit/5443165fcea90b0dbee1b64c2cc1190eba546a22
