### ISSUE TITLE
PC is currently busy error

### ISSUE THREAD

**Issue by simallaire** [moonlight-stream/moonlight-qt#189]
**Describe the bug**
When double clicking the host computer, I get the message that the host computer is busy.
I am using Ubuntu 18.10, it works perfectly on the same computer but Windows 10 Pro

**Steps to reproduce**
-Open moonlight on Ubuntu 18.10
-Click host PC from list or manually enter the host pc IP address.

**Moonlight settings (please complete the following information)**
Default settings and others

**Client PC details (please complete the following information)**
 - OS: Ubuntu 18.10
 - Moonlight Version: 0.9.1

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro
 - GeForce Experience version: 3.17.0.126
 - Nvidia GPU driver:  419.35

**Moonlight Logs (please attach)**

`error: app/com.moonlight_stream.Moonlight/x86_64/master not installed`

:/

**Comment by simallaire** [comment]
After an unknown series of actions, I made it work, but after I disconnected I still encountered similar problems.

**Comment by cgutman** [comment]
This message indicates that you need to pair before streaming for the first time (this will show up as a lock icon on the PC in Moonlight), but your PC must not be streaming a game when attempting to pair. Even if you're not actively playing a game with Moonlight, a stream must not be running (if you connect from a paired PC, this would show up with a Play icon on the active game). If you can't figure out which game is running for some reason, you can kill nvstreamer.exe on the host PC or simply reboot it to ensure the session is terminated.

If you have the same issue again, that may indicate that your pairing data is being deleted or failing to save. Keep in mind that the pairing is unique to the host PC and the client Moonlight installation. If you reinstall GeForce Experience on your host or reinstall Moonlight on the client, you will need to pair again.

If pairing is not persisting and you're following those steps, you can get the logs by running `moonlight` from the terminal. Attach them here as a file.
