### ISSUE TITLE
1920x1200 fullscreen resolution support

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#19]
Please add suport for fullscreen scaling (with black bars if possible) on some resoltions.
Namely on 1920x1200 the full screen scales to about 3 quarters of the image from the top leaving a quarter of the desktop still visibile on the bottom. In the chrome version it used to scale to full screen with black bars, while on the android version it goes for a full pixel to pixel scaling

**Comment by cgutman** [comment]
Can you link a screenshot or picture of exactly what you're seeing with the broken scaling?

**Comment by apoklyps3** [comment]
I'm running a laptop 1920x1080 with two external monitors 1920x1200
I want moonlight to run on one of the monitors as the chrome version did...
this is what I get with qt version:

https://ibb.co/iqRsrK

If I run moonlight-qt in full screen it defaults to the main monitor (the laptops display) and when I try to move it to another monitor it's not getting scaled to the whole screen as you can see.

**Comment by cgutman** [comment]
This should be fixed in https://github.com/moonlight-stream/moonlight-qt/commit/9cc20c27abff3fc8c10662ae6c80f2d3f7cccdc1
