### ISSUE TITLE
Native resolution not working on windows

### ISSUE THREAD

**Issue by BiatuAutMiahn** [moonlight-stream/moonlight-qt#190]
I'm getting a black border when using the native resolution, I tried setting host to native resolution, restarting nvidia services and rebooting host.

**Comment by cgutman** [comment]
Please provide:
- your host resolution
- your client resolution
- your chosen resolution in moonlight
- a screenshot of moonlight showing the issue

**Comment by BiatuAutMiahn** [comment]
sorry for the long delay
Host Res: 1280x720
Client: 1366x768
Chosen Resolution: Native/Any

Details:
No screenshot atm, but this seemed to happen when casting mstsc.exe (Desktop). If the desktop resolution was less than the Client the video would be placed in the top-left of the client's screen. When starting a game that used exclusive fullscreen, the video showed properly.
