### ISSUE TITLE
Native Windows touchscreen support for PCs with touchscreens

### ISSUE THREAD

**Issue by ExsertWizard** [moonlight-stream/moonlight-qt#191]
Native touch support would be nice for the client, currently when using the touchscreen in moonlight, the host's mouse reacts unexpectedly and I wonder if it's possible for the client to have native Windows touch support so that multi-touch gestures and that the host's cursor works properly with touchscreens.

**Comment by cgutman** [comment]
It's not possible to implement native touch support currently with GameStream. The crazy mouse bug when using the touchscreen is a bug in SDL that can be worked around by disabling raw input in Moonlight. https://github.com/moonlight-stream/moonlight-qt/issues/140
