### ISSUE TITLE
Mouse performance stuttering (yet video latency excellent)

### ISSUE THREAD

**Issue by CraigMason** [moonlight-stream/moonlight-qt#192]
**Describe the bug**
The mouse input it stuttering, resulting in a degraded appearance.

Visually it looks like dropped frames in games, but this is not the case; I verified this by using keyboard input only, running timedemos, and viewing 60fps video content remotely. This only manifests when using mouse/trackpad.

Touch input on iPad Pro (on same network with same settings) results in very smooth motion.

**Screenshots**
This is a demo recorded on the same network, with the same game session (resumed), with all of the same streaming settings. (720p, 60fps, 10Mbps).

https://www.youtube.com/watch?v=3eLNC8Nf0Yo&feature=youtu.be

The same performance is observed when changing any/all vsync/fps/bitrate settings. Whilst the latency of the video stream improves, the mouse input is the same.

Also, an example video showing a 60fps video playing remotely, with the mouse panning left/right. Note how the video doesn't drop any frames, but the mouse is juddering.

https://www.youtube.com/watch?v=yyNwmRja2yk

**Affected games**
This affects all games, and also mstsc.exe. The mouse movement is uniform in all games.

**Client PC details**
 - OS: Windows 10 1809
 - Moonlight Version: v0.9.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 1809
 - GeForce Experience version: 3.17.0.126
 - Nvidia GPU driver: 419.35

**Moonlight Logs (please attach)**
[Moonlight-1552483257.log](https://github.com/moonlight-stream/moonlight-qt/files/2961614/Moonlight-1552483257.log)

**Comment by cgutman** [comment]
Can you try v0.8.1 and see if the issue happens on that version too? I'd recommend the portable version so you don't interfere with your 0.9.1 installation for the next steps below.

If that still has the issue, can you switch back to 0.9.1, close Moonlight, then open a command prompt and run the following commands then try streaming in the Moonlight window that will open:
```
set SDL_JOYSTICK_HIDAPI=0
"C:\Program Files\Moonlight Game Streaming\Moonlight.exe"
```

**Comment by cgutman** [comment]
We got this settled on Discord. It turned out to be massive network jitter caused by a Killer Wireless-AC 1550 (9260NGW). Changing the adapter to N-mode seemed to resolve the issue.

**Comment by CraigMason** [comment]
Thanks for the time debugging this @cgutman 

Also worth noting, changing `MOUSE_POLLING_INTERVAL` to `10` had a (very) small but noticeable impact when streaming over the web.

**Comment by amadeok** [comment]
Hello,
I have the same issue, i tried changing my wireless adapter to N mode from device manager but it didn't help.

**Comment by 1yian** [comment]
Hi, I have the same problem described in this issue, does anyone know if this type of issue was solved yet?

**Comment by cgutman** [comment]
@1yian Open a new issue. These types of issues are highly specific to your streaming setup, so this particular issue with the Killer NIC is probably not relevant to you. Make sure you fully fill out the issue template too.
