### ISSUE TITLE
Stuck in 720p when using 1440p (or other "non-tv") resolution

### ISSUE THREAD

**Issue by dbackeus** [moonlight-stream/moonlight-qt#194]
**Describe the bug**
After chosing 1440p as resolution in the moonlight client settings and starting up Steam (or any other game directly) my host switches down to 720p resolution.

**Steps to reproduce**
- Start client
- Go to settings
- Chose 1440p resolution
- Run Steam

**Screenshots**
A screendump from MacOS (showing blurry 720p resolution upscaled to Macbook Pro's native fullscreen resolution):
![steam-720p](https://user-images.githubusercontent.com/3461/54439253-bb710e00-4738-11e9-813e-940c4a157dcd.png)

**Affected games**
- Steam Big Picture
- The Witness
- The Long Dark

Note that whichever resolution I chose inside the games themselves I end up with a 720p blurry mess in the client.

**Moonlight settings**
- 1440p resolution

**Client PC details**
 - OS: Tested in both MacOS 10.14.3 and Windows 10 1809 from a Macbook Pro 15" 2017 model as well as Windows 10 1809 on the hosting PC itself. All have the same behaviour.
 - Moonlight Version: 0.9.1

**Server PC details**
 - OS: Windows 10 1809
 - GeForce Experience version: 3.17.0.126
 - Nvidia GPU driver: 419.35

**Moonlight Logs (please attach)**
[Moonlight-1552661782.log](https://github.com/moonlight-stream/moonlight-qt/files/2971658/Moonlight-1552661782.log)

**Additional context**
I'm assuming this issue might be related to https://github.com/moonlight-stream/moonlight-qt/issues/111. If I chose 1080p or 4K resolution it appears to do the right thing. However I've noted other github issues which discuss custom resolutions as something perfectly doable so I'm confused as to what to expect here. 1440p would seem to offer me the best tradeoff between quality and encoding / bandwidth performance.

As long as these resolutions are selectable without any kind of warning or notice about them potentially not working at all in your UI I would consider this an issue with your client.

**Comment by cgutman** [comment]
Resolutions other than 720/1080/4K don't have Streaming Optimal Playable Settings (SOPS) for GameStream. When GFE lacks SOPS for a game, it will fall back to the lowest supported resolution, 720p.

For 1440p streaming, we request SOPS off (which I confirmed is happening in your log). You will get whatever resolution that the game is configured to use. You should be able to change the game resolution and that will stick in future 1440p game starts.

Steam is a special case though. It appears to get locked to 720p with no way to change it (due to Steam's inability to change display resolution). However, that shouldn't be a real problem, since Steam Big Picture is just the launcher for whatever game you actually want to play, which will be able to change resolution.

You can also just stream your full desktop, which will always run at your host's current resolution - https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop

**Comment by dbackeus** [comment]
Non of your suggestions appear to give the expected results. Here are my findings:

## The Witness

First off I'm pre-configuring The Witness to run in fullscreen mode at 1440p resolution as well as setting the Windows desktop to 1440p display resolution. Then...

### Moonlight client at 1440p resolution

Log: [the-witness-1440p-stream-1440p-resolution.log](https://github.com/moonlight-stream/moonlight-qt/files/2973876/the-witness-1440p-stream-1440p-resolution.log)
<img width="1680" alt="the-witness-1440p-stream-1440p-resolution-2" src="https://user-images.githubusercontent.com/3461/54475161-61328480-47ee-11e9-8ece-82dd3e2ec9b6.png">
<img width="1680" alt="the-witness-1440p-stream-1440p-resolution-1" src="https://user-images.githubusercontent.com/3461/54475162-61328480-47ee-11e9-91fc-c77a218daac2.png">

Again the host switches down the Windows desktop to 720p resolution and the image quality ends up a blurry mess.

### Moonlight client at 4K resolution
Log: [the-witness-4k-stream-1440p-resolution.log](https://github.com/moonlight-stream/moonlight-qt/files/2973881/the-witness-4k-stream-1440p-resolution.log)
<img width="1680" alt="the-witness-4k-stream-1440p-resolution-2" src="https://user-images.githubusercontent.com/3461/54475171-87582480-47ee-11e9-93f0-9b12948fb0c3.png">
<img width="1680" alt="the-witness-4k-stream-1440p-resolution-1" src="https://user-images.githubusercontent.com/3461/54475172-87582480-47ee-11e9-8b5f-d95134007f91.png">

Here we can see the 1440p in game resolution coming across totally crisp.

## Streaming the desktop via `mstsc.exe`

Result from setting up Gamestream to stream the entire desktop. Both windows desktop and Moonlight is configured to use 1440p.

Log: [Moonlight-1552739067.log](https://github.com/moonlight-stream/moonlight-qt/files/2973890/Moonlight-1552739067.log)
![Screenshot 2019-03-15 at 20 14 51](https://user-images.githubusercontent.com/3461/54475209-08afb700-47ef-11e9-946a-2a59cc7a188d.png)

Here for whatever reason the desktop is shrunk to a corner of the screen. The rest of the screen either ends up black (as in the screenshot) or displaying frozen Windows desktop graphics which can't be interacted with.

**Comment by cgutman** [comment]
Ah, I recognize this issue. Make sure your scaling setting is set to GPU.

![image](https://user-images.githubusercontent.com/2695644/54479918-8cfa3e00-47df-11e9-9778-6fd691ba77a9.png)

**Comment by taoi11** [comment]
> Ah, I recognize this issue. Make sure your scaling setting is set to GPU on the host PC.
> 
> ![image](https://user-images.githubusercontent.com/2695644/54479918-8cfa3e00-47df-11e9-9778-6fd691ba77a9.png)

Because I am running headless that display option is not available. 
![image](https://user-images.githubusercontent.com/27467151/178120657-2a06e523-154f-4344-8e8e-6fd3414d8151.png)

**Comment by Dinjoralo** [comment]
This issue seems to still be around in some form. On my Pixel 6 Pro with a 1440p screen, trying to play in 1440p causes my desktop to lower it's resolution to 720p. Other resolutions are set correctly, 1080p sets the desktop to 1080p, and 4K sets the desktop to 4K through Nvidia DSR.

**Comment by cgutman** [comment]
That's [a limitation of GeForce Experience](https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-does-my-host-pc-resolution-change-to-720p-when-i-start-streaming) not a bug in Moonlight itself.

**Comment by SeeDborg** [comment]
I confirm the issue is still around, it desperates me, I want to play with Moonlight in 1440p@120Hz and it seems impossible..
