### ISSUE TITLE
Please add an option to redirect certain keyboard shortcuts to remote PC

### ISSUE THREAD

**Issue by dany4president** [moonlight-stream/moonlight-qt#196]
Hi! I am studying far from my hometown and didn't want to ship my monitor here, so I play games on my laptop using Moonlight to stream my desktop PC.

I always start a Moonlight session by streaming the whole remote desktop (thanks to the short guide you provide) to be able to do some things on the remote PC before starting a game. A lot of times, while in-game, I would like to be able to Alt-Tab out of the game to do other things on the remote PC, or to open the remote PC Task Manager, and so on. 

Could you please add an option to redirect certain keyboard shortcuts to the remote PC (Alt-Tab, Ctrl+Shift+Esc , Windows key, etc.)? For reference, this feature is called "Immersive mode" on Parsec streaming software.

Thanks!

**Comment by cgutman** [comment]
Nvidia's server blocks those key combinations so this is not currently possible. However you can use software like AutoHotkey to bind the combo you want to a different key or key combo.
