### ISSUE TITLE
Mouse cursor moves when regaining focus (alt/tab)

### ISSUE THREAD

**Issue by CraigMason** [moonlight-stream/moonlight-qt#197]
**Describe the bug**
When Moonlight regains focus, the mouse cursor shifts position. This only happens in Fullscreen and Borderless Fullscreen.

**Steps to reproduce**
* Focus in moonlight, move the mouse to a known position
* Alt-tab out
* Immediately alt-tab in
* Mouse has changed positions

**Affected games**
I have tried primarily with mstsc.exe

**Moonlight settings (please complete the following information)**
Fullscreen and Borderless Windows

**Client PC details**
Windows, Moonlight 0.9.1 portable

**Server PC details**
Windows

**Comment by cgutman** [comment]
SDL sends us a spurious mouse move when it receives WM_ACTIVATE after Alt+Tabbing back into the window. I will file a bug with them.
