### ISSUE TITLE
Every time I use Moonlight, PC audio playback is stuck with Nvidia HDMI OUT as default

### ISSUE THREAD

**Issue by guitarjorge24** [moonlight-stream/moonlight-qt#199]
I use Moonlight on my laptop to stream my desktop PC into my laptop through mstsc.exe.
After I end the stream session on my laptop and return to my desktop PC, my desktop PC Playback Sound Device is set to Nvidia HDMI OUT as the default

![image](https://user-images.githubusercontent.com/12472021/54862634-f1ebf180-4d13-11e9-9cec-3acfb7bd70b2.png)

If I try to switch my default audio device to my usual device like my bluetooth headphones or monitor speaker, Nvidia HDMI OUT re-enables itself as the default audio device, meaning I can't hear anything at all.

The only solution I've found use my headphones as default again is to right click the Nvidia HDMI OUT device and disable it. However, once I run Moonlight the issue reappears.

Server:
OS: Windows 10 Pro 1809
Moonlight Version: v0.9.1
Geforce driver version: 419.35

Laptop/Client:
OS: Windows 10 Pro 1809
Moonlight Version: v0.9.1

**Comment by cgutman** [comment]
Are you actually quitting the game from Moonlight? You need to click the X button on mstsc.exe in Moonlight or enable the option to quit the game automatically when you close Moonlight.

**Comment by guitarjorge24** [comment]
Thank you that fixed it! I was not quitting in Moonlight, I was just Alt+F4-ing

**Comment by schmurtzm** [comment]
Just for information, a little trick to reinit nvidia streaming server and remove the blocked session : restart the service "NVIDIA LocalSystem Container".
You can do it by launching this command line (run cmd in administrator mode, then...)  : 

`net stop NvContainerLocalSystem & net start NvContainerLocalSystem`

**Comment by AtomicHaggis** [comment]
@schmurtzm That works perfectly.  I created a bat file on my desktop that I can run if it gets stuck.  Thanks!

**Comment by Caesaro72** [comment]
> Just for information, a little trick to reinit nvidia streaming server and remove the blocked session : restart the service "NVIDIA LocalSystem Container". You can do it by launching this command line (run cmd in administrator mode, then...) :
> 
> `net stop NvContainerLocalSystem & net start NvContainerLocalSystem`

@schmurtzm , could you please tell me how to create a bat file to execute the command .Waiting for your reply, thank yo so much.

**Comment by TomOStewart** [comment]
@Caesaro72 
1. create a text file
2. open the text file
3. write the command "net stop NvContainerLocalSystem & net start NvContainerLocalSystem" in the file
4. save the file as something.bat
5. double click the file

**Comment by Caesaro72** [comment]
Thank you so much for your help, happy new year 2024 from Spain

**Comment by casinowilhelm** [comment]
For anyone reading this, you have to run your .bat file in administrator mode, just double clicking it won't work.

**Comment by TattieMasher** [comment]
Just to add to the comment from @casinowilhelm , you can cut out running as admin every time if you follow these steps.

Make a shortcut to your .bat file
Right click the shortcut > Properties
Advanced
Run as Administrator

You can then run the bat script from the shortcut as admin, meaning just a double click every time.

**Comment by schmurtzm** [comment]
net stop NvContainerLocalSystem & net start NvContainerLocalSystem

**Comment by schmurtzm** [comment]
Hi, here a batch script which systematically run as admin (so no other configuration to do before double clicking on it).

```
@Echo Off
@Title "Moonlight audio fix" & mode con:cols=55 lines=10

FSUTIL DIRTY query %SystemDrive% >NUL || (
    PowerShell "Start-Process -FilePath cmd.exe -Args '/C CHDIR /D %CD% & "%0"' -Verb RunAs"
    EXIT
)

net stop NvContainerLocalSystem
net start NvContainerLocalSystem

echo Moonlight audio fix applied. 
timeout 2 > Nul
```


1. Create a text file
2. Open the text file
3. Copy / Paste the script above in the file
4. Save the file as `Moonlight_Sound_Fix.bat` (or `whatever.bat`)
5. Double click the file (it will ask for an elevation of privilege each time you run it)

**Comment by Caesaro72** [comment]
Got it, thanks!
