### ISSUE TITLE
Multimonitor fullscreen support

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#20]
Please add support for multimonitor configurations.
While the window can be moved and full screened on different monitor than the default one, it seems to be somewhat buggy as you get locked into that monitor and ALT+Tab moves the moonlight window to the main monitor..

**Comment by Jorys-Paulin** [comment]
@apoklyps3 That might be because Moonlight is currently running in exclusive fullscreen mode, not in borderless fullscreen mode. Adding an option in the settings should do it?

**Comment by apoklyps3** [comment]
might be the solution

**Comment by cgutman** [comment]
Moonlight already runs in borderless fullscreen.

Can you elaborate on the bugs please? I run 2 monitors on my machine and don't see any issues moving between displays.

**Comment by apoklyps3** [comment]
Maybe it's because the monitors are not all the same resolution and I'm trying to manually move moonlight to  a monitor that isn't set as the default monitor?

**Comment by apoklyps3** [comment]
the problem is that  the monitor moonlight wants to run on has to be the default monitor set in windows 10 (as far as I can tell)
I even tried borderless gaming app with moonlight and still jumps to default screen (usually I have the laptop screen as default screen) and trying to move it on another monitor doesn't give me full screen...
not sure if this is a windows 10 issue or moonlight-qt...

**Comment by cgutman** [comment]
@apoklyps3 v0.1.0 should solve several of these issues. Can you try it and report what's still broken?
