### ISSUE TITLE
moonlight for OpenEmbedded 3.0 possible?

### ISSUE THREAD

**Issue by juicypop** [moonlight-stream/moonlight-qt#201]
**Is your feature request related to a problem? Please describe.**
If so, the only problem would be that there hasn't been a single release for OE yet

**Describe the solution you'd like**
if possible, a simple port working on latest OE 3.0

**Describe alternatives you've considered**
hooking up an android box to my set-top-box, makes the perfect living room look ugly though

**Additional context**
just to describe why OE implementation would make sense:
I think there are a lot of Engima2 set-top-boxes out there these days, and they (mostly?) run on OE 3.0 
I haven't found anything recent that someone has managed to install moonlight on his set-top-box even though they get more popular day by day. Even Kodi for example has been ported for this architecture the last years. So it would be really nice to see a moonlight port too. Given the fact that my set-top-box (a VU Plus Solo 4k) is really powerful, has built in bluetooth it really would make sense to run moonlight directly on it as a plugin.

I'm willing to give more information/help to test it if someone would mind to fulfill this request. My linux and programming skills are very low but I try to do my best.

I hope I find supporters for this feature request.

**Comment by cgutman** [comment]
I'm not quite sure where to begin for an OpenEmbedded port. As far as I can tell, OE seems to just be a build system that other embedded distros are built upon.

They seem to already have build scripts for cross compiling Qt but I don't see SDL. Even assuming our dependencies were okay, we would still need to figure out the appropriate video acceleration API to use. I don't think embedded devices use the typical VA-API and VDPAU standards that Linux desktops use.

**Comment by juicypop** [comment]
Hmm ok I see, a lot of technical input is needed here.

If you point me into the right direction I could do some research on this topic if this would help
