### ISSUE TITLE
can I implement a gamestream server in android or linux, that can be connected by moonlight android client?

### ISSUE THREAD

**Issue by offbye** [moonlight-stream/moonlight-qt#202]
Is there a opensource  moonlight gamestream server  existed?

We want to integrate it in  our  android hardware box.
can I implement a gamestream server in android or linux, that can be connected by moonlight android client?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Can I implement a gamestream server in android or linux, that can be connected by moonlight android client?

**Describe alternatives you've considered**

**Additional context**

**Comment by cgutman** [comment]
Unfortunately, there is not an open-source GameStream server. It's definitely possible to write one, but nobody has done it as far as I know.

**Comment by mfisher87** [comment]
@cgutman I apologize if using a mention in a months-dead issue is bad etiquette. I considered opening a new issue, but that's probably worse! I couldn't find answers to my questions anywhere and I figured your team might be the best to ask.

Could you speculate on why there is no open-source (or even a closed-source alternative) GameStream server in the wild? I have been absolutely shocked with the GFE user experience (seriously, a web log-in to use my graphics card features?), not to mention security history. I've been looking in to alternatives, and I'm fairly puzzled as to why only a client-side open-source solution exists. Is there some licensing/legal reason why this hasn't been done, or is it purely a technical reverse-engineering problem?

P.S.: Huge :+1: on Moonlight from a happy user. My favorite use case is turning a tablet in to a wireless touch-enabled duplicate display, so I can watch the same content as my family in the living room from anywhere in the house in perfect sync.

**Comment by cgutman** [comment]
There's no legal reason I know of that this wouldn't be possible. I think it's just the reverse-engineering (or reverse-reverse-engineering if you're building a server based on Moonlight).

**Comment by batchfileframework** [comment]
Hi there, 

Just wanted to let you know, there now exists an open source gamestream compatible server it is called Sunshine and it works amazingly well. 

https://github.com/LizardByte/Sunshine/releases/tag/v0.21.0

It works for windows, mac & linux but unfortunately not android as far as I know.
