### ISSUE TITLE
RTSP Handshake failed with error -1

### ISSUE THREAD

**Issue by Gorklax** [moonlight-stream/moonlight-qt#203]
**Describe the bug**
Trying to connect to my home PC over internet from my office results in "RTSP Handshake failed with error -1" Only on PC though, I am able to connect using my phone.

**Client PC details**
 - OS: Windows 10
 - Moonlight Version: v.0.9.1

**Server PC details**
 - OS: Windows 10
 - GeForce Experience version: 3.18.0.94
 - Nvidia GPU driver: 419.67

**Additional context**
As mentioned above, it works on my phone, but not on the laptop. The only thing I can think of is that there are ports blocked by my office as my phone isn't on the same domain as the laptop. If that is case, someone let me know, and I'll mark the issue as closed.  

**Logs**

[Moonlight-1553707977.log](https://github.com/moonlight-stream/moonlight-qt/files/3014938/Moonlight-1553707977.log)
[Moonlight-1553708106.log](https://github.com/moonlight-stream/moonlight-qt/files/3014939/Moonlight-1553708106.log)
[Moonlight-1553707907.log](https://github.com/moonlight-stream/moonlight-qt/files/3014940/Moonlight-1553707907.log)

**Comment by cgutman** [comment]
My guess is that you're correct about the port being blocked by a firewall or something. If your phone works, it has to be something on the client network.

**Comment by Gorklax** [comment]
That's what I figured. I'll mark it as closed. Thanks!

**Comment by abahdirga997-lgtm** [comment]
> That's what I figured. I'll mark it as closed. Thanks!

Hi sir, the issue is still relevant. I'm currently experiencing the same issue on my laptop. The application won't work with the same error message, like RTSP Handshake Error. Have you finding the solution? Can you help me
