### ISSUE TITLE
WebOS / PS4 support

### ISSUE THREAD

**Issue by ErgoProxy1337** [moonlight-stream/moonlight-qt#204]
Hey,
--- WebOS ---
I have since some time an LG OLED55C8LLA and wanted to stream some games from my pc to my TV but noticed that nothing exists for the WebOS
No, Steam Link, no Moonlight no nothing.
Then after a while of frustration there overcome me the idea of porting the moonlight app by my own to the webOS but I`m new at this point.
I found out that the webOS is using Qt for software development and the moonlight exists as -qt version too so...

https://www.youtube.com/watch?v=VXjS_GQmBa0

Questions:
    - Would you try to port it as an app for webOS?
    - Or.. how hard could it be as a beginner in webOS / Qt development to port this app?
        My main used language is java / c# / .NetCore (and it exists some stuf to create Qt with c#)
        Alternative Python with the official PySide2
    - Does it work with webOS 4.0 and without an known jailbreak for root rights? (Even if I dont think there would be root right needed except maybe for the controller driver)
    - Qt / C++ learning curve even If I just want to port an app?

--- PS4 ---
Since its now possible to install own apps and play games on the ps4 too.. should it be possible to port maybe the Moonlight for the ps4 too like for the Vita. Would this be possible?

Would be nice to get an answer

**Comment by ErgoProxy1337** [comment]
can rly noone tell me if this is possible or not?

**Comment by cgutman** [comment]
We aren't going to be doing a webOS port officially in the near future, but you're welcome to try yourself or work with the community to find someone who wants to do it. It appears webOS as used by LG only supports HTML5 apps, which isn't a rich enough API set to port Moonlight. We would need native APIs for sockets and H.264 decoding at least.

I have no idea what porting to PS4 would involve.

**Comment by ErgoProxy1337** [comment]
But it already exists an -qt version. Why it isnt possible to port it when lg webos has built in qt?

**Comment by cgutman** [comment]
webOS might use Qt internally (most OSes are built in C/C++), but that doesn't mean the API is available to third party applications. Also the APIs available in the webOS Open Source Edition aren't necessarily available on webOS TV. Similarly native development was possible back on Palm webOS via their PDK, but it has seemingly been removed since LG has taken over. See LG's website: http://webostv.developer.lge.com/develop/building-your-first-web-app-webos-tv/

There are no references to building C++ or Qt-based applications for webOS. If you can find documentation that indicates that C++ is supported, it may be possible, but I haven't managed to find anything since Palm sold webOS years ago.

**Comment by ErgoProxy1337** [comment]
Okey. Ty for the answer and ur time!
I have atm not enough time to look about it. Could u maybe let this question for 1 week open so I could investigate a bit more? Maybe I could try to write an litle app with qt and try to load it on my tv. If this would work I would give an response back here. It would be rly cool to get it on an LG working cause I wouldnt need an extra device that has HDMI 2.0 for 4k streaming and so on and it could work out of the box.

**Comment by mirh** [comment]
PS4 homebrew uses [this sdk](https://github.com/orbisdev/liborbis) (unless you want to pirate the official SCEI one I guess), which I don't really think has h264 hardware decoding hooked up yet. 

Then, sw one could perhaps work with moderate resolutions, but it's not like you couldn't already do this in linux at this point.

**Comment by sak3r** [comment]
Hi, I'm planning on buying a ps4 given that it's now become simple to install homebrew and was trying to justify it by saying that even though i'm not planning on buying many games ill also be able to use moonlight to take advantage of the same controller, it's certainly more powerful than a raspberry pi 4.. Is it really that different than the vita or the switch?

**Comment by mirh** [comment]
The community is certainly.. direr. 
Anyhow, current sdk sits at: https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain

But it still lacks a H264 decoding library

**Comment by VVi3ard** [comment]
Hello,
I’m currently using the WebOS version of Moonlight, and it works great overall. However, I’ve noticed that my hardware struggles with 4K streaming above 20 Mbps, resulting in visible compression artifacts at this bitrate.
Additionally, constantly re-pairing controllers between my PS4 and TV is inconvenient, and purchasing separate controllers for the TV feels unnecessary.
I’m considering experimenting with Linux on my PS4 Pro to run Moonlight, but this approach is less seamless than a native homebrew solution would be. It’s surprising that the PS4 doesn’t seem to leverage hardware-accelerated H.264/H.265 decoding for streaming, given its ability to handle Blu-ray playback. Is there any hardware limitation preventing this, or could it be addressed in a potential native PS4 version?
Are there any updates or plans for developing a native Moonlight client for the PS4? I believe many users would benefit from a homebrew solution that utilizes the PS4’s hardware capabilities more effectively.
