### ISSUE TITLE
GFE error: cannot configure streamer (error 544)

### ISSUE THREAD

**Issue by MiatWarp** [moonlight-stream/moonlight-qt#205]
Hello.
I'm have three PCs in my room:
1. AMD 1700X CPU, RTX 2080, DDR4 32GB, 1gbps optical internet with static IP (ISP 1)
2. AMD 8350 CPU, GTX 1080, DDR3 32GB, 1gbps optical internet with static IP (ISP 1)
3. AMD 8320 CPU, GTX 10606, DDR3 32GB, 100mbps internet with static IP (ISP 2)

They been built in different time, but they have same windows 10 x64, same GeForce drivers, same GeForce experience. 
Today I'm stuck with the problem that's Moonlight working only on PC 2! When trying to connect to PC 1 or 3 via LAN from my windows laptop/different PC/Android 9 device I receive error 544 "Cannot configure streamer. (Error 544)". I'm tried to reinstall GFE (via DDU), GPU drivers, moonlight, changing moonlight settings, disabling firewall/windows defender (via registry) - nothing helps, same error on PC 1 and 3.

Every PC have Windows 10 PRO x64 v1809 
Last time when everything works - on moonlight v0.7

Screenshots from PC and Android:
![windowsos](https://user-images.githubusercontent.com/6636140/55427521-d5f81380-558f-11e9-94ae-d13b212d613b.jpg)

![android9](https://user-images.githubusercontent.com/6636140/55427524-d8f30400-558f-11e9-8496-8519e0ce365b.jpg)

Logs from laptop:
[Moonlight-1554229824.log](https://github.com/moonlight-stream/moonlight-qt/files/3035467/Moonlight-1554229824.log)

**Comment by cgutman** [comment]
The Moonlight logs aren't going to have much information on this. Grab the Nvidia logs from C:\ProgramData\NVIDIA Corporation\NvStream and I can have a look.

**Comment by MiatWarp** [comment]
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/3050381/NvStreamerCurrent.log)

**Comment by cgutman** [comment]
Hmm, it's failing even earlier than that log really captures.

Can you upload all the logs in C:\ProgramData\NVIDIA Corporation\NvStreamSvc

**Comment by MiatWarp** [comment]
[nvstreamsvc.zip](https://github.com/moonlight-stream/moonlight-qt/files/3051370/nvstreamsvc.zip)

**Comment by cgutman** [comment]
Can you try to stream twice, then upload both NvStreamSvc and NvStream logs? I'm not able to cross-reference between the two because it looks like the service was restarted or the machine was rebooted in between.

**Comment by MiatWarp** [comment]
Sorry, this is because I'm stop stream services to get logs, because their files are been in use.
Here are fresh logs: 
[Logs.zip](https://github.com/moonlight-stream/moonlight-qt/files/3057893/Logs.zip)

**Comment by cgutman** [comment]
```
#2(E)[2019-04-09 08:28:05,273]=11:28:05={000022E0}<AudioEndpointCon> Failed to register audio endpoint in 2000 ms
#3(I)[2019-04-09 08:28:05,273]=11:28:05={000022E0}<NvStreamUserAgen> Failed to set nvvad configuration, failing session
```

This usually happens if you've renamed the NVIDIA Virtual Audio Device to something else. NVIDIA detects it by name unfortunately. Change the name back to "NVIDIA HDMI Out" and it should work again.

![image](https://user-images.githubusercontent.com/2695644/55845891-828a4600-5af8-11e9-9b73-f15b9e0e4606.png)

**Comment by MiatWarp** [comment]
Thanks! Renaming "NVidia" to "NVIDIA HDMI Out" solve the problem!

**Comment by Dantano89** [comment]
Hi Both,

I seem to be experiencing a similar issue.

I get the 'connection failed - cannot configure steamer' error.

The only way I can fix it is to start moonlight on my ipad with sound coming from PC then switch it over once its connected. I ahve tried changing the output names and it did not work. (not sure if mine should be called something different)

Please can either of you support?

Thanks

**Comment by Dantano89** [comment]
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/3129521/NvStreamerCurrent.log)
[NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-qt/files/3129522/NvStreamerOld.log)

 These are the two log

files showing in folder.

Thanks

**Comment by zentz03** [comment]
Can some1 help me I can't fix this T_T

**Comment by Lubensius** [comment]
For those who stumble over this issue after updating to Nvidia 441.66 and having Oculus Software installed.
I got this error 544 after update. Before moonlight worked fine for month.
The NVIDIA Vitual Audio Device is no longer existing after the update.
The solution for me was to enable "Play audio on host PC" in the settings.
Funny thing is, it plays now on both, steamlink and PC.

**Comment by zentz03** [comment]
Thank you . It worked for me . 😄😄

**Comment by supamas** [comment]
That fix did not work for me

**Comment by Casuallynoted** [comment]
I'm getting a consistent alternating 521 and 544 error when trying to connect from my Mac to my PC for game streaming. I don't see an option in moonlight to play audio on host pc, and restarting my PC doesn't seem to fix it.
