### ISSUE TITLE
[Linux] UI scaling issue

### ISSUE THREAD

**Issue by TimsManter** [moonlight-stream/moonlight-qt#21]
UI scaling is too big on GPD Win 2 when run in landscape orientation. It probably has something to do with default screen orientation (portrait) and that Gnome treats portrait as landscape and landscape as portrait for some reason. Althoungh this doesn't happen in other apps nor in Windows. Streaming by itself works perfectly.

Latest master / latest Arch/Gnome

Screenshots:

Landscape | Portrait | Orientations
--- |---|---
![screenshot from 2018-08-01 13-37-37](https://user-images.githubusercontent.com/5507688/43515326-7cab7862-9582-11e8-8f7c-edf077c28583.png) | ![screenshot from 2018-08-01 13-43-36](https://user-images.githubusercontent.com/5507688/43515339-894f666e-9582-11e8-916e-f654449f4b61.png) | ![screenshot from 2018-08-01 13-46-55](https://user-images.githubusercontent.com/5507688/43515341-8b01d8b6-9582-11e8-9a93-5d67619eacca.png)

**Comment by TimsManter** [comment]
I found a workaround to this issue. By adding `QT_SCALE_FACTOR` variable e.g:
```sh
QT_SCALE_FACTOR=0.4 ./moonlight
```
app become usable. Some labels like in header or options are too small but this isn't much a pain.

**Comment by cgutman** [comment]
My guess is that this is something to do with GNOME/Mutter not properly handing the GPD Win 2. I think it should be fixed on their end but in the meantime your workaround works.

**Comment by badjware** [comment]
I am having the exact same issue on my laptop. (ASUS TP300L, not a GPD Win 2)

I am running from master on archlinux / i3 / compton. I am not running GNOME.

**Comment by cgutman** [comment]
@badjware does passing a custom scale factor work for you too?

**Comment by badjware** [comment]
I figured it out, my dpi settings where wrong.

Sorry for taking your time.
