### ISSUE TITLE
Icon / Graphic

### ISSUE THREAD

**Issue by Byron1c** [moonlight-stream/moonlight-qt#210]
**Is your feature request related to a problem? Please describe.**
No - not a problem at all :)

**Describe the solution you'd like**
Just a suggestion on the application icon... no specific solution (maybe a nicer icon?)
I created these to use on my pc

**Describe alternatives you've considered**
Status quo is fine :D

**Additional context**
![MoonLight4_512](https://user-images.githubusercontent.com/16605489/55770761-a469d580-5ac4-11e9-98f1-ece2800850e8.png)

![MoonLight2_512](https://user-images.githubusercontent.com/16605489/55770777-af246a80-5ac4-11e9-88ba-c20fa9da0667.png)

**Comment by Byron1c** [comment]
The first one looks better as a small icon (better contrast), but I do like the second one better myself

**Comment by cgutman** [comment]
Thanks for the contribution.

We're not really looking to change the icon at the moment. It's a pretty large amount of work to change it and regenerate assets for all app icons, promotional art used on the App Store and Play Store, and various copies used for different purposes within each app.
