### ISSUE TITLE
VDPAU through VAAPI broken

### ISSUE THREAD

**Issue by ph1lt0r** [moonlight-stream/moonlight-qt#214]
Since moving to version 0.10 I've not been able to use hardware acceleration. Logs below:

libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
00:00:10 - SDL Info (0): Initialized VAAPI 0.39
00:00:10 - SDL Info (0): Driver: Intel i965 driver for Intel(R) Haswell Mobile - 1.7.3
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Format 0x32315659 -> yuv420p.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Format 0x30323449 -> unknown.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Format 0x3231564e -> nv12.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Format 0x32595559 -> yuyv422.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Format 0x59565955 -> uyvy422.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Format 0x48323234 -> yuv422p.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Format 0x58424752 -> rgb0.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Format 0x58524742 -> bgr0.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Format 0x30313050 -> p010le.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] VAAPI driver: Intel i965 driver for Intel(R) Haswell Mobile - 1.7.3.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc24bb00] Matched driver string as known nonstandard driver "Intel i965 (Quick Sync)", setting quirks (0x2).
00:00:10 - SDL Info (0): Using VAAPI accelerated renderer on X11
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Decoding VPS
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Main profile bitstream
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Decoding SPS
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Main profile bitstream
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Decoding VUI
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Decoding PPS
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Format vaapi_vld chosen by get_format().
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Format vaapi_vld requires hwaccel initialisation.
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] No support for codec hevc profile 1.
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Format vaapi_vld not usable, retrying get_format() without it.
00:00:10 - FFmpeg: [hevc @ 0x55eefc24d440] Error parsing NAL unit #3.
00:00:10 - SDL Warn (0): Test decode failed: Operation not permitted
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x55eefc224400] VDPAU device creation on X11 display :0 failed.
00:00:10 - SDL Error (0): Failed to create VDPAU context: -1313558101
Segmentation fault

**Comment by cgutman** [comment]
Did you get this one sorted out? I believe the issue is outdated VA-API libraries.

**Comment by ph1lt0r** [comment]
Sadly not yet, I've updated to VA-API versions as well as intel drivers:


00:00:00 - SDL Info (0): Loaded 24 new gamepad mappings
00:00:00 - Qt Debug: Current Moonlight version: "0.10.0"
00:00:02 - Qt Warning: qrc:/gui/AppView.qml:7:1: QML AppView: StackView has detected conflicting anchors. Transitions may not execute properly.
00:00:02 - Qt Warning: qrc:/gui/PcView.qml:9:1: QML PcView: StackView has detected conflicting anchors. Transitions may not execute properly.
00:00:04 - Qt Warning: qrc:/gui/AppView.qml:7:1: QML AppView: StackView has detected conflicting anchors. Transitions may not execute properly.
00:00:04 - Qt Info: Server GPU: "GeForce GTX 1080"
00:00:04 - Qt Info: Server GFE version: "3.18.0.102"
00:00:04 - SDL Info (0): Encoder configured for 4 slices per frame
00:00:04 - SDL Info (0): Video bitrate: 8000 kbps
00:00:04 - SDL Info (0): Audio configuration: 0
00:00:04 - SDL Info (0): V-sync enabled
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
00:00:04 - SDL Info (0): Initialized VAAPI 1.4
00:00:04 - SDL Info (0): Driver: Intel i965 driver for Intel(R) Haswell Mobile - 2.3.0
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Format 0x32315659 -> yuv420p.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Format 0x30323449 -> yuv420p.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Format 0x3231564e -> nv12.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Format 0x32595559 -> yuyv422.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Format 0x59565955 -> uyvy422.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Format 0x48323234 -> yuv422p.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Format 0x58424752 -> rgb0.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Format 0x58524742 -> bgr0.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Format 0x30313050 -> p010le.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] VAAPI driver: Intel i965 driver for Intel(R) Haswell Mobile - 2.3.0.
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a446b3500] Driver not found in known nonstandard list, using standard behaviour.
00:00:04 - SDL Info (0): Using VAAPI accelerated renderer on X11
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Decoding VPS
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Main profile bitstream
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Decoding SPS
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Main profile bitstream
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Decoding VUI
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Decoding PPS
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Format vaapi_vld chosen by get_format().
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Format vaapi_vld requires hwaccel initialisation.
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] No support for codec hevc profile 1.
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Format vaapi_vld not usable, retrying get_format() without it.
00:00:04 - FFmpeg: [hevc @ 0x558a446b07c0] Error parsing NAL unit #3.
00:00:04 - SDL Warn (0): Test decode failed: Operation not permitted
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
00:00:04 - FFmpeg: [AVHWDeviceContext @ 0x558a46950d80] VDPAU device creation on X11 display :0 failed.
00:00:04 - SDL Error (0): Failed to create VDPAU context: -1313558101
Segmentation fault

It appears I'm lacking support for the HEVC profile 1 codec (I believe that's x265)

**Comment by ph1lt0r** [comment]
Backtrace results

#0  0x0000000000000041 in ?? ()
#1  0x00005555555c279d in FFmpegVideoDecoder::reset (this=this@entry=0x55555606b990) at streaming/video/ffmpeg.cpp:122
#2  0x00005555555c34ba in FFmpegVideoDecoder::initialize(_DECODER_PARAMETERS*) () at streaming/video/ffmpeg.cpp:462
#3  0x00005555555b2107 in Session::chooseDecoder(StreamingPreferences::VideoDecoderSelection, SDL_Window*, int, int, int, int, bool, bool, bool, IVideoDecoder*&) () at streaming/session.cpp:182
#4  0x00005555555b219d in Session::isHardwareDecodeAvailable (window=window@entry=0x5555560c2300, vds=<optimized out>, 
    videoFormat=videoFormat@entry=256, width=<optimized out>, height=<optimized out>, frameRate=<optimized out>) at streaming/session.cpp:262
#5  0x00005555555b2ffb in Session::initialize() () at streaming/session.cpp:384
#6  0x00005555555b30a7 in Session::exec(int, int) () at streaming/session.cpp:818
#7  0x00005555555c94d9 in Session::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () at release/moc_session.cpp:112
#8  0x00005555555c9693 in Session::qt_metacall (this=0x55555850fca0, _c=QMetaObject::InvokeMetaMethod, _id=7, _a=0x7fffffffb370)
    at release/moc_session.cpp:195
#9  0x00007ffff2d0d9c9 in ?? () from /usr/lib64/libQt5Qml.so.5
#10 0x00007ffff2c729f5 in ?? () from /usr/lib64/libQt5Qml.so.5
#11 0x00007ffff2c7435f in ?? () from /usr/lib64/libQt5Qml.so.5
#12 0x00007ffff2c74fe6 in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const () from /usr/lib64/libQt5Qml.so.5
#13 0x00007ffff2c8edc4 in QV4::Runtime::method_callProperty(QV4::ExecutionEngine*, QV4::Value*, int, QV4::Value*, int) ()
   from /usr/lib64/libQt5Qml.so.5
#14 0x00007ffff2c82426 in ?? () from /usr/lib64/libQt5Qml.so.5
#15 0x00007ffff2d3d2d5 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () from /usr/lib64/libQt5Qml.so.5
#16 0x00007ffff2ccc021 in QQmlBoundSignalExpression::evaluate(void**) () from /usr/lib64/libQt5Qml.so.5
#17 0x00007ffff2ccd393 in ?? () from /usr/lib64/libQt5Qml.so.5
#18 0x00007ffff2d17c93 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib64/libQt5Qml.so.5
#19 0x00007ffff2cae759 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib64/libQt5Qml.so.5
#20 0x00007ffff22db13f in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#21 0x00007ffff44c51f6 in ?? () from /usr/lib64/libQt5Quick.so.5
#22 0x00007ffff2cc78ef in ?? () from /usr/lib64/libQt5Qml.so.5
#23 0x00007ffff2cc7ef2 in QQmlIncubationController::incubateFor(int) () from /usr/lib64/libQt5Qml.so.5
#24 0x00007ffff44417a8 in ?? () from /usr/lib64/libQt5Quick.so.5
#25 0x00007ffff22dc51b in QObject::event(QEvent*) () from /usr/lib64/libQt5Core.so.5
#26 0x00007ffff22b223a in ?? () from /usr/lib64/libQt5Core.so.5
#27 0x00007ffff22b2327 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#28 0x00007ffff23043db in QTimerInfoList::activateTimers() () from /usr/lib64/libQt5Core.so.5
#29 0x00007ffff2304d0c in ?? () from /usr/lib64/libQt5Core.so.5
#30 0x00007fffeda1f22d in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#31 0x00007fffeda1f4c8 in ?? () from /usr/lib64/libglib-2.0.so.0
#32 0x00007fffeda1f55c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#33 0x00007ffff230510f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#34 0x00007fffdf1c1741 in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#35 0x00007ffff22b111a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#36 0x00007ffff22b9b00 in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#37 0x0000555555575feb in main () at main.cpp:458
#38 0x00007ffff0ea075b in __libc_start_main () from /lib64/libc.so.6
#39 0x00005555555765aa in _start () at main.cpp:325
