### ISSUE TITLE
Moonlight kills Mousewithoutborders

### ISSUE THREAD

**Issue by BubiBalboa** [moonlight-stream/moonlight-qt#215]
**Describe the bug**
When I open a connection with Moonlight (PC) the background processes "Mouse without Borders" and "Mouse without Borders Helper" are terminated. It happens reliably every time. It only happens on the machine where Moonlight is running.

**Steps to reproduce**
Run Mousewithoutborders, start Moonlight, open connection to a game, processes disappear

**Screenshots**
N/A

**Affected games**
all of them

**Moonlight settings (please complete the following information)**
Changing the settings does not seem to make a difference

**Client PC details (please complete the following information)**
 - OS: Windows 10 1809
 - Moonlight PC v0.9.1 & v0.10.0

**Server PC details (please complete the following information)**
 - OS:  Windows 10 1809
 - GeForce Experience version: 3.18.0.120
 - Nvidia GPU driver: 419.67

**Moonlight Logs (please attach)**
[Moonlight-1555101907.log](https://github.com/moonlight-stream/moonlight-qt/files/3075128/Moonlight-1555101907.log)

**Comment by cgutman** [comment]
This is a problem with Mouse Without Borders. You should open a ticket with them.

MouseWithoutBorders.exe runs as SYSTEM, so it's not possible for Moonlight to kill this process if even if it tried because Moonlight doesn't run as admin. It must be the MouseWithoutBorders.exe process itself that crashes or decides to kills itself for some reason.

**Comment by BubiBalboa** [comment]
I'll try but the development of MouseWithoutBorders is really slow, the latest release is more than a year old. It would be nice if you guys could still at least take a look if it is something obvious on your side. I run many different programs  and none has this issue.

MouseWithoutBordersHelper.exe runs as USER btw.

**Comment by BubiBalboa** [comment]
I just read through the documentation of MouseWithoutBorders and found out that both  programs use Ctrl+Alt+Shift+Q. This hotkey quits MWB. Changing the hotkey in MWB solved the problem.
