### ISSUE TITLE
Can't create openGL context, openGL 2.0 required, works in previous version. (nVidia ION LE)

### ISSUE THREAD

**Issue by nikleonard** [moonlight-stream/moonlight-qt#216]
Moonlight crashes on startup with the following error:

"Qt_ Fatal: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH."

Tested with windows x64 build, on Windows 10 x64 build 1810 in a Acer Aspire Revo R3600 with nVIdia ION graphics. Previous version (0.9.1) works flawlessly. Tested in normal and portable versions. nVidia driver version 342.01 (last version that supports ION)

Log:
00:00:09 - Qt Warning: QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
00:00:09 - Qt Warning: QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
00:00:09 - Qt Warning: QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
00:00:09 - Qt Warning: QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
00:00:10 - Qt Info: Found "gamecontrollerdb.txt" at "C:/Users/****/Downloads/MoonlightPortable-x64-0.10.0/gamecontrollerdb.txt"
00:00:10 - SDL Info (0): Loaded 18 new gamepad mappings
00:00:10 - SDL Info (0): V-sync enabled
00:00:10 - SDL Info (0): Windowed mode with DWM running
00:00:10 - SDL Info (0): Windowed: 1 | Present Interval: 80000000
00:00:11 - SDL Info (0): Detected GPU: NVIDIA ION LE (10de:87e)
00:00:11 - SDL Info (0): GPU driver: nvd3dumx.dll 21.21.13.4201
00:00:11 - SDL Info (0): Using DXVA2 accelerated renderer
00:00:11 - FFmpeg: [h264 @ 0000020FA83C8FC0] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:11 - FFmpeg: [h264 @ 0000020FA83C8FC0] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:11 - FFmpeg: [h264 @ 0000020FA83C8FC0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:11 - FFmpeg: [h264 @ 0000020FA83C8FC0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:11 - FFmpeg: [h264 @ 0000020FA83C8FC0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:11 - FFmpeg: [h264 @ 0000020FA83C8FC0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:11 - FFmpeg: [h264 @ 0000020FA83C8FC0] Format dxva2_vld chosen by get_format().
00:00:11 - FFmpeg: [h264 @ 0000020FA83C8FC0] Format dxva2_vld requires hwaccel initialisation.
00:00:11 - FFmpeg: [h264 @ 0000020FA83C8FC0] Reinit context to 1280x720, pix_fmt: dxva2_vld
00:00:11 - SDL Info (0): DXVA2 decoder surface high-water mark: 0
00:00:11 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:14 - Qt Warning: QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
00:00:14 - Qt Warning: QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
00:00:14 - Qt Warning: QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
00:00:14 - Qt Warning: QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
00:00:15 - Qt Warning: QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
00:00:15 - Qt Warning: QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
00:01:16 - Qt Fatal: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.

**Comment by cgutman** [comment]
Strange. It might be related to the update from Qt 5.12.1 to 5.12.2.

Do you have libEGL.dll, libGLESv2.dll, and d3dcompiler_47.dll in the folder where you extracted Moonlight?

Can you try MoonlightPortable-x64-release.zip from https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/23819531/job/5de324qklc94rc6v/artifacts and see if the issue persists with that version?

**Comment by nikleonard** [comment]
Do you have libEGL.dll, libGLESv2.dll, and d3dcompiler_47.dll in the folder where you extracted Moonlight?
Yes, I have that files in the app folder.

Can you try MoonlightPortable-x64-release.zip from https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/23819531/job/5de324qklc94rc6v/artifacts and see if the issue persists with that version?
I tried this version and it works fine. No errors whatsoever.

**Comment by cgutman** [comment]
OK, so it's definitely the Qt 5.12.2 update causing the problem.

**Comment by cgutman** [comment]
This was a Qt bug fixed in 5.12.3.

https://bugreports.qt.io/browse/QTBUG-75111
