### ISSUE TITLE
Moonlight Portable writing to Windows user folder

### ISSUE THREAD

**Issue by somerandomperson123** [moonlight-stream/moonlight-qt#217]
Moonlight Portable is once again writing to the user folder.  
\user(username)\AppData\Local\Moonlight Game Streaming Project\Moonlight\cache\qmlcache

Issue was fixed previously but looks like it's returned.

https://github.com/moonlight-stream/moonlight-qt/issues/86

**Comment by cgutman** [comment]
It broke in in Moonlight v0.8.0 with the update to Qt 5.12.0. It looks like they stopped creating the qmlc files during the build, so I manually do so now.
