### ISSUE TITLE
Struggling to get Steam Link version working

### ISSUE THREAD

**Issue by marmite22** [moonlight-stream/moonlight-qt#218]
**Describe the bug**
I followed the instructions but haven't been able to get it working

**Steps to reproduce**
1. Formatted USB drive. I've tried NTFS and Fat32
2. Extracted contents of zip to H:\steamlink\apps\moonlight
3. Inserted drive into steam link
4. Restarted Steam Link

**Expected result**
Not sure exactly - I guess I thought it would boot into a different screen or have some option to select an app?

**Actual result**
The Steam Link started as usual - I could see no reference to Moonlight or see anyway to enable it.

**Comment by cgutman** [comment]
You should extract the zip into the root of the drive, so that the final layout is H:\steamlink\apps\moonlight. The zip already contains the folder hierarchy that you need.

**Comment by marmite22** [comment]
Sorry, I wasn't clear there. I did extract to the root - the path I posted is the final structure, not the directory I extracted the zip to!

**Comment by cgutman** [comment]
You're sure the drive is FAT32 not ExFAT? https://github.com/ValveSoftware/steamlink-sdk#deploying

**Comment by marmite22** [comment]
Not 100% sure! I'll check again tonight when I get home.

Thanks for the link - I'll have a read through and see if I can figure stuff out.

Just so I'm clear - when it works, is it obvious? Like will the Steam Link boot to a different OS or something or am I looking for a new option to appear or what? I've never tried to run anything else on it before.

**Comment by marmite22** [comment]
I did that classic thing of changing two variables at once. I re-formatted the drive and ensured it was FAT32 and then after plugging it in I actually pulled the power out the back of the Steam Link and then plugged it back in. Before I'd just been turning it off using the UI.

Not sure which thing solved the problem, but it works now!
