### ISSUE TITLE
Stream dropping frequently on macOS client since GPU upgrade on host

### ISSUE THREAD

**Issue by bpmcl** [moonlight-stream/moonlight-qt#219]
I recently upgraded the GPU on my Windows host from a GTX 770 to an RTX 2070. However, since then, I have noticed a large increase in the frequency of the stream dropping out suddenly with a "Connection terminated" error. This can happen within seconds of starting a stream, or after a much longer period, even when the stream is seemingly flawless otherwise. It occurs regardless of what is being played on the host, or the quality settings of the stream.

When I upgraded, I performed a full cleanup and reinstall of the host drivers, so I don't think it would be a host driver issue.

**Moonlight settings**
Most settings are default, but I have tried to run at various quality settings with no luck. I also run Moonlight in Borderless Windowed mode, but switching back to Full-screen had no effect.

**Client PC details**
 - OS: macOS 10.14.3
 - Moonlight Version: v0.10.0

**Server PC details**
 - OS: Windows 10 1809
 - GeForce Experience version: 3.18.0.102
 - Nvidia GPU driver: 425.31

**Moonlight Logs**
[Moonlight-1555786666.log](https://github.com/moonlight-stream/moonlight-qt/files/3100517/Moonlight-1555786666.log)

**Comment by cgutman** [comment]
I'll need host logs to debug this, because it appears to be the host terminating the connection.

GameStream logs can be found on the host in "C:\ProgramData\NVIDIA Corporation\NvStream".
"C:\ProgramData" is a hidden folder, so you may need to enable viewing hidden files or type the path into File Explorer manually

**Comment by bpmcl** [comment]
This isn't the exact matching host log, but it's from another instance where the stream started but terminated after a few seconds. The stream has been holding steady at 1440p for the last hour or so, so I can't replicate the issue right now to generate a fresh log. Unfortunately, the issue is intermittent, but seems much more frequent since the upgrade.
[streamissues.txt](https://github.com/moonlight-stream/moonlight-qt/files/3100615/streamissues.txt)

**Comment by bpmcl** [comment]
Issue has started occurring again, and I managed to get a fresh client and host log:
[Moonlight-1556053926.log](https://github.com/moonlight-stream/moonlight-qt/files/3109658/Moonlight-1556053926.log)
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/3109660/NvStreamerCurrent.log)
