### ISSUE TITLE
Video decoder on "Auto" causes some strange taring/cuts

### ISSUE THREAD

**Issue by jacobmix** [moonlight-stream/moonlight-qt#22]
My friend has a NVIDIA GeForce GTX 1050 Ti. I got a GTX 970.
This is what he get's when he connects to me with video decoder on auto:
https://gyazo.com/9d9b2428a4759647954c984d58546f67
The screenshot is a bit werid tho. When he pressed prt sc it activated my screen taking tool lightshot.
For some reason there's two versions up my desktop at the top,
and what looks as 2 black versions on the bottom.
(He also lagged a bit when we got playing using software decoding)
More info will be added as we test, and brainstorm in the Discord.

**Comment by cgutman** [comment]
Can you grab the latest Moonlight log from %TEMP% after an affected session?

**Comment by cgutman** [comment]
This may also be fixed in v0.1.0. Please try that too.
