### ISSUE TITLE
[Controller] Settings scrolling not working

### ISSUE THREAD

**Issue by Jorys-Paulin** [moonlight-stream/moonlight-qt#220]
**Describe the bug**
When inside the settings page, you can focus options normally hidden without scrolling down, however when focusing them it doesn't make the page scroll down to them, so they remain invisible.

**Steps to reproduce**
On a Steam Link with an Xbox 360 controller connected, go to the settings page, and focus down the options. On my screen (1080p60, but the UI seems lower resolution), "Show connection quality warnings" is hidden, but can still be focused and interacted with, even tough it remains hidden by the scrolling.

**Screenshots**
Can't do proper snapshots, but the page doesn't scroll when supposed to

**Affected games**
The app menus are affected

**Moonlight settings (please complete the following information)**
All settings default

**Client PC details (please complete the following information)**
 - OS: Steam Link
 - Moonlight Version: v0.10.0

**Server PC details (please complete the following information)**
I haven't added any server PC yet

**Moonlight Logs (please attach)**
[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/3101036/moonlight.log)

**Additional context**
I also saw that the gamepad mapping aren't ideal: for scrolling vertically inside a select element, I had to use the horizontal axis of stick and vice versa

**Comment by Jorys-Paulin** [comment]
Just confirmed that the issue also happens on desktop, still with the same Xbox controller attached

**Comment by JelledFro** [comment]
I also had this problem, at first I thought the resolution was off. But now it seems more like scrolling in the options menu doesn't work with a controller. Should be fairly simple to make one of the sticks emulate the the scroll function, right? 
I would also suggest that it's a bit more intuitive to change it so you highlight between "computer", "options" & "add new host" with the controller and select with the A button (on an xbox or switch controller that is) as opposed to pressing start for options and not being able to add a new host without using a mouse. This is the behavior of the steam link top menu, so it would be nice if moonlight mirrored this in it's own menu :)
