### ISSUE TITLE
Host PC: If the screen is locked, "nvstreamer.exe" does not terminate upon session quit.

### ISSUE THREAD

**Issue by PKCheap** [moonlight-stream/moonlight-qt#222]
To reproduce:
- Start with the host PC locked.
- Select any game on your client device. 
- After connecting successfully, back out and quit the session.
- On the Host PC, launch your task manager. "Nvidia Streamer Server Component" (Process name for nvstreamer.exe) will still be running.

This does not appear to be affected by Moonlight settings.

Client details:
- OS: Android 9, Build number 47.2.A.10.28
- Moonlight Version: v7.1

Server PC details:
 - OS: Windows 10 1809
 - GeForce Experience version: 3.18.0.102
 - Nvidia GPU driver: 425.31

**Comment by PKCheap** [comment]
I was able to reproduce this using a Windows 10 client - 

- OS: Windows 10 1809
- Moonlight version: 0.10.0.0

[Moonlight-1555889418.log](https://github.com/moonlight-stream/moonlight-qt/files/3101718/Moonlight-1555889418.log)

**Comment by cgutman** [comment]
What is the impact of this bug? Does the nvstreamer.exe process cause problems?

In any case, it's a bug in GeForce Experience. Moonlight has no control over what GFE decides to do here.

**Comment by PKCheap** [comment]
> What is the impact of this bug? Does the nvstreamer.exe process cause problems?
> 
> In any case, it's a bug in GeForce Experience. Moonlight has no control over what GFE decides to do here.

I suspected as much, but I just wanted to be sure. 
The impact of this for myself, is that I have tasks scheduled to fire when the gamestream connection is made / terminated. I use nvstreamer.exe as an indicator for when those two events happen.

**Comment by thamerx** [comment]
Yeah, this bug usually prevents audio coming out of the host after stopping the stream. I usually have to manually terminate it just fine.
