### ISSUE TITLE
How to connect Moonlight via usb tethering

### ISSUE THREAD

**Issue by dedsec995** [moonlight-stream/moonlight-qt#223]
My android mobile(192.168.0.101) is connected to a WiFi router (192.168.0.1). I have enabled USB tethering on the mobile for internet access on my desktop (192.168.42.32). Also from my connection, the gateway is 192.168.42.129. So now we can infer the following from all these data:

Router IP: 192.168.0.1
Mobile's IP (for WiFi interface): 192.168.0.101
Mobile's IP (for USB interface): 192.168.42.32
Desktop's IP: 192.186.42.32

I am able to connect to raspberry pi via putty from pc and can ping rpi from pc but cannot connect or ping from rpi to pc
(P.S: I did thought search on internet and didn't find anything)

**Comment by cgutman** [comment]
If you're still looking for help, our [Discord server](https://discord.gg/MySTSdq) is the preferred way.
