### ISSUE TITLE
key rctrl and rshift not recognized in game

### ISSUE THREAD

**Issue by alex333666333** [moonlight-stream/moonlight-qt#224]
Hello

In game (Cs:go, Day of Infamy), the keys Rctrl and Rshift don't work for me.
The layout keybord is FR (AZERTY)
In local game work fine, in streaming this keys don't work.

Rctrl and Rshift work with GTA4

I have try mstsc.exe, Big picture and direct launch.

Client PC and Server PC have the laster Geforce experience, laster drivers and Windows 1809/1803 and work Gigabit ethernet.
Client and server are AZERTY.

I have already posted issue : https://github.com/moonlight-stream/moonlight-qt/issues/186
Now I have news PC Server and news installation of Windows and the problem is the same.

Thank

**Comment by cgutman** [comment]
Please test your keys by streaming https://www.keyboardtester.com/ through Moonlight. See if left-shift and right-shift work through there.
