### ISSUE TITLE
Custom WoL Port Number

### ISSUE THREAD

**Issue by deep8787** [moonlight-stream/moonlight-qt#225]
So im loving Moonlight, I got it working pretty much A-OK, Streaming is immense over the internet (even on 3G/4G on my mediocre China android phone :D
I can use WoL over my local LAN no problem, but getting it to work over the internet seems problematic...Ive opened ports before to allow me to remote access some stuff like my RPi etc etc all good.
After some testing I finally double checked with an online port scanner and I came to the realisation that my Port # 7 and 9 seem to be blocked from my ISP. Like I Said, I opened all the appropriate ports to allow the streaming to work over external internet etc which is fine. This is my only conclusion so far, I will ring them up in the morning to verify. 
IF for whatever reason my ISP wants to be lame and this stays as it is...I will need to allow for custom port for the WoL to work outside of my Lan....pretty please :)

**Comment by deep8787** [comment]
I just got off the phone from my ISP, they confirmed that the port is blocked for private users and only people with a business internet connection are allowed to use them ports. I have tried using a different external port which then is meant to go to port 7 on my internal network but that didnt work either unfortunately.
Currently I am SSH'ing into my RPi from outside  and then sending a WoL to my pc from my RPi, it works but it would be nice to streamline this into Moonlight for myself and potentially others users with lame ISPs :D

Regards,
Nav

**Comment by cgutman** [comment]
I think exposing a fully configurable WoL port isn't worth the UI complexity. I added UDP ports 48002 and 48010 to the list of ports that Moonlight will send the WoL request to. They are currently unused by GameStream, so you can forward them to your Pi as necessary for WoL functionality.

https://github.com/moonlight-stream/moonlight-qt/commit/2c0e8a0ddfe5ba859c3d957f938911d315a6f3b7
