### ISSUE TITLE
Cant set a resolution greater than monitor has

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#226]
You cant set a resolution greater than the monitor connected to the streaming server has. For example, monitor at the server has 1080p, but you want to stream in 1440p or even 4k.

**Comment by cgutman** [comment]
4K is fully supported on a 1080p monitor. See https://support-shield.nvidia.com/gamestream-user-guide/index.htm#t=HDR_Requirements.htm

1440p is not, and that's a GFE limitation, so Moonlight is working as intended here. You can use an HDMI "fake display" dongle if you don't have a 1440p display (that's how I have mind set up).
