### ISSUE TITLE
Moonlight Portable creating Folders for qmlc files even though no files being written

### ISSUE THREAD

**Issue by somerandomperson123** [moonlight-stream/moonlight-qt#227]
This is the related to the previous issue here - https://github.com/moonlight-stream/moonlight-qt/issues/217

The portable version is no longer writing any actual qlmc files but still creating the folders where they would go whenever Moonlight is run. 

In AppDate\Local\ the following folders are being created -

Moonlight Game Streaming Project\Moonlight\cache\qmlcache 

Nothing is being written into those folders however.

**Comment by cgutman** [comment]
I can't reproduce this issue.

I tried the v0.10.1 x64 portable build on a Windows 8.1 machine and a Windows 10 test machine after deleting the `%LOCALAPPDATA\Moonlight Game Streaming Project` folder and neither machine created `%LOCALAPPDATA\Moonlight Game Streaming Project\Moonlight\cache\qmlcache`. Even running the non-portable install didn't create the `qmlcache` directory.

Can you specify the exact steps and the Moonlight version you ran to see the issue?

**Comment by somerandomperson123** [comment]
After additional testing it seems like the issues goes away if the latest version is extracted to a new folder (fresh install basically). 

Previously I was running the latest version updated via extracting on top of the old folder.  

Comparing the two folders I see that they are not actually identical with the updated folder having more folders with files in them. Perhaps one of them was causing the issue?

For future reference I'm curious where configuration is saved in the portable install? Is Moonlight Game Stream Project/Moonlight.ini the folder/file that would need to be transferred?

**Comment by cgutman** [comment]
Interesting, I wouldn't have expected that the extra qml files would cause the qmlcache directory to be created (even though qmlc files were already there).

Yep, `Moonlight Game Stream Project/Moonlight.ini` is all you need to transfer to the new install to keep your settings and paired computers.

So it sounds like it's working as intended with the caveat that upgrading from v0.10 or earlier requires a folder wipe to avoid this issue.
