### ISSUE TITLE
No window is created after connecting

### ISSUE THREAD

**Issue by OneAndOnlyWisp** [moonlight-stream/moonlight-qt#229]
**Describe the bug**
No window is created after connecting. Connection seems fine, even moving the mouse works. My window manager permanently dies. Atleast the visually. In the background window manager works, but no screen updates coming after this bug happens.

**Steps to reproduce**
Cannot really specify this. The problem occured after installed VAAPI driver for video acceleration.

**Screenshots**
Cannot take screenshot.

**Affected games**
All

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
No
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Client PC details (please complete the following information)**
 - OS: 
Arch Linux with LTS kernel, fully updated
 - Moonlight Version:
0.10.1-1

**Server PC details (please complete the following information)**
 - OS:
Windows 10 Pro 1809
version 17763.379
 - GeForce Experience version:
3.18.0.102
 - Nvidia GPU driver: 
430.39

**Moonlight Logs (please attach)**
[log](https://textuploader.com/1drnl)

**Additional context**
[vainfo log](https://textuploader.com/1drnq)

**Comment by cgutman** [comment]
What window manager are you using? Does it happen if you set the decoder option to "force software decoding"?

**Comment by OneAndOnlyWisp** [comment]
**Window Manager**
i3wm

**VAAPI**
libva-intel-driver 2.3.0-2

**Decode setting**
Didnt really tested, because the main reason was to replace sw with hw decoding.
Will give it a shot when I get home, but it should be working that way.
