### ISSUE TITLE
Moonlight-qt looses gamepad imput if not focused

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#23]
If I alt+tab moonlight it's loosing the gamepad control untill I reselect the moonlight window, something that didn't happen with the chrome version.
Is this a something that can be fixed?

**Comment by Jorys-Paulin** [comment]
@apoklyps3 To better help you, could you give us your os and logs? Thanks!

**Comment by cgutman** [comment]
Should be fixed in the next release
