### ISSUE TITLE
[RPi] Qt Fatal: EGL Error : Could not create the egl surface: error = 0x3001

### ISSUE THREAD

**Issue by 5schatten** [moonlight-stream/moonlight-qt#232]
**Describe the bug**
Moonlight-Qt fails to start on a RPi3B device. The log file itself states that according to https://www.khronos.org/files/egl-1-4-quick-reference-card.pdf that `EGL is not or could not be initialized, for the specified display` so is there any special Qt environment flag necessary or doesn't it run because your mmal implementation is still somewhat tied to X11?

**Steps to reproduce**
Well I use a LibreELEC fork which includes some retro gaming stuff & until today moonlight-embedded which works fine but is rather complicated to setup.

I use this package to build moonlight-qt https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.x-rr-working-tree/packages/5schatten/emulation-standalone/moonlight-qt/package.mk

I use [these Qt5 environment variables](https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.x-rr-working-tree/packages/oem/files/RPi/etc/profile.d/921-video-settings-rpi.conf#L92) to run Qt applications in my build which are fine for Pegasus-Frontend for example.

Moonlight v1.0.0 is compiled against Qt 5.12.0 and all other dependencies are recent versions too.

**Moonlight Logs (please attach)**
http://ix.io/1JJw
```
00:00:02 - SDL Info (0): Loaded 31 new gamepad mappings
00:00:02 - Qt Warning: Cannot find EGLConfig, returning null config
00:00:02 - Qt Fatal: EGL Error : Could not create the egl surface: error = 0x3001
```

If you need any specific information like a build log or else just let me know and I gather them for you :+1:

**Comment by cgutman** [comment]
FYI, Moonlight Qt doesn't support embedded platforms yet, even though the code exists for rendering. Just setting expectations, though you're free to try to get it working.

I don't think it's related to MMAL, since this error is happening well before we get to that point. Do you have other Qt applications that work using the EGLFS backend on this device? Are they using a static Qt build or the Qt 5.12.0 package that you built?

Did you build Qt yourself with the Raspberry Pi steps? https://wiki.qt.io/RaspberryPi2EGLFS

**Comment by 5schatten** [comment]
Well I'm not a programmer so I can only help out with testing :see_no_evil: My Qt package compiles shared libs because other programs like [Pegasus Frontend](https://github.com/mmatyas/pegasus-frontend) also rely on them & work fine with EGLFS. If you want to have a look at my Qt package:

https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.x-rr/packages/5schatten/depends/qt-everywhere/package.mk

Even though it's not supported it basically works on my RockPro64 for example beside the mouse support quirk I reported too. So I guess it's not completely broken and might just need some tweaking ;-)
