### ISSUE TITLE
Full-screen crash when running on discrete GPU using Optimus

### ISSUE THREAD

**Issue by OsaPL** [moonlight-stream/moonlight-qt#235]
Describe the bug
Everything works great, pairing detecting connection etc. but 

Steps to reproduce
Connect to a host, select any game while having fullscren selected.
Everything should go without a problem, but on stream start screen just blinks black and client closes, no error message.

Affected games
All

Moonlight settings (please complete the following information)

Have any settings been adjusted from defaults?
No, and yes. Both act the same, as long as Fullscreen is on.
Client PC details (please complete the following information)

OS:
Windows 10 1809
Moonlight Version: 1.0.0
Server PC details (please complete the following information)

Host:
OS:
Windows 10 1809
GeForce Experience version/Nvidia GPU driver:
Cant check will update when I get back home, moonlight client on other platform works (ps-vita)

.dmp
[Moonlight-1558693893.zip](https://github.com/moonlight-stream/moonlight-qt/files/3216530/Moonlight-1558693893.zip)
.log
[Moonlight-1558693878.log](https://github.com/moonlight-stream/moonlight-qt/files/3216521/Moonlight-1558693878.log)

**Comment by cgutman** [comment]
It looks like a crash in DirectX. I've seen a few instances in the crash analytics data from Microsoft too. I've never seen it in testing on any of my systems, so it's difficult to troubleshoot.

Is the client system running Optimus? Can you get the GPU driver versions on the client (both Intel and Nvidia)? Can you try using Optimus to force Moonlight on the integrated GPU or the Nvidia GPU to see if that makes a difference?

```
00 000000e4`2e0ff360 00007ffb`84ef66fe d3d9!CSwapChain::BltToHybridPrimary+0x200
01 000000e4`2e0ff700 00007ffb`84ea2413 d3d9!CSwapChain::FlipToSurface+0x11a
02 000000e4`2e0ff780 00007ffb`84f0a225 d3d9!CSwapChain::PresentMain+0x3c153
03 000000e4`2e0ff920 00007ffb`84f0a17d d3d9!CBaseDevice::PresentMain+0x9d
04 000000e4`2e0ff970 00007ff6`2fb3e5ef d3d9!CBaseDevice::PresentEx+0xbd
05 000000e4`2e0ff9c0 00007ff6`2fb3c53e Moonlight!DXVA2Renderer::renderFrame+0x5cf [c:\moonlight-qt\app\streaming\video\ffmpeg-renderers\dxva2.cpp @ 987] 
06 000000e4`2e0ffbc0 00007ff6`2fb3ca8a Moonlight!Pacer::renderFrame+0x3e [c:\moonlight-qt\app\streaming\video\ffmpeg-renderers\pacer\pacer.cpp @ 265] 
07 (Inline Function) --------`-------- Moonlight!Pacer::renderLastFrameAndUnlock+0x197 [c:\moonlight-qt\app\streaming\video\ffmpeg-renderers\pacer\pacer.cpp @ 156] 
08 000000e4`2e0ffc10 00007ffb`86441c85 Moonlight!Pacer::renderThread+0x1ca [c:\moonlight-qt\app\streaming\video\ffmpeg-renderers\pacer\pacer.cpp @ 88] 
09 000000e4`2e0ffc50 00007ffb`8644220e SDL2!SDL_RunThread+0x45 [c:\users\aicom\sdl\src\thread\sdl_thread.c @ 283] 
0a 000000e4`2e0ffc80 00007ffb`9e981ffa SDL2!RunThread+0x1e [c:\users\aicom\sdl\src\thread\windows\sdl_systhread.c @ 91] 
0b 000000e4`2e0ffcb0 00007ffb`9fc97974 ucrtbase!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x3a
0c 000000e4`2e0ffce0 00007ffb`a1e2a271 kernel32!BaseThreadInitThunk+0x14
0d 000000e4`2e0ffd10 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

**Comment by OsaPL** [comment]
Optimus is disabled, everything is run on dedicated nvidia gpu (gtx 660m).
Client nvidia drivers: 418.91
Vsync on/off behaves the same.
Intel gpu driver is on 10.18.10.4252 (its apparently a WDM driver)
DxDiag shows that everything looks ok.

**Comment by cgutman** [comment]
Please try the Portable build here and confirm the issue is resolved: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/25472617/job/kx83rngwaat0faxj/artifacts

Don't use the installer because it may conflict with the existing version of Moonlight you have installed.
