### ISSUE TITLE
Washed out colors with HDR host

### ISSUE THREAD

**Issue by kshots** [moonlight-stream/moonlight-qt#236]
As requested, opening a new issue for this...

Describe the bug
The video feed on the client is washed out.

Steps to reproduce
Enable HDR on the host machine, connect to host with a non-HDR client running moonlight, gag on the washed out colors...

Affected games
All software items

Moonlight settings (please complete the following information)
I've tried default settings as well as custom settings. No difference

Client PC details (please complete the following information)

OS: Linux 4.19.44
Moonlight Version: 1.0.0 from git (updated to head as of 2019-05-26 around 0100 EST)
Server PC details (please complete the following information)

OS: Windows 10
GeForce Experience version: 3.18.0.102
Nvidia GPU driver: 430.64
Moonlight Logs (please attach)

[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/3220042/moonlight.log)

Additional context
I am 99% sure this issue is caused by the rgb color range not matching. The client expects the video feed to have a quantization range from 16-235 (pretty much all videos have this) but is not mapping it correctly into the 0-255 range commonly used on PC, causing the image to look washed out. If this is indeed the issue, a toggle in settings to choose the color range would be great.

Also,

screenshot using [moonlight](https://pasteboard.co/IdmoDcc.png) vs [xfreerdp](https://pasteboard.co/Idmp7V4.png)

**Comment by kshots** [comment]
Also note I was able to work around this problem by disabling HDR on Windows on the host machine. Obviously an undesirable workaround, though...

**Comment by dringger** [comment]
I am currently having this issue now with the most recent MacOS client when running from an HDR windows host. Any update?

**Comment by cgutman** [comment]
I think you just have to use the workaround (disable HDR on the host). There doesn't seem to be any client-side solution since we're just displaying what the server send us.
