### ISSUE TITLE
GFE 3.19.0.94 (new) - Black screen with audio

### ISSUE THREAD

**Issue by rampage47** [moonlight-stream/moonlight-qt#237]
gfe 3.19.0.94
can use moonlight client (black screen with audio)
mb nvidia change some ports
windows 10 (server and client)
try to use v.0.10.1 and v 1.0.0 - dont working

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-qt/commit/0a705d67521a875f7480fc9c4c92c154a1ffbe3e

Fix released as v1.0.1
