### ISSUE TITLE
connect error 521

### ISSUE THREAD

**Issue by yolo3a525** [moonlight-stream/moonlight-qt#239]
Streamer could not be initialized.(error 521).
![QQ截图20190531165359](https://user-images.githubusercontent.com/10290796/58694036-b1b88780-83c4-11e9-8d2d-6014b341aaae.png)

**Comment by cgutman** [comment]
That looks like a very out of date version of Moonlight. Newer ones don't have dialogs like that.

In addition, you should use our Discord server for troubleshooting, not GitHub issues. We will direct you to GitHub if it looks like a Moonlight bug.
