### ISSUE TITLE
Video freezes immediately after streaming begins on laptop with discrete graphics

### ISSUE THREAD

**Issue by agent86ix** [moonlight-stream/moonlight-qt#240]
**Describe the bug**
When streaming from my desktop to my laptop (running Windows 10, with a discrete Nvidia GPU) using Moonlight, the first frame of the stream appears, but then Moonlight seems to freeze.  It no longer accepts input, and although I can Alt-Tab or Ctrl-Alt-Del, Moonlight remains on top of all the other windows.  I can temporarily bring up the laptop's start menu and taskbar with the Windows key.

The only way to get out of this situation is to log out or reboot the laptop. 

**Steps to reproduce**
(See above)

**Screenshots**
n/a

**Affected games**
All, including Steam and mstsc.exe

**Moonlight settings (please complete the following information)**
No settings were changed from the defaults. 

**Client PC details (please complete the following information)**
 - OS: Windows 10 1809
 - Moonlight Version: 1.0.1

**Server PC details (please complete the following information)**
 - OS: Windows 10 1809
 - GeForce Experience version: 3.19.0.94
 - Nvidia GPU driver: 430.64

**Moonlight Logs (please attach)**
[Moonlight-1560017983.log](https://github.com/moonlight-stream/moonlight-qt/files/3268848/Moonlight-1560017983.log)

The relevant portion appears to be:
```
00:00:54 - SDL Info (0): IDR frame request sent
00:00:54 - SDL Info (0): Video decode unit queue overflow
00:00:54 - SDL Info (0): IDR frame request sent
00:00:54 - SDL Info (0): Video decode unit queue overflow
00:00:54 - SDL Info (0): IDR frame request sent
00:00:54 - SDL Info (0): Video decode unit queue overflow
00:00:54 - SDL Info (0): IDR frame request sent
00:00:55 - SDL Info (0): Video decode unit queue overflow
```

**Additional context**
Workarounds discovered:

Workaround 1: In the Moonlight settings, change the "Video Decoder" to "Force software decoder"

Workaround 2: Open the Nvidia Control Panel, choose "Manage 3D Settings" On the "Program Settings" tab, Click "Add" and select "Moonlight Game Streaming" from the list.  Set the "preferred graphics processor" to "Integrated graphics" and then **click apply.**

Either of these two workarounds restored Moonlight to a working state.

**Comment by cgutman** [comment]
Please try the Portable build here and confirm the issue is resolved: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/25472617/job/kx83rngwaat0faxj/artifacts

Don't use the installer because it may conflict with the existing version of Moonlight you have installed.

**Comment by agent86ix** [comment]
Verified working, thanks for the fix!
