### ISSUE TITLE
Starting control stream establishment failed: Error -1

### ISSUE THREAD

**Issue by Teutonic84** [moonlight-stream/moonlight-qt#241]
**Describe the bug**
I'm getting an error whenever i try to open a game in moonlight from my steam link. It gets to "Starting Control stream establishment", then throws this error: "Starting control stream establishment failed: Error -1". I can use moonlight on my laptop with my gaming PC just fine, it's only the steam link i'm having issues with. I'm running the latest version of moonlight on both server and client "v1.0.1".

**Steps to reproduce**
Server is on windows 10 LTSB desktop. Client is Steam Link running latest beta version firmware. Both desktop and steam link are set to 1600x900 resolution size. 

**Affected games**
Steam big picture mode, rocket league, assassin's creed odyssey (non-steam version). 

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? No tried using default settings.
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default? Yes.

**Client PC details (please complete the following information)**
 - OS: Steam Link
 - Moonlight Version: 1.0.1

**Server PC details (please complete the following information)**
 - OS: Windows 10 LTSB
 - GeForce Experience version: 3.19.0.94
 - Nvidia GPU driver: 430.86
**Moonlight Logs (please attach)**
(i apologize for not attaching the file but i am at work and can't access the log file directely, only a post i made on the steam discussion forums with the complete log file contents below)

> linux_version_check - failed to open /proc/mv88de3010 linux_version_check - app expects linux kernel revision 6154, please manually check current revision <<<<< CPU-1 OSAL Init memory map size for cache:0x0C000000, fd_cache:4, ret:0 memory map size for non-cache:0x02000000, fd_noncache:3 MV_SHM_Init OK: base_virtaddr_cache:0xA648C000, size:0x0C000000 base_virtaddr_noncache:0xA448C000, size:0x02000000 DBG HEALTH {line: 280 (MV_CC_RPCClnt_Call)} 0x7 DBG HEALTH {line: 280 (MV_CC_RPCClnt_Call)} 0x7 00:00:00 - Qt Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root' 00:00:00 - Qt Warning: Unable to query physical screen size, defaulting to 100 dpi. To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters). 00:00:00 - Qt Warning: SL HACK: No default font - using NotoSans 00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt" 00:00:00 - SDL Info (0): Loaded 31 new gamepad mappings 00:00:00 - SDL Info (0): V-sync enabled 00:00:00 - SDL Info (0): SLVideo video decoder chosen 00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt" 00:00:01 - SDL Info (0): Loaded 31 new gamepad mappings 00:00:02 - Qt Info: "GAMING-RIG" is now online at "192.168.1.61" 00:00:02 - Qt Debug: Current Moonlight version: "1.0.1" 00:00:02 - Qt Info: Discovered mDNS host: "Gaming-Rig.local." 00:00:02 - Qt Info: Resolved "Gaming-Rig.local." to "192.168.1.61" 00:00:02 - Qt Info: Processing new PC at "192.168.1.61" from mDNS 00:00:02 - Qt Info: Executing request: "http://192.168.1.61:47989/serverinfo?uniqueid=0123456789ABCDEF&uuid=ad6d1a05f4b44aa7a6878dedc4e6705b" 00:00:02 - Qt Info: Executing request: "https://192.168.1.61:47984/serverinfo?uniqueid=0123456789ABCDEF&uuid=09a79b3a00e240b2818b4061320c8e21"

**Comment by cgutman** [comment]
It looks like the log you collected was overwritten by another launch of Moonlight, so it doesn't have the error included. Can you attach another log after reproducing the issue?

Additionally, this is probably a host-side issue, so can you collect the logs from C:\ProgramData\NVIDIA Corporation\NvStream and attach them here?

In the past, the likely culprit is that you've renamed your NVIDIA Virtual Audio Device from "NVIDIA HDMI Out" to something else. Restoring it back to "NVIDIA HDMI Out" will resolve the issue.

**Comment by Teutonic84** [comment]
I've attached the moonlight.log file and the nvstream log file. I've also attached a screenshot of my audio drivers. The highlighted one in my screenshot is that what you want me to change to be named "NVIDIA HDMI Out"?
[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/3293792/moonlight.log)
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/3293793/NvStreamerCurrent.log)
![Audio Devices](https://user-images.githubusercontent.com/10197878/59558571-db73d000-8fba-11e9-81d8-945ef10d30c0.jpg)

**Comment by cgutman** [comment]
It looks like a firewall or something is blocking the connection. None of the packets are getting through.

I've also seen this happen if your PC has multiple connections to the same network (like Ethernet and WiFi). If you disconnect one, it should work.

```
#0(I)[2019-06-16 02:49:01,116]=21:49:01={00001FD0}<EnetProtocol>     Enet made total 491 packet transmission attempts in the last 10 sec of which 490 were retransmissions (49000.00%)
#3(W)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetProtocol>     ENet timed out on packet number 1 on channel 255 transmitted 588 times, last packet ack was received 4053609778 ms ago
#4(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Last receive: 4053609778 ms ago; Last sent: 21 ms ago; RTT: 500 ms; Avg Ack Time: 500 ms; Total Reliable Tx :: Attempts: 588; Time-Outs: 587; Re-Tx : 99.83%
#5(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Total incoming data : 0 bytes
#6(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Total outgoing data : 44 bytes
#7(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Next Packet timeout is in 1 ms
#8(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Earliest sent packet timeout is 12014 ms old
#9(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Last RTT : 500 ms
#0(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Lowest RTT : 500 ms
#1(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Last RTT Variance : 0 ms
#2(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Highest RTT variance : 0 ms
#3(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         RTT Variance : +-0 ms
#4(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Total number of bytes unacked : 0
#5(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Total waiting data undispatched : 0 bytes
#6(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetProtocol>     Notifying disconnect to peer.
#7(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Sending reset to remote peer
#8(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Number of reliable packets sent but unacked: 1
#9(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Number of reliable packets queued to be sent: 0
#0(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Number of unreliable packets sent: 0
#1(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Number of unreliable packets queued to be sent: 0
#2(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Number of partially reliable packets sent: 0
#3(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Number of partially reliable packets queued to be sent: 0
#4(I)[2019-06-16 02:49:03,119]=21:49:03={00001FD0}<EnetPeer>         Incoming commands queue size for channel 0 is 0
```

**Comment by Teutonic84** [comment]
Well that's strange considering I can connect from my laptop to my gaming PC through moonlight without issues. It's only the steam link that has issues connecting. I used to have two ethernet cables plugged in (i have 2 NIC cards in the gaming PC), but last week I went down to just one cable plugged in. Wifi is not connected either.

**Comment by Teutonic84** [comment]
I figured it out! Thank you for getting me to look in a general direction that led to the solution. I went into my network settings and noticed windows 10 had put my network connection into "Public". This blocks certain connections. i switched it to "private" and it started working!
