### ISSUE TITLE
Command signals on host os

### ISSUE THREAD

**Issue by johnfg10** [moonlight-stream/moonlight-qt#242]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use ctrl + alt + tab for example to change tabs

**Describe the solution you'd like**
When in full screen i would like all commands like ctrl + alt + tab and such to be passed through to the host OS,  a good example of this is Google Chrome Remote Desktop which is a perfect example that passes all key presses such as ctrl + alt + tab to the host OS

**Additional context**
I thought i would outline the sort of use case this would benefit such as use of graphics/software problems, and other such software which can be manually passed through to Geforce experience

**Comment by cgutman** [comment]
Unfortunately these key combinations are blocked by GameStream on the host side, so they wouldn't work even if we sent them. You can set up AutoHotkey to use other key combos to activate the functionality you want. You can find instructions on our Discord server for doing that.
