### ISSUE TITLE
[Linux] Disconnected USB gamepad requires application restart

### ISSUE THREAD

**Issue by webnard** [moonlight-stream/moonlight-qt#244]
**Describe the bug**
If a USB connection gets cut, I cannot reconnect it and have it work without restarting Moonlight.

**Steps to reproduce**
Start Moonlight with gamepad connected via USB. Unplug gamepad, then plug it back in again. Gamepad no longer works.

 - Moonlight Version: 1.0.1
 - Bus 002 Device 027: Microsoft Corp. Xbox One S Controller

This only happens when running through Flatpak. If I build from source it works as expected.

**Comment by cgutman** [comment]
It's because Flatpak lacks udev, which SDL uses for hotplugging support. I believe udev can't guarantee a stable ABI, so it can't be considered for inclusion in Flatpak runtimes.
