### ISSUE TITLE
Audio crackling (Ubuntu 16.04 64bit with moonlight-snap v1.0.1)

### ISSUE THREAD

**Issue by geekycow** [moonlight-stream/moonlight-qt#245]
**Describe the bug**
- _Mild_ audio crackling every few seconds when using HDMI Stereo out.
- _Unusable_ audio crackling when using SPDIF AC3 out (using the A52 AC3 encoder.)

Video and gaming are fluid at 1080p/60fps 30Mbps, with or without hardware video acceleration, the only issue is the sound.

**Steps to reproduce**
No special steps, seems to occur on all configurations between these machines..

**Screenshots**
Not applicable.

If required, I can include audio samples?

**Affected games**
Seems to affect everything, including the sound in Big Picture Mode, but most noticeable on Riptide GT2 with or without a52 AC3 encoding.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
Issue occurs with default settings.

- If so, which settings have been changed?
Ramping down to 720/30fps 5Mbps makes no difference, nor does changing between hardware and software decoding (software works much better than I'd assumed), nor does forcing x.264, changing v-sync, or frame pacing.

- Does the problem still occur after reverting settings back to default?
Yes.

**Client PC details (please complete the following information)**
- OS: Ubuntu 16.04 64bit
- CPU: Intel Celeron 1007U / NM70 Chipset
- GPU: Integreted into CPU
- RAM: 4Gb
- Network: 1Gbps
- Moonlight Version: moonlight-snap v1.0.1

**Server PC details (please complete the following information)**
- OS: Windows 10 Pro 17134 64bit
- CPU: Intel i5-4460
- GPU: GTX 960 2Gb
- RAM: 32Gb
- Network: 1Gbps
- GeForce Experience version: 3.19.0.94
- Nvidia GPU driver: 417.01

**Moonlight Logs (please attach)**
Attached (plus output of /proc/cpuinfo on the client)

**Additional context**
Other than following [these instructions](https://help.ubuntu.com/community/DigitalAC-3Pulseaudio) for configuring AC3/SPDIF for the a52 AC3 encoder and enabling Intel VAAPI acceleration and "TearFree" vsync the client system is mostly a fairly bog standard Ubuntu 16.04 64bit install with latest updates, but the issue still happens when using stereo over HDMI without invoking the a52 encoder (it's just unuseably worse with the later.)

Although the client CPU is not particularly powerful, the Intel integrated graphics within it is oddly strong for a Celeron, and _this setup works absolutely fluidly with steam in-home streaming with Intel hardware acceleration at 1080p 60fps / 30Mbps+ / 5.1audio (via the A52 encoder.)_

Additionally, the Windows system acting as server is only used for games so is also a fairly standard install (except for whatever horrific things the games do to it of course!)  I don't think it's likely to be the Windows system though as I've been streaming to both a Steam Link (both moonlight and Steam Streaming) and Android devices (again, both Steam Link app and Moonlight) without issues for a few years.

I've also temporarily tried with SUID bit set in order to allow moonlight to set audio at a higher priority (otherwise an audio priority setting complaint is logged) but that made no difference.

[moonlight-hdmistereo-debug.log](https://github.com/moonlight-stream/moonlight-qt/files/3291459/moonlight-hdmistereo-debug.log)
[moonlight-ac3a52spdif-debug.log](https://github.com/moonlight-stream/moonlight-qt/files/3291460/moonlight-ac3a52spdif-debug.log)

**Comment by geekycow** [comment]
[cpuinfo.txt](https://github.com/moonlight-stream/moonlight-qt/files/3291463/cpuinfo.txt)

**Comment by cgutman** [comment]
can you try running with `ML_AUDIO=SDL` set?

```
export ML_AUDIO=SDL
snap run moonlight
```

**Comment by geekycow** [comment]
Yes, with ML_AUDIO=SDL it works perfectly!

(1080p 60fps 30Mbps with vsync on and hardware x.264 decoding with 5.1
audio over SPDIF as AC3 using a52 encoder.)
