### ISSUE TITLE
"Borderless Windowed" should the default/recommended on MacOS

### ISSUE THREAD

**Issue by DoctorWhoof** [moonlight-stream/moonlight-qt#246]
Hi,

While using Moonlight on MacOS I noticed that the default display mode "Full Screen", which is also the "recommended" mode.

It turns out that Full Screen is really not ideal on MacOS, since it prevents all familiar shortcuts - like "Cmd+Q" to quit and "Cmd+Tab" to switch apps - and also does not allow OS gestures of any kind. It was really frustrating the first time I ran it and couldn't alt+tab or even quit the app via familiar methods.

I can see other people having the same issue:https://github.com/moonlight-stream/moonlight-qt/issues/77

Borderless windowed in MacOS is, effectively, full screen, but with all familiar shortcuts and gestures. You lose nothing compared to pure full screen, and gain a lot of OS features.

Cheers!

**Comment by MrBuddyCasino** [comment]
That would be great to have, just experienced this issue. I would implement it myself, if anyone can point me to the right location?
