### ISSUE TITLE
big thanks

### ISSUE THREAD

**Issue by subjectdenied** [moonlight-stream/moonlight-qt#25]
no issue here, but i'd like to mention that this new client is in fact the first and only game-streaming client solution that works blazingly fast, reliable and hw-accelerated on my linux intel-hd ultrabook (the chrome version never worked for me with hw-acceleration) - way better than vpn-only steam-inhome-streaming, parsec, rainway, you name it, and last but not least it is opensource too. and kudos for using flatpak for linux distribution

thanks for your great work!

**Comment by boozecow** [comment]
What a surprise by myself to see this today. By by, unable to create OpenGL context in Chrome. I agree, much better than parsec and allow me to vpn home and run it throw the vpn tunnel !

**Comment by nicholson101** [comment]
I want to echo the above sentiment too. Just stumbled upon this having used the chrome extension for ages and the difference is quite remarkable! Much smoother experience and just works every time! keep up the good work!

**Comment by AgentCrowe** [comment]
Wanted to just say the BETA 1 that dropped a couple days ago is the Bee's Knee! It runs so good! Very impressed with the difference, no more excessive mouse lag and no more weird shutters that I was starting to think was my internet connection. I have been using moonlight for a couple years now and I gotta say I am very excited to see what changes will be made in the near future!

**Comment by Sloanstar** [comment]
Agreed. Whoever is still in the greater Cleveland area working on this, I
need to buy you guys some drinks.

**Comment by Scan4u** [comment]
Good job, folks! Thanks a lot for your perfect soft!

**Comment by Byron1c** [comment]
Fantastic software, works better than Steam Link! Thanks for all the hard work
