### ISSUE TITLE
Connecting over LAN crash with control stream establishment failed (error 11)

### ISSUE THREAD

**Issue by TotomInc** [moonlight-stream/moonlight-qt#250]
**Describe the bug**
I am trying to connect on my W10 computer from a Macbook Pro with Moonlight software (1.0.1), it can't get over the *Starting control stream establishment* step (until it close the game and go back to normal).

**Steps to reproduce**
- Setup GeForce experience + enable it in settings
- Install Moonlight 1.0.1 on both host and guest machines
- Start a game (in my case Path of Exile, Steam, ...)

**Affected games**
CS:GO, Path of Exile, Steam, Skyrim, The Witcher 3, Dark Souls (Remastered, III) (I haven't tried with other games).

**Moonlight settings (please complete the following information)**
- 720P, 60FPS, 5Mbps
- Keeping everything at the defaults still crashses

**Client PC details (please complete the following information)**
 - OS: Mac OS Mojave 10.14.5
 - Moonlight Version: 1.0.1

**Server PC details (please complete the following information)**
 - OS: Windows 10 Enterprise **LTSC** 1809 (17763.557)
 - GeForce Experience version: 3.19.0.107
 - Nvidia GPU driver: 430.86

**Moonlight Logs (please attach)**
[Moonlight-1561400859.log](https://github.com/moonlight-stream/moonlight-qt/files/3322127/Moonlight-1561400859.log)

**Additional context**
It may be important that the host is running an LTSC version of Windows 10, if this can impact the stream.

**Comment by cgutman** [comment]
This is almost always a configuration issue, not a bug in Moonlight. See https://github.com/moonlight-stream/moonlight-qt/issues/241 for some potential resolutions or join our Discord to get help if those don't work https://discord.gg/MySTSdq

**Comment by TotomInc** [comment]
I recently tried again and asked for help on the discord server, someone tried to help me but we are still unable to make it work.

@cgutman, please consider reopening this issue as it doesn’t seems to be related to configuration.

Here’s what I tried:

- disable Windows firewall (not a firewall issue, since I can ping both computers)
- switch host PC (in ethernet) from a public to a private network
- uninstall/reinstall GeForce Experience
- disable GeForce Experience firewall rules
- updated everything (Windows, Moonlight QT, GeForce Experience drivers)

I am still trying to connect my MacBook Pro 2017 (Mac OS Catalina) to my Windows 10 (not an LTSB edition anymore).

I also can’t find any log file of Moonlight QT on my MacBook (tried to look at /tmp but there are not Moonlight log).
