### ISSUE TITLE
Observer Mode - Add ability to disable input capture

### ISSUE THREAD

**Issue by BynariStar** [moonlight-stream/moonlight-qt#252]
Moonlight is a great tool for streaming a game to a friend, however, sometimes you don't need the ability for them to control input of a game and it instead becomes a hindrance.

It would be great if there was a toggle in Moonlight to disable input capture, making Moonlight a seamless game watching client.

**Comment by u3119345** [comment]
I second this. Currently using a 4K iMac as a monitor for a Windows PC and there's a second monitor also connected to the PC. When I launch Moonlight, only the primary monitor can be interacted with because Moonlight captures the input, "trapping" the cursor and preventing it from going to the secondary monitor.

**Comment by Jorys-Paulin** [comment]
Moonlight PC actually has a keyboard shortcut for that. It toggle mouse capture and can be accessed by using `Ctrl+Alt+Shift+Z - Toggle mouse capture`. You can find the keyboard shortcuts on the release notes of each release

**Comment by u3119345** [comment]
That only releases the cursor on the client side. The server/host side cursor is still confined to the primary monitor.

**Comment by Jorys-Paulin** [comment]
@u3119345 That's a limitation of GeForce Experience. As am aware, there's no way to change that, unlike Steam does.

**Comment by u3119345** [comment]
Ah ok that solves that problem. Thanks!

**Comment by fragtion** [comment]
Ctrl+Alt+Shift+Z works well to release the client cursor. However, if you simply click the video window again, cursor control is restored, which I suppose makes sense, but can also be undesirable if you are purely intending to use a session for viewing. It would be ideal if the toggling on/off was strictly by hotkey, or if we could have a settings checkbox to control this behavior

**Comment by shodanx2** [comment]
Hello

CTRL+ALT+SHIFT+M 
Will toggle input capture from, I think, mouse relative captured, to touchscreen like

Now I have two request

A way to make touchscreen-like the default mode


And a way to specify input capture mode on the command line 

Here is my connection command line

"C:\Program Files\Moonlight Game Streaming\Moonlight.exe" --display-mode windowed   --resolution 1280x720 stream 192.168.1.12 desktop


I would like --input-mode capture  or --input-mode nocapture

**Comment by shodanx2** [comment]
Hi,

Here is a potential solution 

Using powershell to call the win32 API, EnableWindow to disable the window

`powershell -Command "[void][Reflection.Assembly]::LoadWithPartialName('System.Runtime.InteropServices');$sig='[DllImport(\"user32.dll\")]public static extern IntPtr FindWindow(string lpClassName,string lpWindowName);[DllImport(\"user32.dll\")]public static extern bool EnableWindow(IntPtr hWnd,bool bEnable);';Add-Type -MemberDefinition $sig -Name Win32 -Namespace Native; $hwnd=[Native.Win32]::FindWindow($null,'Moonlight'); if ($hwnd -ne [IntPtr]::Zero) {[Native.Win32]::EnableWindow($hwnd,$false)} else {Write-Host 'Moonlight window not found.'}"`


I'm not sure if the window title is "Moonlight", this is untested, let me know if it works

and here is the same but to re-enable it

`powershell -Command "[void][Reflection.Assembly]::LoadWithPartialName('System.Runtime.InteropServices');$sig='[DllImport(\"user32.dll\")]public static extern IntPtr FindWindow(string lpClassName,string lpWindowName);[DllImport(\"user32.dll\")]public static extern bool EnableWindow(IntPtr hWnd,bool bEnable);';Add-Type -MemberDefinition $sig -Name Win32 -Namespace Native; $hwnd=[Native.Win32]::FindWindow($null,'Moonlight'); if ($hwnd -ne [IntPtr]::Zero) {[Native.Win32]::EnableWindow($hwnd,$true)} else {Write-Host 'Moonlight window not found.'}"`
