### ISSUE TITLE
More FPS options

### ISSUE THREAD

**Issue by St5sz2Jk** [moonlight-stream/moonlight-qt#253]
If possible it would be cool if there were more options for refresh rates. It is becoming more commonplace to see monitors that support refresh rates such as 144 or 240 hz that is not currently an option for moonlight. Some people even overclock their displays to get a few more frames per second. It would be useful to have a custom option for frame-rate as well.

**Comment by cgutman** [comment]
This is already supported using the "Unlock unsupported FPS options" checkbox. It will let you use the current refresh rate of the monitor (though the host's encoder may not be able to keep up, so YMMV).
