### ISSUE TITLE
Allow games to be hidden in Moonlight

### ISSUE THREAD

**Issue by michellabbe** [moonlight-stream/moonlight-qt#255]
**Describe the bug**
Games flagged as hidden in Geforce Experience still show up in Moonlight.  This gets especially confusing when a game is detected multiple times (see additional context below)

**Steps to reproduce**
Flag a game as hidden in GFE.  It disappear from Home screen in GFE, shows as "hidden" in filters, but Moonlight ignores the hidden flag and still show the game.

**Screenshots**
![2019-07-05_23h55_37](https://user-images.githubusercontent.com/16291382/60751268-c1f1f280-9f80-11e9-9e4b-60596e10e62b.png)

![2019-07-05_23h41_17](https://user-images.githubusercontent.com/16291382/60751133-c3bab680-9f7e-11e9-8e10-773a93a0ecbf.png)

![2019-07-05_23h38_58](https://user-images.githubusercontent.com/16291382/60751058-26f81900-9f7e-11e9-888b-3876cf38afd4.png)

**Affected games**
The Elder Scrolls Online (most likely any games)

**Other Moonlight clients**
Android (see issue [#351](https://github.com/moonlight-stream/moonlight-android/issues/351))

**Client PC details**
 - OS: Windows 10 1903
 - Moonlight Version: 1.0.1

**Server PC details**
 - OS: Windows 10 1903
 - GeForce Experience version: 3.9.0.107
 - Nvidia GPU driver: 430.86

**Moonlight Logs**
[Moonlight-1562381530.log](https://github.com/moonlight-stream/moonlight-qt/files/3364354/Moonlight-1562381530.log)

**Additional context**
I bought The Elder Scrolls Online via Steam, and since it's linked to my Steam account it's much less annoying to launch the game from Steam (auto-logon) than standalone with username and (complex) password that need to be typed manually on every launch.

GeForce Experience detects the game as standalone (and twice for some reason):
...\Steam\steamapps\common\Zenimax Online\
and
...\steam\steamapps\common\zenimax online\launcher\..\

Both copies of the same game show up with the same name and same icon in Moonlight so you don't know which is which (that's how they also show up in GFE so not being able to rename them or change icon is more a GFE annoyance than a Moonlight issue).  Flagging one copy as favorite in GFE doesn't help either to determine which copy is which in Moonlight.

To be able to start the game from Steam (with auto-logon working), I had to create a game shortcut from Steam (target = "steam://rungameid/306130" instead of path/launcher.exe) and add this shortcut to GeForce Experience, then edit it and set a custom icon.  This works great, but even though I hide the other copies of the same game in GFE, Moonlight ignores the hidden flag and show them anyway.

There are other reasons why you may want to hide games (e.g. hide games that won't work 100% with a gamepad).

**Comment by cgutman** [comment]
There is no "hidden" flag in the appdata XML, so we have no clue that the app should be hidden or not. This is a bug for Nvidia, not us.

**Comment by michellabbe** [comment]
Thanks for the (quick!) reply.

I guess NVIDIA only officially support their Shield device as a GameStream client so it's not quite worth filling a bug report over there unless some Shield owner complains about it on the Shield also.

Would it make sense as a feature request to hide games directly in Moonlight as a workaround then?

I'm asking before creating it because issue [#351](https://github.com/moonlight-stream/moonlight-android/issues/351) didn't seem to get any attention from the devs.

**Comment by krodelabestiole** [comment]
+1 that would be great, please don't close, stale bot !

**Comment by cybergrimes** [comment]
Absolutely would love to see a hide option. For some reason I currently have 3 listings in GFE for Path of Exile, I've hidden two on the PC end but obviously see 3 on my client end. It would be great if we could hide on the Moonlight client side.

**Comment by Goodix33** [comment]
+1 it will be nice to have such option in moonlight in order to hide the games we don't want to see

**Comment by Phiben** [comment]
Are there any updates on this issue? This is a serious UI design flaw.

**Comment by Chaoclypse** [comment]
I agree, this would be a much appreciated feature.

**Comment by lyndonguitar** [comment]
Would also like to have this fixed. mainly because I launch my game through the Big Picture app anyway, I have lots of games and it lags my Steam Link(hardware device) when all my scanned games from GFE show up

**Comment by cgutman** [comment]
It’s already implemented in v2.2.0. Right-click the game to hide it. It’s not accessible via game pad due to a bug that will be fixed in v2.3.0.

**Comment by lyndonguitar** [comment]
> It’s already implemented in v2.2.0. Right-click the game to hide it. It’s not accessible via game pad due to a bug that will be fixed in v2.3.0.

Thanks. I plugged in a mouse on my Steam Link and the option to hide it appeared. Big help!
