### ISSUE TITLE
Blank screen after connecting from MacOS, works from other clients

### ISSUE THREAD

**Issue by caparomula** [moonlight-stream/moonlight-qt#256]
When I connect to my Windows 10 PC from Mac OS I get just a black screen after a very brief flash of my PC desktop.  I've verified that I can connect fine from raspberry pi, debian linux machine, and from windows laptop, so it seems to be specific to the Mac OS client.  Also, if I toggle the status display overlay then I can see the desktop when connected from my mac.  Similarly, if I toggle windowed mode I can see it as well.  But when I toggle those off then the screen goes black again.  I'm using the most recent version of moonlight (1.0.1), and my mac is running Mojave 10.14.5.  My PC is running windows 10 Pro 1903 build 18362.207, geForce experience game ready driver 430.86.  Connection is via gigabit ethernet.

Any suggestions?

Thanks!

**Comment by cgutman** [comment]
A user reported the same issue on Discord, but that's an excellent find that the overlay fixes it.

What model of Mac is it? I have a 2016 MacBook on 10.14.5 and it's working for me here.

**Comment by caparomula** [comment]
@cgutman I'm using a Mac mini (2018) 3.6GHz Core i3.

**Comment by caparomula** [comment]
I should also mention that this had previously worked for me, several months ago, though I could not tell you which versions of moonlight, mac os, windows 10, and the geForce drivers I was using back then.
