### ISSUE TITLE
macOS Catalina h.264

### ISSUE THREAD

**Issue by gt2416** [moonlight-stream/moonlight-qt#257]
On MacOS catalina it says no proper h.264 encoder found which causes a huge performance decrease. 
I am running it on an unsupported Macbook 2011 with dosdude1 patch so maybe thats it, but I do have accelerated graphics on the desktop. 
Can someone running catalina on a supported Mac let us know if it works fine ? 
On Mojave, also not officially supported on my Mac it ran fine.

**Comment by cgutman** [comment]
It's working for me on my 2016 MacBook on Developer Beta 3, so it's probably something specific to your setup.

**Comment by gt2416** [comment]
ok thanks for confirming
