### ISSUE TITLE
Ability to wake-on-LAN from command line.

### ISSUE THREAD

**Issue by kwilliams1987** [moonlight-stream/moonlight-qt#260]
**Is your feature request related to a problem? Please describe.**
I've started using Moonlight in conjunction with Playnite to steam to my laptop, and I added a nice shortcut to auto stream Playnite, however if the PC isn't on the shortcut fails.

**Describe the solution you'd like**
I'd really like a command line parameter to automatically try to wake the PC if it doesn't respond, instead of just failing the connection.

**Describe alternatives you've considered**
I considered doing a command line/Powershell script to broadcast the WoL signal before opening Moonlight.

**Additional context**
N/A

**Comment by lukestu** [comment]
I do something like this with a bash script on linux...but a cli option to wake the host would be even better
