### ISSUE TITLE
Are the new Quadro RTX cards supported?

### ISSUE THREAD

**Issue by MrShoenel** [moonlight-stream/moonlight-qt#263]
Hey!
I am wondering if I can stream games from a Windows 10 machine that is using Quadro RTX 4000 card?
Would there be any downsides to that?

**Comment by cgutman** [comment]
Not officially that I'm aware of, though you may be able to patch nvstreamer.exe to allow the Quadro product ID like https://forum.xda-developers.com/showthread.php?t=2394478

**Comment by MrShoenel** [comment]
There is now also Nvidia QuadroExperience, it's still in development, but I have successfully tested it with a Quadro M2000, just letting you know!
