### ISSUE TITLE
iPad on iOS 13 beta no keyboard support

### ISSUE THREAD

**Issue by wajubalo** [moonlight-stream/moonlight-qt#265]
**Describe the bug**
Cannot bring up keyboard in moonlight in iPad OS13.

**Steps to reproduce**
Previously on iOS 12 iPad three finger tap slides up keyboard in moonlight. In iOS 13 beta three finger tap shortcut for keyboard has been overridden by apple to bring up a copy, paste, cut menu rendering moonlight unable to bring up ant keyboard on iPad, a necessary feature. 

Please change the shortcut for bringing up keyboard for iPad. Suggest: three finger  swipe up or four finger tap .uality, please include screenshots.

**Affected games**
All games requiring keyboard input (like inputting a password in dues ex mankind divided) or using windows OS.

**Other Moonlight clients**
- iPad OS 13

**Comment by cgutman** [comment]
This should be filed on the iOS project, not PC. https://github.com/moonlight-stream/moonlight-ios/issues
