### ISSUE TITLE
Wrong keys get sent to server

### ISSUE THREAD

**Issue by GreatTeacherOni** [moonlight-stream/moonlight-qt#268]
Hello , I've got a german (QERTZ) keyboard-layout (as seen here: https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg).
My NumPad-Keys including numbers work perfectly. 

Refering to https://github.com/moonlight-stream/moonlight-chrome/issues/204 which had similar issues. Although i am using the Windows PC Port. I wanted to report this issue since i still experience it.

Following keys don't work correctly:

- "**z**"-key wrongly prints "**y**" and vice versa

- "**ü**"-key wrongly prints "**ß**" and "shift+**ü**" prints "**?**"

- "**?**"-key wrongly prints "**-**" and "shift+**?**" prints "**_**"

- "**´**"-key (right to the "**?**"-key) wrongly prints "**+**"

- "**+**"-key (right to the "**ü**"-key) wrongly prints "**´**" 

- "**ö**"-key  (right to the "**L**"-key) wrongly prints "**ü**"

- "**#**"-key (right to the "**Ä**"-key) wrongly prints "**^**"

- "**^**"-key (accent character left to the "1"-key) wrongly prints "**ö**"

Is this due to GFE (is it different in a newer GFE version?) or can i change this somehow? if so, how?

Kind regards,
GTO

**Steps to reproduce**
Type mentioned letter and check the output. It's not the desired one.

**Affected games**
Affects all games. It's system-wide (Entire-Desktop-view).

**Client PC details (please complete the following information)**
 - OS: Windows 10 Pro x64 1903
 - Moonlight Version: v1.1.0 portable

**Server PC details (please complete the following information)**
 - OS: Windows 7 Pro x64
- GeForce GTX 960
 - GeForce Experience version: 2.11.4.1
 - Nvidia GPU driver: 381.65
(those old drivers still work the best even with most newer games)

**Moonlight Logs (please attach)**

**Additional context**
Tried it with an older portable Moonlight-client. Same outcome.

**Comment by GreatTeacherOni** [comment]
Has no one had the same issue ?

**Comment by cgutman** [comment]
What locale and keyboard layout are your client PC and server PC using?

**Comment by GreatTeacherOni** [comment]
Client PC (Windows 10 Pro):
- locale = german(Germany) 
- keyboard layout = german(Germany)

Server PC (Windows 7 Pro):
- locale = german(Germany) 
- keyboard layout = german(Germany)

**Comment by GreatTeacherOni** [comment]
Sadly i don't have newer hardware to test this with newer drivers or GFE. Could anyone try this and check if the result is the same as mine?

Kind regards,
GTO

**Comment by GreatTeacherOni** [comment]
I am still having this issue :(
