### ISSUE TITLE
Mouse position is incorrect, there is 50px offset when using windows and mac

### ISSUE THREAD

**Issue by Dalizzi** [moonlight-stream/moonlight-qt#269]
When streaming Warhammer Chaosbane from Windows(10 x64) to Macbook pro 13" retina using geforce experience 3.20 and Moonlight Qt 1.1, resolution 1080p on Windows PC, mouse position is incorrect in Macbook screen. Screen orientation is different in Mac ( 16:10 ), so I'm not sure does this cause the problem tough it doens't happen in other games. You cannot go to the bottom of the screen or rightmost part of the screen with mouse pointer, it seems like there is ~50px margin. Then you can go off the screen 50px on top and left. Also, when focusing e.g. menu button with mouse pointer, you have to set it off by ~50px.

**Comment by cgutman** [comment]
If it's a game-specific issue, it definitely seems like a bug on the PC side, either in the game or in Nvidia GameStream code. We don't deal with cursor positioning on the client side. We only send mouse position delta updates.

**Comment by Forceflow** [comment]
Have you tried switching the game between windowed / fullscreen / borderless mode? I doubt it, but it might work. Also check if the game has any setting called "use hardware cursor" and toggle that off/on.
