### ISSUE TITLE
Stretched fullscreen games

### ISSUE THREAD

**Issue by stezubseb** [moonlight-stream/moonlight-qt#271]
when starting a old game with macos client, the aspect ratio of 4:3 gets stretched to 16:9, even if on the moonlight server monitor the picture gets displayed correctly (with black bars)

**Steps to reproduce**
start a old 4:3 game with moonlight client for macos, in my case siege of avalon or technomage

**Other Moonlight clients**
on the ios client on my iphone se there is no stretching

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
bitrate set to higher value, 1080p 100mbps
not starting moonlight in fullscreen

- Does the problem still occur after reverting settings back to default?
yes

**Client PC details (please complete the following information)**
 - OS: macOS Mojave 10.4.6
 - Moonlight Version: 1.1.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 1903
 - GeForce Experience version: 3.20.0.118
 - Nvidia GPU driver: 436.30
i7 4771 CPU
12 GB RAM
GTX 1650 4GB

**Moonlight Logs (please attach)**
are attached
[Moonlight-1568811959.log](https://github.com/moonlight-stream/moonlight-qt/files/3628317/Moonlight-1568811959.log)
[Moonlight-1568812682.log](https://github.com/moonlight-stream/moonlight-qt/files/3628318/Moonlight-1568812682.log)
[Moonlight-1568813124.log](https://github.com/moonlight-stream/moonlight-qt/files/3628319/Moonlight-1568813124.log)
[Moonlight-1568818705.log](https://github.com/moonlight-stream/moonlight-qt/files/3628320/Moonlight-1568818705.log)
[Moonlight-1568835070.log](https://github.com/moonlight-stream/moonlight-qt/files/3628321/Moonlight-1568835070.log)
[Moonlight-1568836455.log](https://github.com/moonlight-stream/moonlight-qt/files/3628322/Moonlight-1568836455.log)
[Moonlight-1568836589.log](https://github.com/moonlight-stream/moonlight-qt/files/3628323/Moonlight-1568836589.log)
[Moonlight-1568836756.log](https://github.com/moonlight-stream/moonlight-qt/files/3628324/Moonlight-1568836756.log)
[Moonlight-1568836794.log](https://github.com/moonlight-stream/moonlight-qt/files/3628325/Moonlight-1568836794.log)
[Moonlight-1568836839.log](https://github.com/moonlight-stream/moonlight-qt/files/3628326/Moonlight-1568836839.log)
[Moonlight-1568838977.log](https://github.com/moonlight-stream/moonlight-qt/files/3628327/Moonlight-1568838977.log)

**Additional context**
in nvidia control panel changed desktop size and position
scale-mode: aspect ratio
scaling with GPU

override game and program settings
set resolution to native monitor resolution (1080p)

starting the game in steam big picture mode doesn't help

If i need to provide further information or testing, ask away

**Comment by stezubseb** [comment]
I just tested on Ubuntu 16.04 and moonlight client.
When i set Desktop resolution in Ubuntu settings to 1024x768 i can choose native resolution in moonlight and the games get streamed in correct 4:3 ratio.
the same method is not possible in macOS, setting custom macOS resolution does not affect moonlight resolution selection.

log from ubuntu machine
[log.txt](https://github.com/moonlight-stream/moonlight-qt/files/3636234/log.txt)


maybe this helps. 

thanks for having a look into this

**Comment by cgutman** [comment]
Try switching to full-screen mode instead of borderless windowed mode in the Moonlight settings. Moonlight defaults to borderless windowed mode on macOS to allow Spaces, Alt+Tab, etc. to work.

**Comment by stezubseb** [comment]
Thanks for your reply

This doesn't help in my case.

log from testing with fullscreen:
[Moonlight-1569047257.log](https://github.com/moonlight-stream/moonlight-qt/files/3638404/Moonlight-1569047257.log)

**Comment by cgutman** [comment]
What is your host PC resolution set to while attempting to stream the 4:3 game?

**Comment by stezubseb** [comment]
Host PC resolution is set to 1080p 60Hz. i tried with 1024x768 as well (changing while streaming Desktop via mstsc.exe)

**Comment by Clete2** [comment]
Same issue here. I can't get any resolutions to match up between Mac (client) and Windows (host).
