### ISSUE TITLE
RTSP connection failed from other devices

### ISSUE THREAD

**Issue by Darkmaniako** [moonlight-stream/moonlight-qt#272]
Hello
Since a couple of days i can't connect to my PC because of the error above.
My firewall is disabled, Moonlight Helper says my PC is ready to stream, but both my smartphone (wifi, same network) and office PC (different network) will give me the same error.
Nothing changed on my router, i have the same problem connecting to the public IP or the DynDNS name.
On the same network i can delete the host and it's found again during the scan (and ask for pairing code), so the service is up, and the PC resolution drops to 720p as i click on a game on the smartphone (it's set on 720p for smoothness) so the connections seems to work.
As soon as the device starts the RTSP handshake it fails.
Could it be a driver issue? I use official 436.30 (10 september)
Thanks

**Comment by jazha** [comment]
I have the same problem after 436.30, computer that connected before, does no longer connect. RTSP failed -1 error.

**Comment by cgutman** [comment]
A GeForce Experience or Nvidia Driver reinstall usually fixes these types of issues. If that doesn't help, I would suggest asking for advice on our [Discord server](https://discord.gg/MySTSdq) where there are many more people able to help than here on GitHub.
