### ISSUE TITLE
UI not updating in real time - Only updating when changing Window Size - MacOS Catalina

### ISSUE THREAD

**Issue by koltenfluckiger** [moonlight-stream/moonlight-qt#273]
**Describe the bug**
Moonlight UI only updates when maximizing and minimizing the window.

**Steps to reproduce**
Maximize and minimize the window of the App

**Screenshots**
https://imgur.com/a/HwRbn7Y

**Affected games**
N/A

**Other Moonlight clients**
No

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Yes,
- If so, which settings have been changed? Video bitrate and res
- Does the problem still occur after reverting settings back to default? Yes

**Client PC details (please complete the following information)**
 - OS: macOS Catalina 10.15 Beta (19A558d)
 - Moonlight Version: Moonlight PC v1.1

**Server PC details (please complete the following information)**
 - OS: Windows 10.0.18362 Build 18362
 - GeForce Experience version: 3.20.0.118
 - Nvidia GPU driver: 436.30

**Moonlight Logs (please attach)**
[Moonlight-1569077288.log](https://github.com/moonlight-stream/moonlight-qt/files/3638836/Moonlight-1569077288.log)
[Moonlight-1569080926.log](https://github.com/moonlight-stream/moonlight-qt/files/3638837/Moonlight-1569080926.log)
[Moonlight-1569081237.log](https://github.com/moonlight-stream/moonlight-qt/files/3638838/Moonlight-1569081237.log)

**Additional context**
This happens while connected to eGPU and dGPU on my Mac

**Comment by cgutman** [comment]
This appears to be a bug in Catalina. I would suggest using Mojave until Apple fixes it.

**Comment by cgutman** [comment]
This was reported upstream as https://bugreports.qt.io/browse/QTBUG-77958 and is fixed in Catalina Developer Beta 9 (19A573a).
