### ISSUE TITLE
Mouse clicks not working on Chromebook Version 77.0.3865.93 

### ISSUE THREAD

**Issue by COliver404** [moonlight-stream/moonlight-qt#274]
**Describe the bug**
Running a Chromebook Version 77.0.3865.93, Moonlight 8.3 app from app store. When I connect to the PC no mouse buttons work. The cursor works fine, but the left, right or wheel do not function at all.

**Steps to reproduce**
Do not think this is needed

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Affected games**
I have been launching warcraft in windows mode. It does not work in game or on the windows desktop. Mouse works fine.

**Moonlight settings (please complete the following information)**
- I have tried tweaking the control settings to with no progress.

**Client PC details (please complete the following information)**
 - OS: Chrome Version 77.0.3865.93 
 - Moonlight Version: 8.3

**Server PC details (please complete the following information)**
 - OS: Windows 10 (Latest Patch)
 - GeForce Experience version: 3.20.0.118
 - Nvidia GPU driver: 436.15

**Moonlight Logs (please attach)**
DId not see any windows logs

**Additional context**
I logged into discord to see if there was a fix but found other people with same issue, on the andriod support page, with no feedback provided.

**Comment by cgutman** [comment]
You should not use the Android version on ChromeOS. You should use the ChromeOS app instead - https://chrome.google.com/webstore/detail/moonlight-game-streaming/gemamigbbenahjlfnmlfdjhdnkpbkfjj
