### ISSUE TITLE
PC client sometimes can't connect when desktop is on lock screen

### ISSUE THREAD

**Issue by jamest212** [moonlight-stream/moonlight-qt#276]
I've observed that sometimes I can't connect from client PC (Qt) to my desktop when the desktop is locked. It goes through the handshake process and the screen starts to display for < 1 second then disconnects.

If I unlock the PC (such as via Chrome Remote Desktop), it seems to work fine after that. This has not always occurred, and I'm not sure what has changed.

Here's what I see in the log:

00:02:03 - SDL Info (0): ENet disconnect event pending
00:02:03 - SDL Info (0): Server notified termination reason: 0x8309
00:02:04 - SDL Info (0): Disconnect event timeout expired
00:02:04 - SDL Error (0): Connection terminated: 33545
00:02:04 - SDL Info (0): Quit event received
00:02:04 - SDL Info (0): Stopping input stream...
00:02:04 - SDL Info (0): done
00:02:04 - SDL Info (0): Stopping audio stream...
00:02:04 - SDL Info (0): Audio latency: 0.005000
00:02:04 - SDL Info (0): done
00:02:04 - SDL Info (0): Stopping video stream...
00:02:05 - SDL Info (0): done
00:02:05 - SDL Info (0): Stopping control stream...

**Comment by cgutman** [comment]
0x8309 is a different termination reason that normal. It probably indicates an error from NvStreamer.

Please upload logs from C:\ProgramData\NVIDIA Corporation\NvStream on your host after triggering the bug.

**Comment by jamest212** [comment]
Ok, thanks for the response - just to clarify, it doesn't happen every time the host is locked. Not sure yet exactly what triggers. Next time it happens, I will grab logs. It's been happening reasonably often so hopefully I will get some soon.

**Comment by jamest212** [comment]
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/3667393/NvStreamerCurrent.log)

Grabbed this shortly after the issue occurred just now

**Comment by cgutman** [comment]
Looks like the frame capture engine breaks on the host for some reason. Probably a driver issue.

```
#3(E)[2019-09-29 13:38:25,623]=08:38:25={000061E0}<Fbc7FrameProvide> Failed to create FBC instance: -5 (NVFBC_ERROR_DRIVER_FAILURE)
#4(E)[2019-09-29 13:38:25,623]=08:38:25={000061E0}<Fbc7FrameProvide> Failed to create FBC object
#5(I)[2019-09-29 13:38:25,623]=08:38:25={000061E0}<Fbc7FrameProvide> Unloading FBC library
#6(I)[2019-09-29 13:38:25,623]=08:38:25={000061E0}<VideoFrameProvid> Initialization error.
#7(E)[2019-09-29 13:38:25,623]=08:38:25={000061E0}<VideoPipeline>    Failed to start: Failed to initialize video frame provider: SERVER_TERMINATED_VFP_CREATE_FAILED
```
