### ISSUE TITLE
Starting RTSP handshake failed: Error -1

### ISSUE THREAD

**Issue by flow38** [moonlight-stream/moonlight-qt#277]
Hello,

Since approximately 2 weeks, the moonlight connection fail with the message :
Starting RTSP handshake failed: Error -1

There's been update on Windows 10 and GeForce driver (436.30) and Geforce Experience so it seems to be linked to the problem.//

Here's the Nvstream's log, if you need other infos let me known !
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/3665892/NvStreamerCurrent.log)

Thanks

**Comment by cgutman** [comment]
A GeForce Experience or Nvidia Driver reinstall usually fixes these types of issues. If that doesn't help, I would suggest asking for advice on our [Discord server](https://discord.gg/MySTSdq) where there are many more people able to help than here on GitHub.

**Comment by Stanislasss** [comment]
Ok, so classic issue, update in the blacklisting of Bitdefender.

**Comment by cgutman** [comment]
If you have Bitdefender installed, that's the likely cause. See the #bitdefender-situation channel on Discord.
