### ISSUE TITLE
audio re-enters if I use skype or discord to talk

### ISSUE THREAD

**Issue by HighPingTek** [moonlight-stream/moonlight-qt#278]
i want to play in local coop talking to skype or discord or anything else that lets you talk, but the client pc hears its voice, is there a way to fix it?

**Comment by cgutman** [comment]
There are instructions on Discord for how to do this:
![image](https://user-images.githubusercontent.com/2695644/66710240-2a433380-ed29-11e9-9d44-9579b15b7f46.png)
