### ISSUE TITLE
Macos xbox one rumble/vibration

### ISSUE THREAD

**Issue by ahasani** [moonlight-stream/moonlight-qt#279]
Hi, i maybe missing something here,,rumble is not working on MacOS. I remember it was working on version like 0.9ish, then it stop working.
I am using Xbox one controller usb connected with [360Controller](https://github.com/360Controller/360Controller) driver on mac 10.14.6 using Moonlight version 1.1.1

Cheers

**Comment by cgutman** [comment]
Can you upload logs of you streaming with rumble not working?

On macOS, Moonlight-###.log files can be found in /tmp. In Finder, press Cmd+Shift+G, then type /tmp to navigate there.

**Comment by ahasani** [comment]
Hi, Thanks, really enjoying moonlight.

Kindly find the attached

[Moonlight-1570265626.log](https://github.com/moonlight-stream/moonlight-qt/files/3693035/Moonlight-1570265626.log)

Cheers

**Comment by Clete2** [comment]
I can't get rumble to work with Mac either. Using a PS3 controller via Bluetooth.

**Comment by ZerOri** [comment]
> Can you upload logs of you streaming with rumble not working?
> On macOS, Moonlight-###.log files can be found in /tmp. In Finder, press Cmd+Shift+G, then type /tmp to navigate there.

Can it rumble with a wireless connection?

**Comment by ahasani** [comment]
> Can it work with a wireless connection in Win10?

Nope

**Comment by cgutman** [comment]
@ahasani  Can you try running Moonlight from the Terminal like this: `SDL_JOYSTICK_HIDAPI_XBOX=0 /Applications/Moonlight.app/Contents/MacOS/Moonlight` and see if rumble works when launched this way?

**Comment by cgutman** [comment]
Fixed by c8b887fe32a893a441a63dceb022281d2b330698

**Comment by ahasani** [comment]
Apologies for not responding earlier, jumbled through the email filtering.
It does indeed fixed in 1.2.

Really grateful & many thanks
Cheers
