### ISSUE TITLE
Error when enable both wifi and ethernet (port forward on ethernet's IP)

### ISSUE THREAD

**Issue by ngonhan2k5** [moonlight-stream/moonlight-qt#280]
**Describe the bug**
Moonlight cannot connect when both wifi and ethernet enabled on host pc.

**Comment by ngonhan2k5** [comment]
[Moonlight-1570608467.log](https://github.com/moonlight-stream/moonlight-qt/files/3706282/Moonlight-1570608467.log)
![bug1](https://user-images.githubusercontent.com/6723054/66464360-0671ba80-eaa9-11e9-8ce4-8d47ecd5c757.PNG)

**Comment by cgutman** [comment]
This is a bug in the libenet library that Nvidia uses. It can respond on the wrong connection, so the response doesn't make it back to the client device. We can work around this issue on the same LAN (and that workaround is present in v1.1.1) but not over the Internet.

The Internet Hosting Tool v4.3 will warn you if you have a configuration with two connections to the same network like this. You should disable one of them to stream reliably over the internet as it says in the warning.
