### ISSUE TITLE
Game Streaming While Signed In to Different User? 

### ISSUE THREAD

**Issue by FractumSeraph** [moonlight-stream/moonlight-qt#282]
I have a good gaming rig currently set up for public use.  Is there any way I can have a game streaming from this PC, while somebody else is signed in to the PC on a different user browsing Facebook or something?

I've been able to do this with some things, but not this.  For example, I'm running Emby and Minecraft servers from my user, while the other family members are signed in to window as a different user.

Can this be done for game streaming?  Whenever I'm streaming a game it seems to get disconnected if I try to switch users.

**Comment by cgutman** [comment]
This isn't possible due to how NVIDIA GameStream works (and client versions of Windows don't support multiple concurrent user sessions either).
