### ISSUE TITLE
Moonlight changing default audio device 

### ISSUE THREAD

**Issue by shustema** [moonlight-stream/moonlight-qt#285]
I have a USB headset on the Windows 10 streaming host, and the NVIDIA HDMI audio is auto changing to the default device whenever I try to switch the default device to the local USB device.

**Comment by cgutman** [comment]
GameStream uses a virtual audio device to capture audio from the host. If you want audio to continue to play from the host PC, you can check the "Play audio on PC" checkbox in Moonlight.
