### ISSUE TITLE
Moonlight client freezes when host views full screen video 

### ISSUE THREAD

**Issue by DevGoslinga** [moonlight-stream/moonlight-qt#290]
Moonlight client freezes when host views full screen video in certain programs like Firefox and UWP apps.

Someone reported the bug at bugzilla: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1580107

Because the bug is not exclusive to Firefox I created this issue.

I am running on Windows 10 1903 and the latest moonlight client.

GPU details: 
NVIDIA GeForce GTX 1060 
NVIDIA driver version 441.08

**Comment by DevGoslinga** [comment]
I changed the bugzilla link it was not pointing to the correct bug report.
https://bugzilla.mozilla.org/show_bug.cgi?id=1580107

**Comment by simpman** [comment]
I know this is old, but this still occurs for me. I've determined it's not just full screen video it's anytime Firefox is full screen mode (F11). The renderer 'freezes' and recovers when the application isn't full screen. Haven't found a solution but I did find a workaround using about:config and setting full-screen-api.ignore-widgets to true. This will allow you to go almost full screen. You can set the taskbar to "auto-hide" for the best experience. Hopefully this helps someone.

**Comment by hoggatt** [comment]
I don't have an issue with full screen browser (Alt+F11), but if I full screen any video (youtube or otherwise), the video freezes and the audio keeps going until I move my mouse.

**Comment by simpman** [comment]
I notice that this problem only occurs for VP9-encoded videos on YouTube. AV1 videos do not have the same issue. You can confirm to see what codec is being used by right clicking on the video and selecting "Stats for Nerds" and checking the Codec there. Good news is you can change what codec is preferred in YouTube Settings. Under Playback and Performance > AV1 settings. A word of warning that older computers may struggle more with AV1 than VP9 at higher resolutions.

**Comment by Akryllax** [comment]
Got the same issue. Changing to AV1 didn't fix it, but strangely when the window (Firefox in this case) looses focus, like pressing Windows key to open the Start Menu, then video playback resumes.

I think it might be relate with some buffer cleanup thing, as I am also using Yuzu lately, and when I get into the UI of a game, then framerate drops very significantly (<15 FPS) until I open and close the Start Menu, when I get back to 60FS. Moonlight client for RPI4 8GB.

**Comment by GucciGross** [comment]
It's something to do with overlays. I use OnTopReplica and it fixes the issue.

**Comment by simpman** [comment]
Using Sunshine instead of GFE is also working for me without other workarounds. YMMV
