### ISSUE TITLE
Microphone support

### ISSUE THREAD

**Issue by MosesXu159** [moonlight-stream/moonlight-qt#294]
Hello!
 I would like to know if there will be microphone support in the future.

**Comment by cgutman** [comment]
This is something that requires support from Nvidia on the host-side before we can implement it. If they do add mic support in an update, we will definitely add support.

**Comment by vdsbenoit** [comment]
My workaround was to use Skype + [VB audio cable](https://www.vb-audio.com/Cable). I call myself on the host computer and I pipe the incoming sound from the call into a virtual input device. 

Here is a quick procedure : 
1. Create 2 Skype accounts
2. Install VB audio cable on the host (the Gamestream computer) 
3. Install Skype for desktop on the host computer, log in and set it up in order to auto accept incoming calls from contacts and to use the virtual input as microphone.
4. Call the host device with another device
5. Enjoy your game

**Comment by lacksfish** [comment]
@vdsbenoit solid advice.

Sometimes a clicking sound of the mouse buttons or my breathing gets passed through and I hear it as "feedback", even though I do not hear myself talk as "feedback". Have you had the same issue and did you find a solution to it? It's a very minor inconvenience though so either way great solution!

**Comment by vdsbenoit** [comment]
It depends on the game you are playing at. In most of the games, you can define a mic volume threshold that will filter most of the background noise like your mouse clicking.

**Comment by bverkron** [comment]
I would really love to see this implemented. I use the AppleTV moonlight client thus cannot use the suggested workaround. Native support would be fantastic!

**Comment by cgutman** [comment]
> I would really love to see this implemented. I use the AppleTV moonlight client thus cannot use the suggested workaround. Native support would be fantastic!

As would I. Unfortunately, [my above comment](https://github.com/moonlight-stream/moonlight-qt/issues/294#issuecomment-560959355) still applies. There is no way to do this from NVIDIA GameStream as it is today. Not even the official NVIDIA Shield clients have mic support for GameStream.

**Comment by rmaenk** [comment]
> My workaround was to use Skype + [VB audio cable](https://www.vb-audio.com/Cable). I call myself on the host computer and I pipe the incoming sound from the call into a virtual input device.

Alternative:
As workaround you can try VoiceMeeter.
[Video on youtube: Dual PC Audio Setup: How to Send Audio & Microphone over Ethernet](https://www.youtube.com/watch?v=DWLOWwm4-2g)

Regards,
Roman

**Comment by os-bldx** [comment]
> Ma solution de contournement consistait à utiliser [le câble audio Skype + VB](https://www.vb-audio.com/Cable) . Je m'appelle sur l'ordinateur hôte et je dirige le son entrant de l'appel vers un périphérique d'entrée virtuel.
> 
> Voici une procédure rapide :
> 
> 1. Créer 2 comptes Skype
> 2. Installer le câble audio VB sur l'hôte (l'ordinateur Gamestream)
> 3. Installez Skype pour ordinateur sur l'ordinateur hôte, connectez-vous et configurez-le afin d'accepter automatiquement les appels entrants des contacts et d'utiliser l'entrée virtuelle comme microphone.
> 4. Appeler le périphérique hôte avec un autre périphérique
> 5. Profitez bien de votre jeu

Bonjour est-ce qu'il est possible de m'aider sur discord pour réaliser ceci car j'ai vraiment beaucoup de mal : Oscaro.com#0390

**Comment by frederikb96** [comment]
I 

> > My workaround was to use Skype + [VB audio cable](https://www.vb-audio.com/Cable). I call myself on the host computer and I pipe the incoming sound from the call into a virtual input device.
> 
> Alternative: As workaround you can try VoiceMeeter. [Video on youtube: Dual PC Audio Setup: How to Send Audio & Microphone over Ethernet](https://www.youtube.com/watch?v=DWLOWwm4-2g)
> 
> Regards, Roman

I wanted to do the same but with streaming microphone audio from Linux to Windows. And I wanted to stream mic audio only and not normal sound. I tried a bit and this is what finally worked out for me. Actually quite simple since it was possible to use Voicemeter via Wine on the Linux side to send some audio stream from my mic.

This is a simple guide I wrote for myself, which might be helpful for others:

To get a microphone transmitting working via Moonlight, we need an additional tool called Voicemeter if trying to forward microphone audio to a Windows PC (from a Linux PC or Windows PC).
- Download [Voicemeter](https://vb-audio.com/Voicemeeter/index.htm)
- And my setup is done similar to [this guide](https://www.youtube.com/watch?v=DWLOWwm4-2g)
	- However, I am only trying to send microphone input via Ethernet and I want to keep the sound output transmitted via Moonlight
	- Note: This is only possible with the sunshine client since Nvidia Shield is not allowing to change any sound devices on Windows

PC 1: transmitting mic audio (Linux)
- Install Voicemeter via Wine (or crossover)
	- I tested it with a Windows 7 32 bit bottle
- Now as Hardware Input 1 choose the microphone of yours and set the channel to B only
	- This is kind of necessary since later B is used for Audio output as microphone in Voicemeter and A is only for sound input into Voicemeter I guess
- The Hardware Output device does not matter on PC1 since we will not output anything here
	- But it must be selected since otherwise Voicemeter will complain and do nothing
- Now enable VBAN and set the IP address of PC2 and enable the output stream for Bus B

PC 2: receiving mic audio, must be Windows
- Here you have to select the Voicemeter Input device as the default audio output device
	- Only this way it works, since otherwise the mic is not working even though we do not want to output anything via Voicemeter actually, but it does not matter
	- Consequently, in Voicemeter, you have to select the real hardware output device, which you normally use, the dummy NVIDIA device if via Moonlight
	- Now audio is transmitted to Voicemeter and then to the NVIDIA output device, so only another loop added
	- Any you have to set channel A only for the Voicemeter Input in Voicemeter
- Set Hardware input 1 to channel B
- Enable VBAN and set the incoming channel to On and set the ip address of the PC 1
	- Also set destination to In1 which now receives the input from your other PC
- So result: You have on PC2 on channel A in hardware output the normal output of this local PC and on channel B the forwarded one from PC 1
	- And B is the one which is mapped to Virtual Output of Voicemeter on PC 2
- Now you simply have to select the Voicemeter output device as you microphone on PC 2 whereever you need the mic from PC 1

**Comment by JulianGro** [comment]
Since Nvidia has pretty much sunset GameStream, microphone support could be added through Sunshine.

**Comment by Acru** [comment]
> PC 1: transmitting mic audio (Linux)

Just a note, AudioRelay has a linux native app; https://audiorelay.net/downloads/linux

**Comment by anthr76** [comment]
So close, too bad it doesn't have a nixos package and proprietary :(

**Comment by alexezio** [comment]
Hi, guys, I have found the perfect solution for the voice stream between pc(thank you,acru).
You just need to install a applicaiton: [AudioRelay](https://audiorelay.net/).  It is free and easy to use, moreover, it is cross platform(you can install it in linux/macos/windows/android)
All you need to do, is lauch the audiorelay on the computer you want to stream voice as server end.  select the microphone device as output device.
<img width="823" alt="image" src="https://github.com/moonlight-stream/moonlight-qt/assets/35565813/097bdf62-e07b-4464-8f75-2e161f9f06af">

the second step: lauch the audiorelay on the pc you want to recieve the voice stream as player end.  and use the virtual mic device as default input device. then we can have fun.
 
<img width="481" alt="image" src="https://github.com/moonlight-stream/moonlight-qt/assets/35565813/555501da-e224-4cf2-898c-ecae792a1982">

don't forget add the port-forwarding rule if the pcs are not in the same network(don't expose 59200/udp, this is for server discovery).
port: tcp/udp 59100

**Comment by anthr76** [comment]
FWIW I have managed to use VB audio cable along with mumble between linux to windows

**Comment by anthr76** [comment]
I would love to start a bounty for support in sunshine/moonlight

**Comment by Clovis-krz** [comment]
Does anyone have a solution to use my microphone connected to my raspberry pi (raspbian) on my remote pc (windows) while using moonlight ? All the solutions I have seen are not rpi compatible

**Comment by Acru** [comment]
> Does anyone have a solution to use my microphone connected to my raspberry pi (raspbian) on my remote pc (windows) while using moonlight ? All the solutions I have seen are not rpi compatible

I was just thinking, AudioRelay also has an android app; https://play.google.com/store/apps/details?id=com.azefsw.audioconnect

Now I don't know if this will work, but I understand there are ways to get android apps working on a pi, either by changing the os or via waydroid or a vm or such.  Though of course not as good as a native solution, let me know if you find success.

**Comment by S0ly** [comment]
still not native ?

**Comment by R-Bose** [comment]
Hi, is it possible to pay for this feature? In order to incentivise developers?

**Comment by Acru** [comment]
> Hi, is it possible to pay for this feature? In order to incentivise developers?

Others have mentioned about starting a bounty pool for it, which would be better than fronting up cash just by yourself, though idk if anything happened with that?  The main problem is also getting support into [Sunshine](https://github.com/LizardByte/Sunshine), a separate project, at the same time.  (Most people are using Moonlight exclusively with Sunshine now, are they not?  Perhaps this issue should be re-opened with that in mind.)

As to alternatives in the mean time, I had written up a reddit post on how to use AudioRelay or VoiceMeeter to achieve the same thing with 3rd party software; https://www.reddit.com/r/MoonlightStreaming/comments/11x2y3y/comment/kjfyj58/

**Comment by 9cento** [comment]
> Hi, guys, I have found the perfect solution for the voice stream between pc without gpu support(thank you,acru). In my scenarios. I want to streaming my macos voice to a windows machine You just need to install a applicaiton: [AudioRelay](https://audiorelay.net/). It is free and easy to use, moreover, it is cross platform(you can install it in linux/macos/windows/android) All you need to do, is lauch the audiorelay on the computer you want to stream voice as server end. select the microphone device as output device. <img alt="image" width="823" src="https://private-user-images.githubusercontent.com/35565813/294380614-097bdf62-e07b-4464-8f75-2e161f9f06af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwODU3ODQsIm5iZiI6MTcyNjA4NTQ4NCwicGF0aCI6Ii8zNTU2NTgxMy8yOTQzODA2MTQtMDk3YmRmNjItZTA3Yi00NDY0LThmNzUtMmUxNjFmOWYwNmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDIwMTEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MGY3ODVjNmZlNzdkNmFmOTM4ZGExNGI0OGMzZjZmY2YyMTQ5ZDAzODA4OWZhNjY0NWNmOTI2ZDBjOWZiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BGTjbiu5qPcelPuSOr6ASwQ4JvMykH0ncekxkLwiOlE">
> 
> the second step: lauch the audiorelay on the pc you want to recieve the voice stream as player end. and use the virtual mic device as default input device. then we can have fun.
> 
> <img alt="image" width="481" src="https://private-user-images.githubusercontent.com/35565813/294381434-555501da-e224-4cf2-898c-ecae792a1982.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwODU3ODQsIm5iZiI6MTcyNjA4NTQ4NCwicGF0aCI6Ii8zNTU2NTgxMy8yOTQzODE0MzQtNTU1NTAxZGEtZTIyNC00Y2YyLTg5OGMtZWNhZTc5MmExOTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDIwMTEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZWU5NGI4OTA3ODg4ZTJiZTBmMjIzMWIyMTU4NDExYjAxY2FlZGQ5ZTcxNTg2NDU1MDkyZjFlMjc3MjA2NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zUwFr8bAtyjpzIn_DI0c6GXBfDRRo1M55ArdwEKSGto">
> don't forget add the port-forwarding rule if the pcs are not in the same network(don't expose 59200/udp for secure reason, this is for server discovery). port: tcp/udp 59100

Underrated, thanks!
