### ISSUE TITLE
Star Wars Jedi Fallen Order doesn't show up on Moonlight?

### ISSUE THREAD

**Issue by ntheosis** [moonlight-stream/moonlight-qt#295]
Hi,

It shows up on my Geforce Experience games list, but not on Moonlight.  I have to manually add it to Geforce Experience for it to actually show up on Moonlight.

Any way to fix this?

**Comment by Forceflow** [comment]
Unfortunately, afaik, the list of games that gets "approved" for GameStream (which is a different list than the one of "games GFE has a profile for") is maintained by Nvidia. And not updated regularly, if at all.

**Comment by cgutman** [comment]
Yep, that's correct.
