### ISSUE TITLE
Ability to force host resolution

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-qt#297]
Could the ability to force the host's screen resolution be added? IE force screen resolution of the host to 1440p, 1080p, etc? I can see this being useful if you have a game that does not have Gamestream ability and also cannot add it to Gamestream as an app (Looking at you Modern Warfare), Currently, in order to stream it at all, I stream my desktop and launch the app, but given I have an Ultrawide on my main machine, this complicates things on the client side as it is an 21:9 image being displayed on a 16:9/10 aspect ratio. I am unsure whether this issue could be addressed within Moonlight or if it is a flaw in Gamestream itself.

**Comment by cgutman** [comment]
Unfortunately, I believe that's a GameStream limitation.
