### ISSUE TITLE
Using quit session shortcut doesnt reset server

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#301]
Using the Ctrl+Alt+Shift+Q - Quit session shortcut doesnt reset the server, for example to the previous used resolution.

**Comment by cgutman** [comment]
The quit shortcut just disconnects your session. If you want to quit the game (losing any unsaved progress) when you disconnect, you can enable the "quit app" option in Moonlight settings.

**Comment by makedir** [comment]
Then would be nice, if you could add a nother chortcut which does that. Better: add a button to the client, which does it (send sigterm or whatever reset to default to server).

**Comment by cgutman** [comment]
There are buttons on the app grid that let you resume or quit the running app.

I would need to think about how to do the quit app shortcut safely since there is a significant risk of progress loss if it is accidentally triggered. You can file an issue for that one.
