### ISSUE TITLE
Add a stream desktop button / icon to the game list

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#302]
Please add a Desktop as a game to stream to just open a stream to the server, for test but also using it for any application / game you want, even browsing, or Photoshop or else. It would makes things way easier.

**Comment by cgutman** [comment]
We already have instructions on how to do this in the setup guide. 

https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop

**Comment by makedir** [comment]
@cgutman doesnt work, tried adding it, starting it via moonlight says:

https://i.imgur.com/Ti5q3pi.png
