### ISSUE TITLE
Moonlight not streaming

### ISSUE THREAD

**Issue by TheMCHacker785** [moonlight-stream/moonlight-qt#303]
I have been trying to use moonlight to connect to my gaming PC, and it works great when I installed it on ios. I then went to install moonlight on my windows 10 DELL Latitude E6440. This laptop has a 4th gen i7 dual core Intel HD Graphics 4600 and an AMD Radeon HD 8600M Series graphics card. When  I load up it gives me the error of "No functioning hardware accelerated H.264 video decider was detected by Moonlight." When I load up a game after a loading the screen turns white then the window closes, no logs in event viewer.  My log will be down below, I would like to know if there is a fix for this problem, and if there is please tell me.

00:00:00 - SDL Info (0): Compiled with SDL 2.0.10
00:00:00 - SDL Info (0): Running with SDL 2.0.10
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "C:/Users/User/Desktop/New folder/MoonlightPortable-x64-1.1.1/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 25 new gamepad mappings
00:00:00 - SDL Info (0): V-sync enabled
00:00:00 - SDL Info (0): Windowed mode with DWM running
00:00:00 - SDL Info (0): Windowed: 1 | Present Interval: 80000000
00:00:00 - SDL Info (0): Detected GPU: AMD Radeon HD 8600M Series (1002:6660)
00:00:00 - SDL Info (0): GPU driver: aticfx64.dll 26.20.12028.2
00:00:00 - SDL Error (0): GetDecoderDeviceGuids() failed: 80004001

connecting to host, no errors in the mid section

00:01:55 - SDL Info (0): Initializing platform...
00:01:55 - SDL Info (0): done
00:01:55 - SDL Info (0): Resolving host name...
00:01:55 - SDL Info (0): done
00:01:55 - SDL Info (0): Starting RTSP handshake...
00:01:55 - SDL Info (0): done
00:01:55 - SDL Info (0): Initializing control stream...
00:01:55 - SDL Info (0): done
00:01:55 - SDL Info (0): Initializing video stream...
00:01:55 - SDL Info (0): done
00:01:55 - SDL Info (0): Initializing audio stream...
00:01:55 - SDL Info (0): done
00:01:55 - SDL Info (0): Initializing input stream...
00:01:55 - SDL Info (0): done
00:01:55 - SDL Info (0): Starting control stream...
00:01:55 - SDL Info (0): done
00:01:55 - SDL Info (0): Starting video stream...
00:01:55 - SDL Info (0): Video stream is 1280x720x60 (format 0x1)
00:01:55 - SDL Info (0): done
00:01:55 - SDL Info (0): Starting audio stream...
00:01:55 - SDL Info (0): Audio backend: WASAPI
00:01:55 - SDL Info (0): Selected audio device: Speakers / Headphones (Realtek High Definition Audio)
00:01:55 - SDL Info (0): Native layout: Stereo (2 channels)
00:01:56 - SDL Info (0): Audio buffer size: 3 packets
00:01:56 - SDL Info (0): Audio stream has 2 channels
00:01:56 - SDL Info (0): done
00:01:56 - SDL Info (0): Starting input stream...
00:01:56 - SDL Info (0): done
00:01:56 - SDL Info (0): Qt UI screen is at (0,0)
00:01:56 - SDL Info (0): SDL found matching display 0
00:01:56 - SDL Info (0): Chosen best display mode: 1600x900x60
00:01:56 - SDL Info (0): V-sync enabled
00:01:56 - SDL Info (0): V-Sync enabled
00:01:56 - SDL Info (0): Windowed: 0 | Present Interval: 1
00:01:56 - SDL Info (0): Detected GPU: AMD Radeon HD 8600M Series (1002:6660)
00:01:56 - SDL Info (0): GPU driver: aticfx64.dll 26.20.12028.2
00:01:56 - SDL Error (0): GetDecoderDeviceGuids() failed: 80004001
00:01:56 - Qt Info: Found "ModeSeven.ttf" at ":/data/ModeSeven.ttf"

**Comment by cgutman** [comment]
I think we got this error sorted out on Discord. Reopen if that's not the case.
