### ISSUE TITLE
NvidiaStream Service / Moonlight creating a lot of virtual controllers

### ISSUE THREAD

**Issue by Forceflow** [moonlight-stream/moonlight-qt#304]
**Describe the bug**
After a few days of using Moonlight (on my Steam Link - loving it!), I was looking at the Win10 Device Manager, with "show hidden devices" turned on, and I found **a lot** of unattached XBOX360 controllers. We're talking 20+ devices. Curious where these came from, I started digging.

Turns out they were created by Nvidia Stream Server. All the devices have a VID _(vendor id)_ of 0955, which is the ID of Nvidia.

I'm not sure whether the specific use of Moonlight triggers this behaviour, or if it's a problem with the SHIELD devices in general as well. I don't own a SHIELD device, and can not test.

I could replicate the behavior of creating a new controller for every session (whilst only having one and the same controller attached to the client) with ... and this is where it gets weird ... having **[Teamspeak](https://www.teamspeak.com/en/)** open. 

This is the program I could reliably replicate this with uptil now. Note that it never has to be in focus, it doesn't even have to be connected to a server to cause the behaviour.

**Steps to reproduce**
_Come with me on a journey!_ 

**Please note** In all the following screenshots I'm using [DevManview](https://www.nirsoft.net/utils/device_manager_view.html), which is an advanced Device Manager Viewer by the great Nirsoft. Green lines mean = device is connected. The view is always filtered on `HID\VID_0955 USB\VID_0955`, so we only see Nvidia-related Human Interface Devices and USB (virtual) devices.

**STEP 1:** We start with a system that is fresh. I've removed all virtual controllers, this is the "clean" state before a GameStream connection is ever made.

![step1](https://user-images.githubusercontent.com/3607063/69908206-2193e300-13e5-11ea-9f1f-c6f2c19d9ec4.png)

**STEP 2:** We start a first GameStream session (just streaming desktop). Hey presto, the required virtual devices are added and used!

![step2](https://user-images.githubusercontent.com/3607063/69908216-42f4cf00-13e5-11ea-924d-1c429639ad5f.png)

**STEP 3:** We close the session from Step 2, and start a new one. Yay, the previously created devices are re-used! Now, before we go to Step 4, start Teamspeak. You don't have to connect to a server, just have it sit in the tray.

![step3](https://user-images.githubusercontent.com/3607063/69908221-6586e800-13e5-11ea-82fd-0b0ccb5efe04.png)

**STEP 4:** We close the session from Step 3, and start a new one.  An **extra** bunch of devices is created, and a new XBOX controller is attached to port 1. Notice how _nothing_ client-side has changed: same controller, same device, same client.

![step4](https://user-images.githubusercontent.com/3607063/69908230-a1ba4880-13e5-11ea-842e-43f24ae69e25.png)

**STEP5:** You can guess what happens in the next sessions we open / close / open : more devices are created. None of the old ones are re-used. I tested this with desktop sessions, game sessions, whatever ... every time you get the win10 info toast "virtual device added", and a new device shows up in the device manager

![step5](https://user-images.githubusercontent.com/3607063/69908232-b39beb80-13e5-11ea-9102-cf959bfaa174.png)

**STEP6:** Close Teamspeak and start a new session. Yay, we're reusing the original port 0 device again! But all the lifeless bodies of the other virtual controllers remain. This _quickly_ builds up to a lot of hidden devices.

![step6](https://user-images.githubusercontent.com/3607063/69908262-12f9fb80-13e6-11ea-9bbd-d5a9a0ca0ad9.png)

(tested it a few more times to be sure)

**Affected games**
Any initiated GameStream. Tried with desktop streaming, Steam, starting executables (Notepad, Control DX12 version, .. )

**Other Moonlight clients**
Unfortunately cannot test with other clients.

**Moonlight settings (please complete the following information)**
Changed from default: allow gamepad mouse input. Toggling it on or off did not change the behaviour, the same with "force gamepad 1". Does not make a difference, unfortunately

**Client PC details (please complete the following information)**
 - Steam Link, Moonlight 1.1.1 for Steam Link.

**Server PC details (please complete the following information)**
 - OS: Windows 10 1909, RTX Super 2070
 - GeForce Experience version: 3.20.1.57
 - Nvidia GPU driver: 441.41

**For testing, replicating:**
The following command will remove all Nvidia HID/USB devices from a system. It uses the command-line version of the [Device Cleanup Tool](https://www.uwe-sieber.de/misc_tools_e.html) by Uwe Sieber.

``DeviceCleanupCmd HID\VID_0955* USB\VID_0955*``

This is important: running this as non-administrator will just list the devices, **running it as administrator will remove them** , after automatically making a system restore point. 

I've run this script a dozen of times on my system and nothing exploded, but caution. The tool should only remove plug-and-play devices that are not connected.

You can also manually remove the devices using Device Manager or the GUI version of Device Cleanup Tool, but that's a lot more clicking, and imho more error-prone, since you have to manually verify the ID for every entry.

**Comment by Forceflow** [comment]
**Confirmed workaround:** Disable the plug-in for gamepads/joysticks that (appearantly) comes with TeamSpeak: Tools -> Options -> Addons -> Plugins -> Gamepad and Joystick Support

Will create a PR on the wiki to add TS to problematic software.

**Comment by cgutman** [comment]
Updated https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#known-application-compatibility-issues with this info
