### ISSUE TITLE
Lag Spike with Xbox One Controller When Firing From a FPS Machine Gun

### ISSUE THREAD

**Issue by jeremybris** [moonlight-stream/moonlight-qt#305]
**Describe the bug**
See the video under screenshots for an example.

Using the default settings of Moonlight Stream, and when I am using an Xbox One controller through bluetooth, whenever I shoot with a machine gun in a game, I get a lag spike.

**Steps to reproduce**
- Use an Xbox One Controller through bluethooth
- Shoot a machine gun in a 1st person game that causes the controller to vibrate, and try to move the right analog stick at the same time
- I used the Outer Worlds and the Master Chief Collection

**Screenshot(s)**
- https://www.youtube.com/watch?v=5PNSnHwudzw

**Affected games**
- Outer Worlds
- The Master Chief Collection (Halo Reach)
- Probably other 1st person shooters with machine guns

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android? - No (But I also do not receive a huge amount of vibration in my controller on the Android version as I do in the Windows version, which I think may be part of the problem.)

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from the defaults? - No

**Client PC details (please complete the following information)**
 - OS: Windows 10 1909 64-bit **(Latest 12/04/19)**
 - Moonlight Version: v. 1.1.1 **(Latest 12/04/19)**

**Server PC details (please complete the following information)**
 - OS: Windows 10 1909 64-bit **(Latest 12/04/19)**
 - GeForce Experience version: v.3.20.1.57 **(Latest 12/04/19)**
 - Nvidia GPU driver: 441.41 **(Latest 12/04/19)**

**Moonlight Logs (please attach)**
- Windows 10 Portable Log 
- [Moonlight-1575491103.log](https://github.com/moonlight-stream/moonlight-qt/files/3923819/Moonlight-1575491103.log) 
- [Moonlight-1575491142.log](https://github.com/moonlight-stream/moonlight-qt/files/3923820/Moonlight-1575491142.log)

**Additional context**

- This issue may be related to #168 , but at least I know how to reproduce my lag issue.

- It seems like the issue is when there is too much input and/or output at one time, and the streaming service tries to catch up. After and before it catches up, it works perfectly fine. 

- I am streaming the Desktop https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop _not_ the application. I am not sure if that matters.

- I _didn't_ try Steam big picture because the Outer Worlds and the Master Chief Collection are on the Windows Store.

- I reproduced this on two, seperate client pcs (using the portable and installer), so it is either my internet or the Moonlight Streaming service. My internet is 20 mb/s download, 10 mb/s upload.

- I got it to work perfectly _once_ when I reinstalled Moonlight, but then never again (even after reinstalling Moonlight). If it works perfectly for you, maybe keep trying subsequent, new sessions to reproduce.

- Issue is present in Moonlight v. 1.0, not sure about older versions.

**Comment by cgutman** [comment]
Can you try disabling rumble/vibration in the game and see if the lag goes away?

Can you try connecting the controller to your PC via USB and see if the lag goes away?

**Comment by jeremybris** [comment]
> Can you try disabling rumble/vibration in the game and see if the lag goes away?
> 
> Can you try connecting the controller to your PC via USB and see if the lag goes away?

Good idea!

- 1st idea (disable rumble ingame) - Works perfectly!
- 2nd idea (plug in controller) - I am missing the plug, and I will update you if I can find the plug.

**Comment by jeremybris** [comment]
> Can you try disabling rumble/vibration in the game and see if the lag goes away?
> 
> Can you try connecting the controller to your PC via USB and see if the lag goes away?

I did some more testing, with a PS4 Controller, and it works fine. So, it appears as though the bluetooth on Xbox One controller may be defective. I will see if there are any driver updates for me controller.

**Comment by cgutman** [comment]
I added some logging of rumble packets to see if we're getting anything excessive from the host. Can you try this build and attach a new log after reproducing the issue?

https://ci.appveyor.com/api/buildjobs/hec0oaugh6ecb9g9/artifacts/MoonlightPortable-x64-release.zip

**Comment by jeremybris** [comment]
> I added some logging of rumble packets to see if we're getting anything excessive from the host. Can you try this build and attach a new log after reproducing the issue?
> 
> https://ci.appveyor.com/api/buildjobs/hec0oaugh6ecb9g9/artifacts/MoonlightPortable-x64-release.zip

Here are two logs of the same event (which is me doing this https://www.youtube.com/watch?v=5PNSnHwudzw).

- (**Not Working**) Xbox One bluetooth log: [Moonlight-1575514816.log](https://github.com/moonlight-stream/moonlight-qt/files/3924934/Moonlight-1575514816.log)
- (**Working**) DS4Windows log (emulated, bluetooth, Xbox 360 controller): [Moonlight-1575515144.log](https://github.com/moonlight-stream/moonlight-qt/files/3924938/Moonlight-1575515144.log)

It may be just a problem with my Xbox One controller. If I had another Xbox One controller I could if it is my controller or not, but I do not.

**Comment by jeremybris** [comment]
I think I will close this issue. I have a workaround.

I believe it is my Xbox One controller, because no one else has reported this obvious problem, but if someone else does report this in the future, we can reopen this.
