### ISSUE TITLE
Fails to find x264 decoder on ChromeOS Debian

### ISSUE THREAD

**Issue by ischorr** [moonlight-stream/moonlight-qt#307]
**Describe the bug**
Flatpack-installed Moonlight complains about no functioning h.264 hardware decoder running in ChromeOS Debian (Chrome version and Android run fine)

**Steps to reproduce**
Any special steps that are required for the bug to appear.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
No.

**Client PC details (please complete the following information)**
 - OS: Chrome OS 79.0.3945.66
 - Moonlight Version: 1.1.1

**Moonlight Logs (please attach)**
$ flatpak run com.moonlight_stream.Moonlight
00:00:00 - SDL Info (0): Compiled with SDL 2.0.10
00:00:00 - SDL Info (0): Running with SDL 2.0.10
00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:01 - SDL Info (0): Loaded 32 new gamepad mappings
00:00:01 - SDL Info (0): V-sync enabled
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
00:00:01 - SDL Error (0): Failed to initialize VAAPI: -1
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x59556e1d9e40] VDPAU device creation on X11 display :99.0 failed.
00:00:01 - SDL Error (0): Failed to create VDPAU context: -1313558101
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x59556e1c09c0] Cannot load libcuda.so.1
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x59556e1c09c0] Could not dynamically load CUDA
00:00:01 - SDL Error (0): av_hwdevice_ctx_create(CUDA) failed: -1313558101
00:00:01 - Qt Info: Found "ModeSeven.ttf" at ":/data/ModeSeven.ttf"
00:00:01 - SDL Info (0): Using SDL renderer
00:00:01 - FFmpeg: [h264 @ 0x59556e88f480] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x59556e88f480] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x59556e88f480] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x59556e88f480] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x59556e88f480] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x59556e88f480] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x59556e88f480] Format yuv420p chosen by get_format().
00:00:01 - FFmpeg: [h264 @ 0x59556e88f480] Reinit context to 1280x720, pix_fmt: yuv420p
00:00:01 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:01 - SDL Info (0): Loaded 32 new gamepad mappings
00:00:01 - Qt Debug: Current Moonlight version: "1.1.1"

**Additional context**
Initial version of Moonlight shipping with ChromeOS+Debian 9 failed with "Could not initialize GLX" errors.

Led to upgrade flatpak to latest supported with Stretch - 1.2.4.  Upgraded Moonlight correspondingly.

Moonlight ran and streamed ok, but failed to find hardware h.264 decoder, presumably due to https://github.com/flatpak/flatpak/issues/3126 , fixed in flatpak 1.2.5

No flatpak 1.2.5 package for Stretch, updated to Buster

h.264 package installed properly, but still failing to attach as above, even forcing -platform wayland

**Comment by cgutman** [comment]
Hardware-accelerated video decoding APIs are not exposed in the Crostini sandbox, so this is a Crostini limitation not a Moonlight issue.
