### ISSUE TITLE
'Stop Streaming' option no longer available in Steam

### ISSUE THREAD

**Issue by lkaczmarski** [moonlight-stream/moonlight-qt#308]
Hello, 
I think this has changed after the recent GFE update. While streaming Steam, the option to choose 'Stop streaming' disappeared from the menu which pops up after you press Escape key. Does anyone know how to fix that? 
Thanks,
Lucas

**Comment by cgutman** [comment]
I believe a Steam update actually caused this. Every so often Steam seems to break their API for launching in "streaming mode" which requires Nvidia to update GFE to fix it.
