### ISSUE TITLE
brightness too high when use moonligh on every device

### ISSUE THREAD

**Issue by hackernich** [moonlight-stream/moonlight-qt#313]
hi every one , i have nvidia gtx 1080 and every device is connected by ethernet, so i can stream from my pc to my phone or my ipad or every device without any issue , i stream at 1080p at 60 fps but i don't know why the brightness is set at max when i start the stream , is anything can i do to fix this problem??

**Comment by cgutman** [comment]
Can you describe what you see in more detail?

Are you saying the screen brightness on your client devices are increased to 100%? Or are you saying that the host PC brightness is set to 100%?

**Comment by hackernich** [comment]
Yes  if you want i can add you on WhatsApp and show you Extacly what happen

**Comment by hackernich** [comment]
The host PC remain at the same brightness As usual but on the device that i use moonlight the brightness is set at maximum but if i try to change from PC or from the device nothing change

**Comment by apereira435** [comment]
I have the same issue, can someone pleas help? 
Same thing, I connect to the host and the brightness goes up. But only on the streaming signal. I have a 970 GTX.
