### ISSUE TITLE
stream trough NAT-VPN issues on 2.1.1

### ISSUE THREAD

**Issue by lodiabloc** [moonlight-stream/moonlight-qt#315]
**Describe the bug**
I use a NAT open-vpn on opnsense firewall to access my home network from internet. the firewall allow all trafic trough the tunnel

- Since I Upgraded to 2.1.1 i cannot connect moonlight to acces my computer for game stream, the host seem to be unreachable (with a warning icon on computer in moonlight UI)
- I tried to associate this again trough the vpn with IP adress and don't work too
- On local network (when i'm in home) the connection is ok
- the other RAT trough vpn is ok (vnc)

I roll-backed the version of moonlight to 1.1.1.0 and I don't encounter this problem trough VPN.

**Steps to reproduce**
- make a firewall appliance with nat openvpn configuration
- associate client and server on local network
- from internet connect your vpn to access local network
- start moonlight and try to connect to our PC

**Screenshots**

**Affected games**
all

**Other Moonlight clients**
I only use on windows client version 2.1.1 (don't work) and 1.1.1 (work)

**Moonlight settings (please complete the following information)**
- resolution modified (720p to 1080p@60fps) for adjusting to my client screen
- i reinstall from scratch the problem is same

**Client PC details (please complete the following information)**
 - OS: Windows 10 1903
 - Moonlight Version: [2.1.1]
 - old version that work : 1.1.1

**Server PC details (please complete the following information)**
 - OS: [Windows 10 1903]
 - GeForce Experience version: [3.1.20.57]
 - Nvidia GPU driver: [441.66]
 - GPU : 970 GTX x2 (SLI)

**Moonlight Logs (please attach)**
- see attachment
[v1.1.1 associated trough vpn ok.log](https://github.com/moonlight-stream/moonlight-qt/files/3992899/v1.1.1.associated.trough.vpn.ok.log)
[v2.1.1 on localnetwork ok.log](https://github.com/moonlight-stream/moonlight-qt/files/3992900/v2.1.1.on.localnetwork.ok.log)
[v2.1.1 trough vpn not ok.log](https://github.com/moonlight-stream/moonlight-qt/files/3992901/v2.1.1.trough.vpn.not.ok.log)

**Additional context**
 - I tried the rollback because i do the update 1.1.1 to 2.1.1 while i'm at home. i tried local connexion  same day and it's ok
the next day i tried to connect remotely and it don't work.
the only change i have done is the update of moonlight client.

 - In my client vpn configuration i force "all traffic trough the tunnel" by changing the default route on system

 - I hidden my public IP of server in logfiles for wol request because it was a static ip

 - sorry for my bad english

**Comment by cgutman** [comment]
Your 1.2.1 log is actually from 1.2.0. It says:
`00:00:00 - Qt Debug: Current Moonlight version: "1.2.0"`

The issue you're having is fixed in 1.2.1. You may need to download it manually because the bug also breaks the automatic update check.

**Comment by lodiabloc** [comment]
thanks for your fast reply, in fact i don't realize the new version released between my bug ascertainment and my report submission 

I installed the new version manually and work fine. :)
