### ISSUE TITLE
Moonlight detected gamepads without a mapping

### ISSUE THREAD

**Issue by alexpdp7** [moonlight-stream/moonlight-qt#318]
**Describe the bug**

Hi, when starting moonlight QT using the Flatpak, I get:

> Moonlight detected gamepads without a mapping:
> 8Bitdo FC30 Pro      8Bitdo FC30 Pro

If I follow the steps in the help button, I use the gamepad tool and it *does* recognize my gamepad. The console logs say:

```
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 76 new gamepad mappings
00:00:00 - SDL Info (0): Unmapped joystick: 8Bitdo FC30 Pro    8Bitdo FC30 Pro 03000000c82d00000090000011010000
00:00:00 - SDL Info (0): Number of axes: 6 | Number of buttons: 15 | Number of hats: 1
00:00:00 - SDL Warn (0): Joystick likely to be an unmapped game controller
```

The relevant entry in the database ( https://github.com/gabomdq/SDL_GameControllerDB/blob/aeebc86f9ffe10103fadba1b5fab459f9c23e142/gamecontrollerdb.txt ):

```
05000000c82d00001038000000010000,8Bitdo FC30 Pro,a:b1,b:b0,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b6,leftstick:b13,lefttrigger:b8,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:b9,rightx:a2,righty:a3,start:b11,x:b4,y:b3,platform:Linux,
```

**Client PC details (please complete the following information)**
 - OS: Debian 10.2
 - Moonlight Version: 

```
Description                                                                  Application                                 Version        Branch      Arch        Origin       Installation
Moonlight - Play games remotely from your NVIDIA GameStream-enabled PC       com.moonlight_stream.Moonlight              1.2.0          stable      x86_64      flathub      system
```

**Comment by alexpdp7** [comment]
Might be caused by using the controller plugged in with USB. However, an Nvidia update has apparently borked stuff, so can't confirm right now.

**Comment by cgutman** [comment]
Yeah I think it's USB vs BT. I believe the leading byte of the mapping ID is the interface type (05 - BT vs 03 - USB).

We source our mappings from the [SDL_GameControllerDB project](https://github.com/gabomdq/SDL_GameControllerDB) so you should submit your mapping there, and I will pull it into the next update.

**Comment by shodanx2** [comment]
Hello,
I have an X52 pro hotas plugged in and I get this warning all the time.
Is there a command line argument I could use to not have this warning pop up every time ? 
Thanks !

**Comment by null-von-sushi** [comment]
I get this message on my steam deck now and moonlight is unusable now
