### ISSUE TITLE
Extreme lag while using a mouse with high polling rate

### ISSUE THREAD

**Issue by krektonik1** [moonlight-stream/moonlight-qt#319]
Everything except the mouse works perfectly. Zero input lag over LAN (with keyboard), and video quality is great.

If I use my 1000hz mouse, the input lag is insane for some reason. I can barely play, and it ruins the experience. I've tried playing with a shitty mouse, and it works great. The program needs an option to limit mouse polling rate.

**Comment by cgutman** [comment]
What version of GeForce Experience? What version of Windows is on the host (including build number and patch level)?

**Comment by krektonik1** [comment]
> 
> 
> What version of GeForce Experience? What version of Windows is on the host (including build number and patch level)?

GeForce Experience Version 3.20.2.34

Windows 10 Home x64, Version 10.0.18362 Build 18362

**Comment by cgutman** [comment]
We currently throttle mouse input to 200 Hz to prevent this issue. I haven't seen it myself with the 200 Hz limit in place, but it may depend on host hardware or software.

Can you upload the logs from the Nvidia Streamer? The logs can be found on the host in `C:\ProgramData\NVIDIA Corporation\NvStream`. `C:\ProgramData` is a hidden folder, so you may need to enable viewing hidden files or type the path into File Explorer manually.

**Comment by Toolzweb** [comment]
Hay buddy have you check your mouse polling rate if not then check here.

 I will suggest you "Mechanical Bazalias V10 Gaming mouse 3200 DPI" this is the best mouse for gaming i am also using it
