### ISSUE TITLE
Qt Fatal: Failed to create OpenGL context

### ISSUE THREAD

**Issue by SasukeK93** [moonlight-stream/moonlight-qt#320]
I tried to used moonlight on my old Laptop HP 530, and moonlight client have an issue when starting "Qt Fatal: Failed to create OpenGL context for format QSurfaceFormat(version 2.0..." Described in the logs. I'am using the latest moonlight portable (x64), but also tested with the installer(x64) and have same issue. The requiered files "ANGLE Open GL ES 2.0 emulation libraries" are on the moonlight directory of course.

**Steps to reproduce**
Download the latest moonlight-client and run it

**Screenshots**
![moonlight](https://user-images.githubusercontent.com/9057699/71393749-0da26200-25dc-11ea-8436-bd6603e5de8b.png)

**Client PC details (please complete the following information)**
Windows 7 x64 7601 SP1
Moonlight Version: 1.2.1

**Moonlight Logs (please attach)**
`00:00:00 - SDL Info (0): Compiled with SDL 2.0.10
00:00:00 - SDL Info (0): Running with SDL 2.0.10
00:00:00 - Qt Warning: DirectWrite: CreateFontFaceFromHDC() failed (Unknown error 0x88985000.) for QFontDef(Family="MS Shell Dlg 2", pointsize=8.25, pixelsize=11, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Roboto", lfWidth=0, lfHeight=-11) dpi=96
00:00:00 - Qt Warning: DirectWrite: CreateFontFaceFromHDC() failed (Unknown error 0x88985000.) for QFontDef(Family="MS Shell Dlg 2", pointsize=8.25, pixelsize=11, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Noto", lfWidth=0, lfHeight=-11) dpi=96
00:00:00 - Qt Warning: QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
00:00:00 - Qt Warning: QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
00:00:00 - Qt Warning: QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
00:00:00 - Qt Warning: QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "C:/Users/Fuxa/Desktop/MoonlightPortable-x64-1.2.1/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 67 new gamepad mappings
00:00:00 - SDL Info (0): V-sync enabled
00:00:00 - SDL Info (0): Windowed mode with DWM running
00:00:00 - SDL Info (0): Windowed: 1 | Present Interval: 80000000
00:00:00 - SDL Warn (0): No hardware vertex processing support!
00:00:00 - SDL Info (0): Detected GPU: Familia Mobile Intel(R) 945 Express Chipset (Microsoft Corporation - WDDM 1.0) (8086:27ae)
00:00:00 - SDL Info (0): GPU driver: igdumd64.dll 8.15.10.1749
00:00:00 - SDL Info (0): Intel driver version blacklisted for HEVC
00:00:00 - SDL Error (0): No matching decoder device GUIDs
00:00:00 - Qt Info: Found "ModeSeven.ttf" at ":/data/ModeSeven.ttf"
00:00:00 - SDL Info (0): Using SDL renderer
00:00:00 - FFmpeg: [h264 @ 0000000006432AC0] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0000000006432AC0] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0000000006432AC0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0000000006432AC0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0000000006432AC0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0000000006432AC0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0000000006432AC0] Format yuv420p chosen by get_format().
00:00:00 - FFmpeg: [h264 @ 0000000006432AC0] Reinit context to 1280x720, pix_fmt: yuv420p
00:00:00 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at "C:/Users/Fuxa/Desktop/MoonlightPortable-x64-1.2.1/gamecontrollerdb.txt"
00:00:01 - SDL Info (0): Loaded 67 new gamepad mappings
00:00:01 - Qt Warning: QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
00:00:01 - Qt Warning: QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
00:00:02 - Qt Warning: QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
00:00:02 - Qt Warning: QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
00:00:23 - Qt Fatal: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.`

**Comment by cgutman** [comment]
I think your GPU is too old. The 945 chipset doesn't support H.264 decoding anyway.
