### ISSUE TITLE
Support for Windows Store missing

### ISSUE THREAD

**Issue by ireun** [moonlight-stream/moonlight-qt#321]
Hello!

I own 'Xbox Game Pass Ultimate' via Microsoft Store, so I have access for example to Dishonored 2 game, unfortunately the launcher doesn't start the game, but Steam - where I don't own this game.

Any fix for this?

**Comment by cgutman** [comment]
Our Discord server contains instructions to add UWP apps:

UWP games need a bit extra to work with GameStream (if not going through Remote Desktop)
- Press Win + R to open run dialog.
- Type: shell:appsfolder
- You should now be seeing a folder called Applications. This folder contains all the UWP apps you have installed on your system (and some more).
- Right click on the desired UWP title icon and create a shortcut on the desktop.
- Finally add the shortcut in GeForce Experience's Shield tab.
