### ISSUE TITLE
Add more key combos and events

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#322]
can you please an option to for key combo to quit current game on host (kill process) and and automatic event to shut down host when quiting session?

**Comment by cgutman** [comment]
I can't do the shutdown host option, but I can do the quit game combo.

**Comment by apoklyps3** [comment]
How about using this?
https://itstillworks.com/send-signal-reboot-pc-through-ip-31505.html

**Comment by cgutman** [comment]
That requires being able to authenticate to the host PC using shared credentials, which may not be possible. It also wouldn't work on Mac or Linux.

**Comment by apoklyps3** [comment]
I see. so the only possible way would be an SSH server on the host and some integration with a ssh client that can log in and send commands to it.
I thought since killapp can be done, this wouldn't be a problem. But I guess quit app thing is a feature by Nvidia gamestream and that's why you can tap into it?

**Comment by cgutman** [comment]
Yes, the quit feature is from GameStream.

You could do something like adding a shortcut to shutdown.exe with the appropriate command-line options.
