### ISSUE TITLE
MacOS client - hardware decoding desaturated colors

### ISSUE THREAD

**Issue by Patbott** [moonlight-stream/moonlight-qt#323]
When using hardware decoding on the MacOS client the colors are desaturated compared to using software decoding, see screenshots below. Logs: [Moonlight-1577450602.log](https://github.com/moonlight-stream/moonlight-qt/files/4005354/Moonlight-1577450602.log).

Software decoding:
<img width="1440" alt="SoftwareDecoding" src="https://user-images.githubusercontent.com/2356279/71518193-01efbd80-28b2-11ea-8f05-400f9f1a6009.png">
<img width="1440" alt="SoftwareDecoding2" src="https://user-images.githubusercontent.com/2356279/71518910-75df9500-28b5-11ea-8664-7913d3c62f63.png">

Hardware decoding:
<img width="1440
" alt="HardwareDecoding" src="https://user-images.githubusercontent.com/2356279/71518197-05834480-28b2-11ea-831c-f5ede08e245e.png">
<img width="1440" alt="HardwareDecoding2" src="https://user-images.githubusercontent.com/2356279/71518936-855ede00-28b5-11ea-8fe7-bc4a99db21a5.png">

**Comment by cgutman** [comment]
I believe this is due to http://www.openradar.me/41565638

While doing color testing on v1.2.0, I noticed a colorspace difference between the HEVC and H.264 codecs on macOS (which is quite strange). Can you try setting the codec option to "Force H.264" and see if the colors look better to you?

For reference, what GPU is in your Mac?

**Comment by Patbott** [comment]
Forcing H.264 unfortunately still gives desaturated colors. My Mac has an iGPU; Intel Iris Plus Graphics 655.

**Comment by fmichenaud** [comment]
I'm getting the same issue with my Mac, also with an Intel Iris Plus, but I noticed the exact same behavior on fullscreen videos played on Safari for example, where there is a highly contrasted video, colors are getting washed out for no reason. You can particularly see it when you hit any control shortcut (volume/brightness...) where the issue disappears for a few seconds, then it gets brighter again.
Also tried to take screenshots but of course it doesn't show the issue...

I doubt this has something to do with Moonlight or Nvidia Gamestream itself, but more like a Mac related issue. 

Does it have something to do with the Intel Iris GPU maybe though ?

**Comment by jonseppanen** [comment]
Also experiencing this on my Mac mini, and also had the same thing when I tried on an RX 580 in an egpu, so don't think it's limited to the iris pro.

**Comment by zurce** [comment]
This issue still going on: 

Software Decoder: 
|![image](https://user-images.githubusercontent.com/3020882/142084777-4e878a78-5d93-49de-bf25-73cd32c434a8.png)|
Hardware Decoder:
|![image](https://user-images.githubusercontent.com/3020882/142084731-5c75fea9-7dd6-4b68-bf5e-8aedbd40504b.png)|

**Comment by ben-cl** [comment]
Issue remain on my side with M1 Pro
