### ISSUE TITLE
stutters ever so often

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#328]
I'm lately having this issue where I get stuttering very often. 
tried multiple 720p and/or multiple bitrates, but nothing helps.
in some days restarting the router seems to help, but I now think it's just a coincidence.

here my log:
[Moonlight-1577631359.log](https://github.com/moonlight-stream/moonlight-qt/files/4008346/Moonlight-1577631359.log)

I just want to know if it's the client pc's fault, the connection or something else entirely

**Comment by cgutman** [comment]
It definitely looks network-related to me. I see packet loss on both audio and video streams at the same time. The loss happens for a significant period of time (long enough to lose entire video frames, not just a few packets).

It could be congestion on your network from other clients or maybe interference on the channel that your WiFi network is operating on. These can be tricky to troubleshoot, but you can get more help on the Discord server.
