### ISSUE TITLE
Vertical black stripes in fullscreen

### ISSUE THREAD

**Issue by RDCH106** [moonlight-stream/moonlight-qt#329]
**Describe the bug**

Fullscreen mode shows vertical stripes. Host machine resolution and client machine uses 1920x1080 resolution.

**Steps to reproduce**
- Start host machine from client using WOL
- Start for example Steam. The problem is showed in screenshots section

**Screenshots**

![imagen](https://user-images.githubusercontent.com/1483414/72002552-e9838980-3247-11ea-8f2b-4fa50a0c80d4.png)

**Affected games**

Any

**Moonlight settings (please complete the following information)**

![imagen](https://user-images.githubusercontent.com/1483414/72003469-bc37db00-3249-11ea-9849-b459af8ee471.png)

**Client PC details**
 - OS: Windows 10 Home 1903
 - Moonlight Version: 1.2.1

**Server PC details**
 - OS: Windows 10 Home 1903
 - GeForce Experience version: 3.20.2.34
 - Nvidia GPU driver: 441.66

**Moonlight Logs**
[Moonlight-1578505381.log](https://github.com/moonlight-stream/moonlight-qt/files/4036664/Moonlight-1578505381.log)
[Moonlight-1578506574.log](https://github.com/moonlight-stream/moonlight-qt/files/4036666/Moonlight-1578506574.log)

**Additional context**
The problem disappears when I execute some games like "Warhammer 40K Space Marines". Then the vertical stripes disappear until the next reboot of the host computer.

**Comment by cgutman** [comment]
These appear on the host monitor too or just on the Moonlight client?

**Comment by RDCH106** [comment]
Both. When the session starts, the problem appears.

**Comment by RDCH106** [comment]
I have done a couple of tests.

Although the resolution I select for the screen is 1920x1080, I think it is using resolution 4096xx2160 (the maximum for the virtual display). When I select 4096x2160 the black vertical stripes disappear.

If I connect the second screen and duplicate the screen, it works correctly because the second screen is FULL HD (1920x1080) and that is the maximum resolution.

Could it have something to do with it?

**Comment by RDCH106** [comment]
Solution found: https://github.com/moonlight-stream/moonlight-qt/issues/194

Go to NVIDIA Control Panel -> Display -> Adjust desktop size and postion 

- Select the display you would like to change: 🖥️
- Select scaling mode: **Aspect ratio** 
- Select scaling on: **GPU**
- Select desired resolution
- Select desired refresh rate

![screenshot](https://user-images.githubusercontent.com/2695644/54479918-8cfa3e00-47df-11e9-9778-6fd691ba77a9.png)
