### ISSUE TITLE
Mouse Lag 1 -2 Ms

### ISSUE THREAD

**Issue by echox7** [moonlight-stream/moonlight-qt#330]
Hi I have a fast server to download and upload 1gbps, the moonlight is hooked up and the server is very fluent. But mouse as if there is a delay i can't make sense, Do you think I can make this mouse the same as the mouse on my own computer? do you think this is possible? Thanks!

**Comment by cgutman** [comment]
GameStream doesn't support client-side mouse rendering, so host-side is the only option right now.
