### ISSUE TITLE
Project Files not Found

### ISSUE THREAD

**Issue by Mok122** [moonlight-stream/moonlight-qt#331]
Hello, 

i Have a Noob Problem ? :)
when debug, is this my output

:-1: Fehler: dependent 'C:\Users\xxxx\Desktop\moonlight-qt-1.2.1\h264bitstream\h264bitstream\h264_avcc.c' does not exist.
:-1: Fehler: dependent 'C:\Users\xxxx\Desktop\moonlight-qt-1.2.1\moonlight-common-c\moonlight-common-c\enet\callbacks.c' does not exist.
:-1: Fehler: dependent 'C:\Users\xxxx\Desktop\moonlight-qt-1.2.1\qmdnsengine\qmdnsengine\src\src\abstractserver.cpp' does not exist.

All this folders was empty

Please help

**Comment by Mok122** [comment]
ok, realy!
the problem is not longer the problem :)
my new problem is

:-1: Fehler: LNK1158: "rc.exe" kann nicht ausgeführt werden.

the RC.exe not running

**Comment by cgutman** [comment]
Can you provide more details about your build environment? Visual Studio version, Qt version, etc?
