### ISSUE TITLE
Wacom support on linux client

### ISSUE THREAD

**Issue by simonouel** [moonlight-stream/moonlight-qt#332]
I wish to have support for wacom tablet and pen pressure.
Currently when I try to use a wacom, the cursor goes automatically in the bottom right corner. Whatever what I am trying to do. It will usefull for using any windows or mac software where wacom tablet is required like photoshop or zbrsuh.

**Comment by cgutman** [comment]
Unfortunately, we're not currently able to implement this due to limitations of the GameStream protocol itself. If Nvidia adds support for tablet input, we can reopen this.
