### ISSUE TITLE
Transcode patch and streaming

### ISSUE THREAD

**Issue by reloxx13** [moonlight-stream/moonlight-qt#333]
**Describe the bug**
If the [nvidia-patch](https://github.com/keylase/nvidia-patch) is applied to allow unlimitted transcodes, no streaming session can start due to a dll loading error logged in the log of the host system.

Moonlight Error 521
![grafik](https://user-images.githubusercontent.com/14855001/73008349-a9f39a80-3e0e-11ea-861e-a6108e1b9fd9.png)

```
Failed to load library C:\Windows\system32\nvEncodeAPI64.dll due to error 2148081673
```
```
#5(D)[2020-01-23 17:15:59,681]=18:15:59={0000215C}<VideoEncoder>     Creating NvEnc9VideoEncoder.
#6(I)[2020-01-23 17:15:59,681]=18:15:59={0000215C}<VideoEncoder>     Initializing NvEnc9VideoEncoder.
#7(I)[2020-01-23 17:15:59,681]=18:15:59={0000215C}<NvEnc9VideoEncod> Using NvEnc header version 9.0.
#8(E)[2020-01-23 17:15:59,681]=18:15:59={0000215C}<GsLoadLibrary>    Failed to load library C:\Windows\system32\nvEncodeAPI64.dll due to error 2148081673
#9(E)[2020-01-23 17:15:59,681]=18:15:59={0000215C}<NvEnc9VideoEncod> Failed to load NvEnc DLL from '\nvEncodeAPI64.dll'.
#0(E)[2020-01-23 17:15:59,681]=18:15:59={0000215C}<NvEncUtil>        Failed to initialize encoder for RTSP SPS/PPS header generation.
```

**Steps to reproduce**
Apply the patch
Start a stream

**Client PC details (please complete the following information)**
 - OS: Win10x64 18362.19h1
 - Moonlight Version: Moonlight PC v1.2.1

**Server PC details (please complete the following information)**
 - OS: Win10x64 18362.19h1
 - GeForce Experience version: 3.20.2.34
 - Nvidia GPU driver: 441.87

**Moonlight Logs (please attach)**
[Moonlight-LOG.zip](https://github.com/moonlight-stream/moonlight-qt/files/4104514/Moonlight-LOG.zip)

**Additional context**
[nvstreamsvcCurrent-LOG.zip](https://github.com/moonlight-stream/moonlight-qt/files/4104519/nvstreamsvcCurrent-LOG.zip)

patch-issue tracking:
https://github.com/keylase/nvidia-patch/issues/215

I dont think you can do anything, but i wanted this to be a result if someone else searches for this in your repo and i suggest to add a hint to this in the troubleshooting guide.

**Comment by cgutman** [comment]
Looks like this one got resolved, but thanks for letting me know.
