### ISSUE TITLE
Problems with Epic Games Store

### ISSUE THREAD

**Issue by Remisonl** [moonlight-stream/moonlight-qt#334]
Hello. I apologize in advance for my English - I am from Russia.

I really hope for your help. There were a couple of problems with Moonlight.

There is a purchased Detroit: Become Human game through the Epic Games Store. When I try to stream to the tablet, a black screen pops up, although sound is present. This happens both in "full screen mode" and in the "window without frames" mode. In the usual "window mode" everything is fine, but, you know, playing with frames, taskbars and not in full screen is not very convenient. As I understand it, the problem is that Geforce Shield / Moonlight does not understand which process to display the image from and only the desktop displays. In Nvidia I tried to manually add different files for this game: an exe file from a folder, a game shortcut from the desktop - the result is unchanged.

A similar problem is observed with Red Dead Redemption 2

99% sure that the piece of crap called the Epic Games Store is to blame. There are absolutely no problems with other games not from clients.

Please help me.

**Comment by cgutman** [comment]
I believe this is due to these games using the Vulkan API. It looks like you can choose DirectX 12 in Red Dead Redemption 2, so you could try that and see if it resolves the issue.

I don't know of a workaround for Detroit: Become Human besides playing in windowed mode.

**Comment by Remisonl** [comment]
Many thanks.

The problems really were related to Vulkan. I changed this parameter in the settings of Red Dead Redemption 2 to DirectX and it worked fine.

Unfortunately, I can’t do it in Detroit either - the game uses only the Vulkan API, which Moonlight seems to have problems with.

Maybe there is any solution to this problem? Or is it left to wait for developers to complete Vulkan support (if it is planned at all)?
