### ISSUE TITLE
Moonlight crashes on Steam Link build 748

### ISSUE THREAD

**Issue by Jorys-Paulin** [moonlight-stream/moonlight-qt#338]
**Describe the bug**
With a Steam Link hardware running build 748 (beta branch), Moonlight 1.2.0 (1.2.1 being a hot fix for PCs only) crashes as soon as it it launched.

**Steps to reproduce**
With a Steam Link hardware running build 748, install Moonlight 1.2.0 for Steam Link and launch it from the main menu.

**Client device details**
 - OS: Steam Link OS (Busybox)
 - Moonlight Version: 1.2.0

**Moonlight Logs (please attach)**
The log file is present in `/tpm/moonlight.log`, but is completely empty.

**Additional context**
When trying to launch via SSH, this error pops-up:
```sh
# ./moonlight
./moonlight: error while loading shared libraries: libQt5QuickControls2.so.5: cannot open shared object file: No such file or directory
```
Maybe it's because I'm launching trough SSH, but I'm not sure.

**Comment by cgutman** [comment]
Thanks for the report. I let slouken know that we're missing libraries - https://steamcommunity.com/app/353380/discussions/1/1743392068392734687/

Hopefully he can get these into the next build.

**Comment by cgutman** [comment]
Fixed in build 749

**Comment by Jorys-Paulin** [comment]
Can confirm that it work now. Thanks!
