### ISSUE TITLE
Chosen best display mode: 1280x720x60 on Steam Link

### ISSUE THREAD

**Issue by igno2k** [moonlight-stream/moonlight-qt#339]
**Describe the bug**
When starting Moonlight on Steam Link I get the following messages in /tmp/moonlight.log:
...
00:01:29 - SDL Info (0): Video stream is 1920x1080x60 (format 0x1)
...
00:01:31 - SDL Info (0): Chosen best display mode: 1280x720x60
...
Does this mean Moonlight is running at 720p? I would think the best display mode is 1920x1080x60 in this case.

**Steps to reproduce**
Start the current Moonlight version on a Steam Link Build 747 (public) with a standard 1080p TV.

**Moonlight settings (please complete the following information)**
Tested with 1080p/60fps/40Mbit - vsync on

**Client PC details (please complete the following information)**
 - OS: Steam Link Build 747
 - Moonlight Version: v1.2.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro 1909
 - GeForce Experience version: 3.20.2.34
 - Nvidia GPU driver: 442.19

**Comment by cgutman** [comment]
This display mode reported by SDL is not accurate. It is operating at 1080p.
