### ISSUE TITLE
Client closes/exits game window at random

### ISSUE THREAD

**Issue by Plebbimon** [moonlight-stream/moonlight-qt#34]
I have an issue where I will play any game for a short amount of time, and between 5-10 minutes into my session the client closes it's game window by itself, leaving the game still running on the host computer.

I am able to continue my session by clicking on the game I was playing and launching the streaming process again, as the moonlight application is still left running when the window closes. The problem does not appear to interfere with the host. 

I am using an intel HD graphics 520 integrated GPU as the client-side decoder, as my dedicated NVIDIA 940mx does not support DXVA2. I've updated drivers on both the host and client machine. I am running recommended options in the moonlight settings.

Will provide more info/details if this is worth looking into.

**Comment by cgutman** [comment]
The main reason that Moonlight will usually exit a stream on its own is if the connection to your PC was lost. The Moonlight logs should tell the exact reason.

Moonlight's logs are in the %TEMP% folder called "Moonlight" followed by some numbers?  Can you get the latest log after you experience the issue?
