### ISSUE TITLE
Moonlight 1.2.0 crash on steamlink beta fw 750

### ISSUE THREAD

**Issue by Toni3402** [moonlight-stream/moonlight-qt#340]
**Describe the bug**
With a Steam Link hardware running build 750 beta, Moonlight 1.2.0 crashes as soon as it it launched.

**Steps to reproduce**
With a Steam Link hardware running build 750, install Moonlight 1.2.0 for Steam Link and launch it from the main menu.

**Client PC details (please complete the following information)**
- OS: Steam Link OS (Busybox)
- Moonlight Version: 1.2.0

**Moonlight Logs (please attach)**
Can't provide now

**Additional context**
perhaps this is due to the current update of QT libraries in Steamlink OS

**Comment by Jorys-Paulin** [comment]
Can confirm that it also happens to me as well.

Running Moonlight from SSH, this error shows up:
```
# ./moonlight.sh
./bin/moonlight: relocation error: ./bin/moonlight: symbol _ZnwjRKSt9nothrow_t, version Qt_5 not defined in file libQt5Core.so.5 with link time reference
```
Seems like another problem with QT, like it was over in issue #338

**Comment by Toni3402** [comment]
Log is empty.
On terminal # ./moonlight.sh
./bin/moonlight: relocation error: ./bin/moonlight: symbol _ZnwjRKSt9nothrow_t, version Qt_5 not defined in file libQt5Core.so.5 with link time reference

**Comment by cgutman** [comment]
Released a fixed build of 1.2.1 that is compatible with both new and old Steam Link firmware versions.

**Comment by Jorys-Paulin** [comment]
I can confirm that it works now, thanks!

**Comment by Toni3402** [comment]
Thank you! Works great!
