### ISSUE TITLE
lfe-remixing not working with moonlight on linux

### ISSUE THREAD

**Issue by djbiti1** [moonlight-stream/moonlight-qt#342]
Moonlight appears to bypass the lfe-remixing in pulseaudio. It is not sending the lower frequencies to the subwoofer as it is supposed to.

I have a 5.1 system connected through 3 jacks to a xonar u5.
Sound from other sources like Firefox or discord correctly sends the bass to the subwoofer, but moonlight doesn't.

Moonlight does send the subwoofer channel as I could test on the host sound configuration.

Other Moonlight clients
If I boot into windows and use the windows version and enable bass management it does work properly.

Moonlight settings:
Audio configuration: 5.1 surround sound
Play audio on host PC: not enabled 
Same settings as the windows client.

Client PC details:

OS: Pop OS 19.10
Moonlight version: 1.2.1

Server PC details:

OS: Windows 10 x64
GFE version 3.20.2.34
Drivers: 441.87

Logs:
[logs.txt](https://github.com/moonlight-stream/moonlight-qt/files/4199534/logs.txt)

**Comment by cgutman** [comment]
Hmm, I'm not sure how we could be doing this. We definitely aren't setting anything like this on purpose.

Can you see if this still happens with the Moonlight Flatpak? It has a newer version of SDL which might have a bugfix for this.

If so, try running `flatpak run --env=ML_AUDIO=libsoundio com.moonlight_stream.Moonlight` and see if the issue still happens with that? That's a totally separate audio backend which shares no code with the SDL one.
