### ISSUE TITLE
Moonlight keeps closing whenever i start it in windows 10

### ISSUE THREAD

**Issue by rem2112** [moonlight-stream/moonlight-qt#344]
**Describe the bug**
moonlight keeps closing whenever i start it and sometimes it doesn't start at all(mostly closes in an instant)

**Moonlight settings (please complete the following information)**
 - All settings are default

**Client PC details (please complete the following information)**
 - OS: Windows 10 1809
 - Moonlight Version: MoonlightPortable-x64-1.2.1

**Additional context**
- Have tried reinstalling and the portable version of moonlight(both latest)
- Tried clean installing graphic drivers
- Someone helped me found out That there is no crash in log's(attached)
- .dmp file generated from moonlight-procdump Link: https://drive.google.com/open?id=1DYdOsKGJVtIwiRn9k4xq3Bi8EDag4PMt

[Moonlight-1582106867.log](https://github.com/moonlight-stream/moonlight-qt/files/4224376/Moonlight-1582106867.log)
[Moonlight-1582106868.log](https://github.com/moonlight-stream/moonlight-qt/files/4224377/Moonlight-1582106868.log)
[Moonlight-1582106882.log](https://github.com/moonlight-stream/moonlight-qt/files/4224378/Moonlight-1582106882.log)
[Moonlight-1582106866.log](https://github.com/moonlight-stream/moonlight-qt/files/4224379/Moonlight-1582106866.log)

**Comment by cgutman** [comment]
Can you try a recent build? https://ci.appveyor.com/project/cgutman/moonlight-qt/build/job/89dcm0pv61qli9t9/artifacts

Uninstall the old one first.
