### ISSUE TITLE
Option to Blank Host screen

### ISSUE THREAD

**Issue by nk33** [moonlight-stream/moonlight-qt#345]
Would it be possible to add an option for blanking the host screen - so that anyone who happens to be in the room at the time you are gaming cant see what your playing or doing?

I think this would be really usefull for many who have shared living space...

There are similar options in various remote desktop software

thanks in advance

**Comment by nk33** [comment]
well...if you read it you will see that it is clearly a feature request.....

did you read it mate?

**Comment by nk33** [comment]
sorry - just realised it was an auto-comment - my bad

**Comment by nk33** [comment]
so nobody thinks this would be useful??

**Comment by Jorys-Paulin** [comment]
I know AMD Link has such feature, but not GeForce Experience. You can turn the screen off, or even use a headless HDMI dongle instead of a physical screen.

**Comment by cgutman** [comment]
@Jorys-Paulin is correct. This is not something we can implement without support in GeForce Experience.

**Comment by 9cento** [comment]
> @jorys-paulin is correct. This is not something we can implement without support in GeForce Experience.

It could be feasible trough a driver hack, that's what programs like TeamViewer or AnyDesk do to accomplish that task afaik
