### ISSUE TITLE
Some box art are not showing up in the Windows client

### ISSUE THREAD

**Issue by michellabbe** [moonlight-stream/moonlight-qt#346]
**Describe the bug**
Some Box art I made myself don't show up in the Windows client.
Switch box art to another one and revert (back and forth) makes the game appear/disappear (blank game) on the Windows client.

**Steps to reproduce**
Add/edit a custom game in GeForce Experience (under the SHIELD tab) and use box art for any title with the provided example1 or example2 below.

**Screenshots**
Windows client:
![Moonlight_Win10](https://user-images.githubusercontent.com/16291382/74995867-0c48b680-5420-11ea-9a2f-e9cc2c5021d3.png)

Linux (Raspbian) client:
![Moonlight_Raspbian](https://user-images.githubusercontent.com/16291382/74995872-0f43a700-5420-11ea-9df0-ce4518579b32.png)

**Affected games**
Any

**Other Moonlight clients**
- The same box art show fine on linux (Ubuntu on x86 or Raspbian) clients.

**Moonlight settings**
- Have any settings been adjusted from defaults? No

**Client PC details**
 - OS: Windows 10 1909
 - Moonlight Version: 1.2.1

**Server PC details**
 - OS: Windows 10 1909
 - GeForce Experience version: 3.20.2.34
 - Nvidia GPU driver: 441.87

**Additional context**
Reproduced on multiple hosts and multiple clients.
Converting PNG file to JPG instead doesn't fix the issue.

example1 (shows on linux but not windows client):
![FS-UAE Arcade](https://user-images.githubusercontent.com/16291382/74995931-38643780-5420-11ea-9420-2491f5619da1.png)

example2 (shows on linux but not windows client):
![Kodi-dark](https://user-images.githubusercontent.com/16291382/74995984-5e89d780-5420-11ea-8b35-e02565f0951f.png)

small variant of example2 that shows fine on both linux and windows clients:
![Kodi-dark2](https://user-images.githubusercontent.com/16291382/74996004-69446c80-5420-11ea-85a5-625ec3ff8682.png)

**Comment by cgutman** [comment]
The PNG decoding bug is https://bugreports.qt.io/browse/QTBUG-81604 which is already fixed upstream and will be released in Qt 5.14.2.

The bug that caused Moonlight to not display the placeholder box art is fixed by https://github.com/moonlight-stream/moonlight-qt/commit/9f77f3d968b2e517158f0e27b1b51e3652f419c0
