### ISSUE TITLE
Mac Client Keychain request

### ISSUE THREAD

**Issue by wackjee** [moonlight-stream/moonlight-qt#35]
Randomly, the moonlight client will exit my stream to ask me for an unknown keychain password. The only way to get around this is to force quit the application.

**Comment by cgutman** [comment]
Can you confirm you're running v0.2.0? Changes were made there to address keychain password prompts. If you are running v0.2.0, can you try downgrading to v0.1.0 to see if they go away?

**Comment by wackjee** [comment]
I had the v0.1.0, I didn't realize there was a new version, my bad. Seems to be working fine now, thanks!

**Comment by cgutman** [comment]
Thanks for following up and confirming the fix worked for you.
