### ISSUE TITLE
Support for ARM based CPU windows

### ISSUE THREAD

**Issue by DanXHK** [moonlight-stream/moonlight-qt#350]
Surface pro X has launched and it’s a ARM based tablet.

Though it can run 32bit softwares, but the performance is bad. Would Moonlight create a ARM based Windows version for this tablet? Thanks.

**Comment by howwarrd** [comment]
I agree with DanXHK, I have a Samsung Galaxy Book S which is running Windows 10 on an ARM chip. If it were possible to have a Windows on ARM version that would be fantastic.

**Comment by cgutman** [comment]
So you've tried the 32-bit version and it doesn't run well? Can you post the Moonlight log so I can look?

**Comment by DanXHK** [comment]
> So you've tried the 32-bit version and it doesn't run well? Can you post the Moonlight log so I can look?

Oh it actually runs well, but it runs in emulator so the battery drained so fast.

**Comment by Jonathanlodorcleary** [comment]
Can confirm. It works really well but the battery life takes a huge hit. An Arm64 for Windows build would go a long, long way!

**Comment by lunim** [comment]
Would love to see ARM64 support!

**Comment by belliAndrea** [comment]
Yeah me too

**Comment by cgutman** [comment]
Here is an early preview of a native ARM64 version of Moonlight. Let me know how it runs for you, and let me know if you encounter any bugs other than those in the "Known Issues" section below.

[MoonlightPortable-arm64-a6551c3.zip](https://github.com/moonlight-stream/moonlight-qt/files/5683863/MoonlightPortable-arm64-a6551c3.zip)

Known issues:
- On-screen performance overlay doesn't work when hardware decoding

**Comment by Wii60** [comment]
> Here is an early preview of a native ARM64 version of Moonlight. Let me know how it runs for you, and let me know if you encounter any bugs other than those in the "Known Issues" section below.
> 
> [MoonlightPortable-arm64-a6551c3.zip](https://github.com/moonlight-stream/moonlight-qt/files/5683863/MoonlightPortable-arm64-a6551c3.zip)
> 
> Known issues:
> 
> * On-screen performance overlay doesn't work when hardware decoding

https://www.youtube.com/watch?v=0iAzMRKFX3c

This is amazing! Initial test running great. About to do a long session in Cyberpunk to stress test. What an awesome surprise!

**Comment by Wii60** [comment]
> Here is an early preview of a native ARM64 version of Moonlight. Let me know how it runs for you, and let me know if you encounter any bugs other than those in the "Known Issues" section below.
> 
> [MoonlightPortable-arm64-a6551c3.zip](https://github.com/moonlight-stream/moonlight-qt/files/5683863/MoonlightPortable-arm64-a6551c3.zip)
> 
> Known issues:
> 
> * On-screen performance overlay doesn't work when hardware decodi

> Here is an early preview of a native ARM64 version of Moonlight. Let me know how it runs for you, and let me know if you encounter any bugs other than those in the "Known Issues" section below.
> 
> [MoonlightPortable-arm64-a6551c3.zip](https://github.com/moonlight-stream/moonlight-qt/files/5683863/MoonlightPortable-arm64-a6551c3.zip)
> 
> Known issues:
> 
> * On-screen performance overlay doesn't work when hardware dec

> Here is an early preview of a native ARM64 version of Moonlight. Let me know how it runs for you, and let me know if you encounter any bugs other than those in the "Known Issues" section below.
> 
> [MoonlightPortable-arm64-a6551c3.zip](https://github.com/moonlight-stream/moonlight-qt/files/5683863/MoonlightPortable-arm64-a6551c3.zip)
> 
> Known issues:
> 
> * On-screen performance overlay doesn't work when hardware decoding

It definitely performs much better. Emulated 32 bit worked well, but this is way better. I had grown accustomed to a slight lag on my Surface Pro X, but figured it was part of streaming since my iPad does the same. That lag is gone with the native port so far. 15 minutes in and I'm thrilled.

**Comment by cgutman** [comment]
Here is a near-final ARM64 build.

Fixes:
- Performance statistics overlay works now
- Video upscaling quality is improved

[MoonlightPortable-arm64-c3f9742b.zip](https://github.com/moonlight-stream/moonlight-qt/files/5727616/MoonlightPortable-arm64-c3f9742b.zip)

**Comment by encryptededdy** [comment]
Working perfectly on my Galaxy Book S (Snapdragon 8cx)!

**Comment by Wii60** [comment]
> Here is a near-final ARM64 build.
> 
> Fixes:
> 
> * Performance statistics overlay works now
> * Video upscaling quality is improved
> 
> [MoonlightPortable-arm64-c3f9742b.zip](https://github.com/moonlight-stream/moonlight-qt/files/5727616/MoonlightPortable-arm64-c3f9742b.zip)

Just wanna say I’ve been using this regularly and it’s awesome.

**Comment by DanXHK** [comment]
> Here is a near-final ARM64 build.
> 
> Fixes:
> 
> * Performance statistics overlay works now
> * Video upscaling quality is improved
> 
> [MoonlightPortable-arm64-c3f9742b.zip](https://github.com/moonlight-stream/moonlight-qt/files/5727616/MoonlightPortable-arm64-c3f9742b.zip)

I got an issue on this build. The top left corner of the screen is split. Image is attached.
![bug](https://user-images.githubusercontent.com/61811892/103180842-9f6e3a80-48d4-11eb-82e8-383e8b3e4855.png)

**Comment by DanXHK** [comment]
> > Here is a near-final ARM64 build.
> > Fixes:
> > 
> > * Performance statistics overlay works now
> > * Video upscaling quality is improved
> > 
> > [MoonlightPortable-arm64-c3f9742b.zip](https://github.com/moonlight-stream/moonlight-qt/files/5727616/MoonlightPortable-arm64-c3f9742b.zip)
> 
> I got an issue on this build. The top left corner of the screen is split. Image is attached.
> ![bug](https://user-images.githubusercontent.com/61811892/103180842-9f6e3a80-48d4-11eb-82e8-383e8b3e4855.png)

FYI, 
1) the previous build (MoonlightPortable-arm64-a6551c3.zip) works fine without this issue.
2) surface pro x native resolution is 2880x1920, which is not a typical 16:9 screen

**Comment by cgutman** [comment]
@DanXHK hmm, that's very odd. I'm not seeing that behavior on my Surface Pro X running the Windows 10 Insider Preview build 21277. What version of Windows 10 are you running on yours?

Do you have to do anything specific to trigger it?

Can you screenshot the Moonlight settings page, so I can tell exactly how you've got it configured?

**Comment by DanXHK** [comment]
window 10 pro build 1909
setting:
![setting_bug](https://user-images.githubusercontent.com/61811892/103181358-31794180-48db-11eb-8fa6-d9fb5dc1b291.png)

**Comment by cgutman** [comment]
@DanXHK Hmm, I tried those exact same settings and it works properly for me. Is there anything you can think of that might be required to trigger this issue? A setting in Windows, or something else?

@Wii60 you're not seeing that bug either, right? What version of Windows 10 are you running on your Pro X?

**Comment by DanXHK** [comment]
> @DanXHK Hmm, I tried those exact same settings and it works properly for me. Is there anything you can think of that might be required to trigger this issue? A setting in Windows, or something else?
> 
> @Wii60 you're not seeing that bug either, right? What version of Windows 10 are you running on your Pro X?

Ummm I tried few things but it is really odd.
1) I tried changing the resolution to native(2880x1920) full screen/bordered windows and the issue solved . ( but the screen stretch as the source is 16:9). If I change the resolution to native(2880x1920) windows mode, the issue exists.
2) I changed to use the preview build and it works fine again.

**Comment by DanXHK** [comment]
> > @DanXHK Hmm, I tried those exact same settings and it works properly for me. Is there anything you can think of that might be required to trigger this issue? A setting in Windows, or something else?
> > @Wii60 you're not seeing that bug either, right? What version of Windows 10 are you running on your Pro X?
> 
> Ummm I tried few things but it is really odd.
> 
> 1. I tried changing the resolution to native(2880x1920) full screen/bordered windows and the issue solved . ( but the screen stretch as the source is 16:9). If I change the resolution to native(2880x1920) windows mode, the issue exists.
> 2. I changed to use the preview build and it works fine again.

FYI,
below setting is native + windowed mode.
I can give you the IP to try connecting

![windowsmode_bug](https://user-images.githubusercontent.com/61811892/103192552-0d862200-4914-11eb-81a1-79f02372dfe2.png)

**Comment by cgutman** [comment]
@DanXHK ok, thanks for the additional info.

Can you try these steps?

1. Close Moonlight
2. Opening a Command Prompt or Powershell window in the directory where Moonlight.exe is located (the version with the bug)
3. Run these commands to start Moonlight:
```
set DXVA2_DISABLE_VIDPROC_BLACKLIST=1
Moonlight.exe
```
4. Check if the bug still happens in that Moonlight window

**Comment by DanXHK** [comment]
> @DanXHK ok, thanks for the additional info.
> 
> Can you try these steps?
> 
> 1. Close Moonlight
> 2. Opening a Command Prompt window in the directory where Moonlight.exe is located (the version with the bug)
> 3. Run these commands to start Moonlight:
> 
> ```
> set DXVA2_DISABLE_VIDPROC_BLACKLIST=1
> Moonlight.exe
> ```
> 
> 1. Check if the bug still happens in that Moonlight window

Problem solved after following the steps

**Comment by DanXHK** [comment]
> Moonlight.exe

but the images quality is not that good

> > @DanXHK ok, thanks for the additional info.
> > Can you try these steps?
> > 
> > 1. Close Moonlight
> > 2. Opening a Command Prompt window in the directory where Moonlight.exe is located (the version with the bug)
> > 3. Run these commands to start Moonlight:
> > 
> > ```
> > set DXVA2_DISABLE_VIDPROC_BLACKLIST=1
> > Moonlight.exe
> > ```
> > 
> > 
> > 
> > 1. Check if the bug still happens in that Moonlight window
> 
> Problem solved after following the steps

But the image quality is not that good

**Comment by cgutman** [comment]
I confirmed that the issue impacts Win10 1903 and 1909, but it is fixed in Win10 2004 and 20H2. I wasn't able to find a workaround, so I'll just mention in the release notes that you need to upgrade to Win10 2004/20H2 to use Moonlight on the Surface Pro X.

**Comment by javvydawg** [comment]
First off Happy New Year to everyone and thanks for bringing this amazing app to all our devices, including some that others may have forgotten (Looking at PS Vita lols) 

Second I am also on a Surface Pro X (SQ2 version) but my issue is that if i have a game controller plugged into my Surface then moonlight just freezes, stating (Not Responding). I have a feeling its because I am using a  PS5 Dual Sense Controller but just wanted to post this. 

Any idea what could be causing this? I have not installed anything besides Moonlight and Tidal (Music Streaming Service) on my machine and have tried both Wired and Wireless. App just freezes =/ 

Thanks Again!!

**Comment by cgutman** [comment]
@javvydawg Which build are you using? One of the builds from this thread, or the official v2.2.0 release?

I can take a look at the hang if you get a dump file. When Moonlight freezes, open Task Manager, right click Moonlight.exe in the Processes Tab, and choose Create Dump File. You can zip that dump file and post a link to it here.

**Comment by javvydawg** [comment]
@cgutman - Thanks for the quick response! && I am on the following build that was posted in this thread "MoonlightPortable-arm64-c3f9742b.zip". 

I went ahead and took a dump of Moonlight while controller is plugged in directly into Surface (figured direct would be best). Please see attached dump. Thanks again!

<a href=http://www.filedropper.com/moonlight><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file storage online</a></div>

**Comment by cgutman** [comment]
@javvydawg It is definitely a hang in the new PS5 code in SDL 2.0.14.

Does it always freeze immediately after you plug in the gamepad? Does it freeze if you connect the gamepad while already streaming?

**Comment by javvydawg** [comment]
@cgutman - Yup always freezes when gamepad is connected. I tried launching moonlight first then plugging in the controller but still freezes the moment the controller, I guess, initiates?

If I plug it in once streaming It also freezes and gives an error that Connection is too slow or something and then if I unplug the controller I get a Connection Terminated error.

**Comment by cgutman** [comment]
@javvydawg I've got a fix that works for me. Try replacing the SDL2.dll file inside that ARM64 build with this one [SDL2.zip](https://github.com/moonlight-stream/moonlight-qt/files/5759603/SDL2.zip)

**Comment by javvydawg** [comment]
@cgutman - you're the man!!! That did it! Working great now! Thanks sooo muchh!!!!

**Comment by DanXHK** [comment]
> I confirmed that the issue impacts Win10 1903 and 1909, but it is fixed in Win10 2004 and 20H2. I wasn't able to find a workaround, so I'll just mention in the release notes that you need to upgrade to Win10 2004/20H2 to use Moonlight on the Surface Pro X.

I have updated to build 20H2, and problem solved. Image quality is better. Thank for your effort and great work!!!!!

**Comment by cgutman** [comment]
Released official ARM64 binaries in v3.0.0

**Comment by ephr385-svg** [comment]
> Adoraria ver suporte para ARM64!

https://github.com/moonlight-stream/moonlight-qt/issues/350#issuecomment-667556460

**Comment by ephr385-svg** [comment]
- rudsonalmeida862@gmail.com
