### ISSUE TITLE
Touchpad freezing issue on Linux client

### ISSUE THREAD

**Issue by tiff4** [moonlight-stream/moonlight-qt#353]
**Describe the bug**
Cannot use the touchpad as the cursor freezes inside Moonlight after switching applications.

**Steps to reproduce**
1. Connect to the server.
2. Click anything on the server.
3. Switch application (i.e. via Alt+Tab).
4. The cursor and Moonlight freeze. Ctrl+Alt+Shift+Q won't work so you have to force kill the  process.

**Client PC details (please complete the following information)**
 - OS: Manjaro Linux 19.0.2 Kyria (Kernel 5.4-LTS)
 - Moonlight Version: 1.2.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 Build 18363
 - GeForce Experience version: 3.20.2.34
 - Nvidia GPU driver: 442.74

**Moonlight Logs (please attach)**
[Moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/4364590/Moonlight.log)

**Additional context**
I am using Dell Latitude 7490. Everytime I open up the Moonlight client, the program throws a warning message that says "Moonlight detected gamepads without a mapping: DELL081C:00 044E:121F Touchpad. Click the Help button for information on how to map your gamepads." Don't know if it's related to this issue.

**Comment by cgutman** [comment]
Can you provide more information about your setup? Are you using X or Wayland? What version of Mesa is installed?

I'm not able to reproduce on Fedora 32 running Wayland or X with Mesa 20.0.1 on my XPS 13 9370.
