### ISSUE TITLE
MacOS: dmg corrupt image

### ISSUE THREAD

**Issue by damarq001** [moonlight-stream/moonlight-qt#356]
Running OSX 10.10.5

When attempting to mount the dmg, I get the following error message:

<img width="371" alt="Screen Shot 2020-03-29 at 2 10 41 PM" src="https://user-images.githubusercontent.com/62852783/77858160-4fd4d400-71c7-11ea-83cf-28003baa1bdc.png">

Same error appears for previous releases.

**Comment by cgutman** [comment]
Moonlight requires macOS 10.13 High Sierra or later.
