### ISSUE TITLE
Moonlight on client pc just blank before even connecting to the main gaming pc.

### ISSUE THREAD

**Issue by ArtificialGeek** [moonlight-stream/moonlight-qt#359]
Hi, 

I seem to be having a problem with Moonlight on a Windows client PC. Once I install Moonlight, when I go to open it up either with admin rights or not, I seem to get a blank black screen. At this point Im not even paired or trying to connect to the main streaming machine. 

I can select the gaming machine by clicking on the location it would normally be and the pairing box appears on the main gaming machine. But because I cant actually see anything on the client pc, I dont know the pairing code to even connect the two machines together. 

I was just wondering if anyone else has had this problem and how I can resolve it?

Cheers

**Comment by cgutman** [comment]
Please try with v2.0.0 and see if the issue still occurs.
