### ISSUE TITLE
Strange stuttering with Intel HD Graphics 520

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#36]
The qt version is great, very responsive to controls and great quality, but I experience some strange stuttering from time to time.
The laptop it is running on has a dual graphic card setup and I guess only the iGPU does hardware video deconding because I have not seen the descrete GPU getting any of these tasks in other apps (youtube in chrome etc)
Here is the log. Hope it helps
[Moonlight-1534114108.log](https://github.com/moonlight-stream/moonlight-qt/files/2281423/Moonlight-1534114108.log)

**Comment by apoklyps3** [comment]
@cgutman seems it's not only with Intel HD 520
tested with an older laptop that has an nvidia card (420M) and it even it seems a little better there are still stutters from time to time. they seem pretty random. Log seems alot cleaner... not so many errors like on the Intel GPU laptop
[Moonlight-1534397994.log](https://github.com/moonlight-stream/moonlight-qt/files/2292554/Moonlight-1534397994.log)

**Comment by cgutman** [comment]
Can you try the build I linked in this comment on your 2 machines and see if it's stuttering less? https://github.com/moonlight-stream/moonlight-qt/issues/37#issuecomment-413470851

**Comment by apoklyps3** [comment]
I only can on the second machine as they are both in different locations.
It actually makes it worse. the stuttering is there 90% of the time and it comes with other issues like input lag and stream drop (image freezes with audio glitches)

**Comment by cgutman** [comment]
Can you attach the log?

**Comment by apoklyps3** [comment]
[Moonlight-1534423201.log](https://github.com/moonlight-stream/moonlight-qt/files/2294631/Moonlight-1534423201.log)

**Comment by cgutman** [comment]
It looks like the network is dropping way more packets in the last log than when you ran the first test on this machine. I don't think that's related to the changes in this build (since it's impacting audio which was not changed at all).

Can you try to alternate between the updated version and v0.2.0 in the same network environment to compare apples to apples?

Here, you're losing hundreds of packets on the network:
```00:00:56 - SDL Info (0): Returning RTP packet queued for too long
00:00:56 - SDL Info (0): Received OOS audio data (expected 44359, but got 44585)
00:00:56 - SDL Info (0): Waiting for IDR frame
00:00:56 - SDL Info (0): Waiting for IDR frame
00:00:56 - SDL Info (0): IDR frame request sent
00:00:56 - SDL Info (0): Waiting for IDR frame
00:00:56 - SDL Info (0): Waiting for IDR frame
00:02:05 - SDL Info (0): Returning RTP packet queued for too long
00:02:05 - SDL Info (0): Received OOS audio data (expected 58410, but got 58411)
00:02:44 - SDL Info (0): Network dropped an entire frame
00:02:44 - SDL Info (0): Waiting for IDR frame
00:02:44 - SDL Info (0): Waiting for IDR frame
00:02:44 - SDL Info (0): Waiting for IDR frame
00:02:44 - SDL Info (0): Returning RTP packet queued for too long
00:02:44 - SDL Info (0): Received OOS audio data (expected 623, but got 773)

**Comment by apoklyps3** [comment]
tested on the second laptop(the one with nvidia GPU) and the stuttering is there no matter what build I used...
I'm going to have a chance to test the first laptop again today to see where we stand...

**Comment by cgutman** [comment]
Ok, I've been working on more extensive changes to the Windows renderer over the last several days. I'll let you know when I have a new build to try.

**Comment by cgutman** [comment]
Please try v0.3.0 and see if that improves performance for you.

**Comment by apoklyps3** [comment]
clearly better.
there's a hitch here and there, but nowhere near as it waa before this version. I could live with it.

**Comment by cgutman** [comment]
Thanks for confirming. The other hitches are probably actual packet loss (seen in your last log). That will be better addressed with reference picture invalidation in a future build. Closing this ticket.
