### ISSUE TITLE
amd link by re-live

### ISSUE THREAD

**Issue by manotroll** [moonlight-stream/moonlight-qt#361]
amd has documented a way to use your program for vr streaming through the ReLive for VR app
https://www.amd.com/en/support/kb/faq/dh-030
couldn't you just take her protocol and add it to the program?

**Comment by oreyg** [comment]
"**just** take her protocol and add it" kek

**Comment by manotroll** [comment]
but it is not compatible with all phones like the google solution

**Comment by cgutman** [comment]
This is out of scope for Moonlight. There's is a work-in-progress server for Moonlight that can run on non-Nvidia hardware though: https://github.com/loki-47-6F-64/sunshine
