### ISSUE TITLE
updated GeForce experience, now it forces big picture mode when running stream

### ISSUE THREAD

**Issue by weisskrutz** [moonlight-stream/moonlight-qt#368]
Just updated my GeForce experience today.  When I went to moonlight on my stram link and hit stream,  it runs steam on big picture mode and will not allow me to exit out of it. Only option is to stop streaming . Not sure how to fix this .

**Comment by cgutman** [comment]
This was the desired behavior of the "Steam" app the whole time. It was just broken by changes on Steam's side prior to GFE 3.20.3 and didn't actually start big picture mode. If you want to stream your desktop or other apps, add them to GeForce Experience per [the setup guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#adding-custom-programs-that-are-not-automatically-found).
