### ISSUE TITLE
Create an Open Source Server Sided Solution that allows GameStreaming and works without NVIDIA Geforce Experience or use Intel Quick Sync and move away from NVIDIA GPU's completely. Reducing Hardware requirements to a capable CPU only.

### ISSUE THREAD

**Issue by Spamm00r** [moonlight-stream/moonlight-qt#369]
**Is your feature request related to a problem? Please describe.**
NVIDIA Geforce Experience gets updated often and forced updates are required. Updating a working setup often breaks Nvidia gamestream and requires DDU and new Setup for Moonlight and Geamstream to work again.  I feel like everytime I want to use Gamestream, I have to update Geforce Experience. And often Gamestream will not show the "Shield" Section in the settings tab making it a pain to use GameStream. Why GeForce Experience suddenly does not show the SHield Section in GFE anymore is a mystery to me. My research indicates that GFE does not recognize the attached Monitor and thus refuses to stream, even though a Monitor is connected to the NVIDIA GPU and the picture is shown by the GPU.

**Describe the solution you'd like**
I want Moonlight Gamestreaming not to rely on Nvidia anymore. Either by having an own Server sided solution, that provides the Encoded real time Screen grab as Geforce Experience does or by disregarding NVIDIA completely by switching to other Hardware Accelerated Encoding methods like using Intel Quick Sync for creating the real time encoded HEVC or at least h264 stream for gamestreaming. That way the hardware requirement will be reduced to a capable CPU only. 

**Describe alternatives you've considered**
I considered to switch to services like Parsec. But I don't like them having to build a Internet Connection to their servers first. I want a selfhosted solution only.  Steam In Home Streaming is quality wise unaccpetable over the Internet. There are no settings in Steam to use HEVC or tweak the encoding settings.

**Additional context**

**Comment by cgutman** [comment]
There is one in development: https://github.com/loki-47-6F-64/sunshine

**Comment by Spamm00r** [comment]
And it works flawless. Thanks for pointing it out.
