### ISSUE TITLE
inconsistent frame rate / stutter

### ISSUE THREAD

**Issue by decknine** [moonlight-stream/moonlight-qt#37]
In assassins creed origins it looks like the stream is dropping frames constantly and not actually at 60fps most of the time. the ubisoft fps overlay says 60fps the whole time though and streaming through Steam IHS at 140mbps is smooth as butter. Also the quality seems poor in comparison to identical settings through android.

tested:
1440p at 70mbps - 100mbps, HEVC forced, HW decode forced, 5.1, fullscreen.

system:
host - gtx1070 (8gb), i7 6700k (Skylake)
client - gtx1060 (3gb), i5 4460 

I understand the software is in alpha! just giving my feedback, happy to test or supply additional information.

**Comment by cgutman** [comment]
Thanks, I've got a few things for you to try and questions about your setup.

Can you get the Moonlight log from %TEMP% after running an affected streaming session?

Does changing to Force H.264 change anything?

What about reducing the bitrate to 40 Mbps?

How are you setting the bitrate to 140 Mbps in Steam? I only see settings up to 50 Mbps, then Unlimited.

Does changing to Force Software Decoding improve the image quality?

What Android device are you comparing to?

**Comment by cgutman** [comment]
@decknine The stuttering should be addressed by the Windows frame pacing support in https://github.com/moonlight-stream/moonlight-qt/commit/404eaa44e455f95b47f288451cf6c848b4128129

Can you confirm that this fixes your issue? Grab the portable zip from here and run it (to avoid having to uninstall your existing version first) - https://ci.appveyor.com/project/cgutman/moonlight-qt/branch/master/job/6agn88bj459t974r/artifacts

**Comment by decknine** [comment]
I can't see a download option anywhere through the link provided.

**Comment by cgutman** [comment]
I thought that link was for a specific build but it wasn't. Here is a corrected link: https://ci.appveyor.com/project/cgutman/moonlight-qt/build/0.0.0.118/job/6agn88bj459t974r/artifacts

**Comment by decknine** [comment]
OK so with V-Sync OFF the results are the same, however, with V-Sync ON there is a definite improvement. What was previously a predictable stutter every 1-2 seconds, is now quite smooth with random/unpredictable stutter, which is less frequent though still clearly visible and quite annoying.

Here are the logs:
V-Sync OFF
[Moonlight-1534486943(V-SyncOFF.log](https://github.com/moonlight-stream/moonlight-qt/files/2296295/Moonlight-1534486943.V-SyncOFF.log)

V-Sync ON
[Moonlight-1534486464(V-SyncON.log](https://github.com/moonlight-stream/moonlight-qt/files/2296297/Moonlight-1534486464.V-SyncON.log)

Also V-Sync Creates more latency (at least through steam) and steam is able to achieve smooth panning without it, so I'm not sure how helpful V-Sync ON is as a solution.

**Comment by cgutman** [comment]
Please try v0.3.0. It has significant rendering changes that should improve video performance.

**Comment by decknine** [comment]
Indeed it does and I was mistaken about steam not using it's own v-sync. I can confirm this issue is fixed for me at least and looks glorious streaming at 1440p/60fps/95mbps. I'm still confused as to why vsync off causes the game to stutter every second or so, but considering there isn't any screen tearing there must be another form of vsync on somewhere else... windows desktop maybe. I think it would be good if moonlight was able to force the game's v-sync on though I'm not sure that is possible.

**Comment by cgutman** [comment]
Thanks for confirming the fix.

The V-sync issue may have something to do with the NvFBC capture method that GeForce Experience uses. It caps the frame rate at whatever Moonlight sets the streaming frame rate to but I don't know how they're handling excess frames above the cap. If they're letting the application render as fast as possible then you'll probably get stutter because some frames will be displayed and others will be skipped. With V-sync on, the app will be forced wait if there are too many frames in flight at one.
