### ISSUE TITLE
Mouse / Keyboard issues when playing with both of them are Bluetooth

### ISSUE THREAD

**Issue by tranbaohuu** [moonlight-stream/moonlight-qt#371]
I'm using Dell XPS 13 9380, Microsoft Bluetooth Mouse 3600. I just bought a Bluetooth Keyboard Keycheron K2 with Bluetooth too.
+the problem is when i connect to play game, i move mouse too fast i face the issue on the cursor like disconnect for 0.2 seconds then reconnect and it loop. When I moved mouse slowly it worked smooth. Important when i disconnected my Bluetooth keyboard everything working perfect !
this is video for my issue !

https://youtu.be/d9wFHCs1Hqc

**Comment by cgutman** [comment]
On Discord. you mentioned this was fixed in 2.0.0.
