### ISSUE TITLE
Not supported hevc decoding on MX150

### ISSUE THREAD

**Issue by nrm-mrn** [moonlight-stream/moonlight-qt#372]
I'm using a host with RTX2060 and a xiaomi mi notebook pro as a client (i5-8250U with UHD620 and discrete MX150, windows 10). GFE and drivers are the latest available 445.87. 
As per [this](https://en.wikipedia.org/wiki/Nvidia_PureVideo#Table_of_GPUs_containing_a_PureVideo_SIP_block) table, MX150 has a feature set H, which "are capable of hardware-accelerated decoding of 8192x8192 (8k resolution) H.265/HEVC video streams". But when I try to force HEVC and hardware decoding in moonlight settings, I get an error "This PC's GPU lacks support for decoding chosen codec". What might be the problem, am I getting something wrong?

h.264 works ok, though, requires too much bandwidth for my circumstances.

**Comment by cgutman** [comment]
We will need the Moonlight logs.

`Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.

**Comment by nrm-mrn** [comment]
This is the relevant input in the log:
17:07:28 - Qt Info: Server GPU: "GeForce RTX 2060"
17:07:28 - Qt Info: Server GFE version: "3.20.3.63"
17:07:28 - SDL Info (0): Video bitrate: 10000 kbps
17:07:28 - SDL Info (0): Audio backend: WASAPI
17:07:28 - SDL Info (0): Selected audio device: Динамики (Realtek High Definition Audio)
17:07:28 - SDL Info (0): Native layout: Stereo (2 channels)
17:07:28 - SDL Info (0): Audio buffer size: 0.014999 seconds
17:07:28 - SDL Info (0): Audio latency: 0.010000
17:07:28 - SDL Info (0): Audio channel count: 2
17:07:28 - SDL Info (0): Audio channel mask: 3
17:07:28 - SDL Info (0): Audio backend: WASAPI
17:07:29 - SDL Info (0): Selected audio device: Динамики (Realtek High Definition Audio)
17:07:29 - SDL Info (0): Native layout: Stereo (2 channels)
17:07:29 - SDL Info (0): Audio buffer size: 0.014999 seconds
17:07:29 - SDL Info (0): Audio latency: 0.005000
17:07:29 - Qt Info: Found "gamecontrollerdb.txt" at "C:/Program Files/Moonlight Game Streaming/gamecontrollerdb.txt"
17:07:29 - SDL Info (0): Loaded 62 new gamepad mappings
17:07:29 - SDL Info (0): V-sync enabled
17:07:29 - SDL Info (0): Windowed mode with DWM running
17:07:29 - SDL Info (0): Windowed: 1 | Present Interval: 80000000
17:07:29 - SDL Info (0): Detected GPU: Intel(R) UHD Graphics 620 (8086:5917)
17:07:29 - SDL Info (0): GPU driver: igdumdim64.dll 22.20.16.4771
17:07:29 - SDL Info (0): Intel driver version blacklisted for HEVC
17:07:29 - SDL Info (0): GPU blacklisted for format 100
17:07:29 - SDL Error (0): Unable to load FFmpeg decoder
17:07:29 - Qt Info: Found "gamecontrollerdb.txt" at "C:/Program Files/Moonlight Game Streaming/gamecontrollerdb.txt"
17:07:29 - SDL Info (0): Loaded 62 new gamepad mappings

Seems like it uses iGPU instead of discrete one for some reason. Can I change it somehow?

**Comment by cgutman** [comment]
HEVC was automatically disabled because your old Intel GPU driver is affected by a bug that causes artifacts during HEVC decoding.

All you need to do to fix this is install the latest GPU driver from Intel's website and HEVC will be enabled.

**Comment by nrm-mrn** [comment]
Indeed, problem solved, thanks.
