### ISSUE TITLE
Hi, I wondering if you can recompile your client application to work on a Surface RT with windows 8.1 ? its an ARM system. Beucase we can thind this device for 50$ or less :P

### ISSUE THREAD

**Issue by DavidFFerreira** [moonlight-stream/moonlight-qt#373]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cgutman** [comment]
Unfortunately this isn't feasible. It's not as simple as just recompiling. The renderer would have to be rewritten to work on a UWP system. Additionally, the Qt framework doesn't support UWP on Win8.1.

**Comment by MakiseKurisu** [comment]
Currently Surface & Surface 2 can be jailbroken / flashed to run unsigned desktop app. Unfortunately those are 32 bits devices so we need another port. cgutman can you try building it? I tried myself but I can't even get a working msvc-arm64 qt toolchain so build-arch.bat failed at linking qt libraries, and I also need to figure out how to build moonlight-qt-prebuilts. That's pretty daunting without any documentation.

**Comment by cgutman** [comment]
@MakiseKurisu please open a new issue for that and I would be happy to help.
