### ISSUE TITLE
Analog left direction not working properly on Nintendo switch  

### ISSUE THREAD

**Issue by penkamaster** [moonlight-stream/moonlight-qt#374]
Can't reach 100% of the left direction with the analog stick on l4t Ubuntu on the Nintendo switch  

both streamed games and the game selection menu itself are affected.

In the Moonlight game selection menu, you cannot move the cursor to the left with the analog stick, while the other directions are working.

As a workoround for gaming, I have tried to calibrate the switch joystick on Windows while connected with Moonlight, even not reaching the left limit of the stick, but I have not managed to fix it.

I do not know if other versions of Moonlight for Linux have the problem, since I have not tried another, but the ones that I tried (Mac, Windows and android) works correctly.
Maybe is an OS problem.

 - OS: L4t Ubuntu 3.0.0 for Nintendo Switch
 - Moonlight Version: Moonlight PC V2.0.0

**Comment by penkamaster** [comment]
my joystick appears to be out of calibration.

**Comment by penkamaster** [comment]
Calibrated with jscal

**Comment by penkamaster** [comment]
It seems that the default configuration of my joysticks is out of calibration.
If I install an application like jstest-gtk on L4t, in order to test joysticks, I can see how the default configuration of /dev/input/js4 device (which currently seems to be the one used by the applications) cannot reach the left limit of the joystick.

I've tried to calibrate the joystick using jscal with this device (/dev/input/js4), and while jstest-gtk is able to use the new calibration, moonlight seems to keep reading the old one.

Could you help me to understand how moonlight reads the joystick calibration settings?

Thank you.

**Comment by cgutman** [comment]
Moonlight uses SDL2 for joystick and gamepad support. SDL2 uses the newer `/dev/input/event` devices for joystick input, rather than the old `/dev/input/js` devices. To calibrate the evdev devices, you should use `evdev-joystick` as shown here https://joaorb64.github.io/2018/02/14/Configuring-a-Nintendo-Switch-Pro-Controller-on-Linux.html
