### ISSUE TITLE
Non Native Resolution on Streaming Desktop - Display Issues

### ISSUE THREAD

**Issue by Byron1c** [moonlight-stream/moonlight-qt#377]
**Describe the bug**
I have a GTX1060 and a 4k monitor on the host pc, and 1080p on the client. Client is set to 1080p, and works fine when streaming the desktop and games at 1080p. When I changed the Host's resolution to 1440p, streaming the desktop does not display properly. Its showing full sized screen, and a smaller (shrunk 1440p) version super imposed over it.

**Steps to reproduce**
As per description above, change the Host's resolution to a lower than native resolution, then stream the desktop from a 1080p client.

**Screenshots**
Attached

**Affected games**
Streaming the desktop

**Other Moonlight clients**
Android - No
Others - unsure

**Moonlight settings (please complete the following information)**
Tried turning settings on and off - optimise game, changed client resolution settings, bitrate, Frame Pacing, 
I cannot see any way of resetting settings back to default? (feature/enhancement?)

**Client PC details (please complete the following information)**
- Win 10 64bit Pro, latest updates
- GTX1050M 4gb, i7 7990, 1080p
- 442.19-notebook-win10-64bit-international-dch-whql

**Server PC details (please complete the following information)**
- Win 10 64bit Pro, latest updates
- GTX1060 6gb, i7 4770, 4k native, 1440p current setting
- 445.87-desktop-win10-64bit-international-dch-whql

**Moonlight Logs (please attach)**
- Attached
[Moonlight-1588476040.log](https://github.com/moonlight-stream/moonlight-qt/files/4569582/Moonlight-1
![2020-05-03](https://user-images.githubusercontent.com/16605489/80898025-bc4e7000-8d3d-11ea-86b0-28e5c9af03f4.png)
588476040.log)

**Comment by Byron1c** [comment]
oh, Im using the latest Moonlight too of course (2.0)

**Comment by cgutman** [comment]
Change the resolution using the NVIDIA Control Panel, not the Windows display settings.

**Comment by Byron1c** [comment]
By that I assume you mean on the host... did not work, and the resolution was already set as desired in Nvidia Control Panel on the host
Ive double checked in the 3D per-app and global settings and there is no option to set a resolution there either

![Capture](https://user-images.githubusercontent.com/16605489/80898562-13574380-8d44-11ea-8961-67a8cda6e169.JPG)
, as per the screen shot

**Comment by cgutman** [comment]
Try toggling to 1080p and back to 1440p using the Nvidia Control Panel. The Windows display options only rescale the output which leads to the artifacts you show in your screenshot.

If that still doesn't work, go to the "adjust desktop size and position" and make sure "perform scaling on" is set to GPU.

**Comment by Byron1c** [comment]
Toggling the res in the control panel did the trick :)  
Its funny (of Windows) that it doesnt get fixed on a reboot 
Thanks for that!!
