### ISSUE TITLE
Key combos involving cmd are no longer sent to the server/host

### ISSUE THREAD

**Issue by leftyfl1p** [moonlight-stream/moonlight-qt#378]
**Describe the bug**
Keyboard inputs are not sent to the host (server) if the cmd key is held down as of 2.0. Previously on older versions (1.2.1) if the cmd key was held down and the corresponding key wasn't a valid keyboard shortcut, the corresponding key would still be sent to the host. This was useful for being able to use mouse button shortcuts for things like finder/browser forward/backward navigation with cmd + [ and still being able to use the buttons in games with moonlight. Since moonlight doesn't have anything like a disable hotkey or 'gaming mode' as some call it, the only solution is to bind the mouse button to a simple key and neuter the navigation functionality.

**Steps to reproduce**
Hold cmd down and type other invalid shortcut keystrokes, no inputs are sent. On 1.2.1 inputs other than the cmd key are still sent. An example of a valid keyboard shortcut is cmd q (for quit), an invalid one would be something like cmd [ or any other combo that MacOS does not recognize.

**Client PC details (please complete the following information)**
 - OS: MacOS 10.14.6
 - Moonlight Version: 2.0.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 18362
 - GeForce Experience version: 3.20.3.63
 - Nvidia GPU driver: 445.87

**Moonlight Logs (please attach)**
[Moonlight-1588535129.log](https://github.com/moonlight-stream/moonlight-qt/files/4571494/Moonlight-1588535129.log)

**Additional context**
In the log session I attempted to use the key combo as normal and I'd guess thats what the spam of unhandled button events is.

**Comment by cgutman** [comment]
This was fixed by https://github.com/moonlight-stream/moonlight-qt/commit/d7fd578cc35d14577d33f7301f0e241b28b38d06

You can use a nightly build including the fix - https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/32610165/job/t6qvt6aleelst3q9/artifacts
