### ISSUE TITLE
Feature request: auto updater

### ISSUE THREAD

**Issue by lodesmets** [moonlight-stream/moonlight-qt#38]
This might be a useful (non essential) feature: an auto updater (or at least a popup message saying there is a new build available).
So people don't have to check the github page every so often

**Comment by Jorys-Paulin** [comment]
@lodesmets Already implemented. It shows an icon when an update is detected, you still have to download it manually for now.

**Comment by lodesmets** [comment]
Really? I opened moonlight before I posted this, and I just checked (to be sure) and I can't find the icon

**Comment by Jorys-Paulin** [comment]
Maybe because you're running the latest version? (v0.2.0)

**Comment by lodesmets** [comment]
Nope, just re checked version 0.1.0.0
install date 5/8/2018

**Comment by lodesmets** [comment]
This is my screen
![knipsel2](https://user-images.githubusercontent.com/31108717/44037296-44b4d34a-9f14-11e8-8966-286ff7f596be.PNG)

**Comment by Jorys-Paulin** [comment]
Well, report to @cgutman, it's supposed to work.

**Comment by cgutman** [comment]
The update functionality was added in v0.2.0, so you will see the button appear when the next release after v0.2.0 is pushed.

**Comment by Jorys-Paulin** [comment]
Yeah, kinda confused myself with the features there, sorry @lodesmets!
