### ISSUE TITLE
starting Remote Desktop session causes moonlight to lose connection and not recognize the game stream PC anymore

### ISSUE THREAD

**Issue by resk8** [moonlight-stream/moonlight-qt#382]
Hi there,

I might have found a bug here. It seems that after starting a remote desktop session from Mac to PC, is causing moon light to lose connection and forget the PC even after disconnecting the remote desktop session. I have to quit the Remote Desktop app and restart the host pc to be able to re-add the PC again in moonlight.

Client:
Mac with Catalina 10.15.4 

Host:
Windows 10 pro 1909 build 18363.815
Nvidia RTX 2070 Founder's edition
Geforce Experience 3.20.3.63
[Moonlight-1589083200.log](https://github.com/moonlight-stream/moonlight-qt/files/4605118/Moonlight-1589083200.log)

Reproduce:
* Open moonlight on Mac
* (if host is in sleep mode, wake up through moonlight (if wake-on-lan is setup in host) )
* Open Remote Desktop app
* start a session with Host
* You should see the Desktop Icon show a warning in moonlight
* disconnect or close Remote desktop
* moonlight still shows warning and won't connect to host anymore
* trying to add host manually with IP address also does not work

workaround:
* close moonlight on client (Mac)
* close remote desktop app
* power cycle the host 
* re-open moonlight
* should find the game stream PC 

Screenshot of the issue:

![Screen Shot 2020-05-09 at 8 52 07 PM (2)](https://user-images.githubusercontent.com/15257387/81490503-e9b48580-9237-11ea-8c5a-790dff3a34ab.png)
![Screen Shot 2020-05-09 at 8 57 19 PM (2)](https://user-images.githubusercontent.com/15257387/81490506-ede0a300-9237-11ea-839a-776b796f9eaa.png)

I don't know how to get the version of moonlight from Mac but I download the latest Mac version of moonlight second week of may 2020 ( 4th to 8th). Don't remember

moonlight logs client (Mac)
[Moonlight-1589083200.log](https://github.com/moonlight-stream/moonlight-qt/files/4605121/Moonlight-1589083200.log)

**Comment by cgutman** [comment]
Microsoft Remote Desktop causes NVIDIA GeForce Experience's GameStream server to shut down, probably because it locks the user session on the physical PC.

This is noted on our troubleshooting page: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#known-application-compatibility-issues

Other remote desktop software like TeamViewer or Chrome Remote Desktop don't cause this problem.

**Comment by resk8** [comment]
ohh sorry I missed this FAQ,

**Comment by CyberMew** [comment]
If you don't have easy physical access to your host machine like me, install/setup Parsec via Microsoft Remote Desktop, disconnect from Microsoft Remote Desktop session, then connect via Parsec on your client and use it to remote login back to the windows account. Works as well.

**Comment by ajmcmiddlin** [comment]
You can also use [TightVNC](https://www.tightvnc.com) to login remotely if you don't have physical access to your PC and want something open source. Furthermore, you can add `C:\Windows\system32\mstsc.exe` to your Shield apps to get remote desktop via Moonlight in the future.

**Comment by t-zone** [comment]
I use rdpwrap to login with a second account using rdp and this seems to cause the same issue. Logging out from that account doesn't resolve the issue. I have to restart the PC to get it working again. Is there a way to restart the GameStream server after the issue is triggered?

**Comment by xthree** [comment]
In case someone doesn't see the comment above about it being noted in the Troubleshooting page: 

To use Moonlight again after connecting via RDP:

1. Log into the PC via Teamviewer, VNC, or locally. 
2. The computer should be visible in Moonlight again.
