### ISSUE TITLE
Moonlight only showing blank screen on Intel iGPU, crashes upon interaction

### ISSUE THREAD

**Issue by kyoubate-haruka** [moonlight-stream/moonlight-qt#384]
**Describe the bug**
Trying to run Moonlight on a Windows 7 machine results in a completely blank window. Trying to click into or move the window results in a crash.

**Steps to reproduce**
All I did was launching the program.

**Screenshots**
![IMG_20200511_1847130](https://user-images.githubusercontent.com/46010460/81589461-bd287700-93b9-11ea-9ecc-4f407d052767.jpg)
Don't have a keyboard attached to the machine, sorry.

**Affected games**
N/A

**Other Moonlight clients**
N/A

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
No, as I can't even get into the settings menu.
- If so, which settings have been changed?
N/A
- Does the problem still occur after reverting settings back to default?
N/A

**Client PC details (please complete the following information)**
 - OS: Windows 7 SP1
 - Moonlight Version: 2.0.0 portable

**Server PC details (please complete the following information)**
N/A

**Moonlight Logs (please attach)**
Log: [Moonlight-1588683517.log](https://github.com/moonlight-stream/moonlight-qt/files/4611002/Moonlight-1588683517.log)
Crash dump: [Moonlight-1588683754.zip](https://github.com/moonlight-stream/moonlight-qt/files/4611004/Moonlight-1588683754.zip)

**Additional context**
The box runs a really old Intel integrated GPU as far as I'm aware of. Non-demanding games however work fine on it. I am not aware of any newer drivers existing for this machine.

**Comment by cgutman** [comment]
Try launching Moonlight from the command line but run `set QT_ANGLE_PLATFORM=d3d9` first. If that fails, you can try `set QT_ANGLE_PLATFORM=warp`.

**Comment by kyoubate-haruka** [comment]
`QT_ANGLE_PLATFORM=d3d9` worked, thank you!
