### ISSUE TITLE
Host resolution changes automatically

### ISSUE THREAD

**Issue by endyb66** [moonlight-stream/moonlight-qt#389]
My host resolution ist set to 4k (3820x2160). My moonlight client display supports only 1080p, so i set it to that. Now when i connect, the resolution of the host changes also to 1080p and after disconnect, it does not change back. Is this normal behavior? When selection 4k on the moonlight client, everything is okay, but a waste of bandwidth...

**Comment by cgutman** [comment]
Did you close the app you were streaming within moonlight? Just closing moonlight leaves your session running for you to resume later. You need to click on the X on the app in the grid that you were streaming to terminate the steam.

**Comment by endyb66** [comment]
Basically i boot my host, which does start Steam BP, when connecting with moonlight, the resolution changes to 1080p. When i want to end my session, in steam i select at the top right corner stop streaming. Does it mean, i have to quit Steam BP too?
