### ISSUE TITLE
Virtualhere sharing (for Steam Controller)

### ISSUE THREAD

**Issue by ngmoviedo** [moonlight-stream/moonlight-qt#395]
I'm using Moonlight on the Steam Link device, and I'm trying to use the Steam Controller through Virtualhere.

The Virtualhere trial version (limited to one device) is installed and running on the host PC, and the Virtualhere server (downloaded from the Virtualhere webpage) is running on the Link. This setup works perfectly with the built-in streaming of the Link, but I have been unable to get it working through Moonlight. It seems like Moonlight "grabs" the Steam Controller once initiated and doesn't pass it through Virtualhere.

Is there a way in which this behaviour could be changed? I haven't checked if the situation is related exclusively to this controller, but I'll do it as soon as I can.

Maybe an option could be added on the settings menu to forbid Moonlight from grabbing certain controllers, although I see how this could be problematic in some cases.

I don't know if it was necessary, but as suggested in this thread: https://steamcommunity.com/app/440520/discussions/0/135508833657224350/, I have modified /home/steam/bin/usb_sharing.sh so that the Steam Controller could be seen by Virtualhere. 

It's a pitty that the Steam Controller can't be used through Moonlight.

**Comment by cgutman** [comment]
You should be able to achieve this using SDL's `SDL_GAMECONTROLLER_IGNORE_DEVICES` hint.

```
/**
 *  \brief  A variable containing a list of devices to skip when scanning for game controllers.
 *
 *  The format of the string is a comma separated list of USB VID/PID pairs
 *  in hexadecimal form, e.g.
 *
 *      0xAAAA/0xBBBB,0xCCCC/0xDDDD
 *
 *  The variable can also take the form of @file, in which case the named
 *  file will be loaded and interpreted as the value of the variable.
 */
#define SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES "SDL_GAMECONTROLLER_IGNORE_DEVICES"
```

I don't know the Steam Controller's VID/PID pair, but if it was 0x1234/0x5678, then you can add
`SDL_GAMECONTROLLER_IGNORE_DEVICES=0x1234/0x5678` before the `exec` line in `moonlight.sh` and that should do the trick.

**Comment by ngmoviedo** [comment]
I'm not sure if I completely understand your advice. I have checked the VIP/PID pair of the Steam Controller through lsusb and modified the moonlight.sh file accordingly. Having done that, it is still not working. 

Was that the only file to modify or have I missed something?

**Comment by cgutman** [comment]
Can you post the log from `/tmp/moonlight.log`?

**Comment by ngmoviedo** [comment]
Yes, here it is.

[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/4683833/moonlight.log)

**Comment by cgutman** [comment]
It looks like the controller is still be picked up by SDL so the environment variable must be set wrong or something

**Comment by ngmoviedo** [comment]
That's strange. I've tried setting both environment variables on moonlight.sh. Perhaps I've done something wrong, but I can't see what it could be.

```
#!/bin/sh

# The default HOME is not persistent, so override
# it to a path on the onboard flash. Otherwise our
# pairing data will be lost each reboot.
HOME=/usr/local/moonlight

# For a seamless transition across the Qt 5.9 -> Qt 5.14 boundary,
# we bundle binaries built with both Qt 5.9 and Qt 5.14 and pick
# the correct one at runtime.
if [ -d "/usr/local/Qt-5.14.1" ]; then
    BIN="moonlight"
else
    BIN="moonlight59"
fi

# Renice PE_Single_CPU which seems to host A/V stuff
renice -10 -p $(pidof PE_Single_CPU)

# Renice Moonlight itself to avoid preemption by background tasks
# Write output to a logfile in /tmp
echo Launching $BIN
SDL_GAMECONTROLLER_IGNORE_DEVICES=0x0424/0x2514,0x1d6b/0x0002,0x28de/0x1142,0x28de/0x1142
SDL_ENABLE_STEAM_CONTROLLERS=0
exec nice -n -10 ./bin/$BIN > /tmp/moonlight.log
```

**Comment by ngmoviedo** [comment]
Shouldn't the environment variables be defined with "export"? In that case, I can see why it was not working. I'll try that as soon as possible.

**Comment by ngmoviedo** [comment]
It works! It seems like I had broken some things while tinkering. A factory reset and reinstallation solved the issue. It's not ideal, as you need a second controller to use on Moonlight's menu, but that was expected.

**Comment by talondnb** [comment]
Sorry to chime in on a closed thread, but I'm trying to get my Steam Controller to be detected under the Steam app as a Steam Controller and not an Xbox controller under moonlight. As it's not detected as a Steam Controller, I can't use the right side D-pad in games and it only appears to function as a mouse cursor, even with the Steam overlay.

Any advice on how to get this working?

**Comment by ngmoviedo** [comment]
You can try Virtualhere or USBIP, but it's tricky, especially if you are not willing to pay for a full Virtualhere license (which is horribly expensive). Those two programs allow you to send usb input over your network. USBIP is the original one and it's FLOSS, but it's lacking good support on Windows and getting it to run it's not trivial at all. If you feel adventurous, there are some recent forks on Github. Just google "usbip windows".
You don't specify in what platform are you running the Moonlight client. If in GNU/Linux, the USBIP server should be straightforward to install, just check your distribution's documentation. If in a Steam Link, I've read is theoretically possible to install USBIP there, but it requires some cross-compiling, and I haven't tried it. I don't know about Mac, iOS, nor Android.
The "easiest" option would be using Virtualhere. The free version allows using one device, but I've got the impression that the Steam Controller gets recognized as two, so I've had no luck with it. At least the installation is simple, you only need to download the client and the server from the webpage: [](https://www.virtualhere.com/home). Just in case, the client is the PC where the games are running, and the server is where you've connected your controller.
Steam Links have a VirtualHere server preinstalled, but it only works with the paid version. If you are using this device you can install this simple program: [](https://github.com/l1m3r/freeVHUSB4SL). The last commit is old, but it still works.
As a last resort, there's the paid Virtualhere license, but I have not tried it.
Sadly, I ended up using Steam remote play for the Steam Controller. It's not as good and stable as Moonlight, but it's OK if you tinker a bit with the settings and its controller support is amazing.
Anyway, don't blame Moonlight for the lack of controller support. That's NVIDIA's fault.
Hope it helps.

**Comment by talondnb** [comment]
Thanks @ngmoviedo for the detailed response. It sounds a lot like I'm in the same boat as you; I was only just trying out moonlight for the first time last night on my Steam Link hardware. There is certainly a noticeable improvement in streaming with moonlight over remote play with the steam controller, but as you've mentioned, the support for controllers is all right there.

Would you mind sharing any tweaks you've done to improve your experience with remote play? So far I've only really enabled hardware encoding and changed the streaming setting to 'Beautiful' (I'm running wired ethernet).

**Comment by ngmoviedo** [comment]
I've decided to give it another try, and I've been successful. It seems like I had been missing one step on my previous attempts. I'll detail my steps. Note that a second controller or mouse is required for the process.
1. Install Moonlight and Virtualhere server on the Steam Link. The latter can be found here: https://github.com/l1m3r/freeVHUSB4SL/releases. Enable ssh access in your Steam Link if you haven't done it before. Look here if you don't know how to do it: https://mcd1992.blogspot.com/2015/10/alright-this-was-lot-easier-than-i.html.
2. Access your Link via ssh from your PC and modify the file moonlight.sh
`vi ../apps/moonlight/moonlight.sh`
Add this two lines before the last line:
> export SDL_GAMECONTROLLER_IGNORE_DEVICES=0x0424/0x2514,0x1d6b/0x0002,0x28de/0x1142,0x28de/0x1142 
> export SDL_ENABLE_STEAM_CONTROLLERS=0
3. On the Link, start the Virtualhere server.
4. Run the client on your PC. Can be found here: https://www.virtualhere.com/usb_client_software
5. You'll see two references to Steam Controller. In my case, the second one is the correct one. If not, trial and error is the way to go. Enable one of them. You should see a Steam notification saying that a Steam Controller has been connected.
6. Now, the part that I forgot. Enter Moonlight on your Link. Your Steam Controller shouldn't be working. That's alright, and means that you are on the right track. With a second controller or mouse enter Moonlight's settings and disable the option to use the controller as a mouse. If you don't do this, the right trackpad won't work.
7. Once you select the game with the second controller, the Steam Controller should be working.

Once configured, you just need to enable the server on the Link and the client on the PC each time. You can select auto-use on the client to make it more comfortable. I haven't used it extensively this way, so I can't speak about the stability or reliability, but it appears to work. 
Hope it works for you.

**Comment by ngmoviedo** [comment]
In any case, if you end up returning to remote play, which is far more straight forward for the Steam Controller, I've found that unticking "Enable hardware decoding" under "Advanced client options" really makes a difference on my setup. I don't know the reason for it, and I know it seems counter intuitive, but I've read many reports on the same behaviours in multiple forum posts. The only caveat is that this option reenables itself on each reboot, so you have to remember to change it.
Like you, I'm also on a wired connection and have it on "Beautiful" and "Unlimited bandwidth".
I have also made some adjustments under the QoS section of my router to prioritize the traffic between the PC and the Link, and enabled "Prioritize network traffic" under "Advanced host options".
I've read somewhere that disabling unnecessary hardware encoding options in "Advanced host options" can help: when using an NVIDIA card you can disable the Intel and AMD options. I'm not sure this is useful but it doesn't hurt.
I suppose it may depend a lot of the PC and the network specifications, but on my setup this works very well, even for demanding games.

**Comment by JelledFro** [comment]
@ngmoviedo , I followed your steps (except step 2, because I want to connect a usb headset, not a controller) but it's not working. Nothing shows up on the pc client. When I select the VH icon on the steam link the screen goes black, then a "connecting to network" loading/boot screen appears and I'm back in the main menu. Is that the expected behavior? I don't know how to check if the VH server is actually running. The client can detect other VH servers, so I don't think that's the issue. Do you have any tips?
