### ISSUE TITLE
Windowed mode not working in Linux

### ISSUE THREAD

**Issue by KokoseiJ** [moonlight-stream/moonlight-qt#397]
**Describe the bug**
When I press Ctrl+Shift+Alt+X, It should switch to the windowed mode, but It won't turn to windowed mode and just makes the screen size smaller.

**Steps to reproduce**
I just pressed Ctrl+Shift+Alt+X and this happened, Nothing much

**Screenshots**
![image](https://user-images.githubusercontent.com/40889113/82961359-1ae2d300-9ff8-11ea-9415-e9b235fac969.png)

**Affected games**
Seems like It affects every game, I opened up explorer.exe at the screenshot

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?
No.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
No.

**Client PC details (please complete the following information)**
 - OS: Fedora 32 x86_64 Cinnamon spin
 - Moonlight Version: v2.1.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 1909
 - GeForce Experience version: 3.20.3.63
 - Nvidia GPU driver: 445.87

**Moonlight Logs (please attach)**
[Moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/4685663/Moonlight.log)

**Additional context**

**Comment by cgutman** [comment]
This works fine for me on Fedora 32 (GNOME) with the 440.82 driver. Maybe it's something to do with your window manger.

**Comment by h0tw1r3** [comment]
I'm using Fedora 32 (GNOME), wayland, intel graphics. Same problem.

**Comment by h0tw1r3** [comment]
narrowed it down to hardware video decoding. disable and the problem goes away.

**Comment by KiralyCraft** [comment]
This issue seems to be related to the SDL_GetWindowBordersSize function ([See here](https://media.discordapp.net/attachments/465369864534491146/776394646586261525/Kepernyokep_errol_2020-11-12_11-34-38.png?width=1440&height=520))
The SDL documentation says this method is only available on X11, and fails on Wayland: [link](https://wiki.libsdl.org/SDL_GetWindowBordersSize)

**Comment by cgutman** [comment]
It's fine if that fails (and it does on macOS too). We just don't consider the bordersv when sizing the window.
