### ISSUE TITLE
Moonlight No Longer Works on Latest Geforce Update, 446.14

### ISSUE THREAD

**Issue by jeremybris** [moonlight-stream/moonlight-qt#398]
**Describe the bug**
Moonlight worked great, until the latest Geforce Experience, then I could not connect to the host PC on the same, local network. I tried to uninstall and reinstall moonlight on the client PC. It detected the host PC correctly, then after I typed in the access code, I got this error

<img width="956" alt="Capture34" src="https://user-images.githubusercontent.com/11889359/83077953-79cf3900-a046-11ea-9000-65f3f505fdc6.PNG">

**Steps to reproduce**
- Install the latest Geforce Experience.

**Other Moonlight clients**
- This does not occur on the Android version. I am not sure about the IOS, linux, or any other versions.

**Moonlight settings (please complete the following information)**
- Defaults.

**Client PC details (please complete the following information)**
 - OS: Windows 10, Latest Update
 - Moonlight Version: Latest Version, v2.1.0

**Server PC details (please complete the following information)**
 - OS: Windows 10, Latest Update
 - GeForce Experience version: Latest Update, 3.20.3.63
 - Nvidia GPU driver: Latest Update, 446.14
- CPU: AMD Ryzen
- GPU: RTX

**Moonlight Logs (please attach)**
- I cannot provide a Moonlight Log because the application does not start for me.

**Additional context**
- My internet has been spotty lately. I will reset my internet tonight and close the report if that works.

**Comment by cgutman** [comment]
I'm able to pair and stream fine from GFE 3.20.3.63 with the 446.14 driver on my RTX 2080 Super with Moonlight v2.1.0. So the issue seems specific to your system.

**Comment by jeremybris** [comment]
Ok, after reinstalling the Geforce Experience, restarting my host PC, and restarting my client PC, it fixed itself. I'm sorry about posting the erroneous report.
