### ISSUE TITLE
Start moonlight client in fullscreen mode

### ISSUE THREAD

**Issue by igno2k** [moonlight-stream/moonlight-qt#399]
**Is your feature request related to a problem? Please describe.**
For a gaming pc (linux) hooked up to a tv I want to start the moonlight client in full screen mode without X11 windows decoration.

**Describe the solution you'd like**
Command line option to start moonlight client in fullscreen

**Comment by jmt-gh** [comment]
I've opened PR #492 for this. I've added it as a UI option in the Moonlight UI, rather than a CLI option, as most of the options provided through the CLI are for the gamestream configuration, not the Moonlight UI
