### ISSUE TITLE
Blurry and distorted image with AMDGPU and VDPAU hardware decoding

### ISSUE THREAD

**Issue by igno2k** [moonlight-stream/moonlight-qt#401]
**Describe the bug**
When using hardware decoding on an Arch Linux system with a Radeon RX 570 GPU I get a blurry (hevc) or distored (h264) image. See screenshots.
Using software decoding is working fine.

**Steps to reproduce**
Stream moonlight in 1080p/60fps with Auto setting or fixed hardware decoder (hevc or h264) on an Arch Linux client with RX 570 GPU. Using AMDGPU driver and radeonsi for VDPAU / VA-API support.

**Screenshots**
Working with software decoder:
![Bildschirmfoto von 2020-06-01 17-10-07](https://user-images.githubusercontent.com/3158341/83425721-68af6f00-a42e-11ea-8de0-b1d93c5c8807.png)
Auto / Auto settings:
![Bildschirmfoto von 2020-06-01 17-10-59](https://user-images.githubusercontent.com/3158341/83425800-7e249900-a42e-11ea-8658-e569a4431f49.png)
Forced hardware / h264 decoder:
![Bildschirmfoto von 2020-06-01 17-10-38](https://user-images.githubusercontent.com/3158341/83425837-8f6da580-a42e-11ea-8078-6151eca3a156.png)

**Other Moonlight clients**
No, only this constellation with Radeon card. Other clients (Steam Link, Arch Linux with Intel GPU) work fine.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
yes, see screenshot
- If so, which settings have been changed?
![Bildschirmfoto von 2020-06-01 17-08-55](https://user-images.githubusercontent.com/3158341/83425966-c774e880-a42e-11ea-8493-ed6d357a50cc.png)
- Does the problem still occur after reverting settings back to default?
yes, default settings with 1080p / 60fps and auto / auto setting also show this problem.

**Client PC details (please complete the following information)**
 - OS: Arch Linux with AMDGPU open source driver
 - Moonlight Version: 2.1.0

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - GeForce Experience version: 3.20.3.63
 - Nvidia GPU driver: 445.87

**Moonlight Logs (please attach)**
full log attached, trying different settings.
[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/4712140/moonlight.log)
Output from `vainfo` and `vdpauinfo` also attached.
[vainfo_out.log](https://github.com/moonlight-stream/moonlight-qt/files/4712141/vainfo_out.log)
[vdpauinfo_out.log](https://github.com/moonlight-stream/moonlight-qt/files/4712142/vdpauinfo_out.log)

**Additional context**
Also tried `FORCE_VAAPI=1` without any luck.

**Comment by cgutman** [comment]
Probably an upstream bug in Mesa or something. The fact that it occurs in both VAAPI and VDPAU backends strongly suggest it's not Moonlight's fault.

**Comment by igno2k** [comment]
OK, thanks - I will check if it is an upstream bug there.

**Comment by uraza** [comment]
Hi @igno2k !
Do you remember getting any feedback elsewhere regarding this issue?
I am facing the same problem today where hardware decoding leads to blurry texts, but software decoding looks just fine.
Thanks!
