### ISSUE TITLE
Toggle for Key forwarding (windows)

### ISSUE THREAD

**Issue by jkommeren** [moonlight-stream/moonlight-qt#402]
**Is your feature request related to a problem? Please describe.**
Whenever I press the windows key, or alt-tab, I'm taken to my pc's desktop instead of the server's.

**Describe the solution you'd like**
I'd like a toggle to forward alt / tab and windows-key commands, if possible. I understand it might not be desirable for "pure" gamers (hence the toggle)

**Describe alternatives you've considered**
I could not find any other way to achieve this.

(I hope this is easy enough to implement. I frikkin love this platform, so if it's not possible, no biggie)

**Comment by cgutman** [comment]
Those keys are blocked on the host-side by GeForce Experience even if we did send them.

You can bind them to different key combos using Autohotkey on the host if you want. The bot on the discord server has instructions for that.

**Comment by NullVoxPopuli** [comment]
Is there some protocol we could come up with to get around it?

Like, run a little moonlight-shortcut-key-service on the host that could execute the blocked keys?
This'd require an additional socket connection to the host... but maybe that's fine?
