### ISSUE TITLE
Implement Multitouch (Windows?)

### ISSUE THREAD

**Issue by jkommeren** [moonlight-stream/moonlight-qt#403]
**Is your feature request related to a problem? Please describe.**
When playing games with touch screen remotely, it forwards only single-touch commands, and registers a long-press only for a couple of seconds.

**Describe the solution you'd like**
I'd like to play pinball (in an ideal world) and keep both of my flippers up using the touch screen

**Describe alternatives you've considered**
On-screen keyboard, disabling rightmouse triggering for long-press (turns out after a few secs it just does not register it as a touch anymore, instead of a right mouse)

**Additional context**
As a fellow developer I understand this could be a tough cookie, for maybe only a few cases (like the people with a surface book or surface pro, like me). If I can help out in any way, please let me know.

**Comment by cgutman** [comment]
This isn't possible with the GameStream protocol.
