### ISSUE TITLE
Performance overlay not showing on Linux

### ISSUE THREAD

**Issue by alomsimoy** [moonlight-stream/moonlight-qt#405]
I've been using moonlight-qt in linux for a while, and it works flawlessly. However, the "Toggle performance stats overlay" keybind seems to do nothing. I've found people with moonlight on other OS that can activate this, so I guess it's a linux issue. All the other shortcuts works fine.
I would like to use it to improve my settings without having to "guess" if a config were working better or worse than the previous one.

**Describe the bug**
The performance stats overlay does not show

**Steps to reproduce**
- Install moonlight-qt 2.1.0 in linux
- Pair a computer
- Open a game
- Press Ctrl+Alt+Shift+S to open the performance stats overlay
- Nothing happens

**Affected games**
- All games affected

**Other Moonlight clients**
- Tested with moonlight-qt in linux. Cannot test with other OS since I don't have any other one.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Yes
- If so, which settings have been changed? Resolution, framerate, Video decoder and Video codec
- Does the problem still occur after reverting settings back to default? Yes

**Client PC details (please complete the following information)**
 - OS: Archlinux
 - Moonlight Version: 2.1.0 (tested flatpak and native)

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro
 - GeForce Experience version: 3.20.3.63
 - Nvidia GPU driver: 445.87

**Moonlight Logs**
[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/4726243/moonlight.log)

**Comment by cgutman** [comment]
The performance overlay is not yet supported on most Linux renderers.

**Comment by alomsimoy** [comment]
Is there any plan to add it? What's blocking the addition of that feature to linux?

**Comment by cgutman** [comment]
VDPAU and direct VAAPI renderers don't have the ability to overlay on top. We will need to move them to the EGL renderer.

**Comment by alomsimoy** [comment]
It's a planned bugfix? Or will it be on hold for the moment?

**Comment by cgutman** [comment]
It's not a bug fix; it's a feature request.

Overlay support for EGLRenderer needs to be written.

**Comment by alomsimoy** [comment]
Okay, thank you :)
