### ISSUE TITLE
SSO Integration

### ISSUE THREAD

**Issue by The-Funk** [moonlight-stream/moonlight-qt#41]
Not really an issue, more of a feature request or recommendation request. Is there any sort of SSO integration that I can use with moonlight to connect to a Windows 10 remote machine that is not yet logged in and running GFE?

**Comment by Jorys-Paulin** [comment]
@The-Funk We are totally dependant on GFE to make everything run. This would be too complex to implement and would only be used once to set up for GFE, so I don't see any benefits.

**Comment by The-Funk** [comment]
High performance VDI was my original thought. Why limit yourself to streaming games? You've got the best performing VDI platform out there that I can find. Add in SSO and those of us with KVM labs will jump for joy.

**Comment by cgutman** [comment]
I think someone on the Discord server has written something that remotely fills in the PIN for pairing (only part of the problem here). I suspect there is a way to forklift the tokens that the PC uses to sign in with GFE to another machine so you could avoid the initial sign in.
