### ISSUE TITLE
Screen tearing on Raspberry Pi

### ISSUE THREAD

**Issue by michellabbe** [moonlight-stream/moonlight-qt#410]
As already reported in https://github.com/moonlight-stream/moonlight-qt/issues/160#issuecomment-585449634

> * The UI tearing issue is a problem with the graphics stack of the Pi. Even though EGLFS does support V-sync, it doesn't work on the Pi (even with QT_QPA_EGLFS_FORCEVSYNC=1)

For the records, there is a workaround:

`sudo raspi-config -> Advanced Options -> Compositor -> then choosing "no" to xcompmgr composition manager`

It seems to work fine while waiting for a [definitive fix](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=246291&start=25#p1641846).

This technique might be usable by Moonlight to fix tearing without requiring disabling xcompmgr:

> use X11 MMAL splitter for video output. As soon as you switch to full screen mode (f key), the video is shown in an overlay created by the GPU. No screen tearing or lost frames anymore.

**Comment by cgutman** [comment]
This is a change that would need to be made on the Qt-side. Our MMAL renderer already uses overlays which is why the stream itself doesn't tear.

You can file an bug on Qt at https://bugreports.qt.io/
