### ISSUE TITLE
Dual monitors+Synergy

### ISSUE THREAD

**Issue by stefanw1337** [moonlight-stream/moonlight-qt#411]
I have issues when using dual monitors and Synergy. So when I go from one monitor(PC) to the one running moonlight, it will instead of going to the first monitor, just go to the moonlight window. 
I know this is a very nishe problem, but it's still a problem for me.

More in-depth description: Let's say you have three monitors, two of which are on the PC you need to use moonlight(middle, and right monitor). And one is another PC/monitor(left). When you then come from this single-monitor PC, and to the PC running moonlight, it will instead of going to the middle monitor, it will go straight to the right one. So eventhough there's a middle monitor, and moonlight is in a window-window, you can't use the middle monitor until you minimize the moonlight window.

And in addition to this, there's mouse issues when coming into the right-most monitor(running moonlight), the mouse get's stuck 1/3rd of the monitor, and you have to wiggle the mouse left and right to gain the entire window back for using the mouse on. It's very weird.

**Comment by cgutman** [comment]
This is probably because Moonlight captures the mouse. Many games don't work properly without the mouse captured, since they use it as a relative input device.

If you want to disable mouse capture, check the "optimize mouse for remote desktop" option.

**Comment by stefanw1337** [comment]
Wouldn't that cause issues with games? I'm using this primarily because of games.
________________________________

**Comment by cgutman** [comment]
It certainly might, depending on the game.

If you want Synergy to do something different on systems with apps/games utilizing pointer capture, you should contact them about that.
