### ISSUE TITLE
RPi4 installation crashes after a couple of minutes

### ISSUE THREAD

**Issue by plimmplamm** [moonlight-stream/moonlight-qt#416]
Hi everyone. I have installed Moonlight on a raspbian OS on RPi4.
So far everything went smoothly but when I start streaming (LAN to PC) at some points I have a black screen and have to restart the RPi.

What do I have to look into?
Where to find reports / logs?

Can you help me? Thanks! Have a nice day!
Plimmplamm

**Comment by cgutman** [comment]
Logs are printed to the console when you start `moonlight-qt` please attach those at least.
