### ISSUE TITLE
Mouse cursor position bugs

### ISSUE THREAD

**Issue by barbaduk** [moonlight-stream/moonlight-qt#417]
Mouse cursor is fine when it’s just an arrow, but when it changes to any other (text, resize windows, etc.) it starts to show wrong position. It started after update to Windows 2004 + Nvidia 451.48 (and Ctrl+Shift+Alt+M doesn't fix anything)

It's even worse in Photoshop, in addition to wrong position, the brush circle is become invisible when in certain sizes (but if you zoom in or out it will apear again).

The photosop thing was there as long as i use moonlight (java version and up to date). But not being able to select text properly is pain in the ass. I'm not consedering to roll back to 1909 (where text indicator was in place), so i hope it can be fixed somehow.

I made a short [video](https://www.youtube.com/watch?v=K3Q6lGOd6-E) where you can see what am i talking about, here are couple of screenshots from it:
[Text cursor](https://i.imgur.com/7Uvp1e0.png)
[Photoshop brush](https://i.imgur.com/dbte80c.png)

**Server PC details**
 - OS: Windows 10 2004
 - GeForce Experience version: 3.20.2.34
 - Nvidia GPU driver: 451.48

**Moonlight settings**
Doesn't matter, tried different version, settings, and resetting to default

**Client PC details**
 - OS: Windows 10 1909
 - Moonlight Version: 2.1.0

**Other Moonlight clients**
It's absolutly the same on Android client.

**Comment by cgutman** [comment]
I've been on Win10 2004 for months, but I only started seeing the bug with GPU driver 451.48. Try rolling back to the 446.14 driver.

The bug is on the host side, so Nvidia will need to fix it in a new driver or GFE update.

**Comment by barbaduk** [comment]
> 
> 
> I've been on Win10 2004 for months, but I only started seeing the bug with GPU driver 451.48. Try rolling back to the 446.14 driver.
> 
> The bug is on the host side, so Nvidia will need to fix it in a new driver or GFE update.

**Comment by CheckYourFax** [comment]
I have this issue still, on latest drivers, a restart on the host side fixes it until something causes it to be "desynced" again.

**Comment by william-bohannan** [comment]
Seeing the same issue, cursor is off, seems to be out to the bottom right a little (about 1cm)..  will try the reboot of host method.

Host OS: Latest Windows 10 + Geforce 1080ti (using a dummy monitor as PC in the shed)
Guest OS: Latest Windows 10

**Comment by cgutman** [comment]
This is a duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/10

Please follow that issue for updates, rather that commenting on this one.
