### ISSUE TITLE
Explanation of statistics overlay?  (re: frame queue delay and average rendering time)

### ISSUE THREAD

**Issue by sofakng** [moonlight-stream/moonlight-qt#418]
Can anybody give me a description of the values on the statistics overlay?

Average receive time I'm assuming is network latency.
Average decoding time sounds like the time it takes for the client to decode the H264/H265 stream.

What is Average frame queue delay?

Also, what is Average rendering time?  I'm also confused because it includes V-sync latency?

**Comment by cgutman** [comment]
Receive time: Time between receiving the first packet in a frame and the last packet
Decode time: Time to decode the video data and receive a decoded frame back
Frame queue delay: Time spent delaying frames received too early, waiting for the renderer to finish drawing the previous frame, or holding/discarding extra frames received (ex: 59.94 Hz client vs 60 Hz server)
Rendering time: Time spent rendering the frame and waiting for the frame to be swapped on-screen (V-sync)
