### ISSUE TITLE
resolution not being set when launching a game

### ISSUE THREAD

**Issue by freshgregor** [moonlight-stream/moonlight-qt#42]
**Describe the bug**
GFE is not setting the correct resolution when launching a game. It is launching my monitor resolution (3440 x 1440) instead of what I pick in moonlight.

**Steps to reproduce**
launch moonlight for pc on any pc (surface laptop, msi gs63vr, dekstop pc.

**Screenshots**

**Moonlight settings (please complete the following information)**
standard 1080p setting in moonlight. reduced to 8 Mbits for online streaming

**Client PC details (please complete the following information)**
 moonlight version 0.02
windows 10 enterprise edition (surface pro) all others windows pro

**Logs (please attach)**
attached
[Moonlight-1534387482.log](https://github.com/moonlight-stream/moonlight-qt/files/2292334/Moonlight-1534387482.log)

**Additional context**
everything works fine except i have to manually set the resolutuion once in game to avoid stretching and shrinking from the 3440 x 1440 local resolution.

**Comment by cgutman** [comment]
From the launch URL in the log, it looks like you're trying to stream at some odd native resolution: 2256x1504

When you stream at resolutions that aren't officially supported by GameStream, it won't change the resolution to match. Similarly, if you uncheck the "Optimize Game Settings" checkbox, it will also not change the resolution to match.

In your bug report, you mention that you're streaming at 1080p. Can you double check that and whether "Optimize Game Settings" is checked or unchecked?

**Comment by michaeldperlo** [comment]
I’m having what I believe is the same issue:

 I have a 21:9 display and no matter how I fiddle with both the host and client resolution settings, Moonlight always streams at 21:9. On my Android phone, the host image is always stretched vertically to fill the client screen. On my iPhone I can set a custom resolution of 3440x1440 and it will display my host screen accurately (with letterboxing on top and bottom), however, if I select any 16:9 resolutions the image is squished with pillar boxing. With Steam Link when I connect on either Android or iOS it automatically adjusts the host resolution to 16:9, which then displays perfectly on my clients. Am I doing something wrong?

**Comment by cgutman** [comment]
If you’re experiencing a scaling issue specific  to the Android client, please file an issue on the Android client repository.

**Comment by michaeldperlo** [comment]
It isn’t really specific to Android because it happens on both my Android and iOS phones. It seems like it’s something with the host program not changing the resolution of the screen regardless of which option is chosen (720p, 1080p, custom 21:9 res) when the client connects to it. I did notice that it randomly works on one game — Forza Horizon 4 — but nothing else that I’ve noticed.

**Comment by cgutman** [comment]
Lets carry on discussion in #784
