### ISSUE TITLE
Mac os version work with micro lags, very bad!

### ISSUE THREAD

**Issue by GreypaX** [moonlight-stream/moonlight-qt#420]
i have iMac 2019 and CPU core i9 9900k, 32 gb DDR memory, video: Radeon Pro 580X 8gb., Ethernet 1000 mbps.

in bootcamp (windows 10) Moonlight works very good 4K and 60 FPS! in the Mac OS very bad, i have micro lags, not stable FPS! why? Also i tested moonlight in iOS and there all good, stable 60 fps with 1920p.

**Comment by cgutman** [comment]
Duplicate of #414
