### ISSUE TITLE
Black screen over Internet, every thing ok on LAN

### ISSUE THREAD

**Issue by Tomp0uce** [moonlight-stream/moonlight-qt#423]
Hi,
I'm experiencing a bug it seems and after hours of tries I didn't manage to fix it.
I use my gaming PC as moonlight server.
When I stream at home from this PC, on the same LAN, to my shield, or my laptop or my phone, everything is working fine, I have absolutly no problem.
But as soon as I try to stream over the internet, on my laptop I obtain a white screen after the launch of the stream and on my smartphone I obtain a black screen. I tried with wired, wifi or 5G connection (every connection was very good according to speedtest)
All my port are forwarded on my router, Moonlight Internet Hosting Tool v5.0 says every thing is okay and my pc is ready for streaming over the internet. 
The server is well detected over the internet by each device, I can launch the game on the client, it launch it on the server, but the black/white screen remain. And the weirdest is that the mouse input on the client are well transfered to the server (tested with my phone on 5G network). 
It seems that just the image is not streamed to the client over the internet while it is on LAN.
I tried to deactivate my firewall without any further success.

Thank you for your help!
Best regards

**Comment by cgutman** [comment]
You can get logs from Android, but you will need to connect your phone to a PC via USB (unless your phone is rooted).

Here is a tutorial (which I haven't tried but it looks correct at first glance): https://android.gadgethacks.com/how-to/android-basics-capture-logcat-for-detailed-bug-reports-0167774/

**Comment by Tomp0uce** [comment]
[Moonlight-1598806566.log](https://github.com/moonlight-stream/moonlight-qt/files/5147155/Moonlight-1598806566.log)
Thank you @cgutman for your help.
Finally, I used my phone as 4G+ modem for my laptop to test it on windows. You could find enclosed the log of the moonlight session. I manage to connect to the server and to control the mouse cursor but I had no image only a white screen. 
there seems to be a lot of  Unrecoverable frame on the log

**Comment by cgutman** [comment]
Yeah, looks like extreme packet loss on both audio and video streams. Your client is only successfully receiving 1 or 2 of the tens or hundreds of packets in each frame.

Your log also shows your video bitrate is way way too high (86 Mbps).  Start at 5 Mbps and see how that does.

What's the upload speed of your host PC's internet connection?

**Comment by Tomp0uce** [comment]
[Moonlight-1598820555.log](https://github.com/moonlight-stream/moonlight-qt/files/5147437/Moonlight-1598820555.log)
Here is the log with low settings (720p / 30fps / 5Mbps)

Host Speedtest : Ping : 3ms / Down : 943 Mbps / up : 465Mbps

Client Speedtest (laptop with shared connection from smartphone) : Ping : 18ms / Down : 196 Mbps / up : 13.05Mbps
And when I initially posted my message my client speedtest (laptop with wired connection) was around :  Ping : 10ms / Down : 200 Mbps / up : 100Mbps

**Comment by cgutman** [comment]
Yeah still looks like horrible packet loss. Maybe there's a switch or router along the way that doesn't like the traffic pattern of GameStream? I've seen some switches and Powerline networking adapters cause issues like this.

Moonlight should terminate the connection under those severe packet loss conditions, but it didn't because you received some video packets, just never a full video frame. After 2e87f5ff857f9bdc3a475ac03b10797d4534b70d, it will terminate the connection with a "connection unstable" warning rather than just sitting at the black/white screen.

Since that issue is fixed, I'm going to close this issue since Moonlight is working as expected under the severe packet loss conditions. For further connection support, our Discord is the your best bet.
