### ISSUE TITLE
Portable Version - Location where host and other settings are saved

### ISSUE THREAD

**Issue by somerandomperson123** [moonlight-stream/moonlight-qt#43]
From what I understand currently all settings and host information is saved to Windows registry. 

This means if I run the portable version on say a USB drive and connect to my PC the next user can simply install moonlight and connect unless I manually delete host settings. Likewise if that user changes any other settings such as changing hosts or changing other program settings would be carried over. 

I'm wondering if this can be changed to within the application folder to be more truly portable?

**Comment by cgutman** [comment]
The settings are written to your user hive of the registry, so they would only be accessible to users that share your user account. Other user accounts on the system would have their own Moonlight settings, pairing, hosts, etc. That goes for the installable version and the current portable version.

However this isn't ideal for the portable version, for cases like public shared computers or just having Moonlight on a USB stick to use on whatever computer you have.

I agree that the settings should be stored alongside the portable version. I will try to get this change in for Alpha 3.

**Comment by shodanx2** [comment]
Hi,
Where are the setting and pairing information stored ?

I have a strange situation where I need to run moonlight.exe from a specific working folder or else it will claim the client is not paired

This in case 

These commands work and connect without issue
```
D:\guest\winkit\installs\MoonlightPortable>start "" "moonlight.exe" --display-mode windowed --absolute-mouse --resolution 1920x1080 --fps 60 stream joputer.lan desktop

D:\guest\winkit\installs>powershell -NoProfile -Command "$target='joputer.lan'; $app='desktop'; $args='--display-mode windowed --absolute-mouse --resolution 1920x1080 --fps 60'; $exe='MoonlightPortable\\moonlight.exe'; Start-Process -FilePath $exe -ArgumentList \"$args stream $target $app\" -WorkingDirectory $PWD"
```

While the following commands, return a client not paired error, which is baffling !
```
D:\guest\winkit\installs>start "" "MoonlightPortable\moonlight.exe" --display-mode windowed --absolute-mouse --resolution 1920x1080 --fps 60 stream joputer.lan desktop

D:\guest\winkit\installs\MoonlightPortable>powershell -NoProfile -Command "$target='joputer.lan'; $app='desktop'; $args='--display-mode windowed --absolute-mouse --resolution 1920x1080 --fps 60'; $exe='moonlight.exe'; Start-Process -FilePath $exe -ArgumentList \"$args stream $target $app\" -WorkingDirectory $PWD"
```

<img width="1618" height="797" alt="Image" src="https://github.com/user-attachments/assets/d3ac8a30-96de-4d89-be46-625672863ec8" />

In effect, I have to start moonlight from OUTSIDE its folder, specifically it's parent folder, or else it complains that the client is not paired

I tried also another outside folder, and this ALSO connects without a hitch
```
D:\guest\winkit>powershell -NoProfile -Command "$target='joputer.lan'; $app='desktop'; $args='--display-mode windowed --absolute-mouse --resolution 1920x1080 --fps 60'; $exe='installs\MoonlightPortable\\moonlight.exe'; Start-Process -FilePath $exe -ArgumentList \"$args stream $target $app\" -WorkingDirectory $PWD"
```

This is strange !  

As far as I can tell, there are no pairing files in the current folder where it works. It seems to not work ONLY in the MoonlightPortable folder ?! 
I don't understand why that is !
