### ISSUE TITLE
Add aspect ratio setting

### ISSUE THREAD

**Issue by madrobby** [moonlight-stream/moonlight-qt#430]
**Is your feature request related to a problem? Please describe.**
My Gaming PC renders in 2560x1440 (16:9) and but my MacBook Pro 13" has a 16:10 screen (afaik). The full-screen rendered image is squished and things are stretched vertically.

**Describe the solution you'd like**
Allow me to set a aspect ratio in the settings and add black bars when necessary. (Note: Steam does this when streaming from the same computer).

**Describe alternatives you've considered**
I don't know, get a different laptop? :)

**Comment by madrobby** [comment]
> Can't you just select 1440p in Moonlight?

No, that resolution is not available.

**Comment by cgutman** [comment]
That's one of the always available resolutions. Please screenshot your resolution drop-down in Moonlight settings.
