### ISSUE TITLE
Steam Link: audio stuttering, log message: SDL Info (0): Too many queued audio frames

### ISSUE THREAD

**Issue by igno2k** [moonlight-stream/moonlight-qt#431]
**Describe the bug**
I'll get audio stuttering on the steam link device with moonlight. Tested different steam link devices, settings, GFE versions and TVs.

**Steps to reproduce**
Play for a while and get audio stuttering on different games. Some games/applications do not to have this problem.

**Affected games**
Examples: Rocket League, Lego Worlds

**Other Moonlight clients**
No problem with Linux Client or Android Client.

**Moonlight settings (please complete the following information)**
1080p/60fps/40MBit
vsync off
5.1 Audio
decoding auto

Tried to lower settings to 30 MBits and stereo audio without luck.

**Client PC details (please complete the following information)**
 - OS: Latest stable Steam Link build
 - Moonlight Version: 2.1.0

**Server PC details (please complete the following information)**
 - OS: Latest Windows 10 build (stable) - had this issue also with older Windows 10 versions
 - GeForce Experience version: latest stable - had this issue also with older versions
 - Nvidia GPU driver: latest stable - had this issue also with older versions

**Moonlight Logs (please attach)**
log from /tmp/moonlight.log attached
[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/5112043/moonlight.log)

**Comment by igno2k** [comment]
Update:
The issue is definitely related to USB driver or subsystem. Using two controller connected via Bluetooth (XBOX One S + PS4) are working flawlessly. Switching to an USB connected controller (XBOX 360 with wireless adapter, XBOX One S connected via USB) is causing audio stuttering. Streaming needs to be restarted and USB controller disconnected, to work again.

Is it possible to get more debug output from moonlight to further investigate in this issue? I don't see any other related log entries in moonlight.log, dmesg output or other system logs.

**Comment by cgutman** [comment]
What sort of logging are you looking for? Moonlight's logs are already pinpointing the problem: audio playback is too slow for the rate of the incoming audio stream. To get more detailed performance information, you'll need to use something like the Linux `perf` tool.

**Comment by igno2k** [comment]
I think we can close this. I have still no real resolution for this. Since it is working flawlessly with a bluetooth controller (like XBOX One) I am happy :)

**Comment by dewedin** [comment]
Old closed issue but wanted to confirm this audio stutter occurs in Moonlight 6.1.0 on Steam Link hardware while using a USB dongle for my controller. Switching my controller to Bluetooth completely solved it. I suspect the root cause is something to do with the high USB polling rate of my controller that perhaps the setup can't cope with.
