### ISSUE TITLE
"audio-on-host" not working

### ISSUE THREAD

**Issue by tadly** [moonlight-stream/moonlight-qt#435]
**Describe the bug**
The cli option `--audio-on-host` doesn't work.
As soon as I connect the session, the host audio-output device switches from my preferred one to NVIDIA

**Steps to reproduce**
Connect to a host using the `--audio-on-host` option.

**Affected games**
I am connecting to the host via `mstsc.exe`

**Other Moonlight clients**
On Android it works as expected.
[moonlight-embedded](https://github.com/irtimmer/moonlight-embedded/) works too.

**Moonlight settings (please complete the following information)**
Default settings.

**Client PC details (please complete the following information)**
 - OS: Ubuntu 20.04
 - Moonlight Version: 2.1.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 1909
 - GeForce Experience version: 3.20.4.14
 - Nvidia GPU driver: 452.06

**Moonlight Logs (please attach)**
https://paste.ubuntu.com/p/F6rqWMXZHm/

**Comment by cgutman** [comment]
The local audio playback mode is only an attribute that can be adjusted when the streamed app is first started. In your log, you have resumed an active stream, rather than starting a new one. You need to quit the streamed app and launch it again for the audio to play on the host machine as expected.

I verified locally that the `--audio-on-host` option does work when starting a fresh session from the terminal. Notably in the `/launch` URL, you will see `localAudioPlayMode=1`.

**Comment by tadly** [comment]
Huh.. Interesting. I just restarted the PC and tried again with the same thing happening.
In the log I see `localAudioPlayMode=0` which would explain the issue.

My command is:
```sh
$ moonlight stream --1080 --no-vsync --fps 60 --bitrate 50000 --display-mode borderless --quit-after --no-game-optimization --audio-on-host --no-frame-pacing tadly-gamer Desktop
```
And the resulting log: https://paste.ubuntu.com/p/M66JBXrK7S/

What version of moonlight do you have?
Did you test with `mstsc.exe` or a game?
Do you see anything wrong with my command that would affect audio-streaming?

**Comment by tadly** [comment]
Found it (kinda).

It's either a issue with snaps or the commandline-parser is kinda borked.

Changing the UI settings to "play audio on the host" works.
Because I use moonlight exclusively through CLI on my HTPC, I only launched the UI for initial pairing and did everything else
through CLI args.

This bug-report is still valid from my POV

**Comment by cgutman** [comment]
If you remove the v2.1.0 snap and install the edge snap with `snap install --edge moonlight` does the issue still happen?

**Comment by cgutman** [comment]
Nevermind, I figured out the bug. I'm not sure how it ever worked in our testing.

Once the next build of the Snap's edge channel runs, you should be able to test the fix locally.

**Comment by tadly** [comment]
> I'm not sure how it ever worked in our testing.

Maybe because the config-file had `hostaudio=true` set.
For cli testing, it's probably best to use a blank config

Anyways, thanks for the quick fix :)
