### ISSUE TITLE
multi-client co-op (like PS4's 'share play' mode)?

### ISSUE THREAD

**Issue by michaelpalumbo** [moonlight-stream/moonlight-qt#436]
Hi! I'm wondering if more than one client can connect, such that I could play a couch co-op game with a remote friend? See [PS4's share play](https://www.playstation.com/en-ca/explore/ps4/share-play/) for reference. Cheers!

**Comment by cgutman** [comment]
GeForce Experience doesn't support this, however there is an experimental server for Moonlight that does - https://github.com/loki-47-6F-64/sunshine
