### ISSUE TITLE
Controller issues when streaming

### ISSUE THREAD

**Issue by acfin** [moonlight-stream/moonlight-qt#437]
I've tested this with DS4 and Xbox One controllers, both bluetooth and wired. When streaming, the dpad is not properly inputted. It's hard to describe exactly what is wrong. When I press a direction on the d pad, the opposite direction is also immediately inputted somehow. But only on the top and bottom inputs, the left and right ones seem to work fine. Unfortunately this makes some games unplayable.

**Comment by cgutman** [comment]
What OS version is running on your client? What version of GeForce Experience is installed on your host?

Does the d-pad work correctly to navigate the Moonlight UI like the app list? If so, that indicates something is wrong on your host PC.

Usually this is a problem with Steam's controller remapping support on the host. Make sure that is disabled.

Try [streaming your full desktop](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop), opening https://html5gamepad.com in your browser, and testing the gamepad there to see if the buttons are mapped correctly.
