### ISSUE TITLE
  HUAWEI TV unable to connect not available   ，HarmonyOS1.0.1.32,Can install , cannot connect 

### ISSUE THREAD

**Issue by wtugug** [moonlight-stream/moonlight-qt#439]
HUAWEI TV unable to connect not available   ，HarmonyOS1.0.1.32,Can install , cannot connect

**Comment by cgutman** [comment]
Please do not file multiple issues for the same problem.

This is a duplicate of https://github.com/moonlight-stream/moonlight-android/issues/877
