### ISSUE TITLE
Please make a gyroscopic mouse support to android

### ISSUE THREAD

**Issue by zeekei** [moonlight-stream/moonlight-qt#440]
This will be useful in where you can play fps games with gamepad and use a gyroscope input as a mouse from your android device. This combination will be great and most modern mobile fps games use this as they can move arround faster, so why not make an support for this, to connect it with your android device to PC. This will be a game changing, i already look some apps that can control the mouse of your PC using gyroscope input in android. I would like to see this in your creation. Thankyouu!!

**Comment by cgutman** [comment]
It looks like you already filed an issue for this https://github.com/moonlight-stream/moonlight-android/issues/879

Closing this as a duplicate
