### ISSUE TITLE
Cannot start moonlight connection when connected to VPN

### ISSUE THREAD

**Issue by MrBenFTW** [moonlight-stream/moonlight-qt#442]
`Moonlight version: 2.2.0`

During my free time I like to play games at college as I'd normally go home however I have to get the bus and so I'm stuck here for up to 5 hours when I have only 1 class.

Anyways, my college has a strict wifi network with fortinet firewalls. However, I have managed to create myself a vpn (I'm a developer myself) for my laptop which can bypass the schools restrictions. My GPU server shows up in moonlight as available, I click a game and it does the handshake and everything. However just before it launches full screen, I get error 60. Which indicates my Mac isn't letting it connect due to a firewall issue.

However, when connected to my phone over 4g, it works fine. Not sure what is going on, parsec does not work either and gives a sTUN error which I believe might be because my VPN is using tunnels. 

Microsoft remote desktop which does not work without the vpn works with the vpn enabled and connects and works perfectly well so not sure why moonlight would be different?

<img width="1392" alt="Screenshot 2020-09-15 at 10 35 38 am" src="https://user-images.githubusercontent.com/27426792/93193771-33a9fc80-f73f-11ea-8642-d6ae963bf228.png">
[Moonlight-1600161817.log](https://github.com/moonlight-stream/moonlight-qt/files/5223951/Moonlight-1600161817.log)

**Comment by MrBenFTW** [comment]
[Moonlight-1600161817.log](https://github.com/moonlight-stream/moonlight-qt/files/5223986/Moonlight-1600161817.log)

**Comment by cgutman** [comment]
How is your VPN configured? Is it set up to tunnel all traffic, or is it a split tunnel with just the traffic you specify passing through it?

**Comment by manaboy** [comment]
I get error 10060 when trying to connect to my pc that is connected via proton VPN, it works fine when connecting without VPN, any workaround guys? Just want to remote access my desktop whilst it's connected to VPN for security.
