### ISSUE TITLE
About the addition of H.266 encoding

### ISSUE THREAD

**Issue by Tiexcn** [moonlight-stream/moonlight-qt#446]
The H.266 standard has been released for some time, I wonder if moonlight can think about adding H.266 decoding function? Because this can save a lot of network bandwidth, even if it will increase the workload of the computer. But in contrast, the reduction of network bandwidth will bring a smooth experience, at least the experience under the PC will be great.

**Comment by cgutman** [comment]
It is not just a matter of a new codec being finalized. It must also have support in NVENC, which is obviously contingent on hardware support. Ampere has AV1 decode but not encode, so I suspect Ampere's successor will have AV1 encode, then maybe we can investigate using it (again contingent on software support in GFE)

As it stands, this probably won't be actionable until the next generation of GPUs, so I'll close this.

**Comment by TacticalCheerio** [comment]
With Ada being capable of AV1 encode, has there been any consideration for adding support in moonlight?

**Comment by cgutman** [comment]
Definitely. Nvstreamer.exe appears to have some initial plumbing for AV1, but it doesn't appear to be usable yet. I'll be checking each GFE release to see if/when that changes.
