### ISSUE TITLE
Delete PC button doesn't do anything

### ISSUE THREAD

**Issue by arnath** [moonlight-stream/moonlight-qt#45]
I opened up Moonlight and added my machine. When I right click on the machine, a "Delete PC" option appears but if you click on it, nothing changes and there doesn't appear to be a way to remove a PC.

**Comment by cgutman** [comment]
Please attach logs:

- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux, logs print to the terminal when running via `flatpak run com.moonlight_stream.Moonlight`
