### ISSUE TITLE
Wrong version in SteamLink package

### ISSUE THREAD

**Issue by jjoselv** [moonlight-stream/moonlight-qt#452]
The version inside Steam Link says 2.1, even though I downloaded and put in the USB flash drive the 2.2 version. Is this a bug?

**Comment by Jorys-Paulin** [comment]
Did you power-cycle your Steam Link when plugging in your USB stick? It's required for the Steam Link to copy the new version onto its internal memory.

**Comment by jjoselv** [comment]
Good point, done, thanks :)
