### ISSUE TITLE
Headless streaming tips, don't work

### ISSUE THREAD

**Issue by SubsterNL** [moonlight-stream/moonlight-qt#453]
I didn't know where else to post this. I'm having a lot of trouble with streaming to my android tablet when I turn off my only DP connected gaming monitor, the connection to my android tablet which is then streaming is disconnected. I know people advice to get a HDMI dummy plug which I did (https://www.bol.com/nl/p/hdmi-display-port-dummy-plug-4-k-display-emulator/9200000090918849/)

However I have no clue how to use this plug because my connection to my tablet still disconnects when I turn off my monitor.

Could someone give me some pointer on how to set this up or point me to a guide on how to do this. I've tried everything.

I'm running the latest updated 2004 version of windows 10, Ryzen 5-3600, MSI GTX 1060 Armor, 16 gig ram.

Streaming itself works perfect with audio available and stutterfree streaming. But I would like to turn my monitor off.

**Comment by SubsterNL** [comment]
BTW it even disconnects the streaming when I turn my TV on (which is connected to my PC through HDMI but disabled in nvidia control panel)

**Comment by adzil** [comment]
From my experience Gamestream will close the connection when there's change to the display arrangement (e.g. connecting or disconnecting the display).

**Comment by igno2k** [comment]
Plug in HDMI dummy + your monitor via Display Port. Choose Duplicate/Clone Displays in Windows.

That is what I am using. Working fine when "remote" waking up the PC and monitor is off or monitor goes to sleep mode.

You can then also use tools like gamestream_launchpad ( https://github.com/cgarst/gamestream_launchpad ) to switch resolutions when connecting/disconnection via Gamestream (I use 1080p for streaming and 1440p for Desktop usage).
