### ISSUE TITLE
Changing screen resolution upon connection despite identical resolution settings

### ISSUE THREAD

**Issue by qdrop17** [moonlight-stream/moonlight-qt#454]
Currently I'm using a 4K-screen at 1440p resolution. The thing is: When connection with Moonlight to my gaming-rig, the resolution on the displayport gets adjusted (to 4K output resolution), resulting in the screen going dark temporarily. Of course, this makes it very cumbersome to switch between apps and Moonlight.

The resolution of the stream is 1440p, the resolution of the client is 1440p and the resolution of the host is 1440p.

Steps to reproduce this behaviour:
Try to set a lower-than-native resolution on your client and stream and connect to a stream in full-screen.
When setting the client screen resolution to 4K, the screen isn't changing the resolution.

- This occurs with mstsc.exe.
- The client is using the most recent Windows version (Build 18363) with the most recent (2.2.0) Moonlight version.
- The server is using the most recent Windows version (Build 18363) with the most recent Nvidia-Drivers and Geforce-Experience.

**It seems like it is definitely a client issue, changing the output for some reason. This also does not happen when streaming with Parsec.**

These are the logs:
[Moonlight-1601995486.log](https://github.com/moonlight-stream/moonlight-qt/files/5334628/Moonlight-1601995486.log)

Any help is highly appreciated.

**Comment by cgutman** [comment]
Which PC's screen resolution is being changed? The client running Moonlight, or the host?

**Comment by qdrop17** [comment]
> Which PC's screen resolution is being changed? The client running Moonlight, or the host?

The one on the client running Moonlight.

**Comment by cgutman** [comment]
That's because it's switching into full-screen exclusive mode when the stream starts (which typically improves video latency by 1 frame), as set by the "display mode" option in Moonlight settings. If you don't want that, you can set the display mode to "borderless windowed".

**Comment by qdrop17** [comment]
> That's because it's switching into full-screen exclusive mode when the stream starts (which typically improves video latency by 1 frame), as set by the "display mode" option in Moonlight settings. If you don't want that, you can set the display mode to "borderless windowed".

But why isn't this happening when the client resolution is set to 4K with the same settings (full-screen)? Furthermore, my screen reports a resolution of 1440p. When I connect with Moonlight, this switches to 4K. Despite not having 4K enabled anywhere.

**Comment by cgutman** [comment]
It seems to be choosing 1440p as expected, so I don't think there's a Moonlight bug here.

```
00:00:18 - SDL Warn (0): No matching refresh rate found; using desktop mode
00:00:18 - SDL Info (0): Chosen best display mode: 2560x1440x60
```

I suspect the APIs that SDL is using the under the hood (or the driver itself based on your scaling preferences in NVIDIA Control Panel) are triggering GPU scaling (rather than monitor scaling) where the output is being scaled to native resolution by the GPU and the monitor scaler is not used.

In any case, for fast task switching, borderless windowed is recommended (not just in Moonlight, but [in any game](https://game.info.intel.com/gaming-access/should-you-use-fullscreen-or-borderless-windowed-mode)).

**Comment by qdrop17** [comment]
nice, thank you very much for clarifying.
