### ISSUE TITLE
Gamestream mouse cursor alignment is off

### ISSUE THREAD

**Issue by Triangle345** [moonlight-stream/moonlight-qt#455]
When opening up a text editor or using other text editing applications, its fairly obvious how off the mouse cursor is. A good example would be to open up a text editor and type in two brackets with no space in between like so: '[]'. Try to navigate the mouse cursor and get it between the brackets. Actually, go head, open up gamestream moonlight and attempt to type something between the brackets I made just above :). On my setup it seems like its aligned 10-20px to the left.

**Comment by cgutman** [comment]
This is a driver bug introduced in the 450.x driver series. It's already been reported to Nvidia. You can downgrade to 446.x in the meantime.

**Comment by Triangle345** [comment]
Rolling back the driver to 446 worked.
