### ISSUE TITLE
Intermittent Hitching on version 2.2.0

### ISSUE THREAD

**Issue by Nez-debug** [moonlight-stream/moonlight-qt#456]
Good afternoon,

I've recently moved from Steam Link to Moonlight (on SL hardware) v 2.2.0.

I have my host PC wired in to my router, and the SL also connected direct though also have Moonlight on two mobile devices connected on wireless AC situated a couple of metres away that I've been using to troubleshoot. All devices exhibit the exact same issue despite of what bitrate, resolution or frame rate I set in the client.

I'm hosting on a Windows 10 PC with with the latest game ready drivers and Geforce experience.  

The stream will load and run as expected then 18-20 seconds the stream will hitch for a split second (audio will freeze too) then it continues fine for another specific amount of time.

I've closed out of nearly everything I can on my PC to ensure nothing is running in the background.

I just wonder if this is a known problem with this version? Maybe i will revert back to an older version of the client and try that this evening.

Many thanks

**Comment by manaboy** [comment]
Any luck with older version?


Regards

**Comment by manaboy** [comment]
Have you also checked your connections latency?
