### ISSUE TITLE
Pen Pressure

### ISSUE THREAD

**Issue by Danhanado** [moonlight-stream/moonlight-qt#457]
Would it be possible to add pen pressure when using devices such as the surface pro that has a stylus pen?
This would mean I could use my surface for more taxing apps that utilise graphics tablet features

**Comment by cgutman** [comment]
Unfortunately, the Nvidia GameStream protocol does not support native multi-touch/pen input as of today. If that changes, I'll reopen this.

**Comment by VrTech** [comment]
I saw they support stylus at the moment? Any updates?

**Comment by cgutman** [comment]
This is an Android API. We need support on the GameStream protocol.

**Comment by TangXiaoLin-CN** [comment]
> This is an Android API. We need support on the GameStream protocol.

Hello ,Now Sunshine has added support for multitouch and pens, but currently I am using Surface Pro7 on the latest Moonlight v5.0.1, which allows for multitouch but cannot use pens. Is it possible that Windows Pen support has not been added or is there an issue with my usage?
