### ISSUE TITLE
CLI launch option to specify which display to run on

### ISSUE THREAD

**Issue by matoi974** [moonlight-stream/moonlight-qt#459]
**Is your feature request related to a problem? Please describe.**
When I run Moonlight from CLI, it runs on the primary display and I can't move it to a different one.

**Describe the solution you'd like**
A command-line launch option, such as ``--display \\DISPLAY2``

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by igno2k** [comment]
Is this on Windows/Linux/macOS? On Linux it should run on the active screen you are launching it from (tested with Gnome/Arch Linux).

**Comment by matoi974** [comment]
Not sure about macOS, but on Windows it only seems to start on the primary display, unless I did something wrong.

**Comment by igno2k** [comment]
Have you tried this:
https://answers.microsoft.com/en-us/windows/forum/windows_10-start-winpc/opening-programs-on-second-monitor-not-main/ebc1d56d-8b75-47d4-91b8-64ea71cc206a?auth=1

Sounds a little hacky, but maybe it works.
