### ISSUE TITLE
Brightness not keep while I play on host gamepad- Moonlight PC v0.2.0 (Alpha 2)

### ISSUE THREAD

**Issue by feather7** [moonlight-stream/moonlight-qt#46]
Hello I am ussing new *.exe app. Moonlight PC v0.2.0 (Alpha 2).
Is working very good, but Brightness not keep while I play on host gamepad. This working fine with google chrome plugin app. But not in this exe app.

I play on my notebook in same room like is my PC. So all remote things/controllers I have connected to the PC (not notebook), it means gamepad Xbox one. But when I didnt touch my laptop then after 15minut my brightness fall down. (windows power save actions)

So, if i use my laptop only like monitor, not like remote, then I have to change rules for sleep and etc. in windows.

My idea is change options of *.exe app and disable to pc sleep and sleeping modes. Same rulles like has aplications for movies/videos.

BR

Roman

**Comment by cgutman** [comment]
Yep, I saw this behavior too. I think it should be fixed upstream in SDL but for now, I can work around it.

Are you running in windowed or full-screen when you see this issue?

**Comment by cgutman** [comment]
The issue will be fixed in the next release, but I'm still interested in the answer to the question above about windowed or full-screen.

**Comment by feather7** [comment]
I am using full screen only. I can try windowed if you want next details. :)

**Comment by cgutman** [comment]
Nope, that's okay. I think it would definitely not work in windowed if it wasn't working in full-screen.
