### ISSUE TITLE
Black Screen on any games when starting

### ISSUE THREAD

**Issue by d122082** [moonlight-stream/moonlight-qt#460]
**Describe the bug**
After connecting to machine and launching a game, screen is all black.
PC client v2.2.0
Android client v9.7.1

**attach file is PC client log.**
[NvStreamerCurrent.zip](https://github.com/moonlight-stream/moonlight-qt/files/5394821/NvStreamerCurrent.zip)

**Steps to reproduce**
Trying to connect to a game

**Moonlight settings (please complete the following information)**
Tried changing rendering from software to hardware, no difference

**Server PC details (please complete the following information)**
OS: Windows 10 1809
GeForce Experience version: latest
Nvidia GPU driver: latest

**Comment by cgutman** [comment]
Yeah looks like tons of errors trying to capture a frame from Nvidia's side:
```
#7(W)[2020-10-17 01:13:59,745]=09:13:59={13652}<CaptureThread>    Frame 18 (FBC Frame: 13) capture took long time (1010.97 msec)
#8(I)[2020-10-17 01:14:00,250]=09:14:00={12112}<VideoSender>      Unable to get a frame for 500 ms, timeout at 7000 ms
#9(W)[2020-10-17 01:14:00,522]=09:14:00={13480}<VideoPipeline>    Encode waited 775 ms for a frame, timing out in 5225 ms.
#0(I)[2020-10-17 01:14:00,522]=09:14:00={13480}<VideoEncoder>     Enqueue to encoder thread is in state: STATE_ENQUEUE_FINISH
#1(W)[2020-10-17 01:14:00,528]=09:14:00={14180}<CaptureThread>    Capture waited 782 ms for a frame, timing out in 4218 ms.
#2(I)[2020-10-17 01:14:00,750]=09:14:00={12112}<VideoSender>      Unable to get a frame for 1000 ms, timeout at 7000 ms
#3(W)[2020-10-17 01:14:00,755]=09:14:00={13652}<Fbc7FrameProvide> NvFBC cuda grab frame for frame number 13 took long time (1009.04 msec)
#4(W)[2020-10-17 01:14:00,755]=09:14:00={13652}<Fbc7FrameProvide> FBC reported driver internal error 0xfbcb0003.
#5(W)[2020-10-17 01:14:00,755]=09:14:00={13652}<CaptureThread>    Frame 19 (FBC Frame: 13) capture took long time (1009.1 msec)
#6(I)[2020-10-17 01:14:01,259]=09:14:01={12112}<VideoSender>      Unable to get a frame for 500 ms, timeout at 7000 ms
#7(W)[2020-10-17 01:14:01,523]=09:14:01={13480}<VideoPipeline>    Encode waited 765 ms for a frame, timing out in 5235 ms.
#8(I)[2020-10-17 01:14:01,523]=09:14:01={13480}<VideoEncoder>     Enqueue to encoder thread is in state: STATE_ENQUEUE_FINISH
#9(W)[2020-10-17 01:14:01,527]=09:14:01={14180}<CaptureThread>    Capture waited 771 ms for a frame, timing out in 4229 ms.
#0(I)[2020-10-17 01:14:01,759]=09:14:01={12112}<VideoSender>      Unable to get a frame for 1000 ms, timeout at 7000 ms
#1(W)[2020-10-17 01:14:01,768]=09:14:01={13652}<Fbc7FrameProvide> NvFBC cuda grab frame for frame number 13 took long time (1012.06 msec)
#2(W)[2020-10-17 01:14:01,768]=09:14:01={13652}<Fbc7FrameProvide> FBC reported driver internal error 0xfbcb0003.
#3(W)[2020-10-17 01:14:01,768]=09:14:01={13652}<CaptureThread>    Frame 20 (FBC Frame: 13) capture took long time (1012.14 msec)
#4(I)[2020-10-17 01:14:01,771]=09:14:01={11612}<NvscStreamingSes> Sent QoS info: stream: 0, client Q-score 100, RTD 0, scores(100, 100, 100)
#5(I)[2020-10-17 01:14:02,273]=09:14:02={12112}<VideoSender>      Unable to get a frame for 500 ms, timeout at 7000 ms
```

What games were you trying to play?

**Comment by d122082** [comment]
I 

> Yeah looks like tons of errors trying to capture a frame from Nvidia's side:
> 
> ```
> #7(W)[2020-10-17 01:13:59,745]=09:13:59={13652}<CaptureThread>    Frame 18 (FBC Frame: 13) capture took long time (1010.97 msec)
> #8(I)[2020-10-17 01:14:00,250]=09:14:00={12112}<VideoSender>      Unable to get a frame for 500 ms, timeout at 7000 ms
> #9(W)[2020-10-17 01:14:00,522]=09:14:00={13480}<VideoPipeline>    Encode waited 775 ms for a frame, timing out in 5225 ms.
> #0(I)[2020-10-17 01:14:00,522]=09:14:00={13480}<VideoEncoder>     Enqueue to encoder thread is in state: STATE_ENQUEUE_FINISH
> #1(W)[2020-10-17 01:14:00,528]=09:14:00={14180}<CaptureThread>    Capture waited 782 ms for a frame, timing out in 4218 ms.
> #2(I)[2020-10-17 01:14:00,750]=09:14:00={12112}<VideoSender>      Unable to get a frame for 1000 ms, timeout at 7000 ms
> #3(W)[2020-10-17 01:14:00,755]=09:14:00={13652}<Fbc7FrameProvide> NvFBC cuda grab frame for frame number 13 took long time (1009.04 msec)
> #4(W)[2020-10-17 01:14:00,755]=09:14:00={13652}<Fbc7FrameProvide> FBC reported driver internal error 0xfbcb0003.
> #5(W)[2020-10-17 01:14:00,755]=09:14:00={13652}<CaptureThread>    Frame 19 (FBC Frame: 13) capture took long time (1009.1 msec)
> #6(I)[2020-10-17 01:14:01,259]=09:14:01={12112}<VideoSender>      Unable to get a frame for 500 ms, timeout at 7000 ms
> #7(W)[2020-10-17 01:14:01,523]=09:14:01={13480}<VideoPipeline>    Encode waited 765 ms for a frame, timing out in 5235 ms.
> #8(I)[2020-10-17 01:14:01,523]=09:14:01={13480}<VideoEncoder>     Enqueue to encoder thread is in state: STATE_ENQUEUE_FINISH
> #9(W)[2020-10-17 01:14:01,527]=09:14:01={14180}<CaptureThread>    Capture waited 771 ms for a frame, timing out in 4229 ms.
> #0(I)[2020-10-17 01:14:01,759]=09:14:01={12112}<VideoSender>      Unable to get a frame for 1000 ms, timeout at 7000 ms
> #1(W)[2020-10-17 01:14:01,768]=09:14:01={13652}<Fbc7FrameProvide> NvFBC cuda grab frame for frame number 13 took long time (1012.06 msec)
> #2(W)[2020-10-17 01:14:01,768]=09:14:01={13652}<Fbc7FrameProvide> FBC reported driver internal error 0xfbcb0003.
> #3(W)[2020-10-17 01:14:01,768]=09:14:01={13652}<CaptureThread>    Frame 20 (FBC Frame: 13) capture took long time (1012.14 msec)
> #4(I)[2020-10-17 01:14:01,771]=09:14:01={11612}<NvscStreamingSes> Sent QoS info: stream: 0, client Q-score 100, RTD 0, scores(100, 100, 100)
> #5(I)[2020-10-17 01:14:02,273]=09:14:02={12112}<VideoSender>      Unable to get a frame for 500 ms, timeout at 7000 ms
> ```
> 
> What games were you trying to play? Do you have a monitor connected?

I tried Remote Desktop(mstsc.exe) and The Division 2.
They have same symptoms -> Black screen.

**Comment by d122082** [comment]
Hi there
I have  monitor connected.
Tested Game: The Division 2, mstsc.exe

**Comment by d122082** [comment]
Hi all

Sorry about my mistake, this is an user error.
My server PC connect to a Amplifier and the Amplifier connect to my monitor.
I found my Amplifier changed it input to another channel, so it make the Moonlight black screen, just like no connect a monitor.
Thanks for the advice.
