### ISSUE TITLE
Xbox Wireless suddenly stops with Steam Link Moonlight 2.2.0

### ISSUE THREAD

**Issue by SimStm** [moonlight-stream/moonlight-qt#464]
Hi. I have discovered recently that Moonlight works with Steam Link Hardware, so I decided to try out.

When I start playing, everything works well and seamless. My Xbox Wireless Adapter connected to the Steam Link USB and the controller synced correctly. During the play (usually after some minutes) the Xbox controller suddenly stops syncing (and the USB adapter keeps the "sync light" on) and only after restarting the Steam Link the controller works again. This happens with any game I try.

Also, I've noticed that the last time I tried, my Steam Controller USB stopped working too. Maybe some failure in Moonlight made all the USB ports to fail?

I don't have the same problem playing through the Steam Link mode, only through Moonlight.

I'm using the Steam Link hardware (latest beta version - build 782), with Moonlight v2.2.0.
In my PC, I have the latest Nvidia drivers and GeForce Experience software installed.

How can I obtain the logs from Steam Link's Moonlight? Maybe it'll be useful to discover the problem.

Thanks!

**Comment by cgutman** [comment]
I doubt that anything Moonlight could do would break your USB ports (unless there is an OS bug). Something is probably causing the xow daemon that runs your Xbox controllers to crash.

Perhaps the xow folks would have an idea of some logs you could collect or something? I'd start there https://github.com/medusalix/xow

**Comment by cgutman** [comment]
If they do in fact indicate that it's something Moonlight specifically is doing to crash it, feel free to reopen this bug.
