### ISSUE TITLE
gamepad-tool crashed on my macos 10.15, is there any way I can update the sdl2 gamepad mapping?

### ISSUE THREAD

**Issue by coolhihi** [moonlight-stream/moonlight-qt#468]
Is there a folder in moonlight I can update or create `gamecontrollerdb.txt`?

**Comment by btorresgil** [comment]
Not sure if this helps for your situation, if not maybe it helps others.

My issues was I wanted to use the new Xbox Series X gamepad. It's not mapped in the `gamecontrollerdb.txt` included with Moonlight, but it is mapped in the latest `gamecontrollerdb.txt` here:  https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

So I downloaded the new `gamecontrollerdb.txt` from that site and put it in a directory. The only way I could figure out to make Moonlight use it is to start Moonlight from the directory with the file. For example, here's what I did on my Mac:

```shell
$ mkdir gamepad-mapping
$ cd gamepad-mapping
$ curl -o gamecontrollerdb.txt https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txt
$ /Applications/Moonlight.app/Contents/MacOS/Moonlight
```

This example downloads the newest mapping into a directory called `gamepad-mapping` and starts Moonlight with that directory as the working directory, thus loading the new `gamecontrollerdb.txt` file. You can check the Moonlight log to verify it loaded the new mapping file.

Sadly, none of this helps you load gamepad-tool on MacOS 10.15, but you'll probably have to ask elsewhere for help with that. If you can get or create the mapping, this will at least help you load it in Moonlight.

**Comment by coolhihi** [comment]
@btorresgil Thanks.

**Comment by mac-iek** [comment]
Hi,

I found the original Moonlight gamepads mapping file in `~/Library/Caches/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt`, but the list was quite short, so I tried to download the longer list from https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt.

Unfortunately, my gamepad isn't supported yet. It's a [SteelSeries Nimbus+](https://steelseries.com/gaming-controllers/nimbus-plus), a dedicated pad for Apple, and it works great with Apple TV, but I can't run it with macOS.

The gamepad-tool detects a new pad, but I can't run a mapping session, it's just not working.

I tried to replace the ID from the other SteelSeries gamepads (in the file mentioned above), but the mapping is quite weird (arrows works fine, but jumping, running etc in Cyberpunk doesn't work well)

The detected ID is: `05000000556e6b6e6f776e204e696d00`

I'm running macOS 11.2 (Big Sur) on MacBook Air (2020, with M1).

Could you please post the correct mapping for this pad or propose another solution?

**Comment by ollidiemaus** [comment]
Hey there the Problem with the Xbox Series X Controller is that its currently not supported by Mac OS it will be supported in 11.3

**Comment by btorresgil** [comment]
> the Problem with the Xbox Series X Controller is that its currently not supported by Mac OS it will be supported in 11.3

@ollidiemaus It works fine on my MacOS 10.15.7
