### ISSUE TITLE
About translation contribute

### ISSUE THREAD

**Issue by bnk159hair** [moonlight-stream/moonlight-qt#469]
**Is your feature request related to a problem? Please describe.**

Hello, we are Korean university students. This project is an area we are interested in, so we would like to contribute.
We want to contribute through the Korean translation of the project. Is it okay to contribute?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cgutman** [comment]
Yes, you can absolutely contribute translations. We use the standard Qt methods for localization (Qt Linguist)

https://doc.qt.io/qt-5/linguist-manager.html
https://doc.qt.io/qt-5/linguist-translators.html
