### ISSUE TITLE
PS4 Controller does not accept inputs during rumble/vibrations

### ISSUE THREAD

**Issue by Couls** [moonlight-stream/moonlight-qt#470]
**Describe the bug**
If the controller vibrates during gameplay it'll ignore any inputs during the vibration and a bit after its stopped

**Steps to reproduce**
Plug in PS4 Controller through USB or through bluetooth and have moonlight detect it and emulate it as an Xinput controller, play any game with motor feedback and you'll notice that you can't do anything while the controller is vibrating

**Affected games**
Every game with vibration/controller feedback

**Other Moonlight clients**
Only tested with the windows client

**Moonlight settings (please complete the following information)**
Default settings

**Client PC details (please complete the following information)**
- OS: Windows 10
 - Moonlight Version: 2.20

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - GeForce Experience version: 3.20.5.70
 - Nvidia GPU driver: 457.30

This doesn't happen when running the PS4 Controller through DS4Windows

**Comment by cgutman** [comment]
I have updated SDL to 2.0.14. This library provides Moonlight's controller/mouse/keyboard support.

Please try a portable build and see if the issue persists. https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/36952943/job/t47sg5jl6na7h53a/artifacts
