### ISSUE TITLE
[Request] (Desktop) Change host resolution via Nvidia API to match client set resolution on launch 

### ISSUE THREAD

**Issue by allycatty** [moonlight-stream/moonlight-qt#473]
**The Problem**
I often times swap clients at various resolutions. Even if the client resolution is set to native, on the host it will not change the resolution of the encoded video, rather just the client's borderless window size. 

**The Solution**
For the encoded Nvidia Resolution to change to match that of the client upon launch. 

**The Workaround**
I've been able to do this on the fly manually with the Nvidia Control Panel however; this does not work via the Windows native resolution settings. 

**Additional context**
I've been trying to figure out how to make a veryyy simple exe to set in Nvidia Experience, that changes the encoded resolution via the Nvidia SDK. With my limited understanding of the dev kit it's proven difficult. 
_On a personal note - I love Moonlight soooo much!! I mostly use it as a remote desktop on my LAN and it's totally changed my workflow for the better, thank you soooo much for all the effort y'all have put into this project!! <3_

**Comment by igno2k** [comment]
Have you tried this:
https://github.com/cgarst/gamestream_launchpad

**Comment by allycatty** [comment]
> Have you tried this:
> https://github.com/cgarst/gamestream_launchpad

Exactly what I was trying to make on my own. Perfect thank you!!
