### ISSUE TITLE
Add Multiple PC support

### ISSUE THREAD

**Issue by DisneyGaming** [moonlight-stream/moonlight-qt#474]
As the title Says allows the end-user to have multiple paired systems linked to Moonlight. This could allow for easier troubleshooting across systems for example from a Cloud Hosting machine to an office PC. Also, that would seem dumb it would add quite a lot to those who have multiple systems and plan to use to use Moonlight as a Primary Connection Driver

**Comment by cgutman** [comment]
This is already supported.
