### ISSUE TITLE
Improve efficiency on Mac with apple silicon

### ISSUE THREAD

**Issue by chou0212** [moonlight-stream/moonlight-qt#477]
Both the moonlight-qt and moonlight-ios are works well on my Macintosh with apple silicon, But it consumes a lot of power, more than my old device.  Should I try and other versions or waiting for Apple to resolve?

**Comment by cgutman** [comment]
How are you measuring that it consumes more power?

While Moonlight is still running on Rosetta, most of the CPU-intensive processing is taking place in VideoToolbox code (VTDecoderXPCService) which is native ARM64 code. The one place that might benefit from native ARM64 code a little bit is the Opus audio decoding, but Opus is so easy to decode that you can do it on a Raspberry Pi. The M1 has so much more performance that it should make quick work of even poorly optimized x86-to-ARM64 translated Opus code. I don't expect a Universal binary to have much visible performance/efficiency impact.

**Comment by chou0212** [comment]
> How are you measuring that it consumes more power?
> 
> While Moonlight is still running on Rosetta, most of the CPU-intensive processing is taking place in VideoToolbox code (VTDecoderXPCService) which is native ARM64 code. The one place that might benefit from native ARM64 code a little bit is the Opus audio decoding, but Opus is so easy to decode that you can do it on a Raspberry Pi. The M1 has so much more performance that it should make quick work of even poorly optimized x86-to-ARM64 translated Opus code. I don't expect a Universal binary to have much visible performance/efficiency impact.

It consumes over 15% power per hour on 2K@60Hz HEVC decoding, but it takes 8% on my samsung galaxy tab s7 with same settings. I think may be the Snapdragon 865 has much more performance/efficiency. 
thanks for your help.

**Comment by sofakng** [comment]
Which version is recommended for the Apple MacBook M1?  moonlight-qt or moonlight-ios?

**Comment by chou0212** [comment]
> Which version is recommended for the Apple MacBook M1? moonlight-qt or moonlight-ios?

I only know that the moonlight-ios can't be full screen..

**Comment by cgutman** [comment]
I have built a native ARM64 Moonlight build for Windows in https://github.com/moonlight-stream/moonlight-qt/issues/350

The blocker for a similar early preview ARM64 version for macOS is currently that AppVeyor doesn't have Xcode 12 on their macOS images yet (https://github.com/appveyor/ci/issues/3542). Hopefully they will get updated macOS images deployed soon.

> Which version is recommended for the Apple MacBook M1? moonlight-qt or moonlight-ios?

Moonlight Qt is recommended.

**Comment by eiyjam** [comment]
> I have built a native ARM64 Moonlight build for Windows in #350
> 
> The blocker for a similar early preview ARM64 version for macOS is currently that AppVeyor doesn't have Xcode 12 on their macOS images yet ([appveyor/ci#3542](https://github.com/appveyor/ci/issues/3542)). Hopefully they will get updated macOS images deployed soon.
> 
> > Which version is recommended for the Apple MacBook M1? moonlight-qt or moonlight-ios?
> 
> Moonlight Qt is recommended.

Yes，But I hope you can make it native to Apple M1 in the next version，PLS！

**Comment by PolCPP** [comment]
Might be an issue with videotoolbox itself and the root reason of #414. There is a fairly recent issue regarding that on ffmpeg tracker https://trac.ffmpeg.org/ticket/8731 

Specially since it also seems to happen on moonlight-ios i wouldn't blame rosetta.

**Comment by cgutman** [comment]
> Yes，But I hope you can make it native to Apple M1 in the next version，PLS！

As I mentioned, I'm blocked on AppVeyor before I can build the dependencies for my universal binaries. Qt is also not shipping universal macOS binaries until Qt 6.1 ([expected in April](https://wiki.qt.io/Qt_6.1_Release)), so that will also block any official universal Moonlight release.

However, when AppVeyor's macOS image is updated and Qt has an alpha of Qt 6.1 with universal binaries, I will create a preview build and post a link to it here for you all to try.

**Comment by eiyjam** [comment]
> > Yes，But I hope you can make it native to Apple M1 in the next version，PLS！
> 
> As I mentioned, I'm blocked on AppVeyor before I can build the dependencies for my universal binaries. Qt is also not shipping universal macOS binaries until Qt 6.1 ([expected in April](https://wiki.qt.io/Qt_6.1_Release)), so that will also block any official universal Moonlight release.
> 
> However, when AppVeyor's macOS image is updated and Qt has an alpha of Qt 6.1 with universal binaries, I will create a preview build and post a link to it here for you all to try.

OK!Thanks，I still have some question ，I can feel that the stream screen is not soomth in moonlight-qt evidently,I don't mean delay,I've turned on 60Hz streaming,but It's like playing a 60fps game on a 30Hz screen, and It's worse if turning on 30Hz Streming. However the Streaming screen in moonlight-ios is smoother than rosetta , but the moonlight-ios can't be full screen perfectly。Do you have any way to make MacBook with m1 silicon streaming perfectly now？

**Comment by cgutman** [comment]
Those of you having streaming performance/smoothness issues on Apple M1 devices, please give this build a try and let me know if it changes anything - https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/37009322/job/f4db16d79jn3tftj/artifacts

It is _not_ a native Apple Silicon build, but it contains a fix for a video decoding performance issue on Big Sur that may impact the M1 devices too (possibly even more than Intel devices).

**Comment by iAbadia** [comment]
Just tested L4D2 1080p (light load on the host) and I don't see a noticeable difference, comfortable to play at about 50ms delay on both versions. Measured recording with a handheld at 480fps and then counting frames 😄

**Comment by cgutman** [comment]
Here is a native build of Moonlight for Apple silicon - https://drive.google.com/file/d/1KRVMGebMT7tmWIFlS_LOrg6eR4gmWhkw/view?usp=sharing

I don't have an M1 Mac to test with, so I will have to rely on your help for that.

If you can, please test as much as possible from this list and note what you've tested in a comment:
- General streaming performance
- Software and hardware decoding
- V-sync and frame pacing checkboxes on and off
- H.264 and HEVC codecs
- Fullscreen, borderless windowed, and windowed mode
- PS4/PS5 gamepad connected via Bluetooth (including connecting and disconnecting it while streaming)
- Ctrl+Alt+Shift+S (stats overlay) with Moonlight set to software decoding
- Discord integration (it should show that your user is playing Moonlight if you're running Discord on your Mac while streaming)

**Comment by chou0212** [comment]
> https://drive.google.com/file/d/1KRVMGebMT7tmWIFlS_LOrg6eR4gmWhkw/view?usp=sharing
<img width="1440" alt="截屏2021-01-11 下午2 21 45" src="https://user-images.githubusercontent.com/2795904/104151671-96bf4d80-5418-11eb-8679-fb64204b0cea.png">

**Comment by chou0212** [comment]
> Here is a native build of Moonlight for Apple silicon - https://drive.google.com/file/d/1KRVMGebMT7tmWIFlS_LOrg6eR4gmWhkw/view?usp=sharing
> 
> I don't have an M1 Mac to test with, so I will have to rely on your help for that.
> 
> If you can, please test as much as possible from this list and note what you've tested in a comment. It's okay if you don't have time or the hardware required to test everything, just do what you can.
> 
> * General streaming performance
> * Software and hardware decoding
> * V-sync and frame pacing checkboxes on and off
> * H.264 and HEVC codecs
> * Fullscreen, borderless windowed, and windowed mode
> * PS4/PS5 gamepad connected via Bluetooth (including connecting and disconnecting it while streaming)
> * Ctrl+Alt+Shift+S (stats overlay) with Moonlight set to software decoding
> * Discord integration (it should show that your user is playing Moonlight if you're running Discord on your Mac while streaming)

Failed to launch...

errors as follows

Termination Reason:    DYLD, [0x2] Wrong architecture

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtQuickControls2.framework/Versions/5/QtQuickControls2
  Referenced from: /Applications/Moonlight.app/Contents/MacOS/Moonlight
  Reason: no suitable image found.  Did find:
	/Applications/Moonlight.app/Contents/MacOS/../Frameworks/QtQuickControls2.framework/Versions/5/QtQuickControls2: mach-o, but wrong architecture
	/Applications/Moonlight.app/Contents/MacOS/../Frameworks/QtQuickControls2.framework/Versions/5/QtQuickControls2: mach-o, but wrong architecture

Binary Images:
       0x102208000 -        0x1024ebfff +com.moonlight-stream.Moonlight (2.2.0 - 2.2.0) <F0667C05-833F-3D0A-A7F2-3DD8DF3A299E> /Applications/Moonlight.app/Contents/MacOS/Moonlight
       0x102604000 -        0x102693fff +org.libsdl.SDL2-ttf (2.0.15 - 2.0.15) <AD7038D7-9439-3671-A170-514D6A9C7750> /Applications/Moonlight.app/Contents/Frameworks/SDL2_ttf.framework/Versions/A/SDL2_ttf
       0x1026cc000 -        0x102747fff  dyld (832.7.1) <B7DB9E8A-A898-3C11-91A0-2B0264F05CB6> /usr/lib/dyld
       0x1027d0000 -        0x1029bbfff +libavcodec.58.dylib (0) <6F670B3D-0BAF-33FD-9639-E1C7587033D2> /Applications/Moonlight.app/Contents/Frameworks/libavcodec.58.dylib
       0x1029f4000 -        0x102a4ffff +libavutil.56.dylib (0) <3B3CE4C3-6BF6-3FAC-A167-71B83FE94B48> /Applications/Moonlight.app/Contents/Frameworks/libavutil.56.dylib
       0x102c7c000 -        0x102d7bfff +org.libsdl.SDL2 (2.0.15 - 2.0.15) <71628889-9922-3575-A805-7AD0282EEFFA> /Applications/Moonlight.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2
       0x192038000 -        0x192070fff  libobjc.A.dylib (818.2) <A4BC7D83-2CA5-32B1-B1CA-1D1431C04916> /usr/lib/libobjc.A.dylib
       0x1939a9000 -        0x193fcdfff  com.apple.audio.CoreAudio (5.0 - 5.0) <0E6AD3C8-3E90-3CB7-BE25-DDD37AFD1917> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
       0x196d94000 -        0x197381fff  com.apple.CoreGraphics (2.0 - 1463.2.2) <D6C003BF-A49F-37E4-ADE1-31AFA72DDB41> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
       0x198ba8000 -        0x198bfafff  com.apple.CoreVideo (1.8 - 408.4) <B877220F-1199-3F9F-B00E-2DD96231D7DF> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
       0x199b39000 -        0x199c2ffff  com.apple.CoreMedia (1.0 - 2760.6.4.6) <5F17C1F2-DF73-3C8A-B049-E270941A1196> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
       0x19cddf000 -        0x19cf04fff  com.apple.VideoToolbox (1.0 - 2760.6.4.6) <7225282B-0656-37B2-8A61-DC1D4B005000> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
       0x1a4461000 -        0x1a4461fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <E2E442D0-D865-3703-9B74-3C2BE1190D42> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
       0x1adefe000 -        0x1adefefff  com.apple.avfoundation (2.0 - 2000.5.4.2) <546A45E4-BC3D-30E7-8544-5829FD8CD1DA> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation

Model: MacBookAir10,1, BootROM 6723.61.3, proc 8:4:4 processors, 8 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Oct 20 2020 12:49:54 version 18.20.222.14.7.8.100 FWID 01-ba327c2d
Bluetooth: Version 8.0.2f9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Air, Apple Inc., 0.0
Thunderbolt Bus: MacBook Air, Apple Inc., 0.0

**Comment by iAbadia** [comment]
Got the same error. The error is pretty self explanatory but just to confirm it seems like the QtQuickControls2 bundled with the app image is still built for x86.

<img width="908" alt="Screenshot 2021-01-11 at 10 09 09" src="https://user-images.githubusercontent.com/6335213/104167916-14716200-53f5-11eb-95d8-aa86c5ff720c.png">

If I had to guess I'd say that all other bundled Qt libraries suffer from the same issue.

**Comment by cgutman** [comment]
OK, thanks for testing. It looks like it deployed the wrong architecture of Qt into Moonlight.app. I think I've fixed that.

Please try testing again with this version - https://drive.google.com/file/d/1qC-qsnDCUqWqe9yn3lZuCGKedVxxuF-Q/view?usp=sharing

**Comment by chou0212** [comment]
This version is OK.

It shows a "avg decoding time" on stats overlay. and I got 4-6ms whether on HEVC or AVC with hardware decoding. this number could reach 40+ ms in software decoding.

Fullscreen, borderless windowed, and windowed mode got the same performace on M1 Mac.
I'll keep testing other funcs.

**Comment by cgutman** [comment]
> This version is OK.
> 
> It shows a "avg decoding time" on stats overlay. and I got 4-6ms whether on HEVC or AVC with hardware decoding. this number could reach 40+ ms in software decoding.

Is that better, worse, or the same as with the v2.2.0 build running with Rosetta?

**Comment by chou0212** [comment]
> > This version is OK.
> > It shows a "avg decoding time" on stats overlay. and I got 4-6ms whether on HEVC or AVC with hardware decoding. this number could reach 40+ ms in software decoding.
> 
> Is that better, worse, or the same as with the v2.2.0 build running with Rosetta?

Much better than v2.2.0, 4ms VS 8ms,  it's great!

**Comment by PolCPP** [comment]
Didn't try the rosetta one, but getting ~3-4ms at 1920x1200 on a air on this one which is less than the 16" i9

**Comment by cgutman** [comment]
Released beta binaries for ARM64 in v3.0.0. Please leave feedback in this thread.

**Comment by mac-iek** [comment]
I'm using a ARM64 native build on MacBook Air M1 and Cyberpunk 2077 works with native resolution, 60fps and full bitrate (150Mbps) without any problems in LAN.  I'm streaming from I9-990k, 32GB, RTX 2080.

Currently trying to do the same over a WireGuard tunnel (both locations have 300Mbps+ symmetric fiber, less than 12ms latency). I'll keep you posted.

**Comment by mac-iek** [comment]
> Currently trying to do the same over a WireGuard tunnel (both locations have 300Mbps+ symmetric fiber, less than 12ms latency). I'll keep you posted.

I realized that declared Internet speed is a little bit different when it comes to a direct connection. Using `iperf3` I was able to keep a stable ~90Mbps (in both ways), which is more than enough to play smoothly. So, in summary - Moonlight works perfectly on MacBook M1 with a native resolution (2K - 2560 x 1600), 60 fps, and Video Bitrate set to 50Mbps over a WireGuard VPN tunnel.

**Comment by cgutman** [comment]
For the next release, I'm working on a Universal binary for Moonlight.

I've got something that works on my Intel Mac. Could you test this build on your Apple Silicon Macs and let me know how it works?

https://drive.google.com/file/d/177yFueHOcO5frSeMmHIVmeUIFuAtiHtC/view?usp=sharing

**Comment by qfettes** [comment]
I'll test a little now. Is there any log files or metrics you want? Or just a general feel on how it is working compared to 3.0.0? @cgutman

**Comment by cgutman** [comment]
If it works at all, that's a good sign. I guess you could compare the performance with the old 3.0.0 ARM64 build. It should be pretty much identical.

**Comment by vhd** [comment]
Just checked it out. Works identically with the old 3.0.0 ARM64 build. Switching to Rosetta works too.
Here are some "stress tests" vids :)
https://1drv.ms/f/s!AnCo99qPTV5VgedCMgjMI42B0s3Zxg

**Comment by qfettes** [comment]
Activity Monitor reports it as an apple silicon process. System Report identifies it as a universal binary. Like you said, the performance is identical as far as I can tell. I've been streaming civ 6 for about 30 minutes and it's completely stable. 

I forced rosetta emulation and it worked fine. The activity monitor correctly reported the architecture as Intel. My rough estimate is that decode performance was ~19% slower (~3.35ms avg vs. ~2.8ms avg while runing natively) with Rosetta, which makes sense.

**Comment by qfettes** [comment]
This might be a silly question, but I noticed moonlight on the m1 mac utilizes the CPU heavily but doesn't utilize the GPU at all. Could utilizing the GPU to decode improve performance? Since the CPU decoding performs so well as is, maybe there is also a way to split the load between the CPU and GPU such that frames are decoded in an alternating fashion like CPU, GPU, CPU, GPU, etc.

**Comment by cgutman** [comment]
> This might be a silly question, but I noticed moonlight on the m1 mac utilizes the CPU heavily but doesn't utilize the GPU at all. Could utilizing the GPU to decode improve performance? Since the CPU decoding performs so well as is, maybe there is also a way to split the load between the CPU and GPU such that frames are decoded in an alternating fashion like CPU, GPU, CPU, GPU, etc.

Moonlight does utilize the fixed-function decode hardware present on the M1 (and other Macs). Because the M1 has separate areas of the SoC for video decoding (what is typically done by the GPU in other systems), it may not appear as GPU load. Similarly, the GPU load calculation may just be using load on the general purpose ALUs, rather than fixed function hardware like the decoder blocks.

In any case, v3.1.0 is out with official M1 support, so closing this issue now.
