### ISSUE TITLE
Connecting to Windows 10 PC turns on mouse acceleration

### ISSUE THREAD

**Issue by ipkpjersi** [moonlight-stream/moonlight-qt#480]
**Describe the bug**
When connecting to my Windows 10 laptop via Moonlight, mouse acceleration randomly turns on and I have to turn it off every time. I have not experienced this bug with Steam in-home streaming or Parsec.

**Steps to reproduce**
1. Connect to Windows 10 Pc running Moonlight
2. Look at Mouse settings, mouse acceleration is turned on.

**Screenshots**
![](https://i.imgur.com/vgdJo8q.png)

**Affected games**
Everything, anything I connect to turns on mouse acceleration. 

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? 
No.

**Client PC details (please complete the following information)**
 - OS: Ubuntu 18.04 LTS
 - Moonlight Version: v2.2.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 LTSC 1809 
 - GeForce Experience version: 3.20.5.70
 - Nvidia GPU driver: 457.51
 - Moonlight Version: v2.2.0

**Moonlight Logs (please attach)**
[MoonlightLogs.zip](https://github.com/moonlight-stream/moonlight-qt/files/5676459/MoonlightLogs.zip)

**Comment by atticusnari** [comment]
Having this same issue unfortunately :(

**Comment by cgutman** [comment]
This isn’t a behavior that Moonlight controls. It’s GeForce Experience doing it when a GameStresm session is active.

If you’re using Moonlight for Remote Desktop type use cases, activate Remote Desktop mouse mouse in Moonlight settings for 1:1 cursor control between host and clients. 

Alternately, I think somebody has a script pinned on the Discord server that can put your mouse settings back after the stream starts.

**Comment by cgutman** [comment]
Added this to the FAQ too - https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-does-my-hosts-mouse-acceleration-change-while-streaming
