### ISSUE TITLE
Cursor offset issue

### ISSUE THREAD

**Issue by mtwomey** [moonlight-stream/moonlight-qt#482]
This is related to #455 

This is stated as an nvidia bug introduced in the 450.x driver series with the recommendation to stick with nvidia version 446 if you want to avoid it. 

However, we're now 16 versions past 446 and into the 460 series, so it doesn't seem like there is going to be any change in this regard on the nvidia side. Is there a possibility of compensating for this in Moonlight?

**Comment by cgutman** [comment]
It is not possible to compensate in Moonlight. The cursor is included in the video stream from the host, we do not draw it on our side.
