### ISSUE TITLE
GFE error: cannot configure streamer (error 544) after installation of Windows 10 update KB4592438

### ISSUE THREAD

**Issue by GreenTeaBalls** [moonlight-stream/moonlight-qt#483]
**Describe the bug**
After installing the Windows 10 quality/security update KB4592438 on the server PC, Moonlight clients (tested on Windows, Mac OS and Steam Link) fail to connect to Windows 10 server PC running Geforce Experience. Moonlight initially fails with error code 521, every subsequent attempt fails with error code 544.

Issue can be fixed by uninstalling KB4592438 (which isn't really desirable as this is the December 8 batch of security updates for W10).

**Steps to reproduce**
Install KB4592438. 
Try to connect to Windows 10 PC.

**Affected games**
All, no game or remote desktop session can be started.

**Other Moonlight clients**
Affects Windows, Mac OS and Steam Link client. Not tested on Android or iOS.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? **No**

**Client PC details (please complete the following information)**
 - OS: Windows 10 2004, Mac OS 10.15, Steam Link
 - Moonlight Version: 2.2.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 2004
 - GeForce Experience version: 3.20.5.70
 - Nvidia GPU driver: 456.38

**Moonlight Logs (please attach)**
[Moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/5688401/Moonlight.log)

**Comment by cgutman** [comment]
My Win10 2004 host works fine with KB4592438, so this is something specific to your system which you should troubleshoot with the folks  on [Discord](https://moonlight-stream.org/discord).

**Comment by GreenTeaBalls** [comment]
Thanks for checking this, I have let the folks on the Discord know.
