### ISSUE TITLE
Desktop Resolution Change not properly displaying on client

### ISSUE THREAD

**Issue by gregmarut** [moonlight-stream/moonlight-qt#485]
**Describe the bug**
When streaming the desktop (mstsc), resolution changes on the host does not stream to the client correctly. I have a host connected to a 4K monitor and running at 4K resolution. I also have a client running at a much smaller screen and a different aspect ratio 1280x800 (16:10). I understand that Geforce Experience will not automatically change the resolution of the host when streaming the desktop. However, when I manually change the resolution myself, the host is running on the correct resolution but the client is not. To me, it appears as if the client's frame is still the same original size but the picture was just simply been shrunk down to scale.

Both host and client are on Windows 10. Host is running latest Nvidia drivers as of 12/17/2020. Client is running latest moonlight release 2.2.0

As a workaround, I found that if I quit the current session after changing the resolution and connect to Steam BigPicture, then quit that session and return back to streaming the desktop, it appears to work.

**Steps to reproduce**

- Run a host at 4K resolution
- From a client with a native resolution of 1280x800, stream the desktop by running mstsc.exe
- Then change the host resolution to 1280x800 (or any other resolution)

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/11442365/102498920-92398c00-4048-11eb-8f5f-f1155f439eb5.png)
![Screenshot (2)](https://user-images.githubusercontent.com/11442365/102498922-94034f80-4048-11eb-855f-090b4485f536.png)

**Affected games**
mstsc.exe

**Other Moonlight clients**
- Have not tried

**Moonlight settings (please complete the following information)**
- Settings are default

**Client PC details (please complete the following information)**
 - OS: Windows 10 19041.685
 - Moonlight Version: 2.2.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 19042.685
 - GeForce Experience version: 3.20.5.70
 - Nvidia GPU driver: 460.89

**Moonlight Logs (please attach)**
[Moonlight-1608211876.log](https://github.com/moonlight-stream/moonlight-qt/files/5710055/Moonlight-1608211876.log)

**Comment by cgutman** [comment]
If you use Windows Display Settings to change your resolution, the OS is upscaling your chosen resolution to the native display resolution, which results in capture artifacts (because upscaling happens _after_ NVENC has already received the frame).

The trick is to change the resolution from the NVIDIA Control Panel instead. In NVIDIA Control Panel, change resolution back to native, then back to 1280x800. 

If that doesn't work, hop on [Discord](https://moonlight-stream.org/discord) and someone can help.

**Comment by gregmarut** [comment]
This appears to have worked. Thanks
