### ISSUE TITLE
Unable to start streaming via 5210 x 1440

### ISSUE THREAD

**Issue by psydrohne** [moonlight-stream/moonlight-qt#486]
Before my DualQHD resolution, i was able to stream with 2560 x1080.
With my new resolution 5210 x 1440@60 i do no get the monnlight connection established. After a short blank the connection disappears. But when i connect via 4k client resolution, the connection works with a awful compressed desktop view.

host machine i7-4x, 2x970
with headless display dongle for stabilizing the host resolution, configured in nvidia systemcenter
![2020-12-17 20_42_39-NVIDIA Systemsteuerung](https://user-images.githubusercontent.com/25859398/102535789-fbe98280-40a8-11eb-91ca-6ebc5d772a6e.png)

here is my nv-streamer protocol:
if there is no bug in moonlight, i believe the problem was the headless dongle...

> #6(I)[2020-12-17 19:25:37,561]=20:25:37={15760}<NvEnc10VideoEnco> Open encoding session result: NV_ENC_SUCCESS.
#7(I)[2020-12-17 19:25:37,572]=20:25:37={15760}<NvEnc10VideoEnco> HEVC video format selected
#8(I)[2020-12-17 19:25:37,572]=20:25:37={15760}<NvEnc10VideoEnco> Multi-reference is enabled
#9(I)[2020-12-17 19:25:37,595]=20:25:37={15760}<NvEnc10VideoEnco> Encoder initialization result: NV_ENC_ERR_INVALID_PARAM.
#0(E)[2020-12-17 19:25:37,595]=20:25:37={15760}<NvEnc10VideoEnco> Failed to initialize encoder
#1(E)[2020-12-17 19:25:37,595]=20:25:37={15760}<NvEnc10VideoEnco> Encoder not initialized, nothing to free.
#2(I)[2020-12-17 19:25:37,595]=20:25:37={15760}<VideoEncoder>     Error starting encoder.
#3(E)[2020-12-17 19:25:37,595]=20:25:37={15760}<VideoPipeline>    Failed to start: Failed to start the video encoder.
#4(W)[2020-12-17 19:25:37,595]=20:25:37={15760}<NvThread>         Invalid thread handle, thread not started or already quit: CaptureThread (thread id: 00000000)
#5(I)[2020-12-17 19:25:37,595]=20:25:37={15760}<FrameProcessor>   Finalizing Frame Processor
#6(I)[2020-12-17 19:25:37,595]=20:25:37={15760}<VideoFrameProvid> Stopping Fbc7FrameProvider.
#7(I)[2020-12-17 19:25:37,595]=20:25:37={15760}<VideoFrameProvid> Stopped.
#8(E)[2020-12-17 19:25:37,595]=20:25:37={15760}<VideoEncoder>     Encoder already stopped.
#9(I)[2020-12-17 19:25:37,595]=20:25:37={15760}<VideoEncoder>     Deinitialized NvEnc10VideoEncoder.
#0(I)[2020-12-17 19:25:37,595]=20:25:37={15760}<VideoFrameProvid> Deinitializing Fbc7FrameProvider.
#1(I)[2020-12-17 19:25:37,595]=20:25:37={15760}<Fbc7FrameProvide> Destroying FBC object.
#2(I)[2020-12-17 19:25:37,631]=20:25:37={15760}<Fbc7FrameProvide> Unloading FBC library
#3(I)[2020-12-17 19:25:37,631]=20:25:37={15760}<VideoFrameProvid> Deinitialized.
#4(I)[2020-12-17 19:25:37,667]=20:25:37={15760}<AdapterContext>   Deinitialized CUDA context for adapter 0.
#5(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<AdapterContext>   Deinitialized context for adapter 0
#6(E)[2020-12-17 19:25:37,685]=20:25:37={15760}<VideoStreamer>    Failed to start video pipeline for stream::0.
#7(E)[2020-12-17 19:25:37,685]=20:25:37={15760}<VideoStreamer>    Failed to setup encode config for stream:0.
#8(E)[2020-12-17 19:25:37,685]=20:25:37={15760}<NvscStreamingSes> Failed to create video stream 0.
#9(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<NvscStreamingSes> Starting teardown
#0(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<NvscStreamingSes> Quit requested, waiting on child threads to quit
#1(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<StopEvent>        Termination infos:
#2(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<StopEvent>        - Source 'VideoPipeline', reason 'Failed to start: Failed to start the video encoder.', code 0x800E840F NVST_DISCONN_SERVER_VIDEO_ENCODER_INIT_FAILED
#3(I)[2020-12-17 19:25:37,685]=20:25:37={16348}<StreamSdkEvents>  Invoking clientEventCallback NvstEventDetail::NVST_ED_STREAM_ATTEMPT_FAILED: 
#4(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<ClientControl>    Client control thread terminating
#5(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<Etwprof>          Number of delayed commands: 1
#6(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<EnetPeer>         Last ack received: 299 ms ago; Last keep alive: 251 ms ago; Last sent: 251 ms ago; RTT: 118.69 ms; Avg Ack Time: 118.69 ms; Total Reliable Tx :: Attempts: 11; Time-Outs: 0; Re-Tx : 0.00 %
#7(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<EnetPeer>         Next Packet timeout is in 191 ms
#8(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<EnetPeer>         Earliest sent packet timeout reset by ack received 299 ms ago
#9(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<EnetPeer>         Channel 0 :: Incoming Reliable Sequence: 10
#0(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<EnetPeer>         Channel 0 :: Outgoing Reliable Sequence: 8; Largest Acked Reliable Sequence: 8
#1(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<EnetPeer>         Channel 0 :: Incoming queue sizes :: Reliable: 0; Part-Reliable: 0; Unreliable: 0
#2(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<EnetPeer>         Outgoing commands queue sizes :: Reliable queued: 0; Reliable sent but unacked: 0; Part-Reliable queued: 0; Part-Reliable sent but unacked: 0; Unreliable queued: 0; Unreliable sent: 0
#3(I)[2020-12-17 19:25:37,685]=20:25:37={15760}<EnetPeer>         Total aggregated sends: 7; Total send skips due to high reliable packet count: 0; Total send skips due to high partial reliable message size: 0; Average partial reliable message starving period: 0.00 ms; Average send headroom bytes in MTU buffer for partial reliable message: 0
#4(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<ClientControl>    Created termination notification with reason 260312704, and 0 bytes of user-provided data.
#5(I)[2020-12-17 19:25:37,686]=20:25:37={16348}<SciBase>          Sent event StreamAttemptFailed: 
#6(I)[2020-12-17 19:25:37,686]=20:25:37={16348}<StreamSdkEvents>  Invoking diagnosticsEventRaised TerminationReason
#7(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<NvscStreamingSes> ~StreamingStats()
#8(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<VideoStreamer>    Destroying video streamer.
#9(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<VideoPipeline>    Termination_validity_log: Encoder use count = 2
#0(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<VideoPipeline>    Termination_validity_log: Frame Processor use count = 2
#1(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<StreamSdkEvents>  Enqueuing event for stream of type NVST_MT_INPUT: NvstEventDetail::NVST_ED_STREAM_DISCONNECT_INTENTIONAL, message = 'Session quitting.'
#2(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<StreamSdkEvents>  Enqueuing event for stream of type NVST_MT_MIC: NvstEventDetail::NVST_ED_STREAM_DISCONNECT_INTENTIONAL, message = 'Session quitting.'
#3(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<StreamSdkEvents>  Enqueuing event for stream of type NVST_MT_AUDIO: NvstEventDetail::NVST_ED_STREAM_DISCONNECT_INTENTIONAL, message = 'Session quitting.'
#4(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<StreamSdkEvents>  Enqueuing event for stream of type NVST_MT_VIDEO_INTERNAL: NvstEventDetail::NVST_ED_STREAM_DISCONNECT_INTENTIONAL, message = 'Session quitting.'
#5(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<StopEvent>        Termination infos:
#6(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<StopEvent>        - Source 'VideoPipeline', reason 'Failed to start: Failed to start the video encoder.', code 0x800E840F NVST_DISCONN_SERVER_VIDEO_ENCODER_INIT_FAILED
#7(W)[2020-12-17 19:25:37,686]=20:25:37={15760}<NvscStreamingSes> Terminated unintentionally with reason 0x840F
#8(I)[2020-12-17 19:25:37,686]=20:25:37={16348}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_INPUT: NvstEventDetail::NVST_ED_STREAM_DISCONNECT_INTENTIONAL, message = 'Session quitting.'
#9(I)[2020-12-17 19:25:37,686]=20:25:37={16348}<NvInputStream>    InputStreamEventRaised
#0(I)[2020-12-17 19:25:37,686]=20:25:37={16348}<NvInputStream>    Stop Input stream.
#1(I)[2020-12-17 19:25:37,686]=20:25:37={16348}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_MIC: NvstEventDetail::NVST_ED_STREAM_DISCONNECT_INTENTIONAL, message = 'Session quitting.'
#2(I)[2020-12-17 19:25:37,686]=20:25:37={16348}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_AUDIO: NvstEventDetail::NVST_ED_STREAM_DISCONNECT_INTENTIONAL, message = 'Session quitting.'
#3(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<NvscStreamingSes> stopping audio controller
#4(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<NvscStreamingSes> Stopping audio session 0x000002B41FA2D1D0
#5(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<RtpAudioStreamer> exiting audio streamer timeMs 674 packetCount 118
#6(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<FecRtpSink>       No network errors observed
#7(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<NetworkRtpSink>   Closing internal socket
#8(I)[2020-12-17 19:25:37,686]=20:25:37={15760}<NvNetworkWin32>   Invoking QOSRemoveSocketFromFlow for handle 0000000000000650
#9(I)[2020-12-17 19:25:37,687]=20:25:37={16348}<AudioController>  Audio Stream: Disconnected
#0(I)[2020-12-17 19:25:37,687]=20:25:37={16348}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_VIDEO_INTERNAL: NvstEventDetail::NVST_ED_STREAM_DISCONNECT_INTENTIONAL, message = 'Session quitting.'
#1(I)[2020-12-17 19:25:37,687]=20:25:37={16348}<VideoContext>     VideoStreamEventRaised
#2(I)[2020-12-17 19:25:37,687]=20:25:37={16348}<StreamSdkEvents>  Invoking clientEventCallback NvstEventDetail::NVST_ED_STREAM_DISCONNECT_UNINTENTIONAL: NVST_DISCONN_SERVER_VIDEO_ENCODER_INIT_FAILED
#3(I)[2020-12-17 19:25:37,687]=20:25:37={16348}<SciBase>          Sent event StreamDisconnectUnintentional: NVST_DISCONN_SERVER_VIDEO_ENCODER_INIT_FAILED

**Comment by cgutman** [comment]
The NV_ENC_ERR_INVALID_PARAM error is because Maxwell's NVENC encoder doesn't support video dimensions greater than 4K. Encoding HEVC at up to [8K was introduced in Pascal](https://en.wikipedia.org/wiki/Nvidia_NVENC#Fourth_generation,_Pascal_GP10x).

**Comment by cgutman** [comment]
Moonlight will now warn that Maxwell 2 GPUs don't support encoding over 4K as of https://github.com/moonlight-stream/moonlight-qt/commit/22bebb6bbc33dd6092c097b532d2358ab928a5ea rather than just having GFE close the connection with no warning.
