### ISSUE TITLE
How to Disable Auto Update Checker and Moonlight Logs?

### ISSUE THREAD

**Issue by S4nfs** [moonlight-stream/moonlight-qt#487]
I added a Universal Theme and i don't want Moonlight to update the current version How do i disable the auto update checker? Also i want moonlight not to generate any of the logs related to my servers.

**Comment by cgutman** [comment]
As I mentioned in https://github.com/moonlight-stream/moonlight-qt/issues/478#issuecomment-749392053, I'm not able to provide individualized help with your personal Moonlight modifications. I encourage you to use the resources I pointed you to.

Additionally, creating issues on these GitHub repos should only be used for bugs or feature requests from the official Moonlight binaries and source code, not for 3rd-party forks or mods.
