### ISSUE TITLE
1Gbps option for streaming on LAN

### ISSUE THREAD

**Issue by yorinubu** [moonlight-stream/moonlight-qt#488]
When i am home at my local area network, i want to play 4k@120hz on tv but the 150Mbps option which is maximum is too low for this settings.

Expand the "bitrate speed bar" to more Mbps, it doesnt have to be exactly 1000Mbps but atleast 500Mbps would be great! :)

This feature would really help me get rid of cabels around my home when i want to play on TV and heaving PC in different room, too far from pc also you can get rid off HDMI 2.1 support becouse of this, which reduce the tv price significantly :)

Thank you for considering.

**Comment by jletizia** [comment]
>Finally, GeForce Experience itself also caps the bitrate that it will use for encoding, regardless of what Moonlight asks for. This is likely due to the encoding limitations above.

https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-doesnt-the-bitrate-slider-go-beyond-150-mbps

**Comment by cgutman** [comment]
Yeah I wrote that FAQ entry but forgot to link it here and close this. 🤦

**Comment by Espionage724** [comment]
What about when using Sunshine with AMD GPUs? I don't imagine Sunshine has to honor a 150Mbps limit?

**Comment by koshisan** [comment]
Would it make sense to maybe revisit this with many people moving to sunshine an higher resolutions?

**Comment by wyywang** [comment]
Would it make sense to maybe revisit this with many people moving to sunshine an higher resolutions?
+1

**Comment by WinkelCode** [comment]
@cgutman

> it's unlikely that the hardware decoder and driver could handle a 1 Gbps video stream even if you have a 1 Gbps network connection.

Apple's Media Engine seems to be able to handle this nowadays: https://github.com/moonlight-stream/moonlight-qt/pull/1377#issuecomment-2294590227
