### ISSUE TITLE
Flatpak Fails with "Could not initialize GLX"

### ISSUE THREAD

**Issue by myamanaka** [moonlight-stream/moonlight-qt#49]
**Describe the bug**
The flatpak fails silently from the icon and with a "Could not initialize GLX" error from the terminal.

**Steps to reproduce**
flatpak run com.moonlight_stream.Moonlight

**Moonlight settings (please complete the following information)**
The settings have not been adjusted from the default.

**Client PC details (please complete the following information)**
 - OS: Linux Mint 19
 - Moonlight Version: v0.3.0
 - NVIDIA Driver: 340.107
 - Video Card: NVIDIA Corporation GT218M

**Logs (please attach)**
```
myamanaka@adell:~$ flatpak run com.moonlight_stream.Moonlight 
00:00:00 - Qt Warning: Qt: Session management error: None of the authentication protocols specified are supported
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
00:00:00 - Qt Fatal: Could not initialize GLX
```

**Additional context**
Some googling told me I might be missing the flatpak NVIDIA drivers matching my system drivers, but they appear to all be correct.  I have 340.107 installed both via apt and flatpak.
```
com.moonlight_stream.Moonlight/x86_64/stable            system,current
com.slack.Slack/x86_64/stable                           system,current
com.valvesoftware.Steam/x86_64/stable                   system,current
com.visualstudio.code/x86_64/stable                     system,current
io.atom.Atom/x86_64/stable                              system,current
org.kde.kdenlive/x86_64/stable                          system,current
org.openmw.OpenMW/x86_64/stable                         system,current
org.freedesktop.Platform.Compat.i386/x86_64/18.08       system,runtime
org.freedesktop.Platform.Compat32/x86_64/1.6            system,runtime
org.freedesktop.Platform.GL.nvidia-340-107/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL32.nvidia-340-107/x86_64/1.4 system,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08       system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6              system,runtime
org.freedesktop.Platform.html5-codecs/x86_64/18.08      system,runtime
org.freedesktop.Platform/x86_64/1.6                     system,runtime
org.freedesktop.Platform/x86_64/18.08                   system,runtime
org.freedesktop.Sdk/x86_64/1.6                          system,runtime
org.gtk.Gtk3theme.Mint-Y/x86_64/3.22                    system,runtime
org.kde.Platform/x86_64/5.11                            system,runtime
org.kde.Platform/x86_64/5.9                             system,runtime
```
```
nvidia-340:
  Installed: 340.107-0ubuntu0~gpu18.04.1
  Candidate: 340.107-0ubuntu0~gpu18.04.1
  Version table:
 *** 340.107-0ubuntu0~gpu18.04.1 500
        500 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     340.106-0ubuntu3 500
        500 http://mirror.csclub.uwaterloo.ca/ubuntu bionic/restricted amd64 Packages
```
The glxinfo command dumps out a pretty big list, here's the first section:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_stereo_tree, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_NV_delay_before_swap, 
    GLX_NV_float_buffer, GLX_NV_multisample_coverage, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_swap_control, GLX_SGI_video_sync
```

I've tried OpenMW via flatpak and that works.  I've also tried Steam via flatpak and do not have any issues there either.

I'm not exactly sure how to troubleshoot the moonlight-qt issue further.

**Comment by cgutman** [comment]
Can you try the following commands and paste their output here:
`flatpak --version`
`flatpak run --command=sh com.moonlight_stream.Moonlight -c export`
`flatpak update`

**Comment by myamanaka** [comment]
Here is the output from the requested commands:

flatpak --version
```
Flatpak 0.11.7
```

flatpak run --command=sh com.moonlight_stream.Moonlight -c export
```
export AT_SPI_BUS_ADDRESS="unix:path=/run/user/1000/at-spi-bus"
export CINNAMON_VERSION="3.8.8"
export COLORTERM="truecolor"
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
export DCONF_USER_CONFIG_DIR=".config/dconf"
export DEFAULTS_PATH="/usr/share/gconf/cinnamon.default.path"
export DESKTOP_SESSION="cinnamon"
export DISPLAY=":99.0"
export FLATPAK_SANDBOX_DIR="/home/myamanaka/.var/app/com.moonlight_stream.Moonlight/sandbox"
export GDMSESSION="cinnamon"
export GDM_LANG="en_US"
export GI_TYPELIB_PATH="/app/lib/girepository-1.0"
export GJS_DEBUG_OUTPUT="stderr"
export GJS_DEBUG_TOPICS="JS ERROR;JS LOG"
export GNOME_DESKTOP_SESSION_ID="this-is-deprecated"
export GNOME_TERMINAL_SCREEN="/org/gnome/Terminal/screen/a2d85d98_bf47_4a11_9146_47072b77ccb4"
export GNOME_TERMINAL_SERVICE=":1.57"
export GPG_AGENT_INFO="/run/user/1000/gnupg/S.gpg-agent:0:1"
export GST_PLUGIN_SYSTEM_PATH="/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/gstreamer-1.0"
export GTK_MODULES="gail:atk-bridge"
export GTK_OVERLAY_SCROLLING="1"
export HOME="/home/myamanaka"
export KDE_FORK_SLAVES="1"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US"
export LESSCLOSE="/usr/bin/lesspipe %s %s"
export LESSOPEN="| /usr/bin/lesspipe %s"
export LIBVIRT_DEFAULT_URI="qemu:///system"
export LOGNAME="myamanaka"
export LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
export MANDATORY_PATH="/usr/share/gconf/cinnamon.mandatory.path"
export OLDPWD
export PATH="/app/bin:/usr/bin"
export PULSE_CLIENTCONFIG="/run/user/1000/pulse/config"
export PULSE_SERVER="unix:/run/user/1000/pulse/native"
export PWD="/home/myamanaka"
export QML2_IMPORT_PATH="/app/lib64/qml:/app/lib/qml"
export QT_ACCESSIBILITY="1"
export QT_PLUGIN_PATH="/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins"
export QT_QPA_PLATFORMTHEME="qt5ct"
export SESSION_MANAGER="local/adell:@/tmp/.ICE-unix/1545,unix/adell:/tmp/.ICE-unix/1545"
export SHELL="/bin/sh"
export SHLVL="2"
export SSH_AGENT_PID="1609"
export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"
export TERM="xterm-256color"
export USER="myamanaka"
export VTE_VERSION="5202"
export XAUTHORITY="/run/user/1000/Xauthority"
export XDG_CACHE_HOME="/home/myamanaka/.var/app/com.moonlight_stream.Moonlight/cache"
export XDG_CONFIG_DIRS="/app/etc/xdg:/etc/xdg"
export XDG_CONFIG_HOME="/home/myamanaka/.var/app/com.moonlight_stream.Moonlight/config"
export XDG_CURRENT_DESKTOP="X-Cinnamon"
export XDG_DATA_DIRS="/app/share:/usr/share:/usr/share/runtime/share:/run/host/share"
export XDG_DATA_HOME="/home/myamanaka/.var/app/com.moonlight_stream.Moonlight/data"
export XDG_GREETER_DATA_DIR="/var/lib/lightdm-data/myamanaka"
export XDG_RUNTIME_DIR="/run/user/1000"
export XDG_SEAT="seat0"
export XDG_SEAT_PATH="/org/freedesktop/DisplayManager/Seat0"
export XDG_SESSION_DESKTOP="cinnamon"
export XDG_SESSION_ID="c2"
export XDG_SESSION_PATH="/org/freedesktop/DisplayManager/Session0"
export XDG_SESSION_TYPE="x11"
export XDG_VTNR="7"
export _="/usr/bin/flatpak"
```

flatpak update
```
Looking for updates...
Updating: org.freedesktop.Platform/x86_64/18.08 from flathub
[####################] 8 delta parts, 4 loose fetched; 64650 KiB transferred in 224 seconds
Now at b85155963350.
Updating: org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08 from flathub
[####################] 1 delta parts, 1 loose fetched; 277 B transferred in 120 seconds
Now at a914fd4dabc0.
Updating: org.freedesktop.Platform.html5-codecs/x86_64/18.08 from flathub
[####################] 1 delta parts, 2 loose fetched; 2451 KiB transferred in 181 seconds
Now at 6e3e9f613bdd.
Updating: org.freedesktop.Platform.Compat.i386/x86_64/18.08 from flathub
[####################] 3 delta parts, 3 loose fetched; 24969 KiB transferred in 204 seconds
Now at 5ef1f120bbb2.
```

**Comment by cgutman** [comment]
Hmm, perhaps updating Flatpak might help things? Can you see if your distro has an updated package for Flatpak 1.0.0?

Otherwise, I'll try to reproduce this myself when I get some time.

**Comment by myamanaka** [comment]
I've installed flatpak from the official flatpak Ubuntu PPA which brought me up to 1.0.0, but unfortunately I still see the same issue.

```
myamanaka@adell:~$ apt-cache policy flatpak
flatpak:
  Installed: 1.0.0-flatpak2~bionic
  Candidate: 1.0.0-flatpak2~bionic
  Version table:
 *** 1.0.0-flatpak2~bionic 500
        500 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     0.11.7-0ubuntu0.1 500
        500 http://mirror.csclub.uwaterloo.ca/ubuntu bionic-updates/universe amd64 Packages
     0.11.3-3 500
        500 http://mirror.csclub.uwaterloo.ca/ubuntu bionic/universe amd64 Packages
```
```
myamanaka@adell:~$ flatpak run com.moonlight_stream.Moonlight 
00:00:00 - Qt Warning: Qt: Session management error: None of the authentication protocols specified are supported
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
00:00:00 - Qt Fatal: Could not initialize GLX
```

**Comment by 0xC1A551C** [comment]
I have the same exact issue on ubuntu 18.04. Happened after I installed the latest nvidia driver 390. fresh install

**Comment by 0xC1A551C** [comment]
I ran the flatpak update & it started working.

**Comment by logix2** [comment]
You need to install the Nvidia drivers from Flatpak (same version as your regular install drivers) to get apps that use OpenGL to work with proprietary Nvidia drivers. See here: https://www.linuxuprising.com/2018/06/how-to-get-flatpak-apps-and-games-built.html

**Comment by sandzhaj** [comment]
@logix2  
it doesn't work. 

flatpak list:
```
com.moonlight_stream.Moonlight/x86_64/stable          system,current
org.freedesktop.Platform.GL.nvidia-340-106/x86_64/1.4 system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6            system,runtime
org.gtk.Gtk3theme.Breeze/x86_64/3.22                  system,runtime
org.kde.Platform/x86_64/5.11                          system,runtime
```

nvidia:
```
apt-cache policy nvidia-340
nvidia-340:
Установлен: 340.106-0ubuntu3
Кандидат: 340.106-0ubuntu3
Таблица версий:
*** 340.106-0ubuntu3 500
```
As you see, version the same

Still getting error while flatpak run com.moonlight_stream.Moonlight:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
00:00:00 - Qt Fatal: Could not initialize GLX
```

A also can't build moonlight from source - https://i.imgur.com/yHHSB5r.png
Cause ubuntu doesn's have ffmpeg-devel. I installed all dev packages from this page: https://launchpad.net/ubuntu/+source/ffmpeg
But without result.

**Comment by cgutman** [comment]
@sandzhaj Ubuntu doesn't ship FFmpeg 4.0 which is required to build and run Moonlight. However, you can still build Moonlight from source on Ubuntu by downloading FFmpeg and building it from source or installing a PPA that contains FFmpeg 4 like https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4 (which our Travis CI config uses to build on Ubuntu).

If you install that PPA (and remove any existing older ffmpeg stuff), you can just `apt install libavcodec-dev libavutil-dev` and you should be good to go.

**Comment by sandzhaj** [comment]
@cgutman Oh, yeah, it works! Thank you!

**Comment by shamanman** [comment]
I get  flatpak run com.moonlight_stream.Moonlight

00:00:00 - Qt Warning: Qt: Session management error: None of the authentication protocols specified are supported
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
00:00:00 - Qt Fatal: Could not initialize GLX


When using Nvidia official drivers.
 everything is fine with open source drivers. (except no hardware acceleration)
also tested the official drivers with flatpak VLC and hardware acceleration seems to work with it vaapi and vdpau 

ps: sorry if my report is bad first time reporting

glxinfo
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_stereo_tree, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_NV_delay_before_swap, 
    GLX_NV_float_buffer, GLX_NV_multisample_coverage, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_swap_control, GLX_SGI_video_sync
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
client glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_stereo_tree, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_NV_copy_image, 
    GLX_NV_delay_before_swap, GLX_NV_float_buffer, 
    GLX_NV_multisample_coverage, GLX_NV_present_video, GLX_NV_swap_group, 
    GLX_NV_video_capture, GLX_NV_video_out, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_stereo_tree, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_NV_delay_before_swap, 
    GLX_NV_float_buffer, GLX_NV_multisample_coverage, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_swap_control, GLX_SGI_video_sync
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 1024 MB
    Total available memory: 1024 MB
    Currently available dedicated video memory: 928 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 220/PCIe/SSE2
OpenGL core profile version string: 3.3.0 NVIDIA 340.107
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:

its very long so i didnt post it all.

**Comment by shamanman** [comment]
pelase ignore my post it seems that nvidia drivers are very broken!

**Comment by cgutman** [comment]
I wonder if this issue is related to the ancient GeForce GPUs in your machines (200-series that's long out of official support).

Maybe the flatpak runtimes don't have support for such old hardware or the OpenGL support is too low for Qt.
