### ISSUE TITLE
Steam Link Controller Problem (Main UI)

### ISSUE THREAD

**Issue by BigBoiJeff** [moonlight-stream/moonlight-qt#496]
Whenever I try to navigate the interface on Steam Big Picture Mode, my A button refuses to work via the controller. When I try to map all the controller inputs, Steam Big Picture doesn't recognize me clicking in. 
Also, Steam Big Picture recognizes my Moonlight controller as a Switch Pro controller.

**Comment by cgutman** [comment]
Does it work properly in the Moonlight UI?

**Comment by BigBoiJeff** [comment]
Kind of?
The arrow keys work to navigate from game to game, but none of the buttons
work for selecting anything.

**Comment by cgutman** [comment]
What controller are you using?

**Comment by BigBoiJeff** [comment]
Just some Xbox 360 game pad I got from Amazon.
