### ISSUE TITLE
3.0.0 Windows Installer does not work

### ISSUE THREAD

**Issue by 3bst0r** [moonlight-stream/moonlight-qt#498]
The just released Windows installer does not seem to work. After completing the setup, clicking on the 'Launch' button has no effect. I also noticed the folder "Program Files\Moonlight Game Streaming" is empty.

**Comment by cgutman** [comment]
Fixed in installer update for v3.0.0 - https://github.com/moonlight-stream/moonlight-qt/releases/tag/v3.0.0
