### ISSUE TITLE
PC context menu not centered

### ISSUE THREAD

**Issue by raidancampbell** [moonlight-stream/moonlight-qt#5]
observed: menu is anchored to upper-left

expected: menu should open where the mouse is

<img width="298" alt="screenshot 2018-07-29 19 06 33" src="https://user-images.githubusercontent.com/5506073/43374054-94340980-9362-11e8-8a8d-14fcbecccaad.png">

**Comment by cgutman** [comment]
Would be nice to fix, but not worth keeping an issue open for.
