### ISSUE TITLE
PC rename and disable auto detection of network computers

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#50]
I would like to see an option to disable autodetection of network computers that have Geforce experience installed. 
I'm using Moonlight at work and my list is always automaticaly populated by network computers I don't want in my list.
Also the possibily to rename the computers in the moonlight main list would be nice.
Thanks in advance

**Comment by Jorys-Paulin** [comment]
@apoklyps3 Auto detections is done via mDNS, also used by Chromecast, but I don't think you can disable it on your host, so you'll need to disable it on the client side, bit problematic if you have multiple clients.
When it comes to renaming your computer, same thing. You can do it under the windows system options though.

**Comment by apoklyps3** [comment]
Am talking about Moonlight-Qt...so of course client side.
Not talking about real renaming modifications to the host side, just the way they are displayed in moonlight UI

**Comment by Jorys-Paulin** [comment]
@apoklyps3 Was just giving options that might be better for future readers.

**Comment by cgutman** [comment]
I implemented the "disable mDNS" option to address the main request in this ticket. Adding renaming support requires additional consideration that I didn't want to tackle at this point (namely, exactly how to handle the precedence of the host PC's name and the client's chosen name for the PC, including when the host PC's name changes after the client already renamed it).
