### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by drbree82** [moonlight-stream/moonlight-qt#51]
Windows 10 Pro - Linux subsystem running Ubuntu
Snapdragon 835 CPU

qmake does nothing

make produces following output

`cd moonlight-common-c/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/drbree82/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && make -f Makefile
Project ERROR: openssl development package not found
Makefile:46: recipe for target 'sub-moonlight-common-c-make_first' failed
make: *** [sub-moonlight-common-c-make_first] Error 3`

**Comment by cgutman** [comment]
Well it's complaining that you're missing OpenSSL, one of our required dependencies. Did you install any of the documented dependencies for building Moonlight?

If you're on Ubuntu, the package list in the Travis CI config is a good place to start - https://github.com/moonlight-stream/moonlight-qt/blob/master/.travis.yml

**Comment by asocjal** [comment]
Have the same issue on ubuntu. I can't install open-ssl-devel. Have no such thing in repo. I installed 'libssl-dev' instead. Unfortunatelly it didn't help:

`cd@cdpc:~/workspace-cpp/moonlight-qt$ sudo apt-get install libssl-dev
[sudo] password for cd: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libssl1.0-dev
The following NEW packages will be installed:
  libssl-dev
0 upgraded, 1 newly installed, 1 to remove and 60 not upgraded.
Need to get 0 B/1 374 kB of archives.
After this operation, 377 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 193116 files and directories currently installed.)
Removing libssl1.0-dev:amd64 (1.0.2n-1ubuntu5.3) ...
Selecting previously unselected package libssl-dev:amd64.
(Reading database ... 193031 files and directories currently installed.)
Preparing to unpack .../libssl-dev_1.1.0g-2ubuntu4.3_amd64.deb ...
Unpacking libssl-dev:amd64 (1.1.0g-2ubuntu4.3) ...
Setting up libssl-dev:amd64 (1.1.0g-2ubuntu4.3) ...
cd@cdpc:~/workspace-cpp/moonlight-qt$ make release
cd moonlight-common-c/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/cd/workspace-cpp/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && make -f Makefile release
Project ERROR: openssl development package not found
Makefile:356: recipe for target 'sub-moonlight-common-c-release' failed
make: *** [sub-moonlight-common-c-release] Error 3
` 

Open ssl seams to be installed, but maybe this is not development version?:

`cd@cdpc:~/workspace-cpp/moonlight-qt$ openssl help

Standard commands
asn1parse         ca                ciphers           cms               
crl               crl2pkcs7         dgst              dhparam           
dsa               dsaparam          ec                ecparam           
enc               engine            errstr            exit              
gendsa            genpkey           genrsa            help              
list              nseq              ocsp              passwd            
pkcs12            pkcs7             pkcs8             pkey              
pkeyparam         pkeyutl           prime             rand              
rehash            req               rsa               rsautl            
s_client          s_server          s_time            sess_id           
smime             speed             spkac             srp               
ts                verify            version           x509              

Message Digest commands (see the `dgst' command for more details)
blake2b512        blake2s256        gost              md4               
md5               rmd160            sha1              sha224            
sha256            sha384            sha512            

Cipher commands (see the `enc' command for more details)
aes-128-cbc       aes-128-ecb       aes-192-cbc       aes-192-ecb       
aes-256-cbc       aes-256-ecb       base64            bf                
bf-cbc            bf-cfb            bf-ecb            bf-ofb            
camellia-128-cbc  camellia-128-ecb  camellia-192-cbc  camellia-192-ecb  
camellia-256-cbc  camellia-256-ecb  cast              cast-cbc          
cast5-cbc         cast5-cfb         cast5-ecb         cast5-ofb         
des               des-cbc           des-cfb           des-ecb           
des-ede           des-ede-cbc       des-ede-cfb       des-ede-ofb       
des-ede3          des-ede3-cbc      des-ede3-cfb      des-ede3-ofb      
des-ofb           des3              desx              rc2               
rc2-40-cbc        rc2-64-cbc        rc2-cbc           rc2-cfb           
rc2-ecb           rc2-ofb           rc4               rc4-40            
seed              seed-cbc          seed-cfb          seed-ecb          
seed-ofb          
`

**Comment by jaclo187** [comment]
Same problem here. Also running WSL Ubuntu 20.04.

**Comment by cgutman** [comment]
hmm, do you have CMake installed?
