### ISSUE TITLE
[REQUEST]"Disable mouse acceleration" toggle

### ISSUE THREAD

**Issue by Adephx** [moonlight-stream/moonlight-qt#513]
Game Stream - Nvidia applies mouse acceleration by default, so I "solved" the issue by biding my Moonlight session to a "Desktop.exe" which is nothing but a glorified .bat file containing the following command: **START MouseFix.reg**

MouseFix.reg then contains the following:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Mouse]
"ActiveWindowTracking"=dword:00000000
"Beep"="No"
"DoubleClickHeight"="4"
"DoubleClickSpeed"="500"
"DoubleClickWidth"="4"
"ExtendedSounds"="No"
"MouseHoverHeight"="4"
"MouseHoverTime"="400"
"MouseHoverWidth"="4"
"MouseSensitivity"="10"
"MouseTrails"="0"
"SmoothMouseXCurve"=hex:00,00,00,00,00,00,00,00,15,6e,00,00,00,00,00,00,00,40,\
  01,00,00,00,00,00,29,dc,03,00,00,00,00,00,00,00,28,00,00,00,00,00
"SmoothMouseYCurve"=hex:00,00,00,00,00,00,00,00,fd,11,01,00,00,00,00,00,00,24,\
  04,00,00,00,00,00,00,fc,12,00,00,00,00,00,00,c0,bb,01,00,00,00,00
"SnapToDefaultButton"="0"
"SwapMouseButtons"="0"
"MouseThreshold1"="0"
"MouseThreshold2"="0"
"MouseSpeed"="0"

```

Would it be possible to integrate the mouse acceleration override directly into Moonlight?

**Comment by CyberMew** [comment]
If we were to manually go into regedit and turn it off, which is the key we need to add/modify? I thought I already disabled it via windows setting but looks like it isnt..

**Comment by Adephx** [comment]
> If we were to manually go into regedit and turn it off, which is the key we need to add/modify? I thought I already disabled it via windows setting but looks like it isnt..

You can't turn it off in the registry. Every time that you connect to your device, GameStream enables mouse acceleration by default. I haven't yet found a way to disable that, so you have to run the script above (just copy it into a notepad and change the extension from .txt to .reg), or turn it off manually in the mouse settings.

**Comment by SalvatoryMalamar** [comment]
This was discussed briefly in #128. Some sample code was identified from [this stackoverflow exchange](https://stackoverflow.com/questions/3902477/how-to-configure-mouse-enhance-pointer-precision-programmatically) that may be relevant.

```
// Turns mouse acceleration on/off by calling the SystemParametersInfo function.
// When mouseAccel is TRUE, mouse acceleration is turned on; FALSE for off.
void SetMouseAcceleration(BOOL mouseAccel)
{
    int mouseParams[3];

    // Get the current values.
    SystemParametersInfo(SPI_GETMOUSE, 0, mouseParams, 0);

    // Modify the acceleration value as directed.
    mouseParams[2] = mouseAccel;

    // Update the system setting.
    SystemParametersInfo(SPI_SETMOUSE, 0, mouseParams, SPIF_SENDCHANGE);
}
```

**Comment by makedir** [comment]
Anyone new on this? Could Moonlight do something about it? I notice it gets always turned back on when I connect.

**Comment by PedanXr** [comment]
Is there any update on this? Would really loveto see this feature at least considered

**Comment by cgutman** [comment]
GameStream is being discontinued by Nvidia, so this is not likely to ever be implemented on their side. However, [Sunshine](https://github.com/LizardByte/Sunshine) doesn't mess with your mouse acceleration like GFE did, so it seems unnecessary now.

**Comment by makedir** [comment]
"GameStream is being discontinued by Nvidia" WAIT WHAT!??? what does that mean!?? moonlight is dead and wont work anymore from a specific version of GFE in the future!?????

**Comment by PedanXr** [comment]
The hosting part from Geforce Experience is being discontinued. Moonlight is just a client. You can install Sunshine on your Host in order to continue using moonlight. 
Link to sunshine: https://github.com/LizardByte/Sunshine

**Comment by makedir** [comment]
wait what? I dont think that is correct that is gives the same performance as native Nvidia streaming on the host, Nvidia game streaming same as Steam streaming uses a closed API by Nvidia, so that is has low latency, which is not available for other software.
