### ISSUE TITLE
crackling/stuttering audio moonlight application android

### ISSUE THREAD

**Issue by thesandman12** [moonlight-stream/moonlight-qt#514]
hello, I have been using moonlight recently for pc work and it works perfectly but the audio keeps crackling and stuttering. Im pretty sure it isnt my wifi. I would appreciate some help with this as I need good sound.

**Comment by cgutman** [comment]
I see Android in the title of this bug. Was this meant to go in the https://github.com/moonlight-stream/moonlight-android project?
