### ISSUE TITLE
Github Actions for nightly builds

### ISSUE THREAD

**Issue by komawoyo** [moonlight-stream/moonlight-qt#515]
We can automate the build process on pull/merge using github actions so nightly builds are available

EDIT: nvm, appveyor exists

**Comment by Jorys-Paulin** [comment]
Hello, nightly builds are already avaliable, but via AppVeyor: https://ci.appveyor.com/project/cgutman/moonlight-qt/branch/master

**Comment by archive-r** [comment]
thx
