### ISSUE TITLE
Starting audio stream establishment failed: Error -1

### ISSUE THREAD

**Issue by ReindeerG** [moonlight-stream/moonlight-qt#52]
My office is moved to other place, and new desktop can not play moonlight portable 0.3.0.

ios version is still enable to connect my com. (I think Server com or firewall or tcpudp is well)

I think that's qt's problem or desktop..

**Client PC details (please complete the following information)**
 - OS: Windows 10
 - Moonlight Version: 0.3.0 portable

![20180827_16 20 52](https://user-images.githubusercontent.com/41472963/44646295-7f34c500-aa15-11e8-814d-29ddc18b8777.png)
[Moonlight-1535354427.log](https://github.com/moonlight-stream/moonlight-qt/files/2322802/Moonlight-1535354427.log)

**Comment by cgutman** [comment]
It looks like a bug in SDL when attempting to open your audio device. There seem to be some garbage characters or possibly an incorrect Unicode conversion.

```
00:00:16 - SDL Info (0): Starting audio stream...
00:00:16 - SDL Error (0): Failed to open audio device: WASAPI can't find requested audio endpoint: ¿ä¼Ò°¡ ¾ø½À´Ï´Ù.
00:00:16 - SDL Info (0): Audio stream start failed: -1
```

Can you right-click your Volume icon then click Audio Settings and upload a screenshot of that?

**Comment by ReindeerG** [comment]
If you have any information, please comment.
![20180827_18 44 13](https://user-images.githubusercontent.com/41472963/44653305-53233f00-aa29-11e8-820d-93b853877411.png)

**Comment by ReindeerG** [comment]
I Install Virtual Audio device (VBCable) then Moonlight can be started. but I wish Moonlight is still enabled even though don't have any sound device.

**Comment by cgutman** [comment]
OK, I see. So you intentionally have no audio device and want to stream?

**Comment by ReindeerG** [comment]
Yes. this Error may be solved by just having a earphone, but some computers still don't have speakers. There are a lot of programs or games that can be used without sound, but I think it is a little sad that all functions are blocked because there is no device to play.

**Comment by ReindeerG** [comment]
Yes. this Error may be solved by just having a earphone, but some computers still don't have speakers. There are a lot of programs or games that can be used without sound, but I think it is a little sad that all functions are blocked because there is no device to play.

**Comment by ReindeerG** [comment]
Yes. this Error may be solved by just having a earphone, but some computers still don't have speakers. There are a lot of programs or games that can be used without sound, but I think it is a little sad that all functions are blocked because there is no device to play.

**Comment by cgutman** [comment]
OK, I can make this work. I'll just show a warning during connection establishments saying that an audio device wasn't found.

**Comment by xczsonn** [comment]
Ugly korean
