### ISSUE TITLE
Mouse position incorrect for some UI elements when streaming desktop via mstsc.exe

### ISSUE THREAD

**Issue by thelazyfox** [moonlight-stream/moonlight-qt#521]
**Describe the bug**
Moonlight appears to render the mouse position incorrectly, the correct mouse rendering can be observed in the client when doing simple things like dragging an explorer window to be larger/smaller while streaming the desktop via the mstsc.exe route. This happens with the latest moonlight on both mac and windows clients, and the latest nvidia drivers on the host.

**Steps to reproduce**
1. Set up gamestreaming on a host, moonlight on either a mac or windows client.
2. Start streaming the desktop with mstsc.exe
3. Open a window, for example opening the documents folder in the explorer window
4. Grab the bottom right corner of the window and drag it to be larger or smaller. Observe that the resize mouse indicator goes from being rendered once, in an incorrect spot to rendered twice while dragging (one correct and one incorrect).

**Screenshots**
I can post screenshots/videos if others have trouble reproducing.

**Affected games**
Seems to happen globally? The mouse position does not seem incorrect in all scenarios but this one is a clear example of one.

**Other Moonlight clients**
- No idea, can't test this myself.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
I tried with defaults, all three window/fullscreen settings, and with the two different mouse modes.
- If so, which settings have been changed?
see above
- Does the problem still occur after reverting settings back to default?
seems to always happen

**Client PC details (please complete the following information)**
 - OS: Windows 10 19041.804
 - Moonlight Version: 3.0.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 19042.804
 - GeForce Experience version: 3.21.0.36
 - Nvidia GPU driver: 461.40
 - 
**Moonlight Logs (please attach)**
N/A

**Additional context**
The mouse position is correct for a lot of UI elements, but not all. I have no idea how/why this would be the case.

**Comment by cgutman** [comment]
Moonlight does not render the mouse cursor itself. The mouse cursor is already included in the video stream from the PC, so this is something Nvidia will have to fix. Unfortunately, there's nothing we (on the client side) can do here.

We do know that the mouse pointer issue was introduced in the 450 driver series. Downgrading to 446 has been the workaround of choice for those affected.
