### ISSUE TITLE
Moonlight-qt takes a long time open

### ISSUE THREAD

**Issue by ReenigneArcher** [moonlight-stream/moonlight-qt#522]
**READ ME FIRST!**
This issue tracker is not the right place to ask for troubleshooting help if you're not able to connect or stream at all. For those requests, please use the #pc-help channel on our Discord server where there are many more people who can help (or direct you back here if it looks like a Moonlight bug after all). https://moonlight-stream.org/discord

**Describe the bug**
On Windows 10, Moonlight QT takes a long time to open (roughly 18 seconds) before anything is shown after double clicking the desktop icon. I tried with 3.0.0 and 2.2.0.

**Steps to reproduce**
Not entirely sure.

I have OS and moonlight installed to Samsung 970 EVO 1TB M.2 nvme drive with plenty of space left.

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Affected games**
List the games you've tried that exhibit the issue. To see if the issue is game-specific, try streaming Steam Big Picture with Moonlight and see if the issue persists there.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?... No

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Everything is default, fresh install.
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809] Windows 10 Pro 19041
 - Moonlight Version: [e.g. v0.9.0] 3.0.0

**Server PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809] Windows 10 19042
 - GeForce Experience version: [e.g. 3.16.0.140] 3.21.0.36
 - Nvidia GPU driver: [e.g. 417.35] 461.09

**Moonlight Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux with the Flatpak, logs print to the terminal when running with the command: `flatpak run com.moonlight_stream.Moonlight`
- On Linux with the Snap, logs print to the terminal when running with the command: `moonlight`

```
00:00:00 - SDL Info (0): Compiled with SDL 2.0.15
00:00:00 - SDL Info (0): Running with SDL 2.0.15
00:00:00 - Qt Debug: Translation loaded: false
00:00:00 - Qt Info: No existing credentials found
00:00:00 - Qt Info: Wrote new identity credentials to settings
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:06 - Qt Info: Found "gamecontrollerdb.txt" at "C:/Program Files/Moonlight Game Streaming/gamecontrollerdb.txt"
00:00:06 - SDL Info (0): Loaded 73 new gamepad mappings
00:00:06 - SDL Info (0): V-sync enabled
00:00:06 - SDL Info (0): Windowed mode with DWM running
00:00:06 - SDL Info (0): Windowed: 1 | Present Interval: 80000000
00:00:06 - SDL Info (0): Detected GPU: NVIDIA GeForce RTX 2080 SUPER (10de:1e81)
00:00:06 - SDL Info (0): GPU driver: nvldumdx.dll 27.21.14.6140
00:00:06 - SDL Info (0): Using DXVA2 accelerated renderer
00:00:06 - FFmpeg: [h264 @ 0000018057B6DF80] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:06 - FFmpeg: [h264 @ 0000018057B6DF80] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:06 - FFmpeg: [h264 @ 0000018057B6DF80] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:06 - FFmpeg: [h264 @ 0000018057B6DF80] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:06 - FFmpeg: [h264 @ 0000018057B6DF80] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:06 - FFmpeg: [h264 @ 0000018057B6DF80] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:06 - FFmpeg: [h264 @ 0000018057B6DF80] Format dxva2_vld chosen by get_format().
00:00:06 - FFmpeg: [h264 @ 0000018057B6DF80] Format dxva2_vld requires hwaccel initialisation.
00:00:06 - FFmpeg: [h264 @ 0000018057B6DF80] Reinit context to 1280x720, pix_fmt: dxva2_vld
00:00:06 - SDL Info (0): DXVA2 decoder surface high-water mark: 0
00:00:06 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:16 - Qt Info: Found "gamecontrollerdb.txt" at "C:/Program Files/Moonlight Game Streaming/gamecontrollerdb.txt"
00:00:16 - SDL Info (0): Loaded 73 new gamepad mappings
00:00:16 - Qt Debug: Current Moonlight version: "3.0.0"
00:00:16 - Qt Info: Downloaded updated gamepad mappings
00:00:16 - Qt Info: Discovered mDNS host: "MSI.local."
00:00:16 - Qt Debug: Found update manifest match for current platform
00:00:16 - Qt Debug: Latest version of Moonlight for this platform is: "3.0.0"
00:00:16 - Qt Debug: Update manifest version equal to current version
00:00:16 - Qt Info: Resolved "MSI.local." to QHostAddress("192.168.1.13")
00:00:16 - Qt Info: Resolved "MSI.local." to QHostAddress("fe80::c101:5dd1:c14c:ed24")
00:00:18 - Qt Info: Processing new PC at "192.168.1.13" from mDNS QHostAddress("")
00:00:18 - Qt Info: Executing request: "http://192.168.1.13:47989/serverinfo?uniqueid=0123456789ABCDEF&uuid=4590df92c1db44dea0402f85ec8a35ec"
```

**Additional context**
Anything else you think may be relevant to the issue

**Comment by cgutman** [comment]
While Moonlight is trying to open (preferable around that gap from :06 to :16 seconds), please use Task Manager to collect a memory dump of Moonlight.exe by right clicking the process and choosing "Create Memory Dump". Zip it and post a link here.

With that I should be able to see what Moonlight is doing for that 10 seconds where it seems hung.

**Comment by ReenigneArcher** [comment]
> 
> 
> While Moonlight is trying to open (preferable around that gap from :06 to :16 seconds), please use Task Manager to collect a memory dump of Moonlight.exe by right clicking the process and choosing "Create Memory Dump". Zip it and post a link here.
> 
> With that I should be able to see what Moonlight is doing for that 10 seconds where it seems hung.

Here you go.

https://drive.google.com/file/d/1eMLR8L6u-EWJGNwk4BqDdXeLnIJye49k/view?usp=sharing

**Comment by cgutman** [comment]
It looks like the problem is that one of your connected HID devices is very slow to respond to string queries made by DirectInput when SDL asks for a device list. I don't think there's anything we can do generally to prevent this. Some hardware is just broken.

Try unplugging any USB or Bluetooth HID devices one by one to figure out which one is the cause.

```
0:000> kc
 # Call Site
00 ntdll!NtDeviceIoControlFile
01 KERNELBASE!DeviceIoControl
02 kernel32!DeviceIoControlImplementation
03 hid!DeviceIoControlHelper
04 hid!HidD_GetProductString
05 dinput8!fGetProductStringFromDevice
06 dinput8!CHid_GetProperty
07 dinput8!CHid_GetDeviceInfo
08 dinput8!CDIDev_GetDeviceInfoW
09 dinput8!CDIDEnum_Next
0a dinput8!CDIObj_EnumDevicesW
0b SDL2!SDL_DINPUT_JoystickDetect
0c SDL2!SDL_DINPUT_JoystickUpdate
0d SDL2!SDL_JoystickInit
0e SDL2!SDL_InitSubSystem_REAL
0f Moonlight!SdlInputHandler::getUnmappedGamepads
```

**Comment by ReenigneArcher** [comment]
Weird, it was just a bluetooth dongle with no devices attached to it. Not using it anyway. Thanks!
