### ISSUE TITLE
Server randomly not reachable when starting PC

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#523]
Not sure since when this happened but mostly one of the last versions, that the streaming pc is not reachable when started Windows. Have to restart the Pc and then it may work.

**Comment by cgutman** [comment]
Some users have reported this happening with GeForce Experience v3.21. The Shield tab in GFE may disappear as well until a reboot. Those affected users confirmed that it's not Moonlight's fault, as the problem happens with Nvidia's official clients and can also be confirmed by attempting to access http://127.0.0.1:47989/serverinfo on the affected system.

I'm not familar with workarounds for this specific GeForce Experience bug, but I believe some folks on Discord may be able to help - https://moonlight-stream.org/discord

**Comment by makedir** [comment]
Seems there is an issue with GFE that when an update happened it doesnt update itself automatically on its own and stays broken until you manually open GFE on the server at least once. Then it triggers the installation. Though just if you open GFE manually once.
