### ISSUE TITLE
Mouse cursor randomly not working when leaving client window

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#524]
Happens often that you cant switch out of the streaming client window and switching out doesn't work anymore, have to quit via shortcut to get mouse control of the client pc back.

**Comment by cgutman** [comment]
Can you provide more details?

What OS are you running Moonlight on?
What do you mean by "switching out"?

Please provide exact steps I can use to reproduce the bug locally and any other details that may be relevant.

**Comment by makedir** [comment]
No I cant reproduce it it just happened now randomly a few times. Client Windows 10 latest version. Just switching out of it, and sometimes you have no mouse cursor anymore in Windows 10 when switching out of the streaming client until you force close it.

**Comment by cgutman** [comment]
How are you switching out? You mean with Alt+Tab? Pressing the Windows key? Something else?

**Comment by makedir** [comment]
yes windows key or alt+tab, just leaving the streaming window. and it happened a few times, that I had no mouse cursor outside of it anymore, until closing the stream.

**Comment by cgutman** [comment]
Does this still happen with v3.1.0?

**Comment by makedir** [comment]
Will test, thanks. The new feature in 3.1.0 of capturing system hotkeys is great though so I maybe wont have issues anymore with that. However: the "Ctrl+Alt+Shift+D" to minimize the client is a bit "complicated" to memorize. A (overlay) GUI would be a good way maybe to implement in the future. Something you can easily access with a shorter shortcut and have all the shortcuts in it to see.
