### ISSUE TITLE
Mouse cursor of streaming pc not scaling with Windows 10 scaling

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#525]
Mouse cursor too small and not scaling correctly with Windows 10 mouse cursor size setting of the host Pc.

**Comment by Nexxkinn** [comment]
Apparently, you can mitigate this by using older mouse settings.

![image](https://user-images.githubusercontent.com/7548170/109334904-2c226f80-7816-11eb-90c2-d98f67021463.png)

**Comment by cgutman** [comment]
Moonlight does not render the mouse cursor itself. The mouse is already included in the video stream from the PC, so this is something Nvidia will have to fix. Unfortunately, there's nothing we (on the client side) can do here.
