### ISSUE TITLE
Windows key wont be sent through moonlight

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#527]
Windows key wont be sent through moonlight, please make an option to make this work. It is important to switch out of games through moonlight to make settings on the host PC.

**Comment by PolCPP** [comment]
The Windows key is blocked by GFE, so moonlight can't do anything. Check https://github.com/moonlight-stream/moonlight-chrome/issues/455

**Comment by cgutman** [comment]
We did find a way to work around GFE's block.

This is already implemented in Moonlight PC v3.0.0 (see the release notes). You just have to enable the "Capture system keyboard shortcuts" option in settings.
