### ISSUE TITLE
On last release of Raspberry Pi OS, the sound cut for one second every 20 seconds or so.

### ISSUE THREAD

**Issue by nicolaspernoud** [moonlight-stream/moonlight-qt#528]
**Describe the bug**
On last release of Raspberry Pi OS (Raspbian Buster 2021-01-11), the sound cut for one second every 20 seconds or so.

**Steps to reproduce**
On last release of Raspberry Pi OS (Raspbian Buster 2021-01-11), the sound cut for one second every 20 seconds or so.
The video quality is flawless, without any stutter, and with 1Gb Ethernet between the PC and the raspberry pi.

I use Moonlight outside the GUI (from command line), and it would seem that the pulseaudio daemon is not started ...
ps aux | grep pulse => gives nothing.
If I tried to start it manually with pulseaudio -D before launching moonlight-qt, it is even worse : a lot of sound stuttering...

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Affected games**
Every game, namely Rayman Legends and Detroid Become Human

**Other Moonlight clients**
It doesn't occur using moonlight embedded with the same machine.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? => NO

**Server PC details (please complete the following information)**
 - OS: Windows 10 20H2 19042.746
 - GeForce Experience version: 3.21.0.36
 - Nvidia GPU driver: 461.33

**Moonlight Logs (please attach)**
févr. 19 20:30:19 box.local moonlight.sh[26281]: error: XDG_RUNTIME_DIR not set in the environment.
févr. 19 20:30:19 box.local moonlight.sh[26281]: 00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at "/home/box/.cache/Moonlight Game Streami
févr. 19 20:30:19 box.local moonlight.sh[26281]: 00:00:01 - SDL Info (0): Loaded 109 new gamepad mappings
févr. 19 20:30:19 box.local moonlight.sh[26281]: error: XDG_RUNTIME_DIR not set in the environment.
févr. 19 20:30:20 box.local moonlight.sh[26281]: 00:00:01 - SDL Info (0): V-sync enabled
févr. 19 20:30:20 box.local moonlight.sh[26281]: 00:00:01 - SDL Info (0): Using MMAL renderer
févr. 19 20:30:20 box.local moonlight.sh[26281]: 00:00:01 - FFmpeg: [h264_mmal @ 0xfbfe10] Format mmal chosen by get_format().
févr. 19 20:30:20 box.local moonlight.sh[26281]: 00:00:01 - FFmpeg: [h264_mmal @ 0xfbfe10] Using MMAL H264 encoding.
févr. 19 20:30:20 box.local moonlight.sh[26281]: 00:00:01 - FFmpeg: [h264_mmal @ 0xfbfe10] Changing output format.
févr. 19 20:30:20 box.local moonlight.sh[26281]: 00:00:01 - SDL Info (0): FFmpeg-based video decoder chosen
févr. 19 20:30:21 box.local moonlight.sh[26281]: 00:00:02 - SDL Info (0): Loaded 109 new gamepad mappings
févr. 19 20:30:21 box.local moonlight.sh[26281]: 00:00:02 - Qt Info: "MISTRAL" is now online at "192.168.1.89"
févr. 19 20:30:21 box.local moonlight.sh[26281]: 00:00:02 - Qt Debug: Current Moonlight version: "3.0.0"
févr. 19 20:30:21 box.local moonlight.sh[26281]: 00:00:02 - Qt Info: Discovered mDNS host: "mistral.local."
févr. 19 20:30:21 box.local moonlight.sh[26281]: 00:00:02 - Qt Info: Resolved "mistral.local." to QHostAddress("192.168.1.89")
févr. 19 20:30:21 box.local moonlight.sh[26281]: 00:00:02 - Qt Info: Resolved "mistral.local." to QHostAddress("fe80::719d:c561:94a1:e172")
févr. 19 20:30:21 box.local moonlight.sh[26281]: 00:00:02 - Qt Info: Downloaded updated gamepad mappings
févr. 19 20:30:23 box.local moonlight.sh[26281]: 00:00:04 - Qt Info: Processing new PC at "192.168.1.89" from mDNS QHostAddress("")
févr. 19 20:30:23 box.local moonlight.sh[26281]: 00:00:04 - Qt Info: Executing request: "http://192.168.1.89:47989/serverinfo?uniqueid=012345
févr. 19 20:30:23 box.local moonlight.sh[26281]: 00:00:04 - Qt Info: Executing request: "https://192.168.1.89:47984/serverinfo?uniqueid=01234

**Additional context**
As said, the pulseaudio daemon seems not to be running when started from command line, maybe the problem is there ?

**Comment by cgutman** [comment]
If you run Moonlight with the following command to force ALSA, does that solve the issue?

```PULSE_SERVER=none moonlight-qt```

**Comment by nicolaspernoud** [comment]
No, it is the same. I think when booting from console, the pulseaudio daemon is not started anyway (`sudo ps aux | grep pulse` gives nothing), so it runs with alsa from the start. When trying to start pulse manually (pulseaudio -D) before running moonlight-qt, it is even worse.

I have a quite simple setup with last release of raspberry pi os (normal edition), with just kodi installed and starting straight from console enabled...

**Comment by cpetry** [comment]
I also have trouble with sound.
I have the latest Rpi raspbian distro but I have to force ALSA as discribed in the moonlight Rpi 4 installation discription to get any sound.

**Comment by cgutman** [comment]
@nicolaspernoud What audio output device are you using? Are you using surround sound? Is your Pi connected via Ethernet or WiFi? I use 3.5mm stereo output with an Ethernet connection and audio is flawless for me.

@cpetry Do you have a `~/.asoundrc` file? What audio output device are you using? 

Just to confirm, have you done the following steps mentioned by the [blog post](https://www.raspberrypi.org/blog/new-raspberry-pi-os-release-december-2020/)?
```
sudo apt update
sudo apt full-upgrade
```

Are you able to try with a freshly flashed SD card using the latest Raspberry Pi OS image to rule out any non-standard settings in your existing OS?

**Comment by cpetry** [comment]
Strange.
I reinstalled pulse audio, checked if it is really used and misteriously got it working without a hitch.
Seems it's solved for me.

**Comment by nicolaspernoud** [comment]
@cgutman : I use HDMI output but without any tweaks, my pi is connected via Ethernet, and the video is flawless...
the ~/.asoundrc is as follow, created by system I guess, not by me :
```
pcm.!default {
  type asym
  playback.pcm {
    type plug
    slave.pcm "output"
  }
  capture.pcm {
    type plug
    slave.pcm "input"
  }
}

pcm.output {
  type hw
  card 0
}

ctl.!default {
  type hw
  card 0
}
```
I'll try to test it with a newly flashed card, but not right now (maybe next weekend).

**Comment by nicolaspernoud** [comment]
I'll tried to start moonlight-qt on a fresh system. The audio cuts seems to have disappeared... **but**, when starting from the command line, pulseaudio seems not to be used anyway : `sudo ps aux | grep pulse` giving no result... maybe the audio cuts happens because of kodi initializing something audiowise... even if I quit kodi before starting moonlight qt...

**Comment by cgutman** [comment]
Maybe Kodi is touching `~/.asoundrc` or `/etc/asound.conf`?

**Comment by nicolaspernoud** [comment]
Please find below the content of `~/.asoundrc` (with kodi running) :
```
pcm.!default {
  type asym
  playback.pcm {
    type plug
    slave.pcm "output"
  }
  capture.pcm {
    type plug
    slave.pcm "input"
  }
}

pcm.output {
  type hw
  card 0
}

ctl.!default {
  type hw
  card 0
}
```
`/etc/asound.conf` does not exist. There is a directory `/etc/alsa/conf.d` with the following files though :
```
10-rate-lav.conf    10-speexrate.conf     50-jack.conf  50-pulseaudio.conf   60-upmix.conf     98-usb-stream.conf                  99-pulse.conf
10-samplerate.conf  50-arcam-av-ctl.conf  50-oss.conf   60-a52-encoder.conf  60-vdownmix.conf  99-pulseaudio-default.conf.example
```
