### ISSUE TITLE
MacOS: Moonlight actively prevents sleep while stream is active

### ISSUE THREAD

**Issue by baughj** [moonlight-stream/moonlight-qt#529]
**Is your feature request related to a problem? Please describe.**
On OSX, I find that when I am actively streaming something, even say msrdp (I mostly use Moonlight as a 4k desktop that happens to also be able to play games), OSX is actively prevented from sleeping (you can see this in Activity Monitor). If the stream is closed, sleep is allowed. I use Moonlight extensively to do remote development to a headless Windows machine and I'd much rather prefer this be configurable especially as it prevents screensaver activation / autolock of the Mac in question which I feel for a lot of people is probably a security concern.

**Describe the solution you'd like**
I would either suggest this could be a toggle in settings (maybe Advanced Settings?) or the behavior could be disabled entirely. 

**Describe alternatives you've considered**
Remembering to quit Moonlight would definitely be an alternative. 😄 

**Additional context**

**Comment by cgutman** [comment]
Fixed by 97d8274911491746dbc9125ce4c2d0b2d889549c
