### ISSUE TITLE
[RELEASE] Moonlight Alt+Tab workaround

### ISSUE THREAD

**Issue by Vyrosa** [moonlight-stream/moonlight-qt#531]
Since some people use Azure nv6/nv6_promo to use Moonlight from the main clients to connect to their vms, I thought I'd make a workaround for alt+tab because azure specs arent good enough for game streaming, therefore you need to use special scrips to get shield gamestream enabled, anyways, just download the file and run it, ill leave a virus total just for you to see that its not a virus, enjoy gamers: 

Download : https://cdn.discordapp.com/attachments/811957378685206570/815542734781022218/Godly_AltTab_for_VMS.exe

VT : https://www.virustotal.com/gui/file/d6928f18b19e0ac7392ce459cb6b89ca2bb80a44390f60d361ed402ef35e73d7/detection

The 3 suspicious detections are false positives, have a nice day

**Comment by Vyrosa** [comment]
Oh by the way i forgot to mention you need to press Ctrl+Tab for it to work
or Ctrl+tab+shit, depends on how youre used to do it

**Comment by lateforwork1000** [comment]
I'v been using Parsec it has full control over windows(alt-tab and alt-control-delete, etc).

**Comment by cgutman** [comment]
Moonlight v3.0.0 already supports capturing system keys like Alt+Tab, Win+Tab, etc. when you use it with GeForce Experience v3.20 or later.

Is there something else that you're missing?

**Comment by lateforwork1000** [comment]
I use parsec because it has support for the windows key and the "Fn" combo key I'm able to switch desktops and works spaces. The mouse works with out needing to switch profiles?. It works fine for what I need it to do. 
These are just small things (work related stuff)  moonlight is still better at gamestreaming.

**Comment by lateforwork1000** [comment]
Also I forgot to mention some games are now DRM protected and nvidia gamestream will not allow you to stream it. Iv been having on and off problems playing overwatch sometimes i'll get a DRM block.
