### ISSUE TITLE
Black out monitors not used

### ISSUE THREAD

**Issue by witchcraftsman** [moonlight-stream/moonlight-qt#534]
ATM: 
I run moonlight client on external monitor (mac os, but that relates to windows as well)
I use my macbook's keyboard so I can't close the lid
When I connect to remote desktop I got what was displayed on macbook screen
This is distracting (or even too bright depending on contents displayed) and since I can't fall back to host OS to gain control, this couldn't be changed with active connection

Should be either:
- All other displays go black 
- I could switch to host OS with Cmd-Tab to be able to make some arrangements (if it's even possible by design)
- An option of above choices in preferences. Personally I'd prefer option no.2 to be more flexible, anyway I don't see how this would organically fit current prefs setup
Option no.2 is FR by itself

**Comment by cgutman** [comment]
I'm not really following. Are you saying the stream starts on the wrong display (a different one than the one where the Moonlight UI was on)?

As mentioned on your other issue, you can use Cmd-Tab in borderless windowed.

Can you clarify your issue further?

**Comment by witchcraftsman** [comment]
No, the stream starts on the one where UI is.
I just wanted all other displays (macbook's screen in my case) to go black.

**Comment by cgutman** [comment]
Ok, I understand. I think blanking other displays is a bit outside the realm of things Moonlight should be doing (affecting system-wide state in a single app).

Fortunately, it appears there is a setting that will do this - https://superuser.com/questions/979935/mac-dual-monitor-prevent-second-monitor-to-go-black-while-first-one-is-fullscre (in your case, you want to do the opposite of what this person wants).
