### ISSUE TITLE
Is moonlight Windows client using decode swap chains with d11 decoding, if so please disable

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#537]
Hello,

 I found this bug around 2 years ago and reported it in the mean time to
 Chrome dev team. We could debug it down to the cause of using decode swap
 chains with direct3d11 in combination with Intel <=Gen9 on Windows 10.

 The issue is, when a software is using decode swap chains with a
 direct3d11 device, it can cause the driver to crash.

 The issue, how it happens, and how to fix is described here with the
 Chrome dev team:

 https://bugs.chromium.org/p/chromium/issues/detail?id=1107403

 The "workaround" Chrome dev team implemented was to deactivate decode swap
 chains at all for all <=Gen9 Intel:

 https://chromium.googlesource.com/chromium/src.git/+/727753712e66aac0dc130dc6c1625d2938d32a0f

As I see it, every software, which uses a decode swap chain with D11 will eventually trigger this issue and cause the Intel driver to crash.

So if Moonlight client uses a decode swap chain, can you maybe disable it on Intel <=gen9 on Windows10 or implement a debug toggle checkbox to manually disable decode swap chains in the settings?

**Comment by cgutman** [comment]
Moonlight uses DX9 with DXVA2 to render on Windows, so it is not affected by this bug.

See the bug you filed #317 that still isn't marked done ;)
