### ISSUE TITLE
vibration pass through

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#54]
any chance  controller vibration could passed trough?

**Comment by cgutman** [comment]
Yes, GameStream supports but Moonlight-common-c doesn't yet because I haven't figured out how exactly it works.

**Comment by apoklyps3** [comment]
cool.
hope you figure it out should you wish to add it...
moonlight has already gotten to a level I didn't imagine it could get

**Comment by posti85** [comment]
Hello, just to know, are there any new on this? Thank you @cgutman very much for this amazing project :).

**Comment by cgutman** [comment]
Nope, not yet.

**Comment by mrb113** [comment]
https://github.com/moonlight-stream/moonlight-qt/commit/7b0596d9df3ebd7021d4629f80e5c2efa4a2834a 
Done - if you try it out, let us know what you think.

**Comment by posti85** [comment]
Really? :O But shouldn't it be implemented in moonlight-common-c library so it could be used in other moonlight based applications?

**Comment by cgutman** [comment]
It is. It's using the new rumble callback from moonlight-common-c to tell SDL when to rumble.

**Comment by posti85** [comment]
Great!!! I'm waiting anxiously its support in moonlight-embbeded project

**Comment by ayushsharma82** [comment]
@mrb113 I don't think it's working anymore? I'm using DS4Windows + DualSense controller, The rumble/vibration works on the client PC ( tested via https://gamepad-tester.com ) but when I try to issue the same command via host PC, the vibration is not getting passed through.
