### ISSUE TITLE
[Feature] build opts to disable "Discord" & "Help" buttons/links

### ISSUE THREAD

**Issue by SupervisedThinking** [moonlight-stream/moonlight-qt#540]
**Describe the solution you'd like**
Is it possible to disable the "Discord" & "Help" links in the moonlight-qt gui? I build moonlight e.g. HTPC SBC builds for "embedded systems" where no browser, discord or full desktop is available anyway.

**Comment by cgutman** [comment]
Yeah, the existing code does support this, but we are forced to use heuristics to identify cases where we're running in an embedded environment:
https://github.com/moonlight-stream/moonlight-qt/blob/b5f8e6738a514b3e9d0f43afe6564b9ca27015d1/app/backend/systemproperties.cpp#L58-L63

Can you describe more about the setup you're running Moonlight on? Perhaps there is something we could look for.

**Comment by SupervisedThinking** [comment]
I'm running moonlight with this base https://github.com/SupervisedThinking/LibreELEC-RR which is basically a [LibreELEC fork](https://github.com/LibreELEC/LibreELEC.tv)

The Generic builds use X11 and I've added brave browser but as you might guess it's not exactly a usual desktop distro where "windowed multitasking" is possible.

**Comment by cgutman** [comment]
Is there an environment variable we could check like `XDG_CURRENT_DESKTOP` that will indicate we're in this environment?

`HAVE_DISCORD` is defined in app.pro for Windows and macOS builds.

**Comment by SupervisedThinking** [comment]
I only have `XDG_RUNTIME_DIR` defined but I could define any envar that's needed. What would you suggest to define to tell moonlight-qt it's running an embedded environment?

**Comment by cgutman** [comment]
OK, this should be fixed with d6b314f573712687197f66401fa6ed87c4064dae

When you build, use `qmake "CONFIG+=embedded" moonlight-qt.pro` and it will disable all that stuff.

**Comment by SupervisedThinking** [comment]
Tested & works perfectly fine! 🥇
