### ISSUE TITLE
Controller doesn't connect to the virtual machine on moonlight

### ISSUE THREAD

**Issue by WicktorB** [moonlight-stream/moonlight-qt#543]
Hi, 
I have an xbox serie x controller which can connect very well to my laptop via bluetooth (Macbook pro m1, Big Sur OS 11.3 demo). I can't get it connected via usb but it's ok. 
However, I am using a virtual machine (MaximumSettings) on moonlight and I can't get my controller connected to my virtual machine via bluetooth. It's just not responsive even if it works on my mac.
Any idea ?

**Comment by cgutman** [comment]
This bug is a duplicate #503

It is already fixed, but not yet released. You can find a build including the fix here- https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/38209695/job/abyinvs6ouejgd53/artifacts

**Comment by cgutman** [comment]
The fix is officially released in v3.1.0.
