### ISSUE TITLE
3.1 Universal not working on M1

### ISSUE THREAD

**Issue by PolCPP** [moonlight-stream/moonlight-qt#544]
Using 11.2.3, Mac Os saying it cannot be opened and make sure it's compatible.

Running from CLI gives this.

```
dyld: Library not loaded: @rpath/QtQuickControls2.framework/Versions/5/QtQuickControls2
  Referenced from: /Applications/Moonlight.app/Contents/MacOS/./Moonlight
  Reason: no suitable image found.  Did find:
	/Applications/Moonlight.app/Contents/MacOS/../Frameworks/QtQuickControls2.framework/Versions/5/QtQuickControls2: mach-o, but wrong architecture
	/Applications/Moonlight.app/Contents/MacOS/../Frameworks/QtQuickControls2.framework/Versions/5/QtQuickControls2: mach-o, but wrong architecture
zsh: abort      ./Moonlight
```

If i run it from cli using rosetta ( arch -x86_64 ./Moonlight ) it works

Edit the universal build from a few days ago was working on my machine

**Comment by cgutman** [comment]
Please try this new build - https://github.com/moonlight-stream/moonlight-qt/releases/download/v3.1.0/Moonlight-3.1.0.dmg

**Comment by PolCPP** [comment]
That one works

**Comment by cgutman** [comment]
Ok, thanks for testing. Updated the releases page with the new build.
