### ISSUE TITLE
AZERTY keyboard layout ignored on Raspberry Pi OS Lite

### ISSUE THREAD

**Issue by Jorys-Paulin** [moonlight-stream/moonlight-qt#548]
**Describe the bug**
While playing around with the new "pre-configuration" options of the Raspberry Pi imager, I noticed that even though I've set my keyboard layout to French, inside Moonlight's UI typing the "first keys" AZERTY outputs QWERTY instead. It seems like it's not picking up my keyboard layout and defaults to the American layout instead. I'm running on Raspberry Pi OS lite, up-to-date without XServer or anything like that. While streaming it also does output QWERTY to the host computer, but it might be normal, or Sunshine, or something else.

**Steps to reproduce**
1. Create a new bootable RPI OS Lite installation on a USB stick
2. Change keyboard settings to use French (AZERTY) keyboard layout, reboot for good measure
3. Open the "Add PC" dialog and enter the "first keys" (AZERTY on a French keyboard, QWERTY on an American one)

**Screenshots**
I'm not able to take screenshots from the Raspberry Pi

**Other Moonlight clients**
- The issue doesn't appear using the Windows client
- The issue doesn't appear using the Android client

**Moonlight settings (please complete the following information)**
All settings are default, nothing was changed

**Client PC details**
 - OS: Raspberry Pi OS Lite (January 11th 2021)
 - Moonlight Version: 3.1.0
 - GPU: Broadcom VideoCore VI @ 500 MHz

**Server PC details**
(Not applicable, shouldn't matter)

**Moonlight Logs (please attach)**
[moonlight-log.txt](https://github.com/moonlight-stream/moonlight-qt/files/6175099/moonlight-log.txt)

**Additional context**
While the keyboard layout has been changed, the system language wasn't changed

**Comment by cgutman** [comment]
does it work with X running? I suspect SDL doesn't support keyboard layouts in the KMSDRM backend.

**Comment by Jorys-Paulin** [comment]
Hello, I'll try manually installing `xserver-xorg` by itself. In the meantime, is there a work-around, maybe using an environement variable?

**Comment by cgutman** [comment]
Just run `startx`, though if you don't have a desktop environment installed, you probably won't get very far in X.

**Comment by Jorys-Paulin** [comment]
Oh my, after installing both `xserver-xorg` and `xinit`, I was able to run `startx moonlight-qt` and it actually worked! Now, it shows a small white terminal and then the main Moonlight window in like 1600x720px and in the top left, but the keyboard layout is correct!

**Comment by Jorys-Paulin** [comment]
After some more testing, it seems like while streaming the keyboard layout is correct, though the Ctrl+Shift+Alt+Q shortcut is still bound to client-side layout.

I also noticed that performance while using either command-line only or `startx` was worse than regular Raspbian with the desktop environment installed and all. Performance even varies if using `startx moonlight-qt` or `startx $(moonlight-qt >> log.txt)`, again decoding times are always higher than regular Raspbian.

I'm wondering if there's something that can be done about it, wether it's reporting the bug to Qt themselves, using a variable or just mentioning this issue on the wiki.
