### ISSUE TITLE
2 displays

### ISSUE THREAD

**Issue by LinkSayrus** [moonlight-stream/moonlight-qt#55]
**Describe the bug**
If there are 2 displays connected to the client, the mouse is not fixed on the display and the Moonlight client always turns off.

**Steps to reproduce**
Play in any action)

**Screenshots**
----

**Moonlight settings (please complete the following information)**
Full-Screen on

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1803]
 - Moonlight Version: [e.g. v0.3.0]

**Logs (please attach)**
---

**Additional context**
---

**Comment by cgutman** [comment]
Can you provide more details on the exact issue you're seeing? I don't understand what you mean by "mouse isn't fixed" or "Moonlight client always turns off". And it's your client with 2 monitors not your server? Do you have your monitors configured in Surround or Eyefinity?

I run 2 monitors on my workstation (where I write Moonlight) and everything works as expected on the various OSes I test on that machine (Fedora 28, Win7, Win 8.1, and Win10 RS5). I've also successfully used multiple displays on macOS High Sierra.

**Comment by LinkSayrus** [comment]
The mouse cursor is not fixed (located) on the display where the moonlight client is running, in full-screen mode. When the mouse moves in the game, the cursor moves to the second display and when the mouse is pressed (when the cursor is located on the 2nd display), the client collapses.

In windowed mode, the cursor is fixed in the moonlight window until you release it by pressing Ctrl + Alt + Shift + Z

**Comment by LinkSayrus** [comment]
Only remote access programs such as: temwiever, radmin

**Comment by cgutman** [comment]
Hmm, I don't think Radmin is commonly used, so it could be the cause. I can see reasons why remote control programs would try to avoid mouse capture (issues uncapturing, incompatibility with relative mode capture with most normal remote control apps not designed for gaming). It also looks designed for businesses where breaking games wouldn't likely be noticed.

**Comment by cgutman** [comment]
That's probably because the old Chrome and Java clients didn't use exclusive full-screen mode like the new client does. It remove a frame of video latency so it's a great benefit.

Can you try another program on your client PC that uses exclusive full-screen move and mouse capture like a first-person shooter?

Does the problem resolve if you uninstall Radmin?

**Comment by LinkSayrus** [comment]
In general, the problem was solved.
This happened when I changed screens using Alt + Tab. Then the mouse was not fixed, but after pressing Ctrl + Alt + Shift + Z (2 times) the problem disappears.

**Comment by PatiB87** [comment]
I also noticed that with 2 monitors active I get flickering in certain games on fullscreen mode. Although this might be an Nvidia issue since Steam in home streaming is doing it too, when I turn nvidias direct frame buffer copy on there as well.

**Comment by cgutman** [comment]
@PatiB87 I'm assuming that's 2 monitors on the host side.

This issue is about 2 monitors on the client side and the issue seems to be resolved.
