### ISSUE TITLE
Numpad not working in remote desktop 

### ISSUE THREAD

**Issue by bobbybean** [moonlight-stream/moonlight-qt#552]
**Describe the bug**
Numpad doesn't appear to work in moonlight/gamestream. Have tried various full size keyboards, the numpad keys don't work in moonlight, however numbers below the f1 keys work fine. 

**Steps to reproduce**
Tested on keyboards: 
g613
g915 

**Affected games**
Have only tested in Windows 10, desktop

**Other Moonlight clients**
QT version

**Comment by cgutman** [comment]
I'm not able to reproduce this issue on my Windows 10 client machine. The numpad keys work fine for me.

Are they producing the non-NumLock functionality (arrow keys) or nothing at all?

One thing that can cause numpad keys to not work properly is if the NumLock state is not matching on the client and host PC. The numlock light on your keyboard just indicates the numlock state of your client system. The host system may have numlock in a different state, and the host system's numlock state will prevail over the function of the number pad keys.

A trick to flip the numlock state if it gets desynchronized with the host is to toggle it on your client while the Moonlight stream is not the active window.

**Comment by bobbybean** [comment]
I found out the culprit. I had switched on control mouse with "numpad". This was a workaround to make my mouse appear. When this option is turned off the mouse often dissapears.

**Comment by reloxx13** [comment]
ahh right i have the same problem caused by enbling this option cause of a missing mouse.
