### ISSUE TITLE
Font-Size of Moonlight Gui (Raspberry Pi3)

### ISSUE THREAD

**Issue by Ramalama2** [moonlight-stream/moonlight-qt#555]
Hi, when i start moonlight-qt from cli on the pi3, the fontsize of the Gui is extremely small.
The output is an normal 1080P LG TV.

The games itself or everything else moonlight related, works amazingly good.
Just the fontsize in the moonlight-gui itself is unreadable.

Is there any argument or something i could give moonlight to increase the fontsize?
the gui is a bit broken too, but the main issue is the font i think xD

See pictures below xD
![16166301315322722404494666483592](https://user-images.githubusercontent.com/6314556/112398692-04370680-8d05-11eb-9401-c2d667ee7d89.jpg)
![IMG_20210325_005023](https://user-images.githubusercontent.com/6314556/112398727-131db900-8d05-11eb-98a8-6a99606a9f8f.jpg)

**Comment by Ramalama2** [comment]
FML, while the performance of the pi3 is good.
The pi4 is another world, it's realtime xD

Forget this bugreport, i close it, the pi3 is useless, thanks anyway! xD

**Comment by ambientsound** [comment]
I have the same issue with small font size on Raspberry Pi 4.

**Comment by SearingEchoes** [comment]
I have this issue on a RPI4 with Raspberry pi OS Lite 64bit.
