### ISSUE TITLE
[X11] Frame rate limited to slowest monitor refresh rate

### ISSUE THREAD

**Issue by DarkArc** [moonlight-stream/moonlight-qt#557]
**Describe the bug**
Under X11, if one monitor is running at say 144hz and the second monitor is running at 60hz, moonlight will limit the decoding frame rate to 60fps.

**Steps to reproduce**
- Two monitors, one running above 60hz, one running at 60hz.
- Run moonlight qt on the monitor running > 60hz (e.g. 144hz monitor)
- Observe frame rate information

**Moonlight settings (please complete the following information)**
- Set framerate to 144hz, also set video to 1440p
- Vsync setting doesn't seem to have an impact

**Client PC details (please complete the following information)**
 - OS: Fedora 33 (KDE Spin)
 - Moonlight Version: 3.1.0 (flatpak)
 - GPU: Nvidia Gtx 970
 - Nvidia GPU driver: 460.67

**Server PC details (please complete the following information)**
 - OS: Windows 10 19042.868
 - GeForce Experience version: 3.21.0.36
 - Nvidia GPU driver: 461.92
  - GPU: Nvidia Rtx 2080
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Comment by DarkArc** [comment]
[bad.log.txt](https://github.com/moonlight-stream/moonlight-qt/files/6216315/bad.log.txt)
[ok.log.txt](https://github.com/moonlight-stream/moonlight-qt/files/6216316/ok.log.txt)

The only difference here is the in `ok.log.txt` the 60hz monitor (HDMI) was disabled in KDE display settings, in bad.log.txt the 60hz monitor was enabled.

**Comment by maxiberta** [comment]
As far as I know, [that's a known limitation on X11](https://www.phoronix.com/scan.php?page=news_item&px=KWin-2021-Better-Experience), where compositing is throttled to the lowest common refresh rate in multi-screen setups. But fortunately, it can be overriden. I'm using KDE on a 60+120Hz setup myself at 120Hz with an Nvidia GPU on X11 on Ubuntu, with Moonlight reporting incoming/decoding/rendering frame rates of 120Hz. You'll find lots of people with the same issue if google something like "kwin refresh rate", but here's a summary of my experience:

* On KDE >= 5.21 + Wayland, [each display should refresh at its own native refresh rate](https://kde.org/announcements/plasma/5/5.21.0/) automagically.

* On KDE >= 5.21 + X11, try these environment variables (see [kde bug #433094](https://bugs.kde.org/show_bug.cgi?id=433094#c15)):
```sh
KWIN_X11_REFRESH_RATE=144000
KWIN_X11_NO_SYNC_TO_VBLANK=1
KWIN_X11_FORCE_SOFTWARE_VSYNC=1
```
* On KDE < 5.21, you can try setting under `[Compositing]` in kwinrc, as explained in [kwin-lowlatency's README](https://github.com/tildearrow/kwin-lowlatency#old-background):
```
MaxFPS=144
RefreshRate=144
```
... or just try [kwin-lowlatency](https://github.com/tildearrow/kwin-lowlatency).

* I've also had good results with these env vars:
```sh
KWIN_OPENGL_INTERFACE=egl
__GL_SYNC_DISPLAY_DEVICE=DP-0  # your 144Hz display name here
```

**Comment by DarkArc** [comment]
I was under the impression this is a limitation as well, until today, when someone corrected me on reddit :)

It seems X11 KDE does set one monitor to 144hz and the other to 60hz, moonlight seems to be "stuck" at 60hz though. The compositing settings also shouldn't be affecting anything as I understand it, as the compositing should be disabled by moonlight, no?
