### ISSUE TITLE
Solved: Segfault with jetson nano 4gb on latest sdk

### ISSUE THREAD

**Issue by jpecih** [moonlight-stream/moonlight-qt#559]
When installing a fresh l4t 18.04 ubuntu on my jetson nano 4gb, following github installation procedure, and launching moonlight-qt, segfault always occurs.

Distributor ID:    Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:    18.04
Codename:    bionic

root@jl-desktop:/home/jl# moonlight-qt
00:00:00 - SDL Info (0): Compiled with SDL 2.0.15
00:00:00 - SDL Info (0): Running with SDL 2.0.15
00:00:00 - Qt Info: No translation available for  "es_ES"
00:00:00 - Qt Info: No existing credentials found
00:00:00 - Qt Info: Wrote new identity credentials to settings
00:00:01 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:01 - SDL Info (0): Loaded 106 new gamepad mappings
00:00:01 - SDL Info (0): V-sync enabled
00:00:01 - SDL Info (0): Using SDL renderer
00:00:01 - FFmpeg: [h264_mp4toannexb @ 0x558fb8f050] The input looks like it is Annex B already
Opening in BLOCKING MODE
Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
Segmentation fault (core dumped)

**Comment by KiralyCraft** [comment]
Attaching some relevant info: 
https://media.discordapp.net/attachments/465383758061895680/826096536714346526/20210329_161233.jpg
https://media.discordapp.net/attachments/465383758061895680/826096806130614332/20210329_161335.jpg

Happens with Moonlight 3.1.0, 3.0.0 (did not test lower?); The version of the nvmpi library should be checked soon

**Comment by jpecih** [comment]
I am answering myself. Thanks to BenchBot for the support. I installed jetpack sdk 4.4.1 from oct/2020 archived versions and everything worked as a charm. 
To conclude, latest official sdk produces segfault on my jetson 4gb when executing moonlight-qt.

**Comment by johnnyvf24** [comment]
+1 Would love if someone could fix this on jetpack sdk 4.5.1 :) Thanks

**Comment by cgutman** [comment]
Fixed in v4.0.0 by #745
