### ISSUE TITLE
Can pair and connect with Android app, but not Windows client

### ISSUE THREAD

**Issue by Norumu** [moonlight-stream/moonlight-qt#56]
**Describe the bug**
I have a GameStream PC that I'm trying to connect to on my laptop via internet, but the x64 Windows client is spitting out the error "Unable to connect to the specified PC. Ensure GameStream is enabled in GeForce Experience." What's notable is that the Moonlight Android app can pair and successfully connect with the very same PC, no problems.

**Steps to reproduce**
Load up Windows app > Add PC > enter IP address > get error message "Unable to connect to the specified PC. Ensure GameStream is enabled in GeForce Experience."

**Screenshots**
![image](https://user-images.githubusercontent.com/42848288/44874563-69f7aa80-ac50-11e8-89c5-ec224b197138.png)

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Nope, no changes.

**Client PC details (please complete the following information)**
 - OS: Windows 10 Pro build 17134
 - Moonlight Version: 0.3.0 x64, both Setup and Portable versions.

**Logs (please attach)**
[Moonlight-1535657281.log](https://github.com/moonlight-stream/moonlight-qt/files/2337626/Moonlight-1535657281.log)

**Additional context**
- This laptop was able to connect to the target Gamestream PC when it was on the same local network.
- Android app on Pixel 2 is able to connect to the target Gamestream PC via internet, on both mobile network and same wifi network the laptop is on.

**Comment by cgutman** [comment]
Any firewall or AV software on that client PC?

**Comment by Norumu** [comment]
> Any firewall or AV software on that client PC?

Just the standard Windows firewall. Turning it off entirely doesn't change anything.

**Comment by cgutman** [comment]
Ok, if I'm understanding correctly, you mention that you are able to connect with this PC when you're on the same network, just not outside the network using your public IP address?

**Comment by Norumu** [comment]
Correct. This PC client was able to connect to the GameStream PC while on the same local network, but not when outside the network.

I have a Pixel 2 phone with the Android app that is able to connect the GameStream PC while on the same local network and from an outside network, including the same wifi network the PC client is failing to connect through.

**Comment by cgutman** [comment]
Ok, and if you type the same IP address that you're trying to use on the PC into the Add PC dialog on Android, no errors?

**Comment by Norumu** [comment]
No errors. I just removed the pairing from the Android device, restarted it, and added it back with the same IP address, and the Android app is able to pair and connect completely.

**Comment by cgutman** [comment]
Does the error message appear almost immediately after clicking OK on the Add PC dialog or does it take several seconds?

**Comment by Norumu** [comment]
It takes a few seconds after clicking OK

**Comment by cgutman** [comment]
Interesting, if you try to access http://[your IP address]:47989/serverinfo (replace [the text in brackets] with your IP address) on your PC and phone, does that work?

**Comment by Norumu** [comment]
The phone shows me a big ol' string of info. The client PC laptop returns with a connection timeout. Definitely seems like something about the laptop is blocking this, but I can't fathom what it is.

**Comment by cgutman** [comment]
Got any VPN software on that machine?

**Comment by Norumu** [comment]
No VPN software, no VPNs setup in Windows.

**Comment by Norumu** [comment]
I just did a bit more playing around, and I think it is an issue with the hotel's network that I'm on. I shut off the mobile data on the Android device, but kept the wifi, and it was unable to connect to the Gamestream PC. I'm guessing my phone piggybacked the mobile network to connect (though, interestingly, the app doesn't warn for the metered network like it does on a pure mobile network connection).

So, I'm willing to bet it's something in this network being the block. No idea what, nor will I find out, but sorry to waste your time and attention!

**Comment by cgutman** [comment]
Thanks, it's not a problem at all. From your logs, I realized I'm not actually logging anything when adding a PC fails, so there is a bug for me here after all.

**Comment by Norumu** [comment]
Well, glad to be of service! 👍 
Thanks for your work and support!
