### ISSUE TITLE
GeForce Experience Beta 3.22.0.28 breaks streaming

### ISSUE THREAD

**Issue by marcusboon** [moonlight-stream/moonlight-qt#561]
It looks like GFE 3.22.0.28 has broken the RTSP handshake. Have confirmed that both TCP and UDP port 48010 are unblocked but moonlight is failing the RTSP handshake with either error 500 or 35 now.

Attaching logs:
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/6272051/NvStreamerCurrent.log)

**Comment by beckershoff** [comment]
Yup, can confirm this bug as well. Looks like Nvidia made some changes in the latest release 😔

**Comment by cgutman** [comment]
Yep, we're aware. I'm working on fixing it, but it doesn't look simple.

**Comment by marcusboon** [comment]
After a DDU and re-install of the latest geforce drivers + GFE (non-beta) I can confirm that streaming is working again. A bit worrying though if that beta change makes it to stable.

**Comment by quesog** [comment]
Looks like [Moonlight 3.1.1](https://github.com/moonlight-stream/moonlight-qt/releases/tag/v3.1.1) fixes streaming from GFE 3.22. Thanks for the quick work, devs!

**Comment by cgutman** [comment]
Yep, streaming should work with Moonlight v3.1.1.
