### ISSUE TITLE
PlayStation 4 Controller stopped working with Moonlight 3.0.0 & 3.1.0

### ISSUE THREAD

**Issue by abusse** [moonlight-stream/moonlight-qt#562]
**Describe the bug**
The PlayStation 4 controller does no longer work in Moonlight 3.0.0 and 3.1.0 under Linux. It works without any issues in Moonlight 2.2.0.

**Steps to reproduce**

Working in 2.2.0:

1. Connect PlayStation 4 controller to Linux via Bluetooth
2. Launch Moonlight 2.2.0
3. Go to https://html5gamepad.com
4. Observe that the PlayStation 4 controller works

Non-working in 3.0.0 and 3.1.0:

1. Connect PlayStation 4 controller to Linux via Bluetooth
2. Launch Moonlight 3.0.0 or 3.1.0
3. Go to https://html5gamepad.com
4. Observe that no controller is detected and the quit-combo does not work as well

**Affected games**
All games and software are affected.

**Other Moonlight clients**
I have not tested other clients

**Moonlight settings**
The issue persists when reverting to default settings

**Gamepad-related issues**
- Do you have any gamepads connected to your host PC directly? No
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad? Yes

**Client PC details (please complete the following information)**
 - OS: Linux, Kernel version 5.4.97
 - Moonlight Version: 3.0.0 and 3.1.0
 - GPU: Intel UHD Graphics 605

**Server PC details (please complete the following information)**
 - OS: Windows 10 20H2
 - GeForce Experience version: 3.21.0.36
 - Nvidia GPU driver: 465.89
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Moonlight Logs**

[moonlight-2.2.0.log](https://github.com/moonlight-stream/moonlight-qt/files/6280589/moonlight-2.2.0.log)
[moonlight-3.1.0.log](https://github.com/moonlight-stream/moonlight-qt/files/6280591/moonlight-3.1.0.log)

**Comment by cgutman** [comment]
What package of Moonlight are you using? Snap/Flatpak/AppImage?

**Comment by abusse** [comment]
Neither, I build it from source.

**Comment by abusse** [comment]
I just dug a litte through the code and noticed that v3.0.0 introduced a new setting toggling the controller input when Moonlight is in background. Changing this settings makes the controller work again. However, since in my setup Moonlight is literally the only program running that raises the question why it thinks it is in background. As this is a hole different issue that I will have to look into more detail first, this one here can be closed.

**Comment by cgutman** [comment]
It may relate to your particular window manager. SDL depends on the WM to keep it informed of input focus.
