### ISSUE TITLE
Moonlight stream loses 60hz fluidity when V-Sync is off.

### ISSUE THREAD

**Issue by Dantido2** [moonlight-stream/moonlight-qt#563]
**Describe the bug**
For some unknown reason, Moonlight streams may start to lose smoothness and stop to feel like 60hz, but rather lower (30hz), even though the game is running at 60FPS on the host and the stream GUI says the streaming is being rendered at 60FPS. 
This only happens when V-Sync is off.

**Steps to reproduce**
Start a Moonlight client with V-Sync off.

**Screenshots**
If it is extremely needed, I may try to record, but it's going to be extremely hard considering my client PC is an extremely CPU-bottlenecked machine.

**Affected games**
I've tried this, so far, with the Mouse Fix available on the official discord. I've never tried streaming individual games.

**Other Moonlight clients**
I've never tried iOS/Android Moonlight, so I sadly can't say for sure.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Yes.
- If so, which settings have been changed? V-Sync has been turned off, and the bitrate has been set from the default to 47mbps.
- Does the problem still occur after reverting settings back to default? No, as the V-Sync is therefore enabled. However, V-Sync causes a lot of latency.

**Client PC details (please complete the following information)**
 - OS:  Windows 7
 - Moonlight Version:  Latest available for Windows.
 - GPU: GT 1030

**Server PC details (please complete the following information)**
 - OS: Windows 10 1909
 - GeForce Experience version: Latest stable batch (non-beta)
 - Nvidia GPU driver: 456.71
 - Antivirus and firewall software: Windows Defender and Windows Firewall.

**Moonlight Logs (please attach)**
[Moonlight-1617980528.log](https://github.com/moonlight-stream/moonlight-qt/files/6289773/Moonlight-1617980528.log)

**Additional context**
I know things like this can be subjective, but trust me when I say the difference between the fluidity of V-Sync on and off is VERY noticeable.

**Comment by cgutman** [comment]
It looks like there are a ton of dropped frames due to packet loss on the connection between the host and client. Are you sure that's not what you were experiencing?

**Comment by Dantido2** [comment]
Actually, that might be the problem. Still, I couldn't see the "Frames
dropped due to network connection." going up when the V-Sync lost fluidity.
I'll try it again now that I have a more stable connection between host and
client and see if it works.
