### ISSUE TITLE
Cursor shift bug

### ISSUE THREAD

**Issue by animaion** [moonlight-stream/moonlight-qt#565]
Hi,

Thanks a lot for the great remote access solution.
I noticed serious UI bug – cursor (virtual) is shifted. It is quite annoying for precision (3D, graphic) jobs. If this could be improved then Moonlight would come much closer to perfection.
Graphics attached to illustrate the problem.
Server: W10. Client: Mac

Best regards,
Bo

![Moonlight_CursorShift](https://user-images.githubusercontent.com/55259287/114355892-48812e00-9b70-11eb-9c83-f324a16982f3.gif)
![Moonlight_CursorShift_realscale](https://user-images.githubusercontent.com/55259287/114356011-68185680-9b70-11eb-8ea7-6d397382ca1c.png)
![Moonlight_CursorShift](https://user-images.githubusercontent.com/55259287/114356018-6a7ab080-9b70-11eb-8e15-8c995a06cbc5.png)

**Comment by cgutman** [comment]
Duplicate of #521
