### ISSUE TITLE
Overcooked game title embedded in BoxArt

### ISSUE THREAD

**Issue by michellabbe** [moonlight-stream/moonlight-qt#567]
**Describe the bug**
Overcooked BoxArt has an annoying "Overcooked" raw text embedded in the middle of the Box Art.  As far as I can recall, Moonlight-QT always had this issue on this title (multiple windows/moonlight/nvidia driver/software versions). I first thought it was a nVidia issue, but the BoxArt appears fine on a Shield Pro.

I also just realized that the png file in the Moonlight cache folder doesn't have this embedded text so it definitely seems like an issue in Moonlight and not with the png file that is pulled from nVidia or some BoxArt website.

Also, if I mouseover this BoxArt, the game name doesn't appear (grey label that pops up over the BoxArt doesn't show up at all) like other games.

**Screenshots**
![Moonlight_Overcooked_BoxArt](https://user-images.githubusercontent.com/16291382/114477278-f8cf5080-9bc9-11eb-9d6b-417ccb12b2cb.png)

![Overcooked_cache](https://user-images.githubusercontent.com/16291382/114478506-62e8f500-9bcc-11eb-87c7-de71bfb5629e.png)

![419927105](https://user-images.githubusercontent.com/16291382/114478526-6ed4b700-9bcc-11eb-8afd-19c9dd353dd6.png)

**Affected games**
Overcooked (steam ID: 448510)

**Other Moonlight clients**
N/A

**Moonlight settings (please complete the following information)**
N/A

**Gamepad-related issues (please complete if problem is gamepad-related)**
N/A

**Client PC details (please complete the following information)**
 - OS: Windows 10 (20H2, 2004, 1909, 1903, 1809, etc.), Ubuntu (16, 18, 20), Raspberry Pi
 - Moonlight Version: multiple (currently 3.1.1)
 - GPU: nVidia RTX 2060, 1070, 970

**Server PC details (please complete the following information)**
 - OS: Windows 10 (20H2, 2004, 1909, 1903, 1809, etc.)
 - GeForce Experience version: all versions from the last 2-3 years (currently 3.22.0.32).
 - Nvidia GPU driver: all versions from the last 2-3 years (currently 461.40)
 - Antivirus and firewall software: Windows Firewall and Bitdefender Total Security

**Moonlight Logs (please attach)**
[Moonlight-1618273923.log](https://github.com/moonlight-stream/moonlight-qt/files/6300495/Moonlight-1618273923.log)

**Additional context**
The game doesn't appear in the list of games on GeForce Experience Home screen but doesn't need to be added manually to appear in Moonlight/Shield.

**Comment by Jorys-Paulin** [comment]
Hello, I've noticed that issue as well, it turns out this cover art is 628x888px, exactly the dimensions of the "default" cover art, and that's what Moonlight uses to detect it (because GFE doesn't mention if it's a default cover art or not).
The only way to fix it would be to ask NVIDIA to change it (to the normal resolution of 300x400px), and the issue would go away, but I don't know how we can contact them about that.

**Comment by michellabbe** [comment]
> The only way to fix it would be to ask NVIDIA to change it (to the normal resolution of 300x400px), and the issue would go away, but I don't know how we can contact them about that.

I can try to [report it to nVidia](https://www.nvidia.com/support/), but I doubt they will care fixing an issue that doesn't affect their product (although it's much less effort to resize a png file than fix some memory leak issue in their driver).

Isn't it possible to patch directly in Moonlight for this particular game name, png filename/checksum or something?

e.g. check picture size when saving/loading the png to/from the Moonlight **boxart** cache folder and resize to 300x400px if needed.  That would fix any similar issue with other BoxArts in the future.

As a workaround, I resized the png file manually in the cache folder and I confirm the issue went away.

**Comment by Jorys-Paulin** [comment]
Moonlight could add an exception for Overcooked's app ID as sent by GFE, but I'm not sure if it's the same for everyone. That would be the cleaner way going forward, even if it would be better if NVIDIA just sized that covert art correctly.

**Comment by michellabbe** [comment]
I reported the non-standard size of Overcooked BoxArt file to nVidia Support (ref: #210413-000663), and also via the "Send feedback" option at the bottom right of the GFE window.

We'll see if that goes anywhere...

I don't understand why Moonlight needs to make a difference between a "default" cover art and regular BoxArt.  I only see one type/size of game pictures (BoxArt) shown in Moonlight.  And it doesn't quite make sense to me that Moonlight rely only on picture resolution to determine if a png file is a BoxArt or a "default" cover art, when all BoxArt files are stored in a cache folder under the name "boxart".

IMHO it would be more future-proof to just make sure BoxArt files are properly scaled to 300x400 before processing them in Moonlight (or treat all files in Moonlight\cache\boxart\ folder as actual boxart).  That would also prevent the same issue to happen with custom BoxArt files for games added manually by users in GFE.

If you prefer the Overcooked app ID exception route anyway, then it looks like the app ID is the same for everyone:

From [https://services.gfe.nvidia.com/GFE/v1.0/streaming-assets/overcooked](https://services.gfe.nvidia.com/GFE/v1.0/streaming-assets/overcooked)
(thanks to @dr00t with [#181](https://github.com/moonlight-stream/moonlight-chrome/issues/181#issuecomment-275861374))

Comparing with similar links for other games, the original Overcooked non-standard png file seems to be this one:
[http://download.gfe.nvidia.com/GFE/ops/streamingassets/overcooked/21091944/overcooked-box-art.png](http://download.gfe.nvidia.com/GFE/ops/streamingassets/overcooked/21091944/overcooked-box-art.png)

And the [StreamingSettings.json](http://download.gfe.nvidia.com/GFE/ops/streamingassets/overcooked/21091944/StreamingSettings.json) provides the GFE unique app ID:

`            "VersionName": "steam-generic",`
`            "StreamingDisplayName": "Overcooked",`
**`            "UniqueId": "18655001",`**
`            [...]`
`            "SteamAppID": 448510,`

**Comment by Jorys-Paulin** [comment]
Moonlight needs to detect this because that's how it chooses to display the text or not, for games with covert art the game's title is burned in so no need to display the game a second time, but for apps with no cover art, you need to determine which one is which, and that's where the text shows up.

GFE doesn't send any information about the cover art to Moonlight, including whether or not it's a default image:
```xml
<App>
  <AppInstallPath>D:\SteamLibrary\steamapps\common\Overcooked\</AppInstallPath>
  <AppTitle>Overcooked</AppTitle>
  <CmsId>18655111</CmsId>
  <Distributor>Steam</Distributor>
  <ID>128036890</ID>
  <IsAppCollectorGame>0</IsAppCollectorGame>
  <IsHdrSupported>0</IsHdrSupported>
  <MaxControllersForSingleSession>4</MaxControllersForSingleSession>
  <ShortName>overcooked</ShortName>
  <SupportedSOPS>
    <SOPS>
      <Height>720</Height>
      <RefreshRate>30</RefreshRate>
      <Width>1280</Width>
    </SOPS>
    <SOPS>
      <Height>720</Height>
      <RefreshRate>60</RefreshRate>
      <Width>1280</Width>
    </SOPS>
    <SOPS>
      <Height>1080</Height>
      <RefreshRate>30</RefreshRate>
      <Width>1920</Width>
    </SOPS>
    <SOPS>
      <Height>1080</Height>
      <RefreshRate>60</RefreshRate>
      <Width>1920</Width>
    </SOPS>
  </SupportedSOPS>
  <UniqueId>18655001</UniqueId>
  <simulateControllers>0</simulateControllers>
</App>
```

Here's the bit of code where Moonlight compares the resolution to try and figure out if it's a default box art: https://github.com/moonlight-stream/moonlight-qt/blob/21be832161e05ec6d2bc9fb99ba4d672ff6fb2d4/app/gui/AppView.qml#L91-L96

Nothing in the files you linked seems to indicate this as well, there's just information about the file. I don't know any app that doesn't have a placeholder cover (apart from custom ones) so I can't determine if in those cases the metadata is different.

The problem with resizing all images would be that Moonlight wouldn't know what image is a placeholder anymore, since all of them would have the same resolution, breaking the text label code above.

**Comment by michellabbe** [comment]
Thanks for the explanations.  I haven't seen these placeholders very often (I quickly make sure all my games have proper boxart) and hadn't noticed the joypad in the middle.  I thought it was just an empty placeholder (without picture at all) so I thought the mechanic was:
- png file = show the png as boxart
- no png file = show the game name as text in the middle of the (empty) placeholder

I tested adding a game manually, without boxart, and I now see the default placeholder png file added to the cache folder.  That makes sense now :)

How about adding the exact filesize of these default placeholder files in that part of the code to improve detection?  They seem to always be a copy of the exact same file (it's not like nVidia changes them every couple months).

e.g. (don't know the proper syntax but you'll get the point)
`if (sourceSize.width == 628 && sourceSize.height == 888 && sourceSize.filesizebytes == 6768)`

Checking CRC or hash could be an even better way to identify as default placeholder image or not, but it takes some time to calculate and would probably slow down (alot) loading time to display them in the UI so not a good idea.

**Comment by Jorys-Paulin** [comment]
Maybe it could work, hopefully every cover art is the exact same filesize, including after compression.

**Comment by michellabbe** [comment]
I tested with a couple games on two different Win10 computers yesterday, and they all had the same size/hash.

It might be worth also checking on different OS (might use different compression, ending up with different filesizes) though.

I could also check Ubuntu 20 and RPi4, but I'm having a hard time finding where the cache folder is on these OS.

**Comment by michellabbe** [comment]
File size always seem to be the same (6768 bytes) under Win10 (always same hash as well).

File size always seem to be the same (6555 bytes) under Ubuntu 20 and PiOS (always same hash as well).

It would probably require checking with more distros before concluding it's the same for all linux distros (and macos) though.  But with all the distros and versions I think there's good chances the file size could eventually be different and break detection.

Is there a way to check total bytes as sent by GFE (e.g. before OS saves it as png in Moonlight cache folder)?

How about just adding a manual override option we could set/use manually (like "Hide Game") on the rare titles that aren't detected properly like Overcooked?

It could either be a "Force as boxart/empty placeholder" checkbox to force `isPlaceholder = true/false` for that title, or (even simpler) a KISS "Fix boxart dimensions" option that scale this particular boxart to standard 300x400px and overwrite the png file in cache folder without needing to use external apps (and ssh on linux boxes) or changing detection code at all.

**Comment by michellabbe** [comment]
Just got a reply from nvidia level 1 support.  I'm always impressed at how level 1 support (in general) seem to just read a couple random words and make up their mind for what they think an issue could be with these few words.

e.g.
"Can you fix Overcooked boxart png file at this URL, and make it 300x400px like all other games please."

answer:
"From the issue description, I understand that you are facing issues with the game Overcooked on the machine."..

*facepalm"

**Comment by michellabbe** [comment]
Sorry, closed in error.

**Comment by michellabbe** [comment]
> I reported the non-standard size of Overcooked BoxArt file to nVidia Support (ref: #210413-000663).
> 
> We'll see if that goes anywhere...

Reply received today from nVidia Support (escalations group):
> "I will pass on the information but I can't comment on any specific outcome or timetable as to when things might change."

I understand they may or may not fix that png file on their server.

Any thought on a "Resize picture to standard boxart dimension" function?
Assuming it's easy/quick to code (resize to 300x400 and overwrite png file in cache folder, then reload), that would allow to manually fix any occurrence of this issue in just 2 mouse clicks, under any OS.

**Comment by michellabbe** [comment]
@cgutman Is your fix supposed to be included in Moonlight v3.1.2/v3.1.3?

I'm still having the issue with Overcooked in v3.1.3.

**Comment by michellabbe** [comment]
Also I though resizing the png file manually in cache folder would be a good workaround, but the original boxart files are pulled again and overwrite the "fixed one" on every Moonlight update so I'd have to resize the file on all pcs on every moonlight update.

**Comment by michellabbe** [comment]
For the records:

Titanfall 2 also have the same issue.

Native GameStream (on Shield TV) doesn't have this issue because game name is written below all coverart so they don't need to detect if coverart is empty or not.

Best workaround for Moonlight would probably be a "Hide Title" manual toggle similar to "Hide Game" for affected titles.  Seems easier than resizing picture and deal with cache updates/exceptions.
