### ISSUE TITLE
Moonlight not working on any device. Im reading Errors 111 500 and 526 

### ISSUE THREAD

**Issue by gagrecco** [moonlight-stream/moonlight-qt#571]
Im using Geforce version 3.22.0.32. gpu its a 2080 and drivers are v466.11

Im trying to use my switch. Either Moonlight ubuntu or moonlight nx. and even tried with my iphone and nothing. 
let me know if you need more info

**Comment by coolwhg** [comment]
V3.1.1, this problem has been solved

**Comment by cgutman** [comment]
Yes, you need to update Moonlight to the latest version with GFE 3.22 support.
