### ISSUE TITLE
[Recalbox] [W10] blackscreen stream

### ISSUE THREAD

**Issue by Kiri85** [moonlight-stream/moonlight-qt#573]
Hello,

I have a problem since yesterday.
I have recalbox OS on raspi 2 (connexion with RJ45).
I launch moonlight, stream begin and after i have à black screen on my tv.
I update nvidia drivers and software on my pc but doesn't work.

Do you have solution or idea about the problem ?

Tank you for you time and answer.

**Comment by cgutman** [comment]
If you’re using a Raspberry Pi 2, I suspect you are not running Moonlight Qt. It’s more likely that you are using https://github.com/irtimmer/moonlight-embedded

I recommend collecting logs (which may require you to figure out where/if those are stored on Recalbox) and open an issue on the moonlight-embedded.
