### ISSUE TITLE
Moonlight 3.1.1 stream loses 60Hz while 3.1.0 keeps it

### ISSUE THREAD

**Issue by guillaume-thomas** [moonlight-stream/moonlight-qt#576]
Hi !

Updating Moonlight 3.1.0 to 3.1.1 implies a lot of frames drops, with the same network, same configuration. I tried a rollback to 3.1.0 and the stream retrives its solig 60 fps.

Do you know why ? 

GFE version on my Gamestream server is 3.21.0.36. Update it to 3.22.0.2 does not fix my issue.

3.1.0 log : 
[Moonlight-1618679727-3.1.0.log](https://github.com/moonlight-stream/moonlight-qt/files/6329728/Moonlight-1618679727-3.1.0.log)

3.1.1 log : 
[Moonlight-1618679866-3.1.1.log](https://github.com/moonlight-stream/moonlight-qt/files/6329729/Moonlight-1618679866-3.1.1.log)

Thank you very much :)

**Comment by cgutman** [comment]
Hmm, that's definitely strange. I see from your logs that the render time has gone up significantly with 3.1.1 and that it looks like the render frame rate is locked at 30 FPS. However, there are no changes at all to the DXVA2 renderer in 3.1.1. I don't see anything that would explain this issue in the relatively small number of changes between 3.1.0 and 3.1.1.

To help narrow down the cause, can you collect host-side logs with the 3.1.0 and 3.1.1?
1. Use Moonlight 3.1.0 to start a stream, let the stream run for a couple minutes, then quit the stream within Moonlight.
2. On your host PC, collect `C:\ProgramData\NVIDIA Corporation\NvStream\NvStreamerCurrent.log` (name it `NvStreamerCurrent-3.1.0.log` or something)
3. Next use Moonlight 3.1.1 to start a stream, let the stream run for a couple minutes, then quit the stream within Moonlight again.
4. Collect `C:\ProgramData\NVIDIA Corporation\NvStream\NvStreamerCurrent.log` (name it `NvStreamerCurrent-3.1.1.log`)

**Comment by guillaume-thomas** [comment]
Sure ! :)

Same tests as yesterday. 5 minutes of streaming each.

Host-side logs :

3.1.0 : [NvStreamerCurrent-3.1.0.log](https://github.com/moonlight-stream/moonlight-qt/files/6330668/NvStreamerCurrent-3.1.0.log)

3.1.1 : [NvStreamerCurrent-3.1.1.log](https://github.com/moonlight-stream/moonlight-qt/files/6330669/NvStreamerCurrent-3.1.1.log)

Client-side logs : 

3.1.0 : 

3.1.1 : 

Thank you very much for your quick response and your help ;)

**Comment by guillaume-thomas** [comment]
Hello !

In order to help where the issue could possibily come, I forked the project and cherry picked commits from 3.1.0 to 3.1.1. It seems that this particular commit is the cause of my issue :

https://github.com/moonlight-stream/moonlight-qt/commit/e74753bec15b5c0c021a2d0fc03811cf9cd68d3e

Do you know why ?

Thank you very much !

**Comment by guillaume-thomas** [comment]
All right, I built a release without these commits : https://github.com/moonlight-stream/moonlight-qt/commit/e74753bec15b5c0c021a2d0fc03811cf9cd68d3e, https://github.com/moonlight-stream/moonlight-qt/commit/74bf981f3d209a2ed2dcf70d2a6cda7fd2bd2f3a and https://github.com/moonlight-stream/moonlight-qt/commit/02e3f0e71bff5e2647fde427b41a68a6144cff90.

It works perfectly with GFE 3.22.

**Comment by cgutman** [comment]
Thank you for investigating.

That result is quite odd. The EGL codepath isn't even compiled on Windows and `testRenderFrame()` isn't implemented for the DXVA2 renderer, so I'm not sure how it could affect things. I will have to look more.

In the meantime, can you provide info for the rest of the bug report template?

**Affected games**
List the games you've tried that exhibit the issue. To see if the issue is game-specific, try streaming Steam Big Picture with Moonlight and see if the issue persists there.

**Steps to reproduce**
Any special steps that are required for the bug to appear.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - Moonlight Version: [e.g. v0.9.0]
 - GPU: [e.g. Intel HD Graphics 520]

**Server PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - GeForce Experience version: [e.g. 3.16.0.140]
 - Nvidia GPU driver: [e.g. 417.35]
 - Antivirus and firewall software: [e.g. Windows Defender and Windows Firewall]

**Additional context**
Anything else you think may be relevant to the issue

**Comment by cgutman** [comment]
I've scrutinized that code for quite a while. I also stepped through it in the debugger to validate my assumptions about the control flow there and didn't see anything wrong. I also validated that we never hit the codepath in `SdlRenderer::testRenderFrame()` where we initiate read-back.

The only behavior change I could discern is that we are doing a little extra work initializing the decoder for EGL even though we don't support EGL on Windows. I've fixed the redundant initialization in 8fcef63890279b69ba56982ef60b6b3a5df20e91. At the very least, it should be a small speed improvement for launching streams and starting Moonlight.

Please try the latest build with that fix and report your results: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/38961104/job/5uqqlb0c4e9wnkrk/artifacts

**Comment by guillaume-thomas** [comment]
Hello ! Sorry for this late reply !


Thank you very much ! I will provide you the bug report and test this build today :)

**Comment by guillaume-thomas** [comment]
Affected games
    All games, including Steam Big Picture

Steps to reproduce
    Install the latest release 3.1.1 on Windows. The streaming turns from 60hz on the 3.1.0 version to 30hz for the new one.

Other Moonlight clients

    I don't know. It seems to be a Windows only issue.

Moonlight settings (please complete the following information)

    All default. Resolution is set to 4K with 60fps.

Client PC details (please complete the following information)

    OS: Windows 10
    Moonlight Version: 3.1.1
    GPU: Nvidia GTX 1050 

Server PC details (please complete the following information)

    OS: Windows 10
    GeForce Experience version: 3.21.0.36 and 3.22.0.2
    Nvidia GPU driver: 466.11
    Antivirus and firewall software: Avast and Windows Firewall

Additional context
Exclude this commit resolve the issue : e74753b

**Comment by guillaume-thomas** [comment]
Hi ! Unfortunately, the Portable version (x64) crashes when I try to launch it. I can try to build a version from my computer. Which branch should I use ?

Thank you very much :)

**Comment by guillaume-thomas** [comment]
Alright, I'm building master and testing. I will give you a response today.

**Comment by cgutman** [comment]
> Hi ! Unfortunately, the Portable version (x64) crashes when I try to launch it. I can try to build a version from my computer.

Can you upload the crash dump (.dmp) file here and log from that build here? It should be in the same folder as Moonlight.exe.

**Comment by guillaume-thomas** [comment]
Hello !

I have tested your build this morning and this time, Moonlight.exe has not crashed. Maybe my OS or antivirus broke something.

So I have launched a streaming and .... your fix works !!!! :) 60fps while streaming Steam BigPicture. I will test some games but it seems to me that it is OK now :)

Thank you very much !

**Comment by cgutman** [comment]
Great! I guess we must have triggered a driver bug or something when initializing the DXVA2 decoder twice. I don't understand it, but at least it's fixed.
