### ISSUE TITLE
Wake-on-Lan proxy

### ISSUE THREAD

**Issue by Jorys-Paulin** [moonlight-stream/moonlight-qt#577]
**Is your feature request related to a problem? Please describe.**
I have a router at home, provided by my ISP, that has a Wake-on-LAN proxy, and I was wondering if Moonlight could, while streaming from outside the local network, make a WOL request compatible with the proxy, so a distant computer can be turned on even if the client device isn't on the local network.

**Describe the solution you'd like**
Moonlight could execute code with a similar effect to the following Linux command taken from https://doc.ubuntu-fr.org/wakeonlan:
```sh
wakeonlan -i 78.yyy.xxx.zzz 00:0D:9D:9B:BA:xx
```
It sends the WOL packet to 78.yyy.xxx.zzz, the public address of the router, and includes the MAC address of the computer to turn on. If the router supports WOL proxy, it should wake the target computer on, otherwise, nothing should happen.

**Describe alternatives you've considered**
Wake-on-LAN over the WAN can already be achieved by forwarding the port used inside the router (either 0, 7 or 9 apparently), but this limits the use to only one computer per network and requires another port to be opened.

**Comment by cgutman** [comment]
Moonlight does already send WOL packets to the PC's external IP address (and every other address we know of). I'm pretty sure this should work already, since AFAIK the "proxy" WOL packets are just normal WOL packets relayed via a separate host.

https://github.com/moonlight-stream/moonlight-qt/blob/master/app/backend/nvcomputer.cpp#L148

Have you tried it? Can you capture packets from Moonlight and from the other tool and compare them?

**Comment by Jorys-Paulin** [comment]
Hello, I was asking if Moonlight already supported this, since with my network setup it doesn't work. However, I wasn't sure if it was because of my setup (which includes an old system wired to an ADSL+4G internet connection) or because Moonlight didn't implement it (and I didn't know where to look in the code either).

In the end seems like there's a problem with my weird network setup, where WOL works locally but not over the Internet. I'll continue investigating to see if I can make it work, tough my packet capture skills are low to say the least.

Would you recommend a proxy over opening ports? Over on the Discord server we currently recommend either opening ports or using a Raspberry Pi to act as a relay, and was wondering if we could add a WOL proxy on the list, as a recommended way of doing WOL over the Internet.

**Comment by Jorys-Paulin** [comment]
Okay, we'll start recommending WOL proxy over the other solutions then. Thanks for the response!
