### ISSUE TITLE
High frame drop due to network connection

### ISSUE THREAD

**Issue by kishore200083** [moonlight-stream/moonlight-qt#579]
I have an issue plaing games with moonlight.Am streaming from aws instance to my pc and I am getting high frame drops by connection in the day time.There is no issue from 12 am to 9 am.The bandwith speed is constant.I think it's my internet connection issue.But I tried a vpn called Pandavpnpro and they have an option called connect with openvpn.When connecting with it I have no frame drop issues.Its not a permanent solution as the connection gets disconnected every time.Is there any workaround,please help ??

**Comment by cgutman** [comment]
I suspect this is a duplicate of #582 which is fixed by e081401c2d6887ea9feb85785dd27c7595510829
