### ISSUE TITLE
Searching for pcs taking too long

### ISSUE THREAD

**Issue by shubywooby09** [moonlight-stream/moonlight-qt#580]
I have been waiting for 10 minutes, it still hasnt found a pc.

**Comment by cgutman** [comment]
Does your gaming PC meet the [system requirements](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide)? Is it set up according to the [quick start guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#quick-setup-instructions)?
