### ISSUE TITLE
System-wide keyboard shortcuts broken since 3.1.0 (was working on 3.0.0) Linux

### ISSUE THREAD

**Issue by famus484** [moonlight-stream/moonlight-qt#584]
**Describe the bug**
Windows key does nothing, and Alt-Tab changes client windows instead of host.

**Affected games**
Any application where system shorcuts would be useful.  

**Other Moonlight clients**
I tried with both the flatpak and the appimage versions, on linux. Didn't try on windows, and Android version does not have the functionality as far as I know.

**Moonlight settings**
- Have any settings been adjusted from defaults?
  Only "Capture system keyboard shortcuts" being changed. Tried Fullscreen only and always, in windowed and fullscreen. Same results, nothing happens.

**Client PC details**
 - OS: Debian GNU/Linux 10 (buster)
 - Moonlight Version: 3.1.0 and 3.1.1 (3.0.0 worked, but not compatible with newest GeForce Experience)
 - GPU: Intel HD Graphics 4000

**Server PC details**
 - OS: Windows 10 Home 20H2
 - GeForce Experience version: 3.22.0.32
 - Nvidia GPU driver: 461.40
 - Antivirus and firewall software:  Windows Defender

**Comment by cgutman** [comment]
Are you using X11 or Wayland? What desktop environment?

**Comment by famus484** [comment]
Gnome 3.30.2 on X11. I have not thought about trying Wayland, I will do that now

**Comment by famus484** [comment]
Ok, so my findings are interesting. On Wayland, the system keys do work (I only tried in fullscreen), gnome asks permissions (xorg never did, even when it worked) and super+escape is used to restore client shortcuts.

There is another bug that pops up though on Wayland, leaving with Ctrl+Alt+Shift+Q is impossible, the screen becomes frozen. The system does still seem to work, as going to tty3 allows reboot, and alt+tab (when not possessed by Moonlight) still shows opened apps, although switching to another window is impossible. I don't think it's related, because turning off "Capture System keys" doesn't solve the bug. Only way to leave is by using super key (before trying Ctrl+Alt+Shift+Q, otherwise frozen screen) and closing the window from gnome.

Xorg does not have that bug, Ctrl+Alt+Shift+Q works every time (though system key capture still don't work).

**Comment by famus484** [comment]
I do prefer using Xorg for other reasons (better compatibility with pen in my experience), if that's possible to find a workaround there first (although I can help investigate the Wayland bug).

**Comment by famus484** [comment]
Super, thank you. Right now, is it built with an older version of SDL? If so, does that mean that the issue will solve itself when SDL is updated with Moonlight (I can personally wait a while)? Otherwise, I suppose I will have to build it myself with 2.0.14.

Wow, indeed I felt like such a blatant Wayland bug would have been reported and fixed by now if it was not for Wayland 3.30.2 being unused by anyone. I had recently switched from Arch, because I had an unpleasant gnome regression at the worst time. I still use the mega-ultra-stable branch of debian for now, this is a consequence.

**Comment by cgutman** [comment]
Actually it's the opposite. Moonlight is built with newer SDL code than 2.0.14 which hasn't yet made it into an official SDL release. I upstreamed a bunch of our keyboard grab code to SDL along with many Wayland fixes. Moonlight v3.1.0+ is used the new keyboard grab API work I did in SDL.

Ironically, SDL's X11 keyboard grab was the only keyboard grab support I _didn't_ write, since it already existed before my work. However, I know it worked before. In fact, it used to be the _only_ keyboard grab that worked on Linux before I wrote the Wayland keyboard grab support.

I'm going to investigate further tomorrow to at least identify if it is in fact an SDL regression, so I can file a bug to get it fixed before SDL 2.0.16 officially released.

**Comment by famus484** [comment]
Ohh, that is nice! If I can do anything to help identify the bug further, I am happy to help. Moonlight has been legit my favorite program for the past year since I got my pc.

**Comment by cgutman** [comment]
It turned out to be in a Moonlight codepath specific to SDL 2.0.15+. Here is a fixed AppImage: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/38960223/job/fcj2740587kgp347/artifacts

**Comment by famus484** [comment]
I confirmed it works with that Appimage, so awesome! I suppose eventually the fix will make eventually make it to Flatpak? In any case, a definitive thank you!

**Comment by cgutman** [comment]
Yes, it will be in the Flatpak in the next official release which should be in the next few days if nothing else comes up.
