### ISSUE TITLE
Windowed fullscreen mode

### ISSUE THREAD

**Issue by temp2243** [moonlight-stream/moonlight-qt#586]
Currently, I run dual monitors.  The software works great, and it is functional and many thanks to you for allowing me to game stream while I'm on travel.

However, I must say that it is immensely annoying to receive say a message, check a website, or just want to minimize, and have to suffer through the slow exit from fullscreen my computer goes through (monitor goes all black, there is a pause, then the main desktop comes on screen).  This seems to cause issues with other applications then choosing wrong monitors to be on, etc.  Then, to remaximize, repeat the process of black screen, pauses, etc.

I realize this isn't directly a problem with this software, but exclusive fullscreen mode is somewhat annoying generally.  Is it possible to perhaps look into doing a windowed maximized fullscreen equivalent, that quickly allows alt-tabbing out or whatever the escape key might be?

Even more importantly would be able to move my mouse off the full screen window, to a second monitor, and back again, without minimizing/maximizing each time.

**Comment by cgutman** [comment]
This option always exists. Just select “borderless windowed” display mode in Moonlight settings.
