### ISSUE TITLE
Add option to allow untrusted SSL connections

### ISSUE THREAD

**Issue by divadsn** [moonlight-stream/moonlight-qt#588]
**Is your feature request related to a problem? Please describe.**
Sometimes Nvidia has an outdated certificate and also alternative solutions like sunshine use a self-signed CA, in these cases such an option might save a lot of time and frustration for the user.

**Describe the solution you'd like**
I would like to have an option in the settings to allow untrusted SSL connections or/and a popup that warns the user before connecting and awaits a decision whether to ignore or not.

**Describe alternatives you've considered**
While for the alternative solutions I can import the CA in theory, the outdated certificate usually requires running an update for Nvidia GeForce Experience, which can be a problem if the host is far away and unreachable.

**Additional context**
https://github.com/loki-47-6F-64/sunshine/issues/81

**Comment by loki-47-6F-64** [comment]
This is a feature request for Moonlight-qt, you'll have better luck at: https://github.com/moonlight-stream/moonlight-qt :P

**Comment by divadsn** [comment]
Adding the CA didn't help out, it's annoying.

![](https://i.imgur.com/NRp5TGd_d.webp)

**Comment by cgutman** [comment]
There must be more to this. GeForce Experience itself also uses a self-signed certificate, so that's not the problem here.

Can you attach the certificate that Sunshine generated?

**Comment by cgutman** [comment]
I did some further research and found this is actually an alert that the remote host (Sunshine) is sending to Moonlight. So it is Sunshine rejecting Moonlight's certificate, not the other way around.

Let's take this back to the sunshine bug tracker and investigate on https://github.com/loki-47-6F-64/sunshine/issues/81
