### ISSUE TITLE
question about the protocol

### ISSUE THREAD

**Issue by HongZhouyang** [moonlight-stream/moonlight-qt#590]
Hi, I am interested in making NVIDIA&Moonlight to be able to run on WAN, But I can't find the code of NVIDIA Game Stream. Can you provide  me any tip that might help? Looking forward to your reply.   -.-

**Comment by cgutman** [comment]
The shared core client code is here: https://github.com/moonlight-stream/moonlight-common-c (public API is in Limelight.h).

You will still need to interface with the HTTP server for pairing and launching. You can find reference code for that in:
https://github.com/moonlight-stream/moonlight-qt/blob/master/app/backend/nvpairingmanager.cpp https://github.com/moonlight-stream/moonlight-qt/blob/master/app/backend/nvhttp.cpp
