### ISSUE TITLE
Screen tearing using the HEVC decoder on RPi4

### ISSUE THREAD

**Issue by sepcbi** [moonlight-stream/moonlight-qt#591]
Using the experimental HEVC decoder I'm getting screen tearing, doesn't seem like VSync is working properly.
Switching back to the h264 decoder fixes any screen tearing without altering any other settings.

**Comment by sepcbi** [comment]
Looked into it a bit more today, seems like the HEVC encoder introduces a lot of network jitter, according to the output it's around 50% of the frames that gets dropped, it might not be an issue with VSync if that's the case.

Attached logs for each of the encoders, the h264 one reports no network jitter.

[hevc-rpi4-output.log](https://github.com/moonlight-stream/moonlight-qt/files/6507671/hevc-rpi4-output.log)
[h264-rpi4-output.log](https://github.com/moonlight-stream/moonlight-qt/files/6507672/h264-rpi4-output.log)

**Comment by cgutman** [comment]
Are you connected to a 4K display? I believe you're hitting the 30 Hz refresh rate limit on 4K displays, which is why it's dropping 50% of your 60 FPS.

**Comment by sepcbi** [comment]
That was it, had to enable something called "HDMI Deep Color" for the input on the TV for it to allow a 4k60Hz signal instead of the 30Hz one as well as adding `hdmi_enable_4kp60=1` to the bootconfig.  

I'm using an LG 2020 OLED if anyone is looking for a solution here.

Thank you for your help, really love the project!
