### ISSUE TITLE
Add virtual keyboard and cursor to Steam Link. 

### ISSUE THREAD

**Issue by archead** [moonlight-stream/moonlight-qt#592]
As far as I am aware there is no way of entering text without connecting a physical keyboard within the moonlight menu on the Steam Link. Additionally some parts of the UI are impossible to access without a hardware mouse such as the "Add device button" in the top right corner. Without a virtual keyboard (and mouse) it's impossible to add a device through global IP and change the display to a custom resolution.

A controller key-bind similar to exiting the stream (L1+R1+Select+Start) should be implemented in order to bring up a virtual keyboard and cursor within the moonlight menu. This should make every UI part accessible and usable.

**Comment by hfeest** [comment]
For 3d model editor and illustrator or all people, the proyect is the future of work. But without keybard or optical pen is very dificult to work. I tryng to work with fusión 360 and Huawei matepad 10.4.
