### ISSUE TITLE
可以用来和朋友玩双人成行离线模式吗？

### ISSUE THREAD

**Issue by 1265578519** [moonlight-stream/moonlight-qt#595]
可以用来和朋友玩双人成行离线模式吗？需要第二个键盘设备，我测试按下键盘，他只显示第一玩家

**Comment by JerryWu2021** [comment]
貌似不支持多键盘

**Comment by 1265578519** [comment]
@JerryWu2021 我找到多键盘的软件了，，Parsec，可惜限速10M，画面老卡和模糊

**Comment by xuchao1688** [comment]
用手柄吧，之前和前女友一起这样玩过，没想到在issue区看到有相同操作的。。。
