### ISSUE TITLE
Controller reconnect

### ISSUE THREAD

**Issue by JelledFro** [moonlight-stream/moonlight-qt#596]
I'm using a controller to play on the steam link hardware using the latest version of moonlight. Streaming from a desktop PC  with GeForce driver 466.27 with a gtx 970. Overall it's working well but if the controller disconnects it is unable to reconnect. I can change to mouse mode and get a reaction, but I can no longer use the gamepad in "gamepad mode".  I was able to solve this by toggeling the "force gamepad #1 always connected" option. But If I have that option toggled and try to play a game with multiple controllers all controllers register as gamepad 1. When I connect to big picture only one of the several connected to the steam link appear in the menu. So there seems like there is good support both for using multiple controllers and for reconnecting controllers, but they don't work simultaneously.

**Comment by cgutman** [comment]
This is a game specific problem. Some games don’t like the controller being disconnected and reconnected again. The “force controller 1” option is a workaround for games with broken controller hot plug support.

If you stream your Desktop and go to https://html5gamepad.com or navigate around Steam Big Picture, you will see that the gamepad does indeed get reattached after reconnecting. I tried it just now to make sure I’m not crazy.
