### ISSUE TITLE
Black bars option

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#60]
can you please also add black bars option for non standard resolution monitors?
ex 1920x1200
some games look good stretched to 16:10, others look weird and it would be good to have an option to force 16:9 aspect ration with black bars when you wish to do so

**Comment by apoklyps3** [comment]
If I select 1920x1080 the stream window jumps to the default monitor instead of staying on the one I want it to....
that's why I was asking for 1920x1080 with black bars inside a 1920x1200 fullscreen window...

**Comment by cgutman** [comment]
The monitor jumping was fixed by https://github.com/moonlight-stream/moonlight-qt/commit/856318f947a6a73b927b0ef0148fe6eeb2c1d5a5 so I'm closing this issue.
