### ISSUE TITLE
Moonlight closing a few second after launching 

### ISSUE THREAD

**Issue by d3smo** [moonlight-stream/moonlight-qt#600]
Moonlight closing a few second after launching 

Running on Windows 10
Moonlight 3.1.3
Geforce Experience 3.22.0.32
Nvidia Driver 466.47

Issue happen with client on Windows and Android TV (Shield Pro)

[Moonlight-1621759015.log](https://github.com/moonlight-stream/moonlight-qt/files/6527789/Moonlight-1621759015.log)

**Comment by cgutman** [comment]
```
00:00:24 - SDL Info (0): Server notified termination reason: 0x80030023
```

It isn't Moonlight terminating the connection; it's your host. We need the host logs to possibly determine a cause.

Collect the log files from the `C:\ProgramData\NVIDIA Corporation\NvStream` folder and upload them here. `C:\ProgramData` is a hidden folder, so you may need to navigate there manually or enable hidden folders to see it.

**Comment by d3smo** [comment]
Here it is
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/6528661/NvStreamerCurrent.log)

**Comment by cgutman** [comment]
```
#3(I)[2021-05-23 18:21:48,551]=20:21:48={12348}<ResultUtils>      Termination reason = GAME_LAUNCH_FAILED (SRC_TargetAppLaunchFailure)
```

It says the game launch failed. What are you trying to play?

**Comment by d3smo** [comment]
Thanks for helping me understanding the log. I solve the issue that did not came directly from Moonlight let me explain it could be helpfull for other people who do the same as me.
I use Moonlight on a Nvidia Shield on a 4K TV to stream my desktop computer games on wich i've a 1440p screen. So i've create a batch file which switch my resolution to 4K on my desktop and launch Steam in big picture mode. I used to launch this batch file with moonlight on my shield and it works like a charm since a year, until last week. It happens that the resolution switch was not enough quick and when big picture was launch the resolution switch was not fully load, so i had a timeout between switch resolution and big picture launch it solve the issue. I think the problem happen since latest Nvidia driver update which has do something with resolutions settings. So i close the issue thx again for your help.
