### ISSUE TITLE
Steam link device moonlight does not have traditional Chinese

### ISSUE THREAD

**Issue by coolwhg** [moonlight-stream/moonlight-qt#606]
Simplified Chinese displays boxes in the device, and there is no traditional Chinese in the language options

**Comment by cgutman** [comment]
There is no Traditional Chinese option because nobody has contributed a Traditional Chinese translation for Moonlight.

If you have the skills, you can do so here: https://hosted.weblate.org/projects/moonlight/moonlight-qt/
