### ISSUE TITLE
Choose monitor to use on client side [Linux Mint Cinnamon]

### ISSUE THREAD

**Issue by sdietri** [moonlight-stream/moonlight-qt#607]
Is there a way to select which screen Moonlight uses for fullscreen on the client side? I have two monitors, a 1080p and a 4k and I want to use the 1080p for streaming in fullscreen. Somehow, Moonlight always seems to select the biggest screen it can find (my guess at what happens as it happens in a 1080p and 1440p constellation as well) and uses that for fullscreen which defaults to my 4k. Setting a primary display in xrandr doesn't solve the issue.

This might make a great feature request if there isn't a way to select this yet.

**Comment by cgutman** [comment]
Are you referring to the streaming window or the GUI window? The streaming window should always follow the location of the GUI window.

**Comment by sdietri** [comment]
That behaviour only seems to apply with screens of equal resolution (e.g. two 1080p). Otherwise it'll select the biggest screen it can find. Tested with combinations 1080p and 4k, 1440p and 4k, 1080p and 1440p. Equal size was two 1080p screens. Further, setting the 4k to 1080p, it'll also behave as you said with a second 1080p screen. So there's definitely something up with the fullscreen window choosing the biggest resolution available. Where I place the initial GUI window does not seem to matter.

**Comment by cgutman** [comment]
Are you using Wayland? On Wayland, the window manager controls the location of windows and applications cannot control it.

**Comment by sdietri** [comment]
No, I'm on Xorg still.

**Comment by sdietri** [comment]
Good call on the window manager. Installed Fluxbox for a quick test and it does not show this behaviour (aka, it always goes fullscreen on the monitor with the GUI as you described). Seems to be related to Cinnamon desktop.

**Comment by sdietri** [comment]
Okay, figured it out. This seems to be related to how monitors are aligned in the placement. If I align them along the top edge, the strange focus behaviour appears. If I align them at the bottom or somewhere in the middle, the streaming window stays with the GUI window.
![Dontaligntop](https://user-images.githubusercontent.com/35671646/120517248-8f510e80-c3d0-11eb-84db-8101d4638ce8.png)

No idea if it's purely on the Xorg/Cinnamon side or something Moonlight does. Issue itself can be circumvented easily, so close the issue if you feel no more need to keep it open.

**Comment by cgutman** [comment]
OK, I will close this, since it seems to at least be an external bug (in Qt, SDL, or Cinnamon).
