### ISSUE TITLE
P3 color gamut

### ISSUE THREAD

**Issue by dannystewart** [moonlight-stream/moonlight-qt#609]
Is there any possibility of implementing support for the P3 color gamut supported by Macs and other modern displays? I've seen this work over VNC regardless of the display on the other end so I was wondering if it would be possible for Moonlight to make use of it as well. The color difference is striking so this would be great to have for gaming.

**Comment by cgutman** [comment]
Unfortunately, GameStream only supports Rec 601, Rec 709, and Rec 2020. There's no P3 support in the protocol currently, so we'll have to see if Nvidia adds it in the future.
