### ISSUE TITLE
Mouse only working when a button is held down

### ISSUE THREAD

**Issue by incrazyboyy** [moonlight-stream/moonlight-qt#612]
**Describe the bug**
I'm using Moonlight to stream games locally from my PC to my Macbook via ethernet cable. But in 9/10 times when I connect, I'm unable to use my mouse correctly. The cursor will only move when I hold down a button on the mouse. Clicking and scrolling works fine. Usually, this could be solved by keeping my secondary mouse connected to the PC, but for like two weeks, this doesn't help either. My current workaround is connecting my **main** mouse (wired) to the PC, moving it, and then connect it back to the macbook. Once I do that, it keeps working until the next reboot. I already tried a fresh install of Windows 10, but that didn't help.

**Affected games**
I don't start games through Moonlight, I always use the Desktop (mstsc.exe).

**Moonlight settings**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?
- 3440x1440 @100fps/133.333Mbps
- Borderless Window
- Vsync enabled
- Frame Pacing off
- Optimize for Remote Desktop: I tried on and off, neither helped
- Shortcuts off

**Client PC details**
 - OS: macOS Big Sur 11.4
 - Moonlight Version: 3.1.3
 - GPU: Intel Iris Plus Graphics 645 1536 MB

**Server PC details**
 - OS: Windows 10 21H1
 - GeForce Experience version: 3.22.0.32
 - Nvidia GPU driver: 466.77
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Moonlight Logs**
[Moonlight-1623691102.log](https://github.com/moonlight-stream/moonlight-qt/files/6650325/Moonlight-1623691102.log)

**Additional context**
Mouse: Mad Catz R.A.T TE
Mac: Macbook Pro 13" 2020 i5 via Thunderbolt 3

**Comment by cgutman** [comment]
Can you try another type of client like Android or iOS to see if it's a client-side or host-side issue? You could even try a different client or host PC if you have one available.
