### ISSUE TITLE
Mouse is totally unusable since some versions of Moonlight / GFE on Windows

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#616]
Not sure what you did, but the mouse became more and more unable to use to this point of latest 3.14 and latest GFE, it is totally unusable.

Only with the "alternative mouse mode" it works great in Windows, but then in games their is no mouse support, and I have to switch over to ctrl+alt+shift+m and then the mouse works, but is totally unsable. The acceleration is so fast and not accurate, the mouse randomly jumps around when you move a circle with the mouse it randomly jumps away, it stutters and lags.

Tried to deactivate mouse acceleration prediction on the host PC, with no result, I also noticed, GFE seems to activate the acceleration randomly again.

Only way to play is to use some 3rd party app like InputDirector to control mouse/keyboard on the host PC. How come these programs work way better than Moonlight?

Then also randomly the keyboard input stops working when on the client and switching back into the stream window.

**Comment by cgutman** [comment]
There were no changes to mouse input in v3.1.4.

Please open an issue using the proper bug report  issue template that provides OS, software versions, repro steps, etc.
