### ISSUE TITLE
Video decode unit queue overflow on AMD laptop

### ISSUE THREAD

**Issue by dadddda** [moonlight-stream/moonlight-qt#617]
**Bug description:**
The problem is kind of strange. After playing a game(doesn't matter which) for some time, randomly but frequently streaming starts to lag very badly. The frame drops are not random, the video's quality drops to the floor(It gets overly compressed) and on average it starts to stream with 1FPS. Pressing [Ctrl+Shift+Alt Q] and resuming the stream or [Alt+Tab]-ing to a different window on a client computer and then returning back to Moonlight fixes the problem, but the same thing happens after a few minutes or sometimes seconds.

After looking inside log files I noticed the messages about the video decode unit queue overflow, that kind of message is all over the place (Log file is attached below). Normally I stream at 1080p 60FPS with 50Mbps bandwidth but I noticed that when setting 30FPS instead of 60FPS overflows weren't occurring anymore.

I have tried Moonlight-qt's every version from 3.0.0, the same thing happens on all of them... Also, I have tested this behavior with the default settings, as well as with force hardware decoding, H.264 and H.265... but the same thing happens except when using 30FPS as I have stated above.

**Client computer:**
 - OS: Windows 10 21H1
 - Moonlight version: v3.1.3
 - GPU: AMD Ryzen 5 3500U with Vega 8 integrated graphics
 - RAM: 8GB (2GB allocated by the iGPU)

**Server computer:**
 - OS: Windows 10 20H2
 - GeForce Experience version: 3.23.0.74
 - Nvidia GPU driver: 466.77
 - Antivirus and firewall software: Windows Defender and Windows Firewall
 - GPU: GTX 950 2GB
 - RAM: 16GB

**Log file:**
[Moonlight-1624729787.log](https://github.com/moonlight-stream/moonlight-qt/files/6720733/Moonlight-1624729787.log)

**Comment by cgutman** [comment]
Does the problem happen with v-sync disabled? Does it happen if you use borderless windowed or windowed mode instead of fullscreen?

**Comment by dadddda** [comment]
I have V-Sync disabled when playing, but I have also tried with V-Sync enabled and the same thing happens. Also, I tried with borderless windowed mode and the same thing happens, but this time [Alt+Tab]-ing out and then into Moonlight doesn't fix the issue as does in Fullscreen mode, I think that's an important detail.

**Comment by dadddda** [comment]
I want to add that when I'm using an older(From 2019) AMD driver on my client laptop, even on 100Mbps/120FPS overflow happens less frequently but it still happens.

Also, I have freshly reinstalled Windows 10. That didn't solve the problem tho.

**Comment by cgutman** [comment]
OK, start Moonlight in windowed mode and wait for the bug to start happening.

When the bug occurs, open Task Manager, go to the Processes tab, right click Moonlight.exe, and choose Create Dump File. 

Go to the folder where the memory dump is located, ZIP it, and upload it somewhere so I can take a look at it.

**Comment by dadddda** [comment]
Hi and sorry for my late reply,
as soon as I started streaming the same bug occurred and I did what you told me to do.

Here I have uploaded the dump file: [https://drive.google.com/file/d/18dtiytkNic92vHwUSHCOL8BzeL9GzY18/view?usp=sharing](url)

**Comment by Thegiftsyougave** [comment]
Hi there and thanks for this fantastic project.
I've been successfully using an Intel UHD 630 laptop in my home network for months at max bitrate, both codecs, at 60-120fps.

Today I had to replace the Intel laptop with AMD unit, [HP 255 G7]
 **Using the same processor as OP**:

- Ryzen 5 3500U - Zen+ 'Picasso' 
- Radeon Vega 8
- 8GB RAM


I have exactly the same problem as OP.
After seconds or minutes frame rate drops from 120 to 12 (always 12) and ALT-Tab fixes it, for a minute or two.


- RTX 2060 host with driver 496.49 and GFE 3.24.0.114
- Windows 10 20H2
- Gigabit LAN fritz.box

**"frame request sent"
"Video decode unit queue overflow"**

Happens on Wi-Fi or ethernet, with Bluetooth disabled and all power saving disabled.
Happens at 60fps 720p too, but often works for longer than at 120fps 1080p.
x265 seems a bit more reliable than x264.

logs and dumpfile below.

Thanks!
[Moonlight-1636772612.log](https://github.com/moonlight-stream/moonlight-qt/files/7531346/Moonlight-1636772612.log)

https://filetransfer.io/data-package/FPQV8Lo7#link

**Comment by Thegiftsyougave** [comment]
Well, I've identified the problem:

Other users have had similar glitches with the mobile chip 3500U, including when watching high bitrate videos.

The Vega graphics chip in the Ryzen 3500U has a separate 'VCN clock' - this remains at '0' until it is needed to accelerate video.
It ramps up to around 700mHz when moonlight begins, and after pressing ALT-TAB, then for some reason clocks right down to 29mHz after a few minutes (or seconds).

I couldn't find any Windows power setting or Radeon software setting that prevents this downclocking.

**The fix** is to use opensource [ryzrenadj](https://github.com/FlyGoat/RyzenAdj) - with the parameter ryzenadj.exe -t 500.

This fixes the VCN clock above 500mHz until the laptop is restarted and results in perfect 120fps gameplay with moonlight.
