### ISSUE TITLE
Touch control windows 10 tablet/surface book

### ISSUE THREAD

**Issue by SyntheticOD** [moonlight-stream/moonlight-qt#62]
I'm streaming from a windows 10 pc to a windows 10 tablet running Moonlight-QT. 

Is it possible to add the same touch controls for android on windows 10 for games like CIV and other RTS type games.  the option to use the on screen joystick would also be great.

**Comment by airdjing** [comment]
I'm using Dell Venue.
Moonlight touch control is great for handheld computers using the touchscreen.

Touch QT version has been updated so I am really happy.
I didn't even think about it before, but it would be useful to use it properly.

https://youtu.be/h9MEFzRv9OI

But sadly, in my case, touch to reset the position to 0.0.
Is it problem only for me?

**Comment by cgutman** [comment]
@airdjing I'm very confused by the behavior in this video. Moonlight's touch support is implemented where the touchscreen behaves like a trackpad. Your video appears to show the touch support behaving like a touchscreen which is not possible in the current code. The only way I can imagine that it would ever act like this is if you were using Moonlight via Remote Desktop or some other mechanism where touch events would be converted into fake mouse movement.

Can you clarify exactly what software you're using to test this?

**Comment by airdjing** [comment]
I logged on to GFE mstsc.exe setup from my gamestream-qt.
Vaccines use Kaspersky FREE. No seperate firewall.
Windows 10 version is RS5 1809 (17763.55) (both client and server)
I don't know what else is special.
Is there any other way I can provide you with anther specific information?

**Comment by airdjing** [comment]
@cgutman I logged on to GFE mstsc.exe setup from my gamestream-qt.
Vaccines use Kaspersky FREE. No seperate firewall.
Windows 10 version is RS5 1809 (17763.55) (both client and server)
I don't know what else is special.
Is there any other way I can provide you with anther specific information?

**Comment by airdjing** [comment]
@cgutman  Solved the problem.
Turn off the Mouse raw option on the latest 6.3 version .
Thank you.

**Comment by cgutman** [comment]
Fixed by 8cb98b53651633494324f53257b2b0f21e36ea17
