### ISSUE TITLE
Mouse dont work after end 2 game sessions

### ISSUE THREAD

**Issue by tw0f1sh** [moonlight-stream/moonlight-qt#621]
Hi, i try to use moonlight after months again but i got the same issue like befor.

After i start a game via client side and close it (2 times), i cant move the mouse arround at the 3rd start. I try to connect via android to check if its the client-PC but it need to be the server-PC.
 
I try to disable and unplug my 2nd monitor at the server side-PC, exit all nvidia processes and restart the services but the only thing which helps is an server-PC reboot. 

Client PC details:
    - OS: Windows 10 Home & Android 10
    - Moonlight Version: 3.1.4
    - Antivirus and firewall software: non external AV and Windows defender + firewall is deactivated

Server PC details:
    - OS: Windows 10 Home
    - GeForce Experience version: 3.23.0.74
    - Antivirus and firewall software: non external AV and Windows defender + firewall is deactivated

**Comment by zhanhongliau** [comment]
Same here, moonlight clients on Windows 10, Raspbian and Android 10. Mouse stops working after starting and closing the stream several times. Tried with and without "Optimize mouse for remote desktop" to no avail. Nothing I do restores mouse control except for rebooting the server machine.

**Comment by mtwomey** [comment]
Same.
