### ISSUE TITLE
ALT-TAB preview is white

### ISSUE THREAD

**Issue by AdamKlob** [moonlight-stream/moonlight-qt#624]
**Describe the bug**
When switching app via ALT-TAB, Moonlight streaming window preview is completly white.

**Steps to reproduce**
Press ALT-TAB

**Other Moonlight clients**
Not tested

**Moonlight settings (please complete the following information)**
Default

**Client PC details (please complete the following information)**
 - OS:  Windows 10 19041.1083
 - Moonlight Version: 3.1.4
 - GPU: Nvidia GTX 1660 TI

**Server PC details (please complete the following information)**
 - OS: Windows 10 19043.2021
 - GeForce Experience version: 3.23.0.74
 - Nvidia GPU driver: [e.g. 471.11
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Comment by cgutman** [comment]
This is because Moonlight streams in full-screen exclusive mode by default. DWM is unable to capture a window preview snapshot of full-screen exclusive mode applications. It’s an OS limitation, not a Moonlight bug.

If the Alt-Tab preview is important, you can choose to stream in Borderless Windowed.

**Comment by AdamKlob** [comment]
@cgutman your're right, thanks. Maybe consider making borderless window a default setting?

**Comment by cgutman** [comment]
Moonlight is first and foremost low latency streaming software. We default to full-screen exclusive mode for lowest-possible latency (especially on hardware platforms that don't support DirectFlip).

The Alt+Tab preview issue is an incredibly minor issue that is easily outweighed by the improvement to latency and frame pacing provided by full-screen exclusive mode. Users that want the Alt+Tab preview have that ability too.
