### ISSUE TITLE
[BUG] Moonlight-qt HEVC decoding on latest RPi-kernel looks tiled on Pi4

### ISSUE THREAD

**Issue by veldenb** [moonlight-stream/moonlight-qt#630]
**Describe the bug**
On the Raspberry Pi 4 the HEVC the stream looks tiled. A LibreELEC developer suggests upgrading the ffmpeg libraries in moonlight-qt because they may not play well with the latest RPi kernel: https://github.com/LibreELEC/LibreELEC.tv/issues/5521#issuecomment-890343185

**Steps to reproduce**
1. Install LibreELEC 9.95.5 on Pi4 (RPi kernel 5.10.35)
2. Install this Moonlight-qt plugin: https://github.com/veldenb/plugin.program.moonlight-qt
3. Start Streaming, HEVC decodes normal
4. Upgrade LibreELEC to 9.97.1 on Pi4 (behaviour is noticed from RPi kernel 5.10.36 and up)
5. The stream looks tiled

**Screenshots**
It looks like this: ![Broken stream](https://user-images.githubusercontent.com/85257001/127172762-36b53108-4d48-44ab-89de-7c63609672ca.jpg) 

**Affected games**
All

**Moonlight settings (please complete the following information)**
- Occurs with default settings

**Client PC details (please complete the following information)**
 - OS: LibreELEC 9.97.1
 - Moonlight Version: latest Pi4 version
 - GPU: Pi4

**Server PC details (please complete the following information)**
 - OS: Windows 10 latest

**Moonlight Logs (please attach)**
[moonlight-qt.log.kodi.9.95.5.txt](https://github.com/moonlight-stream/moonlight-qt/files/6911195/moonlight-qt.log.kodi.9.95.5.txt)
[moonlight-qt.log.kodi.9.97.1.txt](https://github.com/moonlight-stream/moonlight-qt/files/6911194/moonlight-qt.log.kodi.9.97.1.txt)

**Additional context**
See more information about the bug here: https://github.com/veldenb/plugin.program.moonlight-qt/issues/9
It looks like things went wrong somewhere here: https://github.com/LibreELEC/LibreELEC.tv/compare/9.95.5...9.97.1

edit: added kernel info

**Comment by cgutman** [comment]
Fixed by https://github.com/cgutman/moonlight-packaging/commit/d12eb8e35318328b544f411a250bb379ab2e2302

Fix released to the APT repo: https://cloudsmith.io/~moonlight-game-streaming/repos/moonlight-qt/packages/?q=version%3A3.1.4-2
