### ISSUE TITLE
Black screen, when trying to stream 4k on raspi 4b.

### ISSUE THREAD

**Issue by jascase901** [moonlight-stream/moonlight-qt#631]
**Describe the bug**
Black screen, when trying to stream 4k on raspi 4b.

**Steps to reproduce**
1. Any special steps that are required for the bug to appear.
to enable hevc I modified my boot.txt (attached)

```
[all]
toverlay=vc4-fkms-v3d
hdmi_enable_4kp60=1
force_turbo=0
gpu_mem=320
dtoverlay=rpivid-v4l2
```
2. I launched from tty, instead of using the gui.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- Changed the resolution to 3840x2160 (30 fps and 60 fps) (Saw black Screen)
- Changed the resolution to 2560x1440(Works perfectly)

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - Moonlight Version: [e.g. v3.1.4]
 - GPU: gtx 2080

**Server PC details (please complete the following information)**
 - OS: [Windows 10 pro, 64bit]
 - GeForce Experience version: [3.23.0.74]
 - Nvidia GPU driver: [466.27]
 - Antivirus and firewall software: [Windows Defender and Windows Firewall]

**Moonlight Logs (please attach)**
[config.txt](https://github.com/moonlight-stream/moonlight-qt/files/6911660/config.txt)
[2560x1440](https://github.com/moonlight-stream/moonlight-qt/files/6911661/log.txt)(works
[log_4k.txt](https://github.com/moonlight-stream/moonlight-qt/files/6911663/log_4k.txt) (black screen I tried 4k at the end of this log)

**Additional context**
Im using a an ethernet connection for both the raspi 4b, and then desktop computer.
if I launch steam I can still hear sound, on 4k, but now picture.

**Comment by cgutman** [comment]
Yep, this is a known issue, and it doesn't appear to be Moonlight's fault.

It has been a while since I first tested that, but IIRC you'll see a big nasty `WARN_ON` print from VC4 in your `dmesg` at the time that all those `drmPrimeFDToHandle()` errors begin.

**Comment by jascase901** [comment]
thanks. Thats a bummer.

**Comment by jascase901** [comment]
Thanks for your heads up on the WARN message.
I saw this
```
[18068.243516] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[18068.243531] rpivid feb10000.codec: dma_alloc_coherent of size 12533760 failed
```
and was able to get it to display at 4k.
I was able to get it to boot by giving more memory to the cma
`
dtoverlay=vc4-fkms-v3d,cma-512`

[4k_log.txt](https://github.com/moonlight-stream/moonlight-qt/files/6911971/all.txt)
[config.txt](https://github.com/moonlight-stream/moonlight-qt/files/6911972/config.txt)


I don't yet under stand the repercussions of this parameter, but heres a link that explains what it does.
https://www.dedoimedo.com/computers/rpi4-ubuntu-mate-hw-video-acceleration.html
