### ISSUE TITLE
[FR] Auto mouse mode switching when windowed / fullscreen please

### ISSUE THREAD

**Issue by mrwiwi** [moonlight-stream/moonlight-qt#633]
Hi, thanks a lot for Moonlight 1st, I'm using it on Linux since 2 months after Shadow PC failing, and it's the best streaming solution IMHO.

I have one simple feature request (seems simple), could it be possible to switch the mouse to relative when in windowed mode, then in absolute when in fullscreen ?

Today we need 2 shortcuts to switch to another app : CTRL+ALT+X and CTRL+ALT+Z, systematically. Could we have a simple option to enable mouse relative when the 1st shortcut is done ?

It will be a so more smooth user experience...

Thanks a lot.

That's the only thing I find inferior to parsec or Shadow before.

**Comment by deeeeeebs** [comment]
Not sure if I understood your question correctly so just ignore it if you already know this but you can switch mouse modes with CTRL+ALT+M (while it's not what you asked for, it may help until there's a better solution).
