### ISSUE TITLE
Black Screen on Lock Screen

### ISSUE THREAD

**Issue by JonSnow88** [moonlight-stream/moonlight-qt#634]
Moonlight works great when I am logged in, but if i step away or the PC locks itself I can no longer unlock my PC. I just get a black screen, moonlight is connected as i am able to move the cursor from the remote session, but don't see anything. With the black screen session active if I go to the PC and unlock it everything starts to display correctly in moonlight.

**Comment by cgutman** [comment]
Is the PC display turned off (in power save mode) when this happens?
