### ISSUE TITLE
Starting moonlight-qt on console - Screen blanking must set to off - Screensaver possible?

### ISSUE THREAD

**Issue by zackfuchtel** [moonlight-stream/moonlight-qt#636]
Hello and thanks for the good work.

to work from console with moonlight-qt on an pi400 I have to set console blanking to off because all input devices are send to the remote host and once you got a blank screen on the pi400 you have to leave the session with strg ctrl alt q to "reactivate" the pi400 monitor again.

Is there a way to use a screenblanking /screensaver within a moonlight-qt session? Or maybe you can implement this feature in a further version?

thanks, keep healthy

**Comment by cgutman** [comment]
Fixed by ce2a01fc59753d5bd993d789fc4be275f2c445d1
