### ISSUE TITLE
OBS Studio can't capture the moonlight screen

### ISSUE THREAD

**Issue by JeffCheung85** [moonlight-stream/moonlight-qt#639]
OBS Studio 27.0.1（64bit）
moonlight 3.1.4

Software screens can capture
Cannot capture after opening remote

**Comment by xCISACx** [comment]
This is still a problem.
Moonlight doesn't show up in the Window Capture list, only Game Capture.
It also refuses to show up on Discord's stream window selection unless I alt-tab multiple times.
