### ISSUE TITLE
Installation instructions for Raspberry Pi fail

### ISSUE THREAD

**Issue by shodanx2** [moonlight-stream/moonlight-qt#641]
Install as per https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4

I tried with or without sudo, same thing

pi@raspberrypi:~ $ sudo curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | sudo -E bash
Executing the  setup script for the 'moonlight-game-streaming/moonlight-qt' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=raspbian  version=10  codename=buster  arch=armv7l  
 >>>>:
 NOPE: Checking for apt dependency 'apt-transport-https' ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Reading package lists...
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact Moonlight Game Streaming for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/moonlight-stream/moonlight-qt
 !!!!:

**Comment by Jorys-Paulin** [comment]
Hello! Seems like the required package `apt-transport-https` isn't installed, can you try installing it and running the script again?

**Comment by shodanx2** [comment]
Hello,
I can confirm the issue has been resolved as per the latest script.
I have tried today the installation went through without errors !
