### ISSUE TITLE
Domai names

### ISSUE THREAD

**Issue by gatosyperros** [moonlight-stream/moonlight-qt#642]
**Is your feature request related to a problem? Please describe.**
As of now it seems that the client's are only able to process IP's.
I already have a domain name registered that I use to connect to my server's many services, and it would be a treat to be able to connect only using the domain name, as public IP's could change at any moment.
 

**Describe the solution you'd like**
Obviously haviving a way to resolve domain names into IP's would make life so much easier for a lot of people, especially if you're running a DDNS

**Describe alternatives you've considered**
non that are very practical, I got about 4 pc that run a custom script. that script uploads their public IP onto the main server that host the website (and runs the domain) that way I can simply manually look it up using one domain instead of 5.

using domain1.com and domain2.com would be a bit easier to set up when I'm away.

**Comment by cgutman** [comment]
This is already supported. You can use a domain name in the Add PC dialog.
