### ISSUE TITLE
Dynamic Session Menu

### ISSUE THREAD

**Issue by gatosyperros** [moonlight-stream/moonlight-qt#643]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
an easy way to dynamically control the quality and parameters of the session.
Right now I'm running this on a quite old and out dated computer and the client does not even run properly (the UI does not display anything it's just a white window). taking inspiration from some other applications I use to remote control my systems I would love to have a way to control the currently opened sessions like setting up the FPS, resolution and quality (bitrate) of the stream on the fly.
Not only as a way to make my crappy set up work currently, but as a time saver, when you need/want to adjust a single parameter while the session is on going.

**Describe alternatives you've considered**
non

**Additional context**
non

**Comment by cgutman** [comment]
Unfortunately the GameStream protocol always negotiates these parameters at connection-time, so this is not possible to implement unless/until we figure out how to change them on the fly.

**Comment by gatosyperros** [comment]
Ah Ok, that's too bad, but totally understandable.
Thanks for the clarification.
