### ISSUE TITLE
Close all running sessions before connection

### ISSUE THREAD

**Issue by gatosyperros** [moonlight-stream/moonlight-qt#644]
**Is your feature request related to a problem? Please describe.**
I just stared using it, I was setting it up remotely using some other form of remote control and while trying to set it up my client happened to crash. I was then unable to reconnect due to "an app is currently running either end it or restart the host before opening a new session"

**Describe the solution you'd like**
I would like to have an option to "end all open/running sessions prior to connecting" option, kinda like how some other software do it, that way you can easily hope from machine to machine... or pick up from where the client ended, without the need to ssh in/power down the PC

**Describe alternatives you've considered**
I run two types of remote services, one that is highly dynamic and ends disconnects old connection upon connecting to it, so I was able to end shield sharing in the Gforce control panel, re-enable it, enter the new paring code.... and then reconnect.
 

ps sorry for the triple issue post, but I just started using the moonlight, and those are my 3 main issues as of right now compared to the other remote solution that I currently use.

**Comment by cgutman** [comment]
You can reconnect a session that was started on a different client without any issues. You can even connect while another client is already connected, which will disconnect the other client just like you requested.

The only thing you can’t do is pair while a session is active, and that’s a restriction that GeForce Experience enforces. We can’t do anything about that (and allowing an unpaired client to terminate all connections would be a DoS security vulnerability).
