### ISSUE TITLE
AMD FidelityFX Super Resolution or similar technology up-scaling 

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#647]
Would it be possible to implement some kind of technology like AMD FidelityFX Super Resolution into the Moonlight client, which upscales from 1080p to 4k maybe so it wouldnt look blurry?

**Comment by PolCPP** [comment]
@makedir As a 'hack' you can use the "Lossless Scaling" app with moonlight.

**Comment by makedir** [comment]
@PolCPP what lossless scaling app?

**Comment by PolCPP** [comment]
@makedir  https://store.steampowered.com/app/993090/Lossless_Scaling/

**Comment by makedir** [comment]
@PolCPP thanks. but it doesnt say anything about 4k. it works on videos though?

**Comment by PolCPP** [comment]
@makedir Pretty much it captures the screen at the center and scales it through FSR or Integer scaling (depending of your choice), you can put the output % scaling. So pretty much running moonlight on window mode in the middle at 1080p then using this to scale it 200% does the trick

**Comment by makedir** [comment]
@PolCPP thank you so much for this tip. it actually works great. the integer scaling from 1080p to 4k looks way sharper than using the "in build" scaling of moonlight (1080 run as fullscreen window). why is this the case?

Would it make more sense to use the tool on client side to rescale he video stream, or use on server side and then stream in 4k video?

**Comment by PolCPP** [comment]
@makedir No idea why it looks better using integer scaling than just moonlight, i guess moonlight uses bilinear or trilinear scaling which makes things more softer but allows to fractional scaling (lets say from 1920p to 1440p), which integer scaling does not.

TBH, where to run it mostly depends on your bandwidth , but i swear that FSR cleans up a bit the barely noticeable video artifacts moonlight has

**Comment by makedir** [comment]
@PolCPP What scaling is allowed with integer scaling? Just factors of 2^n? like 2,4,8? But you can select a free factor in the tool, for example 3 with integer too.

So 1440p to 4k does not work either, right?

I think the window on the client side, the tool scales from, always needs exactly the proper input resolution, youre not allowed to re scale the window before scaling with the tool?

I have a 1080p in my server, which is obviously not capable to render 4k but older games, 1440p is also a problem already. And I am using a 4k laptop as a client, a Dell XPS 15 9570.

Would it make sense, to rise the bandwith in Moonlight for 1080 from 20mbit/s to maybe 30mbit/s to maybe reduce codec fragments? I guess fragments are very "bad" for this kind of idea of integer scaling, because it needs a 100% "clean" image, I guess?

So maybe it would make more sense to set the server to 4k, then start games on the server in 1080p window mode, scale the game on the server with the tool to 4k, and then use 4k video streaming with moonlight?

**Comment by redromnon** [comment]
Upscaling on Windows seems to have a solution thanks to Lossless Scaling. But what about Linux users using Moonlight?
Are you aware of any such alternatives?
