### ISSUE TITLE
PC - When I start streaming it zooms out repeatedly to form a loop

### ISSUE THREAD

**Issue by Shaun-Harries** [moonlight-stream/moonlight-qt#65]
**Describe the bug**
I start a game - tried Monster Hunter World and Dark Souls 3. The game itself will launch - Moonlight will zoom out repeatedly that will repeat anything about 20 times - the sound included - tested with music and ingame sound. It also sets my resolution to 1280x720 even though I have set it to Native(1360x768). Once I close the game it sets back to my native reso. That also applies to the game - it will open it in 1280x720.

**Steps to reproduce**
I set my settings to Native Reso - clicked the game - issue.

**Screenshots**
https://gyazo.com/8be36f16c5ae1083a7db78f71e22964f

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- Turned off fullscreen and set to my reso - turned off sound as it was hurting my ears with the loop. 
- Problem still occurs in fullscreen.

**Client PC details (please complete the following information)**
 - OS: Latest Windows 10 Home.
 - Moonlight Version: v.0.3.0

**Logs (please attach)**
- More than one - so added them all.
[Moonlight_Game_Streaming_Client_20180907235105.log](https://github.com/moonlight-stream/moonlight-qt/files/2362890/Moonlight_Game_Streaming_Client_20180907235105.log)
[Moonlight_Game_Streaming_Client_20180907235105_000_Moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/2362891/Moonlight_Game_Streaming_Client_20180907235105_000_Moonlight.log)
[Moonlight-1536360718.log](https://github.com/moonlight-stream/moonlight-qt/files/2362892/Moonlight-1536360718.log)
[Moonlight-1536361710.log](https://github.com/moonlight-stream/moonlight-qt/files/2362893/Moonlight-1536361710.log)
[Moonlight-1536361721.log](https://github.com/moonlight-stream/moonlight-qt/files/2362894/Moonlight-1536361721.log)
[Moonlight-1536361822.log](https://github.com/moonlight-stream/moonlight-qt/files/2362895/Moonlight-1536361822.log)
[Moonlight-1536362188.log](https://github.com/moonlight-stream/moonlight-qt/files/2362896/Moonlight-1536362188.log)
[Moonlight-1536362863.log](https://github.com/moonlight-stream/moonlight-qt/files/2362897/Moonlight-1536362863.log)
[Moonlight-1536366770.log](https://github.com/moonlight-stream/moonlight-qt/files/2362898/Moonlight-1536366770.log)
[Moonlight-1536367088.log](https://github.com/moonlight-stream/moonlight-qt/files/2362899/Moonlight-1536367088.log)
[Moonlight-1536367650.log](https://github.com/moonlight-stream/moonlight-qt/files/2362900/Moonlight-1536367650.log)

**Comment by cgutman** [comment]
It looks like you're streaming to the same machine you're streaming from, which is why you get that hall of mirrors when effect. Moonlight is meant for streaming from your gaming PC to other PCs and devices.

What are you trying to do?

**Comment by Shaun-Harries** [comment]
I was trying to let a mate play a game through my pc - in the end he couldn't add my ip etc so I gave up. We just use geforce experience now - and discord stream if he wants to watch.

**Comment by cgutman** [comment]
Ok, you would need to port forward on your router to let someone connect to you.

In any case, this is working as intended.
