### ISSUE TITLE
Using Moonlight on the different user

### ISSUE THREAD

**Issue by genialen** [moonlight-stream/moonlight-qt#651]
I have a gaming PC but I use it only for web-surfing. I want to add new user and give access through Moonlight connected to mstsc.exe to my friend who may play different games he wants not interrupting me and my user experience. Is there any possibility of that?

**Comment by Jorys-Paulin** [comment]
Hello, if you want to have two people using the same computer at the same time, just "adding a new user" won't do it. There's a way to do it, but it requires setting up virtual machines, here's a video tutorial that explains the idea: https://www.youtube.com/watch?v=XLLcc29EZ_8
