### ISSUE TITLE
Proper 21:9/Ultrawide Support

### ISSUE THREAD

**Issue by nigeljmckernan** [moonlight-stream/moonlight-qt#653]
**Is your feature request related to a problem? Please describe.**

Whenever connecting to my host machine, which runs a 21:9 resolution (3440x1440), attempting to switch to a 16:9/Widescreen resolution ends up with weird graphical artefacts appearing. 

Also, if trying to just deal with running the 21:9 resolution, Moonlight opts to _squish_ the resulting image, instead of maintaining the aspect ratio of the host machine and scaling appropriately to fit the client machine's window, like Parsec does.

**Describe the solution you'd like**

Present an "Aspect Ratio" option for the client machine when connecting, or to correct the current issue of 16:9 resolutions on the host machine not appearing correctly appearing on the client machine.

**Describe alternatives you've considered**

Parsec handles this just fine, however I refrain from using it as I get better/more consistent gaming performance with Moonlight.

**Additional context**

This is what it looks like when running a 21:9 resolution beamed to the client machine (noticed how everything is squished):

![Ultrawide Screen](https://user-images.githubusercontent.com/71948964/134983453-10a785a7-2fcb-42e4-a0e4-6a88fe7599a5.png)

And here's what it looks like when trying to change the host machine to a 16:9 resolution (1920x1080 in this case):

![Standard Widescreen](https://user-images.githubusercontent.com/71948964/134983597-bd752609-3ae5-4a49-8ecb-f29ffae39815.png)

It looks like it overlays the new 16:9 image over the original 21:9 image, but not scaling the 16:9 window to fill the screen.

This issue appears to be quite old; dating back to at least [this Reddit post](https://www.reddit.com/r/ultrawidemasterrace/comments/56xzfv/nvidia_gamestream_moonlight_219_monitor_issue/?utm_source=BD&utm_medium=Search&utm_name=Bing&utm_content=PSR1).

If this is such an old issue, I assume it's a GameStream-related issue and not something Moonlight can address? I would love to be proved wrong about this.

**Comment by cgutman** [comment]
GeForce Experience uses a stretch-to-fill method when encoding your host desktop resolution at the resolution selected in Moonlight. Moonlight _does_ preserve aspect ratio, but you have to pick a stream resolution that matches the aspect ratio of your host PC or GFE will scale things before Moonlight even sees it. Use the custom resolution option in Moonlight to choose a 21:9 resolution if you want your stream in aspect-ratio-preserved 21:9.

If you want it in 16:9 (or anything else), you have to change the resolution on the host using the NVIDIA Control Panel, not Windows display settings, to avoid the video glitch you saw.

**Comment by nigeljmckernan** [comment]
> GeForce Experience uses a stretch-to-fill method when encoding your host desktop resolution at the resolution selected in Moonlight. Moonlight _does_ preserve aspect ratio, but you have to pick a stream resolution that matches the aspect ratio of your host PC or GFE will scale things before Moonlight even sees it. Use the custom resolution option in Moonlight to choose a 21:9 resolution if you want your stream in aspect-ratio-preserved 21:9.
> 
> If you want it in 16:9 (or anything else), you have to change the resolution on the host using the NVIDIA Control Panel, not Windows display settings, to avoid the video glitch you saw.

Tried your suggestion by changing the resolution in Nvidia Control Panel to 1080P while connected to the host machine and it works.

I'll close this issue but leave the following advice for posterity:

After connecting to the host machine with `C:\Windows\System32\mstsc.exe`, change the host's resolution in _Nvidia Control Panel_, and *NOT* through Windows Settings.

Thanks, @cgutman.
