### ISSUE TITLE
snap glibc 2.33

### ISSUE THREAD

**Issue by brightdroid** [moonlight-stream/moonlight-qt#666]
Upgraded to Ubuntu 21.10 and now I'v following dependency problem with glibc:

> /snap/moonlight/1403/usr/bin/moonlight: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)

Using this snap version:
```
$ sudo snap list moonlight
Name       Version  Rev   Tracking       Publisher  Notes
moonlight  3.1.4    1403  latest/stable  maxiberta  -
```

**Comment by maxiberta** [comment]
Are you using an nvidia gpu with the proprietary driver by any chance? There's [a known bug](https://forum.snapcraft.io/t/egl-using-snaps-on-impish-seem-to-be-broken-when-using-the-nvidia-proprietary-driver/25715) affecting snaps on Ubuntu 21.10 with the prorpietary nvidia drivers, unfortunately.

**Comment by maxiberta** [comment]
As a quick workaround, I've force installed the old EGL libs from Ubuntu 21.04 hirsute with great results, fwiw:

```bash
# Add the official ubuntu 21.04 hirsute repo
$ cat /etc/apt/sources.list.d/hirsute.list
deb http://archive.ubuntu.com/ubuntu hirsute main restricted

# Pin the affected packages to the hirsute versions
$ cat /etc/apt/preferences.d/libegl-hirsute
Package: libegl1 libglvnd0 libglx0 libgles2 libopengl0 libgl1
Pin: release n=hirsute
Pin-Priority: 900

# Manually downgrade the affected packages to their hirsute versions
$ sudo apt install lib{egl1,glvnd0,glx0,gles2,opengl0,gl1}=1.3.2-1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be DOWNGRADED:
  libegl1 libgl1 libgles2 libglvnd0 libglx0 libopengl0
0 upgraded, 0 newly installed, 6 downgraded, 0 to remove and 0 not upgraded.
Need to get 251 kB of archives.
After this operation, 20,5 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

**Comment by brightdroid** [comment]
Yes I'm using ubuntu nvidia 470 packages. So as I understand we've to wait for a fix in snap(d)? or use your workaround with the old libegl?

**Comment by maxiberta** [comment]
> Yes I'm using ubuntu nvidia 470 packages. So as I understand we've to wait for a fix in snap(d)? or use your workaround with the old libegl?

Yes, that's my understanding.

**Comment by maxiberta** [comment]
This should be fixed now on `stable`.

**Comment by brightdroid** [comment]
Thanks, working again :)
