### ISSUE TITLE
I can't generate cross-build on linux, for windows(.exe)

### ISSUE THREAD

**Issue by levioase** [moonlight-stream/moonlight-qt#667]
Looking for a way to run the build for windows, I found a solution on stackoverflow, but I couldn't go through the next step:
  - Get to the directory of your app, and run the Qt Makefile generator tool: <mxe root>/usr/bin/i686-w64-mingw32.static-qmake-qt5

even trying to use the route where "mxe" was installed, it doesn't recognize the file or directory, should this step be done in build-release or moonlight-qt folder?

[https://stackoverflow.com/questions/14170590/building-qt-5-on-linux-for-windows](url)

![Screenshot from 2021-11-05 14-41-18](https://user-images.githubusercontent.com/93149471/140555032-dec23b59-1979-40b7-b3b4-cb9e3f1b6d36.png)

**Comment by cgutman** [comment]
Building with MinGW is not supported. You'll need to use MSVC on a Windows machine/VM.
