### ISSUE TITLE
Fullscreen does not grab input

### ISSUE THREAD

**Issue by AdamKlob** [moonlight-stream/moonlight-qt#669]
OS: Windows 11

I have another fullscreen app (VLC) already running (it does not have to be fullscreen to reproduce).

I start Moonlight streaming in fulscreen mode. I see it on top, but keyboard input goes to VLC.

**Comment by cgutman** [comment]
Interesting, Moonlight does avoid grabbing input if it thinks it's not the top-most window to avoid trapping the mouse with no way to interact with Moonlight to unbind it. I suspect Moonlight thinks it's not the top-most window.

Does this just happen with VLC or also other apps? Does it happen with Moonlight in both full-screen and borderless windowed modes?
