### ISSUE TITLE
Error during L4T Moonlight-qt installation

### ISSUE THREAD

**Issue by usepit** [moonlight-stream/moonlight-qt#672]
When I run moonlight-qt on my Jetson Nano I get the following:

> 00:00:00 - SDL Info (0): Compiled with SDL 2.0.15
00:00:00 - SDL Info (0): Running with SDL 2.0.15
00:00:00 - Qt Info: No translation available for  "en_US"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 127 new gamepad mappings
00:00:01 - SDL Info (0): V-sync disabled
00:00:01 - SDL Info (0): Using SDL renderer
00:00:01 - FFmpeg: [h264_mp4toannexb @ 0x7f701e2990] The input looks like it is Annex B already
Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
Segmentation fault (core dumped)

No idea where to begin solving this, thanks.

**Comment by cgutman** [comment]
install Moonlight debugging symbols with `sudo apt install moonlight-qt-dbgsym`, then run `gdb moonlight-qt`. When it crashes, you should get a debugger prompt. Type `bt` and press enter at that prompt then attach that output here.

**Comment by usepit** [comment]
> #0  0x0000007fa8993c84 in NvxUpdateNvMMBufferToNvMediaVideoSurface ()
    at /usr/lib/aarch64-linux-gnu/tegra/libnvmedia.so
#1  0x0000007fa8b5cc04 in  ()
    at /usr/lib/aarch64-linux-gnu/tegra/libnvmmlite_video.so
#2  0x0000007fa89b1338 in  () at /usr/lib/aarch64-linux-gnu/tegra/libnvmedia.so
#3  0x0000007fa890fe18 in  ()
    at /usr/lib/aarch64-linux-gnu/tegra/libnvparser.so
#4  0x0000007fa891332c in  ()
    at /usr/lib/aarch64-linux-gnu/tegra/libnvparser.so
#5  0x0000007fa890cfa4 in  ()
    at /usr/lib/aarch64-linux-gnu/tegra/libnvparser.so
#6  0x0000007fa890ddc8 in  ()
    at /usr/lib/aarch64-linux-gnu/tegra/libnvparser.so
#7  0x0000007fa89b1dd8 in NvMediaParserParse ()
    at /usr/lib/aarch64-linux-gnu/tegra/libnvmedia.so
#8  0x0000007fa8b587d4 in  ()
    at /usr/lib/aarch64-linux-gnu/tegra/libnvmmlite_video.so
#9  0x0000007fb6437628 in  () at /usr/lib/aarch64-linux-gnu/tegra/libnvos.so
#10 0x0000007fb6a37088 in start_thread (arg=0x7fa9a6a31f)
    at pthread_create.c:463
#11 0x0000007fb6714ffc in thread_start ()
    at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

**Comment by usepit** [comment]
afaict from a quick google search this has something to do with nvidia's ffmpeg implementation, supposedly compiling from source fixes a similar error in another program but it did nothing for me.

**Comment by usepit** [comment]
any news? Tried a fresh install of L4T without luck

**Comment by cgutman** [comment]
Fixed in v4.0.0 by #745
