### ISSUE TITLE
Unable to install on Raspbian Bullseye, found workaround

### ISSUE THREAD

**Issue by JoelHobson** [moonlight-stream/moonlight-qt#675]
**Describe the bug**
Following the installation instructions in the wiki [here ](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4) in Raspbian Bullseye on a Raspberry Pi 4 reports that the moonlight-qt package cannot be found. It looks like the install script just uses the codename of the current operating system, but doesn't have a fallback in case the package doesn't exist for that version.

**Steps to reproduce**
Run the following:
```
curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | sudo -E bash
sudo apt install moonlight-qt
```

**Client PC details (please complete the following information)**
 - OS: Raspbian Bullseye

**Solution**
The issue occurs because there isn't a package available for Bullseye. To work around this, I updated `/etc/apt/sources.list.d/moonlight-game-streaming-moonlight-qt.list` and replaced instances of `bullseye` in `deb https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/deb/<distro> <version> main` with `buster`. After this, I was able to `sudo apt install moonlight-qt` successfully.

Once installed, there was another problem where launching a game led to a blank screen. I was able to figure out that I needed to comment out the line `dtoverlay=vc4-kms-v3d` in `/boot/config.txt` and restart the Pi to avoid this. Everything worked after that. 

It may be worth updating the documentation to mention these workarounds.

**Comment by cgutman** [comment]
Thanks, added notes about those workarounds to the wiki.
