### ISSUE TITLE
black screen under GeForce Game Ready driver 496.76

### ISSUE THREAD

**Issue by tomjamescn** [moonlight-stream/moonlight-qt#677]
**Describe the bug**
black screen under GeForce Game Ready driver version 496.76, moonlinght works fine under driver version 456.71.

**Steps to reproduce**
use geforce experience upgrade the latest driver (496.76)，moonlinght client can connect the game server，but screen is black, audio is ok.

**Screenshots**
the whole black  on the screen

**Affected games**
all games and remote desktop app (mstsc.exe)

**Other Moonlight clients**
have not try.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
Yes

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
No

**Client PC details (please complete the following information)**
 - OS: mac os 12.0.1
 - Moonlight Version: 3.1.4

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro 21H1
 - GeForce Experience version: 3.24.0.114
 - Nvidia GPU driver: 496.76

**Comment by cgutman** [comment]
I just tried streaming with identical versions (macOS 12.0.1, Moonlight 3.1.4, and Win10 21H1, GFE 3.24.0.114, and 496.76) and it works properly for me.

Can you provide the Moonlight log files from the `/tmp` folder on your Mac?

Please also provide the logs from your host PC in `C:\ProgramData\NVIDIA Corporation\NvStream`.

**Comment by Sl4vP0weR** [comment]
Same issue here!

**Comment by mrwiwi** [comment]
Same here... Will try to provide logs, same error under macos and linux on Intel and AMD machines...

**Comment by mrwiwi** [comment]
[NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-qt/files/7576891/NvStreamerOld.log)

**Comment by cgutman** [comment]
What GPUs are you all using in your host PCs?

I haven’t had any problems streaming from a RTX 2080 Super, GTX 970, or GTX 750 Ti with the 496.76 driver.

**Comment by mrwiwi** [comment]
GTX1650 and got the issue when playing BF2042 with freezes or black screen, need to quit and restart stream, multiple times. Got back on old drivers, no issues in 1 hour !

**Comment by MonkeyTime** [comment]
Hi,

Same issue with the same driver under windows 11. I experienced the black screen with a display port cable (maybe a track to explore) and in this case when I have the 2nd screen connected moonlight stream the 2nd stream. RTX 2070.

**Comment by mrwiwi** [comment]
I'm on HDMI directly, the issue probably come from the host, downgrading driver fixes everything !

**Comment by Sl4vP0weR** [comment]
> GTX1650

Same

**Comment by Adam1986** [comment]
Morning,

I'm also facing issues too, I actually downgraded to 496.49 and whilst its not as bad as I experienced on the newer driver, it still does ocurr.

My system has a GeForce GTX 1060 6GB.

I've attached a log from a few days ago where this was happening.

[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/7607671/NvStreamerCurrent.log)

**Comment by cgutman** [comment]
Try disabling Hardware-Accelerated GPU Scheduling.

**Comment by Sl4vP0weR** [comment]
On 496.49 I've got my host pc always offline, strange

**Comment by Adam1986** [comment]
> Try disabling Hardware-Accelerated GPU Scheduling.

That might have done the trick with some early testing I've done on driver 472.12 as I also tried downgrading to that but it was still causing me trouble.

Will do some more testing and then update the driver again and see how I get on.

**Comment by cgutman** [comment]
@mrwiwi @Sl4vP0weR @MonkeyTime does disabling Hardware-Accelerated GPU Scheduling fix it for you too?

**Comment by MonkeyTime** [comment]
@cgutman only tested the downgrade to 456.71. Moonlight with nvidia driver 497.09 work great now with and without Hardware-Accelerated GPU Scheduling.

**Comment by Sl4vP0weR** [comment]
> 

I'll try soon

**Comment by tomjamescn** [comment]
RTX 3080

**Comment by Sl4vP0weR** [comment]
When I connected by my second PC as a client, first PC(host) got bpack screen for all clients.

**Comment by tomjamescn** [comment]
> When I connected from my second PC as a client, first PC(host) got black screen for all clients.

May be only one client online at same time.

**Comment by Sl4vP0weR** [comment]
> May be only one client online at same time.
It just making all other clients show the same black screen when they're connected.

**Comment by mrwiwi** [comment]
Still happening on latest driver version... nvidia don't seem to care much..

**Comment by feitianjumao** [comment]
在图形设置里面 开启GPU加速计划之后  当你退出串流  大概率会黑屏   关闭这个GPU加速计划 这个问题就会消失---Original---From: "William ***@***.***>Date: Sun, May 8, 2022 01:03 AMTo: ***@***.***>;Cc: ***@***.***>;Subject: Re: [moonlight-stream/moonlight-qt] black screen under GeForce GameReady driver 496.76 (Issue #677)
Still happening on latest driver version... nvidia don't seem to care much..

**Comment by mrwiwi** [comment]
> 在图形设置里面 开启GPU加速计划之后  当你退出串流  大概率会黑屏   关闭这个GPU加速计划 这个问题就会消失---Original---From: "William ***@***.***>Date: Sun, May 8, 2022 01:03 AMTo: ***@***.***>;Cc: ***@***.***>;Subject: Re: [moonlight-stream/moonlight-qt] black screen under GeForce GameReady driver 496.76 (Issue #677) Still happening on latest driver version... nvidia don't seem to care much.. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Yes I know thanks, but it's a workaround, not a fix...

**Comment by cgutman** [comment]
It has been reported to NVIDIA and they have confirmed it in their labs. We cannot fix it from our side since it's a bug in their graphics driver.

See https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/27
