### ISSUE TITLE
PS5 Controller vibration not working

### ISSUE THREAD

**Issue by ayushsharma82** [moonlight-stream/moonlight-qt#678]
**Describe the bug**
The vibration on PS5 controller is not working on any moonlight client.

**Comment by Jorys-Paulin** [comment]
Hello! Could you give more details about your setup? I just tested on my setup (Windows to Windows) and vibration works both on USB and Bluetooth

**Comment by ayushsharma82** [comment]
Hi @Jorys-Paulin , 
Thanks for the quick reply!

I've 2 setups and vibration doesn't work in either one of those:
1. PC: PS5 Controller + DS4Windows + Moonlight ( Game: "Control" )
2. Android TV: PS5 Controller + Moonlight Android App from Play Store ( Game: "Control" )

I think the issue is more about vibration data not getting passed to the moonlight client?

Testing Procedure:
This is the website I used to test further: https://gamepad-tester.com/ , The vibration works when the controller is connected directly to the host PC with DS4Windows but fails to work when the controller is connected to client PC or any other client device including android TVs.

**Comment by Jorys-Paulin** [comment]
Hello! I don't use DS4Windows personally, and I have a PS4 controller not a PS5 one. While it works on my Windows client, on my Android phone it seems like the phone itself is vibrating, and not the controller.
Note: Trying out https://gamepad-tester.com/ inside Chrome on Android, there's no vibration option but that doesn't mean Android doesn't support it, just that Chrome doesn't.

**Comment by ayushsharma82** [comment]
I think the PS5 controller is to be blamed. It must have changed how vibration feedback is delivered to the controller. Is this something that can be fixed with the moonlight client?

**Comment by Jorys-Paulin** [comment]
I'm not sure, as Moonlight probably doesn't vibrate the controller directly, instead it relies on the operating system to do it, but that means the OS has to support it, or a third-party software like DS4Windows to support it.

Have you tried installing DS4Windows on the client computer? My idea is the controller could first go trough DS4Windows, then Moonlight, and back. Maybe then, when Moonlight receives a vibration input, it'll be able to pass it to DS4Windows, and DS4Windows would make the controller vibrate?

**Comment by ayushsharma82** [comment]
Setup1: I meant DS4Windows on the client PC. I’ve went deep into DS4Windows
and tried every option but the controller didn’t vibrate with moonlight
client.

**Comment by Jorys-Paulin** [comment]
Perhaps DS4Windows is causing the issue then??? Do you have DS4Windows on the server/host side? I don't think it should change anything, since GFE (and Sunshine by default) emulates an Xbox controller and not a PS4 one so DS4Windows shouldn't affect the Xbox controller right?

**Comment by SerLinux** [comment]
When I allow moonlight of iPadOS, ds4Windows cannot recognize my ds4, and I do not vibrate

**Comment by dexotaku** [comment]
Hi Ayushasharma82,
I don't have exactly the same problem but it may be related, 
I currently use a PS5 controller and DS4Windows through the Moonlight Client (on Windows 10 21H2). 
The server only sees a generic "XBox 360 Controller" and doesn't know of the presence of DS4Windows. 
Vibration wasn't working - and the fault was entirely on the machine acting as server. Testing the controller on the client machine with DS3Windows itself or other tools worked fine. Only the Shield-Moonlight combo was broken.
Restarting would not restore vibration and neither would a supposed shut down and cold power-cycle.
Disabling Windows' fast boot made it so restarting if it stopped working fixed the issue every time.
I wish I could remember where I found the advice, as they explained why it works for this,

Cheers,
d

**Comment by Bauzival** [comment]
I can confirm that rumble function is not working using the PS5 controller. Works fine with other controllers.

**Comment by cgutman** [comment]
@Bauzival please file a new issue and fill in all information requested by the bug report template
