### ISSUE TITLE
Moonlight unstable after upgrading graphics drivers

### ISSUE THREAD

**Issue by BitRift** [moonlight-stream/moonlight-qt#682]
I was running Moonlight 3.1.4 on Windows for many hundreds of hours of glitch-free gaming until I upgraded my nVidia graphics drivers on both host and client PC to 496.76.

I don't have the verison number of the previous driver I had installed but it was recent, maybe two months old.

Immediately after the upgrade and ever since, the stream will freeze (completely unresponsive) about once every two or three hours of play, requiring a restart of Moonlight. It seems to happen at the exact moment that I make a mouse click.

I guess the problem may be with nVidia but I thought I would report it here first, perhaps you can run some QA on a basic PC to PC setup with this driver at both ends.

My Windows is up to date and my hardware is solid. I am not sure if it could be game specific (I will try and verify) but I have mostly been playing MTG Arena (both before and after the upgrade).

**Comment by cgutman** [comment]
Try turning off hardware accelerated GPU scheduling on your host PC.

**Comment by BitRift** [comment]
Thank you, this seems to have fixed it. It’s also possible that I changed this setting myself in which case sorry for the misleading suggestion that the driver upgrade was at fault.

**Comment by cgutman** [comment]
Hardware accelerated GPU scheduling used to work reliably prior to the 496 driver series, so it's possible that you had it on for a while and didn't experience issues.

**Comment by Wytoo** [comment]
Is this something that has been fixed now by the moonlight and/or NVidia Team? Cause sometimes you'll get a huge FPS Boost. ex. Cyberpunk 2077 gives me around 15-20 fps more if enabled.
