### ISSUE TITLE
How to specify alsa audio output device ?

### ISSUE THREAD

**Issue by cuteprince** [moonlight-stream/moonlight-qt#689]
I know we can force alsa backend using the PULSE_SERVER=none flag. However there is no mention of how to specify an audio output device. In moonlight-embedded we can specify alsa audio output device using -audio flag. How can I achieve similar functionality in moonlight-qt ?

**Comment by cgutman** [comment]
Moonlight uses SDL2 for audio on Linux, so you should be able to use the `SDL_AUDIO_DEVICE_NAME` environment variable to control the chosen audio device.

**Comment by cuteprince** [comment]
Thanks for the update @cgutman . Also I was wondering where does the flag PULSE_SERVER is being used ? I went through the code and found no reference of it being used in the moonlight codebase. Is it being used by some third party library ?

**Comment by cgutman** [comment]
`PULSE_SERVER` is used by the underlying PulseAudio client library itself.
