### ISSUE TITLE
The button 'start' can't work

### ISSUE THREAD

**Issue by everxola** [moonlight-stream/moonlight-qt#69]
when i play monster hunt world. the start button can't work,but at the panel control.it's work fine. i use xbox controller.

**Comment by cgutman** [comment]
Is this a game-specific issue? Does it happen in other games?

**Comment by everxola** [comment]
the other game work fine.I think it's gem-specific issue. the same issue happened in android. We need custom button . like steam link app.  then we can use different gamepad with same experience.

**Comment by everxola** [comment]
The problem is steam.When i disable option  xbox controller support.Then work fine.when i connect local pc. it's always worked.The issue only happend moonlight streaming steam game.

**Comment by cgutman** [comment]
Thanks for noting the solution. Hopefully this helps other people with this same issue.
