### ISSUE TITLE
[macOS] Allow rebinding of 'command ⌘' key

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-qt#693]
# Problem
I frequently use Moonlight on my 2020 MacBook Air to play games running on my Linux desktop (running [Sunshine](https://github.com/loki-47-6F-64/sunshine)) several US states away (my MacBook being with me in North Carolina, my PC being all the way in Ohio). Everything works great, except a minor annoyance: the 'command ⌘' key on my Macintosh keyboard does nothing when accessing my Linux machine.

# Proposed feature
Having the option for the Moonlight client to broadcast 'control ⌃' or 'super ⊞' when pressing 'command ⌘' on a macOS client would be very useful. When remotely accessing my full desktop, having the key function as a 'super ⊞' key would be quite useful. Similarly, when playing games (such as first-person shooters, where 'control ⌃' is traditionally the key for crouching), there should be an option for the key to function as 'control ⌃'.
Technically, one can use a Macintosh keyboard on a Windows or Linux client as well (meaning they could encounter the same issue), so this proposal is not strictly limited to macOS clients.

**Comment by cgutman** [comment]
You can pass the super key to the host with the "Capture system keyboard shortcuts" option in Moonlight.

<img width="446" alt="Screen Shot 2021-12-19 at 4 25 49 PM" src="https://user-images.githubusercontent.com/2695644/146693009-8c480a1d-bd3d-41c0-9ca8-f377ab4195d9.png">

Support for remapping modifier keys is a more complicated issue. I'm not sure how applicable that situation is to non-Macs. I would rather not overload the settings screen with options that are platform-specific or only applicable to very few users.

**Comment by EmmyGH** [comment]
> You can pass the super key to the host with the "Capture system keyboard shortcuts" option in Moonlight.
> 
> <img alt="Screen Shot 2021-12-19 at 4 25 49 PM" width="446" src="https://user-images.githubusercontent.com/2695644/146693009-8c480a1d-bd3d-41c0-9ca8-f377ab4195d9.png">
> 
> Support for remapping modifier keys is a more complicated issue. I'm not sure how applicable that situation is to non-Macs. I would rather not overload the settings screen with options that are platform-specific or only applicable to very few users. Most games do allow you to remap keys anyway.
> 
> If other folks have use cases for modifier remapping, I'd be interested to hear if there's a broader use case for this than I can come up with.

To add more information regarding the usage of the key: In macOS, the 'command ⌘' key essentially does what 'control ⌃' would do on a Windows or Linux machine. Even outside of games, it would be a lot more convenient to use the 'command ⌘' key to do things such as copy-pasting, just like one would in macOS. It's a minor annoyance when seemingly all of the sudden your keyboard shortcuts aren't working once you've switched to Moonlight, and then you remember you're supposed to now be using a different key.
