### ISSUE TITLE
SHIELD tab is missing in GeForce Experience

### ISSUE THREAD

**Issue by LingHsvan** [moonlight-stream/moonlight-qt#695]
The computer is configured with 9900K and 3080Ti. I ran into this problem yesterday. I was still streaming in the afternoon, and suddenly I couldn't connect at night. When I saw the host first displayed "Unable to obtain information\nTroubleshooting prompt", then there was no tab.
Tried the DDU driver and then reinstalled, reinstalled the system, installed the runtime library, installed Windows11 completely...
Most of the online answers are outdated, including the help files of nVIDIA and moonlight. The current NV driver does not have the nvnetwork service. From last night to now, it took a whole day without any solution. The new installation system has accidentally emptied all XGP games.
NV's customer service told me that it was a GFE software bug, and it can only be fixed in the future. Annoying
Translated by Google
电脑配置9900K和3080Ti，昨天碰到了这个问题。本来下午还在串流，晚上突然就怎么也连不上，一看主机先显示“无法获取信息\n故障排除提示”，然后连选项卡都没有了。
尝试过DDU驱动然后重装、重装系统、安装运行库、全新安装Windows11……
网上的回答也大都过时了，包括nVIDIA和moonlight的帮助文档，现在的NV驱动没有nvnetwork服务。从昨天晚上到现在，花了一整天，都没有解决，全新安装系统还不小心把XGP的游戏全清空了。
NV的客服跟我说是GFE的软件BUG，只能等日后修复。神烦

**Comment by ahjsrhj** [comment]
请问有结果了么？
目前我新装的一台机器安装GFE之后 SHIELD选项卡显示无法获取信息，
GFE版本为：3.24.0.123

**Comment by Shicc** [comment]
我昨天都有SHIELD选择，点进去写的是无法获取信息，今天来看直接就没有了，而且我也更新了GFE，更新后也没有SHIELD，网上搜了一堆都没解决

**Comment by LingHsvan** [comment]
我的在三天前已经恢复正常了，不清楚是怎么解决的，可能是NV后台修复，鬼知道。
顺便，今天发现一个不到百元的安卓电视盒子加个蓝牙手柄就能实现SHIELD的功能。

**Comment by Shicc** [comment]
> 

竟然还能恢复。。。我都两周了都还没恢复，只要GFE不出问题，安卓盒子，手机，啥的，能安装moonlight的都可以串流

**Comment by cgutman** [comment]
This isn't the right place to troubleshoot issues with GeForce Experience. Please use [Nvidia's GameStream forum](https://www.nvidia.com/en-us/geforce/forums/gamestream/19/) or our [Discord server](https://moonlight-stream.org/discord) for help.
