### ISSUE TITLE
White screen while on 4G 

### ISSUE THREAD

**Issue by Ayting69** [moonlight-stream/moonlight-qt#696]
Hello

I have an issue when i want to use moonlight with 4G connection

it says me it's too low and the screen is white. Even if i put settings to 480p  30 fps which use 2 mbps, it doesn't work even if the connection is more than 10 time faster

its very annoying, do you have a solution ?

**Comment by cgutman** [comment]
You also have to factor in the upload speed of your PC's Internet connection and the packet loss rate of the connection between the two. If your PC's internet connection or 4G connection have high packet loss rates (even with high speed test results), then your connection is not suitable for streaming games.
