### ISSUE TITLE
Automatically Load Moonlight and Connect on Steam Link [Feature Request]

### ISSUE THREAD

**Issue by Spottyfriend** [moonlight-stream/moonlight-qt#698]
I have found that the best way to use my wireless Xbox One controllers with the Steam Link is to have the Xbox Wireless Adapter plugged into the PC itself (more reliable than the Steam Link native support, especially when also using emulators). However, this means I need an extra controller to operate the Link, load Moonlight and select my PC.

If it is at all possible to implement, I would love to see an option to automatically select Moonlight and automatically connect to a PC. Someone has (it seems) previously automated selection on the Link before ([video here](https://www.youtube.com/watch?v=XSXkFxxkNKs)) although the GitLab project is now down.

The other problem is that the Link needs a controller plugged in to start up properly... In order to solve the problem of needing an extra controller, there'd have to be a workaround for this as well - making the Link thought it had a controller plugged in(?) - which may be difficult. (Although I have no experience so have no idea).

It would be so satisfying if this were a feature. I use BigBox as my launcher (which I currently Direct Launch from Moonlight), and if this all could be done, all I'd have to do would be turn on my PC, turn on the Link and it would (eventually) load up my beautiful games launcher automatically. It'd be so good!

**Comment by Parapeplum** [comment]
You may want to look at this project:
https://gitlab.com/void-li/steamlink-clac
with some tweaking *it could* start the moonlight.
