### ISSUE TITLE
Games are closed when quitting connection despite "Quit App on Host PC " unchecked

### ISSUE THREAD

**Issue by Gr3atsaga** [moonlight-stream/moonlight-qt#699]
My use-case may be slightly different, considering I use an empty batch script to start a connection which essentially allows me to just remote to my desktop.  So I'm not even actually starting the games from the moonlight client directly, but any time I close the connection while I have a game running (I think it's only when they are full screen), they will be closed on my host PC.

I have the "Quit App on host PC after ending stream" option turned off.  In fact, never had it turned on.

It also happens with games that were running on the host PC before the moonlight connection was made.

**Comment by cgutman** [comment]
That's highly unusual. GameStream does not have the capability to close already running applications, so there is not even a mechanism by which what you described could happen (excluding crashes, bugs, etc)

I suspect there is something more going on, like perhaps the game itself or some system process like DWM itself is crashing when the connection terminates.

**Comment by Gr3atsaga** [comment]
I did not mention that this occurs while connecting to the host PC from another network - not sure if that detail would make a difference, but you are probably right.  I might have to check the windows error reporting after this occurs.

Unsure if it would also happen when on the same network.  I can test that when I am at home.

**Comment by Gr3atsaga** [comment]
I can confirm that it happens regardless if I am connected through the local network or over a different network.  I also do not see anything in the windows event viewer.  Although it only seems to happen now when the game has been started during my moonlight connection.  If the game was running prior to the connection, then closing the connection does not seem to close the game.  But if the game was opened during the connection, then the game just closes on the host when the connection is closed.

Any other places to look that might provide some insight?

**Comment by cgutman** [comment]
You could try uploading the logs from `C:\ProgramData\NVIDIA Corporation\NvStream` and I can see if anything jumps out.

**Comment by cgutman** [comment]
Closing as stale. Please reopen with logs if it happens again.

**Comment by Gr3atsaga** [comment]
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/8857797/NvStreamerCurrent.log)

Uploading the streaming log generated during my test. I connected to my host PC from my laptop on the same network through moonlight. Then started the game "Cookie Clicker" which is not fullscreen. Then closed the moonlight connection on my laptop, and watched Cookie Clicker close on my host PC.

I couldn't get it to reproduce closing the game on the host if the game had already been open prior to the connection in this particular instance... but I have seen it happen, and I know it happens most the time when I'm out of network and sometimes when I'm in network.
