### ISSUE TITLE
Shield 2017 Game Controller connected on Streaming PC/Mac Client does not work in games

### ISSUE THREAD

**Issue by VentureNguyen** [moonlight-stream/moonlight-qt#70]
**Describe the bug**
I have a Shield 2017 Game Controller connected on my Mac or PC Moonlight client. When launching a game, the game does not detect my game controller inputs.

**Steps to reproduce**
1. I have Shield 2017 Controller with latest firmware updates
2. I connected Shield Controller to both Mac and PC via usb
3. I can confirm the gamepad is detected on local steam or http://html5gamepad.com/
4. I launch moonlight client
5. I connect to my game server PC
6. I launch a game
7. The game does not detect my game controller inputs. It does detect my mouse/keyboard

**Screenshots**
N/A

**Moonlight settings (please complete the following information)**
I have tried default settings, and also client setting of enabling/disabling multiple controller support.

**Client PC details (please complete the following information)**
 - OS: macOS High Sierra 10.13.4 ; MacBook Pro (Retina, Mid 2012)
 - OS: Windows 10 build 1803 17134.228
 - Moonlight Version: Moonlight PC v0.4.0 (Beta 1)

**Logs (please attach)**
[Moonlight-1536626662.log](https://github.com/moonlight-stream/moonlight-qt/files/2368985/Moonlight-1536626662.log)
[Moonlight-1536627615.log](https://github.com/moonlight-stream/moonlight-qt/files/2368986/Moonlight-1536627615.log)
[Moonlight-1536628508.log](https://github.com/moonlight-stream/moonlight-qt/files/2368987/Moonlight-1536628508.log)

**Additional context**

**Comment by VentureNguyen** [comment]
Also tested on PC Surface 3 and similar results. Gamepad shows up in windows and works fine, but not coming through the moonlight client to server

**Comment by cgutman** [comment]
Try mapping it with this tool - http://www.generalarcade.com/gamepadtool/

**Comment by VentureNguyen** [comment]
@cgutman , I followed your recommendations using the gamepadtool and it worked! Thanks for sharing and your contributions!
