### ISSUE TITLE
Moonlight nightly build crashing 

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#700]
I always like to use the daily build of moonlight, but since aproximately two weeks ago it keeps crashing when I try to stream anything. No issues with the latest release version(3.1.4)
It generates a minidump which I have attached and event viewer states:

Faulting application name: Moonlight.exe, version: 3.1.4.0, time stamp: 0x61d2384c
Faulting module name: SDL2.dll, version: 2.0.19.0, time stamp: 0x61b4fc92
Exception code: 0xc0000005
Fault offset: 0x00000000000faf36
Faulting process id: 0x4028
Faulting application start time: 0x01d8007da8618e79
Faulting application path: D:\Stuff\MoonlightPortable-x64\Moonlight.exe
Faulting module path: D:\Stuff\MoonlightPortable-x64\SDL2.dll
Report Id: 59039168-ee98-4bee-ad3c-47314c8d01f5
Faulting package full name: 
Faulting package-relative application ID: 

[MoonlightPortable-x64.zip](https://github.com/moonlight-stream/moonlight-qt/files/7801015/MoonlightPortable-x64.zip)

**Comment by cgutman** [comment]
Thanks for reporting this. Can you try replacing SDL2.dll with this version and see if the crash goes away?

[SDL2.zip](https://github.com/moonlight-stream/moonlight-qt/files/7804241/SDL2.zip)

**Comment by apoklyps3** [comment]
Seems to go away with the new dllOn 4 Jan 2022 00:02, Cameron Gutman ***@***.***> wrote:
Thanks for reporting this. Can you try replacing SDL2.dll with this version and see if the crash goes away?
SDL2.zip

**Comment by cgutman** [comment]
Please confirm the latest nightly is no longer crashing, then we can close this issue.

https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/42167801/job/m98gk594iqn1fjh4/artifacts

**Comment by apoklyps3** [comment]
Tested. All good. thank you! :)
