### ISSUE TITLE
How to unlock W10 PC remotely ?

### ISSUE THREAD

**Issue by Ayting69** [moonlight-stream/moonlight-qt#702]
Hello

I have an issue : 

If i want to start or restart my pc remotely when i'm not at home, i can do it with unified remote which have a wake on lan feature. It's especially practical when my screen stuck on moonlight. 

Before i had set no password on my W10 host, so i was able to restart it without any problem

But i've putted a password for more security, and i can no longer do that. I need to use my physical keyboard to unlock my pc.

Did you had find a workaround to enter your password on a cold boot ? 

Thanks in advance.

**Comment by vhd** [comment]
I use TeamViewer solely for this purpose, but maybe there is another way

**Comment by Ayting69** [comment]
Thanks, i'm using anydesk, i've installed it and i'm able to unlock my pc with it even in coldboot

**Comment by apoklyps3** [comment]
teamviewer should do the trick if you enable windows logon in the settings
