### ISSUE TITLE
Issues Compiling on macOS arm64

### ISSUE THREAD

**Issue by FelixKratz** [moonlight-stream/moonlight-qt#711]
**Describe the bug**
I am having problems compiling the source code on macOS 12.1 with an arm64 chip. I have installed all dependencies, but run into a linker problem:
```bash
ld: warning: ignoring file /opt/homebrew/lib/QtQuickControls2.framework/QtQuickControls2, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtQuick.framework/QtQuick, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtOpenGL.framework/QtOpenGL, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtSvg.framework/QtSvg, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtWidgets.framework/QtWidgets, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtGui.framework/QtGui, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtQmlModels.framework/QtQmlModels, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtCore.framework/QtCore, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtQml.framework/QtQml, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtNetwork.framework/QtNetwork, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```
This is probably because the build is trying to create a universal binary and I only have the arm64 binaries of qt installed via brew.

I installed qt via `brew install qt`, so nothing special there.

I then tried to change the `generate-dmg.sh` script to include only arm64: `QMAKE_APPLE_DEVICE_ARCHS="arm64"` but this also leads to an error:
```bash
ERROR: Could not parse otool output line: "/Users/felix/moonlight-qt/build/build-Release/app/Moonlight.app/Contents/Frameworks/libavutil.56.dylib (architecture arm64):"
ERROR: Could not parse otool output line: "/Users/felix/moonlight-qt/build/build-Release/app/Moonlight.app/Contents/Frameworks/libavcodec.58.dylib (architecture arm64):"
```

Any help will be appreciated greatly.

PS: Thank you for this great piece of software!

**Comment by cgutman** [comment]
What step of the build are those "Could not parse otool output line" errors coming from?

**Comment by FelixKratz** [comment]
I tried doing the same on an x86_64 machine:
```bash
ld: warning: ignoring file /usr/local/lib/QtQuick.framework/QtQuick, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtQuickControls2.framework/QtQuickControls2, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtSvg.framework/QtSvg, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtOpenGL.framework/QtOpenGL, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtWidgets.framework/QtWidgets, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtGui.framework/QtGui, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtQmlModels.framework/QtQmlModels, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtQml.framework/QtQml, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtNetwork.framework/QtNetwork, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/QtCore.framework/QtCore, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```
same errors as for arm64 but with switched roles, but now if I  change the `QMAKE_APPLE_DEVICE_ARCHS` to only include x86_64 it compiles just fine and there is no otool error. I can run the app just fine after doing this on x86_64, leading me to believe that the otool error is the main problem on arm64.

**Comment by cgutman** [comment]
I suspect the Homebrew build of Qt is built differently than the official ones from Qt.io that I use and that's what causes all those `rpath` errors. In particular, [this line](https://github.com/Homebrew/homebrew-core/blob/5130bfe526e1a959c0ba889785b17d1da5da238d/Formula/qt.rb#L135) looks suspect. I don't know if the binary you make will actually run on other systems. It might be loading the Qt libraries from `/usr/local/lib` rather than the app bundle itself.

Unfortunately, I have no clue about the `otool` error. All I can suggest is that you use the official Qt installer from qt.io.

**Comment by vhd** [comment]
Did you try to compile it manually, without the scripts provided in `scripts` folder?
For me the brew version of qt works fine on both M1 and Intel macs
```
brew install qt
git clone ...
cd moonlight-qt
git submodule update --init --recursive
qmake moonlight-qt.pro
make release
```
Until I try `generate-dmg.sh` since it doesn't work, at least with brew version of qt.
Though I can't remember the exact issues since it was a while ago

**Comment by FelixKratz** [comment]
> Did you try to compile it manually, without the scripts provided in `scripts` folder? For me the brew version of qt works fine on both M1 and Intel macs
> 
> ```
> brew install qt
> git clone ...
> cd moonlight-qt
> git submodule update --init --recursive
> qmake moonlight-qt.pro
> make release
> ```
> 
> Until I try `generate-dmg.sh` since it doesn't work, at least with brew version of qt. Though I can't remember the exact issues since it was a while ago

This is indeed working, thank you so much!

I would propose that this is reflected in the build step documentation for brew qt installs.
