### ISSUE TITLE
I can't use the Switch Joycon handle.

### ISSUE THREAD

**Issue by Kevin-1117** [moonlight-stream/moonlight-qt#716]
Hello everyone,
I currently encounter a problem when using Moonlight: I can't use the Switch Joycon handle.
The Joycon can be recognized by the Bluetooth connection on the computer, which are respectively Joycon (L)/(R), but on the game PC, it is recognized as the Xbox 360 Controller 0/1. There is no response to pressing the buttons of the controller.
After testing, it was found that the Switch Pro handle can be used normally, and it is also recognized as an Xbox 360 Controller.
The game PC system is windows11.
The client system is windows 11.
The game is Yuzu (Nintendo Switch Emulator).

**Comment by Cousken** [comment]
I have more or less the same issue, but more specifically - the "DPad" buttons don't work as a DPAD. When testing them via Gamepad Tester on my android, the input is received but simply isn't mapped to the DPAD function. Is there some way to solve this?

**Comment by cgutman** [comment]
Unfortunately, this is an [upstream issue with SDL](https://github.com/libsdl-org/SDL/issues/3518). Moonlight will gain support for it when SDL implements it.

**Comment by slouken** [comment]
FYI, Joy-Con support is implemented in SDL 2.24.0

**Comment by happyharryh** [comment]
FYI, I have built a [branch](https://github.com/happyharryh/moonlight-qt/tree/dev) of moonlight-qt with a CemuHook server embedded recently. So that we can send accel and gyro data to the yuzu on the host PC, and play the games which require motion sensor (e.g. Just Dance, Splatoon) remotely~ :p

**Comment by Infi-zc** [comment]
> FYI, I have built a [branch](https://github.com/happyharryh/moonlight-qt/tree/cemuhook-server) of moonlight-qt with a CemuHook server embedded recently. So that we can send accel and gyro data to the yuzu on the game PC, and play the games which require motion sensor (e.g. Just Dance, Splatoon) remotely~ :p

thanks a lot! If you have the time and it's not too much trouble, could you possibly cherry-pick this change into the latest release branch? It would be greatly appreciated!
