### ISSUE TITLE
Moonlight HDR not working macbook pro monterey 12.1

### ISSUE THREAD

**Issue by nonamebran** [moonlight-stream/moonlight-qt#718]
When HEVC HDR is enabled, even games that support HDR give a warning that the game does not support HDR. I'm not sure if I am doing something wrong or if it is limited in support as of now. I know it is experimental but any help would be appreciated. Thanks

**Comment by cgutman** [comment]
GeForce Experience doesn't mark custom added games as HDR compatible. You can use a workaround like this to allow custom added games to use HDR: https://github.com/lyckantropen/moonlight_hdr_launcher

**Comment by nonamebran** [comment]
Thank you that worked perfectly!!
