### ISSUE TITLE
3.2.0 using a lot of CPU on Big Sur on Early 2015 13" MacBook Pro

### ISSUE THREAD

**Issue by TamboTan** [moonlight-stream/moonlight-qt#722]
Hi there

I upgraded to 3.2.0 and noticed that my fan was running constantly within a couple of minutes of starting a Moonlight session. If I downgrade to 3.1.4 it goes back to how it has always been before, basically silent.

I changed it to borderless window and looked at Activity Monitor and can see that Moonlight is constantly sat at 30%+ CPU. Dragged 3.2.0 to the Trash and reinstalled 3.1.4 and back to how it has always beeen before, smooth and silent (it is why I use Moonlight as if I run any games locally to the Mac it struggles unsurprisingly). 

The PC is running the latest Nvidia driver for a 970 (511.23) and the latest GeForce Experience (3.24.0.126) although probably not related because it is so easy to recreate, install 3.2.0 constant loud fan from the MacBook, install 3.1.4 again and silent. I'm on latest available for Big Sur on the Mac side. 

I run 1680x1050 in Moonlight (a native res) and 60fps bandwdith set at 40Mbps, that has't ever been a issue before so hopefully OK. I have the desktop set to the same res on the server and also in game (Hearthstone in this case but it does it at desktop anyway so not game related).

Happy to do any testing required, I'm a systems engineer so familiar with testing protocols.

Thanks

Ollie

**Comment by cgutman** [comment]
I have a suspicion as to which change caused this.

Please try these 2 builds and let me know if one or both show the high CPU usage issue:
- https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/42215360/job/foiu4108u0biod33/artifacts
- https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/42216021/job/mpt7pme3pui6j9ir/artifacts

**Comment by TamboTan** [comment]
Hopefully it is what you were expecting but 1623 (the first link) didn't spin up my fan but 1625 (the second) did pretty much straightaway.

Thanks for the quick response!

**Comment by cgutman** [comment]
ok, that's what I'd hoped. Can you try this build too? https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/42294765/job/wm04c9th36cr3ttj/artifacts

**Comment by TamboTan** [comment]
Hi again sorry for the delay but only just used Moonlight again. Just to confirm that r1647 is fine as well, no fan while I'm using it so presume CPU usage is back to normal. 

Out of interest, what was the issue? Something not hardware accelerated in that vintage hardware? I realise it isn't the most up to date of hardware but one of the reasons I use Moonlight on my old Macbook is because I get a reasonablly decent resolution and screen quality but without constant fan noise and heavy battery drain.

Thanks again :) Not just for this but the entire project, an amazing bit of work! The dev(s) on this project do amazing work and it is very much appreciated. So much better for me than Steam Remote Play. It is like the difference between something I can put up with (Steam RP) vs something that is really nice to use and "just works". I went from hardly ever using my Steamlink device to it being an essential bit of kit and also my Macbook becomes a gaming device as well.

**Comment by cgutman** [comment]
The cause was this change b9a6fb1fe59b565b411a56e893e62b1fff74e673 to workaround an issue on macOS.

@vhd It looks like we'll need to revert this and try a different workaround. Can you test these builds and see if they solve your color issues?
- https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/42300726/job/xgev7ys9h8q6gokv/artifacts
- https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/42294765/job/wm04c9th36cr3ttj/artifacts

**Comment by vhd** [comment]
The first one (r1653) don't has the issue, but it looks a bit oversaturated, just like with SDL renderer. But I think it's perfectly fine, at least that's how Windows looks on Macbook screen.
The second one (r1653) has color issues, just like before.

**Comment by cgutman** [comment]
@vhd Sorry, I actually made a mistake in that first build. I forgot to revert the rasterization workaround.

Can you try this one? https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/42301011/job/yvcc6hrn2es95q1w/artifacts

**Comment by vhd** [comment]
Whoa!
Now it's oversaturated like SDL version **_and_** has color-bleeding issue like before on my M1.
This combo I see for the first time :)
Maybe it's just easier to revert that "fix", since I'm the only one who noticed the issues?

**Comment by cgutman** [comment]
This fix is released in v4.0.0, so closing this.
