### ISSUE TITLE
Moonlight black screen when displayed on amd connected monitor

### ISSUE THREAD

**Issue by jeffery30162** [moonlight-stream/moonlight-qt#725]
Host: 
     5600x
     1080ti
     Windows 10
     Latest nvidia driver
Client
    5950x
    6900xt
    1080ti
    Windows 10
    Latest nvidia and amd driver

I have several monitors connected to both the 1080ti as well as the 6900xt, If the moonlight in windowed mode is on a monitor connected to the 1080ti it works fine. If the window is moved to a monitor connected to the 6900xt. stream goes black.

What is the solution?

**Comment by cgutman** [comment]
I saw this behavior back when I ran an AMD+Nvidia test machine. IIRC it deadlocks inside the AMD driver, so nothing we can do from our side.

**Comment by cgutman** [comment]
Closing as can't fix (bug in AMD's driver).
