### ISSUE TITLE
Performance Infos

### ISSUE THREAD

**Issue by PatiB87** [moonlight-stream/moonlight-qt#73]
I would like to be able to see the input- and video latency (separately!), actual data rate, frame rate, etc. etc.
Steam is able to display similar info.

**Comment by cgutman** [comment]
GameStream doesn't offer the full set of latency numbers that Steam does. Notably, we can't track network latency (as far as we've determined from the protocol).

For the statistics on video performance (FPS, presentation latency), I recommend (and use) PresentMon. https://github.com/GameTechDev/PresentMon/releases

**Comment by cgutman** [comment]
This is implemented in v0.9.0
