### ISSUE TITLE
Bug with pointer capture mode [MacOS]

### ISSUE THREAD

**Issue by Xpymb** [moonlight-stream/moonlight-qt#730]
Pointer capture mode ignores system mouse settings (uses mouse acceleration all time). But Desktop capture mode uses system mouse settings. 

Please fix it, because it is uncomfortable, or add advanced mouse settings in Moonlight App. 

**Client PC details**
 - OS: macOS Monterey 12.1
 - Moonlight Version: v3.2.0
 - GPU: Apple M1
 - Mouse type: USB Mouse
 - System mouse acceleration: -1

**Server PC details**
 - OS: Windows 11 21H2
 - GeForce Experience version: 3.25.0.83
 - Nvidia GPU driver: 511.23
 - Antivirus and firewall software: Windows Defender

**Comment by cgutman** [comment]
Unfortunately, the mouse acceleration adjustments are not something we control. See https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-does-my-hosts-mouse-acceleration-change-while-streaming

**Comment by Debuggernaut** [comment]
@Xpymb hey buddy, I ran into the same issue on my setup.  I was trying to game on my MacBook while keeping the space heater\* in another room, and despite having mouse scaling disabled in MacOS via:

> $ defaults read GlobalPreferences com.apple.mouse.scaling
> -1
> 

(Note that MacOS silently turns this back on any time you open the mouse settings page and mess with the sensitivity, and I think you have to relog to pick up the updated setting)

I was getting obnoxious mouse acceleration on the target device.  I guess the Moonlight devs were just as consterned as I was to find that GeForce Experience turns on pointer acceleration with no way to turn it off.  I was playing World of Warcraft with Moonlight too, and so far as I know WoW doesn't have an option to get raw mouse input.

**I found a nice workaround, though**:  Once you load up WoW (or probably any game) on your gaming PC, OPT-TAB (which sends ALT-TAB to the host PC) and just go into the Mouse control panel and uncheck "Enhance Pointer Precision".  (Note: If you leave that dialog open, it doesn't update when GeForce Experience messes with the settings, so you might have to change a setting and then change it back, then click apply).  This seems to disable GeForce Experience's pointer acceleration.

\* Windows 10 gaming PC

**Comment by sheldonl3** [comment]
> 
It’s right, I used this method to get the desired mouse effect on my MAC . Hope moonlight can use this method to make automatic configuration options
