### ISSUE TITLE
Need Help! Stream constantly disconnects

### ISSUE THREAD

**Issue by MoonSkR** [moonlight-stream/moonlight-qt#732]
ISSUE DESCRIPTION:
I am streaming from my bedroom gaming PC(wired connection) to living room 2021 M1 iMac(latest OS via mesh WiFi6). The strange thing that happens is that after a period of time(5-30mins), my mouse& keyboard suddenly stops working, cursor is still movable but can't click or press button anymore. However, video stream is **still smooth and running**. Then, after several seconds, the stream breaks and says "connection terminated". The PC icon gets a ! mark and can't connect anymore. I have to reboot my gaming pc to be able to restart the above circulation again.

I've tried updating GeForce Experience/ Drivers/ Moonlight Client, or reinstall the Windows 10 on my PC, but can't solve the problem. 
Thanks for attention and help
[Moonlight-1644159561.log](https://github.com/moonlight-stream/moonlight-qt/files/8013164/Moonlight-1644159561.log)
[Moonlight-1644199228.log](https://github.com/moonlight-stream/moonlight-qt/files/8013165/Moonlight-1644199228.log)
!

**Comment by MoonSkR** [comment]
update: I suspect it has something to do with my mesh network( 2 Asus AX6600 routers), when I stream from the same router in my bedroom with my MacBook everything seems fine. I have tried altering settings in mesh setting but can't find a solution.

**Comment by MoonSkR** [comment]
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/8087395/NvStreamerCurrent.log)


> I don't see anything relevant in Moonlight's logs. I'm not seeing typical signs of network issues prior to disconnect either.
> 
> ```
> 01:21:31 - SDL Info (0): Server notified termination reason: 0x80040004
> ```
> 
> It appears that the disconnect was initiated by the host, either due to NvStreamer crashing or encountering some error. Your best bet is to look in the NvStream logs in `C:\ProgramData\NVIDIA Corporation\NvStream`.

Attached mentioned file, please help

**Comment by cgutman** [comment]
It's strange. The connection goes from totally fine to completely gone.

In the cases I've seen this before, the network traffic load from GameStream actually crashes the access point, causing connectivity to drop. Ironically, it was also an Asus branded AP which had the issue before.

I'd suggest looking for a firmware update for your routers. If that doesn't work, try messing with QoS settings on your router to see if that could be the cause.

**Comment by MoonSkR** [comment]
> It's strange. The connection goes from totally fine to completely gone.
> 
> In the cases I've seen this before, the network traffic load from GameStream actually crashes the access point, causing connectivity to drop. Ironically, it was also an Asus branded AP which had the issue before.
> 
> I'd suggest looking for a firmware update for your routers. If that doesn't work, try messing with QoS settings on your router to see if that could be the cause.

The firmware of routers have been updated several times >.<
Any suggestions on the QoS settings?

**Comment by MoonSkR** [comment]
I completely turned QoS off, doesn't help

**Comment by cgutman** [comment]
I can't really provide any further suggestions. There's nothing Moonlight can do if your network is dropping all of its traffic.

It seems to clearly be related to your mesh router setup per https://github.com/moonlight-stream/moonlight-qt/issues/732#issuecomment-1033482414, so I would suggest contacting Asus for further support. They may be able to have you collect router logs during the issue to troubleshoot further.
