### ISSUE TITLE
is possible close current session once game quit ?

### ISSUE THREAD

**Issue by chopin1998** [moonlight-stream/moonlight-qt#735]
Hi, Moonlight is really c00l.

One problem, when i leave a game, moonlight still show the desktop of remove computer.  is that possible close current session after game exit?

Thank you!

**Comment by Dukobpa3** [comment]
Hi

The same question but in case this game is My Own ))

How can I proper say to GameStream that my app closed?
Or maybe implement some manual stream closing from my side?
Something like button "Exit app and close stream"

**Comment by giorgiobrit** [comment]
hi the same request for me! On my Sony TV android i have the same problem.
