### ISSUE TITLE
Stream lag stutters every ~6 min over 5GHz WiFi with an Intel WiFi card -> Found a fix for that

### ISSUE THREAD

**Issue by ottelo9** [moonlight-stream/moonlight-qt#739]
I tried to contact a developer on discord but without luck so far :(. So I try to reach someone how can edit the Wiki troubleshooting page with this "bug report".

I had a problem with Moonlight on my Intel NUC pc running over 5GHz WiFi. A Intel WiFi card is installed. My host is a notebook hardwired (LAN). The WiFi connection was very good and stable (~400mbits) every time I played. But every ~6 minutes the game lags/hangs for few seconds including a slow connection warning. After this the stream continuous very well. I tried everything and I found the solution:

Inside the network adapter settings of my intel wifi card I found a option:
**Global BG scan blocking**
This option was set to = "Never (default): Will perform periodic scans for other available APs."

I set this to "Always: Will not perform periodic scans for other available APs." and the problem was gone!!!

**Please add this important information to your wiki:**

https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

**Comment by cgutman** [comment]
Added, thanks!

**Comment by chu-bin** [comment]
I'm using a newer intel NIC ax211 with pre-installed 23.x drivers and I found out that intel removed the option Global BG scan blocking in 22.150.x and later because they thought the optimized Global BG scan would not have an impact on the network, which is not the case. I'm still experiencing 3-4s of network lag every 10 minutes. 

I'm currently using windows 11's 5Ghz hotspot to provide network to android devices. Any ideas on how to fix the problem with the new intel drivers where the network card cuts off the stream every ten minutes？

**Comment by cstovi** [comment]
I found this issue and fixed with stopping bg scanning years ago but now with a new laptop have found intel wifi can't be downgraded and the option no longer exists. Has anyone got a fix so I don't have to have a different wifi usb adaptor hanging out of the side all the time?

**Comment by felipejfc** [comment]
I created a decky-loader plugin to make the process of locking/unlocking easier:
https://github.com/felipejfc/decky-wifi-locker
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/792

**Comment by TheOneOgre** [comment]
For anyone that finds this issue later, this is a VERY known issue with newer intel drivers. I myself was suffering with an AX210, and then switched to a BE200 which had the exact same problem. 

There is a maintainer of a[ modded set of intel drivers](https://www.techpowerup.com/forums/threads/intel-ax1xx-ax2xx-ax4xx-ax16xx-be2xx-be17xx-intel-modded-wi-fi-driver-with-intel%C2%AE-killer%E2%84%A2-features.326229/) that re-add the BG blocking and other driver settings, and this completely resolves the stutter issue, however seems to break Modern S0 sleep. A trade off of course, but if you want good performance, this is where to look
