### ISSUE TITLE
Two Mice on Screen?

### ISSUE THREAD

**Issue by nothingisrealffs** [moonlight-stream/moonlight-qt#741]
![Screenshot 2022-02-25 082853](https://user-images.githubusercontent.com/88836848/155724725-33fadac1-4b0b-4246-a339-747aa9518d10.png)
Not a problem. This happens on every device i connect with to this computer. Don't have a second to test to see if it happens all of the time, but i imagine that its something specific with my personal setup, since i have yet to see someone else complain or such about this. When i connect to the game computer, i have two cursors for whatever reason. The top left one does nothing. It changes with the bottom right one, so when you do anything that changes the cursor with the "primary" one, the "background" one changes, but if you try to do the same with the "backup", nothing happens.
Host specs:
i7-8700k - Windows 11, latest updates
NZXT Z370 MB
GTX 1650 -Latest Driver

i think its either:
A: a side effect of the GPU being connected via DVI cable, don't have a spare HDMI atm to test (also the computer is in a wall and i'm trying hard not to de-wire everything IF POSSIBLE. No problem with it just don't have spare time and thats on me).
B: Much less likely, but the boundaries of where the mouse changes based on what resolution i've got it set at in the host, so i imagined that it has something to do with bandwidth settings of some sort, that all the data you get fills a box X size and then is expanded based on the bitrate you've set. I've noticed no big changes but it could be possible.

Been a longtime user of this, over the last like 4 computers. Love the program. Haven't seen this before. So its probably a config setting but i'm hoping to narrow down what if anyone has thoughts.

**Comment by cgutman** [comment]
That's really peculiar. I don't think I've seen it before either.

If you unplug your physical mouse from the host PC, does anything change?

**Comment by MightyAx** [comment]
I had this issue recently and realised it was a discrepancy between **Desktop Resolution** and **Active Signal Resolution**, which you can check in Windows: _Settings>System>Display>Advanced display settings_

I fixed it by using the NDIVIA control panel to change the resolution to match what Moonlight was expecting.

**Comment by cgutman** [comment]
Thanks for the solution @MightyAx

**Comment by Juansero29** [comment]
Hello again  @MightyAx and @cgutman, I am having the problem of the double mouse with Moonlight on a Mac and Sunshine on a Windows 11 computer. Even when setting the same resolution (1920x1080p@60hz) on both the client and the server, I stil keep the double mouse issue for some reason. Are there any workarounds or things I should check?

**Comment by starhound** [comment]
This occurs for me on latest build when using a mirrored screen where once is a virtual display at different FPS. 

My remote system is connected to a TV at 60fps, 1080p

And I have a virtual display at 144fps. Same resolutions.

**Comment by evertonstz** [comment]
> This occurs for me on latest build when using a mirrored screen where one is a virtual display at different FPS.
> 
> My remote system is connected to a TV at 60fps, 1080p
> 
> And I have a virtual display at 144fps. Same resolutions.

I was having this same issue and this seems to be the reason. I switched to [this solution](https://github.com/Cynary/sunshine-virtual-monitor/tree/main) and the double pointer is gone.

**Comment by shodanx2** [comment]
I also had this issue on a windows 10 sunshine server with an old amd firepro gpu.

This was resolved by wiping the ssd and reinstalling the operating system from blank.

This might be due to when the CPU encoding fallback is activated.
