### ISSUE TITLE
Latest version produces 2 controllers with 1 connected 

### ISSUE THREAD

**Issue by bigmacxman** [moonlight-stream/moonlight-qt#742]
**READ ME FIRST!**
If you're here because something basic is not working (like gamepad input, video, or similar), it's probably something specific to your setup, so make sure you've gone through the Troubleshooting Guide first: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

If you still have trouble with basic functionality after following the guide, join our Discord server where there are many other volunteers who can help (or direct you back here if it looks like a Moonlight bug after all). https://moonlight-stream.org/discord

**Describe the bug**
In the latest version of moonlight, 2 controller are detected rather than 1. Windows 10 client. Xbox 360 wireless receiver. This receiver is NOT the official Microsoft one(HDE). Rolling back to last version off moonlight fixes issue. 

**Steps to reproduce**
Happens every time. Noticeable in games that accept 2 controllers like “it takes two”

**Screenshots**

**Affected games**
it takes two

**Other Moonlight clients**

it does not happen in the latest version with steam link client

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- Yes
- If so, which settings have been changed?
- Bandwidth and resolution
- Does the problem still occur after reverting settings back to default?
Yes
**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
- No
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
- Did not try
  - Instructions for streaming the desktop can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - Moonlight Version: [e.g. v0.9.0]
 - GPU: [e.g. Intel HD Graphics 520]
 - Intel had graphics 500

**Server PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - GeForce Experience version: [e.g. 3.16.0.140]
 - Nvidia GPU driver: [e.g. 417.35]
 - Antivirus and firewall software: [e.g. Windows Defender and Windows Firewall]

**Moonlight Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux with the Flatpak, logs print to the terminal when running with the command: `flatpak run com.moonlight_stream.Moonlight`
- On Linux with the Snap, logs print to the terminal when running with the command: `moonlight`

**Additional context**
Anything else you think may be relevant to the issue

**Comment by bigmacxman** [comment]
This is not an issue with previous version.  I rolled back and there were no double controller issues

**Comment by bigmacxman** [comment]
Windows 10 client

**Comment by cgutman** [comment]
Please edit the original message to add the details that the template is asking for. Please also attach the Moonlight logs and provide information on the specific model of controller that is being detected twice.

**Comment by bigmacxman** [comment]
Info was updated

**Comment by cgutman** [comment]
@bigmacxman Please try replacing the SDL2.dll in your Moonlight installation with this version and let me know if it resolves the issue for you.

https://drive.google.com/file/d/1VIzYU-lQmbFE1VKvt378ctdHlE_iB7ai/view?usp=sharing

**Comment by SuperLeiyan** [comment]
Same issue with the android version of moonlight

**Comment by cgutman** [comment]
@SuperLeiyan The Android version is a completely different codebase that wouldn’t be affected by this SDL bug (as it doesn’t use SDL at all)

Please file a ticket on the Android project, including details about the controllers you have connected to your host and client, the game you’re testing, and anything else that seems relevant.

https://github.com/moonlight-stream/moonlight-android/issues

**Comment by cgutman** [comment]
Fixed by 73d84dc13f9ea85a277be63dd917917b7d374195
