### ISSUE TITLE
moonlight several mice on the screen

### ISSUE THREAD

**Issue by jefersonj70112** [moonlight-stream/moonlight-qt#743]
moonlight I installed a short time ago and I have this problem I don't know what it could be if any and I had a solution (using google translator)
![WhatsApp Image 2022-02-28 at 12 32 33](https://user-images.githubusercontent.com/100600153/156011734-8701cd52-3326-42ca-ab2b-36a4693f9deb.jpeg)
[

**Comment by cgutman** [comment]
Looks like severe packet loss to me. It also looks like you're running a very old version of GeForce Experience, which may be related to your issues.

Please try a newer version of GeForce Experience or a more stable connection.
