### ISSUE TITLE
Still have the issue with the video getting stuck after downgrading my drivers to 472.12.

### ISSUE THREAD

**Issue by ericsyj** [moonlight-stream/moonlight-qt#744]
I still have the issue with the video getting stuck when watching some live video streams at the specific resolution of the host ( e.g. 2560\*1440, 1920\*1080, etc. ) after downgrading my driver to 472.12 or drivers of other versions, but it works normally at some resolutions ( e.g. 1920\*1440, 1920\*1200, etc. ) in any driver I've tried, and I don't know if it's because my card ( gtx670 ) is too old.

**Comment by ericsyj** [comment]
The same situation happened on my legion r9000p （rtx3060）.

**Comment by vetuaat** [comment]
In gaming I had the same problem, disabling the Hardware-Accelerated GPU Scheduling in Windows settings worked for me

**Comment by cgutman** [comment]
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/27
