### ISSUE TITLE
Problem on Lenovo légion 5 with rtx 3060

### ISSUE THREAD

**Issue by nattyduber** [moonlight-stream/moonlight-qt#749]
Hi

Before i used Moonlight streaming on a desktop with i7 6700+gtx1080 and all work fine
Now im on a desktop Lenovo légion 5 with ryzen 5 and rtx 3060
And i have paired m'y laptop on Android TV or m'y phone
Internet hosting tool Saïd that all are ok

But when i want to connect to m'y pc .. rtsp etc load but i have directly a message like you Can see hère..
![Screenshot_20220316-210234_Moonlight](https://user-images.githubusercontent.com/66644184/158687440-16798ec2-3529-4dc3-8ef0-f92c4da6e4f8.jpg)

Why?

Thanks

**Comment by nattyduber** [comment]
Any reply?

**Comment by nattyduber** [comment]
UP?

**Comment by cgutman** [comment]
This looks like Android. This bug tracker is for the PC client.

Please file an issue on https://github.com/moonlight-stream/moonlight-android if this still affects you.
