### ISSUE TITLE
Moonlight works on mobile-data and other connections but not on school network

### ISSUE THREAD

**Issue by Denniscocacola** [moonlight-stream/moonlight-qt#75]
I can connect to with moonlight using mobile-data but i cant while using wifi on school(5G 4 ping 150mbps up/down)
 I tried creating a vpn on my pc and connecting to it with my laptop on school and it connects just fine(speedtest result 5 ping 100 up/down)  i have internet acces to my home and my pc show up in moonlight but when i connect it gives error -1.
is there a thing i have to change in my vpn settings or is it a moonlight problem?

**Comment by Sloanstar** [comment]
This might be network configuration / DNS related. I'll try and help out
here. Normal discovery is via mDNS, which works well when you are on the
same network  broadcast domain and your IP doesnt change. When you start
trying to VPN or connect over the internet you are going to need well
defined name spaces for resolution.

Over VPN you would need to use your local name server that would be
authoritative for your home network, let's say dennis.home

You would add your gamepc to moonlight using the fully qualified domain
name, say gamepc.dennis.home this should allow you to connect over vpn even
when your game pc changes IP addresses.

Inherently VPN has overhead so if you find yourself with some performance
problems you may want to look at port forwarding and connecting over the
internet natively if possible, your school network might be blocking the
requisite ports though. And you'll likely want to look into a public
namespace provider for dynamic IPs such as dyndns or noip.

Let me know if you you need more help.

**Comment by dennis-8844** [comment]
is there a possible way to change the nvidia gamestream ports? so i can connect at school wich probably blocked some of those ports?

**Comment by Sloanstar** [comment]
Since you're connecting to the GeForce Experience (GameStream) Service this
is really an NVidia question on the connection side, a lightweight google
search didn't turn up anything promising. You can try opening a case w/
nvidia to see if the ports are customizable.
I guess if you were able to change the ports in the client you could do
custom port forwards with port translation on your router, but the ranges
of ports required and increased complexity of the design would make it a
support nightmare, imho.

**Comment by ReindeerG** [comment]
if you have a router(DLINK product, etc, ...) which have the function PORTFOWARDING, you could customize outter port.

**Comment by cgutman** [comment]
For these sorts of connectivity troubleshooting, our [Discord server](https://discord.gg/MySTSdq) is more suitable than a GitHub issue. We can probably help you find a solution there.
