### ISSUE TITLE
Heavy periodic stutters when using Linux but not on windows 

### ISSUE THREAD

**Issue by aacebedo** [moonlight-stream/moonlight-qt#752]
**Describe the bug**
I am using a surface pro 7+ with dualboot Windows/linux to stream games from a gaming rig running GFE on windows 11.
I have Wifi 6 APs and tested my connection with iperf3 (I achieve connection speeds from 700Mbps to 900Mbps on the wirless connection from the surface to the gaming rig).
When using moonlight on the surface running an archlinux derivative with the wifi connection I notice periodic frame drops due to the network (given by the client statistic layer) causing huge stuttering which make some games not playable at all.
If I reboot the exact same machine on windows and connect to the wifi the same way, the frame drops are not present anymore.

When trying through a wired connection everything is ok on both windows and linux.

**Steps to reproduce**
- Stream the same game from the same gaming with the same wifi connection but with Linux and Windows 

**Moonlight settings (please complete the following information)**
40 Mbps bitrate on a 1080 stream.

**Client PC details (please complete the following information)**
 - OS:  Windows 11 and linux EndeavourOS
 - Moonlight Version: 3.2.0
 - GPU: Iris Xe graphics (tiger lake)
 
**Server PC details (please complete the following information)**
 - OS: Windows 11
 - GeForce Experience version: 3.25
 - Nvidia GPU driver: 511.79
 - Antivirus and firewall software:  Windows Defender and Windows Firewall

**Comment by cgutman** [comment]
I have seen this too.

In my case, it was due to the WiFi scanning behavior of things running in the background (like the GNOME weather widget) calling GeoClue (location services daemon) asking for the location. An easy way to reproduce it was to start streaming in a window, open GNOME's WiFi network list. This triggers an immediate scan and causes the stream to stutter or drop frames.

You can try turning off location services, or look at the GeoClue logs to figure out which D-Bus client keeps asking for the location.

**Comment by cgutman** [comment]
Closing, no response from OP.

**Comment by aacebedo** [comment]
Seems like the proposed solution worked. I was keeping gnome settings in the background. I need further tests to confirm though. Thank you.

**Comment by sHedC** [comment]
Hi,

I have had this with periodic high pings, in the end it seems to be the background scanning in the NetworkManager, I could simulate it by manually scanning.  Removing running apps helped but didn't stop it.

It wasn't my server as my XBOX didn't have the same issue wired or wireless.  I have multiple AP's so have to capture the one I am connected to.

In the end I set the BSSID I was connected to and restarted the wifi before starting moonlight seems to have fixed it and automated it from bash.  Once you set the BSSID you have to disconnect and reconnect so it takes effect which means I could immediately reset the BSSID.

# Get the connected wifi Card Details and connected SSID/ BSSID
WIFI_CARD=$(nmcli dev status | grep wifi | grep -v disconnected | head -n1 | cut -d " " -f1)
LINK_INFO=$(iw dev $WIFI_CARD link)
BSSID=$(echo $LINK_INFO | grep -o -P '(?<=Connected to ).*(?= \(on)' | tr '[:lower:]' '[:upper:]') 
SSID=$(echo $LINK_INFO | grep -o -P '(?<=SSID: ).*(?= freq)')

# Lock Wifi to the BSSID to stop background scanning.
nmcli con mod $SSID 802-11-wireless.bssid $BSSID
nmcli dev dis $WIFI_CARD
nmcli dev con $WIFI_CARD
nmcli con mod $SSID 802-11-wireless.bssid ''

Have been running for over an hour no issues even with background apps working, checking ping from command line:
ping <IP> | while read pong; do echo "$(date): $pong" | grep -v "time=[0-9]\."; done

Pings over 20 seemed to cause the stutter.
I also disabled power management but might re-set that and try again.

**Comment by Michael-Yongshi** [comment]
> Hi,
> 
> I have had this with periodic high pings, in the end it seems to be the background scanning in the NetworkManager, I could simulate it by manually scanning. Removing running apps helped but didn't stop it.
> 
> It wasn't my server as my XBOX didn't have the same issue wired or wireless. I have multiple AP's so have to capture the one I am connected to.
> 
> In the end I set the BSSID I was connected to and restarted the wifi before starting moonlight seems to have fixed it and automated it from bash. Once you set the BSSID you have to disconnect and reconnect so it takes effect which means I could immediately reset the BSSID.
> 
> ```
> # Get the connected wifi Card Details and connected SSID/ BSSID
> WIFI_CARD=$(nmcli dev status | grep wifi | grep -v disconnected | head -n1 | cut -d " " -f1)
> LINK_INFO=$(iw dev $WIFI_CARD link)
> BSSID=$(echo $LINK_INFO | grep -o -P '(?<=Connected to ).*(?= \(on)' | tr '[:lower:]' '[:upper:]') 
> SSID=$(echo $LINK_INFO | grep -o -P '(?<=SSID: ).*(?= freq)')
> 
> # Lock Wifi to the BSSID to stop background scanning.
> nmcli con mod $SSID 802-11-wireless.bssid $BSSID
> nmcli dev dis $WIFI_CARD
> nmcli dev con $WIFI_CARD
> nmcli con mod $SSID 802-11-wireless.bssid ''
> ```
> 
> Have been running for over an hour no issues even with background apps working, checking ping from command line: ping | while read pong; do echo "$(date): $pong" | grep -v "time=[0-9]."; done
> 
> Pings over 20 seemed to cause the stutter. I also disabled power management but might re-set that and try again.

Maybe a good tip to enclose $SSID in double quotes to handle SSID's with spaces in them. 
Otherwise it will only capture the first word of the SSID. I just encountered it myself.

Like:
nmcli con mod "$SSID" 802....

**Comment by felipejfc** [comment]
I created a decky-loader plugin to make the process of locking/unlocking easier:
https://github.com/felipejfc/decky-wifi-locker
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/792

**Comment by ruanformigoni** [comment]
For me, the solution was also setting up the BSSID, but I just had to select it in the plasma GUI from a dropdown menu, disconnect, and connect again. So this might be useful if you're in this desktop environment:

![Image](https://github.com/user-attachments/assets/a41fd6b9-7135-43b8-9730-4ff5ac67ac86)
