### ISSUE TITLE
Can't add more than one PC

### ISSUE THREAD

**Issue by BlueSialia** [moonlight-stream/moonlight-qt#756]
**Describe the bug**
If I try to manually add a second PC to Moonlight it will replace the one that is already in the application. It keeps the name of the old one.

**Steps to reproduce**
1. Have a PC added as "Computer 1" for example to the IP 192.168.0.10.
2. Manually add another computer with the IP 192.168.0.20.

The result is that the PC named "Computer 1" is now pointing to 192.168.0.20. It is still named "Computer 1" and it has the lock icon because it requires you to put the code to allow the connection.

**Other Moonlight clients**
I cannot test other clients. I'm sorry.

**Moonlight settings**
I've tried to use the automatic detection of PCs as well. It detects just one PC. It is not always the same, in case that matters.

**Client PC details**
 - OS: Windows 10 21H2
 - Moonlight Version: 3.2.0
 - GPU 0: Intel(R) HD Graphics 5600
 - GPU 1: NVIDIA GeForce GTX 970M <-- I force Windows to use this for Moonlight

**Server PC details**
Both PCs are:
 - OS: Windows 11 Pro 21H2
 - GeForce Experience version: 3.25.0.84
 - Nvidia GPU driver: 511.79
 - Antivirus and firewall software: Whatever Windows Defender does by default. I haven't activated anything manually.

**Comment by cgutman** [comment]
GeForce Experience (and Moonlight) uses the [MachineGuid value in the registry](https://stackoverflow.com/questions/30676726/is-hkey-local-machine-software-microsoft-cryptography-machineguid-unique) to uniquely identify your system.

Having the same values between multiple machines usually indicates a cloned machine image that was not correctly "generalized" with the [Microsoft Sysprep tool](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep--generalize--a-windows-installation?view=windows-11).

**Comment by BlueSialia** [comment]
Oh, that makes sense. Both Windows 11 servers are virtual machines whose C disk was created using `qemu-img` using a backing file containing a clean Windows installation. MachineGuid must be the same for sure.
Do you know of an easy way to change the MachineGuid?
If not it's okay. This issue doesn't really bother me that much.

**Comment by cgutman** [comment]
> Do you know of an easy way to change the MachineGuid?
If not it's okay. This issue doesn't really bother me that much.

I don't personally, but you may find a way to do it on the Internet somewhere.
