### ISSUE TITLE
Game controller nimbus+ l2, r2 not ‘analog’, full press or none

### ISSUE THREAD

**Issue by cooldna2** [moonlight-stream/moonlight-qt#757]
Hello,
with nimbus plus,
when I try to accelerate a car very slowly through moonlight streaming, I press r2 lightly, but no matter how light I press, the car accelerates with full throttle, which means even with very light pressure r2 button sends full pressure signal to the host. I wonder if there is any solution for this.

**Comment by cgutman** [comment]
Most likely this is related to either the specific mapping that SDL is using for your gamepad (fixable) or how your gamepad exposes the trigger buttons (probably not fixable).  It sounds like the current mapping is just using digital buttons as the triggers. Some gamepads report both, so this is not completely unusual.

Moonlight uses controller mappings from https://github.com/gabomdq/SDL_GameControllerDB. You can try using some of the mapping tools mentioned on their readme to see if you can find the proper axis values that are reported for the triggers (if they exist).

**Comment by cooldna2** [comment]
If I learn the syntax of mapping string, I might be able to modify the Nimbus Plus mapping so I can fix this, 'cause I found gamepad tester web site and on the site pushing l2 or r2 button returns the button variable name and its 'analog' value.

**Comment by cgutman** [comment]
I'm going to close this since it's a bug in the https://github.com/gabomdq/SDL_GameControllerDB mappings, not Moonlight itself. If you need further help, you can file an issue on that repo to get the mappings fixed.
