### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by RikudouSage** [moonlight-stream/moonlight-qt#759]
So I added a Czech translation of the whole moonlight-qt project at https://hosted.weblate.org/projects/moonlight/moonlight-qt/cs/. Is there anything else needed to include it in the project? The language name in Czech is "čeština" (but I assume you use some intl library for that).

**Comment by cgutman** [comment]
Nope, you don’t need to do anything else. I’ll pick it up next time I import from Weblate.

Thanks for translating!
