### ISSUE TITLE
Launching any game only launches the first game on my list.

### ISSUE THREAD

**Issue by jrizz43** [moonlight-stream/moonlight-qt#76]
**Describe the bug**

 (Alien Isolation) in this case. It happens to apps I manually added to GeForce Experience and to all of the games auto detected.

**Steps to reproduce**
Any special steps that are required for the bug to appear.

Launch any game

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? No
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1803] W10 1803
 - Moonlight Version: [e.g. v0.2.0] 0.4.0.0

**Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux, logs print to the terminal when running via `flatpak run com.moonlight_stream.Moonlight`

**Additional context**

**Comment by cgutman** [comment]
This is documented in the Known Issues section for v0.4.0. https://github.com/moonlight-stream/moonlight-qt/releases/tag/v0.4.0

You should quit the currently running game before launching a new one in the meantime.

If that doesn't work, please upload the log file as mentioned in the issue template.

**Comment by cgutman** [comment]
Fixed in https://github.com/moonlight-stream/moonlight-qt/commit/b8169ae08b5973eeb0841a8f82a4b26c6e5a0b9f

**Comment by cgutman** [comment]
Fix released in v0.5.0 (Beta 2).
