### ISSUE TITLE
why is gamepad support limited to 4 players?

### ISSUE THREAD

**Issue by FerLuisxd** [moonlight-stream/moonlight-qt#760]
**Is your feature request related to a problem? Please describe.**
why is gamepad support limited to 4 players?

**Describe alternatives you've considered**
Alternatively, Parsec allows more than 4, I'd love to see moonlight with more gamepads allowed for games like Brawlhalla

**Comment by cgutman** [comment]
Nvidia GameStream only supports up to 4 gamepads. Moonlight can support more than 4 but additional controllers are ignored by the host.
