### ISSUE TITLE
Moonlight crashes if TV PC is hooked up to turns off or on

### ISSUE THREAD

**Issue by bhanratt** [moonlight-stream/moonlight-qt#763]
My gaming pc is hooked up to a Sony oled tv. I use moonlight to play games on my windows laptop. If the Sony tv is turned on while playing, moonlight crashes and ends the session. The same happens if the tv turns off. It also has no audio when I start a new session, and I need to change my audio device to Sony TV manually.

**Comment by cgutman** [comment]
Please attach the Moonlight logs mentioned in the issue template.

> It also has no audio when I start a new session, and I need to change my audio device to Sony TV manually.

Where are you selecting that? Moonlight can’t change your system-wide audio device itself. It’s probably that your TV is disconnecting which causes Windows to select a different audio output.
