### ISSUE TITLE
migrate to discord game sdk

### ISSUE THREAD

**Issue by laralove143** [moonlight-stream/moonlight-qt#764]
the currently used discord-rpc is deprecated in favor of discord gamesdk, it'd also let us get neat features like the icon being whatever the user is actually playing instead of just moonlight's icon (that might be kept in the small icon)

**Comment by cgutman** [comment]
This is not possible because the Discord GameSDK is incompatible with GPL-licensed open source programs.

See https://github.com/discord/discord-rpc/issues/290 for details.
