### ISSUE TITLE
4.0 stuck always on top in borderless windowed mode

### ISSUE THREAD

**Issue by arandomusertoo** [moonlight-stream/moonlight-qt#766]
Using 3.2 portable (and previous versions) I've always been able to alt tab out of Moonlight in borderless windowed mode and back into any other program on the client computer.

In 4.0 portable (extracted over the 3.2 folder), alt tab shows the program I'm switching to, but Moonlight stays on top after releasing alt tab.

Downgrading to 3.2 portable (extracted back on top of the 4.0 extracted folder) fixes the issue.

I've checked the release notes for 4.0 and don't see anything that says this should be happening...

**Comment by cgutman** [comment]
You can use Ctrl+Alt+Shift+D as a workaround in the meantime until it's fixed

**Comment by cgutman** [comment]
Upstream SDL bug: https://github.com/libsdl-org/SDL/issues/5509

**Comment by cgutman** [comment]
Fix released in v4.1.0
