### ISSUE TITLE
"Add PC manually" button disappearing in Italian and Traditional Chinese

### ISSUE THREAD

**Issue by jorys-paulin** [moonlight-stream/moonlight-qt#767]
**Describe the bug**
With some languages like Italian, the button to manually add PCs doesn't appear, making it impossible to add PCs manually. Affected languages are Italian `it` and Traditional Chinese `zh_Hant`.

**Steps to reproduce**
1. Start Moonlight in English, see the button is there
2. Open settings, change the language to Italian
3. Go back to the hosts page, the button is now gone

**Screenshots**
![Moonlight_2022-04-10_20-56-53](https://user-images.githubusercontent.com/5084309/162635454-ebfa5b03-3c2a-41b5-8671-51f7a3c94002.png)
![Moonlight_2022-04-10_20-57-58](https://user-images.githubusercontent.com/5084309/162635461-715cc958-b6e8-4a50-94e5-6b4fe6784348.png)

**Other Moonlight clients**
This issue probably doesn't appear on Moonlight Android

**Moonlight settings**
Default settings, only language is changed

**Client PC details**
 - OS: Windows 10 21H2
 - Moonlight Version: 4.0.0
 - GPU: AMD Radeon RX 580

**Moonlight Logs (please attach)**
[Moonlight-1649617551.log](https://github.com/moonlight-stream/moonlight-qt/files/8459721/Moonlight-1649617551.log)

**Additional context**
Two languages, Thai `th` and Swedish `sv`, show the English translation, not sure if it's because it's not defined or was copy-pasted and left untranslated. Either way, the button still shows in those languages.

**Comment by jorys-paulin** [comment]
Thanks to `@KuroiBK#9500` over on the Discord server for discovering and reporting this issue!

**Comment by cgutman** [comment]
The problem was that there were different translations for the same word "Computers" in multiple contexts (PcView.qml and main.qml). This broke the comparison logic that we used to determine if we were on the Computers page.

**Comment by jorys-paulin** [comment]
I can confirm the bug is indeed fixed, thanks for the quick response!
