### ISSUE TITLE
iOS 4.1 custom resolution suddenly crashed

### ISSUE THREAD

**Issue by AlexAnorak** [moonlight-stream/moonlight-qt#768]
Hello,

+ Device:iPad Pro 2020
+ Custom Resolution:2388*1668,iPad 11-inch native resolution

The Custom Resolution has been working perfectly since i upgrade to version 4.1,but today it crashed today suddenly with no reason.But the normal resolution still works well.

**Comment by AlexAnorak** [comment]
i’m sorry ,maybe should i report this issue on moonlight-ios?

**Comment by cgutman** [comment]
Yes please file an issue on moonlight-ios instead. This repo is for the PC client.
