### ISSUE TITLE
Can't quit streaming on macOS client

### ISSUE THREAD

**Issue by PatiB87** [moonlight-stream/moonlight-qt#77]
When I use the macOS client and stream e.g. an emulator, the streaming does not stop when I quit the emulator (might be Nvidias Issue) and therefore I cannot quit the streaming AT ALL!

No cmd+Q, no Ctrl+F4, not even gestures on the trackpad let me quit moonlight!

**Comment by cgutman** [comment]
You can quit with Ctrl+Alt+Shift+Q.

**Comment by cgutman** [comment]
Added help text to stream loading page with the quit shortcut

**Comment by dationguyen** [comment]
should be 
control + option + shift +Q 
there is no alt on Mac's keyboard

**Comment by jaddel** [comment]
When an external monitor was connected and not set as the primary display, I experienced the same issue under MacOS.


Used Keys: control + option + shift +Q

**Comment by Vzor-** [comment]
I changed Globe and Control in Keyboard>Keyboard shortcuts>Modifier keys, and ctrl alt shit q has never worked for me. Changing it to default fixes the issue. Moonlight should respect the system bindings.

**Comment by x1unix** [comment]
Both hotkeys doesn't work when connected to external display

**Comment by kennethklee** [comment]
now, once that quit dialog opens, how do you press the Quit button? Mouse is trapped in-game.

**Comment by Sapu98** [comment]
still a problem, cant quit streaming while im using an external display with my mac
