### ISSUE TITLE
[Report] Issue with keepassxc

### ISSUE THREAD

**Issue by Elegary** [moonlight-stream/moonlight-qt#770]
Hello,

I post this bug report to inform about an issue with the software keepassxc (https://github.com/keepassxreboot/keepassxc/).
I was trying to figure out why all my moonlights clients where unable to launch streaming (network and firewall were all ok), it was showing me to try to figure out which software was using DRM content but that was not my case. I finally found that the issue is coming from keepassxc, which start at reboot for my pc. Just close Keepassxc solved the issue. You should include this software in the Wiki in troubleshootings software.

**Comment by cgutman** [comment]
Yeah, looks like an instance of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/16 but with KeePassXC instead of iCloud Keychain.

**Comment by cgutman** [comment]
Added a note to the troubleshooting page about this. Thanks

**Comment by ZhangTianrong** [comment]
It would also be nice if you can include this workaround, too: If the user is willing to allow capturing of the window, he/she can use the `--allow-screencapture` argument when launching KeepassXC as per [the user guide](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security). There is no way to set this option if the app is set to start with Windows in the setting. To still start the password manager on boot, turn that off and create a shortcut of KeepassXC with the cli argument in the startup folder.

**Comment by Elegary** [comment]
Thanks for the tip I ! I didn't check if this option existed... It's a very useful param.
