### ISSUE TITLE
Scroll acceleration translation bug from macOS to Windows

### ISSUE THREAD

**Issue by vJan00** [moonlight-stream/moonlight-qt#778]
**Describe the bug**
Translating between macOS and Windows when scrolling the mouse does not work properly.
So macOS has a scroll acceleration, which Windows does not have.
This is noticeable in simulation games like Cities: Skylines, Planet Zoo, Planet Coaster.
However, it is a general problem of the Moonlight client, which is only noticeable in games where you have to scroll.

**Steps to reproduce**
Start an NVIDIA GameStream server on Windows and a Moonlight client on macOS, open the browser for example and scroll. Then switch to the Windows PC natively with the mouse, the mouse behaves differently when scrolling.

**Affected games**
Client wide but only affecting programs that uses the scroll wheel.

**Moonlight settings**
Mouse related settings are as follows (changing them didn't solve the problem):
Optimize mouse for remote desktop instead of games: off
Capture system keyboard shortcuts: always
Use touchscreen as virtual trackpad: false
Swap eft and right mouse buttons: false
Reverse mouse scrolling direction: false

**Client PC details**
 - OS: macOS Montery 12.3.1 (21E258)
 - Moonlight Version: v4.0.0
 - GPU: AMD RX580

**Server PC details**
 - OS: Windows 11 Pro 10.0.22000 Build 22000
 - GeForce Experience version: Version 3.25.1.27
 - Nvidia GPU driver: Version 512.15
 - Antivirus and firewall software: Windows Defender and Windows Firewall
 - 
**Additional context**
@vhd once made an fix for it that worked like charm, it included fixing the values that gets transferred:
https://github.com/vhd/moonlight-qt/commit/16333fc997b310740240a4235ace0b273023a449
Maybe this could be implemented with a new settings button to switch on and off?

**Comment by Adnn** [comment]
I can confirm this issue exists with the latest macos moonlight client.

**Comment by kintsugi** [comment]
Me as well.

**Comment by cgutman** [comment]
I introduced a workaround similar to what was done by @vhd to clamp the scroll deltas at +/- 1.

Please try this build and let me know if it fixes the issue: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/43579792/job/jgh7c00aburpqegm/artifacts

**Comment by vJan00** [comment]
The build works for me, no weird scrolling anymore.

**Comment by cgutman** [comment]
Released in v4.1.0

**Comment by Adnn** [comment]
This fixes the issue for me too, thank you!
