### ISSUE TITLE
Why not support Alt + F4？

### ISSUE THREAD

**Issue by House-Men** [moonlight-stream/moonlight-qt#779]
Users accustomed to using Alt + F4
Now when using moonlight full screen operation, you are forced to use the mouse to operate, which is very inconvenient

**Comment by cgutman** [comment]
Moonlight can send Alt + F4 to the host, but GeForce Experience explicitly suppresses that key combo.

If you use an alternate hosting software such as [Sunshine](https://github.com/SunshineStream/Sunshine), Alt+F4 does work.

**Comment by House-Men** [comment]
> Moonlight 可以向主机发送 Alt + F4，但 GeForce Experience 明确禁止显示该键组合。
> 
> 如果您使用[Sunshine](https://github.com/SunshineStream/Sunshine)等备用托管软件，Alt + F4确实有效。

Sunshine is slow to use
It seems that it can only be solved through hook. GeForce Experience not support Alt + F4

**Comment by makedir** [comment]
If I press alt+f4 connection it closes moonlight instead of sending it to the host.

**Comment by shodanx2** [comment]
Hello,
In my current case, 
I would like to send alt-f4 but the moonshine window closes
Is there a way to decide, if the moonlight window is focused
to forward certain key combo to the sunshine host instead ?

Keys such as alt+f4, windows button, printscreen button
maybe decide per-key 
and decide if they are "captured" (not seen on the client OS) of if they are to be processed on both
Like currently, if you press printscreen, both my client OS and my sunshine host do a printscreen

You can imagine someone could prefer, when moonlight is focused
the 3 following possibilities
print screen only in the sunshine host, (this probably should be the default)
print screen only in the client OS
print screen in both (this is what currently happens)

NOTE : I only use moonlight in windowed mode with absolute mouse movement, I suspect this is not the same behaviour for exclusive fullscreen users.

**Comment by cgutman** [comment]
You can use Alt+F4 when you enable the system keyboard shortcut capture option in Moonlight settings. Same with the Windows key.
