### ISSUE TITLE
Random video freezes during play

### ISSUE THREAD

**Issue by oreyg** [moonlight-stream/moonlight-qt#78]
Moonlight becomes unresponsive, but audio continues to play. Input events are passed to host, but client itself does not react to esc or alt+f4. Client will not recover after this. This seem to happen randomly.

Moonlight settings:
1080p, 20mbps

Client:
Intel Core i5-4200u,
Nvidia GT 750m,
6 GB RAM,
Windows 10,
Moonlight 0.4.0

Host:
Intel Core i7-5820k,
Nvidia GTX 980 Ti,
16 GB RAM,
Windows 10,
GeForce Experience 3.14.1

Logs:
[Moonlight-1537047129.log](https://github.com/moonlight-stream/moonlight-qt/files/2386109/Moonlight-1537047129.log)
[Moonlight-1537047840.log](https://github.com/moonlight-stream/moonlight-qt/files/2386110/Moonlight-1537047840.log)

**Comment by oreyg** [comment]
It could be that it is associated with short network connectivity spikes.
Maybe a duplicate of
https://github.com/moonlight-stream/moonlight-qt/issues/57

**Comment by oreyg** [comment]
@cgutman force H.264 fixes this

**Comment by cgutman** [comment]
Great, then the next release will behave properly on Automatic codec selection.

**Comment by cgutman** [comment]
The fix was done in https://github.com/moonlight-stream/moonlight-qt/commit/9dcd856099661f3a575a4bd781af6182864eab10

Fix released in v0.5.0 (Beta 2).
