### ISSUE TITLE
shut down/sleep buttons for the host

### ISSUE THREAD

**Issue by laralove143** [moonlight-stream/moonlight-qt#782]
**Is your feature request related to a problem? Please describe.**
so as it generally happens, i exit the game, the stream is over, i have to restart the stream from the desktop, shut down using the start menu then the stream freezes and i force quit moonlight

**Describe the solution you'd like**
it'd be nice to have buttons to shut down or put our computers to sleep, similar to the WOL function

**Describe alternatives you've considered**
i tried to add a shortcut that runs the shutdown executable, it worked but it's a hacky solution

**Additional context**
the button that opens the shutdown context menu here would be nice
<img width="1312" alt="Screen Shot 2022-04-26 at 5 32 39 PM" src="https://user-images.githubusercontent.com/82576556/165324962-45afacd2-919b-42e7-a878-90073e03757f.png">

**Comment by laralove143** [comment]
is this gonna be considered?

**Comment by cgutman** [comment]
The NVIDIA GameStream protocol does not provide a built-in mechanism for a shutdown or sleep feature, so it is not possible to implement in Moonlight directly.

If you want this functionality, you can probably achieve it by creating a batch script that runs `shutdown /s /t 0` (shutdown) or `rundll32.exe powrprof.dll, SetSuspendState Sleep` (sleep) and [adding it as a custom app](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#adding-custom-programs-that-are-not-automatically-found).
