### ISSUE TITLE
"Unable to locate package" during install moonlight-qt on Nvidia Jetson Xavier NX

### ISSUE THREAD

**Issue by foggyflute** [moonlight-stream/moonlight-qt#786]
**Describe the bug**
install command return "E: Unable to locate package moonlight-qt" on my Jetson Xavier NX board running Jetpack 5.0 Developer Review (Ubuntu 20.04 L4T 64bit). A quick search through bug reports already on Github show that install on 64-bit OS (including what I currently use on Jetson board) currently blocked due to Raspberry Pi OS 64-bit having problem with low latency hardware decoding?

So anyway to go around the blocking, since the Jetson NX is much more powerful, it should be able to perform the decoding that Pi board can not? I'm not an expert in Linux and OS stuffs so apologies if there's a simple solution that I was glossed over.

**Comment by cgutman** [comment]
The issue you saw was specific to the Raspberry Pi (and has since been fixed anyway). The L4T package has been 64-bit from the beginning.

The reason you can't install moonlight-qt is because you're running Ubuntu 20.04 and the L4T package is built for 18.04 (the latest version for the Jetson Nano).

The package for Ubuntu 18.04 might work on Ubuntu 20.04. Can you try:
`curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-l4t/setup.deb.sh' | distro=ubuntu codename=bionic sudo -E bash`

**Comment by foggyflute** [comment]
Thanks for your response, I was able to install moonlight-qt on ubuntu 20.04, but sadly the program unable to run, this is the output in terminal:
`00:00:00 - SDL Info (0): Compiled with SDL 2.0.21
00:00:00 - SDL Info (0): Running with SDL 2.0.21
00:00:00 - Qt Info: No translation available for  "en"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at "/home/foggy/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:01 - SDL Info (0): Loaded 202 new gamepad mappings
00:00:01 - SDL Info (0): V-sync disabled
00:00:01 - SDL Error (0): Failed to open DRM device: 2
00:00:01 - SDL Error (0): Failed to open DRM device: 2
00:00:01 - SDL Error (0): Failed to open DRM device: 2
00:00:01 - SDL Error (0): Failed to open DRM device: 2
00:00:01 - SDL Error (0): Unable to load FFmpeg decoder
00:00:01 - SDL Info (0): V-sync disabled
00:00:01 - SDL Info (0): Using SDL renderer
00:00:01 - FFmpeg: [hevc_mp4toannexb @ 0xffff700f72a0] The input looks like it is Annex B already
Opening in BLOCKING MODE 
00:00:01 - FFmpeg: [hevc_nvv4l2 @ 0xffff705988b0] New NvBuffer Utils version
NvMMLiteOpen : Block : BlockType = 279 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 279 
00:00:01 - FFmpeg: [hevc_nvv4l2 @ 0xffff705988b0] Starting capture thread
00:00:01 - FFmpeg: [hevc_nvv4l2 @ 0xffff705988b0] Resolution changed to: 1280x720
00:00:01 - FFmpeg: [hevc_nvv4l2 @ 0xffff705988b0] Colorspace ITU-R BT.601 with standard range luma (16-235)
Segmentation fault (core dumped)
`
I guess I have to wait for an update when jetpack 5 finally release. Meanwhile, I found an unofficial 3.1.4-2 build that only use software encoding that work okay-ish for my purpose.

Hope to see it fully functional on newer linux for nvidia boards soon, thanks.
Best regards to the team.

**Comment by DanielCalverley** [comment]
+1

stream@stream:~$ curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | distro=raspbian codename=$(lsb_release -cs) sudo -E bash
sudo apt install moonlight-qt
Executing the  setup script for the 'moonlight-game-streaming/moonlight-qt' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
  RUN: Importing 'moonlight-game-streaming/moonlight-qt' repository GPG keys ...gpg: WARNING: unsafe ownership on homedir '/home/stream/.gnupg'
   OK: Checking for apt signed-by key support ...
   OK: Importing 'moonlight-game-streaming/moonlight-qt' repository GPG keys ...
 NOPE: Checking if upstream install config is OK ...
 ^^^^: ... Failed to fetch configuration for your OS distribution release/version.
 >>>>:
 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=raspbian  version=<empty>  codename=mantic  arch=aarch64  
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as Ubuntu/Xenial (16.04), use the following:
 >>>>:
 >>>>:   <curl command> | distro=ubuntu version=16.04 codename=xenial sudo -E bash
 >>>>:
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact Moonlight Game Streaming for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/moonlight-stream/moonlight-qt
 !!!!: 
 !!!!: Last 20 log lines from .csm_setup_IOcp12WKL (might not be errors, nor even relevant):
 !!!!:
 !!!!: > ii  gnupg                                         2.2.40-1.1ubuntu1
 !!!!: > all          GNU privacy guard - a free PGP replacement
 !!!!: > ii  gnupg-l10n                                    2.2.40-1.1ubuntu1
 !!!!: > all          GNU privacy guard - localization files
 !!!!: > ii  gnupg-utils                                   2.2.40-1.1ubuntu1
 !!!!: > arm64        GNU privacy guard - utility programs

**Comment by cgutman** [comment]
@DanielCalverley Test builds of Jammy and Noble packages are available here: https://github.com/moonlight-stream/moonlight-qt/issues/1208#issuecomment-2041182980

Also you should use the L4T apt repo instead of the regular one since L4T requires special patches. See https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Linux4Tegra-(L4T)-Ubuntu

**Comment by EldrML** [comment]
Rather than make a new issue report, I figured I would comment here that I am getting the same error log as DanielCalverley, but I am attempting to install `moonlight-qt` on a Raspberry Pi 400 with Bullseye as the OS.

Would love any feedback on what I might be doing wrong, as I am essentially brand-new to Linux and Raspbian in particular. Thanks!

**Comment by cgutman** [comment]
Released in v6.0.0
