### ISSUE TITLE
Frame drops on Linux

### ISSUE THREAD

**Issue by eke21** [moonlight-stream/moonlight-qt#787]
**Describe the bug**
I'm seeing frame drops (%2-50) when using Moonlight on Linux, both ends are wired, tested on Fedora 36, Ubuntu 22.04 both wayland and x11, hardware and software decoding, this issue doesnt appear on Windows.

**Client PC details (please complete the following information)**
 - OS: Fedora 36
[moonlightlog.txt](https://github.com/moonlight-stream/moonlight-qt/files/8643569/moonlightlog.txt)

 - Moonlight Version: 4.0
 - GPU: Intel HD Graphics 520

**Server PC details (please complete the following information)**
 - OS: Windows 11
 - GeForce Experience version: latest
 - Nvidia GPU driver: latest
 - Antivirus and firewall software: [e.g. Windows Defender and Windows Firewall]

**Moonlight Logs (please attach)**
[moonlightlog.txt](https://github.com/moonlight-stream/moonlight-qt/files/8643569/moonlightlog.txt)

**Additional context**
I monitored network when streaming, while on windows moonlight uses 100Mbit or more when streaming but on linux it fluctates between 20-50mbit. Bitrate setting is 100Mbit

**Comment by cgutman** [comment]
Looks like legit packet loss to me as it's affecting both video and audio.

```
00:00:14 - SDL Info (0): Network dropped audio data (expected 1227, but received 1287)
00:00:16 - SDL Info (0): Unrecoverable frame 484: 11+0=11 received < 17 needed
00:00:16 - SDL Info (0): Network dropped 1 frame (frame 484)
00:00:16 - SDL Info (0): Waiting for IDR frame
00:00:16 - SDL Info (0): IDR frame request sent
00:00:16 - SDL Info (0): Unrecoverable frame 492: 11+0=11 received < 12 needed
00:00:16 - SDL Info (0): Network dropped 1 frame (frame 492)
00:00:16 - SDL Info (0): Waiting for IDR frame
00:00:16 - SDL Info (0): IDR frame request sent
00:00:19 - SDL Info (0): Unrecoverable frame 659: 11+0=11 received < 15 needed
00:00:19 - SDL Info (0): Network dropped 1 frame (frame 659)
00:00:19 - SDL Info (0): Waiting for IDR frame
00:00:19 - SDL Info (0): IDR frame request sent
00:00:20 - SDL Info (0): Unrecoverable frame 711: 11+0=11 received < 13 needed
00:00:20 - SDL Info (0): Network dropped 1 frame (frame 711)
00:00:20 - SDL Info (0): Waiting for IDR frame
00:00:20 - SDL Info (0): IDR frame request sent
```

You mention that it doesn't impact Windows. I assume you are referring to Windows running on the same client PC?

I would initially suspect the NIC driver. The bursts of traffic sent for each frame can easily overwhelm undersized driver/hardware buffers and cause packet loss. The fact that it most often receives exactly 11 packets and no FEC packets (the `+0` in the log) is another indicator that it's unable to cope with the burst and dropping everything after the first few packets. What NIC are you using on your client?

I'd also be interested in the output of `ip -s link show` but the drops may not show there depending on what layer in the stack they're happening.

**Comment by eke21** [comment]
enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 70:8b:cd:1f:80:74 brd ff:ff:ff:ff:ff:ff
    RX:  bytes packets errors dropped  missed   mcast           
    6905358026 5958590      0       3   54829    1236 
    TX:  bytes packets errors dropped carrier collsns           
    4200821186 3051836      0       0       0       0 
`ip -s link show` shows this when streaming, missed packets increasing when frame drops are happening.

Yes i am using the same PC on Windows, NIC is Realtek using r8169 driver. I tested over wifi (2.4ghz) and it seems it doesnt drop frames. I think this issue unrelated to Moonlight. Any idea why ethernet dropping frames when wifi working correctly.

wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether 74:df:bf:f0:b4:42 brd ff:ff:ff:ff:ff:ff
    RX:  bytes packets errors dropped  missed   mcast           
     180286274  178993      0       0       0       0 
    TX:  bytes packets errors dropped carrier collsns           
        529124    4761      0       0       0       0

**Comment by iwillreku3206** [comment]
I am also having this issue for about 2 weeks now. Part of my logs are in the discord server

**Comment by iwillreku3206** [comment]
Does the new release resolve this bug?

**Comment by cgutman** [comment]
No, this is a hardware/driver issue.
