### ISSUE TITLE
[Organisation] Why not add Moonlight-common-c as a submodule?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [moonlight-stream/moonlight-qt#789]
**Is your feature request related to a problem? Please describe.**
The Qt, iOS and Android versions are a bit all over the place, it would be nice to know exactly what revision/commit of moonlight-core they are using.

**Describe the solution you'd like**
All the non-platform specific stuff should come from a submodule, which I guess would be moonlight-common-c like in the ChromeOS/NaCL repo?

**Describe alternatives you've considered**
Some tag/info in the readme ?

**Additional context**
I know I'm just being annoying, but I'm looking into a WASM port, and thinking whether to take one of the mobile platforms and stick Angular/React on top instead of attempting Qt in WASM.

**Comment by cgutman** [comment]
This submodule is here: https://github.com/moonlight-stream/moonlight-qt/tree/master/moonlight-common-c
