### ISSUE TITLE
Starting RTSP handshake failed: Error 500

### ISSUE THREAD

**Issue by pokemaster974** [moonlight-stream/moonlight-qt#790]
**Describe the bug**
Got an error :
Starting RTSP handshake failed: Error 500
Check your firewall and portforwarding rules for port(s) : TCP 48010, UDP 48000, UDP 48010

**Steps to reproduce**
I download the zip from the sunshine github repo
I modify the .conf (or the UI) to change the famiy of ports from 47989 to 37989
I've added ports rules into my Windows firewall
TCP 37984, 37989, 38010
UDP 37998, 37999, 38000, 38002, 38010
I've opened the same ports into my routeur interface
I launch the sunshine.exe

I launched moonlight
I paired my moonlight client with success
I launch the desktop session

**Affected games**
Desktop

**Client PC details (please complete the following information)**
 - OS: Windows 10
 - Moonlight Version: 4.0.0
 - GPU: Intel chipset

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - Sunshine 0.13.0
 - Nvidia GPU driver: 512.77
 - Antivirus and firewall software: Avast, default Windows firewall

**Moonlight Logs (please attach)**
00:01:39 - SDL Info (0): RTSP port: 38010
00:01:39 - SDL Info (0): Initializing platform...
00:01:39 - SDL Info (0): WLAN interface 0 is now in low latency mode
00:01:39 - SDL Info (0): done
00:01:39 - SDL Info (0): Resolving host name...
00:01:39 - SDL Info (0): done
00:01:39 - SDL Info (0): Initializing audio stream...
00:01:39 - SDL Info (0): done
00:01:39 - SDL Info (0): Starting RTSP handshake...
00:01:39 - SDL Info (0): Audio port: 38000
00:01:39 - SDL Info (0): Video port: 37998
00:01:39 - SDL Info (0): Control port: 37999
00:01:39 - SDL Info (0): RTSP ANNOUNCE request failed: 500
00:01:39 - SDL Info (0): failed: 500
00:01:40 - SDL Info (0): TCP port 48010 test successful
00:01:40 - SDL Info (0): UDP port 48000 test successful
00:01:40 - SDL Info (0): UDP port 48010 test successful
00:01:40 - SDL Info (0): Cleaning up audio stream...
00:01:40 - SDL Info (0): done
00:01:40 - SDL Info (0): Cleaning up platform...
00:01:40 - SDL Info (0): done

**Additional context**
I would like to change the family port because of ports blocking in some places I would like to use it (that's why I prefer to use sunshing instead of GFE

**Comment by cgutman** [comment]
This looks like a Sunshine issue. It looks like Moonlight is parsing the custom ports properly, so I don’t see a bug here. You should investigate the Sunshine logs to determine why it decided to respond with a 500 error to Moonlight’s request.
