### ISSUE TITLE
sdl2-2.0.22 breaks xpad support

### ISSUE THREAD

**Issue by cantenna** [moonlight-stream/moonlight-qt#792]
**Describe the bug**
Upgrading to sdl2-2.0.22 breaks xpad support

**Steps to reproduce**
Upgrade to sdl2-2.0.22 

**Affected games**
ALL

**Other Moonlight clients**
- unconfirmed

**Moonlight settings (please complete the following information)**
- Does the problem still occur after reverting settings back to default?
No, reverting to sdl2-2.0.20-2-x86 fixes xpad support

**Comment by cgutman** [comment]
What distro are you using? Which Moonlight package?

In what way is xpad support broken? Are the buttons incorrectly mapped? Does the controller not work at all?

Are other applications that use SDL2 affected?

**Comment by cantenna** [comment]
Using arch, yay air, moonlight-qt, moonlight-qt-git repo

Moonlight with this SDL version actually breaks xpad support system wife for some reason, only fix is to reboot.

Should note xpad work fine with this ver of SDL for so long as you do not start moonlight

**Comment by cgutman** [comment]
> Using arch, yay aur, moonlight-qt, moonlight-qt-git repo

Does this happen if you use on of the official packages? (Flatpak, Snap, or AppImage)

> 
> Moonlight with this SDL version actually breaks xpad support system wide for some reason, only fix is to reboot.

How exactly does it break xpad? What are the symptoms?

> 
> Should note xpad works fine with this ver of SDL for so long as you do not start moonlight

What other SDL-based applications did you try?

**Comment by cantenna** [comment]
Have not tried any of the official images; Flatpak, Snap, or AppImage

What other SDL-based applications did you try?

Retroarch and Steam,both work fine prior to running moonlight. After running moonlight, neigher application works with xpad.

**Comment by cgutman** [comment]
Please collect logs from moonlight by running it from the terminal and attach them to the issue here.

> Have not tried any of the official images; Flatpak, Snap, or AppImage

Please try one. The AUR repo is not an official package source.

> Retroarch and Steam,both work fine prior to running moonlight. After running moonlight, neigher application works with xpad.

You still have not clarified what exactly the symptoms of the issue are. Controllers don't show up anymore? Controllers show up but input doesn't work at all? Controllers show up but input is mapped wrong?

What model of Xbox controller are you using?

**Comment by cgutman** [comment]
Closed due to lack of response from OP
