### ISSUE TITLE
Microphone input

### ISSUE THREAD

**Issue by szelszabi** [moonlight-stream/moonlight-qt#798]
**Is your feature request related to a problem? Please describe.**
I can't seem to use my microphone for voicechat in games.

**Describe the solution you'd like**
In the settings you could select a microphone input that gets transferred along with keyboard, mouse and controller inputs. You could select the device from a drop-down menu.

**Comment by cgutman** [comment]
This a limitation of NVIDIA GameStream. There is no support for microphone when streaming locally from another PC (unlike GeForce Now which does support it). We aren't able to support it until NVIDIA GameStream does.

**Comment by rmaenk** [comment]
As workaround you can try VoiceMeeter.
[Video on youtube: Dual PC Audio Setup: How to Send Audio & Microphone over Ethernet](https://www.youtube.com/watch?v=DWLOWwm4-2g)

Regards, 
Roman
