### ISSUE TITLE
blank screen with audio

### ISSUE THREAD

**Issue by JUSTs79** [moonlight-stream/moonlight-qt#80]
after 0.3.0 version start to experiencing the problem. trying to connect from win10 i have blank screen with audio, but when i try to connect from android 6 in same time, everything works fine.
sometimes 0.3.0 have this issue too but occasionally

problem occurs on 0.4.0 and 0.5.1 versions of moonlight qt. connection was host win 10 1803 to client win10 1803 with latest 399.24 nvidia drivers on geforce 650 Ti

[Moonlight-1537206483.log](https://github.com/moonlight-stream/moonlight-qt/files/2389669/Moonlight-1537206483.log)

**Comment by cgutman** [comment]
This looks like extreme network packet loss. Every frame is missing over 2/3 of its packets.

I would suggest trying a different network cable, switch, or connecting via a different medium (WiFi or Ethernet)
