### ISSUE TITLE
Maximized window keeps gap on top

### ISSUE THREAD

**Issue by reloxx13** [moonlight-stream/moonlight-qt#800]
**Describe the bug**
After some time playing and switching fullscreen/window mode (switching max and non-maximized) with the ctrl+alt+shift+x shortcut, tab-ing in and out and I decide to keep the screen in maximize mode not in fullscreen mode, it won't maximize completely and keeps a gap on top while the bottom of the moonlight window is hidden under my taskbar.    
This bug exists for a long time now and I was so annoyed now that I had to open an issue :D    

I guess it has something to do with my taskbar having the double size (on purpose).

**Steps to reproduce**
it happens randomly by often switching fullscreen, window, maximized window, non-maximized windows mode.
Literally:
- Start a stream
- Switch window to maximize
- Switch to Fullscreen
- Disable fullscreen
- Maximize has gap now

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14855001/171046170-36afbac4-a6ab-4be7-899a-d48f17ed694a.png)

More screenshots at next comment

**Affected games**
It's a client issue, not a host issue.    
Appeared in different games/app.   

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
Yes
- If so, which settings have been changed?
I don't know?!
- Does the problem still occur after reverting settings back to default?
I didn't try, but I think so, as it happens for a long time already.

**Client PC details (please complete the following information)**
 - OS: win10x64
 - Moonlight Version: 4.1.0
 - GPU:  860M, 
 - 1080p resolution

**Server PC details (please complete the following information)**
 - OS: win10x64
 - GeForce Experience version: 3.25.1.27
 - Nvidia GPU driver: 512.95
 - Antivirus and firewall software:  Windows Defender and Windows Firewall

**Moonlight Logs (please attach)**
I'll upload if it happens again.

**Comment by reloxx13** [comment]
It just happened again, play around with maximize, normal and fullscreen and at some point maximize will keep a gap on top of it

Top gap
![grafik](https://user-images.githubusercontent.com/14855001/171047241-2546529d-43f5-40fc-ba14-f8860f8ff698.png)


Bottom client taskbar is hiding/overlapping host taskbar
![grafik](https://user-images.githubusercontent.com/14855001/171048012-8903541e-9d7b-4b38-9ba7-f60b530ed05d.png)


This only happens with moonlight client, never had it happen with other apps/programs

[Moonlight-1653936320.zip](https://github.com/moonlight-stream/moonlight-qt/files/8800298/Moonlight-1653936320.zip)

**Comment by cgutman** [comment]
Yep, this is a known issue due to how Moonlight re-entering windowed mode after exiting full-screen. This code is very sensitive to slight variance in OS behavior and timing. We have to do all the steps in very particular order otherwise we end up with worse issues.

I tried to fix this in https://github.com/moonlight-stream/moonlight-qt/commit/38396b26919d56dab02e3e06e7791ef9b748bacf but had to revert due to the issues described in https://github.com/moonlight-stream/moonlight-qt/commit/f10b547a498ee94ca225acd5809e8a5621cf34ea

**Comment by cgutman** [comment]
Closing per https://github.com/moonlight-stream/moonlight-qt/commit/e0fb7dfd14d47d28b04a5e15049d53f494c7efdd#commitcomment-87409606
