### ISSUE TITLE
Tab s7 plus pairing window has no text, cant see pin

### ISSUE THREAD

**Issue by Discord2k** [moonlight-stream/moonlight-qt#807]
On my s20 fe it works great, I can see the pairing window with the PIN, on the tab s7 plus the window shows up when pairing but does not have any text.  It also shows the PC icon with a lock on it alrthough it does not have a lock on the phone.  They are on the same network as the PC, the enviroment is the same

**Comment by cgutman** [comment]
Please try this build and see if it fixes the issue: https://drive.google.com/file/d/1Tx6kktXOop7HWq-gnvKHiEAAc4AmkiVd/view?usp=sharing

**Comment by Discord2k** [comment]
Wow!  Youre amazing!  That is the fastest response I've ever had.  Thank
you very much.  It worked first time.  I'm up and running.
