### ISSUE TITLE
Controller stops working after UI changes (SteamLink)

### ISSUE THREAD

**Issue by roughnecks** [moonlight-stream/moonlight-qt#816]
Hi,
sorry for the bad title but I wouldn't know how to sum it up differently.

What happens:

- Plug everything to my SteamLink
- Power it on
- Select Moonlight with attached controller
- Moonlight starts
- Controller stops working
- Unplug Controller and plug it back in
- Controller starts working again
- Connect to PC
- Select and start game (Street Fighter V, if you wanted to know..)
- Game launches
- Controller stops working again

At this point I didn't try unplugging it again and plugging back.
Controller is a XBOX ONE Clone by PowerA (wired).

**Comment by cgutman** [comment]
I've seen this too. I believe it's a regression in SDL that happened in a Steam Link firmware update.

It reinitializes controllers when Moonlight calls `SDL_InitSubsystem(SDL_INIT_GAMECONTROLLER)`/`SDL_QuitSubsystem(SDL_INIT_GAMECONTROLLER)`. This happens when transitioning in and out of the UI.

**Comment by roughnecks** [comment]
> I've seen this too. I believe it's a regression in SDL that happened in a Steam Link firmware update.
> 
> It reinitializes controllers when Moonlight calls `SDL_InitSubsystem(SDL_INIT_GAMECONTROLLER)`/`SDL_QuitSubsystem(SDL_INIT_GAMECONTROLLER)`. This happens when transitioning in and out of the UI. Reinitialization should be safe to repeat, but it seems to not be for Xbox One controllers.

okay, do you want me to report it to the SteamLink Forum?

**Comment by cgutman** [comment]
> okay, do you want me to report it to the SteamLink Forum?

No need. I debugged this issue and put up a PR to fix it in SDL. https://github.com/libsdl-org/SDL/pull/5870

**Comment by Friss** [comment]
So how would one go about getting that fix? Do we need a moonlight release or a steam link update?

**Comment by cgutman** [comment]
A Steam Link firmware update unfortunately

**Comment by slouken** [comment]
FYI, Steam Link beta build 842 has this change, but people are still reporting that it's an issue?

**Comment by roughnecks** [comment]
> FYI, Steam Link beta build 842 has this change, but people are still reporting that it's an issue?

I didn't know it was fixed in the beta build, will check it out later. Thanks

**Comment by roughnecks** [comment]
It works in build 842, closing this.
