### ISSUE TITLE
running flatpak on Steam Deck causes "no video recived from host" error

### ISSUE THREAD

**Issue by lavavex** [moonlight-stream/moonlight-qt#818]
**READ ME FIRST!**
Has been read, steps have been tried...

**Describe the bug**
Trying to run Flatpak or Appimage version on my Steam Deck causes "no video received from host error" although everything works flawlessly on every other device i have moonlight on (linux appimage on thinkpad, ios iPad and iPhone, Android, Steam Link, Raspberry Pi 4B)
Tried disabling windows firewall and that did not fix issue. Steam Big Picture (the game i was trying to run, does launch on the pc though.

**Steps to reproduce**
Any special steps that are required for the bug to appear.
nothing special, i just installed flatpak from Discover on Steam Deck and paired normally then tried running Steam Big Picture mode.
same with Appimage

**Screenshots**
<img src=https://cdn.discordapp.com/attachments/465369864534491146/992271426235150366/DD63F1DD-F8A1-4A12-A4D8-664C3D18E30C.jpg></img>

**Affected games**
Every Game including Steam Big Picture

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?
no

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
  - Yes
- If so, which settings have been changed?
  - Resolution set to Native
  - Bitrate set to 20 Mbps (Speedtest shows i can run at this speed)
- Does the problem still occur after reverting settings back to default?
  - Yes

**Gamepad-related issues (please complete if problem is gamepad-related)**
N/A

**Client PC details (please complete the following information)**
 - OS: Steam OS 3.2
 - Moonlight Version: 4.1.0
 - GPU: AMD Custom GPU 0405 (Steam Deck APU)

**Server PC details (please complete the following information)**
 - OS: Windows 10 21H2
 - GeForce Experience version: 3.25.1.27
 - Nvidia GPU driver: 516.40
 - Antivirus and firewall software: Windows Defender and Firewall with Moonlight Exceptions

**Moonlight Logs (please attach)**
[Text_File.txt](https://github.com/moonlight-stream/moonlight-qt/files/9031194/Text_File.txt)

**Additional context**
Sent here by Discord admin when trying to get support in the discord
Also edited after trying Appimage and having same issue

**Comment by cgutman** [comment]
Please attach logs from the host in C:\ProgramData\NVIDIA Corporation\NvStream.

**Comment by lavavex** [comment]
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/9032165/NvStreamerCurrent.log)
[NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-qt/files/9032166/NvStreamerOld.log)
Here ya go!

**Comment by cgutman** [comment]
Something seems to be blocking the video and audio traffic to Moonlight on your Steam Deck. Moonlight claims to have not received a single video or audio packet successfully, yet there are no indications of issues on the host side. It doesn't seem to be a widespread issue, since others are using Moonlight on the Deck without issue. It could be something specific to a setting on your Deck or network configuration.

Are you able to try running a Wireshark packet capture on your Steam Deck to see if the packets are making it to the device?

**Comment by lavavex** [comment]
[moonlight.pcapng.zip](https://github.com/moonlight-stream/moonlight-qt/files/9033879/moonlight.pcapng.zip)
Here is a packet capture from my deck while trying to start Steam Big Picture from moonlight. If you need to know, the Server ip is 192,168,6,69, and i believe my deck has the ip of 192.168.6.220

**Comment by cgutman** [comment]
Yep, looks like Moonlight is reporting accurately. It indeed receives no video or audio from your host PC.

There is no UDP traffic on port 47998 or 48000 from 192.168.6.69 to 192.168.6.220. Moonlight is sending probes to the host PC to initiate traffic but it never does.

Can you perform the same capture on your host PC to compare with what the Steam Deck is receiving?

**Comment by lavavex** [comment]
[moonlightserv.zip](https://github.com/moonlight-stream/moonlight-qt/files/9035180/moonlightserv.zip)

**Comment by lavavex** [comment]
can confirm that it works over a wired ethernet connection on my steamdeck, then if i switch back to wifi without quitting the game or moonlight, i can get controls to work but video just stays frozen

**Comment by cgutman** [comment]
The PC is sending the traffic as expected, so they must be getting dropped somewhere on your network.

My theory is that your WiFi network or the Steam Link's WLAN adapter is dropping the QoS-tagged video and audio packets. Some broken APs/routers do this (or can be accidentally configured to do so).

**Comment by lavavex** [comment]
Yeah, just did some more testing and it works on my 2.4ghz network, but 5ghz kills it... tried disabling QoS but that didnt work...

**Comment by lavavex** [comment]
I think its a steam deck wlan adapter issue as the issue only occurs on the deck and not on any of my other devices on the same 5ghz network

**Comment by cgutman** [comment]
It's probably more likely some kind of interoperability issue with your AP and Steam Deck WLAN adapter. 5 GHz WiFi networks are very common (especially in higher end wireless setups that people who own a Steam Deck are likely to have), so I would expect a lot more reports of this issue if it were impacting all 5 GHz WiFi networks on the Steam Deck.

**Comment by cgutman** [comment]
You could try disabling QoS on the host PC side. Maybe something like this would work: https://docs.microsoft.com/en-us/powershell/module/netadapter/disable-netadapterqos?view=windowsserver2022-ps#example-2-disable-qos-on-a-specified-network-adapter

**Comment by lavavex** [comment]
the command errored out but disabling qos in the network adapter properties gets me further than before. now, i get a few audio packets and a black screen, then no audio packets but controls work and i dont get kicked out for no packets recieved.

**Comment by lavavex** [comment]
Fixed it! turns out steam decks wireless adapter really does not like DFS channels or 160Mhz wide bands on 5ghz... Darn you super expensive router! and Thanks Arch [Wiki!](https://wiki.archlinux.org/title/Network_configuration/Wireless#Cause_#4)

<img src=https://user-images.githubusercontent.com/27239435/177051162-47a22f53-0f46-4bf2-88a7-cdcb2a86ea82.png></img>

**Comment by lavavex** [comment]
I guess I should close the issue… oops!
