### ISSUE TITLE
Question : Number of GB used in 1 hour

### ISSUE THREAD

**Issue by michoko999** [moonlight-stream/moonlight-qt#821]
Hello, I have a question regarding moonlight's data usage.
In 1 hour of play at 1080p 60fps, how many GB will moonlight take ?

**Comment by cgutman** [comment]
It depends on the bitrate you choose. The rough calculation is the video bitrate (in megabits per second) you pick multiplied by the  length of time you play. Add another 3 Mbps or so to account for audio and input and it's probably around the right number.

At the default 20 Mbps setting for 1080p 60 FPS that would be: (20 Mbps + 3 Mbps) * 3600 seconds in an hour / 8 bits in a byte =  10350 MB per hour / 1024 MB per GB = 10.1 GB per hour
