### ISSUE TITLE
Android connexion terminated crash

### ISSUE THREAD

**Issue by Arkzack** [moonlight-stream/moonlight-qt#823]
**Describe the bug**
On android moonlight, I clic on my game, the stream start, but after 10 second, the connexion crash, it say "connexion terminated" "connexion interrupted"
I have turned off firewall, hw gpu scheduling and reinstalled gfe and it doesnt work

**Steps to reproduce**
Just launch game on android moonlight

**Screenshots**
Just a message no screenshot needed

**Affected games**
All game

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?
- Android

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- yes
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?
- Yes

**Client PC details (please complete the following information)**
Galaxy tab s7
 - OS: [android]
 - Moonlight Version: 10.6

**Server PC details (please complete the following information)**
 - OS: [Windows 11]
 - GeForce Experience version: [3.25.1.27]
 - Nvidia GPU driver: [516.59]
 - Antivirus and firewall software: [Windows Defender and Windows Firewall]

**Moonlight Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux with the Flatpak, logs print to the terminal when running with the command: `flatpak run com.moonlight_stream.Moonlight`
- On Linux with the Snap, logs print to the terminal when running with the command: `moonlight`

**Additional context**
Anything else you think may be relevant to the issue

**Comment by cgutman** [comment]
This tracker is for the PC client. Please file an issue on the Android client bug tracker - https://github.com/moonlight-stream/moonlight-android
