### ISSUE TITLE
How to detect new computer at launch time instead of adding manually on GUI

### ISSUE THREAD

**Issue by rkokkili** [moonlight-stream/moonlight-qt#824]
I have a requirement to add new PC at application launch time instead of adding from moonlight GUI after application is launched.
For that, I added first line in visibility as below. How to trigger pairing a computer also from the code. I am fine to hardcode or read it from some file. Can you please suggest where to add.

Code snippet of main.qml

```
visibility: {
        ComputerManager.addNewHostManually("xxx.xxx.xxx.xxx")

        //pairing call

        if (SystemProperties.hasDesktopEnvironment) {
            if (StreamingPreferences.uiDisplayMode == StreamingPreferences.UI_WINDOWED) return "Windowed"
            else if (StreamingPreferences.uiDisplayMode == StreamingPreferences.UI_MAXIMIZED) return "Maximized"
            else if (StreamingPreferences.uiDisplayMode == StreamingPreferences.UI_FULLSCREEN) return "FullScreen"
        } else {
            return "FullScreen"
        }
    }
```

I also want to add below code which is taken from PcView.qml. Can you please suggest how to make it compilable?

```
if (!model.busy) {
        var pin = computerModel.generatePinString()

        // Kick off pairing in the background
        computerModel.pairComputer(index, pin)

 }
```

**Comment by cgutman** [comment]
This is now supported in v4.2.0 via the command line pairing options.
