### ISSUE TITLE
New computer registration port and pin verification port are different

### ISSUE THREAD

**Issue by rkokkili** [moonlight-stream/moonlight-qt#826]
While registering a computer manually from GUI, it is generating a port 47989 and the same is used for pairing, Whereas PIN verification url has 47990 i.e. port https://xxx.xxx.xxx.xxx:47990/pin. How to maintain the port same in both the places?

**Comment by cgutman** [comment]
TCP port 47989 is a GameStream port used for server info and pairing. 47990 is the administrator GUI port for Sunshine (not related to Moonlight). They are completely different use cases (one is for Moonlight to connect, the other is for a user to connect in a browser), so they are handled separately.

I suggest following up with the Sunshine developers if you want to try to script the pairing process.
