### ISSUE TITLE
Question (not a bug) : performance on 4k@60 fps with raspberry pi 4

### ISSUE THREAD

**Issue by nicolaspernoud** [moonlight-stream/moonlight-qt#831]
Hello

Thanks for that amazing work !
I am using moonlight QT on a Raspberry Pi 4 with LibreElec 10.0.2, with the launcher https://github.com/veldenb/plugin.program.moonlight-qt.
I enabled the following options in config.txt :
```
hdmi_enable_4kp60=1
dtoverlay=rpivid-v4l2
dtoverlay=vc4-kms-v3d
gpu_mem=256
```

Performance is somewhat OK with 4K@30fps but 4k@60 fps produces image drops that make games unplayable.

Is that normal (i.e. the Pi4 is not powerful enough), or am I missing something ?

Best regards.

**Comment by cgutman** [comment]
Supposedly the Pi 4 can do 4K60. You could try lowering the bitrate to see if that's the issue.

You might also check `dmesg` while streaming. I've seen issues in the past where the kernel would complain about running out of memory while decoding 4K content.

**Comment by nicolaspernoud** [comment]
Well, lowering the bitrate helps a little bit (and since there is a 1Gb wired connection between the PC and the RPi4; that is not a network issue).
Increasing the video memory to 512 Mb helps a bit too, but that is still sluggish anyway. More (up to 1024) does not seems to help.
dmesg gives the following error while streaming : 
```
[  183.004616] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.068858] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.136086] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.190392] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.237974] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.302716] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.370230] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.422374] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.471650] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.534995] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.603523] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.656196] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
[  183.702294] cma: cma_alloc: alloc failed, req-size: 3060 pages, ret: -12
```
Normal memory consumption is low : about 2.5 % (of 3,5 Gb).

**Comment by cgutman** [comment]
I think CMA is different than GPU memory. You need something like `dtoverlay=vc4-kms-v3d,cma-512` to increase the size of the CMA region.

**Comment by nicolaspernoud** [comment]
Ok, that is actually the libreelec default. The error disappears, but it is still sluggish. I needed to set the bitrate down to 30 Mbps to make it kind of work, but the image quality is then not really better than 1080p, at least in motion. So I will stick with 1080p. Anyway, thanks for this very nice project and your insights !
