### ISSUE TITLE
Key presses regularly get spammed or not recognised

### ISSUE THREAD

**Issue by JRPGod** [moonlight-stream/moonlight-qt#836]
I'm not really sure where to start on this issue or where to even narrow it down - Being an issue with the moonlight core, or qt client, or what.

Moonlight-stream used to work capital-p Perfectly for me. Literally zero bugs or issues. Then out of no where one day, with no discernible rhyme or reason, it just stopped working well. All keyboard keystrokes started either lagging going through, or would hang and spam the inputs. This creates issues where, for example, if I am unlucky enough to press Ctrl+N (to open a new explorer window), it would spam this through, open 1289401284 new windows in the span of a second and crash my computer.

I really have no idea where to start on reporting the bug because like I said, it used to never happen and work perfectly, and then seemingly out of no where (didn't update drivers or the client or anything else that day), it just broke. Updating my nvidia drivers, updating moonlight client, or reinstalling the moonlight server protocol has no effect on this.

I even recently installed parsec out of curiosity lately to see if the problem is the same there, and it is not ,parsec works perfectly. But I don't like Parsec, I LOVED moonlight when it worked properly and would give anything to have it work correctly again.

Any ideas? Or anyone reported something similar? I've gone through the list of github issue and googled hanging issues with keys but was not able to find anything that matched my issue.

Thanks so much for anything you could suggest that might solve this!

**Comment by cgutman** [comment]
Please provide the information requested in the issue template: https://github.com/moonlight-stream/moonlight-qt/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Logs in particular may shed some light on the situation. Can you bring up the performance statistics overlay and see if you see any changes in network latency and/or variance during the issues?

**Comment by JRPGod** [comment]
Just wanted to shed some light: I never saw anything that stood out in the performance statistics, variance and jitter were always 0-1, it never reported dropping frames, seemed like a perfectly fine connection there.

This issue resolved itself upon purchasing a new SSD for unrelated reasons. My system drive was essentially full and needed to purchase a new one (120gb to 1tb): Moonlight works perfectly again now and I have uninstalled Parsec due to it sucking comparatively again.
