### ISSUE TITLE
Graphical Glitch 

### ISSUE THREAD

**Issue by rogeriskira** [moonlight-stream/moonlight-qt#84]
**Describe the bug**
I notice when moving my windowed application that the colors shift as I move the window around. I also noticed that it happens in Firefox while browsing the color shifts as I move the mouse around.

**Steps to reproduce**
The steps to reproduce would be to move windows around while on your desktop and notice the colors shift.

Host PC:
GTX 1070
i7700hq
Geforce 3.14

Client PC:
 - OS: Windows 10 1803
 - Moonlight Version: [e.g. v0.5.1beta2]
 - Intel i5 7200u (Driver 6286)
Moonlight Settings:
Video decoder: Force Hardware Decoding
Video Codec : Force HEVC
[Moonlight-1537366681.log](https://github.com/moonlight-stream/moonlight-qt/files/2397470/Moonlight-1537366681.log)

![error](https://user-images.githubusercontent.com/42848313/45759881-e863be80-bbf6-11e8-9e8f-1ad7552cf548.png)

**Comment by cgutman** [comment]
I think this is due to Intel's video processing effects. I will see if I can avoid Moonlight's video being affected by them.

Can you try Force H.264 to see if it's also affected?

Can you also try adjusting/disabling any video processing options in the Intel GPU Control Panel?

**Comment by rogeriskira** [comment]
You are 100% correct. I found the fix under Intel HD Graphics Control Panel. If you go to Video>Image Enhancement>Contrast Enhancement and change it to Disable it should now stop producing those Graphical glitches. 
![fix](https://user-images.githubusercontent.com/42848313/45840708-b9784600-bce5-11e8-8680-3e78ee5af52f.jpg)

**Comment by cgutman** [comment]
I don't see a way that I can opt out of image processing as an application developer, so I'm closing this as a driver issue.
