### ISSUE TITLE
When mouse move to EditText,the mouse will be hide.

### ISSUE THREAD

**Issue by yoystar** [moonlight-stream/moonlight-qt#844]
I connect from Mac( or Android)  to PC(RTX3060 )  with moonlight(4.1.0),  When mouse move to EditText , the mouse will be hide,it become unvisible,but it can still edit text .If  I move mouse outside EditText,the mouse will be visible .
How can I do for this problem?

https://user-images.githubusercontent.com/3192752/184164982-cfa65234-51e0-417a-ad3a-74a9fb585250.mp4

**Comment by cgutman** [comment]
Please provide information on the GeForce Experience version, Nvidia driver version, Windows version, and whether the system is High DPI.

**Comment by skarekrow** [comment]
@cgutman I see this as well on anything that has an edit text field like Notepad, Notepad++, VS Code, etc. System specs are the same as I posted here: https://github.com/moonlight-stream/moonlight-qt/issues/853#issue-1345410582

**Comment by cgutman** [comment]
This is a GeForce Experience bug. The cursor works correctly with Sunshine.

**Comment by yoystar** [comment]
Thanks.It does works with Sunshine.> This is a GeForce Experience bug. The cursor works correctly with Sunshine.
