### ISSUE TITLE
H264 with Full KMS

### ISSUE THREAD

**Issue by Silent-Hunter** [moonlight-stream/moonlight-qt#848]
**Is your feature request related to a problem? Please describe.**
Raspberry Pi OS has updated, and now the FKMS driver doesn't work correctly anymore, the mouse is jumpy and sluggish.

**Describe the solution you'd like**
Is it _ever_ going to be possible to add H264 support with Full KMS? H265 with rpivid looks blurrier than H264, especially when streaming Minecraft.

**Describe alternatives you've considered**
I've attempted to find _some_ way to fix this issue with the new update, but I can't seem to do anything to fix it.

**Comment by cgutman** [comment]
H.264 is already supported under Full KMS using the steps in the "Workarounds for incompatible software (Kodi v19+)".

https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4#raspbian-bullseye

**Comment by Silent-Hunter** [comment]
Unfortunately the v4l2m2m thing has much worse performance than just an extra couple frames of latency as mentioned in the documentation, it's very choppy and has severe input lag.

I did mention on the RPi forums that FKMS is broken, but there was mention of it being deprecated, so I don't expect them to fix it.

**Comment by cgutman** [comment]
You might be stuck with rpivid then. I had a chat with one of the Raspberry Pi developers about issues with H.264 decoding on Full KMS here: https://github.com/jc-kynesim/rpi-ffmpeg/pull/25

We ultimately reached a conclusion that it's not possible to have H.264 latency as low as HEVC without using MMAL (which requires FKMS).

**Comment by Silent-Hunter** [comment]
I see! Well fortunately, I'm stuck at 1024x768@85Hz now because my monitor doesn't report that it supports 1600x1200@65Hz. I was using xrandr to force it but I can't figure out how to do that with EGLFS. I say fortunately because HEVC looks a bit better at that lower resolution.

Another upside is with HEVC and EGLFS, Moonlight no longer crashes randomly.
