### ISSUE TITLE
Is there a way to turn off automatic mouse acceleration?

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#849]
Every time I connect with Moonlight, GFE seems to enable mouse acceleration again. Is there a way to disable that? Or some macro you could execute or powershell?

**Comment by cgutman** [comment]
The FAQ has an entry for this:  https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-does-my-hosts-mouse-acceleration-change-while-streaming

There are some host-side workarounds to change the value back (mentioned in #513), but unfortunately GeForce Experience just seems to do this by default with no way to opt-out from the client-side.
