### ISSUE TITLE
moonlight-qt nightly crashes 

### ISSUE THREAD

**Issue by ermac500** [moonlight-stream/moonlight-qt#856]
hey,
this isn't the first time I'm coming with this. I always like to use and test the latest version of Moonlight.
Since yesterday the nightly version crashes with no error, actually better said it doesn't even open. 
only generates a log and a dmp whchi I have attached.

Hope you can fix it again. thx!

[Moonlight-1661229092.zip](https://github.com/moonlight-stream/moonlight-qt/files/9399398/Moonlight-1661229092.zip)
.

**Comment by cgutman** [comment]
Thanks for the report. I see SDL is crashing in the gamepad code.

Do you have any gamepads connected? If so, what kind?

**Comment by ermac500** [comment]
yes. Dual Shock 4 v2 controller.
But I'm also using DS4Windows from Ryochan and it may pass as an Xbox Controller in moonlight.

**Comment by ermac500** [comment]
seems to work if I close DS4Windows, but I need my macros :(

**Comment by cgutman** [comment]
Added a workaround in the latest nightly to avoid WGI - https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/44605594/job/txjne28f146pf0bt/artifacts
