### ISSUE TITLE
Portable version still writes and leaves data in \user\(username)\AppData\Local\Moonlight Game Streaming Project

### ISSUE THREAD

**Issue by somerandomperson123** [moonlight-stream/moonlight-qt#86]
The portable version of Moonlight Gamestream writes and leaves data (.qlmc files) in 
"\user\(username)\AppData\Local\Moonlight Game Streaming Project\Moonlight\cache\qmlcache

Not sure if it's possible to also have this moved to the install folder?

**Comment by cgutman** [comment]
Confirmed locally
