### ISSUE TITLE
Macbook m1 16" Full-screen wrong Position

### ISSUE THREAD

**Issue by ScriptType** [moonlight-stream/moonlight-qt#861]
**Describe the bug**
If you use Moonlight in Full-screen on a macbook m1 16" with an 16:10 Resolution (1920x1200 or 3456x2160 for example)
the Image/Stream doesn't start from the bottom its up 30-40 pixels which results in that the notch at the top isn't fully hidden.

**Steps to reproduce**
Set Moonlight to Full screen

**Screenshots**
this is how it looks like in Fullscreen
![bugged](https://user-images.githubusercontent.com/59615891/187094430-ef9bba47-4cb6-4bda-b742-fec277048423.jpeg)

and this is how it looks in borderless (both same resolution)
![notbugged](https://user-images.githubusercontent.com/59615891/187094437-3648fa3e-a9bd-434a-be38-ee8359f45170.jpeg)

**Client PC details (please complete the following information)**
 - OS: Mac OS 12.5
 - Moonlight Version: 4.10
 - GPU: m1 Pro

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - GeForce Experience version: 3.25.1.27
 - Nvidia GPU driver: 516.94

**Comment by cgutman** [comment]
Can you double-check with a nightly build to ensure it wasn't fixed in the latest SDL update? https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/44600131/job/24dvpv0ni7ekqsr9/artifacts

Also was there a reason you picked full-screen instead of borderless windowed on macOS? Borderless windowed should basically be superior to full-screen in every way on macOS (proper support for window switching trackpad gestures, working volume/brightness overlay, notifications can appear while streaming, etc).

**Comment by ScriptType** [comment]
Tested it with the nightly build still the same problem :/,
Uhm I tried Full-Screen because of this
"Behavior Changes:

Moonlight can now reduce the client display resolution in full-screen mode if the current display mode doesn't have a high enough refresh rate for the selected stream frame rate
"

I liked the idea of a dynamic resolution.

**Comment by Proryanator** [comment]
Same here, would be nice to have the moonlight client fill up the whole screen space when game streaming.

**Comment by Foul-Tarnished** [comment]
fullscreen crash for me on nighty, while borderless doesn't show notch at all

I can't use lowdpi res (half), because without the notch I don't know the vertical res

please either fix fullscreen, or make borderless work with notch visible (no black bar)

**Comment by 1PercentSync** [comment]
> fullscreen crash for me on nighty, while borderless doesn't show notch at all
> 
> I can't use lowdpi res (half), because without the notch I don't know the vertical res
> 
> please either fix fullscreen, or make borderless work with notch visible (no black bar)

You can calculate the effective display space (the part without the notch) of all MacBooks with a notch by the horizontal resolution. The ratio is 16:10. For the 14-inch and 16-inch MBP, it is 74 pixels, and for the 13-inch and 15-inch MBA, it is 64 pixels.

**Comment by cgutman** [comment]
This should be fixed in the latest nightly build.

You can test it from here: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/49795697/job/q2f3adjbrm2uhjap/artifacts
