### ISSUE TITLE
Sometimes freezes when quitting stream on Raspberry Pi 4 with HEVC

### ISSUE THREAD

**Issue by Silent-Hunter** [moonlight-stream/moonlight-qt#863]
**Describe the bug**
When exiting the stream using either Ctrl+Alt+Shift+Q or shutting down my PC, sometimes the entire system locks up. I can't even ssh into it. I can however still hear sounds from the PC, like the stream is still running but audio only.

**Steps to reproduce**
Run moonlight-qt with Full KMS and HEVC on Raspberry Pi 4 from the console.

**Affected games**
Minecraft, Mass Effect 3, plain Windows Desktop

**Moonlight settings (please complete the following information)**
Forced HEVC and forced hardware decoding. Also set to native resolution of display (Using official touchscreen, 800x480). Problem still occurs with default settings.

**Client PC details (please complete the following information)**
 - OS: Raspberry Pi OS Lite, Linux Kernel 5.15.61-v8+
 - Moonlight Version: 4.1.0
 - GPU: VideoCore 4 (I think?)

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro 21H1 build 19043.1889
 - GeForce Experience version: N/A (I'm using Sunshine with an AMD RX590)
 - Nvidia GPU driver: N/A (AMD driver version is 22.8.2)
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Moonlight Logs (please attach)**
Cannot provide logs as entire system freezes and must be unplugged and plugged back in to reset.

**Comment by cgutman** [comment]
I think this is fixed by the Pi's 6.1 kernel update and new FFmpeg in the latest moonlight-qt v4.3.1-3 package. Reopen if not.

**Comment by Silent-Hunter** [comment]
Unfortunately this still seems to happen. It seems to only happen when playing for a while, but I'm not sure. The odd thing is, usually when it happens I can use SysRq+K to forcibly kill it and then SysRq+V to get my login prompt back, but just now even that did not work. SysRq+B did, though.

**Comment by Silent-Hunter** [comment]
No, it definitely is still doing it on both kms and fkms.

**Comment by Silent-Hunter** [comment]
This is unfortunately still happening.
