### ISSUE TITLE
Moonlight-qt segfaults on LibreELEC

### ISSUE THREAD

**Issue by veldenb** [moonlight-stream/moonlight-qt#868]
Moonlight-qt segfaults on LibreELEC, reporting as requested.

**Steps to reproduce**
- Install https://github.com/veldenb/plugin.program.moonlight-qt on LibreELEC
- Remove the version constraint in `/storage/.kodi/addons/plugin.program.moonlight-qt/resources/build/rpi/Dockerfile`
- Install the latest moonlight-qt by starting the plugin config panel and update moonlight-qt
- Start Moonlight from the plugin menu
- Connect to PC
- Start a stream
- Moonlight-qt segfaults

**Client PC details**
 - OS: LibreELEC 10 (Pi 4)
 - Moonlight Version: 4.2.1-1
 - GPU: Pi4

**Server PC details**
 - OS: Windows 10
 - GeForce Experience version: 3.25.1.27
 - GPU: Nvidia Geforce 3080

**Moonlight Logs**
GDB Stacktrace: [Moonlight_2.4.1_trace.txt](https://github.com/moonlight-stream/moonlight-qt/files/9556456/Moonlight_2.4.1_trace.txt)

See also https://github.com/veldenb/plugin.program.moonlight-qt/issues/20

**Comment by cgutman** [comment]
Hmm, is your OpenGL implementation working?

It's crashing on https://github.com/libsdl-org/SDL/blob/228b9fb5178405138775db55b28a6b6e787d8ce0/src/render/opengl/SDL_render_gl.c#L1720 which means `glGetString(GL_RENDERER)` returned `NULL`. SDL should probably have some error checking there, but it's also very strange to hit that failure case anyway.

**Comment by veldenb** [comment]
@cgutman  LibreELEC is very bare bones so it could be missing a library for that. Do you know the name of the library that should handle this call? 
For rendering EGL is used but I'm not sure if that should make a difference.

**Comment by veldenb** [comment]
@cgutman I think you are correct about the OpenGL part: https://forum.libreelec.tv/thread/2520-opengl-meson-and-glu-packages/?postID=20143#post20143

It looks like LibreELEC builds it's ARM images without OpenGL and only OpenGLES. So no OpenGL at all.
Do you think a workaround may be possible? On moonlight-qt 4.1.0-1 this problem does not occur.

**Comment by veldenb** [comment]
Digging through moonlight's source code shows that this commit adds the call to the software renderer: https://github.com/moonlight-stream/moonlight-qt/commit/9daf7b5a362f2aff90e61ad16f8390ec637e5f5b

The commit fixes modesetting for non-EGL HEVC streams, but since the Pi4 uses EGL and HEVC this piece may be skipped for systems using EGL and HEVC?

**Comment by veldenb** [comment]
Continuing my monologue :)
I disabled the code from https://github.com/moonlight-stream/moonlight-qt/commit/9daf7b5a362f2aff90e61ad16f8390ec637e5f5b using this patch:  [moonlight.patch.txt](https://github.com/moonlight-stream/moonlight-qt/files/9579263/moonlight.patch.txt)

After patching and compiling for the Pi 4 moonlight 4.2.1 runs with SDL 2.24.0 on LibreELEC 10.
I don't know if this patch breaks things for other systems (I'm not a C developer) but on the Pi running EGL it works very well including HDR: [moonlight-qt.log](https://github.com/moonlight-stream/moonlight-qt/files/9579271/moonlight-qt.log)

Is it possible to include this change in the next moonlight release?

**Comment by cgutman** [comment]
No, we do actually need that call in order to get proper modesetting in some cases, in particular to handle the case where we need to switch from 4K30 to 1080p60.

What happens if you set the `SDL_RENDER_DRIVER` environment variable to `opengles2`?

**Comment by veldenb** [comment]
`export SDL_RENDER_DRIVER="opengles2"` makes the segfault go away :)

Starting the stream now works. But sometimes (I think after switching modes on the Game PC side) the stream gets really laggy (like 2fps) and the moonlight-qt log rapidly fills up with these messages:
```
00:16:42 - FFmpeg: Failed to alloc 7467008 from dma-heap(fd=24): 12 (Cannot allocate memory)
00:16:42 - FFmpeg: [hevc @ 0x34b87d0] v4l2_request_hevc_start_frame: Failed to get dst buffer
00:16:42 - FFmpeg: [hevc @ 0x34b87d0] Error parsing NAL unit #0.
00:16:42 - SDL Warn (0): avcodec_send_packet() failed: Cannot allocate memory
00:16:42 - SDL Info (0): Requesting IDR frame on behalf of DR
00:16:42 - SDL Info (0): IDR frame request sent
00:16:42 - SDL Info (0): Set display HDR mode: disabled
```

dmesg:
```
[ 8709.518528] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.536769] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.553148] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.586822] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.601136] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.617535] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.634676] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.683420] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.716336] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.734914] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
[ 8709.751196] cma: cma_alloc: alloc failed, req-size: 1823 pages, ret: -12
```

Because of the HDR I run full KMS: `dtoverlay=vc4-kms-v3d,cma-512` so it might be a kernel issue. Reconnecting fixes the lag.

I'll try a run with Fake KMS to see if the problem persists.

**Comment by veldenb** [comment]
Pinned down the memory issues above. It only occurs when hopping in and out of HDR games by streaming Steam Big Picture.
Turning off HDR in moonlight makes the errors disappear so I think it's unrelated.

I'll add the env-var to the plugin as a workaround for now.

**Comment by cgutman** [comment]
> Pinned down the memory issues above. It only occurs when hopping in and out of HDR games by streaming Steam Big Picture.
Turning off HDR in moonlight makes the errors disappear so I think it's unrelated.

Yep, I've seen that too. I'm not sure if that's a bug in Moonlight or something else. I'm tempted to think FFmpeg or the V4L2 driver, since we don't see leaks when transitioning between HDR and SDR on any other platforms.

**Comment by veldenb** [comment]
Do you want to close this issue er keep it open to implement an error message for the situation?
The workaround is a workable solution for me, I implemented it in the plugin.
