### ISSUE TITLE
Host PC does not appear in PC view, after enabling Gamestream in host PC

### ISSUE THREAD

**Issue by jhakonen** [moonlight-stream/moonlight-qt#88]
**Describe the bug**
New host PC is not added to PC view while Moonlight is running and Gamestream is enabled from the host PC's GFE settings.

**Steps to reproduce**
1. Turn off Gamestream from host PC
2. Delete host PC from Moonlight's PC view (with e20bf3f "Fix persistence of deleted PCs." commit included)
3. Restart Moonlight, the host PC does not appear in PC view
4. Turn Gamestream on from host PC's GFE settings
5. Wait for it... many, many, minutes... Host PC refuses to appear in the PC view

**Moonlight settings (please complete the following information)**
Using default settings

**Client PC details (please complete the following information)**
 - OS: Windows 10 1803
 - Moonlight Version:
    - Self compiled debug build v0.5.1 @ revision 2c96005, compiled with MSVS2017 x64 compiler/linker
    - Tried also with official 0.5.1 release version, with same results

 - GFE version: 3.15.0.164

**Additional context**
Roughly 10 seconds after turning Gamestream on, application output in QtCreator shows messages:
```
Discovered mDNS host: "Pelikone.local."
Resolved "Pelikone.local." to "192.168.1.22"
Processing new PC at "192.168.1.22" from mDNS
Loaded unique ID from settings: "34dbc0ccd7e2d32"
Executing request: "https://192.168.1.22:47984/serverinfo?uniqueid=34dbc0ccd7e2d32&uuid=eeb63a4f7e9f42e19799029ef2de5b56"
"serverinfo"  request failed with error  QNetworkReply::NetworkError(ServiceUnavailableError)
Exception at 0x7ff8913da388, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at c:\tiedostot\henkilokohtainen\projektit\moonlight\moonlight-qt\app\backend\nvhttp.cpp:424
Exception at 0x7ff8913da388, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at c:\tiedostot\henkilokohtainen\projektit\moonlight\moonlight-qt\app\backend\nvhttp.cpp:98
```
It seems that when PendingAddTask::run() calls http.getServerInfo() it fails due to the ServiceUnavailableError error. Modifying the surrounding code to add a retry seems to fix this issue:
```
        QString serverInfo;
        for (int i = 0; i < 5; i++) {
            try {
                serverInfo = http.getServerInfo(NvHTTP::NvLogLevel::VERBOSE);
                break;
            } catch (...) {
                std::this_thread::sleep_for(std::chrono::milliseconds(1000));
            }
        }
        if (serverInfo.isEmpty()) {
            if (!m_Mdns) {
                emit computerAddCompleted(false);
            }
            return;
        }
```
I'm not just sure if this the correct way to fix this.

**Comment by cgutman** [comment]
Can you capture a Wireshark trace from the client PC to see what's happening on the network?

Can you also upload the log from 0.5.1 (which includes timestamps) so I can get an idea of how long the request took to fail?

**Comment by jhakonen** [comment]
Right, logs are attached: [Captured logs.zip](https://github.com/moonlight-stream/moonlight-qt/files/2408580/Captured.logs.zip)

I've also included gaming PC's wireshark trace. Clocks on the computers are almost in sync, with 1-3 sec difference. I reproduced the issue using the official 0.5.1 release. Started wireshark tracing on both PCs before step 4, and then turned Gamestream on. Which happended at 08.32.40 UTC or so.

Some IP addresses in case they have use for looking at the logs:
* 192.168.1.22 = PELIKONE (with GFE)
* 192.168.1.61 = Eve V (with Moonlight)
* 192.168.1.1 = Router (RT-AC86U)

I've also disconnected all other devices, except internet modem, from the network to reduce traffic.

**Comment by cgutman** [comment]
Can you also upload C:\ProgramData\NVIDIA Corporation\nvstreamsvc\nssCurrent.log after your scenario?

**Comment by cgutman** [comment]
Nevermind, I was able to reproduce this myself.

The interesting log entries from nssCurrent.log seem to be:
```
#8(D)[2018-09-29 09:36:31,244]=02:36:31={0000068C}<Mongoose>         /serverinfo
#9(D)[2018-09-29 09:36:31,244]=02:36:31={0000068C}<MongooseMongoose> MongooseHttpServerInternal::InvokeHandler: ssl = 000000DCEBED1FB0
#0(D)[2018-09-29 09:36:31,244]=02:36:31={0000068C}<OpenSSLCertUtils> OpenSSLCertUtils::GetPeerCertificate is called. ssl: 000000DCEBED1FB0
#1(D)[2018-09-29 09:36:31,244]=02:36:31={0000068C}<MongooseMongoose> ClientCert retrieved in SSL handshake
#2(W)[2018-09-29 09:36:31,245]=02:36:31={0000068C}<NetworkStreamSer> Server is offline, returning service unavailable error
#3(D)[2018-09-29 09:36:31,245]=02:36:31={0000068C}<MongooseMongoose> Successfully sent the response back the the client.
```

I will retry specifically if the server returns ServiceUnavailableError

**Comment by jhakonen** [comment]
Tried with latest master. Seems ok. Can't reproduce. 👍
