### ISSUE TITLE
Can't get moonlight to stream using KMS instead of FKMS on RPI4b

### ISSUE THREAD

**Issue by MwenDavo** [moonlight-stream/moonlight-qt#907]
**Describe the bug**
Following the installation guide for RPI4 (https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4) I've managed to successfully install and run the app itself. But, as the wiki states, if I use KMS on Bullseye, I get a black screen on streaming. If I change it to FKMS, It works, but I don't have access to HDR. While all that is nothing new, if I switch to Buster, I get exactly the same behaviour.

**Steps to reproduce**
Just follow the install guide linked before.

**Client PC details (please complete the following information)**
 - OS: Raspberry Pi OS (Tested on both Buster and Bullseye)
 - Moonlight Version: 4.3.1
 - GPU: Integrated GPU

**Server PC details (please complete the following information)**
 - OS: Windows 10 22H2
 - GeForce Experience version: 3.26.0.154
 - Nvidia GPU driver: 527.37
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Comment by cgutman** [comment]
Can you attach the moonlight log output?

**Comment by MwenDavo** [comment]
Ended up copy-pasting the console output, hope it works.
[moonlight-log.txt](https://github.com/moonlight-stream/moonlight-qt/files/10181548/moonlight-log.txt)

**Comment by cgutman** [comment]
Hmm, that is pretty strange. I'm not sure if this is the actual issue but something appears to be causing a hang in video decoding.

The end of the log is full of this over and over:
```
00:03:22 - SDL Info (0): Video decode unit queue overflow
00:03:22 - SDL Info (0): IDR frame request sent
00:03:22 - SDL Info (0): Waiting for IDR frame
00:03:23 - SDL Info (0): Video decode unit queue overflow
00:03:23 - SDL Info (0): IDR frame request sent
00:03:23 - SDL Info (0): Waiting for IDR frame
00:03:23 - SDL Info (0): Video decode unit queue overflow
00:03:23 - SDL Info (0): IDR frame request sent
00:03:23 - SDL Info (0): Video decode unit queue overflow
00:03:23 - SDL Info (0): IDR frame request sent
00:03:23 - SDL Info (0): Waiting for IDR frame
00:03:23 - SDL Info (0): Video decode unit queue overflow
00:03:23 - SDL Info (0): IDR frame request sent
```

That's saying that the video decoder isn't consuming frames, so too many frames are building up.

To try to get more info, please try running these steps:
1. Run `apt install moonlight-qt-dbgsym` over SSH
2. Run `gdb --args moonlight-qt` over SSH
3. Start streaming and then press Ctrl+Alt+Shift+Q to quit. You should see a bunch of those "Video decode unit queue overflow" messages.
4. Press Ctrl+C in your SSH session to enter the debugger prompt
5. Run `thread apply all bt` at the debugger prompt and attach that output here.

**Comment by MwenDavo** [comment]
Seems like I can't get past the second item. After I type that command moonlight-qt doesn't start, and the SSH terminal stays waiting for input. The output of the gdb command is:

> admin@raspberrypi:~ $ gdb moonlight-qt
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from moonlight-qt...Reading symbols from /usr/lib/debug/.build-id/03/a2cd557be464055eff13b935390abb38cf147d.debug...done.
done.
(gdb)

**Comment by cgutman** [comment]
ah, type `r` at the prompt and press enter.

**Comment by MwenDavo** [comment]
Here it is.
[gdb_output.txt](https://github.com/moonlight-stream/moonlight-qt/files/10233581/gdb_output.txt)

**Comment by MwenDavo** [comment]
Seems like I found the problem: it was the HDMI cable I was using. It was an old cable that didn't support more than 1080p60, and I was forcing it to 1440p or 4k. After swapping the cable for one that supports 4k30, everything went smooth. Before closing the issue, I'd like to know if I can use Raspbian Bullseye instead of Buster and still get both HDR an HEVC, mainly because of the newer kernel wich allows me to use my Dualsense's touchpad as a mouse.

**Comment by cgutman** [comment]
> Seems like I found the problem: it was the HDMI cable I was using. It was an old cable that didn't support more than 1080p60, and I was forcing it to 1440p or 4k. After swapping the cable for one that supports 4k30, everything went smooth

Ah, that makes sense. That would explain why nothing seemed wrong in the logs. Maybe `dmesg` would have said something...

> Before closing the issue, I'd like to know if I can use Raspbian Bullseye instead of Buster and still get both HDR an HEVC, mainly because of the newer kernel wich allows me to use my Dualsense's touchpad as a mouse.

Yeah, Bullseye should be fine. I've been running it since it came out and HDR works fine for me.
