### ISSUE TITLE
Include the latest SDL2 framework in the macOS build

### ISSUE THREAD

**Issue by raznoraznidzank** [moonlight-stream/moonlight-qt#909]
**Is your feature request related to a problem? Please describe.**
The SDL2 framework binary files included in the downloadable macOS images are a number of months old. The latest SDL2 libraries from the SDL site contain, among others, gamepad controller updates which support the Nintendo Switch Joy-Cons much better than the previous versions of the library (all buttons on the controller are supported in all modes).

**Describe the solution you'd like**
Include the latest SDL2 framework binaries in the downloadable macOS version of Moonlight.

**Describe alternatives you've considered**
Compiling Moonlight with the latest SDL2 library works well and fully supports Nintendo Joy-Cons. SDL2 library from the latest Moonlight macOS binaries on the site doesn't support all Joy-Con buttons in all modes.

**Additional context**

**Comment by cgutman** [comment]
Does the latest nightly build work? https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/45530096/job/rhonf574puhcc7tr/artifacts
