### ISSUE TITLE
Mouse button 4 and 5?

### ISSUE THREAD

**Issue by lateforwork1000** [moonlight-stream/moonlight-qt#91]
Would it be possible to add the mouse buttons 4 and 5? (the forward and back buttons)

**Comment by cgutman** [comment]
Last time I tried to support these additional buttons, sending them to the host did nothing. I went back to try this again today to make sure, but this time it does look like the forward and back buttons work. They will work in the next release.

**Comment by slrgt** [comment]
how do you get it to work? mouse 4 and 5 dont do anything for me

**Comment by Incubaitor** [comment]
Having the same issue, the buttons don't get transferred.
