### ISSUE TITLE
HEVC Hardware Decoding Broken with Flatpak Versions 4.3.x (Steam Deck and Linux users)

### ISSUE THREAD

**Issue by Nonary** [moonlight-stream/moonlight-qt#911]
**Describe the bug**
Updating passed 4.2.1 on Flatpak will cause the HEVC decoding to break and display a message that the device does not support decoding and may run into performance issues. When starting a stream, it will default to h264 hardware decoding. This will not affect software decoding options, but this is noticeably much slower than hardware decoding.

**Steps to reproduce**
Update the flatpak Moonlight to at least 4.3.0

**Other Moonlight clients**
I've confirmed this happens on multiple linux distros, but you may see more Steam Deck users have this issue since the Steam Deck is popular and also uses flatpak.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? No
- Does the problem still occur after reverting settings back to default? Yes

**Additional context**
Users can workaround the issue by downgrading the flatpak application back to 4.2.1

To downgrade, run this command:
```
flatpak update --commit a8d2468ff28af6f69c663177adab42d5eed00937967c8df7efffcba91ab0a107 com.moonlight_stream.Moonlight
```

If user is using an OS that automatically updates flatpak applications, they should mask the application to prevent it from automatically updating. For steam deck users, this is not required as flatpak applications do not automatically update on SteamOS.

```
flatpak mask com.moonlight_stream.Moonlight
```

**Comment by Nonary** [comment]
@cgutman Interestingly enough, I didn't have to install that extension. It literally just fixed itself and said it was already installed. 
Additionally, I am on 3.4 on Steam Deck and despite the hardware decoding being disabled, it still works with Moonlight as well.

**Comment by cgutman** [comment]
Yeah, my system downloaded `org.freedesktop.Platform.GL.default//22.08-extra` on its own too when I ran `flatpak update`. That wasn't what I thought was supposed to happen, but I'm definitely not complaining.

If it was opt-in as I had expected, that would result in randomly broken hardware decoding for all Flatpak applications on AMD systems after a `flatpak update`. Opt-out makes more sense for ensuring a seamless transition for users.
