### ISSUE TITLE
nVidia gamestreaming to be discontinued mid-february 2023 - impact on moonlight?

### ISSUE THREAD

**Issue by kshots** [moonlight-stream/moonlight-qt#918]
So... nVidia just announced to their shield users that they are discontinuing support for gamestreaming, and that we should start utilizing the "steam link" app. What's the impact on those of us using moonlight?

Source: https://nvidia.custhelp.com/app/answers/detail/a_id/5436

Edit: Discord is likely a better place to discuss this than the bug tracker. Unfortunately, I don't see a way to delete this post, but apparently I can close it...

**Comment by NightHammer1000** [comment]
Time to put some serious work into https://github.com/LizardByte/Sunshine

**Comment by Nonary** [comment]
> There's also [AMD Link](https://www.amd.com/en/technologies/amd-link)

Unfortunately the main issue with AMD Link and other streaming platforms is that they have **significantly** higher display latency.

For example at best, Steam Link has about 80-110ms of extra delay even when using NVFBC.

Geforce Experience had about 25-30ms of latency at 60fps almost 4 times as fast as Steam Link.

Of course if you don't really care about the extra lag, then yeah that will work. I haven't tested AMD link personally but every other streaming product I've tried seems to have way more latency when I run it under a high speed camera test.

**Comment by NightHammer1000** [comment]
And what exactly do you expect everybody to do about this @Nonary ?
We can't do anything about it. GameStream goes away for good.
That's just how NVIDIA is. You just need to take a look at the Gameworks UE4 Github to see that they drop good tech at a moment's notice just for it to never see the light of day again.
And as everything they do is a Blackbox there is no chance for us to get the Source anyway. 
So, the only thing we really can do is Improving on Sunshine or switch to Steam Link entirely. No matter if it has higher latency. Higher Latency is still better than no solution at all.

**Comment by DarkArc** [comment]
I tried Sunshine again last night and honestly, I couldn't tell a difference in PC <-> PC over LAN.

**Comment by DarkArc** [comment]
> I have a black bar on the top and bottom when I use Sunshine but not when I use gamestream for Moonlight on my Steam Deck. My host pc resolution is 1920x1080, and have my Moonlight/Sunshine set to 1280x800.

There's a list of advertised resolutions in sunshine's general config; I'd _guess_ you just need to add 1280x800 there.

**Comment by MakiseKurisu** [comment]
I'm actually excited for this news. Not only now Sunshine will likely get serious development, we can also develop extensions on the original protocol without worrying about compatibility. We could implement clipboard sync and file transfer for example. We can also morph Moonlight into a front end of LookingGlass as well so that project can focus on the back end while we reduce the duplicated codes and works between similar projects.

**Comment by airdjing** [comment]
This is a tragedy. Sunshine is a great app, of course, but it's not comparable to NVIDIA GameStream's reliability (especially when reconnecting) and short latency.

I've also blocked NVIDIA Web Helper on the My firewall setup to prevent GFE updates.
I plan to collect GFE Installer and Game Ready drivers by version until GameStream disappears from GFE.

**Comment by halikular** [comment]
This has to be a joke, if it's true I'm relieved I didn't upgrade yet to their new GPUs. This is unfathomable, NVIDIA game stream IS the best performing solution we have thanks to the their effort and the open source community who built Moonlight, can't thank you enough. This technology has enabled us to not only play our favorite games remotely with the lowest possible latency and image quality with high end desktop hardware on low powered laptops, but also do demanding 3d modelling, animation, video editing, rendering, compiling, playing games while simultaneously streaming to Twitch, YouTube, and your laptop piping its microphone and webcam to your host PC functioning as a dedicated server for your stream in case your summer house internet connection is not stable enough or whatever... Only your creativity sets the limit for what can be done. I can't even begin to describe how disappointed I am. This decision has to be reversed or NVIDIA has to work with the Moonlight team just like they do with the OBS team to ensure continued support and improvements. NVIDIA should know that if they remove game stream there are no longer any unique quality features separating them from Intel, AMD, and Apple.

**Comment by timm052** [comment]
The wording is confusing, are they actually discontinuing it completely? I just reads like they're removing it from the shield TV.

**Comment by dragonballa** [comment]
I'm confused too, what will be the impact without nVidia's gamestreaming stack? People mention sunshine server, does this mean that somebody is going to implement something similar to NVidia?

**Comment by apoklyps3** [comment]
> The wording is confusing, are they actually discontinuing it completely? I just reads like they're removing it from the shield TV.

the feature was build and advertised for their nvidia shield devices. they will not continue to support/work on it for open source alternatives like moonlight. actually I'm impressed they didn't try to block moonlight trough the time.
I thnk this move is done so we all go to their paid service: geforce now. that's not going to happen for me, at least

**Comment by yungleballz** [comment]
Just join the discord and get all your questions answered: https://discord.gg/moonlight-stream-352065098472488960

**Comment by NightHammer1000** [comment]
Man. I really hate how discord always becomes the news hub because Maintainers are too lazy to put stickies up...

**Comment by yungleballz** [comment]
You don't have the slightest idea how much time and effort all the dev's and contributor's are putting in both projects for no compensation at all.
On discord there's a dedicated support team to help finding actual bugs and mostly troubleshooting user specific issues.
Show some respect or go somewhere else.

**Comment by NightHammer1000** [comment]
Gladly. The last thing I need is another useless Discord bombarding me with Pings.

**Comment by yungleballz** [comment]
Good riddance.
For everyone else concerned:
1. there are no pings about anything, you'd have to subscribe to the announcements channel.
2. you can disable pings in discord.

**Comment by cgutman** [comment]
I wrote a FAQ page which can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/NVIDIA-GameStream-End-Of-Service-Announcement-FAQ

For my part, I have spent the last couple of weeks since the announcement working on improving [Sunshine](https://github.com/LizardByte/Sunshine) to become the standard host for Moonlight. The nightly build is pretty good now and will only get better as we go. It will also allow us to enable some features that were previously impossible with GFE (like mic support, AV1, AMD/Intel support, etc).

**Comment by piotrminkina** [comment]
I've been testing AMD Link on the NVidia SHIELD (Android TV) for the last few days and find it poor. I've already made 10 suggestions and problems to AMD with this app (and I have another one I haven't sent yet), as well as the streaming as a whole. 

I gave Sunshine + Moonlight a chance today and so far it is the best combination, even on an AMD Radeon card. A huge round of applause to the authors of Sunshine and Moonlight for their contribution to the development of these applications! Hats off to them!

**Comment by kostrykin** [comment]
How is Sunshine latency compared to Geforce Experience?

**Comment by piotrminkina** [comment]
2k streams about 1-2 ms on network layer (I have 1GbE) and about 1-2 ms decoding on SHIELD. With 4k streams I noticed about 3-5 ms on network layer and still about 2 ms on SHIELD.

On both the Moonlight and Sunshine side, you can configure whether you go for low latency or quality. I put on quality with HDR and got latency as above.

**Comment by yungleballz** [comment]
> How is Sunshine latency compared to Geforce Experience?

Under ideal circumstances (Ethernet, Quicksync decoder) both can be just ~1frame behind the host.
Sunshine allows you to set even faster encoding presets than gfe (P1 ull for example) which could mean that it will be even faster for you.

**Comment by knaos** [comment]
So is there any impact on using this software now?

**Comment by Silent-Hunter** [comment]
I use Sunshine in software encoding mode and it is absolutely _amazing_.

**Comment by Silent-Hunter** [comment]
> I wrote a FAQ page which can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/NVIDIA-GameStream-End-Of-Service-Announcement-FAQ
> 
> For my part, I have spent the last couple of weeks since the announcement working on improving [Sunshine](https://github.com/LizardByte/Sunshine) to become the standard host for Moonlight. The nightly build is pretty good now and will only get better as we go. It will also allow us to enable some features that were previously impossible with GFE (like mic support, AV1, AMD/Intel support, etc).

I do want to say, mic support would be *incredibly* useful for games that need in-game voice (for spatial audio, etc.).

**Comment by kostrykin** [comment]
> > How is Sunshine latency compared to Geforce Experience?
> 
> Under ideal circumstances (Ethernet, Quicksync decoder) both can be just ~1frame behind the host. Sunshine allows you to set even faster encoding presets than gfe (P1 ull for example) which could mean that it will be even faster for you.

Can you elaborate on this a bit please? I googled for "sunshine P1 ull" but couldn't find a thing.

**Comment by yungleballz** [comment]
> Can you elaborate on this a bit please? I googled for "sunshine P1 ull" but couldn't find a thing.
[](https://developer.nvidia.com/blog/introducing-video-codec-sdk-10-presets/)
For help with this, please come to the discord.

**Comment by kostrykin** [comment]
> > Can you elaborate on this a bit please? I googled for "sunshine P1 ull" but couldn't find a thing.
> 
> https://developer.nvidia.com/blog/introducing-video-codec-sdk-10-presets/ For help with this, please come to the discord.

You mean the Moonlight discord or a specific Sunshine discord? I couldn't find a Sunshine discord, although this seems to be rather related to Sunshine than Moonlight.

**Comment by yungleballz** [comment]
> You mean the Moonlight discord or a specific Sunshine discord? I couldn't find a Sunshine discord, although this seems to be rather related to Sunshine than Moonlight.

Moonlight https://moonlight-stream.org/discord
Sunshine https://app.lizardbyte.dev/discord

**Comment by idc77** [comment]
Discord the proprietary, non-private, walled garden.
It should be a no brainer to provide a forum instead of that

**Comment by Silent-Hunter** [comment]
I too dislike that so many projects are using Discord instead of having a forum like used to be common.

**Comment by Silent-Hunter** [comment]
> > Discord the proprietary, non-private, walled garden. It should be a no brainer to provide a forum instead of that
> 
> Yes, a nice walled garden. Where the staff has their tools to help people quickly and thoroughly. Where people that don't behave well get reminded of the rules, so everyone can have a friendly conversation.

While I don't like the rude way others have been saying it, I too dislike Discord immensely, and wish Github had a forum feature similar to how it has a wiki feature. And a forum still has everything you describe here.

**Comment by yungleballz** [comment]
> While I don't like the rude way others have been saying it, I too dislike Discord immensely, and wish Github had a forum feature similar to how it has a wiki feature. And a forum still has everything you describe here.

Don't get me wrong. I understand why people dislike Discord.
But it's where the people are and where we offer support.
~1000 people each month join the server and only 2% of those are "new" Discord accounts.

**Comment by Silent-Hunter** [comment]
> > While I don't like the rude way others have been saying it, I too dislike Discord immensely, and wish Github had a forum feature similar to how it has a wiki feature. And a forum still has everything you describe here.
> 
> Don't get me wrong. I understand why people dislike Discord. But it's where the people are and where we offer support. ~1000 people each month join the server and only 2% of those are "new" Discord accounts.

That's a good point. If Github did start offering a forum service for projects to use, do you think this one would use it? I'm considering putting a feature request to Github's management. (If one can even do such a thing.)

**Comment by yungleballz** [comment]
please consider that everyone is doing what they do for free, during their freetime.
that includes the developers and all the helpers, moderators etc.
having to maintain multiple platforms would be a lot of extra work.

**Comment by SpiralBrad** [comment]
> please consider that everyone is doing what they do for free, during their freetime. that includes the developers and all the helpers, moderators etc. having to maintain multiple platforms would be a lot of extra work.

Maintaining a Discord alongside the GitHub is literally maintaining multiple platforms, so...
