### ISSUE TITLE
Quit session from command line 

### ISSUE THREAD

**Issue by CarloDePieri** [moonlight-stream/moonlight-qt#92]
I think it would really nice to have the option to close the current session from the command line.

We got command line parameters from #89, in the same way we could envision an action in addiction to 'stream' called 'quit' that closes the current session. This would be useful in a scenario where the main gui is not accessed often and sessions with a target application are launched from the command line: once launched a session, we currently can't really close it (which means we can't then launch a second, different session) without opening the main gui first and closing the existing session from there. Having a 'quit' action could allow for easy scripting e.g. close current existing session then launch application X.

Let me conclude by thanking every contributor for the great job so far, this client really is coming together as a nice piece of software!

**Comment by jhakonen** [comment]
Wouldn't it be better if, when you're starting an app from command line, the UI would ask if you want to quit the previously running app first? Then there wouldn't need for scripting this particular situation. It would work right out-of-the-box.

In fact, when you try to start an app from the menu, it already does this. It is just the stream-command that is lacking. Didn't know of that kind of behavior when I implemented the command line arguments.

Do you think that would cover it? Would there still be some other use case which would require the quit action?

**Comment by CarloDePieri** [comment]
For my particular use case this solution would not be... ideal (although it would partially solve the problem and would be better than the current situation).
The workflow I described allows me to treat streamed applications like native ones: thanks to the stream action I can launch them from a command or a desktop launcher, and when I close the window I usually mean to close the session as well, rather than suspend it. I'm already used to this kind of behaviour from other clients that support it (like [moonlight-embedded](https://github.com/irtimmer/moonlight-embedded/wiki/Usage)).
Now that I think of it, another way to solve this would be to have a dedicated shortcut to disconnect from _and_ close the session (unless it's already there and I missed it), but I supposed that would entail another issue altogether.

Again, thank you for your contribution and your quick response.

**Comment by cgutman** [comment]
I think it makes sense to have an option in the preferences (passable via the command line too) to make quitting the stream also terminate the app on the target PC.

I think a quit action is still useful though and probably wouldn't be hard to add to our current launcher code.

**Comment by CarloDePieri** [comment]
> I think it makes sense to have an option in the preferences (passable via the command line too) to make quitting the stream also terminate the app on the target PC.
Would quitting the app close the session? A command line option for the stream action would be ok, eliminating the need to script this behavior!

**Comment by jhakonen** [comment]
Yeah, actually that command line option would be helpful. I could use it too.

**Comment by jhakonen** [comment]
So to recap, the functionality to be added are:
* A checkbox in settings for terminating app on target PC afet quitting session
* Command line arguments for toggling the app termination on/off
* Quit action from command line
* Starting stream from command line would let user to quit currently running app

Was this correct?

**Comment by CarloDePieri** [comment]
I'm not sure how the 4th point is different from the 2nd, but the first three points seems good to me!

**Comment by JuniorJPDJ** [comment]
@CarloDePieri the difference is that one would terminate after quit and second just before start

**Comment by CarloDePieri** [comment]
Oh, so that the first could be used as 'If I'm closing the window, I intend to disconnect' while the second would be used when launching a second application, to close possible pre-existing session. Those would be useful indeed.

**Comment by JuniorJPDJ** [comment]
s/disconnect/quit game on remote
Exactly.

**Comment by jhakonen** [comment]
Here's the pull request which should now implement this:
https://github.com/moonlight-stream/moonlight-qt/pull/138

**Comment by CarloDePieri** [comment]
Seems exactly what I asked for, I'll try it out soon. Thank you for you hard work!

**Comment by VisionaiR3D** [comment]
any way we could quit a session by intent from android?

**Comment by systox** [comment]
running into this issue on steam deck if i launch games directly with CLI parameters.
