### ISSUE TITLE
Moonlight to sunshine with custom portrange

### ISSUE THREAD

**Issue by apoklyps3** [moonlight-stream/moonlight-qt#927]
I'm trying to test Sunshine as a replacement for gamestream, but I can't even get past the pairing phase as it seems moonlight keeps trying to use the default gamestream ports.
the family port I have set in sunshine is 1100.
I have inputed my ip:port in moonlight, but on android I can see a distinct error the client tries to connect to myip:1095from myclientip:45442

**Comment by ermac500** [comment]
if it helps this is from my laptop log. seem to be a different error.
maybe android client does't yet support custom ports with sunshine, but something seems to go wrong eighter way.

[Moonlight-1672726347.log](https://github.com/moonlight-stream/moonlight-qt/files/10338157/Moonlight-1672726347.log)

**Comment by ermac500** [comment]
I have managed to get it working on a windows laptop with moonlight-qt.
does android version also support this feature ?

**Comment by cgutman** [comment]
Yes Android does support this starting in v10.10.

**Comment by Cokkie203** [comment]
how? i tried for both android and windows (portable) and can't even get the option for it to appear

**Comment by cgutman** [comment]
There's no special option for it.

It will automatically detect the alternate ports via mDNS, or you can specifically add the port number to the IP address or hostname when you add a PC manually. For example, to pair with a PC with an IP address of 192.168.1.100 and Sunshine set to use a base port of 40000, you would type `192.168.1.100:40000` into the Add PC textbox.

**Comment by Cokkie203** [comment]
Ok I didn't know that thanks.
maybe that should be added in a wiki (either moonlight or sunshine)
