### ISSUE TITLE
provide performance stats in option

### ISSUE THREAD

**Issue by sceraser** [moonlight-stream/moonlight-qt#928]
**Is your feature request related to a problem? Please describe.**
without performance stat I cant estimate whats wrong with the streaming

**Describe the solution you'd like**
an option to show fps/latancy/resolution/... like in mobile version

**Comment by AlexKuai** [comment]
I also hope to provide this function

**Comment by Ronalaus** [comment]
You can view some stream stats by pressing Ctrl-Alt-Shift-S while you have a stream running.

**Comment by sceraser** [comment]
> You can view some stream stats by pressing Ctrl-Alt-Shift-S while you have a stream running.

Thkans , I think there should be an notice for this operation.
