### ISSUE TITLE
Please provide additional information on Steam Link setup

### ISSUE THREAD

**Issue by Maismaus** [moonlight-stream/moonlight-qt#932]
**Is your feature request related to a problem? Please describe.**
Limited documentation on Steam Link setup so I had some trouble getting it to work

**Describe the solution you'd like**
Additional documentation on Steam Link setup

**Describe alternatives you've considered**
I tried doing a pull request but I don't think it's possible for release documentation. So I'll do my suggestion here

**Additional context**
Please provide additional information:

To install on Steam Link hardware, extract the ZIP file to the root of a FAT32 flash drive, insert it into your Steam Link, then restart the Steam Link. Moonlight should appear next to your other PCs on the startup menu. To do a full restart, unplug and reinsert the power cable from the Steam Link. Moonlight can run alongside official Steam Link streaming and other Steam Link apps.

**Comment by TheXRMonk** [comment]
"To do a full restart, unplug and reinsert the power cable from the Steam Link."
Thanks, needed this!

**Comment by cgutman** [comment]
I added this to the latest release notes. Thanks!
