### ISSUE TITLE
Issues with Scaling 3840x2400 Sunshine Streams to 1280x800 (Steam Deck native res)

### ISSUE THREAD

**Issue by Nonary** [moonlight-stream/moonlight-qt#945]
**Describe the bug**
If users are using Sunshine and they've added 3840x2400 as a custom resolution, it does not scale properly if the resolution is configured for 1280x800 on Moonlight. I tested this using a steam deck and a MacBook as well as iOS, when the streaming resolution is set to 1280x800 there is a lot of aliasing. 

Using NVIDIA GameStream or changing the resolution to 2560x1600 on host will resolve the issue.
Additionally, if you configure the client to stream at 2560x1600 it will resolve the issue as well.
Basically, only the higher resolution and also having 1280x800 configured on Moonlight causes this issue.

**Steps to reproduce**
Stream using Sunshine.
Add a custom resolution of 3840x2400 to host PC.
Add a custom streaming resolution of 1280x800 to client Moonlight, unless device is already 12800x800 (aka steam deck)
Start a stream with Moonlight, then change host to 3840x2400.

**Screenshots**

<img width="1440" alt="Screen Shot 2023-01-29 at 10 26 51 AM" src="https://user-images.githubusercontent.com/27069224/215341115-777b5218-5cc8-4edc-b1bd-db3002b4d7ea.png">
<img width="1440" alt="Screen Shot 2023-01-29 at 10 25 51 AM" src="https://user-images.githubusercontent.com/27069224/215341133-daade9cc-d078-4f56-9d64-7c31b50aca59.png">
<img width="1440" alt="Screen Shot 2023-01-29 at 10 30 29 AM" src="https://user-images.githubusercontent.com/27069224/215341139-2a208964-c349-42a8-9f5b-a87287f491c4.png">

**Affected games**
Everything.

**Other Moonlight clients**
Confirmed same issue also happens on iOS, could not confirm android but suspect it is the same.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? No, other than custom resolution for MacBook test.

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - Moonlight Version: 4.3.1
 - GPU: 3080 TI

**Server PC details (please complete the following information)**
 - OS:Windows 11
 - Sunshine version: 0.17 as well as latest nightly, both same
 - Nvidia GPU driver: 528.24
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Additional context**
Wasn't sure to put this as a Sunshine issue or not, since the issue only happens when downscaling the image to 1280x800 and the resolution happens to be higher than 2560x1600. This would mostly impact steam deck users that are trying to supersample video games to the 4k equivalent of 16:10 (3840x2400).

**Comment by KyleKreutzer** [comment]
Am also seeing this issue trying to stream 4k from host to 720p client (steam deck).

**Comment by cgutman** [comment]
> Wasn't sure to put this as a Sunshine issue or not, since the issue only happens when downscaling the image to 1280x800 and the resolution happens to be higher than 2560x1600. This would mostly impact steam deck users that are trying to supersample video games to the 4k equivalent of 16:10 (3840x2400).

Yeah, this issue (or feature request) should be filed on Sunshine. Moonlight's scaling logic is correct, since it's working with GeForce Experience.

Sunshine currently scales preserving aspect ratio, which is different behavior than what GFE did. There should be an option added to select between the two modes.
