### ISSUE TITLE
Moonlight list only one machine instead of two

### ISSUE THREAD

**Issue by Xgamerz** [moonlight-stream/moonlight-qt#949]
**READ ME FIRST!**
If you're here because something basic is not working (like gamepad input, video, or similar), it's probably something specific to your setup, so make sure you've gone through the Troubleshooting Guide first: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

If you still have trouble with basic functionality after following the guide, join our Discord server where there are many other volunteers who can help (or direct you back here if it looks like a Moonlight bug after all). https://moonlight-stream.org/discord

**Describe the bug**
wanted to create 3 hosts on my workstation who contains 3 nvidia gpu's. 
3 virtual machines with 3 nvidia gpu's passthrough to each of them, i did 2 fresh installation, both are working fine with moonlight and they are both listed on guest machine, but when i clone a machine to add another host, moonlight identify source and cloned machine as same machine, and it list only one, when i shutdown source or cloned machine the other machine appear in moonlight 

**Steps to reproduce**

**Screenshots**

**Affected games**

**Other Moonlight clients**
- i m using windows 10 as host , and mac as client

**Moonlight settings (please complete the following information)**
Default

**Gamepad-related issues (please complete if problem is gamepad-related)**

**Client PC details (please complete the following information)**
 - OS: MacOS Big Sur 11.6.5
 - Moonlight Version: v4.3.1
 - GPU: AMD 5300M

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro 22H2 Build 19045.2486
 - GeForce Experience version: 3.27.0.112 (gtx 1050ti), 3.23.0.74 (gtx660), 1.3.05 (K4000)
 - Nvidia GPU driver: 517.48 (gtx 1050ti), 456.71 (gtx660), 474.14 (K4000)
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Moonlight Logs (please attach)**
[log.zip](https://github.com/moonlight-stream/moonlight-qt/files/10570291/log.zip)

**Additional context**

**Comment by cgutman** [comment]
This happens because GeForce Experience uses the `MachineGUID` registry value to distinguish machines. If you image them incorrectly (without sysprepping), they will all get the same `MachineGUID` which breaks various things (in addition to GFE). See https://www.reddit.com/r/sysadmin/comments/stvr5h/hklmsoftwaremicrosoftcryptography_machineguid/

The right fix to to sysprep them, but if you don't want to do that, you can use [Sunshine](https://github.com/LizardByte/Sunshine) as your host instead which doesn't use MachineGUID.
