### ISSUE TITLE
White Screen + No audio

### ISSUE THREAD

**Issue by 21synthetic12** [moonlight-stream/moonlight-qt#95]
Whenever I try to connect from another PC I get a white screen and no Audio. Just before this issue I had an issue with the error "Starting control stream establishment failed: Error -1" but this was fixed by fixing some port forwarding. This issue occurred right after the error was fixed.
 
Moonlight 0.5.1.0
Windows 10

[Moonlight-1538606762.log](https://github.com/moonlight-stream/moonlight-qt/files/2444305/Moonlight-1538606762.log)

**Comment by cgutman** [comment]
Does this error just happen over the internet or does it also happen on the same network as the host PC?

Audio and video are sent over UDP 47998 and UDP 48000. Please confirm your port forwarding and firewall rules for those ports.

If this is over the internet, please post a screenshot of your port forwarding configuration in your router settings.

**Comment by 21synthetic12** [comment]
Streaming works fine on my own network. Port forwarded twice because of a way my network is setup.
![firefox_2018-10-03_19-44-32](https://user-images.githubusercontent.com/43831813/46445410-ca44a500-c744-11e8-9749-c37e0b04b27a.png)
![firefox_2018-10-03_19-43-54](https://user-images.githubusercontent.com/43831813/46445411-ca44a500-c744-11e8-8c5c-73d6391fc2f6.png)
![firefox_2018-10-03_19-44-15](https://user-images.githubusercontent.com/43831813/46445412-cadd3b80-c744-11e8-98b9-c5a9028ddf3e.png)

**Comment by cgutman** [comment]
@21synthetic12 I can't really tell because the screenshots don't show the column headers on the first screenshot, but the second screenshot definitely shows that the internal port is wrong for rule 11. It should be 47998-48000 like the service port, or if ranges aren't accepted there, separate rules for each port with the service port and internal port being the same.

**Comment by 21synthetic12** [comment]
The issue was fixed by just leaving the internal box blank. Thanks.
