### ISSUE TITLE
Freezes on start of streaming when using the default fullscreen mode

### ISSUE THREAD

**Issue by ZhangTianrong** [moonlight-stream/moonlight-qt#951]
**Describe the bug**
Whenever I start streaming, there is sound but no image. The black screen freezes on any mouse clicks and then the program stops responding, similar to what's described in #240 where the log showed the same error of `Video decode unit queue overflow`. When I change from the default fullscreen mode to borderless window, the problem goes away.

**Steps to reproduce**
N/A I just started whatever program to stream and the problem always occurs.

**Screenshots**
![image](https://user-images.githubusercontent.com/20651728/217423664-dcf2bd35-6270-4b0d-a5e3-a9b7f6c69fd2.png)

**Affected games**
Anything

**Other Moonlight clients**
There isn't such a problem with iOS, android or Linux clients. The problem isn't happening to my other Windows devices either: when using the laptop as host and the host, a desktop, with dGPU of course, as a client, the streaming doesn't encounter such issues.

**Moonlight settings (please complete the following information)**
It's the default fullscreen mode causing the problem. I have tried changing other options while keeping the fullscreen mode, e.g. enforcing software decoder, enforcing H264 format, reducing bitrate, etc. However, none of them make any difference.

**Gamepad-related issues (please complete if problem is gamepad-related)**
No gamepad is involved.

**Client PC details (please complete the following information)**
 - OS: Windows 11 22H2
 - Moonlight Version: v4.3.1
 - GPU: Nvidia 3050 Ti Mobile

**Server PC details (please complete the following information)**
 - OS: Windows 11 22H2
 - GeForce Experience version: 3.27.0.111
 - Nvidia GPU driver: 528.24
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Moonlight Logs (please attach)**

+ A failed case in fullscreen mode: [Moonlight-1675827294.log](https://github.com/moonlight-stream/moonlight-qt/files/10681454/Moonlight-1675827294.log)
+ A successful case in borderless window mode: [Moonlight-1675827651.log](https://github.com/moonlight-stream/moonlight-qt/files/10681456/Moonlight-1675827651.log)

**Additional context**
The #240 I referred to earlier is dealing with Optimus, so more information on it might be helpful. The client is a Dell G15 5515 with AMD 5800H CPU and Nvidia 3050Ti GPU, running Windows 11 22H2. Optimus is on and there is no way to turn it off if the internal display is used. The responses in that issue also mentioned differences between the installed version and the portable version. I tried both the installed version and the portable version (managed by scoop) and there is not difference.

**Comment by jeffersonStargate** [comment]
I'm trying to use a similar (g15 5510) laptop + GPU, but on a i5-10500h CPU as a client and I'm experiencing the same. Have no issues on any other Moonlight client I use. 

This particular line of laptops doesn't have an optimus MUX switch, so it can't be disabled unless you use an external monitor, as you mentioned. Probably something to do with this, I'd imagine.

**Comment by cgutman** [comment]
When Moonlight freezes, open Task Manager, go to the Details tab, and right click on Moonlight.exe and click Create Dump File. You can compress the dmp file and upload it to a service like Google Drive or Dropbox then share a link to cameron@moonlight-stream.org.

**Comment by ZhangTianrong** [comment]
> 

Sorry for the delay. Here is the [link](https://www.dropbox.com/s/0mv293g1jbrwzp0/Moonlight.DMP?dl=0) to the dump file.

**Comment by cgutman** [comment]
Based on your dump file, the issue appears to be an incompatibility between the D3D9 renderer and your Alienware Sound Center software (which includes NahimicOSD.dll that loads into Moonlight).

I've changed the behavior to prefer D3D11 on multi-GPU systems, which should address the issue for you. Please try the portable build here: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/46493217/job/hi5xxhublo8n33d4/artifacts

**Comment by ZhangTianrong** [comment]
> Based on your dump file, the issue appears to be an incompatibility between the D3D9 renderer and your Alienware Sound Center software (which includes NahimicOSD.dll that loads into Moonlight).
> 
> I've changed the behavior to prefer D3D11 on multi-GPU systems, which should address the issue for you. Please try the portable build here: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/46493217/job/hi5xxhublo8n33d4/artifacts

I tried the new build but the client still freezes. Here is the new log and dump file:
+ log: [Moonlight-1678822484.log](https://github.com/moonlight-stream/moonlight-qt/files/10974548/Moonlight-1678822484.log)
+ dump: [Moonlight.DMP](https://drive.google.com/file/d/1BdhAZDNzibNhUghYPPZ2tspnolJ_Sspd/view?usp=share_link)

**Comment by ZhangTianrong** [comment]
> Based on your dump file, the issue appears to be an incompatibility between the D3D9 renderer and your Alienware Sound Center software (which includes NahimicOSD.dll that loads into Moonlight).
> 
> I've changed the behavior to prefer D3D11 on multi-GPU systems, which should address the issue for you. Please try the portable build here: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/46493217/job/hi5xxhublo8n33d4/artifacts

I tried the new build but the client still freezes. Here is the new log and dump file:
+ log: [Moonlight-1678822484.log](https://github.com/moonlight-stream/moonlight-qt/files/10983980/Moonlight-1678822484.log)
+ dump: [Moonlight.DMP](https://drive.google.com/file/d/1BdhAZDNzibNhUghYPPZ2tspnolJ_Sspd/view?usp=share_link)

**Comment by cgutman** [comment]
Ok, please try this additional fix: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/46529629/job/mwg5mv9yt7fp737d/artifacts

**Comment by ZhangTianrong** [comment]
> Ok, please try this additional fix: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/46529629/job/mwg5mv9yt7fp737d/artifacts

This build does solve the problem. Now I can stream in the fullscreen mode.
