### ISSUE TITLE
Moonlight Quit/Minimise Key Combination Freezes Stream and Doesn't Quit

### ISSUE THREAD

**Issue by xCISACx** [moonlight-stream/moonlight-qt#959]
**Describe the bug**
Sometimes, when inputting the quit or minimise key combinations in Moonlight, the stream will just freeze and not actually quit, forcing me to quit it manually through the taskbar or task manager.
Sometimes only one happens and sometimes both happen. It's very inconsistent.

**Steps to reproduce**
1 - Start stream.
2 - Input Quit/Minimise key combination.
3 - Stream freezes after minimising and going back to it and doesn't quit when using the quit combination.

**Affected games**
Desktop.

**Other Moonlight clients**
Only tested on Windows.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Yes
- If so, which settings have been changed? Unsupported FPS: 144, Capture system shortcuts: always
- Does the problem still occur after reverting settings back to default? Yes

**Client PC details (please complete the following information)**
 - OS: Windows 11 22H2
 - Moonlight Version: 4.3.1
 - GPU: RTX 3060 Mobile

**Server PC details (please complete the following information)**
 - OS: Windows 11 22H2
 - GeForce Experience version: 3.7.0.112
 - Nvidia GPU driver: 516.94
 - Antivirus and firewall software: Malwarebytes

**Moonlight Logs (please attach)**

**Additional context**
Using the latest version of Sunshine, not GFE.

Quit DMP: https://www.mediafire.com/file/1md77pl5k8a7qa3/Moonlight_Quit_Freeze.DMP/file

Minimise DMP: https://www.mediafire.com/file/w19stigkzwp918d/Moonlight+Minimise+Freeze.DMP/file

Quit Log: [Moonlight-1676582837.log](https://github.com/moonlight-stream/moonlight-qt/files/10761051/Moonlight-1676582837.log)

Minimise Log: [Moonlight-1676623610.log](https://github.com/moonlight-stream/moonlight-qt/files/10765248/Moonlight-1676623610.log)

**Comment by cgutman** [comment]
Hmm strange. In your Quit DMP file, I see the streaming session threads working as normal. It's waiting in the SDL event loop for new input events, and all the internal video/audio/control threads are all there just as I'd expect for an active session. It doesn't even look like it receive a request to quit (since the first thing that happens is that it immediately exits that event loop). Your logs show that it did start to quit, but the threads that are terminated before those logs messages are displayed are all running.

Can you try collecting another dump file of the quit case? Maybe you captured it before the log output occurred or something. It's quite strange.

**Comment by LanxingYizhi** [comment]
> 嗯奇怪。在您的退出 DMP 文件中，我看到流会话线程正常工作。它在 SDL 事件循环中等待新的输入事件，并且所有内部视频/音频/控制线程都在那里，就像我对活动会话的预期一样。它甚至看起来不像收到退出请求（因为发生的第一件事是它立即退出该事件循环）。您的日志显示它确实开始退出，但在显示这些日志消息之前终止的线程都在运行。
> 
> 您可以尝试收集退出案例的另一个转储文件吗？也许您在日志输出发生或其他事情之前捕获了它。这很奇怪。
I found that if vertical synchronization is enabled on a screen with a 360Hz refresh rate, it triggers this issue 100% (regardless of the FPS selected in the settings)

**Comment by xCISACx** [comment]
> Hmm strange. In your Quit DMP file, I see the streaming session threads working as normal. It's waiting in the SDL event loop for new input events, and all the internal video/audio/control threads are all there just as I'd expect for an active session. It doesn't even look like it receive a request to quit (since the first thing that happens is that it immediately exits that event loop). Your logs show that it did start to quit, but the threads that are terminated before those logs messages are displayed are all running.
> 
> Can you try collecting another dump file of the quit case? Maybe you captured it before the log output occurred or something. It's quite strange.

Here's a new DMP: https://www.mediafire.com/file/j3mvnm97ejpvz0v/Moonlight_Freeze_August.DMP/file

**Comment by xCISACx** [comment]
The latest nightly doesn't seem to freeze anymore for either of the key combinations so the problem might be fixed.

**Comment by cgutman** [comment]
Cool, thanks for confirming the fix worked.
