### ISSUE TITLE
Black lines 

### ISSUE THREAD

**Issue by Niglb** [moonlight-stream/moonlight-qt#96]
In the latest beta I get random think black lines across the screen - it's sporadic but does seam to be affected by resolution / frame rate (olddly higher res + lower frame rate = less back lines, which leads me to believe its tarring like v-sync issues).

**Comment by Niglb** [comment]
[Moonlight-1538778742.log](https://github.com/moonlight-stream/moonlight-qt/files/2452458/Moonlight-1538778742.log)
![img_181005153602488-1](https://user-images.githubusercontent.com/11722317/46563225-27f7ff00-c8b5-11e8-9345-eeb41ed892b5.jpg)
I had to take the screen shot with my phone as it moves quickly and local captures never caught the glitch. It occurs on all game titles, and even the desktop. I did update my video drivers on both the client and host machines.

**Comment by cgutman** [comment]
Ok, a couple things jump out at me in the logs.

It looks like your display is running at 4K 30 Hz but you're streaming at 1080p 60 FPS, so Moonlight is disabling V-sync to allow it to handle the large gap in the stream FPS vs the display refresh rate.

A couple things to try:
- Switch your client display settings to 1080p 60 Hz in the Intel Graphics Control Panel
- Switch Moonlight to 1080p 30 FPS and see if the issue still occurs

**Comment by Niglb** [comment]
Great you are right getting the displays more in sync cut out this issue - thank you very much!
