### ISSUE TITLE
[Feature request] Gyroscope/Touchpad transfer to Sunshine host

### ISSUE THREAD

**Issue by ld892012** [moonlight-stream/moonlight-qt#960]
**Is your feature request related to a problem? Please describe.**
Some games needs gyroscope or touchpad to work properly like emulated games of some recent games but only axes and buttons is sent to host by Moonlight.

**Describe the solution you'd like**
Sunshine gives possibility to emulate DS4 controller instead of X360 but no motion/touchscreen data is transferred.

**Describe alternatives you've considered**
At this moment, there is no way to send motion data from client to host except for Dolphin or Cemu by create DSU server on client but it not work on all platforms and don't work outside of LAN.

**Additional context**
I will send the same issue to Sunshine, the combo Moonlight/Sunshine is already a great alternative (selectable screen, multi client, custom resolution/fps) and it can be even more greater with this kind of features 👍

**Comment by vcntt** [comment]
Please I need this

**Comment by Rintje** [comment]
> Please I need this

Me too

**Comment by shazibjeahngir** [comment]
must have for switch and wii games!

**Comment by wz9997438** [comment]
moonlight is great. Would be greater if added

**Comment by rzumbado** [comment]
PLEASE!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by lucascanero** [comment]
Please add this feature

**Comment by cgutman** [comment]
This is supported now with https://github.com/moonlight-stream/moonlight-qt/commit/9af58af5e4aa536083ad62997135c1f9c03430ec but the Sunshine side isn't written yet.

**Comment by ld892012** [comment]
> This is supported now with [9af58af](https://github.com/moonlight-stream/moonlight-qt/commit/9af58af5e4aa536083ad62997135c1f9c03430ec) but the Sunshine side isn't written yet.

Cool ! You are the best ! 🥇

**Comment by cgutman** [comment]
Support for the full set of DS4 features is available for testing now. Please give it a try and let me know how it performs. You'll need to use dev builds of both Moonlight and Sunshine listed below.

Moonlight Windows: https://ci.appveyor.com/api/buildjobs/lm0v4h2nc8ehy5xe/artifacts/MoonlightPortable-x64-r2079.zip
Moonlight macOS: https://ci.appveyor.com/api/buildjobs/ha66wtquq7u4qkf1/artifacts/Moonlight-r2079.dmg
Sunshine Windows (need to be signed in on GitHub to download): https://github.com/LizardByte/Sunshine/suites/14159253569/artifacts/793377489

**Comment by ld892012** [comment]
Thanks !
Will the Android app can support the device's gyroscope or just the gamepad's ?

**Comment by ld892012** [comment]
I've just tested your nightlies and it's work fine but like [danaigus](https://github.com/LizardByte/Sunshine/discussions/1200#discussioncomment-6395016) i have a problem with Dualsence's triggers (they just do full or nothing)
I have tested with a wired Dualsence and a wired Xbox Series gamepad with DS4 and Xbox emulation, in all cases Dualsence's triggers provide digital output but no analog

**Comment by vcntt** [comment]
Is this a Sony DS4 controller specific implementation or would this also work with Nintendo Switch Pro Controllers?

**Comment by ld892012** [comment]
> Is this a Sony DS4 controller specific implementation or would this also work with Nintendo Switch Pro Controllers?

I've just test it, NS Pro controller's Accel/Gyro is passed and Capture button work as DS4's Touchpad button

**Comment by cgutman** [comment]
The trigger issue was a bug in the version of SDL included in that build of Moonlight Qt. It is fixed in the builds linked here.

Here are new builds of Moonlight and Sunshine for testing:
Moonlight Windows: https://ci.appveyor.com/api/buildjobs/86obf0nwmskllw7l/artifacts/MoonlightPortable-x64-r2084.zip
Moonlight macOS: https://ci.appveyor.com/api/buildjobs/f4q4opwayiypl4wx/artifacts/Moonlight-r2084.dmg
Sunshine Windows (need to be signed in on GitHub to download): https://github.com/LizardByte/Sunshine/suites/14167610325/artifacts/794048974

**Comment by azuwis** [comment]
What is the current state of Linux support?

I've look at the Sunshine nightly branch, and found Sunshine Linux does not support the feature yet.

Does Moonlight Linux nightly -> Sunshine Windows test build works?

**Comment by cgutman** [comment]
> I've look at the Sunshine nightly branch, and found Sunshine Linux does not support the feature yet.

The feature isn't in nightly yet either for Linux or Windows. It's still in PR. https://github.com/LizardByte/Sunshine/pull/1435

> What is the current state of Linux support?

The PR above includes Windows support and provides stubs for Linux. Another developer has said he will work on the Linux implementation.

> Does Moonlight Linux nightly -> Sunshine Windows test build works?

Yes, that should work if you use the Snap on the edge channel or the AppImage from here https://ci.appveyor.com/api/buildjobs/mtblh3h7dlocn9v2/artifacts/Moonlight-r2084-x86_64.AppImage

One thing to be aware of is that Moonlight uses SDL for controller support and SDL on Linux doesn't have universal support for these extended features (LED control, motion sensors, battery reporting, touchpad input, etc) in the generic Linux gamepad implementation. Many common gamepads (Xbox 360, Xbox One, PS3/4/5, Nintendo Switch) have special HIDAPI driver implementations in SDL that do support those features, but the sandboxes used by Flatpak and Snap may prevent the direct access that HIDAPI requires to work. It's not something I've tested yet.

**Comment by CipherLab** [comment]
If this worked on the Atmoshphere (Nintendo Switch) Moonlight client I would be soooo happy.

**Comment by ld892012** [comment]
> If this worked on the Atmoshphere (Nintendo Switch) Moonlight client I would be soooo happy.

Maybe you can ask at [Moonlight-Switch](https://github.com/XITRIX/Moonlight-Switch) in his related [issue](https://github.com/XITRIX/Moonlight-Switch/issues/87), maybe he can add this feature for his next releases ^^

**Comment by ld892012** [comment]
Now this work fine even with Dualsence's triggers, thank you ! 👍

**Comment by cgutman** [comment]
Sunshine support is merged into the nightly builds and support is present in this client, so going to go ahead and close this as completed. Until new versions of Sunshine and Moonlight are released, you can use the nightly builds for this feature.

**Comment by AE-GM** [comment]
my Bluetooth controller with motion controls doesn't work, but the motion controls works when I connect directly to pc, any fix?

**Comment by kidoman** [comment]
> > Is this a Sony DS4 controller specific implementation or would this also work with Nintendo Switch Pro Controllers?
> 
> I've just test it, NS Pro controller's Accel/Gyro is passed and Capture button work as DS4's Touchpad button

I was trying this on a Fire Stick 4K Max (Gen 1), and the Nintendo Switch Pro Control Gyro does not seem to get passed. What could I be doing wrong?
