### ISSUE TITLE
Windows Client:  Fullscreen Mode Takes 1.5 Minutes to Initiate, Loses Connection on Samsung TV

### ISSUE THREAD

**Issue by Skates1616** [moonlight-stream/moonlight-qt#962]
**Describe the bug**
On Windows 11, using Moonlight-QT with a Intel Xe GPU, I am running into a weird issue where the connection between the client and the host (GFE) starts, the Samsung TV will then disconnect for about 1.5 minutes, and then the TV will reconnect with the stream appearing as if their were no issues.  This only happens with Full Screen Mode, if I change the settings to Windowless Border, the connection initiates immediately.

**Steps to reproduce**
No special steps in this instance.

**Screenshots**
None.

**Affected games**
Desktop Streaming

**Other Moonlight clients**
This issue is limited to the Windows client on this PC.  Using iOS version of Moonlight, it displays the hosts desktop immediately.

**Moonlight settings (please complete the following information)**
Resolution set to 4K, Frame Rate 60FPS.

**Gamepad-related issues (please complete if problem is gamepad-related)**
N/A

**Client PC details (please complete the following information)**
 - OS: Windows 11 22H2 Build 22621.1265
 - Moonlight Version: 4.3.1
 - GPU: Intel Iris Xe

**Server PC details (please complete the following information)**
 - OS: Windows 11 22H2 Build 22621.1265
 - GeForce Experience version: 3.27.0.112
 - Nvidia GPU driver: 528.49
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Moonlight Logs (please attach)**
[Moonlight-1677165076 - Fullscreen Mode.log](https://github.com/moonlight-stream/moonlight-qt/files/10816304/Moonlight-1677165076.-.Fullscreen.Mode.log)
[Moonlight-1677166144 - Borderless Window Mode.log](https://github.com/moonlight-stream/moonlight-qt/files/10816305/Moonlight-1677166144.-.Borderless.Window.Mode.log)

**Additional context*

**Comment by cgutman** [comment]
It looks like it's trying to put your TV into 4K 120 Hz mode, but the TV disconnects (since I can see the HDMI audio device disappear too). If you try to set your TV to 4K 120 Hz in Windows, does the same issue happen?

**Comment by Skates1616** [comment]
I actually figured it out, needed to swap ports on the TV.  I moved the NUC to the port supporting 120hz on the TV.
