### ISSUE TITLE
Invisible mouse 

### ISSUE THREAD

**Issue by Aruscha** [moonlight-stream/moonlight-qt#965]
Hello,

I have installed sunshine / moonlight.
However, I have the problem that I can not see my mouse cursor.

What is the reason for this?

Unraid as server 
Fedora as VM with sunshine

**Comment by Bobbar** [comment]
https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#missing-mouse-cursor

**Comment by Aruscha** [comment]
> https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#missing-mouse-cursor

And where can I find the setting under Fedora?

**Comment by cgutman** [comment]
Yeah, that's correct. You should file a bug report on Sunshine for this.
