### ISSUE TITLE
Windows Client->GFE Host: Emulators crashing with 360 controller reconnects/new connections. 

### ISSUE THREAD

**Issue by Skates1616** [moonlight-stream/moonlight-qt#969]
**Describe the bug**
On Windows 11, using Moonlight-QT with a Intel Xe GPU as my client and GFE on my host, emulators (Dolphin, Ryujinx, Yuzu, specifically) are crashing when a 360 controller disconnects and reconnects along with new controllers being initiated.  The windows in all 3 emulators freeze up.

When running emulators locally on the client, they do not hang with controller disconencts/additions.

**Steps to reproduce**
While in any of the 3 emulator apps, disconnect a 360 controller and reconnect it.  Or connect new 360 controllers on the client, the emulators will lock up on the host.

**Screenshots**
N/A

**Affected games**
The issue affects three popular emulators that I have tested this on (Dolphin, Ryujinx, Yuzu) and possibly more.

**Other Moonlight clients**
N/A

**Moonlight settings (please complete the following information)**
N/A

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
  No
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
  Google Chrome does not crash with controller disconnects/reconnects, all controllers connected were accessible on the site.

**Client PC details (please complete the following information)**

- OS: Windows 11 22H2 Build 22621.1391
- Moonlight Version: 4.3.1
- GPU: Intel Iris Xe

**Server PC details (please complete the following information)**

- OS: Windows 11 22H2 Build 22621.1391
- GeForce Experience version: 3.27.0.112
- Nvidia GPU driver: 531.18
- Antivirus and firewall software: Windows Defender and Windows Firewall

**Moonlight Logs (please attach)**
[Moonlight-1678847312.log](https://github.com/moonlight-stream/moonlight-qt/files/10975676/Moonlight-1678847312.log)

**Additional context**
Anything else you think may be relevant to the issue
No

**Comment by cgutman** [comment]
This isn't a client-side bug. It would need to be fixed by either Nvidia changing their controller emulation, or more likely, there's a bug in SDL2 (used in all 3 emulators) which is causing it to mishandle Nvidia's emulated controllers. 

Since Nvidia has discontinued GameStream, they won't be fixing it, so you will need to migrate to [Sunshine](https://github.com/LizardByte/Sunshine). That will likely eliminate the issue, since it uses a different driver for controller emulation than GFE does.
