### ISSUE TITLE
Connecting to an Android tablet with a cable (possibly OTG)

### ISSUE THREAD

**Issue by Relobum** [moonlight-stream/moonlight-qt#972]
I'm very sorry if I'm posting in the wrong thread. I just didn't find the right one. Hope I can be helped here.

The thing is, I would like to clarify whether there is a function to broadcast using a cable?

Previously always used Wi-Fi. And, although my devices are very good, and data was transmitted and received via Wi-Fi 6E, I inevitably encountered stuttering in the image and sound, scattering of the picture even at a low bitrate. I've already tried everything possible.

Interested in whether there is a function of broadcasting using a cable. If so, what cable would be needed and most preferred? If not, will this feature be implemented in the future?

I'm looking forward to your reply. I hope this thread will also be useful to the community, in particular to beginners who are just getting acquainted with this wonderful application.

**Comment by Relobum** [comment]
P.S. My devices:

- Windows 11 laptop with a full set of high-speed ports (transmitter).

- Samsung Galaxy Tab S7 Plus Lte tablet on Android (receiver).

**Comment by cgutman** [comment]
If your table supports USB tethering (and assuming it can handle the large amount of traffic over USB tethering), it should work.
