### ISSUE TITLE
Moonlight disconnects in several minutes in ios

### ISSUE THREAD

**Issue by zhuhaichao518** [moonlight-stream/moonlight-qt#986]
Hi, I am streaming a remote PC using zerotier(both moolight and zerotier are the latest version) under the same network in PC and iphone. It works perfectly on PC and the network is stable, but when I use ios/iphone, it disconnects randomly (often in 5 minutes) and tells me Connection Terminated. Any ideas why it happened? Is there any difference on PC and IOS?

Here is the log:
`#6(I)[2023-04-0704:49:24,533]=12:49:24={24732}<VideoStreamer>    Obtained SPS/PPS header for stream:0 frame:3783 length 41
#7(I)[2023-04-07 04:49:28,764]=12:49:28={24732}<QosManagerTxNati> Frame Number: 3911, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.86
#8(I)[2023-04-07 04:49:33,796]=12:49:33={24732}<QosManagerTxNati> Frame Number: 4062, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.04
#9(I)[2023-04-07 04:49:38,796]=12:49:38={24732}<QosManagerTxNati> Frame Number: 4212, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.22
#0(I)[2023-04-07 04:49:43,829]=12:49:43={24732}<QosManagerTxNati> Frame Number: 4363, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.93
#1(I)[2023-04-07 04:49:48,833]=12:49:48={24732}<QosManagerTxNati> Frame Number: 4513, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.12
#2(I)[2023-04-07 04:49:53,866]=12:49:53={24732}<QosManagerTxNati> Frame Number: 4664, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.07
#3(I)[2023-04-07 04:49:58,897]=12:49:58={24732}<QosManagerTxNati> Frame Number: 4815, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.23
#4(I)[2023-04-07 04:50:03,931]=12:50:03={24732}<QosManagerTxNati> Frame Number: 4966, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.03
#5(I)[2023-04-07 04:50:08,931]=12:50:08={24732}<QosManagerTxNati> Frame Number: 5116, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.17
#6(I)[2023-04-07 04:50:13,961]=12:50:13={24732}<QosManagerTxNati> Frame Number: 5267, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.70
#7(I)[2023-04-07 04:50:18,994]=12:50:18={24732}<QosManagerTxNati> Frame Number: 5418, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.68
#8(I)[2023-04-07 04:50:19,081]=12:50:19={6884}<AudioSendThread>  Total Energy for audio sample is 0.000000
#9(I)[2023-04-07 04:50:23,996]=12:50:23={24732}<QosManagerTxNati> Frame Number: 5568, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.99
#0(I)[2023-04-07 04:50:28,998]=12:50:28={24732}<QosManagerTxNati> Frame Number: 5718, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.98
#1(I)[2023-04-07 04:50:34,028]=12:50:34={24732}<QosManagerTxNati> Frame Number: 5869, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.09
#2(I)[2023-04-07 04:50:39,031]=12:50:39={24732}<QosManagerTxNati> Frame Number: 6019, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.97
#3(I)[2023-04-07 04:50:40,297]=12:50:40={13708}<QosManagerTxNati> [0] Client requested an IDR at frame 6056
#4(I)[2023-04-07 04:50:40,308]=12:50:40={15904}<EnetProtocol>     Disconnect received from remote peer
#5(I)[2023-04-07 04:50:40,308]=12:50:40={15904}<EnetProtocol>     Handling disconnect.
#6(I)[2023-04-07 04:50:40,308]=12:50:40={15904}<EnetProtocol>     Remote peer state acknowledging disconnect
#7(I)[2023-04-07 04:50:40,308]=12:50:40={15904}<EnetProtocol>     Remote peer sent disconnect
#8(I)[2023-04-07 04:50:40,308]=12:50:40={15904}<EnetSocket>       Received ENET_EVENT_TYPE_DISCONNECT, peer disconnect complete for 0000019598524620, data 0
#9(I)[2023-04-07 04:50:40,308]=12:50:40={15904}<ClientControlRel> ClientControlReliableUdp received ErrorNotification from dataChannelController
#0(D)[2023-04-07 04:50:40,323]=12:50:40={20488}<NvEnc10VideoEnco> Forcing IDR frame at stream:0 frame:6057.
#1(M)[2023-04-07 04:50:40,328]=12:50:40={24732}<VideoStreamer>    Stream:0 Frame 6057 is an I-Frame.
#2(I)[2023-04-07 04:50:40,328]=12:50:40={24732}<VideoStreamer>    Obtained SPS/PPS header for stream:0 frame:6057 length 41
#3(W)[2023-04-07 04:50:40,798]=12:50:40={13708}<ClientControl>    waitForClientCommand: No packets seen on control channel from 501 ms, time-out: 500 ms, last command 302 received, dispatch queue size is 0.
#4(E)[2023-04-07 04:50:40,798]=12:50:40={13708}<ClientControlRel> Failed to read data from dataChannelController with result 8000001A
#5(E)[2023-04-07 04:50:40,801]=12:50:40={13708}<ClientControl>    Failed to read data from the control channel. Error: 80000023
#6(I)[2023-04-07 04:50:40,803]=12:50:40={18328}<StreamSdkEvents>  Invoking diagnosticsEventRaised EnetEvent
#7(D)[2023-04-07 04:50:40,803]=12:50:40={13708}<StopEvent>        Setting event 'Session'. ClientControl:  (0x80040002 NVST_NETERR_CONNLOST)
#8(I)[2023-04-07 04:50:40,803]=12:50:40={6136}<NvscStreamingSes> Stop event received, tearing down.
#9(I)[2023-04-07 04:50:40,803]=12:50:40={6136}<NvscStreamingSes> Starting teardown
#0(I)[2023-04-07 04:50:40,803]=12:50:40={6136}<NvscStreamingSes> Quit requested, waiting on child threads to quit
#1(I)[2023-04-07 04:50:40,803]=12:50:40={6136}<StopEvent>        Termination infos:
#2(I)[2023-04-07 04:50:40,803]=12:50:40={6136}<StopEvent>        - Source 'ClientControl', reason '', code 0x80040002 NVST_NETERR_CONNLOST
#3(I)[2023-04-07 04:50:40,803]=12:50:40={6136}<NvscStreamingSes> Termination reason to report: NVST_NETERR_CONNLOST
#4(I)[2023-04-07 04:50:40,803]=12:50:40={18328}<NvStreamServerCo> DiagnosticEvent: Reported UnifiedErrorCode 80470023 for SessionTerminationReason 100
#5(D)[2023-04-07 04:50:40,803]=12:50:40={6136}<VideoStreamerThr> Destroying video streamer thread.
#6(D)[2023-04-07 04:50:40,803]=12:50:40={13708}<ClientControl>    Last received command: 302
#7(D)[2023-04-07 04:50:40,803]=12:50:40={13708}<NvThread>         Completed thread function for native thread: ClientControl (thread id: 000000000000358C)
#8(D)[2023-04-07 04:50:40,803]=12:50:40={25072}<NvThread>         About to destroy native thread: VideoStreamerThread (thread id: 000000000000609C)
#9(I)[2023-04-07 04:50:40,803]=12:50:40={18328}<StreamSdkEvents>  Invoking diagnosticsEventRaised TerminationReason
#0(I)[2023-04-07 04:50:40,803]=12:50:40={18328}<NvStreamServerCo> DiagnosticEvent: Reported UnifiedErrorCode 80438107 for SessionTerminationReason 8107
#1(I)[2023-04-07 04:50:40,803]=12:50:40={10828}<Server>           Server has been asked to end the current streaming session.
#2(I)[2023-04-07 04:50:40,803]=12:50:40={10828}<Server>           Server is now in state: EndingSession
#3(D)[2023-04-07 04:50:40,803]=12:50:40={10828}<StopEvent>        Append to 'Session'. ClientControl:  (0x80040002 NVST_NETERR_CONNLOST)
#4(I)[2023-04-07 04:50:40,803]=12:50:40={1424}<VideoSenderThrea> Video frame sending ended normally
#5(D)[2023-04-07 04:50:40,803]=12:50:40={1424}<StopEvent>        Append to 'Session'. VideoSenderThread: Thread ended (0x80030000 NVST_DISCONN_INTENDED)
#6(I)[2023-04-07 04:50:40,803]=12:50:40={10828}<RtspHandshake>    Terminating RTSP session
`

**Comment by saxlamen** [comment]
I have the exact same issue.
No problem streaming moonlight with LAN. But keep disconnecting streaming through zerotier remotely.
Have you found the answer yet?

**Comment by zhuhaichao518** [comment]
> I have the exact same issue. No problem streaming moonlight with LAN. But keep disconnecting streaming through zerotier remotely. Have you found the answer yet?

@saxlamen I guess NVDIA terminates streaming when controller thread losts connection and it is easy to happen when remoting. I don't know why it disconnects.
I guess there is a workaround by host a proxy and forward the controller message on the host PC and require the server not to disconnect.

**Comment by saxlamen** [comment]
Issue solved for me yesterday after using Tailscale replacing zerotier. Give it a try!iPhoneから送信2023/4/24 午前9:42、zhuhaichao518 ***@***.***>のメール:﻿

I have the exact same issue. No problem streaming moonlight with LAN. But keep disconnecting streaming through zerotier remotely. Have you found the answer yet?

@saxlamen I guess NVDIA terminates streaming when controller thread losts connection and it is easy to happen when remoting. I don't know why it disconnects.
I guess there is a workaround by host a proxy and forward the controller message on the host PC and require the server not to disconnect.

**Comment by reloxx13** [comment]
Fix your post and use code or quote to not create useless link to other issues with `#8` in logs.

**Comment by zhuhaichao518** [comment]
> Hi, I am streaming a remote PC using zerotier(both moolight and zerotier are the latest version) under the same network in PC and iphone. It works perfectly on PC and the network is stable, but when I use ios/iphone, it disconnects randomly (often in 5 minutes) and tells me Connection Terminated. Any ideas why it happened? Is there any difference on PC and IOS?
> 
> Here is the log: ’’’#6(I)[2023-04-07 04:49:24,533]=12:49:24={24732} Obtained SPS/PPS header for stream:0 frame:3783 length 41 #7(I)[2023-04-07 04:49:28,764]=12:49:28={24732} Frame Number: 3911, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.86 #8(I)[2023-04-07 04:49:33,796]=12:49:33={24732} Frame Number: 4062, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.04 #9(I)[2023-04-07 04:49:38,796]=12:49:38={24732} Frame Number: 4212, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.22 #0(I)[2023-04-07 04:49:43,829]=12:49:43={24732} Frame Number: 4363, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.93 #1(I)[2023-04-07 04:49:48,833]=12:49:48={24732} Frame Number: 4513, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.12 #2(I)[2023-04-07 04:49:53,866]=12:49:53={24732} Frame Number: 4664, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.07 #3(I)[2023-04-07 04:49:58,897]=12:49:58={24732} Frame Number: 4815, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.23 #4(I)[2023-04-07 04:50:03,931]=12:50:03={24732} Frame Number: 4966, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.03 #5(I)[2023-04-07 04:50:08,931]=12:50:08={24732} Frame Number: 5116, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.17 #6(I)[2023-04-07 04:50:13,961]=12:50:13={24732} Frame Number: 5267, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.70 #7(I)[2023-04-07 04:50:18,994]=12:50:18={24732} Frame Number: 5418, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.68 #8(I)[2023-04-07 04:50:19,081]=12:50:19={6884} Total Energy for audio sample is 0.000000 #9(I)[2023-04-07 04:50:23,996]=12:50:23={24732} Frame Number: 5568, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.99 #0(I)[2023-04-07 04:50:28,998]=12:50:28={24732} Frame Number: 5718, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.98 #1(I)[2023-04-07 04:50:34,028]=12:50:34={24732} Frame Number: 5869, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 60.09 #2(I)[2023-04-07 04:50:39,031]=12:50:39={24732} Frame Number: 6019, Client Q-score: 100, RTD: 0 ms, BW score: 100, Loss score: 100, Latency score: 100, Avg Game FPS: 59.97 #3(I)[2023-04-07 04:50:40,297]=12:50:40={13708} [0] Client requested an IDR at frame 6056 #4(I)[2023-04-07 04:50:40,308]=12:50:40={15904} Disconnect received from remote peer #5(I)[2023-04-07 04:50:40,308]=12:50:40={15904} Handling disconnect. #6(I)[2023-04-07 04:50:40,308]=12:50:40={15904} Remote peer state acknowledging disconnect #7(I)[2023-04-07 04:50:40,308]=12:50:40={15904} Remote peer sent disconnect #8(I)[2023-04-07 04:50:40,308]=12:50:40={15904} Received ENET_EVENT_TYPE_DISCONNECT, peer disconnect complete for 0000019598524620, data 0 #9(I)[2023-04-07 04:50:40,308]=12:50:40={15904} ClientControlReliableUdp received ErrorNotification from dataChannelController #0(D)[2023-04-07 04:50:40,323]=12:50:40={20488} Forcing IDR frame at stream:0 frame:6057. #1(M)[2023-04-07 04:50:40,328]=12:50:40={24732} Stream:0 Frame 6057 is an I-Frame. #2(I)[2023-04-07 04:50:40,328]=12:50:40={24732} Obtained SPS/PPS header for stream:0 frame:6057 length 41 #3(W)[2023-04-07 04:50:40,798]=12:50:40={13708} waitForClientCommand: No packets seen on control channel from 501 ms, time-out: 500 ms, last command 302 received, dispatch queue size is 0. #4(E)[2023-04-07 04:50:40,798]=12:50:40={13708} Failed to read data from dataChannelController with result 8000001A #5(E)[2023-04-07 04:50:40,801]=12:50:40={13708} Failed to read data from the control channel. Error: 80000023 #6(I)[2023-04-07 04:50:40,803]=12:50:40={18328} Invoking diagnosticsEventRaised EnetEvent #7(D)[2023-04-07 04:50:40,803]=12:50:40={13708} Setting event 'Session'. ClientControl: (0x80040002 NVST_NETERR_CONNLOST) #8(I)[2023-04-07 04:50:40,803]=12:50:40={6136} Stop event received, tearing down. #9(I)[2023-04-07 04:50:40,803]=12:50:40={6136} Starting teardown #0(I)[2023-04-07 04:50:40,803]=12:50:40={6136} Quit requested, waiting on child threads to quit #1(I)[2023-04-07 04:50:40,803]=12:50:40={6136} Termination infos: #2(I)[2023-04-07 04:50:40,803]=12:50:40={6136} - Source 'ClientControl', reason '', code 0x80040002 NVST_NETERR_CONNLOST #3(I)[2023-04-07 04:50:40,803]=12:50:40={6136} Termination reason to report: NVST_NETERR_CONNLOST #4(I)[2023-04-07 04:50:40,803]=12:50:40={18328} DiagnosticEvent: Reported UnifiedErrorCode 80470023 for SessionTerminationReason 100 #5(D)[2023-04-07 04:50:40,803]=12:50:40={6136} Destroying video streamer thread. #6(D)[2023-04-07 04:50:40,803]=12:50:40={13708} Last received command: 302 #7(D)[2023-04-07 04:50:40,803]=12:50:40={13708} Completed thread function for native thread: ClientControl (thread id: 000000000000358C) #8(D)[2023-04-07 04:50:40,803]=12:50:40={25072} About to destroy native thread: VideoStreamerThread (thread id: 000000000000609C) #9(I)[2023-04-07 04:50:40,803]=12:50:40={18328} Invoking diagnosticsEventRaised TerminationReason #0(I)[2023-04-07 04:50:40,803]=12:50:40={18328} DiagnosticEvent: Reported UnifiedErrorCode 80438107 for SessionTerminationReason 8107 #1(I)[2023-04-07 04:50:40,803]=12:50:40={10828} Server has been asked to end the current streaming session. #2(I)[2023-04-07 04:50:40,803]=12:50:40={10828} Server is now in state: EndingSession #3(D)[2023-04-07 04:50:40,803]=12:50:40={10828} Append to 'Session'. ClientControl: (0x80040002 NVST_NETERR_CONNLOST) #4(I)[2023-04-07 04:50:40,803]=12:50:40={1424} Video frame sending ended normally #5(D)[2023-04-07 04:50:40,803]=12:50:40={1424} Append to 'Session'. VideoSenderThread: Thread ended (0x80030000 NVST_DISCONN_INTENDED) #6(I)[2023-04-07 04:50:40,803]=12:50:40={10828} Terminating RTSP session ’’’



> Fix your post and use code or quote to not create useless links to many other issues with `#8` in logs.

My apologise. Updated the post.

**Comment by zhuhaichao518** [comment]
Closing this issue because tailscale works.
