### ISSUE TITLE
Client window settings are not all viewable if display scaling is set at 150% in windows 10

### ISSUE THREAD

**Issue by bigmacxman** [moonlight-stream/moonlight-qt#99]

**Comment by cgutman** [comment]
Oddly enough, I also noticed this on my high DPI tablet. Are you just not able to see them when the combo box is collapsed or can you also not see them when it's expanded either?

**Comment by bigmacxman** [comment]
Even if the screen is maximized, still can’t quite make out the bottom settings.  It is really close to fitting.

Sent from my iPhone

On Oct 7, 2018, at 8:14 PM, Cameron Gutman <notifications@github.com<mailto:notifications@github.com>> wrote:


Oddly enough, I also noticed this on my high DPI tablet. Are you just not able to see them when the combo box is collapsed or can you also not see them when it's expanded either?

**Comment by cgutman** [comment]
Fix will be released in the next version
