### ISSUE TITLE
custom ffmpeg command line addon.

### ISSUE THREAD

**Issue by Originalimoc** [moonlight-stream/moonlight-qt#993]
**Is your feature request related to a problem? Please describe.**
Yes. Latest driver update(using EndeavourOS) breaks moonlight's call to VAAPI(both flatpak and AppImage, src build can call latest VAAPI). And this(plus mpv, plus chromium(also flatpak ver)) still works but moonlight doesn't:
```
ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i caminandes-2-gran-dillama-x65-aac.mp4 -vf 'format=nv12|vaapi,hwupload' -f null -
```
this get 700FPS, while
```
ffmpeg -c:v hevc -i caminandes-2-gran-dillama-x65-aac.mp4 -f null -
```
get 300FPS.

**Describe the solution you'd like**
environment variable or a config file to pass these command for moonlight to use.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Originalimoc** [comment]
surprisingly x86_64 is quite fast at HEVC software decoding, 1440p60 + all the compositing only need about one 2.4GHz Intel Core™ core.

**Comment by Originalimoc** [comment]
mpv:
```
[vd] Container reported FPS: 24.000000
[vd] Codec list:
[vd]     hevc - HEVC (High Efficiency Video Coding)
[vd]     hevc_qsv (hevc) - HEVC video (Intel Quick Sync Video acceleration)
[vd]     hevc_v4l2m2m (hevc) - V4L2 mem2mem HEVC decoder wrapper
[vd]     hevc_cuvid (hevc) - Nvidia CUVID HEVC decoder
[vd] Opening decoder hevc
[vd] Looking at hwdec hevc-vaapi...
[vo/gpu] Loading hwdec drivers for format: 'vaapi'
[vo/gpu] Loading hwdec driver 'vaapi'
[vo/gpu/vaapi] using EGL dmabuf interop
[vo/gpu/vaapi] Trying to open a x11 VA display...
[vo/gpu/vaapi/vaapi] Initialized VAAPI: version 1.18
[vo/gpu/vaapi] Going to probe surface formats (may log bogus errors)...
[vo/gpu/vaapi] Done probing surface formats.
[vd] Trying hardware decoding via hevc-vaapi.
[vd] Selected codec: hevc (HEVC (High Efficiency Video Coding))
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     aac - AAC (Advanced Audio Coding)
[ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[ad] Opening decoder aac
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: aac (AAC (Advanced Audio Coding))
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...
[af] [in] 48000Hz stereo 2ch floatp
[af] [userspeed] 48000Hz stereo 2ch floatp
[af] [userspeed] (disabled)
[af] [convert] 48000Hz stereo 2ch floatp
[vd] Pixel formats supported by decoder: vaapi vdpau cuda yuv420p
[vd] Codec profile: Main (0x1)
[vd] Requesting pixfmt 'vaapi' from decoder.
[vd] Using hardware decoding (vaapi).
```

**Comment by ayhc** [comment]
This issue also occurs with the Flatpak version on Fedora Kinoite 38, running on a Framework Laptop 13 (Intel 12th Gen, onboard graphics).

**Comment by ranger149** [comment]
Could this issue possibly be related to an issue with the runtime? MPV and others that seem to be working use: org.freedesktop.Platform/x86_64/22.08

however this one and Chiaka which both aren't working use:
org.kde.Platform/x86-64/5.15-22.08

**Comment by Originalimoc** [comment]
@ranger149 both flatpak and AppImage use the old library. build them from the source can call the latest VAAPI system provided.

**Comment by cgutman** [comment]
The root cause is a mismatch between the libva version in the AppImage or Flatpak runtime and the version on the system (or Flatpak extension, in that case). Libva must be at least as new as the drivers built for it in order to properly load them (a driver built against libva 2.18 works with libva 2.19 but not libva 2.17).

The libva version in the KDE runtime was updated by the runtime maintainers and the AppImage in the nightly builds is now on libva 2.19 which is the latest as of this writing, so I think this issue is fully resolved.
